.circleci/config.yml
This PR brings us to a point in between the old days approach (everything dependency is always dynamically resolved in CI to their latest version) to the new days approach (everything is locked by gem lock files checked into the repository).
This new approach allows for changes to Gemfile and Appraisals without respective changes to the committed gem lock files.
This allows for smaller commits that contain dependency changes at the cost of non-deterministic version resolution until the next update to the committed gem lock files. This non-determinism only applies to any changed gems.
This PR ensures that we removed the enforced CI check that prevents dependency changes without lock file changes. Also, it adapts the dependency caching strategy to account for the fact that Appraisals can be …
=> Remove check for uncommitted gemset changes

tasks/update_appraisal_gemfiles.rake
When updating `ddtrace`'s gemfiles, it's often useful to simple `install` a newly introduced dependency, instead of completely `update`ing the whole gemset.
`install` only applies the changes needed and is an order of magnitude faster than `update`.
=> Add install gemset task

.circleci/config.yml
Follow up to #1579
This PR addresses the scenario where we do not find a matching cache for dependencies, thus have to perform `appraisal install`.
In that case, we'll possibly modify the contents of `gemfiles/*.lock`.
As we always save a cache version of the dependencies for future use, that cache should match the newly changed `gemfiles/*.lock`, as to not deceive future cache restorations on the content of the cached dependencies.
=> Fix dependency cache resolution

.circleci/config.yml
Recent runs of the `test-jruby-9.2.0.0` CI job have been failing across all branches: https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/3811/workflows/1a5694f2-1172-4daf-ae2a-09071c9480aa/jobs/147775
These jobs are `Killed` by CircleCI itself. The jobs are not taking too long, and are being killed before the 3 minute mark, so it's not a timeout.
I suspect that it is running our of memory, thus getting killed.
This PR increases the resource class from medium (4GiB) to medium+ (6GiB): https://circleci.com/docs/2.0/executor-types/#available-docker-resource-classes
medium+ is a newly introduced resource class, so I also changed the still unused truffleruby CI config to medium+ (down from large), as it will likely fit in such resource class as well.
=> Increase JRuby 9.2.0.0 memory limit

Rakefile
Having `bundle exec rake` do something useful (usually running the test suite) is a common convention on Ruby codebases.
Since we switched to RSpec, the default target was not doing anything. I've changed it to run the main test suite.
=> Minor: Make default rake target do something useful

ddtrace.gemspec
The `spec.files` setting controls which files get shipped when the gem gets packaged/installed.
We still use the default setup of everything in git, other than spec/test/features folders. The problem is, that this means that
we're shipping the `integration/`, `gemfiles/`, `.circleci/` and a bunch of extra development stuff.
(Full list at: <https://gist.github.com/ivoanjo/0e3aa44ae9e3ca7a14194d8318f52b62>)
I've pared this list down to include only things useful. After this change, we include the following files in a release (with current master):
```
.gitignore
.yardopts
CHANGELOG.md
CONTRIBUTING.md
LICENSE
LICENSE-3rdparty.csv
LICENSE.Apache
LICENSE.BSD3
NOTICE
README.md
bin/ddtracerb
ddtrace.gemspec
docs/DevelopmentGuide.md
docs/GettingStarted.md
docs/ProfilingDevelopment.md
lib/*
``` …
=> Avoid shipping development cruft files in gem releases

.editorconfig, .gitignore, .rubocop.yml, Gemfile, Rakefile, ddtrace.gemspec, ext/ddtrace_profiling_native_extension/extconf.rb, ext/ddtrace_profiling_native_extension/profiling.c, lib/ddtrace/profiling.rb, lib/ddtrace/profiling/native_extension.rb, spec/ddtrace/auto_instrument_spec.rb, spec/ddtrace/profiling/native_extension_spec.rb, spec/ddtrace/profiling_spec.rb
My current plan is to use the profiling native extension to:
* Enable use of libddprof, a (native) shared library which allows datadog profilers to share common code.
One of the main advantages of this library is that it will include its own profile encoding implementation, which will enable us to drop profiler's dependency on the `google-protobuf` gem.
Right now, we need to tell customers to manually it when onboarding, see <https://docs.datadoghq.com/tracing/profiler/enabling/?code-lang=ruby>, which is annoying.
* Call Ruby VM APIs that are otherwise unavailable or costly when called from Ruby code.
But in this commit, I decided to scale it way, way, way back to just the basics: add an empty native extension, and the
scaffolding to load and test it.
Thus, I hope that by releasing the …
=> [PROF-3425] Bootstrap profiling native extension

lib/ddtrace/contrib/aws/patcher.rb, spec/ddtrace/contrib/aws/instrumentation_spec.rb
Fixes #1589 
This PR modifies the AWS instrumentation to only augment the `Aws::S3` package if present.
This issue was introduced in #1494, when presign S3 requests became excluded from network instrumentation in https://github.com/DataDog/dd-trace-rb/releases/tag/v0.51.0.
=> Fix:Aws instrumentation patch without S3

docs/GettingStarted.md, docs/ProfilingDevelopment.md, lib/ddtrace/configuration/components.rb, lib/ddtrace/profiling.rb, lib/ddtrace/profiling/collectors/stack.rb, lib/ddtrace/profiling/trace_identifiers/ddtrace.rb, lib/ddtrace/profiling/trace_identifiers/helper.rb, spec/ddtrace/configuration/components_spec.rb, spec/ddtrace/profiling/collectors/stack_spec.rb, spec/ddtrace/profiling/integration_spec.rb, spec/ddtrace/profiling/trace_identifiers/ddtrace_spec.rb, spec/ddtrace/profiling/trace_identifiers/helper_spec.rb
This PR is an extraction of the work did for #1568, but without the addition of opentelemetry support for profiler.
We're still discussing with upstream how opentelemetry support will look (see https://github.com/open-telemetry/opentelemetry-ruby/pull/842), but I rather liked the refactoring that we did, so I'd like to merge it in, and later we can just add the missing bits from #1568.
=> Refactor reading of trace identifiers in profiler

.circleci/config.yml, lib/datadog/core/environment/variable_helpers.rb, lib/ddtrace/ext/profiling.rb, lib/ddtrace/profiling/transport/http.rb, spec/ddtrace/configuration/components_spec.rb, spec/ddtrace/profiling/transport/http/adapters/net_integration_spec.rb, spec/ddtrace/profiling/transport/http/integration_spec.rb, spec/ddtrace/profiling/transport/http_spec.rb
The profiler supports reporting profiling data directly to the datadog backend, without having to go through an agent. This setup is actively discouraged by the profiling team for users, but hey, it is really handy for testing and prototyping.
But we don't want users to accidentally enable this mode. Up until now, profiler would implicitly use this mode if users set a `DD_API_KEY` and a `DD_SITE` configuration. Now, this mode will only be enabled if a `DD_PROFILING_AGENTLESS` environment variable is set to `true`.
=> [PROF-2720] Remove automatic agentless support

ext/ddtrace_profiling_native_extension/extconf.rb, lib/ddtrace/profiling.rb, spec/ddtrace/profiling_spec.rb
In #1584 I identified that users of dd-trace-rb on Linux/macOS needed to have a working build environment to compile msgpack and ffi, and so installing our gem would be no different.
I've since identified a possible corner case: in the reliability environment, we use the GitLab omnibus distribution
(<https://docs.gitlab.com/omnibus/>), which already ships pre-compiled versions of msgpack and ffi, but does not include a compiler nor the Ruby headers required for compiling extensions.
Thus, up until now it was trivial to add dd-trace-rb (and profiling) to these images, but the addition of the native extension complicates things a lot.
Since the native extension is still in the "we're evaluating and learning about the downsides/sharp edges of having it" phase, I decided to add a …
=> Add experimental toggle to disable the profiling native extension

lib/ddtrace/contrib/httpclient/patcher.rb, lib/ddtrace/contrib/httprb/patcher.rb
I'm experimenting with adding the [sorbet](https://sorbet.org/) type checker to dd-trace-rb. Since my "adding sorbet" branch is getting quite large and will be hard to review, I've decided to break it into smaller PRs.
This PR fixes an issue caught by sorbet -- there's no "module functions" on the `Datadog::Logger` class, and thus these two methods would fail when trying to log that a failure happened. (I've checked that there are no other such instances in the codebase).
Nice going, sorbet 👌
=> Sorbet: Fix incorrect use of logger in error handling code

lib/datadog/ci/ext/environment.rb, lib/datadog/core/environment/cgroup.rb, lib/datadog/core/environment/container.rb, lib/ddtrace/buffer.rb, lib/ddtrace/configuration.rb, lib/ddtrace/contrib/active_record/configuration/resolver.rb, lib/ddtrace/contrib/active_record/utils.rb, lib/ddtrace/contrib/patcher.rb, lib/ddtrace/diagnostics/environment_logger.rb, lib/ddtrace/metrics.rb, lib/ddtrace/profiling/scheduler.rb, lib/ddtrace/profiling/tasks/setup.rb, lib/ddtrace/propagation/http_propagator.rb, lib/ddtrace/sampling/rule.rb, lib/ddtrace/sampling/rule_sampler.rb, lib/ddtrace/transport/http/client.rb, lib/ddtrace/transport/io/client.rb, lib/ddtrace/workers.rb, lib/ddtrace/workers/async.rb, lib/ddtrace/workers/trace_writer.rb
I'm experimenting with adding the [sorbet](https://sorbet.org/) type checker to dd-trace-rb. Since my "adding sorbet" branch is getting quite large and will be hard to review, I've decided to break it into smaller PRs.
This PR fixes a "possible but probably not gonna happen" issue pointed by sorbet -- Ruby exceptions aren't guaranteed to have a backtrace, and thus `.first` is not guaranteed to always work.
(I wish I could've just used `e.backtrace&.first` but alas that feature is only 6 years old [2.3] so we can't use it yet 😭)
=> Sorbet: Correctly handle nil backtraces when logging

benchmarks/profiler_sample_loop.rb, benchmarks/profiler_submission.rb, lib/ddtrace/profiling.rb, lib/ddtrace/profiling/ext/cpu.rb, lib/ddtrace/profiling/pprof/message_set.rb, lib/ddtrace/profiling/pprof/payload.rb, lib/ddtrace/profiling/transport/http.rb, lib/ddtrace/tasks/exec.rb, lib/ddtrace/transport/traces.rb, spec/ddtrace/benchmark/gem_loading_spec.rb, spec/ddtrace/profiling/integration_spec.rb, spec/ddtrace/profiling/spec_helper.rb
I'm experimenting with adding the [sorbet](https://sorbet.org/) type checker to dd-trace-rb. Since my "adding sorbet" branch is getting quite large and will be hard to review, I've decided to break it into smaller PRs.
This PR contains a bunch of small code changes that semantically are expected to be equivalent, but that make it easy for sorbet to typecheck the affected files.
While I'm not the biggest fan of "just do whatevs to make the tool happy", I think most of these changes are quite reasonable and do make the code easier to understand for humans as well, so I think they're an overall win.
I suggest reviewing this PR commit-by-commit, as I've added context to every message.
=> Sorbet: Set of misc clean ups to enable successful sorbet typechecking

Appraisals
We only support JRuby 9.2, which implements Ruby 2.5, so any references to JRuby on older appraisals are outdated and unused.
GitHub tip: ⚙️  -> "Hide whitespace changes" to review the actual diff without the noise of the indentation change.
=> Remove references to JRuby on Appraisals for Ruby < 2.5

lib/ddtrace.rb, lib/ddtrace/configuration.rb, spec/ddtrace/configuration_spec.rb
dd-trace-rb installs a VM `at_exit` handler that allows it to shut down all of its background tasks cleanly, including attempting to submit and remaining traces and profiles.
This finishing of background tasks is already protected by timeouts (to make sure we don't just hang if talking to the agent is slow), but can still take a few seconds.
When a user presses ctrl+c, they usually expect their process to finish in a timely manner, and may assume the process hung if it doesn't finish immediately. To clarify what's going on (and tell users that they **can** press ctrl+c again to force an exit), I've added a nice message that is printed whenever shut down takes longer than 200ms.
Whenever shutdown is fast enough, no message is printed, to avoid extra noise.
=> [PROF-3285] User-friendly handling of slow submissions on shutdown

docs/GettingStarted.md, lib/ddtrace/contrib/grpc/configuration/settings.rb, lib/ddtrace/contrib/grpc/datadog_interceptor.rb, lib/ddtrace/contrib/grpc/datadog_interceptor/server.rb, spec/ddtrace/contrib/grpc/datadog_interceptor/server_spec.rb
Exposes an `error_handler` option to the GRPC tracer configuration. It uses similar approach to the `error_handler`s for Sidekiq and Faraday.
The motivation behind this is that currently `GRPC::NotFound` errors are being reported as server-side errors, even though (in the semantics of our application) this error is acceptable. Having these errors appear in APM just adds noise and diminishes any other _real_ errors that might appear. 
Here's how that ☝️  looks like in Datadog's UI:
By having the `error_handler` exposed as an option, we can set it to:
```ruby
c.use :grpc, service_name: 'grpc-service', error_handler: proc { |span, error|
span.set_error(error) unless span.nil? || error.is_a?(GRPC::NotFound)
}
```
This ☝️ will allow us to ignore the `GPRC::NotFound` error from appearing in …
=> Add error_handler option to GRPC tracer configuration

lib/datadog/core/environment/container.rb, spec/datadog/core/environment/cgroup_spec.rb, spec/datadog/core/environment/container_spec.rb, spec/support/container_helpers.rb
This PR supports two more Faraday 1.4 cgroup formats:
1. Shorter random component to Container ID suffix: e.g. `609015642` part in `cef584f232933b25e0c6933d7e86cb34-609015642`. This was previously expected to always have 1 digits, but we found production cases with 9. This PR performs a broader match, matching numbers from 1 to 10 digits.
1. Support nested docker ECS+docker deployment: This case contains 2 container ids, but the later one represents the currently running container, while the earlier one represents the host. We take the later one to correlate container metrics.
=> Fix:Additional Faraday 1.4+ cgroup parsing formats

.github/workflows/test-head.yaml
Recently, our truffleruby-head CI tests have been taking a long while to run. I've tracked it down to a performance  regression related to code coverage, and reported it upstream as <https://github.com/oracle/truffleruby/issues/2407>.
Since in our "truffleruby-head" tests we don't care about code coverage (we use CircleCI for that), I've also gone ahead and disabled coverage calculation for all of the "Test unstable" github action.
While I was in the "make this github action faster" neighborhood, I've also added `JRUBY_OPTS=--dev` that makes JRuby go faster in test environments (avoids trying to optimize code that's not going to be executed for long). It's otherwise completely unrelated.
https://github.com/DataDog/dd-trace-rb/runs/3143318972?check_suite_focus=true shows show the GitHub …
=> Workaround truffleruby-head CI testing performance issue by disabling code coverage

.circleci/config.yml
The `Gemfile.lock` was missing from the cache key causing [errors like this in CI](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/3946/workflows/769ae5e9-3eff-4120-ad0f-68b2ffd84b60/jobs/152200):
```
Could not find rubocop-1.18.4 in any of the sources
Run `bundle install` to install missing gems.
```
The contents of `Gemfile.lock` weren't used for cache key in the past because they weren't available before `bundle install`, which defeats the purpose of restoring the cache to avoid installing all gems.
We've more recently started using `bundle lock` to only generate the lock file, but not install all gems. This allows us to now have a lock file before fetching all remote gems.
=> CI:Add Gemfile.lock to avoid mismatch cache

lib/datadog/ci/ext/environment.rb, lib/datadog/core/environment/cgroup.rb, lib/datadog/core/environment/container.rb, lib/ddtrace/buffer.rb, lib/ddtrace/configuration.rb, lib/ddtrace/contrib/concurrent_ruby/patcher.rb, lib/ddtrace/contrib/elasticsearch/quantize.rb, lib/ddtrace/contrib/ethon/patcher.rb, lib/ddtrace/contrib/grpc/patcher.rb, lib/ddtrace/contrib/qless/patcher.rb, lib/ddtrace/contrib/rest_client/patcher.rb, lib/ddtrace/contrib/sinatra/patcher.rb, lib/ddtrace/contrib/sucker_punch/patcher.rb, lib/ddtrace/encoding.rb, lib/ddtrace/profiling/transport/client.rb, lib/ddtrace/quantization/http.rb, lib/ddtrace/transport/http.rb, lib/ddtrace/transport/io/traces.rb, lib/ddtrace/transport/parcel.rb, lib/ddtrace/utils/time.rb
I'm experimenting with adding the [sorbet](https://sorbet.org/) type checker to dd-trace-rb. Since my "adding sorbet" branch is getting quite large and will be hard to review, I've decided to break it into smaller PRs.
As pointed out in <https://sorbet.org/docs/error-reference#7003> (case number 5), there's nothing stopping our `Module`s from being `include`d in Ruby `BasicObject` instances.
Thus, Sorbet points out that `Module`s can't assume that they can use methods in `Object` and `Kernel`, because they aren't present in `BasicObject`s.
Of course that's not how we're using them right now, but Sorbet complains anyway that this may be problematic.
I've thus fixed many such issues pointed out by Sorbet by adding `include Kernel` to our modules. I did not fix all of them, as other files I …
=> Sorbet: Include Kernel module to disambiguate from usage in BasicObject 

lib/ddtrace/configuration/components.rb, spec/ddtrace/configuration/components_spec.rb
Coming from https://github.com/DataDog/dd-trace-rb/pull/1527, this PR builds the default sampler instance during tracer construction, instead of letting it build itself internally.
This is done because `trace.rb` calls https://github.com/DataDog/dd-trace-rb/blob/461a627641755f4338e1e7dbb93d366d4534d968/lib/ddtrace/tracer.rb#L432 which in turn invokes https://github.com/DataDog/dd-trace-rb/blob/461a627641755f4338e1e7dbb93d366d4534d968/lib/ddtrace/sampling/rule_sampler.rb#L30-L33 that tries to access the global `Datadog.configuration` object to find the sampling rates.
The issue is that this happens at `Datadog.configure` time, when the tracer is in the process of being initialized. This code only works today because we were careful when ordering invocation calls to `Datadog.configuration`. …
=> Explicitly build default sampler

spec/ddtrace/opentracer/tracer_integration_spec.rb, spec/ddtrace/profiling/encoding/profile_spec.rb, spec/ddtrace/span_spec.rb
Some of our tests do not reliably set a time zone for their time objects.
The only truly offending test today is:
```
1) Datadog::Profiling::Encoding::Profile::Protobuf::encode debug logging debug logs profile information
Failure/Error: expect(message.call).to include '2020-01-01T00:00:00Z'
expected "Encoding profile covering 2020-01-01T08:00:00Z to 2021-01-01T08:00:00Z, events: 42 (template_debug_statistics)" to include "2020-01-01T00:00:00Z"
```
This happens because my laptop's timezone is not UTC.
This PR fixes all cases where we were initializing a time object without a set time zone in our test suite.
There are no occurrences of this pattern in our production code.
=> Fix test time zones

test/default_test.rb, test/helper.rb, test/rate_by_service_sampler_test.rb
This PR removes a minitest test that perform strict type checking on `Datadog.tracer`.
This tests is uncecessary, as we've since introduce more rich testing around the tracer's public API at `ddtrace_integration_spec.rb`: https://github.com/DataDog/dd-trace-rb/blob/aeecf5e95cc1ad0a45ecaf8f2ff18e84b73fe35b/spec/ddtrace_integration_spec.rb#L92-L157
This also help us clean up one more minitest test.
=> Remove unhelpful default test

Gemfile
With the release of https://github.com/thoughtbot/appraisal/releases/tag/v2.4.1, the missing require issue has been fixed: https://github.com/thoughtbot/appraisal/pull/184.
We can now safely unlock `rake` upgrades, as `appraisal` was previously depending on a require statement from `rake`, which it doesn't anymore in `2.4.1`
=> Unlock rake version after appraisal release

integration/apps/rack/Dockerfile-ci, integration/apps/rack/app/acme.rb, integration/apps/rack/bin/run, integration/apps/rack/docker-compose.ci.yml, integration/apps/rack/docker-compose.yml, integration/apps/rack/script/ci, integration/apps/rack/spec/integration/basic_spec.rb, integration/apps/rails-five/Dockerfile-ci, integration/apps/rails-five/README.md, integration/apps/rails-five/app/controllers/health_controller.rb, integration/apps/rails-five/bin/run, integration/apps/rails-five/config/routes.rb, integration/apps/rails-five/docker-compose.ci.yml, integration/apps/rails-five/docker-compose.yml, integration/apps/rails-five/spec/integration/basic_spec.rb
This PR enables and validates that profiler is working for the `rack` and `rails-five` test apps.
It additionally tweaks the `rack` test app to run tests with multiple webservers (puma, unicorn, webrick).
=> [PROF-3692] Expand CI integration tests, and test using profiler

integration/apps/rack/Gemfile, integration/apps/rack/Rakefile, integration/apps/rack/app/acme.rb, integration/apps/rack/app/resque_background_job.rb, integration/apps/rack/app/sidekiq_background_job.rb, integration/apps/rack/bin/resque, integration/apps/rack/bin/run, integration/apps/rack/bin/sidekiq, integration/apps/rack/docker-compose.ci.yml, integration/apps/rack/docker-compose.yml, integration/apps/rack/spec/integration/basic_spec.rb, integration/apps/rack/spec/support/integration_helper.rb, integration/apps/rails-five/app/controllers/health_controller.rb, integration/apps/rails-five/config/routes.rb, integration/apps/rails-five/spec/integration/basic_spec.rb
I've extended the rack integration test app with a few more endpoints that allow some value to be round tripped asynchronously through a sidekiq/resque worker.
This is used to validate that tracing and profiling-enabled sidekiq/resque workers are working correctly.
As I was going through this work, I realized the same JSON-object pattern could be used in the regular health endpoints, so I've replaced the profiler-specific endpoints with generic endpoints that return a JSON object with a lot of information that can then be asserted in the integration tester.
=> [PROF-3692] Add sidekiq and resque to rack integration test app

lib/ddtrace/contrib/action_pack/action_controller/instrumentation.rb, spec/ddtrace/contrib/action_pack/action_controller/instrumentation_spec.rb, spec/ddtrace/contrib/rails/action_controller_spec.rb, spec/ddtrace/contrib/rails/rack_spec.rb
As of #1623, the profiler records the `resource` of the root span, on top of the span id and trace id during sampling.
Also, as discusssed in the description of #1623 (in the "Getting the correct `resource`" section) integrations where the
`resource` is only set at the end pose an extra challenge, as the request may not be finished in time for the `resource` to be included in the profiler payload.
This means that the profiler may miss the `resource` for some of the requests, depending on timing of when the sampling happens and when the request finishes.
(Note that in this case, the trace id and span id will still be propagated, so the samples will always be able to be tied back to the trace that originated them; it's just the `resource` that will not be included in the profiler data).
To …
=> Move Rails span resource setting to beginning of request

lib/ddtrace/contrib/sinatra/tracer.rb, lib/ddtrace/contrib/sinatra/tracer_middleware.rb, spec/ddtrace/contrib/sinatra/tracer_spec.rb
As of #1623, the profiler records the `resource` of the root span, on top of the span id and trace id during sampling.
Also, as discusssed in the description of #1623 (in the "Getting the correct `resource`" section) integrations where the
`resource` is only set at the end pose an extra challenge, as the request may not be finished in time for the `resource` to be included in the profiler payload.
This means that the profiler may miss the `resource` for some of the requests, depending on timing of when the sampling happens and when the request finishes.
(Note that in this case, the trace id and span id will still be propagated, so the samples will always be able to be tied back to the trace that originated them; it's just the `resource` that will not be included in the profiler data).
To …
=> Set Sinatra resource setting at beginning of request and delay setting fallback resource

lib/ddtrace/configuration/components.rb, lib/ddtrace/configuration/settings.rb, lib/ddtrace/ext/profiling.rb, lib/ddtrace/profiling/collectors/stack.rb, lib/ddtrace/profiling/events/stack.rb, lib/ddtrace/profiling/pprof/stack_sample.rb, lib/ddtrace/profiling/trace_identifiers/ddtrace.rb, lib/ddtrace/profiling/trace_identifiers/helper.rb, lib/ddtrace/span.rb, lib/ddtrace/tracer.rb, spec/ddtrace/configuration/components_spec.rb, spec/ddtrace/configuration/settings_spec.rb, spec/ddtrace/profiling/collectors/stack_spec.rb, spec/ddtrace/profiling/events/stack_spec.rb, spec/ddtrace/profiling/integration_spec.rb, spec/ddtrace/profiling/pprof/stack_sample_spec.rb, spec/ddtrace/profiling/spec_helper.rb, spec/ddtrace/profiling/trace_identifiers/ddtrace_spec.rb, spec/ddtrace/profiling/trace_identifiers/helper_spec.rb
This PR extends the existing support for linking traces to profiles with one extra feature: the `resource` from root spans representing inbound web requests (aka "the endpoint") will be included as part of the profiling data.
This will enable the profiler to expose this as part of the profiling UX (which is still WIP/under discussion).
This feature would've been really easy to add ~~if it weren't for those meddling kids~~ if it weren't for the fact that quite a few integrations set the `resource` on the span at the end of the request, not at the beginning. This creates a problem: the profiler can (and probably will) observe the span before this, and would observe a missing or incorrect `resource` if it just recorded the current `resource` at the time of sampling.
To tackle this issue, I …
=> Add support for annotating profiler stacks with the resource of the active web trace, if any

Gemfile, lib/ddtrace/contrib/grape/endpoint.rb, lib/ddtrace/contrib/grape/instrumentation.rb, spec/ddtrace/contrib/grape/tracer_spec.rb
As of #1623, the profiler records the `resource` of the root span, on top of the span id and trace id during sampling.
Also, as discusssed in the description of #1623 (in the "Getting the correct `resource`" section) integrations where the
`resource` is only set at the end pose an extra challenge, as the request may not be finished in time for the `resource` to be included in the profiler payload.
This means that the profiler may miss the `resource` for some of the requests, depending on timing of when the sampling happens and when the request finishes.
(Note that in this case, the trace id and span id will still be propagated, so the samples will always be able to be tied back to the trace that originated them; it's just the `resource` that will not be included in the profiler data).
To …
=> Move Grape span resource setting to beginning of request

.circleci/config.yml
The version of docker we are using in CircleCI today to build our integration test apps (17.09.0-ce) is rather old (from 2017).
In light of [mysterious recent CI failures](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/4055/workflows/53c4c6b2-f8f6-4898-aeec-48f38bd80ba3/jobs/155861) related to the inner workings of docker, I'm upgrading the docker server version in CI.
I found a somewhat relevant issue in docker upstream that might or might not be related to this issue: https://github.com/moby/moby/issues/40993. I think it might not be the exact same case, but it doesn't hurt to bring in over 3 years of bug fixes.
=> Upgrade CI docker server

lib/ddtrace/contrib/grpc/datadog_interceptor/server.rb, spec/ddtrace/contrib/grpc/datadog_interceptor/server_spec.rb, spec/ddtrace/contrib/grpc/interception_context_spec.rb, spec/ddtrace/contrib/integration_examples.rb
Generally speaking (_though open to interpretation and not specific to a datadog tracing specification_), a `peer.service` tag ought to only be applied to services which represent an operation that's accessing a _remote_ service. So, generally the _callee_ spans (`http.client`, `grpc.client`, `aws.client`, `elasticsearch.client` etc etc). Currently we have also labeled `grpc.server` with a `peer.service` tag, which goes against convention and causes (_later in our tracing pipeline_) the `language:ruby` tag to not be applied to `grpc.server` spans. This `language` tag drives behavior in the UI. When absent, it will cause our UI to _hide_ runtime metrics for this service (_since they'd be representative of the underlying host/container and not particularly relevant to the service in …
=> Dont set peer.service tag on grpc.server spans

lib/ddtrace/profiling/recorder.rb, lib/ddtrace/profiling/scheduler.rb, spec/ddtrace/profiling/integration_spec.rb, spec/ddtrace/profiling/scheduler_spec.rb
Due to the way that ddtrace configuration works, if profiling is started using DD_PROFILING_ENABLED=true but the app is then reconfigured using Datadog.configure , the profiler tries to report an almost empty profile (with < 1s of data usually).
This can be even worse if the Datadog.configure call was also setting up the configuration for reporting to the agent, because this empty profile report will be using the environment defaults and thus result in an error if they are incorrect.
Since these profiles are of little value, let's just skip reporting them.
=> [PROF-3314] Do not report profiles with little data (duration < 1s)

lib/ddtrace/profiling/collectors/stack.rb, spec/ddtrace/profiling/collectors/stack_spec.rb
The Ruby `Thread` API has a really sharp edge around `Thread#[]` and `Thread#[]=`: these methods are "not thread-local but fiber-local". 
The documentation even goes as far as calling this "a confusion", see <https://rubyapi.org/3.0/o/thread#method-i-5B-5D>.
Our CPU-time tracking was suffering from this confusion. Because it was using `Thread#[]`/`Thread#[]=`, if a thread switched between fibers, our CPU-time tracking started miscounting time.
E.g., consider the following test application:
```ruby
def fake_cpu_time(n)
Thread.pass
sleep 0.01
Thread.pass
puts "Fiber #{n} yielding..."
Fiber.yield :frozen
puts "Fiber #{n} resumed..."
Thread.pass
sleep 0.005
Thread.pass
sleep 0.005
Thread.pass
end
def start_fibers
fibers = (0..1000).map do |n|
Fiber.new do
fake_cpu_time(n)
end
end …
```
=> [PROF-3321] Fix CPU-time accounting when fibers are used

.pryrc, ddtrace.gemspec
Pry 0.14.0 dropped support for auto-loading plugins (<https://github.com/pry/pry/blob/master/CHANGELOG.md#breaking-changes>) which is really annoying.
Thus, I've decided to add a project-level `.pryrc` that loads all plugins when using pry in dd-trace-rb.
=> Require pry plugins in `.pryrc`

lib/ddtrace/contrib/sinatra/env.rb, lib/ddtrace/contrib/sinatra/tracer.rb, spec/ddtrace/contrib/sinatra/tracer_spec.rb
This fixes a regression introduced in version 0.52.0 by #1628.
When a Sinatra modular application being traced is missing the `Datadog::Contrib::Sinatra::Tracer` middleware (as documented in <https://docs.datadoghq.com/tracing/setup_overview/setup/ruby/#sinatra>), no Sinatra request span is ever created (only a route span).
Because we didn't properly account for this in `#datadog_span`, the following `NoMethodError` was triggered:
```
NoMethodError: undefined method `[]' for nil:NilClass
dd-trace-rb/lib/ddtrace/contrib/sinatra/env.rb:13:in `datadog_span'
dd-trace-rb/lib/ddtrace/contrib/sinatra/tracer.rb:122:in `block in route_eval'
dd-trace-rb/lib/ddtrace/tracer.rb:283:in `trace'
dd-trace-rb/lib/ddtrace/contrib/sinatra/tracer.rb:105:in `route_eval' …
```
=> Fix NoMethodError in sinatra integration when Tracer middleware is missing

lib/datadog/ci/contrib/rspec/integration.rb, spec/datadog/ci/contrib/rspec/integration_spec.rb
This adds support for projects that use `rspec-rails` instead of standard `rspec`. (Both explicitly depend on `rspec-core`.)
=> Require `rspec-core` for RSpec integration

benchmarks/profiler_sample_loop.rb, benchmarks/profiler_submission.rb, spec/ddtrace/configuration/components_spec.rb, spec/ddtrace/configuration_spec.rb, spec/ddtrace/profiling/integration_spec.rb, spec/ddtrace/profiling/pprof/builder_spec.rb, spec/ddtrace/profiling/pprof/stack_sample_spec.rb, spec/ddtrace/profiling/pprof/template_spec.rb, spec/ddtrace/profiling/transport/http/adapters/net_integration_spec.rb, spec/ddtrace/profiling/validate_benchmarks_spec.rb, spec/ddtrace/profiling_spec.rb
While working on #1648 I discovered that one of the profiler benchmarks (profiler_submission.rb) was actually broken, and had been for some time.
To avoid these "surprises", I've added a small spec to load and run the benchmarks, so that if they start failing, we'll know about it.
To avoid impacting the speediness of our test suite, the benchmarks are run with a minimal time/warmup -- the objective is not to measure anything at all, but just to confirm that they do run.
P.s.: This PR was opened on top of #1648; once that branch is merged, this one will switch to target master as well.
P.s.2: Initially when I pushed this branch I got some flakiness in CI, and dividing deep on those failures also made me uncover that one of our specs caused flakiness that made the profiler spec suite not …
=> Add spec to validate that benchmarks don't break + fix profiler spec flakiness

.circleci/config.yml
These had been broken since #1612, due to the change in 4175abdb68 where I added an explicit failure when the ruby and rspec tests tried to run in CI (since they don't actually test anything).
At that time, I changed the regular CI job configuration, but missed that the "edge" one had a copy-pasted configuration that also needed adjustment.
=> Fix broken circleci edge job integration tests

lib/ddtrace/contrib/auto_instrument.rb, lib/ddtrace/contrib/rails/auto_instrument_railtie.rb, lib/ddtrace/contrib/registerable.rb, lib/ddtrace/profiling/tasks/setup.rb
Requiring ddtrace leads to requiring these files which in turn require ddtrace
=> Remove circular dependencies.

docs/GettingStarted.md
Just noticed that the older link was not working.
=> Fix link to Ruby profiler onboarding

docs/GettingStarted.md
Fixing anchor links that go nowhere because their target headings changed.
=> [DOCS-2448] Fix hash links that have lost their anchor

integration/apps/rack/Dockerfile-ci, integration/apps/rack/bin/run, integration/apps/rack/docker-compose.yml, integration/apps/rails-five/Dockerfile-ci, integration/apps/rails-five/bin/run, integration/apps/rails-five/docker-compose.yml, integration/images/include/build_ddtrace_profiling_native_extension.rb
In #1615 I added profiler tests to the integration test apps, and made sure that the profiling native extension was built when running the ci scripts.
I completely missed that the extension was not built when running the integration apps locally.
I've now extracted the "build the native extension" into a separate script in the shared folder, as well as made sure that it runs for both CI and also when running the apps locally using docker.
=> Auto-build profiling native extension before running integration apps locally

lib/ddtrace/contrib/action_cable/instrumentation.rb, lib/ddtrace/contrib/action_cable/patcher.rb, sorbet/rbi/todo.rbi, spec/ddtrace/contrib/action_cable/patcher_spec.rb
Action Cable's channel hooks allow users to perform various tasks, including checking if the channel can actually be subscribed to, and establishing streams based on different parameters (i.e. stream updates from a particular `Post` based on `params[:id]`).
These hooks can result in Active Record calls (and thus database queries), which can cause "orphaned" spans to exist outside of a particular APM service, without a single top-level span that they roll up to. Active Record span in particular end up behaving slightly differently, due to the way Active Record's tracing attempts to use the same service as the span's `parent` (if it exists).
Now, we create an outer span that these lower-level spans roll up to, allowing for much clearer understanding when monitoring Action Cable.
=> Instrument Action Cable subscribe/unsubscribe hooks

lib/datadog/ci/ext/environment.rb, spec/datadog/ci/ext/fixtures/ci/gitlab.json
When a pipeline runs on a merge request it should tag the branch of the merge request
=> Use the merge request branch on merge requests

docs/GettingStarted.md, lib/ddtrace/contrib/active_job/configuration/settings.rb, lib/ddtrace/contrib/active_job/log_injection.rb, lib/ddtrace/contrib/active_job/patcher.rb, lib/ddtrace/contrib/rails/framework.rb, spec/ddtrace/contrib/rails/rails_active_job_spec.rb
Similar to how dd-trace hooks into the Rails web request logs, it can do the same for Active Job executions.
This is not *quite* a full solution to #1068, but it does get dd-trace most of the way there for folks who are using Sidekiq via Active Job. Since Active Job handles *most* of the work in those cases, the only logs that are not correlated to the active DataDog trace are those coming directly from Sidekiq itself (i.e. `start` and `done`).
This follows up on #1639.
=> Correlate Active Job logs to the active DataDog trace

spec/ddtrace/contrib/sucker_punch/patcher_spec.rb
This took me a while to hunt down, and it manifested as a `StandardError: Wait time exhausted!` in the
`try_wait_until { Thread.list.size < count }` line of the `after` cleanup block.
Example failure:
<https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/4346/workflows/88a101cc-8c06-44b6-84b6-efedef4e426a/jobs/165493/parallel-runs/1>
The issue was caused by the cleanup code assuming that the Thread list would go down after telling SuckerPunch to shut down.
This assumption was broken by test cases where we run the test so fast that SuckerPunch doesn't get to start a background thread to run the task. Thus, the number of threads in the `after` block can never go down, since none ended up being started. 
One way of simulating this issue is to comment out the `__perform_async(*args)` …
=> Fix flaky SuckerPunch patcher spec on JRuby

lib/ddtrace/configuration/settings.rb, lib/ddtrace/profiling/collectors/stack.rb, lib/ddtrace/profiling/encoding/profile.rb, lib/ddtrace/utils/time.rb, spec/ddtrace/profiling/collectors/stack_spec.rb, spec/ddtrace/profiling/ext/cthread_spec.rb, spec/ddtrace/profiling/integration_spec.rb, spec/ddtrace/utils/time_spec.rb
Prior to this change, the profiler tried to sample all threads each time it decided to sample.
This could have a negative impact on the latency of Ruby services with a lot of threads, because each sampling pass would be quite expensive.
Just as an illustration, consider the `benchmarks/profiler_sample_loop` benchmark which tries to sample as
fast as possible 4 threads with very deep (500 frames+) stacks.
As the number of threads to sample increases, so does the performance of sampling degrade:
| Sampled threads | Iterations per second                               |
|-----------------|-----------------------------------------------------|
| 4 threads       | 390.921  (± 6.1%) i/s -      3.920k in  10.075624s  |
| 16 threads      |  97.037  (± 6.2%) i/s -    972.000  in  10.072298s  |
| 32 …
=> [PROF-3814] Limit number of threads per sample

lib/ddtrace/contrib/sidekiq/ext.rb, lib/ddtrace/contrib/sidekiq/integration.rb, lib/ddtrace/contrib/sidekiq/patcher.rb, lib/ddtrace/contrib/sidekiq/server_internal_tracer/heartbeat.rb, lib/ddtrace/contrib/sidekiq/server_internal_tracer/job_fetch.rb, lib/ddtrace/contrib/sidekiq/server_internal_tracer/scheduled_push.rb, sorbet/rbi/todo.rbi, spec/ddtrace/contrib/sidekiq/patcher_spec.rb, spec/ddtrace/contrib/sidekiq/server_internal_tracer/heartbeat_spec.rb, spec/ddtrace/contrib/sidekiq/server_internal_tracer/job_fetch_spec.rb, spec/ddtrace/contrib/sidekiq/server_internal_tracer/scheduled_push_spec.rb, spec/ddtrace/contrib/sidekiq/support/helper.rb
These 3 areas of the open source version of Sidekiq are not wrapped in high-level spans, resulting in a *lot* of one-off Redis spans that are not related to one another in any way.
The most important change to call out here is the bump in the supported Sidekiq version. There were some significant underlying code changes between Sidekiq v3 and v4, and with Sidekiq 3.5.4 being over 5 years old (released 2016-01-13), that seemed to be a reasonable decision.
That said, I'm open to keeping v3 support, with this new internal tracing focused only on v4+.
Closes #1673.
=> Trace Sidekiq server internal events (heartbeat, job fetch, and scheduled push)

integration/apps/rack/Gemfile, integration/apps/rack/app/acme.rb, integration/apps/rack/app/resque_background_job.rb, integration/apps/rack/app/sidekiq_background_job.rb, integration/apps/rack/docker-compose.ci.yml, integration/apps/rack/script/ci, integration/apps/rack/spec/integration/basic_spec.rb, integration/apps/rails-five/app/controllers/health_controller.rb, integration/apps/rails-five/script/ci, integration/apps/ruby/script/ci, lib/ddtrace/contrib/delayed_job/plugin.rb
Since #1526 we've been printing the app logs when a failure is triggered, but unfortunately the behavior of using
```some failure || print logs```
breaks the bash `set -euo pipefail` behavior we use that should cause the `ci` test scripts to fail if the underlying command fails.
After I fixed this, I noticed there were a few CI tests that were broken, and fixed them as well. Luckily, the breakages were around test setup, and not (that I could see) any actual issues.
=> Fix CI not properly breaking when integration tests failed + Fix a bunch of broken integration tests

integration/apps/rails-five/Gemfile
Bump Rails dependencies used for integration testing to make dependabot happy.
=> Fix dependabot warnings

lib/ddtrace/contrib/ethon/easy_patch.rb, lib/ddtrace/contrib/ethon/multi_patch.rb, lib/ddtrace/tracer.rb, spec/ddtrace/contrib/ethon/integration_context.rb, spec/ddtrace/contrib/ethon/shared_examples.rb, spec/ddtrace/contrib/ethon/typhoeus_integration_spec.rb
The last production usage of `Datadog::SpanOperation#parent=` was in the Ethon integration.
That usage was necessary to allow for Ethon Multi request to properly parent their "multi" execution context:
```ruby
multi = Ethon::Multi.new
easy_1 = Ethon::Easy.new
easy_1.http_request(url_1, 'GET')
multi.add(easy_1)
easy_2 = Ethon::Easy.new
easy_2.http_request(url_2, 'GET')
multi.add(easy_2)
multi.perform
```
In this example, both `easy_1` and `easy_2` are children requests for the a `multi` span. But because `easy_1` and `easy_2` run concurrently, both will have an open span at the same time.
The timeline is as follows: `multi` span created, `easy_1` span created, , `easy_2` span created, `easy_1` span finished, `easy_2` span finished, `multi` span finished. ("`easy_1` span finished" and …
=> Refactor:Remove Span#parent= usage in Ethon

lib/ddtrace/sync_writer.rb, lib/ddtrace/writer.rb, spec/ddtrace/sync_writer_spec.rb, spec/ddtrace/writer_spec.rb
Services had to be explicitly provided to the trace writer (`Datadog::Writer#write(..., services)`) in order to be instrumented. This has long been unnecessary, and `services` options has been ignored since then.
This PR removes the `services` argument from `Datadog::Writer#write` and `Datadog::SyncWriter#write`.
=> Deprecate:Writer services

lib/ddtrace/contrib/extensions.rb, spec/ddtrace/contrib/extensions_spec.rb
The integration registry has been moved from the configurable `Datadog.configuration.registry` to the global, append-only `Datadog.registry` in #1572.
With this move we deprecated access to `Datadog.configuration.registry` and `Datadog.configuration.registry=`. This PR removes those deprecated APIs. `Datadog.registry` is the recommended replacement.
=> Deprecate:Contrib::Configuration#registry

lib/ddtrace/contrib/resque/integration.rb, spec/ddtrace/contrib/resque/integration_spec.rb
The maximum version limit of 3.0 was mistakenly added in #1213.
Since we support the latest Resque versions (https://rubygems.org/gems/resque/versions), there's no reason to limit the supported version to an upper bound, as we are not aware of any incompatibilities with future Resque versions.
=> Remove maximum resque version support

lib/ddtrace/contrib/mongodb/parsers.rb
These methods have been unused since https://github.com/DataDog/dd-trace-rb/pull/463.
They only reference each other.
=> Deprecate:Unreachable methods in MongoDB integration

lib/datadog/ci/ext/environment.rb, spec/datadog/ci/ext/fixtures/ci/buildkite.json, spec/datadog/ci/ext/fixtures/ci/circleci.json, spec/datadog/ci/ext/fixtures/ci/usersupplied.json
Fixes #1745
Updated CI environment variables parsing algorithm with latest specification.
=> Update CI environment variables parsing

lib/datadog/ci/test.rb
Fixes #1748
Environment tags do not change during the life of the test process, so we should calculate them only once.
=> Memoize environment tags to improve performance

.github/workflows/test-head.yaml
Unfortunately the CI output right now needs to be binary: pass, or fail. Because we don't want to block contributions due to some breakage in truffleruby-head, we set the CI to `continue-on-error: true` aka never fail.
But then we miss that truffleruby-head has been broken for quite some time. And even now that we know it, we won't be doing anything about it, since it's not a priority.
So... this testing doesn't seem to be adding any value. Thus, I propose that we delete it.
Hopefully, in the near future, we'll be able to add a stable truffleruby release to CI, and keep that one green (and care about when it breaks). See #1383 for ongoing tracking for this.
=> Drop truffleruby-head testing

docs/GettingStarted.md, lib/ddtrace/context.rb, lib/ddtrace/manual_tracing.rb, lib/ddtrace/opentelemetry/extensions.rb, lib/ddtrace/pipeline.rb, lib/ddtrace/span.rb, lib/ddtrace/span_operation.rb, lib/ddtrace/sync_writer.rb, lib/ddtrace/tagging.rb, lib/ddtrace/tagging/analytics.rb, lib/ddtrace/tagging/manual_tracing.rb, lib/ddtrace/tagging/metadata.rb, lib/ddtrace/tracer.rb, spec/ddtrace/context_flush_spec.rb, spec/ddtrace/context_spec.rb, spec/ddtrace/contrib/ethon/easy_patch_spec.rb, spec/ddtrace/integration_spec.rb, spec/ddtrace/opentelemetry/span_spec.rb, spec/ddtrace/opentracer/span_spec.rb, spec/ddtrace/pipeline_spec.rb, spec/ddtrace/span_operation_spec.rb, spec/ddtrace/span_spec.rb, spec/ddtrace/tagging/analytics_spec.rb, spec/ddtrace/tagging/manual_tracing_spec.rb, spec/ddtrace/tagging/metadata_spec.rb, spec/ddtrace/tagging_spec.rb, spec/ddtrace/tracer_integration_spec.rb, spec/ddtrace/tracer_spec.rb, spec/support/tracer_helpers.rb
Expanding upon the implementation of `SpanOperation`, this pull request seeks to change its behavior from wrapping and mutating a `Span`, to building a copy of a `Span` only on `SpanOperation#finish`. In effect, the `SpanOperation` acts as a builder or factory pattern.
The main motivation to do this is to:
1. Simplify `Span` objects into basic structs suitable for wire serialization
2. Prevent their mutation after completion so that instrumentation does not produce race conditions or other unexpected behavior by modifying a completed `Span` by reference. (Eventually, we'd like to make `Span` outright immutable, but for now this is an intermediate step.)
3. Reduce the references held on the `Tracer` side of instrumentation, to reduce the likelihood of memory leaks.
In doing so, much of the …
=> Generate Span object from SpanOperation

docs/GettingStarted.md, lib/ddtrace/configuration/components.rb, lib/ddtrace/context_flush.rb, lib/ddtrace/opentracer/tracer.rb, lib/ddtrace/sync_writer.rb, lib/ddtrace/tracer.rb, lib/ddtrace/writer.rb, spec/ddtrace/configuration/components_spec.rb, spec/ddtrace/contrib/http/request_spec.rb, spec/ddtrace/contrib/sidekiq/disabled_tracer_spec.rb, spec/ddtrace/integration_spec.rb, spec/ddtrace/opentracer/tracer_spec.rb, spec/ddtrace/sync_writer_spec.rb, spec/ddtrace/tracer_spec.rb, spec/ddtrace/transport/http/integration_spec.rb, spec/ddtrace/workers_integration_spec.rb, spec/ddtrace/writer_spec.rb, spec/support/tracer_helpers.rb
This PR deprecates the `Datadog::Tracer#configure` method, which partially reconfigured the live tracer at any point of the host application execution. This flexibility created many complications, as the trace writer and sampler could be changed at any point in time, creating possibility for race conditions in many points of interactions of the internal `ddtrace` components.
The functionality from `Datadog::Tracer#configure` has been migrated to `Datadog::Tracer#new`.
Because `#configure` was invoked in the regular `ddtrace` initialization (at [`Components#build_tracer`](https://github.com/DataDog/dd-trace-rb/blob/148dfaeac9a890d8d9ec4fd74abfd3621869f33c/lib/ddtrace/configuration/components.rb#L71-L76)), there was quite a bit of refactoring to do to consolidate all tracer initialization …
=> Deprecation:Tracer#configure

lib/ddtrace/ext/priority.rb, lib/ddtrace/sampler.rb, lib/ddtrace/sampling/rule_sampler.rb, spec/ddtrace/integration_spec.rb, spec/ddtrace/sampler_spec.rb, spec/ddtrace/sampling/rule_sampler_spec.rb
This PR changes changes how the sampling decisions yielded by the `Datadog::Sampling::RuleSampler` affect the span's `_sampling_priority_v1` tag.
Before, `0` (for rejecting) and `1` (for keeping) were used for `RuleSampler` decisions. The issue with this approach is that `0` and `1` are default sampling values that allow for the sampling decision to be altered downstream, either by the Agent or by the Datadog backend.
`0` and `1` communicate intent, not a strong decision. These works great when the sampling rate is not strictly important: for example, it is normally desirable to keep an error span, even if it's marked with a sampling decision of `0`, as that span will have valuable debugging information.
The issue with `0` and `1` is that they don't allow for strict control of sampling …
=> Use USER_KEEP/USER_REJECT for RuleSampler decisions

ext/ddtrace_profiling_native_extension/extconf.rb
The profiling native extension relies on the Ruby MJIT headers on 2.6+.
But these headers are not available in Rubies that were compiled with JIT disabled.
To avoid impacting these users (e.g. making them explicitly need to install with `DD_PROFILING_NO_EXTENSION=true`), let's automatically skip the extension when we detect that the JIT was disabled.
In the future, we can explore using `debase-ruby_core_source` for these Ruby versions, if we still want to support these users.
Fixes #1774
=> Skip building profiling native extension when Ruby has been compiled without JIT

benchmarks/profiler_sample_loop.rb, benchmarks/profiler_submission.rb
This makes it easier to explore these microbenchmarks in the reliability environment (see PR #564 on the private relenv repository).
=> Increase profiler microbenchmark run time

.circleci/config.yml
We haven't observed changes between MRI JIT and non-jit configurations, so let's remove for now our separate JIT testing, to simplify our ever-growing testing matrix.
=> Remove jit variants from CircleCI

docs/GettingStarted.md, integration/apps/rack/app/datadog.rb, integration/apps/rails-five/config/initializers/datadog.rb, integration/apps/rspec/app/datadog.rb, integration/apps/ruby/app/datadog.rb, lib/ddtrace/configuration/settings.rb, spec/ddtrace/configuration/settings_spec.rb, spec/ddtrace/diagnostics/environment_logger_spec.rb
Removes the deprecated `c.analytics_enabled` settings, as `c.analytics.enabled` has been preferred for a while.
=> Deprecation:analytics_enabled setting

docs/GettingStarted.md, integration/apps/rack/app/datadog.rb, integration/apps/rails-five/config/initializers/datadog.rb, integration/apps/rspec/app/datadog.rb, integration/apps/ruby/app/datadog.rb, lib/ddtrace/configuration/settings.rb, lib/ddtrace/opentracer/global_tracer.rb, spec/ddtrace/configuration/agent_settings_resolver_spec.rb, spec/ddtrace/configuration/settings_spec.rb, spec/ddtrace/configuration_spec.rb, spec/ddtrace/diagnostics/environment_logger_spec.rb, spec/ddtrace/integration_spec.rb, spec/ddtrace/opentracer/global_tracer_spec.rb
Removed tracer instance configuration option using the `c.tracer option: value` syntax.
The `c.tracer.option = value` syntax has been preferred for a while.
=> Deprecation:c.tracer() settings

docs/GettingStarted.md, integration/apps/rack/app/datadog.rb, integration/apps/rails-five/config/initializers/datadog.rb, integration/apps/rspec/app/datadog.rb, integration/apps/ruby/app/datadog.rb, lib/ddtrace/configuration/settings.rb, lib/ddtrace/opentracer/global_tracer.rb, spec/ddtrace/configuration/agent_settings_resolver_spec.rb, spec/ddtrace/configuration/settings_spec.rb, spec/ddtrace/configuration_spec.rb, spec/ddtrace/diagnostics/environment_logger_spec.rb, spec/ddtrace/integration_spec.rb, spec/ddtrace/opentracer/global_tracer_spec.rb, spec/ddtrace/workers_spec.rb, spec/support/log_helpers.rb
`c.logger = ...` has been removed, with the preferred `c.logger.instance = ...` as its replacement.
=> Deprecation:c.logger= setting

spec/ddtrace/workers_integration_spec.rb
These tests fail quite often on macOS CI:
* <https://github.com/DataDog/dd-trace-rb/runs/4375525018?check_suite_focus=true>
* <https://github.com/DataDog/dd-trace-rb/runs/4370371648?check_suite_focus=true>
So let's just disable them until someone has the resources to fix it.
=> Disable flaky specs on macOS

docs/GettingStarted.md
As discussed during the last Ruby guild meeting with @delner.
We had discussed making this entry into a table, like we have for interpreters/web servers/etc but on closer look I don't think a table has the space to include the support details, especially the ones for Windows.
=> Document partial support (non-production) of macOS

lib/ddtrace/span.rb, lib/ddtrace/span_operation.rb, lib/ddtrace/transport/serializable_trace.rb, spec/ddtrace/span_operation_spec.rb, spec/ddtrace/span_spec.rb
I recently noticed that while we usually collect the number of memory allocations on a given span, we send it as an "allocations" field to the agent and this data never seems to make it to the backend.
Instead, this refactor reports it as a span metric. Does this make sense?
This is still missing tests and whatnot, but I wanted to get a feel if I'm doing this correctly before I did the full changes.
Also, as requested by @delner I'm targeting this to the 1.0 branch.
=> RFC: Send number of allocations in span as metric

lib/ddtrace/profiling/scheduler.rb, spec/ddtrace/profiling/scheduler_spec.rb
In Ruby applications that use multiple processes (such as webservers like puma), we start a profiler instance for each individual process.
If those applications fork all their processes at the same time (usually at start-up time), we get N processes that start profiling at the same time, and that will report profiles every minute at exacty the same time.
To spread out the impact of this reporting (both on the reporting app, as well as on the profiling backend), this PR adds a very small random sleep (at most 3 seconds) before each report is made.
Note that because we sleep AFTER we collect the events from the recorder, we still report exactly the same data as before -- we just may report it ever-so-slightly later.
=> [PROF-4260] Add jitter to profile flushes

spec/datadog/ci/trace_flush_spec.rb
Fixes naming conflict with base tracer shared examples at `spec/ddtrace/trace_flush_spec.rb` that have the same name:
```
WARNING: Shared example group 'trace operation' has been previously defined at:
./spec/datadog/ci/trace_flush_spec.rb:8
and you are now defining it at:
./spec/ddtrace/trace_flush_spec.rb:6
The new definition will overwrite the original one.
WARNING: Shared example group 'a trace flusher' has been previously defined at:
./spec/datadog/ci/trace_flush_spec.rb:27
and you are now defining it at:
./spec/ddtrace/trace_flush_spec.rb:21
The new definition will overwrite the original one.
```
=> Fix conflicing shared_example in CI test

.circleci/config.yml, .circleci/images/primary/Dockerfile-2.3.8, docker-compose.yml
Ruby 2.3 builds [have been failing](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/5061/workflows/7c4b9709-4e96-4038-8843-6d1dda2a22fd/jobs/189567) with:
```
bundle install
Fetching gem metadata from https://rubygems.org/..........
google-protobuf-3.19.2-x86_64-linux requires ruby version >= 2.5, < 3.1.dev,
which is incompatible with the current version, ruby 2.3.8p459
Exited with code exit status 5
```
This happens despite https://rubygems.org/gems/google-protobuf/versions/3.19.2-x86-linux correctly advertising that it only supports Ruby `>= 2.5, < 3.1.dev`.
This is a bundler issue, and our Ruby 2.3 CI image uses [bundler 1.17.3](https://rubygems.org/gems/bundler/versions/1.17.3), the last of the 1.x series.
We had previously locked bundler to 1.x, as some of our 3rd party …
=> Upgrade Ruby 2.3 bundler to 2.x

Gemfile
Latest version >= 0.5.0 of https://rubygems.org/gems/rspec_junit_formatter does not support Ruby < 2.3: https://github.com/sj26/rspec_junit_formatter/issues/94.
Because a version that does not support Ruby < 2.3 has already been published, we can't allow `rspec_junit_formatter` to install an unbounded version.
This PR locks it to `0.4.1`.
=> Lock rspec_junit_formatter for Ruby < 2.3

.circleci/config.yml, .circleci/images/primary/Dockerfile-2.3.8, Gemfile, docker-compose.yml
This PR actually fixes the build issue regarding the latest version of protobuf. It reverts the previous attempt at #1821.
The issue is that Bundler 1.x fails to recognize that version >= 3.19.2 of protobu is not compatible with older rubies.
This PR ensures that Ruby < 2.4, which use bundler 1.x in our CI, explicitly depend on protobuf < 3.19.2.
=> Lock protobuf for Ruby < 2.3

benchmarks/profiler_sample_loop.rb, benchmarks/profiler_submission.rb
The intention of the `profiling/validate_benchmarks` spec is to run the profiler benchmarks for a short amount of time as part of our test suite, to make sure they haven't broken.
But we saw some flakiness in these tests (see #1812) due to the benchmark harness failing with
```
/usr/local/bundle/gems/benchmark-ips-2.9.1/lib/benchmark/ips/job.rb:187:in `to_i': Infinity (FloatDomainError)
```
Upon investigation, this was caused by the warm up time being so small that sometimes it did not run, which benchmark-ips didn't like at all -- see https://github.com/evanphx/benchmark-ips/issues/120 .
To fix this, I've disabled the warmup (set it to 0), as we don't really care about warmup on these tests.
I've also noted (in <https://github.com/evanphx/benchmark-ips/issues/120#issuecomment-1006487480>) …
=> Fix flaky profiling/validate_benchmarks spec

benchmarks/profiler_submission.rb, lib/ddtrace/ext/profiling.rb, lib/ddtrace/profiling/transport/http/api/endpoint.rb, spec/ddtrace/profiling/transport/http/adapters/net_integration_spec.rb, spec/ddtrace/profiling/transport/http/api/endpoint_spec.rb, spec/ddtrace/transport/http/adapters/net_integration_spec.rb
Although not stated explicitly, the Ruby profiler was previously using the 1.2 intake format.
The 1.3 format (lightly documented [here](https://github.com/DataDog/profiling-backend/blob/prod/README.md#v3-intake-format-used-by-go-net-native) [Datadog-internal link, apologies]) shuffles around the fields a bit:
* `recording-start` => `start`
* `recording-end` => `end`
* `data[0]` + `types[0]` => `data[somefilename]`
* `runtime` => `family`
* `format` is removed
* `version` is added
This change is not observable to customers; but is a requirement to submitting extra files along with profiles, as we plan to do in #1813.
I also included a few cleanups to the specs; I suggest reviewing this PR commit-by-commit.
Since this PR needs some profiling-backend specific knowledge to validate (aka that …
=> [PROF-4535] Switch profiling to use intake 1.3 format

.github/workflows/codeql-analysis.yml
Static code analysis on dd-trace-rb using Github's Code Scanning.
This PR has Github workflow configs to trigger the Code Scanning on every PR and on push to master and release branch. It is a part of Datadog compliance requirements to regularly perform code-scanning on all the customer installed code. As of now only default security based CodeQL queries are configured. We can gradually add queries for Code Quality later.
=> Setup Code Scanning for dd-trace-rb

.github/workflows/test-head.yaml, .github/workflows/test-macos.yaml, Gemfile
```
Bundler found conflicting requirements for the Ruby version:
In Gemfile:
Ruby
ddtrace was resolved to 0.54.1, which depends on
Ruby (>= 2.1.0, < 3.2)
Ruby (>= 2.1.0, < 3.2), which is required by gem 'ddtrace', is not available in
```
The reason for this version constraint is because `ruby2_keywords` is expected to disappear on 3.2 but the current code relies on it.
- Disable testing of ruby-head in CI
- Bump maximum Ruby version to 3.3
- Other?
> Disable testing of ruby-head in CI
Not too fond of this, maybe make it as "allow failure" (if that's not already the case) so as not to block dependent jobs, but GHA is terrible and the UI would mark the whole build as failure even though it's OK (I wish it had a "warning" visual state as in GitLab CI)
> Bump maximum Ruby version to 3.3
I'd …
=> Relax version constraint for Ruby HEAD testing

docs/GettingStarted.md, lib/datadog/tracing.rb, lib/ddtrace.rb, lib/ddtrace/configuration/settings.rb, lib/ddtrace/pipeline.rb, spec/datadog/tracing_spec.rb, spec/ddtrace/configuration/settings_spec.rb
This PR creates explicit methods in the new `Datadog::Tracing` module that expose the core functionality we want to expose for Datadog APM Tracing.
Most existing tracing-specific methods have moved from `Datadog.tracer.method` to `Datadog::Tracing.method`. The main change is that only methods that provide first-class tracing features are exposed in the `Datadog::Tracing` module.
Our hope is that the `Datadog::Tracing` module will be the point of interaction for the vast majority of interactions between the host application and APM Tracing.
The goal is for the vast majority of Datadog tracing methods that need to be interweaved with the host application to come from `Datadog::Tracing`. We'll strive to maintain concise naming and a simple but flexible API for `Datadog::Tracing` methods.
All …
=> Public Tracing API

ddtrace.gemspec
This commit bumps our dependency on the `debase-ruby_core_source` (used by profiling) to allow the latest released version.
Additionally, rather than forcing a specific version, I've relaxed it to allow older versions as well, since customers may have other gems that depend on older/specific versions of that gem.
=> Update debase-ruby_core_source dependency, and allow older versions

CHANGELOG.md
The 0.x-stable branch is now standalone and separate from master (which represents 1.0.0.dev), but we still want the changelog to include entries for all releases of the library, so I'm cherry-picking the relevant commit from #1835 .
=> Sync changelog updates from 0.x-stable branch back to master

Gemfile
See https://github.com/msgpack/msgpack-ruby/issues/239 for more details.
Example of broken CI run: <https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/5167/workflows/1808cc8b-e055-479c-a50d-f00469b260fb/jobs/193173>
=> Fix CI by adding workaround for upstream msgpack issue on JRuby

lib/ddtrace/tracer.rb, spec/ddtrace/tracer_spec.rb
We've removed the statement that outputs the contents of `trace.spans` to the user recently by accident.
This PR restores that debug output.
The string format for `trace.spans` remains the same, I've just replaced the call to
```ruby
str = String.new('')
PP.pp(trace.spans, str)
str
```
with
```ruby
trace.spans.pretty_inspect
````
as they perform the same operation: https://github.com/ruby/ruby/blob/59a91f229b17d9664df6ff78d7aa4e13a88cdb63/lib/pp.rb#L617-L619
=> Restore trace debug logging output

lib/ddtrace/contrib/patchable.rb, spec/ddtrace/contrib/patchable_spec.rb
`ddtrace` can't be correctly installed if `Gem::Version.new(RUBY_VERSION) >= Gem::Version.new(VERSION::MINIMUM_RUBY_VERSION)` fails, thus this condition is impossible in a correctly configured environment.
=> Remove impossible Ruby version check

lib/ddtrace/tracer.rb, spec/ddtrace/tracer_spec.rb
Removes the early return of `continue_trace!`, as we'd like for the provided block to always execute, regardless if there was an error in setting up the tracer internal state.
=> Ensure yield for Tracer.continue_trace!

lib/ddtrace/configuration/settings.rb, lib/ddtrace/tracer.rb, spec/ddtrace/tracer_integration_spec.rb, spec/ddtrace/tracer_spec.rb
Fixes a problem introduced by #1844
When a manual trace is preceded by `Datadog::Tracing.continue_from!`, the trace won't deactivate after finishing:
```ruby
trace_digest = HTTPPropagator.extract(env)
Datadog::Tracing.continue_from!(trace_digest)
span = Datadog::Tracing.trace('http.request')
span.finish
Datadog::Tracing.active_span
```
This is because in `Tracer#manual_trace_activation!`, it has the following line:
```ruby
return if original_trace == trace
```
This safeguard, is meant to prevent deactivation events from being overridden, and trace being reactivated unnecessarily. However because `Tracer#continue_trace!` in this example creates and activates a trace before the span is created, this `manual_trace_activation!` function thinks adding the deactivation event and activating the …
=> Fix manual traces not deactivating

lib/datadog/core/buffer/cruby.rb, lib/datadog/core/buffer/random.rb, lib/datadog/core/buffer/thread_safe.rb, lib/ddtrace/buffer.rb, lib/ddtrace/profiling/buffer.rb, spec/datadog/core/buffer/cruby_spec.rb, spec/datadog/core/buffer/random_spec.rb, spec/datadog/core/buffer/shared_examples.rb, spec/datadog/core/buffer/thread_safe_spec.rb, spec/ddtrace/profiling/buffer_spec.rb
This pull request moves some `Buffer` classes to `Datadog::Core::Buffer`.
It's part of a series of `Core` namespacing PRs derived from `refactor/core-namespacing`:
1. #1847
2. #1848
3. #1850 
4. #1851
5. #1852 
6. #1853 
7. #1854 
8. #1855 
9. **=> Namespacing: Datadog::Core::Buffer**
10. #1857
11. #1858
12. #1859 
13. #1860 
14. #1861 
15. #1862
=> Namespacing: Datadog::Core::Buffer

spec/ddtrace/contrib/sinatra/tracer_spec.rb, spec/ddtrace/integration_spec.rb, spec/ddtrace/propagation/http_propagator_spec.rb, spec/support/tracer_helpers.rb
This PR performs a few tracer RSpec cleanups:
1. Remove `alias get_test_tracer new_tracer`.
2. Remove unused `get_test_tracer_with_old_transport`.
3. Remove `tracer#configure` mocking, unnecessary after #1753.
=> Clean up tracer instance spec

lib/ddtrace/contrib/rack/middlewares.rb, lib/ddtrace/contrib/sinatra/framework.rb, lib/ddtrace/contrib/sinatra/patcher.rb, lib/ddtrace/contrib/sinatra/tracer_middleware.rb, spec/ddtrace/contrib/sinatra/multi_app_spec.rb, spec/ddtrace/contrib/sinatra/tracer_spec.rb
This attemps to mimic what is currently done with Rails.
Sinatra provides only limited public facilities to manipulate the stack
(namely, appending with `use`), assumes his default middlewares are
always first, and has a peculiar way to wrap the middlewares to build
the app stack.
Sinatra also freezes the stack when the builder is run, so we have to
get access to the moment the builder is available but not yet run to
alter the list by patching `Sinatra::Base#setup_default_middlewares`.
The `Datadog::Contrib::Sinatra::Framework` class encapsulates these
internal implementation details behind a few methods to achieve the
desired manipulations.
=> Enable Rack integration for Sinatra

lib/datadog/tracing/metadata/ext.rb, spec/datadog/tracing/contrib/rack/integration_test_spec.rb, spec/datadog/tracing/contrib/sinatra/tracer_spec.rb, spec/datadog/tracing/metadata/ext_spec.rb
This PR addresses HTTP 
- **Changed**: Normalization of `http.response.headers.*` span tags for the Rack and Sinatra integrations have changed to respect [the Datadog standard tagging requirements](https://docs.datadoghq.com/getting_started/tagging/#defining-tags). Additionally, periods (`.`) are replaced with underscores (`_`). For example, a tag that was previously `http.response.headers.content_type` will now become `http.response.headers.content-type`.
=> Core:Fix HTTP header normalization when used as tag

lib/datadog/security/configuration.rb
Seeing the CI product mention an example of its config around recent namespace changes I realised the AppSec configuration DSL was not consistent with other products.
This PR makes it use `c.enabled = true` instead of `c.enabled true`.
=> Use writers for appsec config

lib/datadog/core/configuration/agent_settings_resolver.rb, lib/datadog/core/configuration/settings.rb, lib/ddtrace/transport/http.rb, spec/datadog/core/configuration/agent_settings_resolver_spec.rb, spec/datadog/core/configuration/settings_spec.rb, spec/datadog/profiling/transport/http_spec.rb, spec/datadog/tracing/integration_spec.rb, spec/ddtrace/transport/http/builder_spec.rb, spec/ddtrace/transport/http_spec.rb
Up until now, we supported two ways of passing custom configurations to `transport_options`: either a hash, or as a proc.
The hash variant is not (that I could find) documented anywhere, and is a subset of the proc variant, so I propose that we remove it in time for 1.0.0.
This allows us to remove a lot of extra complexity around configuring our transports, while keeping the same flexibility in place (the proc variant).
(As a reminder, despite its legacy name, `c.tracer.transport_options` is handled by the `AgentSettingsResolver` and can be used by every product to configure its transport).
=> RFC: Remove deprecated ability to provide `c.tracer.transport_options` as a hash, support proc only

lib/datadog/tracing/span_operation.rb, spec/datadog/tracing/span_operation_spec.rb
The allocations metric on Span has been around for a long time, sitting unused, but only recently exposed as a metric.
Because we only collect global statistics, the number of allocations reported on each span can be grossly exaggerated. Besides, it has the highest cost of any operation in the `SpanOperation` class, affecting the critical path performance.
* Removed: span `allocations` metric.
=> Remove SpanOperation.allocations

lib/datadog/tracing/trace_segment.rb
[Forwardable](https://ruby-doc.org/stdlib-3.1.0/libdoc/forwardable/rdoc/Forwardable.html) is very convenient but consistently shows up as adding measurable overhead to method calls.
This PR uses direct calls to previously Forwardable methods in `TraceSegment`.
=> perf:Remove Forwardable from TraceSegment

lib/datadog/tracing/span_operation.rb
`SpanOperation` can emit 4 distinct lifecycle events:
```ruby
:after_finish
:after_stop
:before_start
:on_error
```
Of those, `:on_error` is only accessed when an exception goes unrescued inside a SpanOperation. All other 3 events are always accessed.
This PR makes the `:on_error` lazily initialized, skipping the need to create an object that is likely to never be used.
=> perf:Lazy OnError event initialization

lib/datadog/ci/contrib/cucumber/formatter.rb, lib/datadog/ci/contrib/rspec/example.rb, lib/datadog/tracing/contrib/presto/instrumentation.rb, lib/datadog/tracing/trace_operation.rb, lib/datadog/tracing/tracer.rb, spec/datadog/tracing/trace_operation_spec.rb, spec/datadog/tracing_spec.rb
How we define and call methods can have a significant impact on performance. "Splatting" (use of `*` or `**`) is the most expensive, and utilized a few places as a shorthand. This pull request replaces this behavior with more efficient calls.
Testing many different ways of invoking a function and returning the same output in Ruby 3.0 yields:
```
Comparison:
positional: 10655656.3 i/s
positional kwargs:  9624532.0 i/s - 1.11x  (± 0.00) slower
kwargs:  8061702.1 i/s - 1.32x  (± 0.00) slower
positional opts:  7387281.3 i/s - 1.44x  (± 0.00) slower
explicit **positional:  7131263.9 i/s - 1.49x  (± 0.00) slower
**positional:  6964865.1 i/s - 1.53x  (± 0.00) slower
positional **kwargs:  6907537.6 i/s - 1.54x  (± 0.00) slower
kwargs unused:  5474591.5 i/s - 1.95x  (± 0.00) slower
explicit …
```
=> Remove splat behavior from tracer

lib/datadog/tracing/trace_segment.rb
There's a (small) performance hit incurred by using dynamically defined functions (might have to do with scope.) Instead, using normally defined functions is more performant, even if more verbose.
=> Use functions over helpers in TraceSegment

lib/datadog/core/environment/identity.rb, lib/datadog/core/environment/socket.rb, lib/datadog/tracing/span_operation.rb, lib/datadog/tracing/trace_segment.rb, spec/datadog/tracing/trace_segment_spec.rb
When profiling span creation and serialization, we noticed that object duplication was responsible for a measurable part of our overhead.
This PR avoids some of that cost by only duplicating objects if they are not `.frozen?`.
Many of the values (e.g. lang, span name, span type) are normally internal `ddtrace` string constants, which are frozen.
Some of the values used by `SpanOperation#build_span` and `TraceSegment#initialize` could be frozen in other parts of `ddtrace`, but I'm keeping this PR concise, specially since the changes in this PR have been extensively tested in our internal environment.
=> perf:Avoid copying frozen objects

Rakefile, lib/datadog/appsec.rb, lib/datadog/appsec/configuration/settings.rb, lib/datadog/appsec/contrib/rack/request.rb, lib/datadog/appsec/extensions.rb, spec/datadog/appsec/extensions_spec.rb, spec/datadog/appsec/spec_helper.rb
This PR moves AppSec configuration into the `appsec` configuration namespace in the global configuration: `Datadog.configure { |c| c.appsec._option_ }`.
The existing AppSec configuration code paths still exist, but should be removed in the future. This PR only ensures that `Datadog.configure` can correctly configure AppSec.
I suggest migrating all AppSec configuration to use Core configuration DSL defined in `lib/datadog/core/configuration/*`: this way we are able to seemesly configure all products in a single block. There is a few files that duplicate `lib/datadog/core/configuration/*` behaviour, like `Datadog::AppSec::Configuration::DSL` and `Datadog::AppSec::Configuration::Settings`, so it would be good to reduce duplication and ensure consistent behaviour.
=> Namespace AppSec settings

.github/workflows/system-tests.yml
Enables the full set of Ruby system test apps, comprised of:
```
rack: 3.0
sinatra14: 2.4
sinatra20: 2.7
sinatra21: 3.1
rails32: 2.1
rails40: 2.2
rails41: 2.3
rails42: 2.4
rails50: 2.5
rails51: 2.6
rails52: 2.7
rails60: 2.7
rails61: 3.0
rails70: 3.1
```
The base app images are built from https://github.com/DataDog/system-tests-apps-ruby, currently internal but that will be made public. The system test suite then builds from those base images to use the proper ddtrace version to test against.
=> Run full system test matrix

README.md, docs/GettingStarted.md
This PR adds a link to our YARD documentation page to both our official documentation page (https://docs.datadoghq.com/tracing/setup_overview/setup/ruby/) and to GitHub's Readme.
As a bonus, this adds a Rubygems badge as well.
=> Add YARD link to docs

lib/datadog/appsec/contrib/rails/framework.rb, lib/datadog/appsec/contrib/sinatra/framework.rb
These two lines were mistakenly identified as enabling Tracing instrumentation, but they are AppSec instrumentation.
=> Fix AppSec after c.instrument namespacing

lib/datadog/appsec/contrib/rack/gateway/watcher.rb
No trace is present when the tracer is not setup, which led to a possible crash in AppSec.
This fixes it by adding a truth check. The remainder of the code (in `AppSec::Event`)  then handles the absence of a root span properly already.
=> Ensure presence of active trace when looking for root span in AppSec

integration/apps/rspec/app/datadog.rb, integration/apps/rspec/docker-compose.ci.yml, integration/apps/rspec/docker-compose.yml, lib/datadog/ci.rb, lib/datadog/opentelemetry/extensions.rb, lib/datadog/tracing/contrib.rb, lib/datadog/tracing/contrib/auto_instrument.rb, lib/datadog/tracing/contrib/extensions.rb, lib/datadog/tracing/contrib/rails/auto_instrument_railtie.rb, lib/ddtrace.rb, lib/ddtrace/auto_instrument.rb, spec/ddtrace/auto_instrument_spec.rb
When only `require 'datadog/ci'` is defined, it doesn't load all the dependencies CI uses, and then raises an error. A workaround for this is `require 'ddtrace'` but it will require everything.
We have `datadog/ci.rb` require its dependencies as well. This means we also have to have `datadog/tracing/contrib` load and apply its own extension behavior, which necessitates refactoring out the old extension behavior from `ddtrace.rb` into `contrib.rb` and elsewhere.
=> Fix require 'datadog/ci' not loading dependencies

lib/datadog/profiling/ext.rb, spec/datadog/profiling/transport/http/adapters/net_integration_spec.rb, spec/datadog/profiling/transport/http/api/endpoint_spec.rb
The profiling team decided to rename this file for consistency.
The code provenance feature (#1813) is not yet exposed to customers, and the only release made with the old file name is 1.0.0.beta1 so this does not cause any regression.
=> Rename `code_provenance.json` reported by profiler to `code-provenance.json`

docs/UpgradeGuide.md
To try to improve comprehension and ease of use, I've restructured the 1.0 upgrade guide a bit here.
- Table of contents at beginning outlines a `Basic usage` and `Advanced usage` path.
- Reorganized some existing sections
- Added `Trace API` section with table of common mappings.
- Rewrote `Namespacing` section, added table.
- Updated code blocks for improved legibility.
- Fixed some errors in examples
- Changed anchors to prefix with `1.0` (for future-proofing)
=> 1.0 upgrade guide restructure

docs/GettingStarted.md
The `GettingStarted.md` documentation could be a bit clearer. Specifically we want to add details about UDS configuration and OTLP, but to have sufficient clarity, the install steps require a bit of rework.
This pull request:
- Changes the `Installation` section to describe configuring the agent, and configuring the application to connect to it.
- Condenses much of the `Advanced configuration` section into a table, eliminates a few sections, updates a few others.
Will probably be easiest to review as a whole document, rather than as lines changed.
=> Update installation steps

lib/datadog/appsec/assets/waf_rules/recommended.json, lib/datadog/appsec/assets/waf_rules/risky.json, lib/datadog/appsec/assets/waf_rules/strict.json
Fetched from https://github.com/DataDog/appsec-event-rules/tree/0958752d77604fd2f0b8fd3d778ec5639f4f96c2/build
Tag `1.2.6` missed a rebuild for `risky` and `strict`, so they got fetched from the above commit, where they have been subsequently rebuilt.
=> Update ruleset to v1.2.6

lib/datadog/core/configuration/agent_settings_resolver.rb, lib/ddtrace/transport/http.rb, spec/datadog/profiling/transport/http/integration_spec.rb, spec/ddtrace/transport/http_spec.rb
The `ENVIRONMENT_AGENT_SETTINGS` constant was introduced to support a few classes/specs that needed an `agent_settings` object  to fall back to.
Since there are so little users of this constant (which is good), let's remove it from the `AgentSettingsResolver` class and instead move it to the class/specs that make use of it.
This way, the weight of legacy/weird behavior is on the classes that need it, rather than on the `AgentSettingsResolver` class.
=> Move ENVIRONMENT_AGENT_SETTINGS to class/specs that need it

lib/datadog/core/configuration/agent_settings_resolver.rb, spec/datadog/core/configuration/agent_settings_resolver_spec.rb
I'm working on a change to the `AgentSettingsResolver` and decided to extract these cleanups/fixes out of that branch to make it easier to review and have them merged sooner.
See the individual commits for details on each change.
Note that this PR does not change any observable behavior.
=> `AgentSettingsResolver` cleanups and spec improvements

lib/datadog/core/configuration/agent_settings_resolver.rb, spec/datadog/core/configuration/agent_settings_resolver_spec.rb, spec/datadog/tracing/integration_spec.rb
As documented in the getting started guide (<https://docs.datadoghq.com/tracing/setup_overview/setup/ruby/#configuring-the-transport-layer>), one way of configuring ddtrace is to provide a proc as the `tracing.transport_options` configuration setting.
Up until now, the `AgentSettingsResolver` class effectively "gave up" when it saw one of these procs, and just included it the proc in its `AgentSettings` output.
This meant that:
a) If there were any invalid or conflicting settings, we could not detect or warn about them
b) We were in the dark on what settings actually were going to be used, since the proc could do anything it wanted. The `AgentSettings` object could be completely used or completely ignored.
c) It was hard to provide alternative transport implementations, because they may …
=> Enable extraction of http/unix adapter config from transport_options proc

lib/datadog/tracing/contrib/grape/endpoint.rb, spec/datadog/tracing/contrib/grape/tracer_spec.rb
Closes #1940 
When tracing is disabled, the `enabled?` function in Grape instrumentation was still evaluating to true, because it was only checking the Grape configuration setting. This would cause instrumentation to still run, but yield a `nil` trace and attempt to decorate it.
Updating `enabled?` to check for whether `tracing.enabled` is set fixes the issue.
It would be better in the future if setting `c.tracing.enabled` simply precluded all instrumentation blocks, but our API currently doesn't support this. Thus, instrumentation must check the state itself. Something to improve another time.
=> Fix Grape raising error while tracing is disabled

lib/datadog/tracing/contrib/rake/instrumentation.rb, spec/datadog/tracing/contrib/rake/instrumentation_spec.rb
Addresses #1940 
This pull request adds an additional safeguard to prevent Rake from instrumenting when tracing is disabled.
We will want to adjust the internals and API of the tracer to do this automatically later, but this will help in the interim.
=> Fix Rake instrumenting while disabled

docs/GettingStarted.md
Same as [Remove dead link](https://github.com/DataDog/dd-trace-rb/commit/eed718c9b2e36bf8acfa5696648b113fa7ffd3a1) but on the branch that the public docs uses (release)
=> Remove stale link

lib/datadog/appsec/configuration/settings.rb, spec/datadog/appsec/configuration/settings_spec.rb, spec/datadog/appsec/extensions_spec.rb
Current RFC-defined env vars are:
-  `DD_APPSEC_ENABLED`
-  `DD_APPSEC_RULES` # This one is currently not compliant, which this PR addresses
-  `DD_APPSEC_WAF_TIMEOUT`
=> Align env var with RFC

.circleci/config.yml, gemfiles/ruby_3.0.3_contrib.gemfile.lock
In #1915 the Ruby 3.0 image was updated to 3.0.3 but I forgot to also update the image in `config.yml`.
I've double-checked, and I believe this was the only missing update.
This brings our CI back to beautiful green!
=> Fix incorrect image used for testing Ruby 3.0

docs/GettingStarted.md
We've been running Ruby 3.1 in CI since November 2021 (see #1779 and #1915) but we had not yet updated our docs to state our support for it.
=> Document support for Ruby 3.1

docs/GettingStarted.md
Remove Tracing without Limits occurrences from the Ruby tracer documentation
=> Review Sampling docs for Ruby

ddtrace.gemspec
Latest version changelog looks good:
<https://my.diffend.io/gems/debase-ruby_core_source/0.10.14/0.10.15>
so let's allow this version to be used as well.
=> Bump `debase-ruby_core_source` maximum version to include latest version

lib/datadog/appsec/contrib/rack/request_middleware.rb, lib/datadog/appsec/processor.rb, spec/datadog/appsec/processor_spec.rb
Adjusts the behaviour from raising an exception to outputting an error and allow the app to continue running. This also generalises the error management beyond a ruleset file being missing and also takes into account various invalid ruleset cases or libddwaf unavailability.
In these cases, in addition to the error, a warning is produced that alerts the user that AppSec is subsequently disabled.
=> AppSec: resist missing ruleset file

ext/ddtrace_profiling_native_extension/extconf.rb, ext/ddtrace_profiling_native_extension/profiling.c
The native extension is not intended to expose any symbols/functions for other native libraries to use, so let's set the default visibility to hidden.
This avoids accidental symbol naming clashes with other extensions/libraries.
Test suite still green :)
=> Hide symbols/functions in profiling native extension

.github/workflows/test-macos.yaml
For quite a while Ruby-head was stable enough that it did not affect our testing, but recently a few tests started failing consistently, e.g. <https://github.com/DataDog/dd-trace-rb/runs/5885670306?check_suite_focus=true>
At least one failure is related to a change to the `RubyVM.stat` output, which seems to be undergoing some development (see <https://github.com/ruby/ruby/pull/5766>).
At least one of the other failures (regarding initialization of `Datadog::Profiling::Recorder` seems to be a regression/new bug on upstream Ruby.
I don't think it's worth necessarily tracking Ruby-head breaking changes (for instance the `RubyVM` change had a bit of back and forth and we would've had to do more work if we were trying to keep up with it), so let's remove this for now.
As an alternative, Ruby …
=> Fix broken CI by disabling testing with Ruby head/nightly on macOS

lib/ddtrace/version.rb
A maximum version was initially added in https://github.com/DataDog/dd-trace-rb/pull/1495 because we expected the `ruby2_keywords` method to be removed (see the PR for the discussion).
Now Ruby 3.2.0-preview1 is out and `ruby2_keywords` are still there, and there's even a recent change for it in https://github.com/ruby/ruby/pull/5684 that is documented as "ruby2_keywords needed in 3.2+".
So for now let's bump the maximum version to < 3.3 to allow the Ruby 3.2 series to be supported and we can keep an eye on the Ruby 3.2 test releases to see if anything changes.
(Otherwise, once Ruby 3.2.0 stable is out, we should probably bump this to 3.4, and so on...)
=> Allow dd-trace-rb usage in Ruby 3.2 (aka bump maximum version to < 3.3)

lib/datadog/appsec/contrib/rack/gateway/watcher.rb, lib/datadog/appsec/event.rb, lib/datadog/core/utils/safe_dup.rb, lib/datadog/tracing/metadata.rb, lib/datadog/tracing/metadata/errors.rb, lib/datadog/tracing/metadata/tagging.rb, lib/datadog/tracing/trace_operation.rb, lib/datadog/tracing/trace_segment.rb, lib/ddtrace/transport/trace_formatter.rb, spec/datadog/tracing/metadata/errors_spec.rb, spec/datadog/tracing/metadata/tagging_spec.rb, spec/datadog/tracing/metadata_spec.rb, spec/datadog/tracing/trace_operation_spec.rb, spec/datadog/tracing/trace_segment_spec.rb, spec/ddtrace/transport/trace_formatter_spec.rb
Since trace transport does not have a concept of trace, tags are set on the topmost span.
When partial flushing is involved, the topmost span will be sent upon last flush, therefore tags will only appear in the UI when that final segment is processed.
=> Add setting a tag at the trace-level

docs/UpgradeGuide.md
The upgrade guide was incorrectly recommending usage of `agent.hostname` when it should be recommending `agent.host`.
=> Docs: Fix UpgradeGuide.md "agent.host"

docs/GettingStarted.md
The Getting Started documentation is missing the option for service_name for rake instrumentation.
=> Docs: Fix GettingStarted.md rake

lib/datadog/tracing/context_provider.rb, lib/datadog/tracing/tracer.rb, spec/datadog/tracing/context_provider_spec.rb, spec/datadog/tracing/integration_spec.rb
Fixes https://github.com/DataDog/dd-trace-rb/issues/1979
`Thread[]` and `Thread[]=` are fiber-local attributes[¹](https://bugs.ruby-lang.org/issues/8215#note-1), not thread-local as we have described them in `ddtrace`.
But they are also thread-safe, given these attributes are retrieved from the ["current thread's root fiber if not explicitly inside a Fiber"](https://ruby-doc.org/core-3.1.2/Thread.html#method-i-5B-5D). Effectively, `Thread[]` and `Thread[]=` are both thread-safe and fiber-safe, but fiber-safe is the most accurate way to describe them.
This PR does not change any behavior, only clarifies nomenclature around fiber- vs thread-local storage.
Also, this PR adds one test to ensure the fiber-local behavior explicitly, given all tests are centered around threads today.
One …
=> Rename thread-local to fiber-local in concurrent context

lib/datadog/tracing/correlation.rb, lib/datadog/tracing/span.rb, lib/datadog/tracing/span_operation.rb, lib/datadog/tracing/trace_operation.rb, lib/datadog/tracing/trace_segment.rb, spec/datadog/tracing/trace_operation_spec.rb
`TraceOperation#resource` describes the "best" resource name for the trace. When no value is explicitly set, this value would be inherited (at span creation) from the first span in the trace. e.g. `trace.resource ||= root_span.resource`.
This kind of eager initialization doesn't work well with existing instrumentation: it's common practice for instrumentation to change the resource name from within the trace block itself, after the span was created. e.g.
```ruby
def execute
Datadog::Tracing.trace('job.execute') do |span|
span.resource = job_name
super
end
end
```
Because no resource name is provided when the span is created, the span's resource name defaults to the span's name, then the trace resource name defaults to the spans resource name. Thus the trace resource would be set as …
=> Fix resource not inherited from lazily annotated spans

lib/datadog/tracing/contrib/rails/patcher.rb, spec/datadog/tracing/contrib/rails/support/base.rb
Fixes #1986.
I updated the specs to set up the mock Rails logger to be like [the default logger](https://github.com/rails/rails/blob/7-0-stable/railties/lib/rails/application/bootstrap.rb#L37-L53) that ships in a Rails application. I also tested this in a freshly-generated Rails 7.0 app, and our own production applications. No more warning, and the log tags work correctly.
=> Fix Rails log tagging in 1.0.0.beta2

.github/workflows/system-tests.yml
Bailing out on the first failure prevents other possible failures to be displayed, which makes addressing each one of them in turn a slow, iterative business.
=> Run all system tests on test failure

lib/datadog/appsec/contrib/rack/request.rb
Downstream libddwaf expects keys and values to be extractable separately so we can't use `[[k, v], ...]`. We also want to allow duplicate keys, so we use `[{k, v}, ...]` instead.
Depends on https://github.com/DataDog/system-tests/pull/323 for system tests to pass.
=> Fix query address for libddwaf

integration/apps/rack/app/acme.rb, lib/datadog/appsec/autoload.rb, lib/datadog/ci/ext/environment.rb, lib/datadog/core/configuration/agent_settings_resolver.rb, lib/datadog/core/environment/cgroup.rb, lib/datadog/core/environment/container.rb, lib/datadog/core/metrics/client.rb, lib/datadog/core/runtime/metrics.rb, lib/datadog/core/workers/async.rb, lib/datadog/profiling.rb, lib/datadog/profiling/tasks/exec.rb, lib/datadog/profiling/tasks/setup.rb, lib/datadog/tracing/buffer.rb, lib/datadog/tracing/contrib/active_record/configuration/resolver.rb, lib/datadog/tracing/contrib/active_record/utils.rb, lib/datadog/tracing/contrib/active_record/vendor/connection_specification.rb, lib/datadog/tracing/contrib/active_support/notifications/subscription.rb, lib/datadog/tracing/contrib/rails/log_injection.rb, lib/datadog/tracing/contrib/rake/instrumentation.rb, lib/datadog/tracing/event.rb, lib/datadog/tracing/sampling/rule.rb, lib/datadog/tracing/sampling/rule_sampler.rb, lib/datadog/tracing/span_operation.rb, lib/ddtrace/transport/http/client.rb, lib/ddtrace/transport/io/client.rb
Ruby exceptions can have really confusing, vague, or even empty messages.
To help us out during debugging, I've added the exception class in exception-related logs to give us more context while debugging issues.
This is quite low-hanging fruit, but I think in general we have a long way to go in improving exception logging in dd-trace-rb.
In particular, we should probably look into centralizing exception logging in a method to solve the following:
* Eliminate duplication. Can you spot how often I had to copy paste `e.class.name` in this PR?
* There's a few cases where we just log the message, without any context. (I did not touch those)
* The formatting of our error messages is quite inconsistent. Sometimes we include the backtrace, sometimes not. Sometimes we call the backtrace location, …
=> Improve exception logging

docs/GettingStarted.md
We've been running JRuby 9.3 in CI for ~1 month now (see #1723) without issue, so let's flag it as supported in the compatibility matrix.
=> Add JRuby 9.3 to compatibility matrix

docs/GettingStarted.md
While reviewing https://github.com/datadog/documentation/pull/13871 I got to thinking how easy it is to forget to update the requirements page with any changes we do to `GettingStarted.md`, so I thought of at least adding a comment to hopefully remind us to keep them in sync.
=> Add note to remind us to keep compatibility requirements page in docs in sync

lib/datadog/appsec/contrib/rack/patcher.rb, lib/datadog/appsec/contrib/rails/patcher.rb, lib/datadog/appsec/contrib/sinatra/patcher.rb, lib/datadog/appsec/reactive/operation.rb
There were a couple of circular `require` references in AppSec code that raised some warnings during specs.
=> Remove AppSec circular require references

lib/datadog/appsec/event.rb, lib/datadog/appsec/rate_limiter.rb, spec/datadog/appsec/event_spec.rb
The following condition prevents the scenario from happening, nonetheless I'd rather have this case sorted out within `record`:
```
AppSec::Event.record(*both_response.map { |_action, event| event }) if both_response.any?
```
This becomes increasingly important to guarantee proper rate limiter behaviour upon recording as AppSec functional coverage increases e.g with https://github.com/DataDog/dd-trace-rb/pull/1969
Also, it increases spec coverage for `Datadog::AppSec::Event`, which is always good to have.
=> Ensure appsec rate limiter behaviour

.rubocop.yml, lib/datadog/appsec/configuration/settings.rb
Rubocop has [dropped support for Ruby 2.5 analysis in 1.29.0](https://github.com/rubocop/rubocop/blob/2f2b2a7aa75b5222457966fdacc464f085c8c308/relnotes/v1.29.0.md#changes).
This PR upgrades our `.rubocop.yml` file to adapt to this change.
Another minor change is a fix to a warning about `rubocop:disable Metrics/LineLength` being moved to `rubocop:enable Layout/LineLength`.
=> Upgrade to Rubocop 1.29.0

spec/datadog/integration_spec.rb
This test is regularly flaky, e.g.:
<https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/6027/workflows/64536fbc-1101-4a81-8e85-c5321422aa32/jobs/223019/tests>
```
Failure/Error:
expect(after_open_file_descriptors.size)
.to(
eq(before_open_file_descriptors.size),
lambda {
"Open fds before (#{before_open_file_descriptors.size}): #{before_open_file_descriptors}\n" \
"Open fds after (#{after_open_file_descriptors.size}):  #{after_open_file_descriptors}"
}
)
Open fds before (10): {"/dev/fd/0"=>"/dev/pts/1", "/dev/fd/1"=>"/dev/pts/1", "/dev/fd/2"=>"/dev/pts/1",
"/dev/fd/3"=>nil, "/dev/fd/4"=>nil, "/dev/fd/5"=>nil, "/dev/fd/6"=>nil,
"/dev/fd/7"=>"/tmp/rspec/---patternspec-**-*_spec.rb--exclude-patternspec-**-{contrib,benchmark,redis,opentracer,auto_instrument}-**-*_spec.rb, …
```
=> Reduce test flakyness by relaxing expectation

.rubocop.yml, Rakefile, ddtrace.gemspec, ext/ddtrace_profiling_loader/ddtrace_profiling_loader.c, ext/ddtrace_profiling_loader/extconf.rb, ext/ddtrace_profiling_native_extension/extconf.rb, lib/datadog/profiling.rb, lib/datadog/profiling/load_native_extension.rb, spec/datadog/profiling_spec.rb
When Ruby loads a native extension (using `require`), it uses `dlopen(..., RTLD_LAZY | RTLD_GLOBAL)` (https://github.com/ruby/ruby/blob/67950a4c0a884bdb78d9beb4405ebf7459229b21/dln.c#L362).
This means that every symbol exposed directly or indirectly by that native extension becomes visible to every other extension in the Ruby process. This can cause issues, see https://github.com/rubyjs/mini_racer/pull/179.
Ruby's extension loading mechanism is not configurable -- there's no way to tell it to use different flags when calling `dlopen`. To get around this, this commit introduces introduces another extension (profiling loader) which has only a single responsibility: mimic Ruby's extension loading mechanism, but when calling  `dlopen` use a different set of flags.
This idea was shamelessly …
=> [PROF-5343] Isolate profiling native extension native symbols

lib/datadog/core/configuration/components.rb
The fix in #1998, specifically in 2e5d1eee4e267a2553f2ab92168959b8655bf936 broke using `datadog/core` directly without `require 'ddtrace'`.
For instance:
```
bundle exec ruby -e "require 'datadog/core'; Datadog.configure { }"
Traceback (most recent call last):
9: from -e:1:in `<main>'
8: from .../lib/datadog/core/configuration.rb:89:in `configure'
7: from .../lib/datadog/core/configuration.rb:223:in `safely_synchronize'
6: from .../lib/datadog/core/configuration.rb:223:in `synchronize'
5: from .../lib/datadog/core/configuration.rb:225:in `block in safely_synchronize'
4: from .../lib/datadog/core/configuration.rb:94:in `block in configure'
3: from .../lib/datadog/core/configuration.rb:243:in `build_components'
2: from .../lib/datadog/core/configuration.rb:243:in `new'
1: from …
```
=> Fix NoMethodError when running `Datadog.configure` after only requiring core

lib/datadog/appsec/contrib/rack/request.rb, lib/datadog/appsec/contrib/rails/gateway/watcher.rb, lib/datadog/appsec/contrib/rails/patcher.rb, lib/datadog/appsec/contrib/rails/reactive/action.rb, lib/datadog/appsec/contrib/rails/request.rb, lib/datadog/appsec/contrib/sinatra/gateway/watcher.rb, lib/datadog/appsec/contrib/sinatra/patcher.rb, lib/datadog/appsec/contrib/sinatra/reactive/routed.rb
Since this needs a more varied per framework access pattern, it also splits Rails body params extraction out of Rack.
System test is:
```
runner           | XPASSED tests/appsec/waf/test_addresses.py::Test_PathParams::test_security_scanner - Expected to fail, but all is ok
```
=> Fetch parameters from route path

ext/ddtrace_profiling_loader/extconf.rb
Trying to build for JRuby fails. Even if it did work, we wouldn't use it anyway (we don't support profiling for non-MRI rubies), so let's just skip it.
=> Skip building profiling loader extension on JRuby/TruffleRuby

lib/datadog/profiling/ext.rb, spec/datadog/profiling/transport/http/adapters/net_integration_spec.rb, spec/datadog/profiling/transport/http/api/endpoint_spec.rb
In the UX, tracing is using `process_id` (automatically mapped) and the processes product will also work with `process_id`.
=> Rename profiling `pid` tag to `process_id` to align with other products 

docs/UpgradeGuide.md
Fixes #2014
This PR addresses the misnamed method `Datadog::Tracing.continue_from!`.
This was supposed to be `Datadog::Tracing.continue_trace!`.
At some point in early 1.0.0 development, this method was indeed called `continue_from!`, but was later changed to `continue_trace!` by the 1.0.0 final release.
=> Fix incorrect reference to Tracing.continue_from!

lib/datadog/core/configuration/settings.rb, lib/datadog/core/environment/variable_helpers.rb, spec/datadog/core/environment/variable_helpers_spec.rb
Fixes #1953
This PR adds space-separated list support, in addition to the existing comma-separated list, to environment variable list options.
This brings us up to parity with [other traces](https://github.com/DataDog/dd-trace-py/pull/2196).
The only application option currently is `DD_TAGS`.
Initially, I implemented this change to all users of `Datadog::Core::Environment::VariableHelpers#env_to_list`, but the other use case, `DD_PROPAGATION_STYLE_*`, has a space in one of its supported values.
```
Datadog
B3
B3 single header
```
It wouldn't be possible to configure `DD_PROPAGATION_STYLE_INJECT=B3 single header` correctly, so I left `DD_PROPAGATION_STYLE_*` as comma-separated only in this PR.
=> Support spaces in environment variable lists

Gemfile, Rakefile, docker-compose.yml, ext/ddtrace_profiling_native_extension/NativeExtensionDesign.md, ext/ddtrace_profiling_native_extension/extconf.rb, ext/ddtrace_profiling_native_extension/native_extension_helpers.rb, spec/datadog/core/configuration/components_spec.rb, spec/datadog/core/configuration_spec.rb, spec/datadog/profiling/integration_spec.rb, spec/datadog/profiling/native_extension_helpers_spec.rb, spec/datadog/profiling/native_extension_spec.rb, spec/datadog/profiling/pprof/builder_spec.rb, spec/datadog/profiling/pprof/stack_sample_spec.rb, spec/datadog/profiling/pprof/template_spec.rb, spec/datadog/profiling/spec_helper.rb, spec/datadog/profiling/transport/http/adapters/net_integration_spec.rb, spec/datadog/profiling/validate_benchmarks_spec.rb
[`libddprof`](https://github.com/DataDog/libddprof) is a Rust-based library that implements common functionality used by our profilers:
* aggregation of profiling data
* serialization of profiling data
* reporting of profiling data to backend
This PR adds the scaffolding to enable usage of libddprof from dd-trace-rb, **but does not yet make use of any of its functionality**.
Currently, libddprof works for all supported Rubies (2.1 to 3.2 dev) but only on x86-64 and 64-bit ARM Linux. The current integration has been set up in such a way that on other platforms we print a nice banner telling customers that they won't have profiling **but do not otherwise impact the customer in using all other Datadog products** (tracing, ci, appsec, ...).
This PR includes a nice refactoring + addition of …
=> [PROF-4779] Refactor in prepraration for use of libddprof from profiling native extension

lib/datadog/tracing/trace_operation.rb
Remove duplicated assignment. This should be a save change without behaviour change.
https://github.com/DataDog/dd-trace-rb/pull/2023/files#diff-cee994df96bef5c3cb8fb5c1b83ed6fa3e9d68abb5ba3207a031c1beb2d2e62dL100
=> Remove redundant events assignment

lib/datadog/core/configuration.rb, lib/datadog/tracing/sampling/priority_sampler.rb, lib/datadog/tracing/sampling/rule.rb, lib/ddtrace/transport/http/response.rb, sorbet/rbi/hidden-definitions/hidden.rbi, spec/datadog/profiling/transport/http/response_spec.rb, spec/ddtrace/transport/http/response_spec.rb
Following up on the work of #2025, this PR performs the refactoring necessary to remove the remaining usage of `Forwardable`.
No functional changes take place in this PR, it should be a strict refactor.
=> Refactor to remove usage of forwardable

benchmarks/profiler_submission.rb, lib/datadog/profiling/flush.rb, lib/datadog/profiling/recorder.rb, sorbet/rbi/hidden-definitions/hidden.rbi, spec/datadog/profiling/encoding/profile_spec.rb, spec/datadog/profiling/exporter_spec.rb, spec/datadog/profiling/flush_spec.rb, spec/datadog/profiling/recorder_spec.rb, spec/datadog/profiling/scheduler_spec.rb, spec/datadog/profiling/spec_helper.rb, spec/datadog/profiling/transport/client_spec.rb, spec/datadog/profiling/transport/http/client_spec.rb, spec/datadog/profiling/transport/io/client_spec.rb, spec/datadog/profiling/transport/request_spec.rb
As part of the ongoing refactoring work to report profiling data using libddprof, the `Flush` class is going to need to change its shape.
To enable incremental development of the new code side-by-side with the old code, let's rename the existing class to `OldFlush` so that the new code can take over its name.
Note that the existing Ruby profiler keeps working with the new class name! So this PR can be merged independently of any other libddprof-related PR :)
=> [PROF-4780] Temporarily rename Datadog::Profiling::Flush to OldFlush

lib/datadog/profiling.rb, lib/datadog/profiling/tag_builder.rb, spec/datadog/profiling/tag_builder_spec.rb
This module will be used by the new libddprof-based transport code to build the list of tags to be sent to the backend together with a profile.
Its behavior is a mix of both:
* https://github.com/DataDog/dd-trace-rb/blob/ee2a5eeddee2262ef94cca0a5aabd02439413103/lib/datadog/profiling/transport/http/api/endpoint.rb
* https://github.com/DataDog/dd-trace-rb/blob/ee2a5eeddee2262ef94cca0a5aabd02439413103/lib/datadog/profiling/flush.rb
Both of which I plan to remove in a later PR (which already exists -- https://github.com/DataDog/dd-trace-rb/pull/1924 -- but I kept it as a draft).
=> [PROF-4780] Add `TagBuilder` module for building tags to attach to profiles

.gitignore, Gemfile, ddtrace.gemspec, ext/ddtrace_profiling_native_extension/extconf.rb, ext/ddtrace_profiling_native_extension/native_extension_helpers.rb, lib/datadog/profiling.rb, lib/datadog/profiling/scheduler.rb, spec/datadog/core/configuration/components_spec.rb, spec/datadog/profiling/native_extension_helpers_spec.rb, spec/datadog/profiling/spec_helper.rb, spec/datadog/profiling_spec.rb
In #1885 we bootstrapped support for libddprof in ddtrace. This PR adds the final bits needed to make it an actual dependency of ddtrace.
This PR:
* Upgrades libddprof to 0.6.0.1.0 (latest release)
* Improves detection and error messages of setups we don't support
* Drops profiler support for macOS. The profiler support wasn't great on macOS already -- we only supported wall-clock and were missing cpu-time data. libddprof currently doesn't ship binaries for macOS, so we can't suport it anymore until that's changed.
* Adds a way to force-enable using libddprof on macOS, for profiling development, aka I use it myself. It does work on macOS, the main problem for restoring support is solving the libddprof macOS distribution story.
* Adds a way to record the specific reason why the profiling …
=> [PROF-4780] Add libddprof dependency to power the new Ruby profiler

ddtrace.gemspec
I've reviewed the latest version and it looks good <https://my.diffend.io/gems/debase-ruby_core_source/0.10.15/0.10.16>, and it even removes old 1.9 cruft.
=> Bump debase-ruby_core_source maximum version to latest version

README.md
Hyperlink it to https://rubygems.org/gems/ddtrace/
=> Fix gem badge in README

spec/datadog/tracing/workers_integration_spec.rb
See <https://github.com/DataDog/dd-trace-rb/runs/6503764102?check_suite_focus=true>
for a flaky run for this test.
A bunch of other tests on this file are already skipped on our macOS CI as flaky.
=> Tag another test in `workers_integration_spec.rb` as flaky on macOS

LICENSE-3rdparty.csv, ext/ddtrace_profiling_native_extension/clock_id_from_pthread.c, ext/ddtrace_profiling_native_extension/collectors_stack.c, ext/ddtrace_profiling_native_extension/extconf.rb, ext/ddtrace_profiling_native_extension/libddprof_helpers.h, ext/ddtrace_profiling_native_extension/private_vm_api_access.c, ext/ddtrace_profiling_native_extension/private_vm_api_access.h, ext/ddtrace_profiling_native_extension/profiling.c, ext/ddtrace_profiling_native_extension/stack_recorder.c, ext/ddtrace_profiling_native_extension/stack_recorder.h, lib/datadog/profiling.rb, lib/datadog/profiling/collectors/stack.rb, spec/datadog/profiling/collectors/stack_spec.rb, spec/datadog/profiling/stack_recorder_spec.rb
This PR adds the new `Stack` collector, which samples using the `rb_profile_frames` API.
Rather than using the `rb_profile_frames` API directly, it copy pastes it from the Ruby VM sources into the `private_vm_api_access.c` file. 
I claim license-wise this is OK since upstream Ruby allows the source code to be used under the terms of the BSD-2-Clause license, which I include in the file with the copied snippets as well as in the `LICENSE-3rdparty.csv` file as usual. I'll also run this through the internal opensource group, in case they have any notes/concerns.
Code-wise, here's a quick description of `rb_profile_frames` and why we need it:
`rb_profile_frames` is a Ruby VM debug API added for use by profilers for sampling the stack trace of a Ruby thread.
Its main other user is the …
=> [PROF-4904] First implementation of new Stack collector based on `rb_profile_frames` API

lib/datadog/appsec/contrib/sinatra/patcher.rb
This case happens if AppSec fails to initialise properly, e.g due to making the ruleset setting point to a nonexistent file.
Caught by system tests, this allows the corresponding system test case to be enabled.
=> Fix missing fallback for Sinatra

spec/datadog/appsec/processor_spec.rb
Processor being unreferenced means it can be garbage collected, which leads to the WAF handle being reaped while it is still needed.
This does not affect code in `lib` which properly retains `Processor` beyond `Context` lifespan.
See https://github.com/DataDog/libddwaf/issues/76
=> Fix processor spec segfault

.rubocop.yml, Gemfile, ext/ddtrace_profiling_native_extension/NativeExtensionDesign.md, ext/ddtrace_profiling_native_extension/collectors_stack.c, ext/ddtrace_profiling_native_extension/extconf.rb, ext/ddtrace_profiling_native_extension/libddprof_helpers.h, ext/ddtrace_profiling_native_extension/private_vm_api_access.c, ext/ddtrace_profiling_native_extension/private_vm_api_access.h, ext/ddtrace_profiling_native_extension/stack_recorder.c, ext/ddtrace_profiling_native_extension/stack_recorder.h, lib/datadog/profiling/collectors/stack.rb, lib/datadog/profiling/stack_recorder.rb, spec/datadog/profiling/collectors/interesting_backtrace_helper.rb, spec/datadog/profiling/collectors/stack_spec.rb, spec/datadog/profiling/stack_recorder_spec.rb, spec/datadog/profiling/tasks/exec_spec.rb
The new stack collector introduced in #1966 gets feature-complete in this PR.
By feature-complete I mean:
* There is extensive test coverage with many corner cases being checked
* Our custom `rb_profile_frames` got quite a lot of fixes to exactly match the Ruby reference stack trace api (`Thread#backtrace_locations`)
* It works for all supported Rubies, including 2.1 and 2.2 which were a though nut to crack
* It matches the behavior of the old profiling codepaths, e.g. it has placeholders for threads with empty stacks that are running in native code and for threads with too deep stacks
* etc...
I don't quite like how long and how complex this PR got. Thanks for putting up with it 😅 , and feel free to challenge me if this should be further broken down. Reviewing it commit-by-commit may …
=> [PROF-4904] New Stack collector is feature-complete

spec/datadog/core/configuration_spec.rb, spec/datadog/core/diagnostics/environment_logger_spec.rb, spec/datadog/profiling/integration_spec.rb, spec/datadog/profiling/native_extension_spec.rb, spec/support/log_helpers.rb
I really dislike extra noise during RSpec runs, so here's a bunch of tiny fixes to prevent profiling-related logs that had escaped my earlier attempts :)
=> Reduce profiling log noise during test suite execution

lib/datadog/tracing/contrib/action_pack/action_controller/instrumentation.rb, spec/datadog/tracing/contrib/rails/action_controller_spec.rb
In environments where tracing is disabled, Datadog spits out a lot of
unnecessary error logs here, due to the instrumentation assuming that
there's an active trace to maintain.
This fix is in the same vein as #1943 and #1945.
```
E, [2022-05-17T22:15:02.337370 #2639] ERROR -- ddtrace: [ddtrace] (/home/circleci/tmp/vendor/bundle/ruby/3.1.0/gems/ddtrace-1.0.0/lib/datadog/tracing/contrib/action_pack/action_controller/instrumentation.rb:43:in `rescue in start_processing') undefined method `resource=' for nil:NilClass
trace.resource = span.resource
^^^^^^^^^^^
E, [2022-05-17T22:15:02.340414 #2639] ERROR -- ddtrace: [ddtrace] (/home/circleci/tmp/vendor/bundle/ruby/3.1.0/gems/ddtrace-1.0.0/lib/datadog/tracing/contrib/action_pack/action_controller/instrumentation.rb:79:in `rescue in …
```
=> Prevent `action_controller` tracing when disabled

ext/ddtrace_profiling_native_extension/collectors_stack.c, ext/ddtrace_profiling_native_extension/ruby_helpers.h, ext/ddtrace_profiling_native_extension/stack_recorder.c
After fixing the VM interruptions issue for `HttpTransport` in 4cd898e829d34f994973452e4503a88d37b4f99c (#1923), I suspected that the same issue could happen to the `StackRecorder`.
It took a few attempts to reproduce this issue, but the easiest way seems to be to "send ctrl+c to itself" by adding
```c
#include <signal.h>
kill(getpid(), SIGINT);
```
before the call to `rb_thread_call_without_gvl2`.
This made the VM flag an interrupt, which as long as no exception was raised (and RSpec has its own interrupt handler) simulated the issue.
TL;DR `rb_thread_call_without_gvl2` can return BEFORE running our code when the VM has a pending interruption, so we need to let the VM do its work, but there's no reason to fail the action (in this case, fail to serialize) if all the VM wants is to run …
=> Handle VM interruptions during `StackRecorder` serialization instead of failing

docs/GettingStarted.md
Fix some malformed markdown. `|` need to be escaped in order to be rendered. The issue can be observed here: https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md#sidekiq in the default value for `error_handler`
=> Fix malformed markdown

.github/workflows/draft-release-on-release-branch-push.yaml
Whenever we start a release, we push a branch called `bump_to_version_x.y.z`, where `x.y.z` is the full version version we intend on releasing. Here's an example for [1.1.0](https://github.com/DataDog/dd-trace-rb/pull/2046) (branch is already deleted).
This PR creates a draft GitHub release in the [Releases section](https://github.com/DataDog/dd-trace-rb/releases) of `dd-trace-rb` containing a draft Changelog with from all the closed PRs for the milestone matching the branch name (Milestone named `x.y.z` in this example).
This Changelog still needs to be curated, but it's very helpful as a starting point. It can be also used to fill out the `Changelog.md` entry for the release at hand.
I've actually used this GH Action in the last release, …
=> Actions: Create draft release on release branch push

CONTRIBUTING.md
We currently have a developer guide file in a standard location (`CONTRIBUTING.md`), but have valuable developer information in `docs/DevelopmentGuide.md`.
This PR links to `docs/DevelopmentGuide.md` from `CONTRIBUTING.md`, in order to make it discoverable.
Overall, I think we might want to refactor these documentations, but I'm not 100% sure what that looks like, so I'm proposing this small improvement for now.
Thanks to @seuros for bringing this to our attention.
=> Link to DevelopmentGuide.md from CONTRIBUTING.md

lib/datadog/tracing/sampling/rate_sampler.rb, lib/datadog/tracing/sampling/span/matcher.rb, spec/datadog/tracing/sampling/span/matcher_spec.rb
This PR adds the first class that will support work to allow users to set sampling decisions on individual spans.
These single span sampling decisions can override the trace level sampling decision when the trace level decision is to drop the trace. This allows users to keep important spans, especially the ones used to calculate business metrics or perform aggregated reports in their Datadog App.
The specific mechanisms for how flushing and tagging work will be implemented later. This PR only creates a pattern matcher.
This matcher processes a simple matching language and matches the provided patterns with a SpanOperation.
=> [Single Span Sampling] Add single span matcher

README.md
The old `http://gems.datadoghq.com/trace/docs/` link does not seem to load for me on firefox nor chrome. I can see it with curl though...
I suspect this may be related to modern browsers trying to get to an https version of the site, which doesn't work.
Instead, I've replaced the link with one that works over https and seems to be working fine. In the future if/when we fix https support for `gems.datadoghq.com` directly we can go back to the old url :)
Fixes #2057
=> Fix docs link not working

ext/ddtrace_profiling_loader/ddtrace_profiling_loader.c, ext/ddtrace_profiling_native_extension/clock_id.h, ext/ddtrace_profiling_native_extension/clock_id_from_pthread.c, ext/ddtrace_profiling_native_extension/clock_id_noop.c, ext/ddtrace_profiling_native_extension/extconf.rb, ext/ddtrace_profiling_native_extension/private_vm_api_access.c, ext/ddtrace_profiling_native_extension/private_vm_api_access.h, ext/ddtrace_profiling_native_extension/ruby_helpers.h
A new `struct rb_native_thread` was introduced to contain the `thread_id` (see  https://github.com/ruby/ruby/pull/5836) and thus we need to add a ifdef for Ruby 3.2.
Fixes #2065
(Note: We don't yet have Ruby 3.2 in our CI setup, so you'll just have to take my word for it that this makes it compile now! Or try it locally on your own machine :P)
=> Fix profiler not building on ruby-head (3.2) due to VM refactoring

lib/datadog/profiling/ext/forking.rb, spec/datadog/profiling/ext/forking_spec.rb
Since we're adding a method to `Kernel`, I've decided to namespace the method just in case we cause any collisions OR it's confusing to users where this method is coming from.
=> Rename `at_fork_blocks` ➡️ `ddtrace_at_fork_blocks`

ext/ddtrace_profiling_native_extension/extconf.rb, ext/ddtrace_profiling_native_extension/native_extension_helpers.rb
To avoid impacting customers, whenever we detect an issue which would've led to the profiling native extension compilation to fail, we instead skip the compilation.
This ensures that customers (especially those *not* using profiling) don't get impacted at installation time.
Instead, at execution time, if they do try to enable profiling, they'll get a message such as
```
WARN -- ddtrace: [ddtrace] Profiling was requested but is not supported,
profiling disabled: Your ddtrace installation is missing support for the
Continuous Profiler because there was a problem in setting up the
libddprof dependency. For help solving this issue, please contact
Datadog support at https://docs.datadoghq.com/help/.
```
But while investigating one such issue reported by a customer …
=> Add env var for debugging profiling native extension compilation issues + Log `PKG_CONFIG_PATH` to mkmf.log

integration/apps/rails-six/Gemfile
- Rails 6.1.6 is out, fixing an issue with ActionMailer.
- Newer versions of some gems fail to install on Ruby 2.5, this also addresses those.
=> Fix rails-six integration app gems with Ruby 2.5

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
This PR adds a first version of Github issue templates.
The goal is to have this in place, as opposed to no template 🙂, in order to help users get their issues addressed faster.
You can create as many issues as you'd like in my personal fork, which has this templated enabled: https://github.com/marcotc/dd-trace-rb/issues/new/choose
This is what users will see when they click the "New issue" button:
Here's an example on how a brand bug report comes out:
https://github.com/marcotc/dd-trace-rb/issues/11
And brand new feature request:
https://github.com/marcotc/dd-trace-rb/issues/12
This is not meant to be the end-all of all issue templates, but it's helpful to remove a bit of back and forth when a new issue is opened.
=> Github: Add issue templates

docs/GettingStarted.md, lib/datadog/tracing/contrib/rest_client/configuration/settings.rb, lib/datadog/tracing/contrib/rest_client/request_patch.rb, spec/datadog/tracing/contrib/rest_client/request_patch_spec.rb
Rest Client didn't know about this option, and now it does! This should bring it closer to parity with the other external HTTP request library integrations.
=> Teach Rest Client integration the `:split_by_domain` option

docs/GettingStarted.md, lib/datadog/tracing/contrib/rails/configuration/settings.rb, lib/datadog/tracing/contrib/rails/framework.rb
Supporting this means I don't need to add and hacky overrides
=> Allow passing request_queuing option to Rack through Rails tracer

spec/datadog/tracing/tracer_spec.rb
We likely forgot to remove this test when we did #1891 because it's currently skipped in CI.
=> Test:Remove leftover from Span#allocations removal

.rubocop.yml
`Gemspec/DateAssignment` was integrated into `Gemspec/DeprecatedAttributeassignment` in rubocop 1.31.0 (released today).
Updated `rubocop.yml` based on changelog [here](https://github.com/rubocop/rubocop/blob/master/CHANGELOG.md)
=> Update rubocop.yml to use Gemspec/DeprecatedAttributeAssignment

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
I'd like to thank @marcotc for adding the issue templates in #2090!
Here's a few more tweaks inspired from the [issue templates](https://github.com/DataDog/libdatadog/tree/main/.github/ISSUE_TEMPLATE) we have for `libdatadog`.
For the bug report template:
* Mention log messages and screenshots in "steps to reproduce"   suggestions
* Add a "How does ddtrace help you" section. This helps us to know more about the customer's use case, and also gives some space for customers to hopefully tell us what we're doing well
For the feature request template:
* Add a few sections to guide the feature request.
=> Tweaks to GitHub issue templates

spec/datadog/tracing/tracer_spec.rb
The `shared_context` is obsolete and not been referenced.
Remove it
=> Remove obsolete shared_context

.github/PULL_REQUEST_TEMPLATE.md
Adds a link to https://github.com/DataDog/dd-trace-rb/blob/master/docs/DevelopmentGuide.md to the PR template, to help developers test and clean up their code.
Also, expand the language around testing requirements for the PR
=> GH: Expand on PR template with link to docs

lib/datadog/core/utils.rb, lib/datadog/tracing/span.rb
Fix a TODO by making sure span and trace IDs are greater than zero. 
**Motivation**
The Agent [drops IDs == 0](https://github.com/DataDog/datadog-agent/blob/main/pkg/trace/agent/normalizer.go#L42-L49), in the unlikely case random returns zero we would drop that span/trace.
=> Span and trace IDs should not be zero

lib/datadog/opentracer/thread_local_scope_manager.rb, lib/datadog/tracing/context_provider.rb
I stumbled upon this flaky error: https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/6331/workflows/02b56e62-53d7-4d50-ac12-f3e84194bf8f/jobs/234310/parallel-runs/1
```
Failures:
1) Datadog::Tracing::FiberLocalContext#initialize create one fiber-local variable
Failure/Error: expect { fiber_local_context }.to change { Thread.current.keys.size }.by(1)
expected `Thread.current.keys.size` to have changed by 1, but was changed by 0
```
It happens because we use `object_id` as a thread local key and `object_id` can be reused after garbage collection, causing collision between a recently garbage collected instance of `FiberLocalContext` and a new one.
This PR addresses this issue in two places where we use `object_id` as a thread local key by creating a thread-safe counter for each of …
=> Fix object_id usage as thread local key

lib/datadog/core/telemetry/collector.rb, lib/datadog/core/telemetry/event.rb, spec/datadog/core/telemetry/collector_spec.rb, spec/datadog/core/telemetry/event_spec.rb, spec/datadog/core/telemetry/v1/shared_examples.rb
Continuing from #2102, this PR adds an `Event` class to construct a telemetry request event based on the `request_type`. Currently only `app-started` is implemented.
**Motivation**
This event class ensures that we are constructing a well-formed telemetry request object.
Some questions:
- Does it make sense to allow users to pass in an `api_version` if the only supported version right now is `v1`?
- Should a new `Event` class be instantiated each time a telemetry request needs to be made (i.e. does it make more sense to have the initialization return a `TelemetryRequest` object and to remove the `telemetry_request` function)? Or does this make more sense as a module and not a class?
Unit tests were added to test the …
=> Create Telemetry Event class

lib/datadog/tracing/metadata/tagging.rb
Fixes https://github.com/DataDog/dd-trace-rb/issues/2075
I respect that you may not want to do this, but I think this would be a pretty practical and ergonomic improvement to the span interface.
=> Add convenient interface for getting and setting tags using `[]` and `[]=` respectively.

.circleci/config.yml, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, .rubocop.yml, docs/GettingStarted.md, lib/datadog/core/configuration/settings.rb, lib/datadog/core/environment/platform.rb, lib/datadog/core/utils.rb, lib/datadog/opentracer/thread_local_scope_manager.rb, lib/datadog/tracing/context_provider.rb, lib/datadog/tracing/contrib/rails/configuration/settings.rb, lib/datadog/tracing/contrib/rails/framework.rb, lib/datadog/tracing/contrib/rest_client/configuration/settings.rb, lib/datadog/tracing/contrib/rest_client/request_patch.rb, lib/datadog/tracing/sampling/rate_sampler.rb, lib/datadog/tracing/sampling/span/ext.rb, lib/datadog/tracing/sampling/span/rule.rb, lib/datadog/tracing/span.rb, spec/datadog/core/environment/platform_spec.rb, spec/datadog/tracing/contrib/rest_client/request_patch_spec.rb, spec/datadog/tracing/sampling/span/rule_spec.rb, spec/datadog/tracing/tracer_spec.rb
Follow up to #2055
This PR adds a sampling rule that applies a sampling rate (between 0% and 100% sampling) to a single span operation.
This rate is only applied if the provided matcher, introduced in #2055, is satisfied.
Additionally, a rate limiter (spans/sec limit) is applied to spans that satisfy both the matcher and sampling rate.
If the span is kept after all these checks, a few metrics are set in the span to let the Datadog App downstream know how the sampling happened: this allows it to adjust rates reported in the App despite receiving only a subset of the spans. It also allows users to know how much rate limiting is affecting their observability.
Also a reminder that the concept of "Single Span Sampling" only applies to spans that are part of traces that were dropped at …
=> [Single Span Sampling] Add single span sampling rule

lib/datadog/tracing/sampling/rate_limiter.rb, lib/datadog/tracing/sampling/span/matcher.rb, lib/datadog/tracing/sampling/span/rule.rb, lib/datadog/tracing/sampling/span/rule_parser.rb, spec/datadog/tracing/sampling/rate_limiter_spec.rb, spec/datadog/tracing/sampling/span/rule_parser_spec.rb
Follows up from #2091 
This PR parses user provided JSON rules into `Datadog::Tracing::Sampling::Span::Rule` objects.
The code ensures that no errors are propagated back to the user in the form of an exception, but all errors are logged to aid in addressing them.
In the future, we'll likely support parsing this data directly from YAML or a global `datadog.conf` JSON, thus a non-JSON specific method, `parse_list`, is also provided in additional to the main `parse_json` method.
A few other changes:
* The `TokenBucket` now is more strict about its inputs, which helps the validation of Single Span sample rules.
* Equality helpers were added to `Rule` and `Matcher` to ease testing.
=> [Single Span Sampling] Add single span parser

README.md
Add a note of thanks to Mike on the project README.
**Motivation**
We've long been in talks to adopt the `datadog` gem name for future projects, but an issue was that the name was already taken on rubygems.org .
@miketheman was awesome in allowing us to get that name, and all he asked in return was that his contribution not be forgotten, which is extremely fair :)
So, let's thank him! And good luck for current/future endeavors!
P.s.: In the future, if/when we create a repository for the `datadog` gem, let's remember to keep these thanks there as well!
=> Add thanks to @miketheman for gifting us access to the `datadog` gem

Gemfile, ext/ddtrace_profiling_native_extension/extconf.rb, ext/ddtrace_profiling_native_extension/native_extension_helpers.rb, integration/apps/rack/Dockerfile, integration/apps/rack/Gemfile, spec/datadog/profiling/native_extension_helpers_spec.rb
As reported in #2067, in these environments ddtrace (and libddprof) are moved after installation, which broke linking from the profiling native extension to libddprof.
As a fix/"workaround", we additionally add the relative path between both gems while linking; see the comments on the `.libddprof_folder_relative_to_native_lib_folder` helper for more details and how this works.
Note that key word above is **aditionally** -- e.g., we're adding more paths in which to find libddprof, and keeping the existing absolute path, so this should not impact any setups where things were already working fine.
Fixes #2067
**Motivation**
Make sure profiling is usable in all environments and deployment styles used by customers.
I had to do some unrelated …
=> [PROF-5747] Fix broken libddprof linking on Heroku and AWS Elastic Beanstalk

lib/datadog/tracing/sampling/span/sampler.rb, lib/datadog/tracing/tracer.rb, spec/datadog/tracing/sampling/span/sampler_spec.rb, spec/datadog/tracing/tracer_spec.rb
Follow up from #2095 
This PR adds a new Single Span Sampling class that ties up all the previous Single Span Sampling work.
This class alters span tags when spans are finished, based on the provided rules.
At this moment, this is functionally a no-op, as the interface to configure rules will be done in a following PR.
=> [Single Span Sampling] Span Sampler

lib/datadog/core/configuration/components.rb, lib/datadog/core/telemetry/client.rb, lib/datadog/core/telemetry/event.rb, spec/datadog/core/configuration/components_spec.rb, spec/datadog/core/telemetry/client_spec.rb, spec/datadog/core/telemetry/event_spec.rb
This PR implements the `app-closing` event when a `shutdown` event occurs. There is no required payload for this event type.
**Motivation**
This event is one of the ones specified in the [telemetry spec](https://github.com/DataDog/instrumentation-telemetry-api-docs/blob/main/GeneratedDocumentation/ApiDocs/v1/producing-telemetry.md#app-closing).
Unit tests were added to cover the relevant changes.
=> Send telemetry app-closing event on shutdown

lib/datadog/tracing/span.rb, lib/datadog/tracing/span_operation.rb, lib/datadog/tracing/trace_operation.rb, spec/datadog/tracing/span_operation_spec.rb, spec/datadog/tracing/trace_operation_spec.rb, spec/support/span_helpers.rb
`top_level_hits` is one of the computed stats required to be collected, hence `top_level` span is required to be identified. 
The logic of a span qualified to be a `top_level` span.
1. root span of the current thread
2. `span.service` is different from its immediate parent's service 
The definition of `top_level` is interchangable with `service_entry` as stated from [public documentation](https://docs.datadoghq.com/tracing/visualization/#service-entry-span).
> A span is a service entry span when it is the entrypoint method for a request to a service. You can visualize this within Datadog APM when the color of the immediate parent on a flame graph is a different color. Services are also listed on the right when viewing a flame graph.
The `service_entry` attribute is kept private, since we …
=> Implement private attributes `service_entry` for span

.circleci/config.yml
This PR changes the RSpec output format in CircleCI from 
```
........
```
to
```
gRPC integration test
multiple client configurations
uses the correct configuration information
request reply
behaves like associates child spans with the parent
is expected to eq 4465632251790005042
behaves like a peer service span
contains peer hostname tag
contains peer service tag
client stream
behaves like associates child spans with the parent
is expected to eq 1213191866811280859
behaves like a peer service span
contains peer hostname tag
contains peer service tag
```
This allows us to debug hung jobs, like https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/6554/workflows/201f8b0c-d745-4681-92e3-2a9bead2a0b3/jobs/242672/parallel-runs/17?filterBy=ALL.
=> CI:RSpec documentation format to debug hung tests

ext/ddtrace_profiling_native_extension/extconf.rb, ext/ddtrace_profiling_native_extension/native_extension_helpers.rb, spec/datadog/profiling/native_extension_helpers_spec.rb
Add a better error message to be presented to customers when `pkg-config` is not installed. (See below for example)
**Motivation**
In #2068 a customer reported that they were not getting profiling with the message:
> Profiling was requested but is not supported, profiling disabled: Your ddtrace installation is missing support for the Continuous Profiler because there was a problem in setting up the libddprof dependency.
After investigating this issue (and adding extra tools to debug it, see #2069) it turns out that the customer was missing the `pkg-config` tool.
This tool is currently invoked indirectly via Ruby's `mkmf` helper, and is used to configure linking to libddprof/libdatadog.
I must admit I was surprised that there's not better error logging in `mkmf` …
=> [PROF-5748] Improve error message when pkg-config tool is not installed

spec/ddtrace/transport/trace_formatter_spec.rb, spec/support/span_helpers.rb
While using the `have_metadata` RSpec custom helper, I noticed it was working as I expected.
It was always returning "match", regardless of the expectation provided.
Turns out it's because the matcher argument is positional, not keyword as we previously had:
```diff
-  RSpec::Matchers.define :have_metadata do |**tags|
+  RSpec::Matchers.define :have_metadata do |tags|
```
The argument supported is also always a single Hash argument.
This PR addresses that.
In fixing this, one test was shown to be incorrect: https://github.com/DataDog/dd-trace-rb/blob/017624521d2f73643be30a5ee41e48a226a4dea1/spec/ddtrace/transport/trace_formatter_spec.rb#L147-L155
This happened because the subject under test (`format!`) is invoked in an outer `before` block, and thus executed before this test's `before` …
=> Fix have_metadata RSpec helper

spec/ddtrace/benchmark/telemetry_spec.rb
Adds a simple benchmarking test to compare the time it takes to run a configure block with telemetry enabled vs. without. 
There seems to be quite a bit of variance between test runs:
**Motivation**
Comparing performance is important to ensure we're not adding a lot of overhead by sending telemetry requests
I also ran these tests in a rails app to test behavior with requests being sent via the agent:
```
with telemetry enabled:
user       system     total        real
#app-started                     0.002635   0.004334   0.006969 (  0.330376)
#integrations-change             0.003728   0.000769   0.004497 (  0.208753)
without telemetry:
user       system     total        real
#app-started                     0.000000   0.001966   0.001966 ( …
```
=> Add simple benchmark test for telemetry

lib/datadog/tracing/metadata/ext.rb, lib/datadog/tracing/span.rb, spec/datadog/tracing/span_spec.rb
This PR is the first step towards early top level detection in the tracer.
As a preamble, the definition of top-level span is:
> A span is defined as a top level if any of the following are true:
> * It’s a root span
> * Its parent has a different service
> * It’s a local root in a distributed trace (local root of flushed trace in an agent)
After the introduction of the `service_entry` attribute in #2080, now know how to calculate the effective top-level spans in a trace, [exactly how the agent does](https://github.com/DataDog/datadog-agent/blob/b4542cc65a1289cfe72903e52c9ed4d219d6453b/pkg/trace/traceutil/trace.go#L116-L132). Both the tracer and agent must follow the definition in previous paragraph.
[For every trace received, the agent calculate the top-level spans and tags them with …
=> Compute top-level span in tracer

lib/datadog/core/telemetry/client.rb, lib/datadog/core/telemetry/emitter.rb, lib/datadog/core/telemetry/http/adapters/net.rb, spec/datadog/core/telemetry/client_spec.rb, spec/datadog/core/telemetry/emitter_spec.rb, spec/datadog/core/telemetry/http/adapters/net_spec.rb
To protect against older agent versions that do not support telemetry, when the requested path is not found, set `@unsupported=true` in the `Client` and disable future telemetry events. Additionally, this changes all log levels related to telemetry to `debug` rather than `info`.
**Motivation**
These changes were made to prevent errors from telemetry causing unnecessary info logs from being logged.
Unit tests were added to test the new expected behavior
=> Add unsupported flag for telemetry

ddtrace.gemspec, ext/ddtrace_profiling_loader/ddtrace_profiling_loader.c, ext/ddtrace_profiling_native_extension/NativeExtensionDesign.md, ext/ddtrace_profiling_native_extension/extconf.rb, ext/ddtrace_profiling_native_extension/http_transport.c, ext/ddtrace_profiling_native_extension/native_extension_helpers.rb, ext/ddtrace_profiling_native_extension/stack_recorder.c, lib/datadog/profiling/http_transport.rb, spec/datadog/profiling/http_transport_spec.rb, spec/datadog/profiling/native_extension_helpers_spec.rb, spec/datadog/profiling/spec_helper.rb, spec/datadog/profiling/stack_recorder_spec.rb
The `libddprof` dependency has been renamed `libdatadog`.
This PR updates dd-trace-rb to use the new version, including a few API changes from the 0.6 to 0.7 release.
I'm marking this PR as a draft because the only `libdatadog` version right now is `0.7.0.1.0.rc1` and I want to avoid releasing a rc1 to customers. Once the final 0.7.0 release hits, we just need to change the `gemspec` and merge.
=> Replace `libddprof` dependency with `libdatadog`, and upgrade to 0.7.0

Rakefile, docs/GettingStarted.md, ext/ddtrace_profiling_native_extension/collectors_stack.c, ext/ddtrace_profiling_native_extension/extconf.rb, ext/ddtrace_profiling_native_extension/native_extension_helpers.rb, ext/ddtrace_profiling_native_extension/private_vm_api_access.c, ext/ddtrace_profiling_native_extension/private_vm_api_access.h, ext/ddtrace_profiling_native_extension/stack_recorder.h, integration/apps/rack/spec/integration/basic_spec.rb, integration/images/include/build_ddtrace_profiling_native_extension.rb, lib/datadog/profiling/stack_recorder.rb, spec/datadog/profiling/collectors/old_stack_spec.rb, spec/datadog/profiling/http_transport_spec.rb, spec/datadog/profiling/native_extension_helpers_spec.rb, spec/datadog/profiling/spec_helper.rb
This PR remove support for profiling Ruby 2.1 using the Continuous Profiling product. Other products shipped in ddtrace (tracing, application security monitoring, CI, etc) are unaffected.
This dropping of support does not impact our customer's ability to install the latest dd-trace-rb on Ruby 2.1. What it does is
1. Skip compilation of the profiling native extension on Ruby 2.1
2. Print a warning message when customers try to enable profiling on Ruby 2.1 (but does not otherwise block or break their application)
The warning message shown to customers is:
> W, [2022-07-08T14:08:51.295193 #51899]  WARN -- ddtrace: [ddtrace] Profiling was requested but is not supported, profiling disabled: Your ddtrace installation is missing support for the Continuous Profiler …
=> [PROF-5774] Remove support for profiling Ruby 2.1

lib/datadog/profiling/ext/forking.rb, spec/datadog/profiling/ext/forking_spec.rb
This PR includes a handful of small cleanups to the `Forking` monkey patch. I suggest reviewing it commit-by-commit.
This part of the code hasn't been touched in a while but a customer ran into an issue where the `Process.daemon` API (which also triggers `fork`) is skipping the `Forking` monkey patch.
While investigating the issue, I ended up going in and adding a number of comments and cleanups. I'll submit the actual fix separately.
There's existing test coverage for this feature, and it's still passing.
=> [PROF-4756] Cleanups for profiling `Forking` monkey patch

spec/datadog/profiling/collectors/old_stack_spec.rb, spec/datadog/profiling/native_extension_spec.rb
*cof* *ahem* now that I got your attention, some of the specs using `Process.detach` really were leaving behind "zombie" forked processes that never terminated.
I've reviewed all uses of this API and re-ran the test suite both on Linux as well as macOS to ensure no zombie processes are left behind.
P.s.: I could not resist the PR title :)
---
Makes sure no "zombie" processes are left behind after executing the test suite.
I do not look forward to the zombie apocalypse. I only know computers, which would become quite useless.
I am not available for birthday party bookings.
Run the full test suite, and then run `ps aux | grep ruby` and `ps aux | grep rspec` to guarantee that no processes are left …
=> [PROF-5793] I unleashed the zombie apocalypse when running our test suite

lib/datadog/profiling/ext/forking.rb, spec/datadog/profiling/ext/forking_spec.rb
Simplify the profiling `Forking` monkey patch, by removed the unused `:prepare` and `:parent` stages for callbacks.
The profiling `Forking` monkey patch only has a single customer: the `Datadog::Profiling::Tasks::Setup` class, which uses it to add an `at_fork(:child)` that takes care of restarting the profiler and fixing up the thread ids after a fork happened.
Since the `Forking` monkey patch affects core Ruby classes, I decided to simplify it, as we're not using the added complexity, and I prefer it being as simple as possible.
My additional motivation is that I'm working on support for monkey patching `Process.daemon`, and this simplifies the amount of code and tests needed to implement the needed functionality.
(We can always undo this if …
=> [PROF-4756] Simplify profiling `Forking` monkey patch, making it less generic

lib/ddtrace/transport/ext.rb, lib/ddtrace/transport/http.rb, spec/ddtrace/transport/http_spec.rb
Follow up from #2137.
This PR lets the Agent know that the tracer has calculated top-level spans and tagged them appropriately.
**This prevents partially flushed trace segments from being considered top-level, which used to create incorrect metrics and increase the resource name cardinality for the affected service name.**
Any value can be set in the HTTP header. The agent simply checks if it's not empty.
(If you are still confused, the description of #2137 has all the information regarding this and the previous PR)
=> Tell agent to trust tracer top-level span tagging

lib/datadog/tracing/pipeline/span_filter.rb, spec/datadog/tracing/pipeline/span_filter_spec.rb
Addresses #2038 
`SpanFilter` attempts to drop all descendant spans for any span targeted by the filter. To do this efficiently, it depends upon the spans to be ordered in a particular way in the trace span array: parent-to-child.
In 1.x, this ordering reversed, thereby breaking the filter.
As a partial solution, this PR simply reverse iterates the span array, applying the same logic. This should address most of the old behavior, however, it is still an incomplete solution, since it is still order dependent, just the opposite now. Furthermore, it's actually impossible for `SpanFilter` to work effectively if a trace is ever flushed in smaller segments, as is often the case in partial flushing.
In short, this a workaround to try to restore previous 0.x behavior in most cases. It needs …
=> Drop spans for child-to-parent ordered traces in SpanFilter

lib/datadog/profiling/tag_builder.rb, spec/datadog/profiling/tag_builder_spec.rb
Ensure that the tags passed on to the profiling `HttpTransport` are always strings.
A customer reported having their profiles fail with the following issue:
> Unable to report profile. Cause: wrong argument type nil (expected String) Location: /var/cache/bundle/ruby/3.0.0/gems/ddtrace-1.2.0/lib/datadog/profiling/http_transport.rb:115:in _native_do_export'
Unfortunately there's a bunch of data passed in to that function so just from that information it's not possible to be 100% sure which one was `nil`, but while doing a second pass at the code I noticed one way to trigger this would be to have tags that are `nil`.
Issue #2151
* Unit tests are included
* To trigger the issue manually, you can use …
=> Ensure all tags are strings when reporting profile

ext/ddtrace_profiling_native_extension/NativeExtensionDesign.md, ext/ddtrace_profiling_native_extension/collectors_stack.c, ext/ddtrace_profiling_native_extension/http_transport.c, ext/ddtrace_profiling_native_extension/libddprof_helpers.h, ext/ddtrace_profiling_native_extension/ruby_helpers.c, ext/ddtrace_profiling_native_extension/ruby_helpers.h
While investigating #2151, I realized that `Check_Type`'s error message: `TypeError: wrong argument type nil (expected String)` is very hard to debug in functions that do many `Check_Type` verifications (such as `_native_do_export`).
To fix this, I've created a new `ENFORCE_TYPE` helper which behaves similarly, but generates error messages such as:
```
TypeError: wrong argument nil for 'pprof_file_name' (expected a RUBY_T_STRING) at ../../../../ext/ddtrace_profiling_native_extension/http_transport.c:280:in `_native_do_export'
```
Hopefully this message will help us get to the bottom of the issue.
I've modified every other use of `Check_Type` in the profiling native extension to use this new helper, in case we need to debug similar issues in the …
=> [PROF-5808] Add `ENFORCE_TYPE` as user-friendly alternative to `Check_Type`

lib/datadog/profiling/ext/forking.rb, lib/datadog/profiling/scheduler.rb, spec/datadog/profiling/ext/forking_spec.rb
Extend the `Forking` monkey patch to also cover the `Process.daemon` API (that is another way of forking a Ruby process).
When the Ruby VM `fork`s, only the thread that called `fork` survives in the child process.
Thus, we have the `Forking` monkey patch which allows us to run callbacks in the child process, including restarting the profiler.
But there's a less known API in Ruby that also makes use of forking -- `Process.daemon`. One example of using this API is when calling `rails server -d`; that `-d` makes Rails call this API.
Because we were missing monkey patching `Process.daemon`, the profiler would not restart on `Process.daemon`. A customer using exactly `rails server -d` ran into this issue.
This PR is on top of …
=> [PROF-4756] Fix profiler not restarting on `Process.daemon`

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time.c, lib/datadog/core/configuration/components.rb, lib/datadog/core/utils/time.rb, lib/datadog/profiling/ext.rb, spec/datadog/profiling/collectors/cpu_and_wall_time_spec.rb, spec/datadog/profiling/collectors/stack_spec.rb, spec/datadog/profiling/spec_helper.rb, spec/datadog/profiling/stack_recorder_spec.rb
This PR adds the `thread id` label to profiler samples taken using the new `CpuAndWallTime` collector. This behavior already existed for the pure-Ruby `OldStack` collector, I'm just reimplementing it in the profiling native extension. 
Also adds a new helper that is useful when asserting on pprof data, and refactors a few specs to make use of the new helper instead of duplicating pprof parsing code.
Have the profiling native extension reach feature parity with the `OldStack` collector.
In a previous PR, we added a `per_thread_context` structure that can store information for each thread being sampled.
The first bit of information being stored there is the `thread id`, which we will also use to tag all samples with the thread …
=> [PROF-4902] Include 'thread id' label when sampling threads

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time.c, ext/ddtrace_profiling_native_extension/extconf.rb, ext/ddtrace_profiling_native_extension/private_vm_api_access.c, ext/ddtrace_profiling_native_extension/private_vm_api_access.h, spec/datadog/profiling/collectors/cpu_and_wall_time_spec.rb
Adds support for gathering thread names during profiling.
I've wanted to support this extra tiny feature for quite a while now: gathering the thread names, not just their IDs.
We already have this feature for the Java and Python profilers, and I like it quite a lot.
This feature is only being added on the profiling native extension, it won't show up for customers for now since we haven't wired it up for use yet.
This change includes test coverage.
=> [PROF-4902] Gather thread name during sampling

.rubocop.yml, ddtrace.gemspec
While researching how to enforce `require_relative` with Rubocop, I stumbled upon the [Rubocop extension "RuboCop Packaging"](https://docs.rubocop.org/rubocop-packaging/index.html). This extension ensures we are being good citizens in the way we package our gem.
Turns out, there are a few improvements to be made.
But as I turned on this new cop, I noticed that `ddtrace.gemspec` was excluded from Rubocop currently, and it needed a bit of work just to get it to comply with our current cops.
This PR does just that. A follow up PR will add "RuboCop Packaging" and only includes changes related to the new cops added by it.
=> Lint:ddtrace.gemspec

ddtrace.gemspec
Remove non-utf8 character in gemspec
**Motivation**
It breaks some old versions of bundler
=> Remove non-utf8 character in gemspec

.rubocop.yml, Rakefile, lib/datadog/appsec/contrib/rails/patcher.rb, lib/datadog/appsec/contrib/sinatra/patcher.rb, lib/datadog/appsec/reactive/operation.rb, lib/datadog/ci/ext/environment.rb, lib/datadog/core/configuration/agent_settings_resolver.rb, lib/datadog/core/diagnostics/environment_logger.rb, lib/datadog/profiling/transport/http.rb, lib/datadog/tracing/contrib/active_support/cache/instrumentation.rb, lib/datadog/tracing/contrib/extensions.rb, spec/datadog/core/configuration/settings_spec.rb, spec/datadog/core/runtime/metrics_spec.rb, spec/datadog/profiling/collectors/old_stack_spec.rb, spec/datadog/profiling/pprof/builder_spec.rb, spec/datadog/tracing/contrib/action_mailer/helpers.rb, spec/datadog/tracing/contrib/active_record/configuration/resolver_spec.rb, spec/datadog/tracing/contrib/active_record/tracer_spec.rb, spec/datadog/tracing/contrib/elasticsearch/integration_spec.rb, spec/datadog/tracing/contrib/elasticsearch/quantize_spec.rb, spec/datadog/tracing/contrib/rails/support/rails3.rb, spec/datadog/tracing/contrib/redis/configuration/resolver_spec.rb, spec/datadog/tracing/contrib/sinatra/tracer_spec.rb, spec/datadog/tracing/contrib/support/matchers.rb, spec/datadog/tracing/distributed/headers/b3_spec.rb, spec/datadog/tracing/distributed/headers/datadog_spec.rb, spec/datadog/tracing/distributed/metadata/b3_spec.rb, spec/datadog/tracing/distributed/metadata/datadog_spec.rb, spec/datadog/tracing/propagation/http_spec.rb, spec/datadog/tracing/writer_spec.rb
For my friend, @ivoanjo ❤️ 
This PR reduces the indentation level of multi-line arguments.
From:
```ruby
expect(build_location.to_h).to match(hash_including(id: location_id,
line: [{
function_id: function.id, line: line_number
}]))
```
To:
```ruby
expect(build_location.to_h).to match(hash_including(id: location_id,
line: [{
function_id: function.id, line: line_number
}]))
```
2587 white-spaces removed 🙂:
```ruby
git diff head^ | ruby -e "puts ARGF.readlines.select{|x| x.start_with?('-', '+')}.map{|x| s = x.scan(' ').size; x.start_with?('-') ? -s : s}.sum"
```
One issue this change has is that it leaves the first parameter in a muiti-line argument block alone, at the top-right side:
```ruby
expect(build_location.to_h).to match(hash_including(id: location_id,
line: [{ …
```
=> Lint:Ensure multi-line arguments align close to left margin

integration/apps/rails-seven/bin/setup, integration/apps/rails-seven/config/initializers/datadog.rb, integration/apps/rails-seven/docker-compose.yml, integration/apps/rails-seven/nginx.conf
Add `nginx` as reverse proxy for rails 7 integration app
**Motivation**
In order to understand `request_queuing` behaviour, a reverse proxy is required
=> Add reverse proxy setup for rails 7 integration

.rubocop.yml, Gemfile, ddtrace.gemspec, spec/ddtrace/release_gem_spec.rb, tasks/release_gem.rake
Follow up to #2160.
This PR adds the [Rubocop Packaging](https://docs.rubocop.org/rubocop-packaging/index.html) extension to ddtrace.
Working towards implementing #2077, I noticed that Rubocop Packaging has cops that will allow us to ensure we are using `require_relative` correctly.
In particular, we still want to use `require` in our test suite, which can be ensured by the [Packaging/RequireRelativeHardcodingLib cop](https://docs.rubocop.org/rubocop-packaging/cops_packaging.html#packagingrequirerelativehardcodinglib).
The reason this is important is because downstream services might want to run our test suite while testing the system installed `ddtrace`, [as explained here](https://docs.rubocop.org/rubocop-packaging/cops_packaging.html#packagingrequirerelativehardcodinglib):
> Debian has …
=> Lint:Add Rubocop Packaging extension

docker-compose.yml
Update docker-compose configuration used for development/CI to improve compatibility with arm64 machines.
I've been pairing with @TonyCTHsu on getting our docker-compose to a state where it can run and pass the entire test suite when run on an arm64 machine.
The following configuration is an improvement on the status quo (as far as we know, only mongodb seems to be failing on arm64 at the moment), and still happily runs on x86-64, as well still being green in CI.
Note for anyone running stuff on arm64: docker-compose/docker only consider the `platform` setting when first downloading an image, so you'll probably need to delete the existing linux/x86_64 images for docker to realize it can download arm64 images instead.
It's …
=> Tweak docker-compose setup for arm64 machines

integration/apps/rack/bin/setup, integration/apps/rails-five/bin/setup, integration/apps/rails-seven/bin/setup, integration/apps/rails-six/bin/setup, integration/apps/rspec/bin/setup, integration/apps/ruby/bin/setup, integration/apps/sinatra2_modular/bin/setup
Add building native extension in `bin/setup` for integration app
**Motivation**
User would follow the `README.md` for integration app setup
```
1. `cp .envrc.sample .envrc` and add your Datadog API key.
2. `direnv allow` to load the env var.
3. `docker-compose run --rm app bin/setup`
```
The third step would fail with 
```== Installing dependencies ==
Run: gem install bundler --conservative
[DEPRECATED] This Gemfile does not include an explicit global source. Not using an explicit global source may result in a different lockfile being generated depending on the gems you have installed locally before bundler is run. Instead, define a global source in your Gemfile like this: source "https://rubygems.org".
The following gems are missing
* libdatadog (0.7.0.1.0) …
```
=> Build native extension in `bin/setup` for integration app

docker-compose.yml
Upgrade the mysql image used for testing in CI to a more modern version.
According to @TonyCTHsu this version works well on arm64, and it still seems to work fine on all Ruby versions in CI, so this is more of a "why not" change.
**Additional Notes**: 
This is a follow-up to #2171.
* Check that our mysql integration tests are still passing.
=> Bump mysql image used for testing for improved arm64 compatibility

lib/datadog/tracing/contrib/delayed_job/ext.rb, lib/datadog/tracing/contrib/delayed_job/patcher.rb, lib/datadog/tracing/contrib/delayed_job/server_internal_tracer/worker.rb, lib/datadog/tracing/contrib/sidekiq/ext.rb, lib/datadog/tracing/contrib/sidekiq/patcher.rb, lib/datadog/tracing/contrib/sidekiq/server_internal_tracer/redis_info.rb, lib/datadog/tracing/contrib/sidekiq/server_internal_tracer/scheduled_poller.rb, spec/datadog/tracing/contrib/delayed_job/plugin_spec.rb, spec/datadog/tracing/contrib/sidekiq/patcher_spec.rb, spec/datadog/tracing/contrib/sidekiq/server_internal_tracer/heartbeat_spec.rb, spec/datadog/tracing/contrib/sidekiq/server_internal_tracer/redis_info_spec.rb, spec/datadog/tracing/contrib/sidekiq/server_internal_tracer/scheduled_poller.rb, spec/datadog/tracing/contrib/sidekiq/support/helper.rb
This PR adds additional instrumentation to Sidekiq and DelayedJob to wraps spans from Redis/ActiveRecord to prevent them from appearing as top-level spans.
**Motivation**
Addresses #2056 
Additional unit tests were added to verify the changes.
=> Add internal tracing to Sidekiq / DelayedJob

docs/GettingStarted.md
Removes `database_service` and `cache_service` from the `GettingStarted` doc - it seems these were removed in 1.x but the changes were not reflected here
**Motivation**
Saw this resolved issue: #2115 
N/A (I just removed two lines)
=> Update GettingStarted doc rails options

docs/GettingStarted.md, lib/datadog/tracing/contrib/rake/configuration/settings.rb, lib/datadog/tracing/contrib/rake/instrumentation.rb, spec/datadog/tracing/contrib/rake/instrumentation_spec.rb
**Release notes**
Users of the Rake instrumentation will have to explicitly list the tasks that they want instrumented. This was done to **prevent memory bloat issues** that can arise from instrumenting long-running Rake tasks.
From today's configuration:
```ruby
c.tracing.instrument :rake
end
```
The list of desired Rake tests to instrument should be added:
```ruby
c.tracing.instrument :rake, tasks: ['task1', 'task2', ...]
end
```
Not providing this list will effectively instrument no Rake tasks.
This PR requires the Rake instrumentation to receive an explicit list of task to be instrumented. This list can be a list of String task names, or other values that can be stringified (e.g. it's common to declare Rake …
=> Rake:Require instrumented task list

.rubocop.yml, ext/ddtrace_profiling_native_extension/clock_id.h, ext/ddtrace_profiling_native_extension/clock_id_from_pthread.c, ext/ddtrace_profiling_native_extension/clock_id_noop.c, ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time.c, spec/datadog/profiling/collectors/cpu_and_wall_time_spec.rb
This PR adds support for tracking the passage of CPU-time between samples to the `CpuAndWallTime` collector.
The way this works is similar to wall-clock time: on every sample we get the current value from the OS, and we calculate the  elapsed CPU time from the previous sample (which is stored in `cpu_time_at_previous_sample_ns`).
(The first time a thread is sampled, the elapsed time is set to 0).
It also adds the CPU samples count, which is useful to measure how many samples actually were taken.
In #2163 we added tracking of wall-clock time, and this PR adds CPU-time, which is needed to produce CPU profiles aka to figure out how much time different parts of the code spent executing on CPU.
Like for the old profiler, we only …
=> [PROF-4902] Track passage of CPU-time between samples

docs/ProfilingDevelopment.md, lib/datadog/profiling/collectors/stack.rb, lib/datadog/profiling/stack_recorder.rb
A quick update to the `ProfilingDevelopment.md` file with the current state of affairs around the new profiler components.
Keep the architecture documented and hopefully accessible to others beyond the profiling team.
I've left a few gaps and TODOs. I'll fill these up later.
Does not actually change production code.
=> Update profiling development documentation

ext/ddtrace_profiling_native_extension/NativeExtensionDesign.md, ext/ddtrace_profiling_native_extension/extconf.rb, ext/ddtrace_profiling_native_extension/native_extension_helpers.rb
This PR includes three small changes related to the profiling native extension. I recommend reviewing commit-by-commit.
These changes:
* Improve our documentation around the profiling native extension
* Add more information to the compilation log (the compiler version)
* Suggest that users look at the profiler troubleshooting page when there's an issue 
While looking into support tickets, I thought we could do these small improvements to help the customer experience, as well as improve our support experience.
You can simulate a compilation failure in the profiler by running (in a docker container) ```rm `which pkg-config` ``` and then `bundle exec rake clean compile`.
Otherwise, if the profiler builds and starts up, …
=> Small improvements to documentation, user experience, and debugging of the profiling native extension

gemfiles/ruby_3.0.3_contrib.gemfile.lock, gemfiles/ruby_3.0.3_contrib_old.gemfile.lock, gemfiles/ruby_3.0.3_core_old.gemfile.lock, gemfiles/ruby_3.0.3_cucumber3.gemfile.lock, gemfiles/ruby_3.0.3_cucumber4.gemfile.lock, gemfiles/ruby_3.0.3_cucumber5.gemfile.lock, gemfiles/ruby_3.0.3_rails61_mysql2.gemfile.lock, gemfiles/ruby_3.0.3_rails61_postgres.gemfile.lock, gemfiles/ruby_3.0.3_rails61_postgres_redis.gemfile.lock, gemfiles/ruby_3.0.3_rails61_postgres_sidekiq.gemfile.lock, gemfiles/ruby_3.0.3_rails61_semantic_logger.gemfile.lock, gemfiles/ruby_3.0.3_resque2_redis3.gemfile.lock, gemfiles/ruby_3.0.3_resque2_redis4.gemfile.lock
Introduce `aarch64-linux` platform for `gemfile.lock`
**Motivation**
Adding this would make re-resolving for the addition of that platform.
=> Update appraisal gemfile.lock with platform aarch64-linux

lib/datadog/tracing/sampling/span/sampler.rb, lib/datadog/tracing/trace_operation.rb, spec/datadog/tracing/sampling/span/sampler_spec.rb, spec/datadog/tracing/trace_operation_spec.rb
The tracer flushes all traces that have not been dropped by the internal sampler (`TraceOperation#sampled == false` means dropped internally). This includes traces that might be dropped due to their Priority Sampling status downstream.
For Single Span Sampling, we need to guarantee that Single Span Sampled spans are kept and thus cannot trust that all spans flushed by the tracer are kept, unless it's both selected by the internal sampler (`TraceOperation#sampled == true`)  the Priority Sampling status are set to keep (`TraceOperation#sampling_priority > 0`).
This logic is different from the logic used to flush traces through the transport: the tracer wants to send all traces that have not been rejected internally OR traces with Priority Sampling > 0. For Single Span Sampling, we only want …
=> [Single Span Sampling] Consider traces rejected solely by priority sampling as rejected

integration/apps/rack/Gemfile, integration/apps/rails-five/Gemfile, integration/apps/rails-seven/Gemfile, integration/apps/rails-six/Gemfile, integration/apps/rspec/Gemfile, integration/apps/ruby/Gemfile, integration/apps/sinatra2-classic/Gemfile, integration/apps/sinatra2-modular/Gemfile
Set global source in Gemfile
**Motivation**
Fix flaky spec and follow the hint
```
[DEPRECATED] This Gemfile does not include an explicit global source. Not using an explicit global source may result in a different lockfile being generated depending on the gems you have installed locally before bundler is run. Instead, define a global source in your Gemfile like this: source "https://rubygems.org".
```
https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/6826/workflows/06fa256e-a72e-4ef9-854f-ded000e353e8/jobs/252886
```
Fetching gem metadata from https://rubygems.org/............
Resolving dependencies...
Your bundle is locked to google-protobuf (3.21.4-x86_64-linux) from rubygems
repository https://rubygems.org/ or installed locally, but that version …
```
=> Set global source in Gemfile

lib/datadog/profiling/exporter.rb, lib/datadog/profiling/old_recorder.rb, lib/datadog/profiling/scheduler.rb, spec/datadog/profiling/exporter_spec.rb, spec/datadog/profiling/old_recorder_spec.rb, spec/datadog/profiling/scheduler_spec.rb
Replace `Exporter#empty?` with `Exporter#can_flush?`.
The `#empty?` method was used by the `Scheduler` to determine if there was data to be flushed.
With the move to libdatadog to keep the data, it's somewhat awkward to implement an `#empty?` method, since that would entail looking at internal libdatadog state or tracking such a thing ourselves.
Instead, let's replace it with a time-based `#can_flush?` that uses the same `duration_below_threshold?` mechanism we had to decide if there was enough data on a flush. 
The resulting outcome is similar, but needs no extra tracking outside of the `Exporter` class.
`Scheduler#work_pending?` gets called from `Datadog::Core::Workers::IntervalLoop` which implements the reusable looping …
=> Replace `Exporter#empty?` with `Exporter#can_flush?`

LICENSE-3rdparty.csv
Add 3rdparty gem dependencies to LICENSE-3rdparty.csv file.
This brings the `LICENSE-3rdparty.csv` file in line with current Datadog open-source policies. (As discussed with @jeremy-lq.)
This is just a documentation change, no impact to code.
=> Add 3rd party gem dependencies to LICENSE-3rdparty.csv file

ext/ddtrace_profiling_native_extension/stack_recorder.c, lib/datadog/profiling/stack_recorder.rb, spec/datadog/profiling/stack_recorder_spec.rb
Adds a concurrency-safe synchronization mechanism to `StackRecorder`, because this component will be used from threads that can be accessing it in parallel.
The `StackRecorder` component will be accessed from two threads that can be operating in parallel:
* The sampler thread (a thread that is recording stack samples)
* The serializer thread (a thread that wants to report profiling data)
Thus, we need a concurrency mechanism to ensure that such access is safe.
Below I've included an extensive description of how the concurrency mechanism works.
I suggest reviewing this PR commit-by-commit.
This PR already includes test coverage. This mechanism will also be indirectly tested by our other …
=> [PROF-5858] Add synchronization mechanism to StackRecorder

spec/datadog/tracing/contrib/rails/cache_spec.rb
Fix the specs by moving examples to the correct scope, which verified the methods are present, meaning it is a valid Ruby or Rails version that is meant to be tested. Otherwise, skipping the example.
**Motivation**
Testing suite is failing. The examples are acting assuming  `ActiveSupport::Cache` would respond to `write_multi` and `fetch_multi`. Both methods are introduced in later Ruby and Rails versions, hence it is breaking tests.
=> Fix failing spec

lib/datadog/core/configuration/components.rb, spec/datadog/core/configuration/components_spec.rb
This PR refactors the profiling components initialization, as well as the components specs to make it easier to add the new components (which are implemented in the native extension).
I'm getting ready to add a way to enable the new components (off by default), and this refactoring was extracted from my working branch.
This is one of those PRs where I recommend enabling the "hide whitespace" option while looking at the diff on github.
Furthermore, I recommend reviewing it commit-by-commit.
The changes to the components include test coverage; and if the components setup breaks the profiler will not work so every integration test and reliability environment test would break as well.
=> [PROF-5860] Refactor profiling components and components spec in preparation for new components

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time.c, ext/ddtrace_profiling_native_extension/collectors_stack.c, ext/ddtrace_profiling_native_extension/stack_recorder.c, lib/datadog/profiling/collectors/cpu_and_wall_time.rb, lib/datadog/profiling/collectors/stack.rb, lib/datadog/profiling/stack_recorder.rb, spec/datadog/profiling/collectors/cpu_and_wall_time_spec.rb, spec/datadog/profiling/collectors/stack_spec.rb, spec/datadog/profiling/stack_recorder_spec.rb
This change follows from [this discussion thread](https://github.com/DataDog/dd-trace-rb/pull/2181#discussion_r929383004) on improving how testing-only methods are exposed from the native extension.
Here's what I came up with:
* All methods exposed only for testing are scoped inside `Testing` modules; e.g. testing methods for `StackRecorder` are inside `StackRecorder::Testing`
* Removed the "middlemen" methods on the classes themselves. They existed only for documentation of the existence and objective of those methods, but now that they are scoped under `Testing` the "middlemen" methods seem less interesting to have.
* Changed any specs using those methods to directly call the native methods in the `Testing` modules.
* Still kept the `_native_` prefix for all …
=> RFC: Refactor how native extension testing methods are exposed

docs/ProfilingDevelopment.md, ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time.c, ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time.h, ext/ddtrace_profiling_native_extension/ruby_helpers.h, lib/datadog/profiling/collectors/cpu_and_wall_time.rb
This PR includes 3 small changes I've extracted from a bigger branch that adds the final component needed for the new Ruby profiler: the `CpuAndWallTimeWorker`.
This component will take care of triggering samples, e.g. making them happen periodically, which is the big missing part from the new Ruby profiler. (Up until know, we could only manually take samples)
**Motivation**: 
I like to submit small PRs, and the `CpuAndWallTimeWorker` will by itself contain a bit of complexity, so this way I'll reduce the size of that upcoming PR.
I also like to do at least one PR per day, and I was missing my daily PR :)
None of the changes in this PR actually change any observable behavior yet; they'll only come into action in future PRs.
=> [PROF-5859] Preparation to add the new `CpuAndWallTimeWorker` component

lib/datadog/opentracer/rack_propagator.rb, lib/datadog/opentracer/text_map_propagator.rb, spec/datadog/opentracer/propagation_integration_spec.rb, spec/datadog/opentracer/rack_propagator_spec.rb, spec/datadog/opentracer/text_map_propagator_spec.rb
During `1.x` upgrade, we introduce the `TraceDigest` for distributed tracing. 
The `inject` method takes an active trace from span context before converting to `TraceDigest` and propagate to the carrier. The `extract` method returns a span context with `TraceDigest` but not active trace, hence when the result of `extract` is provided to `inject`, an error occurs.
This PR changes the `inject` method to take trace digest when given a span context without an active trace.
**Motivation**
https://github.com/DataDog/dd-trace-rb/issues/2191
Users are using `OpenTracing#inject` and `OpenTracing#extract` for manual instrumentation and distributed tracing. The propagation chain breaks when `inject` after `extract`.
=> Opentracing propagation with TraceDigest

docs/GettingStarted.md
This PR updates the documentation for integration options (`c.tracing.instrument :integration_name, **options`) to clarify that they are keyword arguments, and not a simple `Hash` parameter.
Since Ruby 3.0, providing a Hash instead of keyword arguments fails the `#instrument` method call.
Also, this PR updates the language around `options`. Specifically, it updates parts that mention that `options` is a Hash:
```markdown
Where `options` is an optional `Hash` that accepts the following parameters:
```
=> Doc:Instrumentation options are keyword arguments

lib/datadog/tracing/contrib/rails/framework.rb, spec/datadog/tracing/contrib/rails/defaults_spec.rb
While the code comment states:
> By default, default service would be guessed from the script being executed, but here we know better, get it from Rails config.
In practice, because `Datadog.configuration.service` is *always* present ([here](https://github.com/DataDog/dd-trace-rb/blob/26e8a2da7f04e446e109993b6276746dcbbd46f9/lib/datadog/core/configuration/settings.rb#L271-L287)), `||=` will never set anything.
Now, the Rails framework integration leverages `Datadog.configuration.service_without_fallback` to determine if `Datadog.configuration.service` should be set.
**Motivation**
When adding ddtrace to a new project, I was surprised to see `dd.service=rails` in the log correlation output, when the application name was definitely *not* `"rails"`. Looking further …
=> Correctly set the default service based off of Rails config

lib/datadog/core/telemetry/client.rb, lib/datadog/core/telemetry/collector.rb, lib/datadog/core/telemetry/emitter.rb, lib/datadog/core/telemetry/event.rb, lib/datadog/core/telemetry/heartbeat.rb, lib/datadog/core/telemetry/http/adapters/net.rb, lib/datadog/core/telemetry/http/transport.rb, lib/datadog/core/telemetry/v1/application.rb, lib/datadog/core/telemetry/v1/host.rb, lib/datadog/core/telemetry/v1/telemetry_request.rb, spec/datadog/core/telemetry/v1/telemetry_request_spec.rb
The telemetry feature branch was branched off of `master` a while ago - this PR makes the necessary changes to ensure the telemetry code conforms with the new linting requirements (i.e. using `require_relative` and proper line breaks for method definitions with multi-line parameters).
**Motivation**
This will allow the CI checks to pass on the telemetry feature branch in preparation for merging
Unit tests still pass + rubocop passes
=> Use require_relative and proper line breaks for telemetry

Gemfile
Set Rubocop version `1.32.0` to fix CI
**Motivation**
Rubocop version `1.33.0` breaks CI at this moment
=> Fix CI with rubocop verison

docs/GettingStarted.md, lib/ddtrace/transport/ext.rb, lib/ddtrace/transport/http/adapters/net.rb
Improve the timeout example in the documentation with a reasonable value (which is the same as we currently use as a default).
Also remove an unused and misleading "default timeout" constant.
As raised in #818, the default `timeout` example is rather far away from the actual default being used, which may lead customers that copy-paste the example to have a bad experience.
I also discovered we had an incorrect constant with the default timeout which was not even being used anywhere (you can grep for it  to confirm!).
Thanks @benjaminwood for the awesome suggestion!
Validate that no tests are impacted by the removed constant.
=> Minor improvement to timeout documentation

integration/apps/rack/Gemfile
Temporary skip spec for sidekiq 
**Motivation**
The latest two versions of sidekiq contains undeclared dependency of `concurrent-ruby`
=> Fix sidekiq broken version

.github/workflows/test-head.yaml, .github/workflows/test-macos.yaml
This PR fixes a recent CI issue with MacOS builds not being able to fetch a proper Ruby 3.1 build:
https://github.com/DataDog/dd-trace-rb/runs/7754285255?check_suite_focus=true
```
Downloading Ruby
https://github.com/ruby/ruby-builder/releases/download/toolcache/ruby-3.1.0-preview1-macos-latest.tar.gz
Took   0.16 seconds
Error: Unexpected HTTP response: 404
```
The action is mysteriously trying to fetch `ruby-3.1.0-preview1-macos` for the `3.1` configuration, even though 3.1 is already out.
Upgrading the Action version did the trick.
=> Action:Upgrade ruby/setup-ruby action version

lib/datadog/ci/contrib/cucumber/integration.rb, lib/datadog/ci/contrib/rspec/integration.rb, spec/datadog/ci/contrib/cucumber/formatter_spec.rb, spec/datadog/ci/contrib/rspec/instrumentation_spec.rb
**Motivation**
The CI instrumentation configuration is broken, cannot be customized(for example, `service_name`)
Fix the integration by implementing `new_configuration` and remove `default_configuration`
=> Fix CI instrumentation configuration 

docs/ProfilingDevelopment.md, ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time.c, ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time.h, ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c, ext/ddtrace_profiling_native_extension/extconf.rb, ext/ddtrace_profiling_native_extension/private_vm_api_access.c, ext/ddtrace_profiling_native_extension/profiling.c, ext/ddtrace_profiling_native_extension/stack_recorder.c, ext/ddtrace_profiling_native_extension/stack_recorder.h, lib/datadog/profiling.rb, lib/datadog/profiling/collectors/cpu_and_wall_time_worker.rb, lib/datadog/profiling/stack_recorder.rb, spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb, spec/support/synchronization_helpers.rb
Adds the new `Profiling::Collectors::CpuAndWallTimeWorker`.
The `CpuAndWallTimeWorker` component takes care of automatically triggering the `CpuAndWallTime` collector.
In a single sentence, this component a) runs in a background thread, b) periodically uses a unix signal (SIGPROF) to interrupt a running Ruby thread, and c) gets the interrupted Ruby thread to call the `CpuAndWallTime` collector to take a sample.
Thus we achieve periodic sampling of Ruby threads. The `CpuAndWallTimeWorker` was the last big missing piece for the new Ruby profiler, and we can now turn it on and actually get samples.
This component has the important job of periodically triggering taking samples. In the old profiler, this behavior lived in `Collectors::OldStack`. …
=> [PROF-5859] Introduce `CpuAndWallTimeWorker` to trigger profiling samples

lib/datadog/core/configuration/components.rb, lib/datadog/core/configuration/settings.rb, spec/datadog/core/configuration/components_spec.rb, spec/datadog/core/configuration/settings_spec.rb
But! We actually can turn it on now -- by using `DD_PROFILING_FORCE_ENABLE_NEW=true`.
The rest of the pieces have been put into place in previous PRs.
Add a setting that allows choosing between the "old" profiler codepath, and the new "CPU Profiling 2.0" codepath.
Making it possible to test the new profiler.
This PR sits atop #2208 because without the component in #2208 the profiler would not be able to be turned on. It is otherwise independent from that change.
Here's a simple run of the new profiler:
```
$ DD_TRACE_DEBUG=true DD_PROFILING_ENABLED=true DD_SERVICE=ivoanjo-testing DD_ENV=staging DD_PROFILING_FORCE_ENABLE_NEW=true bundle exec ddtracerb exec ruby -e sleep
I, …
```
=> [PROF-5860] Allow new CPU Profiling 2.0 **alpha** profiler to be enabled

spec/datadog/profiling/encoding/profile_spec.rb
Fix a flaky spec.
The `template` double used in this test was missing the `debug_statistics` method which was used only for debug logging.
This caused the following error if debug logging was enabled:
```
$ DD_TRACE_DEBUG=true bundle exec rspec ./spec/datadog/profiling/encoding/profile_spec.rb
Failures:
1) Datadog::Profiling::Encoding::Profile::Protobuf.encode returns a pprof-encoded profile
Failure/Error: "events: #{event_count} (#{events_sampled}#{template.debug_statistics})"
#<InstanceDouble(Datadog::Profiling::Pprof::Template) (anonymous)> received unexpected message :debug_statistics with (no args)
```
By default, the tests run with debug logging disabled, which means this should not be triggered but clearly there are some specs that enable debug logging …
=> Fix flaky profiling spec

README.md, docs/GettingStarted.md
Tweak the language of the note we added at the top of the README.md and GettingStarted.md documents to refer to the 1.x series, and not just to 1.0.0.
It seemed a bit weird/confusing to me that the wording was presenting 1.0.0 as if it was the latest release, whereas customers should be on 1.3.0 (or whatever comes after).
This does not affect code, so looking at the diff and the GitHub markdown preview is enough.
=> Tweak the upgrade guide banner in README/Getting Started to mention 1.x instead of 1.0.0

spec/spec_helper.rb
In another attempt to debug [log writing failed. closed stream](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/6939/workflows/5a1363b8-007f-468a-a334-262ac35cd0d9/jobs/256791), I'm adding a test deadline monitor thread to our CI test runs. This specific run ran for 5 hours 😮 
This monitor will dump the stack track of all threads after 30 minutes and kill the RSpec process with a non-zero exit code.
None of our tests are close to taking 30 minutes (the slowest tests, for JRuby, take around 6 minutes).
Hopefully this will allow debugging not only this specific issue, but any other tests that happen to get stuck in the future.
=> CI:Test time limit with thread dump report

docs/GettingStarted.md, docs/UpgradeGuide.md, spec/datadog/tracing/trace_operation_spec.rb
* Fix `Datadog::SpanOperation` -> `Datadog::Tracing::SpanOperation`
* Fix `Datadog::TraceOperation` -> `Datadog::Tracing::TraceOperation`
Fix typos in documentation
**Motivation**
While upgrading code to the 1.x API (we were using `ddtrace` 0.52), we ran into a few minor problems.
There shouldn't be any occurrences of the incorrect class names in the codebase:
```bash
[ -z "$(git grep -E 'Datadog::(Span|Trace)Operation')" ] && echo success
```
=> fix namespace typos in docs

integration/apps/rack/Gemfile
This reverts commit 79b9138cee3e6cf0832fcbe6ad208f55b3e34e84.
**Motivation**
Sidekiq have already released a newer version which fixed the broken dependency.
https://github.com/mperham/sidekiq/blob/main/Changes.md#654
=> Remove sidekiq version cap

docs/GettingStarted.md
This PR fixes the two leftover mentions of `use` in the docs that I found that should be replaced by `instrument`. I did not change the sinatra docs to avoid a conflict with #2217.
While reviewing #2217 where we fixed the sinatra documentation not to mention the outdated `use`, I decided to make a quick check if we had any more such leftovers, and it turns out we did.
Check that the documentation is actually correct now / build an example app and check that `instrument` correctly instruments it.
=> Fix outdated references to `use` instead of `instrument` in docs

docs/GettingStarted.md
Remove the analytics related documentation
**Motivation**
Integration analytics options are deprecated. We recently added some back from our community, which was meant to be removed.
https://github.com/DataDog/dd-trace-rb/pull/2195
=> Remove analytics docs for actionmailer and graphql

ext/ddtrace_profiling_native_extension/stack_recorder.h
The profiling backend team (cc @peterg17) has been working on aligning most runtimes on a standard set of profile value types.
To align with the standard set, the profile types used were changed as follows:
* `alloc-space` became `alloc-size`
* `heap-space` became `heap-live-size`
Additionally, the following two changes were made:
* Introduce a definition for `heap-live-samples`
* Reformat spacing to keep it consistent (sorry for the diff noise on this one -- hopefully it's worth the readability boost) (**You can use GitHub's "Hide whitespace" option to show a better diff**)
Aligning most runtimes on a standard set of profile value types.
I'll get someone from the profiling backend team to review this, since it makes a lot …
=> Align profile value types with latest backend expectations

integration/apps/rack/Gemfile, integration/apps/rails-five/Gemfile, integration/apps/rails-seven/Gemfile, integration/apps/rails-six/Gemfile
Do not use redis 5 for integration test
**Motivation**
Fix CI breaking version on redis 5
https://github.com/redis/redis-rb/issues/1142#issue-1354572770
https://github.com/resque/resque/issues/1821
https://github.com/resque/resque/pull/1823
=> Restrain redis 5 version for known compatibility issue

ext/ddtrace_profiling_loader/ddtrace_profiling_loader.c
Add a missing check for a `NULL` result of `dlsym` that happens when Ruby is not built with `libruby.so`.
The logic in `ddtrace_profiling_loader.c` follows Ruby's `dln.c`; see the big comment at the top of the former for why it needs to exist.
The `incompatible_library` sanity check exists to try to catch situations where the library being loaded is linked to a different `libruby.so` (or equivalent in other OSs) than the one that is doing the loading.
BUT when we implemented `incompatible_library` we missed an check that upstream Ruby does.
From https://github.com/ruby/ruby/blob/v3_1_2/dln.c#L295:
```c
static bool
dln_incompatible_library_p(void *handle)
{
void *ex = dlsym(handle, EXTERNAL_PREFIX"ruby_xmalloc");
void *const fp = (void …
```
=> [SCP-184] Fix incompatible library check when there's no libruby.so

lib/datadog/tracing/contrib/faraday/middleware.rb
`service_name(env[:url].host, options)` was called but the result was not used.
Fixes a bug where faraday middleware duplicates `HttpAnnotationHelper` logic.
**Motivation**
I have a patched version of `HttpAnnotationHelper` logic which allows combining `service_name` and `split_by_domain` together as currently they are exclusive. However, I noticed that this update logic is not applied automatically to requests made by faraday library.
This change does not modify existing library behavior, it only removes duplication so that future changes to `HttpAnnotationHelper` are by automatically used across all http tracing libraries, including faraday.
=> Faraday middleware uses HttpAnnotationHelper

lib/datadog/tracing/distributed/datadog_tags_codec.rb, spec/datadog/tracing/distributed/datadog_tags_codec_spec.rb
This PR implements part of the `[RFC] Trace Tags Propagation in Distributed Traces`.
The work will be merged into the `feat-Sampling-Propagation` branch, like this PR.
This PR serializes and deserializes `x-datadog-tags`, when sending or receiving them through HTTP headers. The format is available in the RFC.
These tags will be received from upstream services through distributed trace propagation, and be send downstream through propagation injection.
Follow up PRs will actually use this serialize/deserializer.
=> Sampling Propagation:Tag serializer

integration/apps/rack/Gemfile, integration/apps/rack/app/acme.rb, integration/apps/sinatra2-classic/app/acme.rb, integration/apps/sinatra2-modular/app/basic.rb, integration/apps/sinatra2-modular/app/health.rb
We've started getting this issue in CI:
```
Rack::Lint::LintError: Status must be an Integer >=100
```
And that's because we've been returning the status code in Rack apps as strings, not integers. A new version of Rack now checks for that, a few more things in the `Lint` middleware: https://github.com/rack/rack/blob/main/lib/rack/lint.rb
This PR solves that.
=> chore:Satisfy new Rack linter middleware

lib/datadog/ci/ext/environment.rb, spec/datadog/ci/ext/fixtures/ci/appveyor.json
Fixes getting the full commit message when running on the AppVeyor CI.
**Motivation**
Previously we were only checking `APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED` which, [as per the docs](https://www.appveyor.com/docs/environment-variables/) only contains the "rest" of the commit message. The first line of the commit message is in `APPVEYOR_REPO_COMMIT_MESSAGE`.
Updated appveyor fixture.
=> Correctly extract commit message from AppVeyor

lib/datadog/ci/ext/environment.rb
Reads committer and author info from the env vars set by the CI provider.
Other tracers always set `TAG_COMMIT_COMMITTER_EMAIL` to the committer name. However there's a committer email variable we can use. I assume this was a typo that propagated from the spec to all tracers, so I've changed the spec to say we should use the email and fallback to the name if not available (just in case the spec was intentional because the email is not always available).
**Motivation**
These are in the CI spec but were missing from this tracer.
=> CI: Fetch committer and author in Bitrise

lib/datadog/tracing/contrib/rack/middlewares.rb, lib/datadog/tracing/metadata/ext.rb, spec/datadog/tracing/contrib/rack/integration_test_spec.rb
Add `http.useragent` tag to capture and report the user agent that made an HTTP request to Rack-based applications.
**Motivation**
While User-Agent is a header and can be included in the http.request_headers tag, it is not by default, and even if it were it could be removed from the list by the user.
This unconditionally obtains the request header value and stores it in a dedicated tag.
This is a requirement for server-side ASM and is part of the APM tag standardization project. 
=> Add http.useragent tag

ddtrace.gemspec
Bump allowed version of debase-ruby_core_source to include the latest v0.10.17.
In the past, we decided to manually opt-in to debase-ruby_core_source releases; but we also don't want to force customers to stay on an older version.
I validated this release is ok by looking through:
* https://github.com/ruby-debug/debase-ruby_core_source/releases/tag/v0.10.17
* https://my.diffend.io/gems/debase-ruby_core_source/0.10.16/0.10.17
Check that profiling continues to compile and work on Ruby <= 2.5 (later versions do not use this dependency).
=> Bump allowed version of debase-ruby_core_source to include v0.10.17

spec/datadog/core/telemetry/collector_spec.rb
`Time.new(2020).to_i` returns different values depending on the local time zone. This breaks the assertion `is_expected.to eq(1577836800)`.
This PR makes it return the same epoch on regardless of the system timezone.
=> test:Fix flaky time in test

lib/datadog/tracing/contrib/ext.rb, lib/datadog/tracing/contrib/pg/instrumentation.rb, lib/datadog/tracing/metadata/ext.rb, spec/datadog/tracing/contrib/pg/patcher_spec.rb
This PR moves database-specific contrib fields to inside the `contrib` folder: before it was under the more general `metadata` folder.
This changes aligns these tags more with our isolated contrib goals.
=> Move contrib-specific database span tags

.circleci/config.yml, .circleci/images/primary/Dockerfile-3.2.0-preview2, docker-compose.yml, integration/apps/rails-seven/Gemfile
Setup the newly-released ruby 3.2.0-preview2 for use in development and testing. This includes testing with the integration apps BUT DOES NOT include running the main+integration test suites (see below).
Make sure we're compatible with the upcoming Ruby 3.2 release.
The main+integration test suites are broken on 3.2, see [this run](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/7254/workflows/5ee2a9c4-f04b-4444-ba20-501bbaf3516a/jobs/268577/parallel-runs/9?filterBy=FAILED). To allow us to still merge this PR to master, I've kept them disabled for now.
1. Validate that `build_and_test_integration-3.2-1` is green on CircleCI.
2. Validate that the `tracer-3.2` can be used for local …
=> Setup ruby 3.2.0-preview2 image for testing

.circleci/config.yml
We recently added the sinatra2 integration apps, but forgot to also update the edge workflow to run them.
Make sure edge workflow matches the workflow we use for PRs/branches.
Not sure how to test before merging. To test the change after merging, we need to wait until the next "edge" workflow [on CircleCI](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb?branch=master) (runs once a day) and validate that the new sinatra apps are correctly running.
=> Add new integration apps also to edge workflow

lib/datadog/tracing/trace_operation.rb, spec/datadog/tracing/integration_spec.rb, spec/datadog/tracing/trace_operation_spec.rb
Fixes #2101
**Motivation**
In v0.x of `ddtrace`, the currently active trace, represented by the `Context` class, would always have a `sampled == true` by default, as it inherited its value from `Span#sampled`: https://github.com/DataDog/dd-trace-rb/blob/9fd04441f91f4668c6d31dcff2af2115b38318c0/lib/ddtrace/context.rb#L299
And `Span#sampled` defaults to `true`: https://github.com/DataDog/dd-trace-rb/blob/9fd04441f91f4668c6d31dcff2af2115b38318c0/lib/ddtrace/span.rb#L94
In v1.x, the currently active trace is now represented by a `TraceOperation`.
`TraceOperation#sampled` defaults to `false`: https://github.com/DataDog/dd-trace-rb/blob/4f646ea8f3b926715e3a7bbe4a5a1195ef4b7223/lib/datadog/tracing/trace_operation.rb#L77
And there's no mechanism to inherit sampling from the active span in v1.x. …
=> Set TraceOperation to sampled=true by default

.rubocop.yml, docs/GettingStarted.md, lib/datadog/appsec/configuration/settings.rb, lib/datadog/core/configuration/agent_settings_resolver.rb, lib/datadog/core/configuration/components.rb, lib/datadog/core/configuration/settings.rb, lib/datadog/profiling/collectors/old_stack.rb, lib/datadog/tracing/contrib/rack/middlewares.rb, lib/datadog/tracing/contrib/utils/quantization/http.rb, lib/datadog/tracing/span_operation.rb, lib/datadog/tracing/trace_operation.rb, lib/datadog/tracing/trace_segment.rb, lib/datadog/tracing/tracer.rb, spec/datadog/tracing/contrib/rack/integration_test_spec.rb, spec/datadog/tracing/contrib/sinatra/multi_app_spec.rb, spec/datadog/tracing/contrib/utils/quantization/http_spec.rb
*Adjust HTTP URL tags to comply with span tag unification RFC*
- align http.url with tag naming RFC (and Rack's #url) to include the
complete request URL
- drop http.base_url, now unneeded
- preserve REQUEST_URI logic that differs from Rack's logic
- add SCRIPT_NAME which was previously unhandled for PATH_INFO
- append QUERY_STRING when using PATH_INFO to match REQUEST_URI
*Enable query string quantization by default*
This change is mandated by the unifying tag RFC.
**Motivation**
Compliance with internal RFC document.
=> Use full URL in `http.url` tag

lib/datadog/opentracer/tracer.rb, spec/datadog/opentracer/propagation_integration_spec.rb
Fixes #2191 
Context propagation in OpenTracing was not working properly. Ordinarily, each new `Span` should get its own `SpanContext`, containing the relevant `Datadog::Tracing::Context` state. Instead, of building this `SpanContext` with the current state, it would build it with the previous state in inherited from its parent. This would case the child to inherit the grandparent's ID as its parent ID.
This change makes sure we build a new `SpanContext` per `Span`, and only propagate the relevant `Datadog::Tracing::Context`.
=> Fix OpenTracing context propagation

lib/datadog/tracing/contrib/graphql/configuration/settings.rb
Just a simple typo fix in the configuration file of the Graphql integration. I don't know if this is the source of some of my recent issues, but if the option is going to be there... it should be right.
=> Fix `service_nam` typo to `service_name`

lib/datadog/appsec/contrib/rails/integration.rb
As discussed in slack. 
rails gem is a meta gem and should not be used to detect the presence of the rails framework.
If an application is running with stripped gem-set , the AppSec Extension fail to load with a comparison  error `nil >= MINIMUM_VERSION`
=> fix: AppSec Rails should check for railties instead of rails meta gem

lib/datadog/core/configuration/settings.rb, spec/datadog/core/configuration/settings_spec.rb
Colons are allowed in Datadog tags: they are considered part of the key's "value".
From: https://docs.datadoghq.com/getting_started/tagging/#define-tags
> <p> The key always precedes the first colon of the global tag definition, for example:</p>
> 
> Tag | Key | Value
> -- | -- | --
> env:staging:east | env | staging:east
This PR allows for DD_TAGS to contain colons in the tag "value" component.
=> Allow DD_TAGS values to have the colon character

lib/datadog/core/workers/interval_loop.rb, spec/datadog/core/workers/runtime_metrics_spec.rb, spec/support/synchronization_helpers.rb
I don't like slow tests: they waste our finite time in this beautiful world.
Runtime metric is one of the slowest test files we have, sometimes have one test case that takes 5 seconds to run ("Datadog::Core::Workers::RuntimeMetrics#perform when #enabled? is true starts a worker thread"): https://app.circleci.com/insights/github/DataDog/dd-trace-rb/workflows/build-and-test/tests?branch=master&reporting-window=last-30-days
There are other, slower tests but some are pretty tricky to solve and this one was a low-hanging fruit.
=> test:Reduce wait time on RuntimeMetrics tests

lib/ddtrace/transport/traces.rb
When enabling diagnostic logging, we can see all traces that are sent to the writer.
This is very helpful, but does not capture the complete story of a trace.
The trace will be modified by **TraceFormatter**, which does quiet a bit of work applying tags to the root span: the root span that we see today in diagnostic logs will be much different when actually flushed.
There's also the Processing Pipeline that can modify or drop traces.
This PR adds a debug-level log as late as possible: right before we mush our trace into unintelligible bytes.
The log line looks like this:
```
Flushing trace: [{"error":0,"meta":{"env":"test-env","language":"ruby","runtime-id":"24c8dbaf-bd09-407d-812d-a8737f4bcaf0"},"metrics":{"_dd.top_level":1.0,"_dd.agent_psr":1.0,"system.pid":70439.0,"_sampling_priority_v1 …
```
=> Debug:Print trace as it is about to be flushed

docs/GettingStarted.md
This change tries to clarify as much as possible that `Application-side sampling` will yield unreliable numbers in the Ingestion page.
I've moved the `Application-side sampling` to be last one in the Sampling doc options, in order to disincentivize its use.
I've also removed a lot of the language, and only left the required information.
=> Doc:Clarify Application-side sampling

lib/datadog/core/configuration/settings.rb, lib/datadog/tracing/configuration/ext.rb, lib/datadog/tracing/distributed/headers/datadog.rb, lib/datadog/tracing/distributed/headers/ext.rb, lib/datadog/tracing/metadata/ext.rb, lib/datadog/tracing/propagation/http.rb, lib/datadog/tracing/trace_digest.rb, spec/datadog/core/configuration/settings_spec.rb, spec/datadog/opentracer/rack_propagator_spec.rb, spec/datadog/tracing/distributed/headers/datadog_spec.rb, spec/datadog/tracing/trace_digest_spec.rb
Follow up from #2216
_**I recommend reviewing this PR with "No Whitespace" enable, as I've indented most of the `lib/datadog/tracing/distributed/headers/datadog.rb` file.**_
This PR extracts and injects trace-level distribute tags through the HTTP header `x-datadog-tags`.
The tags are currently read and written to a `TraceDigest`, but not yet consumed by the rest of the application: this will be done in a later PR.
Most of the complexity is around error handling, which is defined in the feature's RFC.
One configuration was added: a max size to the `x-datadog-tags` (and respective environment variable `DD_TRACE_X_DATADOG_TAGS_MAX_LENGTH`), as per RFC.
=> Sampling-Propagation:Extract/Inject distributed headers

lib/datadog/tracing/trace_operation.rb, lib/datadog/tracing/tracer.rb, spec/datadog/tracing/trace_operation_spec.rb, spec/datadog/tracing/tracer_integration_spec.rb, spec/datadog/tracing/tracer_spec.rb
Follow up from #2264
This PR consumes the `TraceDigest#trace_distributed_tags` field in `Tracing.continue_trace!`.
Incoming distributed tags become regular trace-level tags of the active trace.
This means that they will make it to the backend through the regular agent payload, as well as be propagated to downstream services on `Tracing::Propagation::HTTP.inject!`.
=> Sampling-Propagation:Consume distributed tags in TraceOperation

ext/ddtrace_profiling_native_extension/collectors_stack.c, ext/ddtrace_profiling_native_extension/collectors_stack.h, spec/datadog/profiling/collectors/stack_spec.rb, spec/datadog/profiling/stack_recorder_spec.rb
This PR adds a new feature to the `Collectors::Stack`: being able to include, at the top of the sampled stack, a placeholder frame saying "Garbage Collection".
The "Garbage Collection" placeholder is part of a new feature to show on the flamegraph the CPU and wall-clock time spent in garbage collection.
Right now we are not yet collecting this information, but I will follow up with a later PR to add this feature to `Collectors::CpuAndWallTime`.
~~I'm opening this PR as a draft because:~~
* ~~it's on top of #2302 to avoid a later rebase~~
* ~~libdatadog 0.9 has not been released yet, so CI fails~~
~~Thus, once libdatadog 0.9 is released and #2302 is merged, I'll re-trigger CI and mark this PR as non-draft when CI is back to …
=> Support placeholder Garbage Collection frames in Collectors::Stack

lib/datadog/tracing/contrib/redis/ext.rb, lib/datadog/tracing/contrib/redis/tags.rb, spec/datadog/tracing/contrib/redis/instrumentation_spec.rb
Add tag `db.redis.database_index` for `redis` integration
=> Unified tagging `db.redis.database_index`

lib/datadog/tracing/contrib/rack/middlewares.rb, spec/datadog/tracing/contrib/rack/integration_test_spec.rb
This fixes `URI::InvalidURIError` when it runs on WEBrick.
This error introduced in v1.5.0 (#2265).
`env['REQUEST_URI']` is often only path, but in some environments (e.g. WEBrick) it contains the base url (e.g. `http://localhost:3000/foo/bar`).
https://github.com/ruby/webrick/blob/v1.7.0/lib/webrick/httprequest.rb#L423
https://github.com/ruby/webrick/blob/v1.7.0/lib/webrick/httprequest.rb#L218
https://github.com/ruby/webrick/blob/v1.7.0/lib/webrick/httprequest.rb#L484-L505
Start rails server on WEBrick and access app via web browser (e.g. `http://localhost:300/foo`).
My environment is below:
* Ruby 2.7.5
* ddtrace 1.5.0
* rack 2.2.4
* webrick 1.7.0
* rails 5.2.8.1
=> Fix `URI::InvalidURIError`

lib/datadog/core/diagnostics/environment_logger.rb, spec/datadog/core/diagnostics/environment_logger_spec.rb
Mitigate the [error](https://github.com/DataDog/dd-trace-rb/issues/2312) from environment logger when IO transport is configured.
The environment logger, seems to be only working for HTTP transport, the object has client attribute, and api and adapter so on…, but not for IO transport
=> Fix agent_url in environment logger when io transport 

spec/datadog/tracing/contrib/redis/instrumentation_spec.rb
Fix redis database index in spec
**Motivation**
The flaky spec in introduced from https://github.com/DataDog/dd-trace-rb/pull/2274
The redis connection would fire `select db` command when switching database, since `0` is the default database for redis, the db select span would be skipped, hence leading to flakiness.
=> Fix flaky spec with redis database index

LICENSE-3rdparty.csv, lib/datadog/tracing/contrib/utils/quantization/http.rb, spec/datadog/tracing/contrib/utils/quantization/http_spec.rb
Handle additional URL corner cases.
**Motivation**
Fixes #2309
Not entirely sure about the expected `placeholder` behaviour but it's an undocumented feature.
Specs.
=> Handle URLs with invalid characters

lib/datadog/tracing/contrib/rack/middlewares.rb, spec/datadog/tracing/contrib/rack/integration_test_spec.rb
https://github.com/DataDog/dd-trace-rb/issues/2315
When instrumenting a non-GET request, a Rails app with [exceptions_app](https://guides.rubyonrails.org/configuring.html#config-exceptions-app) configured would mutated the request method to `GET` before dispatching to the exception handling app. 
https://github.com/rails/rails/blob/8015c2c2cf5c8718449677570f372ceb01318a32/actionpack/lib/action_dispatch/middleware/show_exceptions.rb#L45
Hence, it would be more accurate to fetch the value from the original rack env(prior to the mutation).
=> Fix Non-GET request method with rails exception controller

lib/datadog/tracing/contrib/rack/middlewares.rb, spec/datadog/tracing/contrib/rack/integration_test_spec.rb
Backport of #2310 to `1.5-stable`
**Motivation**
Without this fix there's a possibility of crash.
=> Backport "Fix `URI::InvalidURIError`"

lib/datadog/tracing/contrib/mongodb/ext.rb, lib/datadog/tracing/contrib/mongodb/subscribers.rb, spec/datadog/tracing/contrib/mongodb/client_spec.rb, spec/datadog/tracing/contrib/mongodb/integration_spec.rb
Add tag `db.mongodb.collection` for `mongodb` integration
=> Unified tagging `db.mongodb.collection`

spec/datadog/tracing/contrib/faraday/middleware_spec.rb
Replace unnecessary variable `request_span` with `span`, since there is only one `span` and assertion also apply on the name of span
=> Improve faraday test

Gemfile, integration/apps/rack/Gemfile, integration/apps/rack/spec/spec_helper.rb
Adds a restriction on our `Gemfile` (only used for testing) to not use `rspec-mocks` 3.11.2.
**Motivation**
This version of rspec-mocks breaks CI for Ruby 2.7, 3.0 and 3.1 on the following tests:
* ./spec/datadog/core/configuration_spec.rb:377 (Ruby 2.7)
* ./spec/datadog/core_spec.rb:35 (Ruby 2.7)
* ./spec/ddtrace/transport/http/builder_spec.rb:250 (Ruby 3.0, 3.1)
References:
* <https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/7560/workflows/24205733-d9fb-4781-962c-87499bad162d/jobs/280394>
* <https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/7560/workflows/24205733-d9fb-4781-962c-87499bad162d/jobs/280387>
* <https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/7560/workflows/24205733-d9fb-4781-962c-87499bad162d/jobs/280396> …
=> Avoid using problematic rspec-mocks 3.11.2

lib/datadog/appsec/contrib/rack/request_middleware.rb, lib/datadog/appsec/event.rb, lib/datadog/core/configuration/settings.rb, lib/datadog/tracing/client_ip.rb, lib/datadog/tracing/configuration/ext.rb, spec/datadog/appsec/contrib/rack/integration_test_spec.rb, spec/datadog/appsec/contrib/rails/integration_test_spec.rb, spec/datadog/appsec/contrib/sinatra/integration_test_spec.rb
Change `http.client_ip` (implemented in https://github.com/DataDog/dd-trace-rb/pull/2248) collection to opt-in.
**Motivation**
`http.client_ip` should not be collected by default by the tracer as it constitutes PII.
=> Default to disable `http.client_ip` tag collection

lib/datadog/tracing/contrib/rack/middlewares.rb, spec/datadog/tracing/contrib/rack/middlewares_spec.rb
This has been reported to happen on WEBrick, it may happen in other ways depending on how the variable is set.
Handle #2310 differently, preventing an exception for invalid URLs as found in #2309
**Motivation**
#2310 causes #2309 again because of the introduction of URI parsing via `URI.join` at a stage to early.
Start an app like so (with tracing enabled of course):
```
bundle exec puma -w 0 -p 9292
bundle exec rackup -s webrick -p 9292
```
Then `curl` it:
```
curl -vvv 'http://user:pass@127.0.0.1:9292/foo/bar|'
```
On Puma this should return a `HTTP/1.1 404 Not Found` and in the `rack.request` span tags the path should be replaced by a `?` placeholder by quantization:
```
// with quantization: base: :show …
```
=> Handle REQUEST_URI with base url

Gemfile, integration/apps/rack/Gemfile, integration/apps/rack/spec/spec_helper.rb, lib/datadog/tracing/contrib/rack/middlewares.rb, spec/datadog/tracing/contrib/rack/middlewares_spec.rb
Backport #2328 
**Motivation**
Rapid crasher fix for out of band release.
=> Backport #2328

Gemfile, integration/apps/rack/Gemfile, integration/apps/rack/spec/spec_helper.rb, lib/datadog/appsec/contrib/rack/request_middleware.rb, lib/datadog/appsec/event.rb, lib/datadog/core/configuration/settings.rb, lib/datadog/tracing/client_ip.rb, lib/datadog/tracing/configuration/ext.rb, spec/datadog/appsec/contrib/rack/integration_test_spec.rb, spec/datadog/appsec/contrib/rails/integration_test_spec.rb, spec/datadog/appsec/contrib/sinatra/integration_test_spec.rb
Backport https://github.com/DataDog/dd-trace-rb/pull/2321
**Motivation**
Rapid PII fix for out of band release.
=> Backport #2321

lib/ddtrace/transport/traces.rb, spec/datadog/core/configuration_spec.rb, spec/datadog/core_spec.rb, spec/ddtrace/transport/http/builder_spec.rb, spec/ddtrace/transport/traces_spec.rb
This proposes a fix for https://github.com/DataDog/dd-trace-rb/issues/2334
TraceSegment doesn't respond to `map` but the spans inside it do, so it should provide usable debug information going forward.
I'm not confident that the test is the best it can be, I'm just focused on the issue I've encountered, I had to change the logger statement to actually render the log line to ensure it works appropriately.
**Motivation**
I found the bug
=> Ensure that Datadog::Tracing::TraceSegment can be reported correctly when they are dropped

Gemfile
The same issue we ran into in #2327 is present on the newly-released rspec-mocks 3.12.0.
This PR adds a restriction on our `Gemfile` (only used for testing) to not use `rspec-mocks` 3.12.2.
**Motivation**
This version of rspec-mocks breaks CI for Ruby 2.7, 3.0 and 3.1 on the following tests:
* ./spec/datadog/core/configuration_spec.rb:377 (Ruby 2.7)
* ./spec/datadog/core_spec.rb:35 (Ruby 2.7)
* ./spec/ddtrace/transport/http/builder_spec.rb:250 (Ruby 3.0, 3.1)
References:
* <https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/7611/workflows/dfae185d-fb67-44c6-bef3-1d0aad44d652/jobs/282330>
* <https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/7611/workflows/dfae185d-fb67-44c6-bef3-1d0aad44d652/jobs/282324>
* …
=> Workaround issue with rspec-mocks 3.12.0

ext/ddtrace_profiling_native_extension/stack_recorder.c, spec/datadog/profiling/stack_recorder_spec.rb
(Important note: This fix only affects the new CPU Profiling 2.0 profiler which is still in **alpha**, see #2209)
In #2181 we added a concurrency-safe mechanism for `StackRecorder`. Key to how it works, is that we keep two `ddog_Profile` instances at every point in time, and we alternate between using them.
But this alternation introduced a bug with the `start_time` of profiles. Previously, the `start_time` got set whenever a profile got created or reset, and we used the current time for it.
That caused the following effect:
```
t=0
created slot_one_profile (start_time=0)
created slow_two_profile (start_time=0)
make_active slot_one_profile
t=60
serialized slot_one_profile (start_time=0, finish_time=60)
reset slot_one_profile (start_time=60)
make_active …
```
=> Fix incorrect start time for profiles

lib/datadog/tracing/contrib/aws/instrumentation.rb, lib/datadog/tracing/contrib/ethon/easy_patch.rb, lib/datadog/tracing/contrib/ethon/multi_patch.rb, lib/datadog/tracing/contrib/excon/middleware.rb, lib/datadog/tracing/contrib/faraday/middleware.rb, lib/datadog/tracing/contrib/grpc/datadog_interceptor/client.rb, lib/datadog/tracing/contrib/http/instrumentation.rb, lib/datadog/tracing/contrib/httpclient/instrumentation.rb, lib/datadog/tracing/contrib/httprb/instrumentation.rb, lib/datadog/tracing/contrib/mysql2/instrumentation.rb, lib/datadog/tracing/contrib/rest_client/request_patch.rb, spec/datadog/tracing/contrib/aws/instrumentation_spec.rb, spec/datadog/tracing/contrib/ethon/multi_patch_spec.rb, spec/datadog/tracing/contrib/ethon/shared_examples.rb, spec/datadog/tracing/contrib/excon/instrumentation_spec.rb, spec/datadog/tracing/contrib/faraday/middleware_spec.rb, spec/datadog/tracing/contrib/grpc/datadog_interceptor/client_spec.rb, spec/datadog/tracing/contrib/http/miniapp_spec.rb, spec/datadog/tracing/contrib/http/request_spec.rb, spec/datadog/tracing/contrib/httpclient/instrumentation_spec.rb, spec/datadog/tracing/contrib/httprb/instrumentation_spec.rb, spec/datadog/tracing/contrib/mysql2/patcher_spec.rb, spec/datadog/tracing/contrib/rest_client/request_patch_spec.rb
Unified tagging `span.kind` as `client`, inspired by [Opentelemetry](https://github.com/open-telemetry/opentelemetry-specification/blob/9fa7c656b26647b27e485a6af7e38dc716eba98a/specification/trace/api.md#spankind
)
=> Unified tagging `span.kind` as `client`

.circleci/config.yml, docker-compose.yml
The Datadog agent now requires a meaningful hostname in order to start (https://github.com/DataDog/datadog-agent/issues/14152)
The CircleCI environment is not really a fully fledged production environment, thus the agent fails to find a suitable hostname.
This PR adds a hostname explicitly to the agent.
=> Add required hostname value to Datadog agent

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time.c, ext/ddtrace_profiling_native_extension/extconf.rb, ext/ddtrace_profiling_native_extension/private_vm_api_access.c, ext/ddtrace_profiling_native_extension/private_vm_api_access.h, ext/ddtrace_profiling_native_extension/stack_recorder.c, spec/datadog/profiling/collectors/cpu_and_wall_time_spec.rb, spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb, spec/datadog/profiling/spec_helper.rb
This PR extends the `thread id` label that is attached to profiling samples to include the thread's "native thread id".
Up until now, the `thread id` that we attached was the result of calling `Thread#object_id`. That approach allows us to easily match what we see inside the Ruby process (because we can log the `Thread#object_id` where something happens) with the profile.
BUT if we wanted to match the profile with what the operating system's tooling showed, it was quite hard, because threads shown in the OS task manager tools show an OS-level thread identifier, which is not the same as the `Thread#object_id`.
To enable this matching, this PR changes the format of the `thread id` from `"#{thread.object_id}"` to `"#{thread.native_object_id} (#{thread.object_id})"` …
=> Include native thread id as part of thread id label for profiling

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c, ext/ddtrace_profiling_native_extension/ruby_helpers.c, ext/ddtrace_profiling_native_extension/ruby_helpers.h, lib/datadog/core/configuration/components.rb, lib/datadog/core/configuration/settings.rb, lib/datadog/profiling/collectors/cpu_and_wall_time_worker.rb, spec/datadog/core/configuration/components_spec.rb, spec/datadog/core/configuration/settings_spec.rb, spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
This PR:
* Adds a toggle that can be used to enable/disable the GC profiling feature added in #2336
* Enables the GC profiling feature by default on Ruby 2.x and disables the feature by default on Ruby 3.x
* Exposes a new `DD_PROFILING_FORCE_ENABLE_GC` / `settings.profiling.advanced.force_enable_gc_profiling` setting to allow customers that don't use Ractors to manually re-enable the GC profiling feature.
While validating that the new profiler correctly works with Ractors, I discovered that adding specs that invoked Ractors caused the previously-built GC profiling feature (and attached specs) to start failing.
I was able to track this down to an actual VM bug, which I've reported upstream as <https://bugs.ruby-lang.org/issues/19112>.
To avoid …
=> Disable GC profiling on Ruby 3 by default due to Ruby VM Ractor-related bug

docker-compose.yml
Update Redis image to 6.2
**Motivation**
Currently, our test suite is testing Sidekiq 5.x, in order to put the later versions of Sidekiq into our automated test suite. The image for Redis need to be updated
* Sidekiq 6.x requires Redis 4+
* Sidekiq 7.x requires Redis 6.2+
=> Upgrade Redis to 6.2

ext/ddtrace_profiling_native_extension/extconf.rb, ext/ddtrace_profiling_native_extension/private_vm_api_access.c, ext/ddtrace_profiling_native_extension/private_vm_api_access.h, ext/ddtrace_profiling_native_extension/profiling.c, spec/datadog/profiling/native_extension_spec.rb
Add a new helper to `private_vm_access.c` that allows the caller thread to ask if it's running as part of the main Ractor.
On Rubies without Ractor support, as a simplification, we always return `true` so that callers don't need to probe for Ractor support.
This helper will be used to make sure the profiler code does not run on the wrong Ractor, since the profiler code is currently not built to be called in parallel from multiple Ractors.
Hey, I added the first spec that uses Ractors to our test suite!
Test coverage included.
=> Add profiler helper for detecting if we're on the main Ractor

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time.c, ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c, lib/datadog/core/configuration/settings.rb, spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
This PR builds on top of #2350 and changes the `Collectors::CpuAndWallTimeWorker` to never trigger sampling if any of its methods get called from outside the main ractor.
This means that the profiler will not have visibility beyond the main ractor. Building support for that will come later, as we'll need to deal with the complexity of the profiler potentially being called from multiple ractors.
We don't yet support Ractors, but on an application using Ractors the profiler should not fail or misbehave. The expected behavior is that it just won't profile Ractors beyond the main one.
(Nothing)
I've included partial coverage, but testing the GC-related behavior was harder than I expected (also …
=> [PROF-5942] Disallow sampling ractors in profiler

ext/ddtrace_profiling_loader/ddtrace_profiling_loader.c, ext/ddtrace_profiling_loader/extconf.rb, ext/ddtrace_profiling_native_extension/extconf.rb
This PR enables the `-Werror` compiler flag, which turns any compiler warnings into errors, when compiling profiler C code in CI.
I also refreshed the `extconf.rb` for the `ddtrace_profiling_loader` to match the compiler flags from `ddtrace_profiling_native_extension` as well.
Most compiler warnings are quite useful at point out potential bugs, and we want to make sure our code is warning-free on all Ruby versions we support.
We don't enable `-Werror` always because we can't control what compiler our customers use. E.g. they may use a new compiler which introduces a new warning which we haven't seen and it doesn't make sense to "break" profiling for them just because of that.
**This PR is on top of …
=> [PROF-6288] Enable `-Werror` to turn compiler warnings into errors in CI

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c, lib/datadog/profiling/collectors/cpu_and_wall_time_worker.rb, spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
This PR collects fixes for two issues related to the new profiler and Ruby apps that employ fork. See individual commits for details.
We fully support Ruby applications that use fork, so I've been spending time making sure the new profiler is correct for these applications as well.
I suspect there may be a few more fixes needed before the new profiler is solid on Ruby apps that use fork, so expect more PRs on this subject.
**This PR is on top of #2358 as I wanted to avoid any conflicts, but is independent of it**
Both changes include test coverage. Additionally, the first change can be easily observed by checking that the profiler restarts successfully after a fork in a Ruby app that uses …
=> [PROF-5953] Ruby VM forking fixes for new profiler

ext/ddtrace_profiling_native_extension/stack_recorder.c, lib/datadog/profiling/exporter.rb, lib/datadog/profiling/scheduler.rb, lib/datadog/profiling/stack_recorder.rb, spec/datadog/profiling/exporter_spec.rb, spec/datadog/profiling/scheduler_spec.rb, spec/datadog/profiling/stack_recorder_spec.rb
When a Ruby app forks, we automatically restart the profiler in the child process as well. This ensures that in apps such as forking webservers we still provide full profiling coverage.
As part of automatically restarting the profiler in the child process, we want to clear any profiling data that has accumulated from the parent, as otherwise both the parent as well as the child process would report that data.
This "clearing of profiling data" happens in `Scheduler#after_fork`. Previously, this method would "clear data" by asking the exporter for the latest profile and then throwing this away.
This worked but it was rather heavy handed -- it did some useless work, as well as generated a few slightly-confusing debug logs:
```
DEBUG …
```
=> Improve clearing of profile data after Ruby app forks

lib/ddtrace/transport/trace_formatter.rb, spec/ddtrace/transport/trace_formatter_spec.rb
Removes unnecessary `peer.service` check when setting `lang` tags to ensure `lang` tags are set on all spans 
The trace-agent currently reads the language headers from the trace and extracts into the payload which the backend then expands on a span-by-span basis accordingly. Thus to have consistency, in older versions where the trace-agent does not read headers, the `lang` tag should just be set on all spans anyway.
=> Removes unnecessary peer.service check for language

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time.c, ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c, ext/ddtrace_profiling_native_extension/stack_recorder.c, lib/datadog/profiling/collectors/cpu_and_wall_time.rb, lib/datadog/profiling/collectors/cpu_and_wall_time_worker.rb, lib/datadog/profiling/collectors/old_stack.rb, lib/datadog/profiling/exporter.rb, lib/datadog/profiling/old_recorder.rb, lib/datadog/profiling/profiler.rb, lib/datadog/profiling/scheduler.rb, lib/datadog/profiling/stack_recorder.rb, lib/datadog/profiling/tasks/setup.rb, spec/datadog/profiling/collectors/cpu_and_wall_time_spec.rb, spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb, spec/datadog/profiling/collectors/old_stack_spec.rb, spec/datadog/profiling/exporter_spec.rb, spec/datadog/profiling/old_recorder_spec.rb, spec/datadog/profiling/profiler_spec.rb, spec/datadog/profiling/scheduler_spec.rb, spec/datadog/profiling/stack_recorder_spec.rb, spec/datadog/profiling/tasks/setup_spec.rb
This PR is a follow-up from work started in #2359 and continued in #2362 for fixing and improving support for Ruby VM forks in the new profiler.
When a Ruby application forks (such as the puma webserver in multiprocess mode), we automatically restart the profiler in the child processes.
But, as part of restarting we should also make sure to reset any state that is leftover from the parent process.
This PR makes sure that, for the new profiler:
1. Resetting the state is done in a safe way (e.g. without concurrency issues). This required a refactoring of how we do it.
2. There is no leftover state from the parent.
While the old profiler codepath was also affected by the refactoring in this PR, it was already doing the two steps above correctly; the changes in this …
=> [PROF-5943] Clear leftover state on new profiler after Ruby VM forks

lib/datadog/tracing/contrib/grpc/datadog_interceptor/server.rb, lib/datadog/tracing/contrib/mongodb/subscribers.rb, lib/datadog/tracing/contrib/rack/middlewares.rb, spec/datadog/tracing/contrib/grpc/datadog_interceptor/server_spec.rb, spec/datadog/tracing/contrib/mongodb/client_spec.rb, spec/datadog/tracing/contrib/rack/integration_test_spec.rb
Unified tagging `span.kind` as `server` and `client`, inspired by [Opentelemetry](https://github.com/open-telemetry/opentelemetry-specification/blob/9fa7c656b26647b27e485a6af7e38dc716eba98a/specification/trace/api.md#spankind
)
=> Unified tagging `span.kind` as `server` and `client`

lib/datadog/tracing/contrib/propagation/sql_comment.rb, spec/ddtrace/benchmark/sql_comment_propagation_spec.rb
Benchmark `mysql2` with sql comment propagation
**Without DB connection**
```
Warming up --------------------------------------
disabled     2.051k i/100ms
service     1.819k i/100ms
full     1.542k i/100ms
Calculating -------------------------------------
disabled     20.420k (±13.2%) i/s -    100.499k in   5.014070s
service     18.319k (±12.5%) i/s -     90.950k in   5.050858s
full     16.038k (±12.4%) i/s -     80.184k in   5.083800s
Comparison:
disabled:    20420.2 i/s
service:    18319.0 i/s - same-ish: difference falls within error
full:    16038.1 i/s - same-ish: difference falls within error
```
-----------------
**Without DB connection**
```    
Warming up --------------------------------------
disabled   557.000  i/100ms
service   534.000  i/100ms
full …
```
=> Benchmark SQL comment propagation with `mysql2`

.circleci/config.yml, docker-compose.yml, ext/ddtrace_profiling_loader/extconf.rb, ext/ddtrace_profiling_native_extension/extconf.rb
In #2358 we changed how the profiling native extension is built in CI by adding the `-Werror` compiler option to turn warnings into errors.
We did this automatically by checking if the `CI` environment variable was set to `true`.
Unfortunately, this broke at least one user, see <https://github.com/DataDog/datadog-api-client-ruby/pull/1137>. The warning that was triggered in that case was actually not relevant, see my investigation in <https://github.com/DataDog/dd-trace-rb/issues/2377>.
The `CI=true` was never meant to trigger outside of our CI, but clearly it's too generic of a name for us to rely on that.
To fix this, I've gone ahead and changed the configuration so that `-Werror` only gets added when `DD_PROFILING_CI=true`. I also changed our docker and …
=> [PROF-6566] Fix ddtrace installation issue when users have CI=true

Appraisals, gemfiles/ruby_3.0.3_contrib.gemfile.lock, spec/datadog/tracing/contrib/que/tracer_spec.rb
Updates the `contrib` appraisal group and associated specs to support `que` version 2.
=> Support que 2

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time.c, lib/datadog/profiling/collectors/cpu_and_wall_time.rb, spec/datadog/profiling/collectors/cpu_and_wall_time_spec.rb, spec/datadog/profiling/spec_helper.rb
This PR reimplements support for the profiling endpoint feature in the `CpuAndWallTime` collector.
Although the implementation is different, the approach is conceptually the same as provided by `Datadog::Profiling::TraceIdentifiers::Ddtrace` for the old profiler codepaths.
The constraints of this implementation are the same as the ones in #2342 and effectively this is only a small extension of the work done in that PR.
Endpoint profiling allows customers to filter down their profiles to individual endpoints (for web apps) that they may be interested in investigating.
Comparing a Ruby string with a `char *` is really annoying.
Beyond the code coverage included by the change, it can also be tested …
=> [PROF-6463] Implement support for endpoint profiling in CpuAndWallTime collector

lib/datadog/tracing/contrib/redis/instrumentation.rb, spec/datadog/tracing/contrib/redis/instrumentation_spec.rb, spec/datadog/tracing/contrib/redis/miniapp_spec.rb, spec/datadog/tracing/contrib/redis/redis_spec.rb
Tags `span.kind` of `redis` as `client`, inspired by [Opentelemetry](https://github.com/open-telemetry/opentelemetry-specification/blob/9fa7c656b26647b27e485a6af7e38dc716eba98a/specification/trace/api.md#spankind
)
=> Adds `span.kind` as `client` for `redis`

lib/datadog/tracing/contrib/delayed_job/plugin.rb, lib/datadog/tracing/contrib/redis/instrumentation.rb, spec/datadog/tracing/contrib/delayed_job/plugin_spec.rb, spec/datadog/tracing/contrib/redis/instrumentation_spec.rb, spec/datadog/tracing/contrib/redis/miniapp_spec.rb, spec/datadog/tracing/contrib/redis/redis_spec.rb
Adds `span.kind` tag for certain spans in delayed_job
Refer to [Opentelemetry](https://github.com/open-telemetry/opentelemetry-specification/blob/9fa7c656b26647b27e485a6af7e38dc716eba98a/specification/trace/api.md#spankind) for definitions of producer and consumer
The `instrument_invoke` method has been tagged with `consumer` for `span.kind`
The `instrument_enqueue` method has been tagged with `producer` for `span.kind`
=> Adds `span.kind` with values `producer` and `consumer` for `delayed_job`

lib/datadog/tracing/contrib/que/tracer.rb, lib/datadog/tracing/contrib/resque/resque_job.rb, lib/datadog/tracing/contrib/shoryuken/tracer.rb, lib/datadog/tracing/contrib/sneakers/tracer.rb, spec/datadog/tracing/contrib/que/tracer_spec.rb, spec/datadog/tracing/contrib/resque/instrumentation_spec.rb, spec/datadog/tracing/contrib/shoryuken/tracer_spec.rb, spec/datadog/tracing/contrib/sneakers/tracer_spec.rb
Adds `span.kind` tag for integrations `que`, `shoryuken`, `sneakers`, and `resque`
Refer to [Opentelemetry](https://github.com/open-telemetry/opentelemetry-specification/blob/9fa7c656b26647b27e485a6af7e38dc716eba98a/specification/trace/api.md#spankind) for definitions of consumer
These integrations uniquely only have `consumer` tags and the corresponding `producer` functions are not traced thus no span within the integration has an opposing `producer` tag.
`que`, `shoryuken`, and `sneakers` integrations have the `span.kind` tag set within the `call` function that runs jobs
`resque` has `span.kind` tag set within the `perform` function that runs jobs
=> Adds `span.kind` tag for `que`, `shoryuken`, `sneakers`, and `resque`

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c, ext/ddtrace_profiling_native_extension/private_vm_api_access.c, ext/ddtrace_profiling_native_extension/setup_signal_handler.c, ext/ddtrace_profiling_native_extension/setup_signal_handler.h, spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
This PR:
* Refactors the signal handler installation/removal/blocking code from the `CpuAndWallTimeWorker` implementation to a separate file
* Modifies the `install_sigprof_signal_handler` to receive the name of the handler being setup, so that exception messages can also include this information.
I'm working on two other signal-related changes, and extracted these commits from my branch to enable smaller reviews :)
The signal handler code has test coverage via the `CpuAndWallTimeWorker` specs. I decided to leave the tests there for now, rather than separating them out.
This is because some of these low-level behaviors are hard to test in isolation.
Existing tests already cover this change.
=> [PROF-6556] Profiler signal handler setup improvements

.circleci/images/primary/Dockerfile-2.7.6, .github/workflows/build-ruby.yml, docker-compose.yml
Allows nokogiri 1.13+ binary gems to be installed otherwise they fail on `aarch64` with:
version `GLIBC_2.29' not found
Indeed ruby:2.7.3 has libc6 2.28 and ruby:2.7.6 has libc6 2.31
Also, bundler and rubygems can now be updated as this is fixed:
https://github.com/thoughtbot/appraisal/issues/162
Needed for: https://github.com/DataDog/system-tests-apps-ruby/pull/7
=> Update to Ruby 2.7.6

ext/ddtrace_profiling_native_extension/private_vm_api_access.c
Silence a compiler warning that we can't do anything about (it's on the Ruby VM headers) and that is breaking CI (because we turn warnings into errors in CI).
We can't do anything about these warnings, so they are not interesting to see.
In particular, here's the warning I saw:
```
In file included from /usr/local/bundle/gems/debase-ruby_core_source-0.10.17/lib/debase/ruby_core_source/ruby-2.4.3-p205/method.h:14,
from /usr/local/bundle/gems/debase-ruby_core_source-0.10.17/lib/debase/ruby_core_source/ruby-2.4.3-p205/vm_core.h:67,
from ../../../../ext/ddtrace_profiling_native_extension/private_vm_api_access.c:22:
/usr/local/bundle/gems/debase-ruby_core_source-0.10.17/lib/debase/ruby_core_source/ruby-2.4.3-p205/internal.h:991:1: warning: 'const' …
```
=> Silence compiler warning in Ruby headers

.circleci/config.yml, gemfiles/ruby_2.4.10_contrib.gemfile.lock, gemfiles/ruby_2.4.10_contrib_old.gemfile.lock, gemfiles/ruby_2.4.10_core_old.gemfile.lock, gemfiles/ruby_2.4.10_cucumber3.gemfile.lock, gemfiles/ruby_2.4.10_cucumber4.gemfile.lock, gemfiles/ruby_2.4.10_hanami_1.gemfile.lock, gemfiles/ruby_2.4.10_rails5_mysql2.gemfile.lock, gemfiles/ruby_2.4.10_rails5_postgres.gemfile.lock, gemfiles/ruby_2.4.10_rails5_postgres_redis.gemfile.lock, gemfiles/ruby_2.4.10_rails5_postgres_redis_activesupport.gemfile.lock, gemfiles/ruby_2.4.10_rails5_postgres_sidekiq.gemfile.lock, gemfiles/ruby_2.4.10_rails5_semantic_logger.gemfile.lock, gemfiles/ruby_2.4.10_resque2_redis3.gemfile.lock, gemfiles/ruby_2.4.10_resque2_redis4.gemfile.lock, gemfiles/ruby_2.4.10_sinatra.gemfile.lock
Ruby 2.4 image update to Debian Buster should have used a new cache, but a CI race condition on the `binary_version` file update may have caused cache pollution with Stretch-built gems, in turn making any later attempt to use this image fail.
**Motivation**
CircleCI `test-2.4` job failing all around.
CircleCI `test-2.4` job should turn green.
=> Fix ruby 2.4 image

.circleci/images/primary/Dockerfile-jruby-9.2.21.0, .circleci/images/primary/Dockerfile-jruby-9.2.8.0, .circleci/images/primary/Dockerfile-jruby-9.3.9.0, .github/workflows/build-ruby.yml, docker-compose.yml
Built 9.3 from a buster base, vendored in to attempt to avoid any issues with bullseye.
Also, a bit of alignment on 9.2.8.0.
And removed the `-latest` suffixes as they don't mean much.
=> Update to JRuby 9.2.21.0 and 9.3.9.0

spec/datadog/core/workers/polling_spec.rb
We've all seen it: "`Datadog::Core::Workers::Polling` failed in CI, unrelated to my changes!" :shakesfist:.
I tried to fix it yesterday, but couldn't find anything wrong with it, so I propose to postpone our pains and unblock our CI.
https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/8010/workflows/6392c14c-0cb7-4f9b-9471-6b2a01780df7/jobs/297446
```
Datadog::Core::Workers::Polling when included into a worker #perform by default is expected to have received perform(*(any args)) 1 time
Failure/Error: expect(worker_spy).to have_received(:perform).at_least(:once)
(Double "worker spy").perform(*(any args))
expected: at least 1 time with any arguments
received: 0 times with any arguments
```
This PR skips this specific test, with a comment that it is flaky and requires further …
=> Temporarily disable Workers::Polling flaky test

lib/datadog/tracing/contrib/sidekiq/client_tracer.rb, lib/datadog/tracing/contrib/sidekiq/server_tracer.rb, spec/datadog/tracing/contrib/sidekiq/client_tracer_spec.rb, spec/datadog/tracing/contrib/sidekiq/server_tracer_spec.rb
Adds `span.kind` tag for integrations `sidekiq`
Refer to [Opentelemetry](https://github.com/open-telemetry/opentelemetry-specification/blob/9fa7c656b26647b27e485a6af7e38dc716eba98a/specification/trace/api.md#spankind) for definitions of consumer and producer
The client_tracer enqueues jobs in an asynchronous manner meaning that it gets the `producer` value for `span.kind`
The server_tracer completes jobs in an asynchronous manner meaning that it gets the `consumer` value for `span.kind`
Note the internal spans are not marked with span.kind but because they are edge spans, there may need to be marked with `peer.service` down the line to match [Otel](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/7cc8a21f80eb77519de0612c718d7a2702692604/instrument …
=> Adds `span.kind` tag for `sidekiq`

lib/datadog/tracing/contrib/kafka/consumer_event.rb, lib/datadog/tracing/contrib/kafka/events/produce_operation/send_messages.rb, lib/datadog/tracing/contrib/kafka/events/producer/deliver_messages.rb, spec/datadog/tracing/contrib/kafka/patcher_spec.rb
Adds `span.kind` tag for integrations `kafka`
Refer to [Opentelemetry](https://github.com/open-telemetry/opentelemetry-specification/blob/9fa7c656b26647b27e485a6af7e38dc716eba98a/specification/trace/api.md#spankind) for definitions of consumer and producer
The producer  and produce_operations files enqueues jobs in an asynchronous manner meaning that it gets the `producer` value for `span.kind`
The consumer_event super class completes jobs in an asynchronous manner meaning that it gets the `consumer` value for `span.kind`
Note that currently unable to distinguish between the spans of sending and receiving a message for kafka request under the connections folder. If that is ever more specific, we can add `span.kind` tags there
=> Adds 'span.kind' tag for 'kafka'

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c, ext/ddtrace_profiling_native_extension/setup_signal_handler.c, ext/ddtrace_profiling_native_extension/setup_signal_handler.h, spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
This PR changes the teardown behavior of the `CpuAndWallTimeWorker` collector to NOT remove its SIGPROF signal handler, and instead leave behind an empty one.
While doing other experiments with signal handling, I discovered that if the Ruby VM receives a SIGPROF signal without having a signal handler setup, it defaults to the awful UNIX/POSIX behavior of instantly dieing with a confusing "Profiling timer expired" message (that has nothing to do with our profiler).
I reasoned that because signal handling is asynchronous, the following theoretical situation may happen:
1. `CpuAndWallTimeWorker` sends SIGPROF signal
2. `CpuAndWallTimeWorker` notices request to shut down
3. `CpuAndWallTimeWorker` removes SIGPROF signal handler during teardown
4. …
=> [PROF-6556] Leave SIGPROF signal handler after disabling profiling

.circleci/config.yml
Making sure to use a dedicated cache per patch version
**Motivation**
Changing versions (even patch) sometimes comes with userland changes as well (e.g glibc gets bumped) as the base image gets updated.
This has caused some issues in the past, either directly or via cache pollution from an updated branch saving a new cache then an earlier non-updated branch picking that cache up.
So making sure to use a dedicated cache per patch version reduces potential for breakage.
This also adds a `ruby-` prefix, materialising the ruby engine in use, making it consistent with other non-MRI engines. It shoudl probably apply to job names as well, but I punted on that because of the GitHub PR merge enforcement on job names.
CI …
=> Align Ruby CI cache keys

ext/ddtrace_profiling_native_extension/collectors_stack.c
This PR slightly tweaks some of the profiler C code to avoid triggering an incorrect compiler warning, and thus breaking CI (because we turn all warnings into errors in CI).
In <https://github.com/DataDog/dd-trace-rb/issues/2377> I documented a set of compiler warnings that are incorrect. Usually having incorrect warnings is not an issue, but in CI we compile with `-Werror` to turn all warnings into errors, so we can't just ignore them.
In <https://github.com/DataDog/dd-trace-rb/pull/2408> while upgrading our Ruby images, we ran into this issue again on our own CI.
Can I go back to coding Ruby?
CI should remain green, even when using the 2.7 docker image from …
=> Tweak profiler code to avoid triggering bug in compiler warnings

.github/workflows/build-ruby.yml, .github/workflows/codeql-analysis.yml, .github/workflows/system-tests.yml, .github/workflows/test-head.yaml, .github/workflows/test-macos.yaml
Update actions to use Node 16-based ones.
**Motivation**
Node 12 actions are deprecated.
GHA CI should stay green, no deprecation notice should be shown in summaries.
=> Update actions/checkout and actions/*-artifact to Node 16

.github/workflows/test-macos.yaml
Small adjustments to this GH workflow:
- lock macOS version 
- test on multiple macOS versions
- name jobs
- rename some stuff
**Motivation**
`macos-latest` is a moving target. In fact, some jobs pick it up as `macos-12` and some seem to pick it up as `macos-11` as we get a warning.
Native libraries (e.g libddwaf) may encounter issues on specific macOS versions.
Naming is for clarity, renaming is to follow the "{verb} {something}" pattern of GH Actions
Take a peek at CI.
=> Adjust macOS testing

tasks/update_appraisal_gemfiles.rake
This PR fixes #2443 and #2444 by forcing the affected Rubies to run on older versions of bundler.
With this PR I could run `bundler exec rake install_appraisal_gemfiles` cleanly on my machine.
Make sure the `install_appraisal_gemfiles` works correctly.
(None)
Check that the affected rake tasks work correctly.
---
Fixes #2443
Fixes #2444
=> Override appraisal bundler versions on legacy rubies

docker-compose.yml, ext/ddtrace_profiling_loader/extconf.rb, ext/ddtrace_profiling_native_extension/extconf.rb, ext/ddtrace_profiling_native_extension/stack_recorder.c
This PR fixes one case where we were using a legacy style for defining a C function + explicitly enables compiler warnings for these kinds of legacy definitions.
We want to avoid the use of legacy definitions, to avoid issues moving to future compilers and/or future C language versions (C11 I'm looking at you).
For some reason `-Wall -Wextra` did not enable these compiler warnings. I'll be on the look out for more warnings that we can also enable.
=> Fix using legacy C definitions

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c, ext/ddtrace_profiling_native_extension/extconf.rb, ext/ddtrace_profiling_native_extension/private_vm_api_access.c, ext/ddtrace_profiling_native_extension/private_vm_api_access.h, ext/ddtrace_profiling_native_extension/profiling.c, ext/ddtrace_profiling_native_extension/ruby_helpers.h, ext/ddtrace_profiling_native_extension/setup_signal_handler.h, lib/datadog/core/configuration/components.rb, spec/datadog/core/configuration/components_spec.rb, spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb, spec/datadog/profiling/collectors/interesting_backtrace_helper.rb, spec/datadog/profiling/native_extension_spec.rb
While working on improving the way we trigger profiling samples on the new profiler, I discovered that the Ruby VM API `ruby_thread_has_gvl_p()` that we were using to detect if our signal handler had "landed" on the right thread was actually giving incorrect results.
Specifically, this API can still return `true` even when a thread DOES NOT HAVE the global VM lock. 
In particular, looking at the implementation, that API assumes that if a thread is not in a "blocking region" then it will have the GVL which is probably true for the situations that API was designed to be called from BUT this assumption does not hold true when calling `ruby_thread_has_gvl_p` from a signal handler. (Because the thread may have lost the GVL due to a scheduler decision, not because it …
=> [PROF-6556] Fix profiler incorrectly detecting if a thread is holding the Global VM Lock

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time.c, ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c, ext/ddtrace_profiling_native_extension/ruby_helpers.h, lib/datadog/profiling/collectors/cpu_and_wall_time_worker.rb, spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
This PR adds an inner `stats` struct to the `CpuAndWallTimeWorker` state. This is similar to what we already did for the `CpuAndWallTime` state.
Additionally, it adds 3 stats:
* `trigger_sample_attempts`
* `signal_handler_enqueued_sample`
* `signal_handler_wrong_thread`
and starts keeping track of them.
I'm currently working on changing the profiler to send a SIGPROF signal not to the whole process as we do currently, but to the specific thread that owns the Global VM Lock. (See #2415 for some of the groundwork for this).
But, testing such a change is kinda hard! How do you test that you're now sending signals to a specific thread instead of the whole process?
I decided to approach the testing by looking at stats: for an example that is known to …
=> [PROF-6556] Add stat tracking to `CpuAndWallTimeWorker`

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c, ext/ddtrace_profiling_native_extension/profiling.c, ext/ddtrace_profiling_native_extension/setup_signal_handler.c, ext/ddtrace_profiling_native_extension/setup_signal_handler.h, lib/datadog/profiling/collectors/cpu_and_wall_time_worker.rb, spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb, spec/datadog/profiling/collectors/interesting_backtrace_helper.rb
[PROF-6556] Fix profiler issue due to Ruby native thread reuse
This PR fixes an issue that caused Ruby threads to inherit SIGPROF blocking from the `CpuAndWallTimeWorker` worker thread.
The issue is caused by an interaction with Ruby's native thread cache. When a Ruby `Thread` dies, Ruby does not immediately kill the underlying OS native thread.
Instead, it keeps it around for some time, and if another Ruby `Thread` starts in the meanwhile, it reuses the OS native thread, rather than getting a new one.
This can be observed easily starting on Ruby 3.1+ which actually added a method to observe the native thread id:
```ruby
puts RUBY_DESCRIPTION
puts Thread.new { Thread.current.native_thread_id }.value
puts Thread.new { Thread.current.native_thread_id }.value
puts …
```
=> [PROF-6556] Fix profiler issue due to Ruby native thread reuse

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c, spec/datadog/profiling/integration_spec.rb, spec/datadog/profiling/tasks/setup_spec.rb
This PR adds a new global variable, `active_sampler_instance_state`, that is easier and cheaper to access during profiling to look up and record information. It then changes previous usages of `active_sampler_instance` to use this new one directly.
Finally, the `active_sampler_owner_thread` global variable was removed, and it was moved inside the state.
When the profiler is enabled, it keeps a reference to its state on a global variable. This is needed because in some contexts (e.g. signal handling) we don't have a good way to pass in the current state as an argument.
Up until now, we were only storing the `active_sampler_instance`, e.g. the Ruby `VALUE` from which we can extract the `CpuAndWallTimeWorker` state.
But... this got really awkward, …
=> [PROF-6556] Refactor profiling global variables

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c, spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
This PR changes the `CpuAndWallTimeWorker` so that it triggers sampling by sending a SIGPROF signal directly to the thread that is holding the Global VM Lock.
Previously, we would instead send a SIGPROF to the entire Ruby process.
Note that reading the GVL owner and sending them a signal is a race -- the Ruby VM keeps on executing while we're doing this, so we may still not signal the correct thread from time to time, but the profiler is built to handle this correctly.
The previous "send a SIGPROF to the entire process" approach could cause the profiler to miss a lot of samples, because the signal handler would not be called on the right thread.
I observed that at least on my local development machine, the signals tended to land on the Ruby main …
=> [PROF-6556] Directly send SIGPROF signals to thread holding Global VM Lock

.rubocop.yml, lib/datadog/tracing/distributed/trace_context.rb, lib/datadog/tracing/sampling/priority_sampler.rb, lib/datadog/tracing/trace_digest.rb, spec/datadog/tracing/distributed/trace_context_spec.rb, spec/datadog/tracing/sampling/priority_sampler_spec.rb, spec/datadog/tracing/trace_digest_spec.rb
This PR adds support trace propagation through the the "W3C Trace Context": https://www.w3.org/TR/trace-context/.
This standard is used by OpenTelemetry to propagate traces by default.
This PR adds the propagator class **but does not wire it yet**, as to make this PR smaller to review.
=> Add W3C Trace Context propagator

spec/datadog/profiling/integration_spec.rb
In 7930f62bef08f1f5c7a76742bee51b74655391cd I changed the profiling integration spec to avoid warnings coming from the tracer trying to report data and failing.
This PR reverts that change, and instead configures the tracer with a test adapter, so it accomplishes the same objective without the weird approach of calling `shutdown!` in the middle of a trace.
This makes the `profiling/integration_spec.rb` work correctly and not emit any log messages during execution.
(N/A)
Validate that CI is still green and that the
`profiling/integration_spec.rb` runs without outputting any extra messages to stdout/stderr.
=> Fix profiling integration spec not shutting down tracer correctly

lib/datadog/tracing/contrib/grpc/distributed/propagation.rb, lib/datadog/tracing/contrib/http/distributed/propagation.rb, spec/datadog/tracing/contrib/grpc/distributed/propagation_spec.rb, spec/datadog/tracing/contrib/http/distributed/propagation_spec.rb
This PR adds support for the newly introduced [W3C Trace Context propagator](https://github.com/DataDog/dd-trace-rb/pull/2451).
This means that it is now possible to use the propagation style `tracecontext`, introduced in #2454, as a valid propagation style.
=> Wire W3C propagator to HTTP & gRPC propagation

lib/datadog/tracing/distributed/trace_context.rb, spec/datadog/tracing/distributed/trace_context_spec.rb
I looked at our internal RFC and found a few cases where we could process invalid `traceparent` headers:
1. Hex integers that are too large or too small are not allowed.
2. Trailing whitespace is allowed.
=> Extra testing from W3C spec

lib/datadog/tracing/distributed/trace_context.rb, spec/datadog/tracing/distributed/trace_context_spec.rb
Recent spec change: `;` are not allowed characters in the `origin` propagation field. They are replaced with `_`, as are all other disallowed characters.
=> Semicolons not allwed in 'origin'

ext/ddtrace_profiling_native_extension/NativeExtensionDesign.md, ext/ddtrace_profiling_native_extension/profiling.c, ext/ddtrace_profiling_native_extension/ruby_helpers.c, ext/ddtrace_profiling_native_extension/ruby_helpers.h, ext/ddtrace_profiling_native_extension/stack_recorder.c, spec/datadog/profiling/native_extension_spec.rb
While working on other parts of the profiler, I observed that if the `serializer_flip_active_and_inactive_slots` function in `stack_recorder.c` tried to raise an exception, the Ruby VM could crash.
**Fortunately, the `StackRecorder` is only used on the new profiler codepath, which is still considered in alpha state and off by default**. Furthermore, the exceptions would only happen in cases that are not expected to ever happen in production.
The crash was caused by the fact that `serializer_flip_active_and_inactive_slots` is called without the Global VM Lock being held, and it's not valid to try to raise exceptions in this state.
To fix this, and because I still find raising exceptions to be useful in the native parts of the profiler, I've introduced two new …
=> Fix unsafely raising exceptions without global VM lock in new profiler

lib/datadog/tracing/metadata/ext.rb, spec/datadog/tracing/contrib/grape/tracer_spec.rb, spec/datadog/tracing/contrib/http/request_spec.rb, spec/datadog/tracing/contrib/mongodb/client_spec.rb, spec/datadog/tracing/contrib/mysql2/patcher_spec.rb, spec/datadog/tracing/contrib/rack/integration_test_spec.rb, spec/datadog/tracing/contrib/rails/cache_spec.rb, spec/datadog/tracing/contrib/rails/middleware_spec.rb, spec/datadog/tracing/contrib/redis/shared_examples.rb
What does this PR do?
Renames the `error.msg` tag to `error.message` tag in order to meet the requirements of naming across all tracers.
=> Changes `error.msg` to `error.message` for UNC

ext/ddtrace_profiling_native_extension/profiling.c, ext/ddtrace_profiling_native_extension/ruby_helpers.c, ext/ddtrace_profiling_native_extension/ruby_helpers.h, ext/ddtrace_profiling_native_extension/setup_signal_handler.c, ext/ddtrace_profiling_native_extension/stack_recorder.c, spec/datadog/profiling/native_extension_spec.rb
This PR introduces two new helpers in the profiler native code -- `ENFORCE_SUCCESS_GVL` and `ENFORCE_SUCCESS_NO_GVL` and updates existing code to use it.
Constantly checking for errors on system APIs such as `pthread_mutex_lock` is a lot of boiler plate that constantly breaks the flow of the code.
I decided to take a stab at improving this by introducing the new helpers.
The new helpers usually contain all of the information needed to tie the error back to where it came from in the native code. Here is one such example:
```
Errno::EINTR: Interrupted system call - Failure returned by 'syserr_errno' at
../../../../ext/ddtrace_profiling_native_extension/profiling.c:246:in `trigger_enforce_success'
```
Note that it includes:
* …
=> Simplify system API error handling in profiler

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c, ext/ddtrace_profiling_native_extension/collectors_idle_sampling_helper.c, ext/ddtrace_profiling_native_extension/collectors_idle_sampling_helper.h, ext/ddtrace_profiling_native_extension/private_vm_api_access.c, ext/ddtrace_profiling_native_extension/profiling.c, ext/ddtrace_profiling_native_extension/ruby_helpers.h, ext/ddtrace_profiling_native_extension/setup_signal_handler.c, lib/datadog/profiling.rb, lib/datadog/profiling/collectors/cpu_and_wall_time_worker.rb, lib/datadog/profiling/collectors/idle_sampling_helper.rb, lib/datadog/profiling/stack_recorder.rb, spec/datadog/profiling/collectors/cpu_and_wall_time_spec.rb, spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb, spec/datadog/profiling/collectors/idle_sampling_helper_spec.rb, spec/datadog/profiling/collectors/stack_spec.rb, spec/datadog/profiling/stack_recorder_spec.rb
This PR finishes the work started in #2415 and #2438.
In particular, #2415 ("[PROF-6556] Fix profiler incorrectly detecting if a thread is holding the Global VM Lock") opened a bit of a can of worms, because we learned (and fixed) that we were asking the VM to sample in situations where we don't think it's safe.
Furthermore, we also learned that we could not sample when the application was idle. This caused, among other things, several `CpuAndWallTimeWorker` specs to be flaky, because sometimes we got unlucky and could not sample/sample enough during the spec.
This PR actually makes us able to take samples in periods of idleness in the Ruby VM, and also solves a bunch of flakiness in specs that missing this feature introduced.
In a first approach, I thought …
=> [PROF-6556] Fix new alpha profiler not being able to sample in periods of idleness

lib/datadog/tracing/contrib/mysql2/instrumentation.rb, lib/datadog/tracing/contrib/pg/instrumentation.rb, lib/datadog/tracing/contrib/propagation/sql_comment.rb, lib/datadog/tracing/contrib/propagation/sql_comment/ext.rb, spec/datadog/tracing/contrib/propagation/sql_comment_spec.rb, spec/datadog/tracing/contrib/sql_comment_propagation_examples.rb
Implement SQL comment propagation with `full` mode, which includes `traceparent`
=> SQL comment propagation full mode with traceparent

lib/datadog/tracing/contrib/patcher.rb, lib/datadog/tracing/contrib/redis/integration.rb, lib/datadog/tracing/contrib/redis/patcher.rb, spec/datadog/tracing/contrib/redis/integration_spec.rb, spec/datadog/tracing/contrib/redis/patcher_spec.rb
Until `redis` 4, all instrumentation happened in one gem: `redis`. Since `redis` 5, instrumentation happens in a separate gem: `redis-client`. Because `redis` 4 does not depend on `redis-client`, it's possible for both gems to be installed at the same time. 
For example, if `sidekiq` 7 and `redis` 4 are installed: both `redis` and `redis-client` will be installed.
This implementation improves the patching condition to apply to whenever it is possible.
PS. The minimun `redis-client` supported would be `0.11.0`, where `Config#custom` is implemented.
=> Improve redis integration patching

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time.c, spec/datadog/profiling/collectors/cpu_and_wall_time_spec.rb, spec/datadog/profiling/spec_helper.rb
This PR changes the `span id` sent in profiling data (and used to power the "Code Hotspots" tab when viewing a trace) as a number in the underlying pprof, instead of as a string.
The numeric representation is smaller and also avoids needing to use the string table to represent this information.
We've wanted to do this change for a while, but only now was the profiling backend extended to support this.
The `local root span id` is still recorded as a string because there's a feature in libdatadog that relies/assumes this string representation.
I plan to later change libdatadog at a later time to allow us to send both values as a number.
This change affects only the new (still in alpha) Ruby profiler codepath, and thus is not …
=> [PROF-6691] Send span id in profiles as number and not string

docs/GettingStarted.md, lib/datadog/tracing/contrib/grpc/distributed/propagation.rb, lib/datadog/tracing/contrib/http/distributed/propagation.rb, lib/datadog/tracing/distributed/none.rb, spec/datadog/tracing/contrib/grpc/distributed/propagation_spec.rb, spec/datadog/tracing/contrib/http/distributed/propagation_spec.rb, spec/datadog/tracing/distributed/b3_single_spec.rb, spec/datadog/tracing/distributed/datadog_spec.rb, spec/datadog/tracing/distributed/none_spec.rb, spec/datadog/tracing/distributed/propagation_spec.rb, spec/datadog/tracing/distributed/trace_context_spec.rb
I noticed, while adding a new propagator style, that `spec/datadog/tracing/contrib/grpc/distributed/propagation_spec.rb` & `spec/datadog/tracing/contrib/http/distributed/propagation_spec.rb` were not failing tests when I accidentally removed existing propagator styles from their configuration.
This happened because those tests were testing the style classes directly, `Distributed::B3Multi.new(fetcher: Contrib::GRPC::Distributed::Fetcher)`, instead of through the Propagation class, `Contrib::GRPC::Distributed::Propagation.new`.
This PR makes those test cover the same test surface, but by using the respective `Propagation` class instead.
Now, there should be no coverage lacking in distributed tracing propagation.
=> Test Propagation class instead of styles directly

spec/datadog/tracing/contrib/grape/tracer_spec.rb
This is an old flaky test that doesn't happen super often but does happen still: https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/8259/workflows/4ad2adbf-5954-471a-bf16-6584d79e913d/jobs/307083/parallel-runs/21?filterBy=FAILED
I tried my best to debug it, but couldn't find out why. And I couldn't reproduce it either.
I'm instead then adding additional debug information in the event of a CI failure.
=> Add debug information for flaky grape test

spec/datadog/core/workers/runtime_metrics_spec.rb, spec/datadog/tracing/contrib/presto/client_spec.rb, spec/datadog/tracing/contrib/redis/integration_test_spec.rb, spec/datadog/tracing/contrib/sidekiq/support/helper.rb, spec/datadog/tracing/integration_spec.rb, spec/datadog/tracing/workers/trace_writer_spec.rb, spec/support/synchronization_helpers.rb
While adding a `try_wait_until` of 10 seconds to https://github.com/DataDog/dd-trace-rb/pull/2477 I noticed how opaque the configuration options are for `try_wait_until`.
This PR adds a hopefully simpler to reason about `seconds` configuration option.
Instead of configuring `try_wait_until(attempts: 100, backoff: 0.1)` we can now do `try_wait_until(seconds: 10)`: these two scenarios yield the same configuration to `try_wait_until`.
=> Allow try_wait_until to be configured with seconds

spec/datadog/tracing/contrib/sidekiq/server_internal_tracer/heartbeat_spec.rb, spec/datadog/tracing/contrib/sidekiq/support/helper.rb
* Add spec  for `sidekiq.stop` , which was previously skipped, https://github.com/DataDog/dd-trace-rb/pull/2441
* Fix `sidekiq.heartbeat` wait until condition
* Tweak for speed and streamline some setup
=> Spec for `sidekiq.stop`

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c, ext/ddtrace_profiling_native_extension/extconf.rb, ext/ddtrace_profiling_native_extension/native_extension_helpers.rb
This PR introduces the use of C atomic primitives to the profiling native extension.
In particular, it:
* Adds checking at gem installation time that the C atomic primitives are available (and a suitable user-friendly error message when they aren't)
* Converts the `volatile bool should_run` into an atomic type. I've wanted to do this for some time (even left a comment about it) but didn't want to venture into atomic types until now.
I'm preparing to introduce dynamic sampling rate into the profiler, and my plans will require atomic types, so I decided to start with a small PR to ensure we could use them without issues.
(N/A)
There were no behavior changes, so the existing test coverage should be …
=> [PROF-6557] Groundwork for using C atomic primitives

lib/datadog/core/configuration/components.rb, lib/datadog/core/configuration/settings.rb, spec/datadog/core/configuration/components_spec.rb
We previously only enabled GC profiling by default on Ruby 2.x (we disabled it on 3.x due to a bug, see #2354).
This PR changes the profiling configuration to never enable GC profiling by default (thus bringing the Ruby 2.x and 3.x defaults into sync).
I've had one new Ruby profiler alpha user report that GC profiling had a quite big overhead, and I could replicate the issue on a GC-heavy benchmark.
Since we'd like to get the new Ruby profiler out into customer's hands in beta, I decided to disable this feature by default, and come back to it after beta is out.
GC profiling can still be enabled via configuration.
Change includes test coverage. Furthermore, profiling any application will no longer …
=> Temporarily disable GC profiling by default in new Ruby profiler due to overhead

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time.c, ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c, spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
This PR adds tracking of the min, max and total wall-time that the profiler spent sampling.
For now this is exposed as `#stats` and not particularly recorded or sent anywhere.
I'm preparing to introduce dynamic sampling rate into the profiler, and as part of it, I'll need to use the time the profiler spent sampling to decide how often the profiler runs.
For a long time I've wanted to add these stats for debugging and analysis so I decided to do a small PR to add them first, and then later have the dynamic sampling rate PR rely on them as well.
(N/A)
Change includes code coverage.
=> [PROF-6557] Record stats for time spent sampling in new profiler

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c, ext/ddtrace_profiling_native_extension/collectors_dynamic_sampling_rate.c, ext/ddtrace_profiling_native_extension/collectors_dynamic_sampling_rate.h, ext/ddtrace_profiling_native_extension/profiling.c, lib/datadog/profiling.rb, lib/datadog/profiling/collectors/dynamic_sampling_rate.rb, lib/datadog/profiling/collectors/idle_sampling_helper.rb, spec/datadog/profiling/collectors/dynamic_sampling_rate_spec.rb
This PR adds a dynamic sampling rate implementation for the new profiler. The old profiler implementation already included a similar strategy, and it has been serving us quite well.
To more easily test and document the new feature, even though in the end it's not that much code, I chose to implement it in a separate module -- `Collectors::DynamicSamplingRate`.
This module gets called by the `CpuAndWallTimeWorker` at key times during sampling and in the loop that triggers sampling, so that its internal tracking gets taken into account.
Our profilers get deployed in quite unpredictable situations in terms of system resources. While they can provide key information to help customers solve their performance problems, the profilers must always be …
=> [PROF-6557] Implement dynamic sampling rate for new profiler

README.md, docs/GettingStarted.md
As the 1.x ddtrace series has been released for quite some time, thus the phrasing `We've recently released the 1.x version series` is no longer accurate.
Also the banner was placed at the very top of our documentation pages, which I believe is not longer needed.
This PR moves the banner to the first actual documentation section and rephrases the "recently released" language.
=> Update banner on 1.0 upgrade guide

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c, lib/datadog/core/configuration/components.rb, spec/datadog/core/configuration/components_spec.rb
This PR collects a few small changes needed before releasing the new Ruby profiler bits ("CPU Profiling 2.0") as opt-in (that is, disabled by default) public beta.
I recommend reviewing commit-by-commit.
We're finally ready to start telling customers they can enable this new mode.
(N/A)
Change includes test coverage (the little code that is affected).
=> [PROF-6559] Mark Ruby CPU Profiling 2.0 as being in beta

docs/GettingStarted.md
Add `full` mode for SQL comment propagation in documentation
=> Add `full` mode for SQL comment propagation in documentation

lib/datadog/core/configuration/base.rb, lib/datadog/core/configuration/option_definition.rb, lib/datadog/core/configuration/settings.rb, lib/datadog/tracing/configuration/settings.rb, spec/datadog/core/configuration/base_spec.rb, spec/datadog/core/configuration/option_definition_spec.rb, spec/datadog/core/configuration/settings_spec.rb, spec/datadog/tracing/configuration/settings_spec.rb
Moves `agent.port` setting to `Tracing::Configuration::Settings`.
To do this, it decorates the `agent` settings defined in `Core::Settings` with `port`, thus preserving existing functionality.
**Motivation**
I want to isolate tracing-specific features and supporting code within the `datadog/tracing` directory. This will reduce `Core`'s knowledge of `Tracing`, thereby reducing complexity.
This should not contain any breaking changes, despite moving code from `Core` to `Tracing`.
Depends on #2493. Merge that first.
=> Move `agent.port` to `Tracing::Configuration::Settings`

lib/datadog/tracing/distributed/trace_context.rb, lib/datadog/tracing/trace_digest.rb, spec/datadog/tracing/distributed/trace_context_spec.rb, spec/datadog/tracing/trace_digest_spec.rb
Unknown Datadog-specific fields should be propagated as-is, as they might belong to future versions Datadog Tracers.
`ddtrace`'s job is to simply pass the them downstream with the same incoming values.
=> W3C: Propagate unknown values as-is

lib/datadog/tracing/contrib/http/distributed/fetcher.rb, spec/datadog/tracing/contrib/http/distributed/fetcher_spec.rb
While working with OpenTelemetry, I noticed their propagator is flexible when working with [Rack HTTP headers](https://github.com/rack/rack/blob/a7d56490fd2fb41de8c94ead2f63fbad71c5c489/SPEC.rdoc?plain=1#L63-L73).
Our HTTP propagator has always only matched headers that are formatted as `HTTP_MY_HEADER_NAME`. This means it was not possible to perform simple matches, like `my-header-name`.
Because it's possible to do both at the same time with almost guarantee safety, this PR does that.
The only conflicting case is if both `my-header-name` and `HTTP_MY_HEADER_NAME` are present in the environment. In such case, we prefer to perform the exact match: `my-header-name`.
I believe this will have no effect on current users.
=> Flexible header matching for HTTP propagator

integration/images/ruby/2.3/Dockerfile, integration/images/ruby/2.4/Dockerfile, integration/images/ruby/2.5/Dockerfile, integration/images/ruby/2.6/Dockerfile, integration/images/ruby/2.7/Dockerfile, integration/images/ruby/3.0/Dockerfile, integration/images/ruby/3.1/Dockerfile, integration/images/ruby/3.2/Dockerfile
With the release of RubyGems 3.4.0, `gem update --system` gets confused in older versions of Ruby and tries to install the latest version, which is [not compatible with older rubies](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/8440/workflows/f4589780-3c72-4dd4-810e-af908e9d6da3/jobs/313812):
```
Step 8/15 : RUN gem update --system
---> Running in f24e823e31e6
ERROR:  Error installing rubygems-update:
There are no versions of rubygems-update (= 3.4.1) compatible with your Ruby & RubyGems
rubygems-update requires Ruby version >= 2.6.0. The current ruby version is 2.5.9.229.
```
This PR locks the version of RubyGems we upgrade to in each integration test environment.
=> Lock gem upgrade version for integration tests

.github/workflows/check.yml, .github/workflows/test-head.yaml, .github/workflows/test-macos.yaml
Upgrade to release https://github.com/ruby/setup-ruby/releases/tag/v1.131.0, titled "Use the correct Bundler version depending on the target Ruby version".
This should fix our GitHub Action CI failures due to bundler version mismatches.
=> Action:Upgrade setup-ruby to fix bundler version matching

.circleci/config.yml, .circleci/images/primary/Dockerfile-3.2.0, .github/workflows/build-ruby.yml, docker-compose.yml
Move from the preview ruby image to the final one.
**Motivation**
So we can base ourselves on the latest thing to make things pass.
CircleCI test is still disabled as tests don't pass yet, so we can change that right away as well without caring about the image being published.
This should build the image in CI. As always publishing is done later.
Image can also be built locally as always, and then tested using docker compose:
```
docker buildx build . --platform linux/$(uname -m | sed 's/arm64/aarch64/') -f Dockerfile-3.1.1 -t ghcr.io/datadog/dd-trace-rb/ruby:3.1.1-dd
docker-compose run --rm tracer-3.2 /bin/bash
```
=> Move to Ruby 3.2.0 final

.circleci/config.yml
The CI Rubocop job (`lint`) has been running at [99% memory recently](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/8450/workflows/552247af-bfb0-4a9d-9a96-d2856fcb0ac8/jobs/314215/resources):
Sometimes, it fails with `Parallel::DeadWorker`, likely due to out of memory errors.
This PR bumps up the machine size from 2Gb, to 6Gb (our default). I skipped the 4Gb runner because it would add combination of runners to our `config.yml`, and the 6Gb runner is also faster (more CPU) so there are still benefits to it.
=> Lint: Rubocop running out of memory in CI

.rubocop_todo.yml, spec/datadog/core/workers/async_spec.rb, spec/datadog/tracing/benchmark/support/benchmark_helper.rb, spec/datadog/tracing/contrib/rails/rack_spec.rb
Fixes old cop infraction from `.rubocop_todo.yml`.
=> Lint: Fix Lint/ConstantDefinitionInBlock occurrences

.rubocop_todo.yml, spec/datadog/tracing/contrib/grpc/support/grpc_helper.rb
Fixes old cop infraction from `.rubocop_todo.yml`.
=> Lint: Fix Lint/Void occurrences

.circleci/config.yml, Gemfile, Rakefile
Codecov has deprecated language-specific uploaders, include the [Ruby gem](https://github.com/codecov/codecov-ruby) we use: https://about.codecov.io/blog/codecov-uploader-deprecation-plan/
This PR follows the [Deprecated Uploader Migration Guide](https://docs.codecov.com/docs/deprecated-uploader-migration-guide#ruby-uploader) steps, now uploading an `xml` format coverage report using [Codecov's CircleCI Orb](https://circleci.com/developer/orbs/orb/codecov/codecov).
There are no behaviour changes in this PR.
=> Test: Migrate to Codecov Uploader

ddtrace.gemspec
Allow using the latest `debase-ruby_core_source` together with dd-trace-rb.
As discussed in #1740, we decided to pin the range of versions of `debase-ruby_core_source` we use, so that we can validate each version as it comes out.
The changes on 3.2.0
(<https://my.diffend.io/gems/debase-ruby_core_source/0.10.18/3.2.0>) don't impact dd-trace-rb, because they only affect Ruby 3.2.0 and 2.0.0 and we don't use `debase-ruby_core_source` on Ruby >= 2.6 (nor support Ruby 2.0).
Nevertheless, it's important we keep our version up-to-date as customers may need the latest version of `debase-ruby_core_source` for other gems they use.
~CI is breaking for Ruby 3.2 for an unrelated reason.~ Update: fixed.
CI …
=> Allow `debase-ruby_core_source` 3.2.0 to be used

integration/images/ruby/3.2/Dockerfile
Update the integration apps `Dockerfile` for Ruby 3.2 to use the latest stable release (3.2.0 as of this writing, but newer releases will be automatically picked up).
Make sure integration apps are running fine on Ruby 3.2.
~The CI failure (https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/8490/workflows/96149110-10e1-4042-8bb2-07023fd1bb66/jobs/315673) may look related (because it's also for 3.2) but it actually is unrelated -- we use different images for the integration apps.~
~The CI failure instead is due to #2510 and is affecting every PR right now (for instance [this other PR](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/8482/workflows/f8cfb120-aef9-4eea-8817-99ced812dffe/jobs/315376)).~ …
=> Use stable Ruby 3.2 when testing integration apps

lib/datadog/core/configuration/settings.rb
Add missing documentation to settings.rb.
This is a setting that most customers should never need to touch, but if they need to, it's helpful to document that they can also use an environment variable.
(N/A)
Check that API documentation includes the newly-added information :)
=> Minor: Document that `DD_PROFILING_MAX_FRAMES` can be used to configure profiling `max_frames`

ddtrace.gemspec, ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time.c, ext/ddtrace_profiling_native_extension/collectors_stack.c, ext/ddtrace_profiling_native_extension/collectors_stack.h, ext/ddtrace_profiling_native_extension/http_transport.c, ext/ddtrace_profiling_native_extension/libdatadog_helpers.h, ext/ddtrace_profiling_native_extension/stack_recorder.c, ext/ddtrace_profiling_native_extension/stack_recorder.h, spec/datadog/profiling/http_transport_spec.rb
Upgrade dd-trace-rb to use the latest libdatadog release (1.0.1.1.0).
This libdatadog release includes:
* A number of API renames (documented in <https://github.com/DataDog/libdatadog/pull/73>)
* The addition of `endpoint_counts`, which we don't use yet, but that needed a few additional changes to API calls and specs.
Keep up with latest improvements and features being added to libdatadog.
I've skipped packaging the libdatadog 1.0.0 release, and we're going straight to 1.0.1.
~~I'm opening this PR as a draft because libdatadog 1.0.1.1.0 has not yet been published to rubygems (hence our CI failing with this PR). Once I've published it, I'll re-trigger CI and remove the draft label with no further changes.~~ Update: Published, …
=> [PROF-6838] Upgrade to libdatadog 1.0.1.1.0

.circleci/images/primary/Dockerfile-2.1.10, .circleci/images/primary/Dockerfile-2.2.10, .circleci/images/primary/Dockerfile-2.3.8, .circleci/images/primary/Dockerfile-2.4.10, .circleci/images/primary/Dockerfile-2.5.9, .circleci/images/primary/Dockerfile-2.6.10, .circleci/images/primary/Dockerfile-2.7.6, .circleci/images/primary/Dockerfile-3.0.4, .circleci/images/primary/Dockerfile-3.1.2, .circleci/images/primary/Dockerfile-3.2.0, .circleci/images/primary/Dockerfile-jruby-9.2.21.0, .circleci/images/primary/Dockerfile-jruby-9.2.8.0, .circleci/images/primary/Dockerfile-jruby-9.3.9.0, .circleci/images/primary/Dockerfile-jruby-9.4.0.0, .circleci/images/primary/Dockerfile-truffleruby-22.3.0
Pin rubygems and bundler to last known compatible versions for old rubies
**Motivation**
Newer rubygems and bundler versions require 2.6
Removed a duplicate install of bundler from jruby.
Images should build in CI.
=> Pin bundler and rubygems fro Rubies < 2.6

spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
This PR tweaks a profiling spec that caused flakiness in CI:
* Ruby 2.4: <https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/8534/workflows/68f4694f-e9d1-4106-9662-a9f0a747eec7/jobs/317412/tests#failed-test-0>
* Ruby 2.3: <https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/8545/workflows/8eda1b26-3959-4c89-94e6-b2a94f0bbd78/jobs/317806>
* Ruby 2.6: <https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/8534/workflows/68f4694f-e9d1-4106-9662-a9f0a747eec7/jobs/317421/tests#failed-test-0>
This spec by design cannot escape some potential for flakiness, since it starts the profiler and then is checking some stats on how it did, and asserting on them.
In the failed cases, it looks like in the given time period the profiler did not manage …
=> Tweak flaky profiling spec

integration/images/include/build_ddtrace_profiling_native_extension.rb
This PR is a follow-up of #2535 and fixes the same issue, but this time in the integration apps (I missed fixing them on that other PR...).
@TonyCTHsu reported an issue where compilation was failing in the integration apps, and upon analysis the issue was the following:
1. When the `build_ddtrace_profiling_native_extension.rb` step runs to setup the integration apps, it ran `rake compile`, which generated a `Makefile` for profiling. This `Makefile` included hardcoded paths for `libdatadog` version 0.9.
2. Then I merged the upgrade to `libdatadog` 1.0 to master, and he pulled this update.
3. When running the integration apps, the `build_ddtrace_profiling_native_extension.rb` step re-ran, but it reused the existing `Makefile`. This existing `Makefile` was using …
=> Fix leftover profiling `Makefile` breaking integration app run

.rubocop.yml
Have Rubocop ignore `vendor/bundle`
**Motivation**
Depending on one's setup, `vendor/bundle` may be used to install gems per project. Rubocop looks recursively into subfolders for additional `.rubocop.yml`, which is not going to work.
See https://github.com/rubocop/rubocop/issues/9832
The error I encountered (spurious cop notices + missing `panolint` gem):
```
bundle exec rake rubocop
Running RuboCop...
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file.
Please also note that you can opt-in to new cops by default by adding this to your config:
AllCops:
NewCops: enable
Gemspec/DeprecatedAttributeAssignment: # new in 1.30
Enabled: true
Gemspec/RequireMFA: …
```
=> Ignore `vendor/bundle` for rubocop

ddtrace.gemspec, ext/ddtrace_profiling_native_extension/native_extension_helpers.rb, spec/datadog/profiling/native_extension_helpers_spec.rb
This PR fixes an issue I spotted recently relating to the libdatadog version that gets picked during profiler build.
Specifically, I had the following setup:
* Two versions of the libdatadog gem locally installed (1.0.1.1.0, 0.9.0.1.0)
* I tried to install ddtrace 1.8.0 from rubygems
The ddtrace 1.8.0 release has a dependency on libdatadog 0.9.x.
But, what I observed is that building the profiler (and thus installing ddtrace) failed because the profiling native extension was trying to compile and link to libdatadog 1.0.x instead of 0.9.x.
Upon investigation, I've discovered that the issue is that the `extconf.rb` script (which gets called by rubygems during installation) is not run with the equivalent of `bundle exec`, e.g. it can access all gems (and versions) …
=> [PROF-6900] Fix wrong libdatadog version being picked during profiler build

.circleci/images/primary/Dockerfile-2.1.10, .circleci/images/primary/Dockerfile-2.2.10, .circleci/images/primary/Dockerfile-2.6.10, .circleci/images/primary/Dockerfile-2.7.6, .circleci/images/primary/Dockerfile-3.1.2, .circleci/images/primary/Dockerfile-3.2.0, .circleci/images/primary/Dockerfile-jruby-9.2.21.0, .circleci/images/primary/Dockerfile-jruby-9.2.8.0, .circleci/images/primary/Dockerfile-jruby-9.3.9.0, .circleci/images/primary/Dockerfile-jruby-9.4.0.0, .circleci/images/primary/Dockerfile-truffleruby-22.3.0
- pin bundler
- remove an env var that causes confusion
**Motivation**
Things (including appraisal command) are broken with 2.4!
- Images should generate properly
- Images should not have bundler 2.4
- Images should install gems in /usr/local/bundle whether via `gem install` or `bundle install`.
=> Pin bundler to 2.3

lib/datadog/ci/ext/environment.rb
Fixes a copy-paste error where the wrong env var was being used to compute the pipeline URL for TeamCity.
=> [ci visibility] Fix copy-paste error in teamcity env vars

Steepfile, lib/datadog/kit/enable_core_dumps.rb, lib/datadog/kit/events.rb, lib/datadog/kit/identity.rb, sig/datadog/kit/enable_core_dumps.rbs, sig/datadog/kit/events.rbs, sig/datadog/kit/identity.rbs, sig/datadog/tracing/event.rbs, sig/datadog/tracing/metadata/tagging.rbs, sig/datadog/tracing/trace_operation.rbs, sig/datadog/tracing/trace_segment.rbs, spec/datadog/kit/events_spec.rb
Implement event sugar API for users to emit either login events or custom business events to be tracked.
**Motivation**
These events are a key feature that Sqreen had and enabled higher level analysis and partially to fully automated security response.
Just as with `Datadog::Kit::Identity#set_user` this looks like convenience syntactic sugar. Nonetheless, just as with `set_user`, wrapping the tag keys allows for these keys to evolve, or even the transport mechanism to change.
In addition, blocking may be handled and triggered, which is probably a feature we don't want in `set_tag`!
There are a bunch of specs added.
=> Add event kit API

lib/datadog/core/diagnostics/environment_logger.rb, spec/datadog/core/diagnostics/environment_logger_spec.rb
This PR adds a `profiling_enabled` entry in the environment logger output, which reflects the current configuration for profiling.
This was requested internally as being useful to support, and at least Node and Java already provide this key.
We also had a TODO for it, so one less TODO.
I hesitated between adding the configuration of the profiler being on, or the profiler actually being on (e.g. it's possible that the profiler has been requested on, but can't be enabled because for instance google-protobuf is missing).
My thinking is that the information about if the profiler really is on could be instead relayed via telemetry, so it may not be worth duplicating it here.
Change includes test …
=> [PROF-6660] Add `profiling_enabled` state to environment logger output

docker-compose.yml, integration/apps/hanami/docker-compose.yml, integration/apps/rails-seven/docker-compose.yml, integration/apps/sinatra2-classic/docker-compose.yml, integration/apps/sinatra2-modular/docker-compose.yml
This PR modifies our `docker-compose.yml` files to bind any ports on the development docker containers only for access by the host machine.
This should not impact any development use-cases.
If the ports are not bound to localhost, they could potentially be accessed by other machines in the same network, which is not a great idea.
(N/A)
Check that running tests using `docker-compose` still works, as well as running them from your development machine directly.
=> Expose development docker container ports to localhost only

.github/workflows/codeql-analysis.yml
The CodeQL Action v1 is scheduled to be deprecated by January 2023. No new updates will be made to v1, which means that new CodeQL analysis capabilities will only be available to users of v2.
Hence upgrading the version of CodeQL github actions to v2.
More info here: https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
**Motivation**
=> Upgrade CodeQL Github Action to v2

lib/datadog/appsec/assets/waf_rules/recommended.json, lib/datadog/appsec/assets/waf_rules/risky.json, lib/datadog/appsec/assets/waf_rules/strict.json
Update the waf rules to the latest version. `1.4.3` 
**Motivation**
The release of the 1.4.3 rules https://github.com/DataDog/appsec-event-rules/tree/1.4.3/build
=> Update appsec rules 1.4.3

integration/README.md, integration/apps/hanami/.envrc.sample, integration/apps/hanami/README.md, integration/apps/hanami/docker-compose.yml, integration/apps/rack/.envrc.sample, integration/apps/rack/README.md, integration/apps/rack/docker-compose.yml, integration/apps/rails-five/.envrc.sample, integration/apps/rails-five/README.md, integration/apps/rails-five/docker-compose.yml, integration/apps/rails-seven/.envrc.sample, integration/apps/rails-seven/README.md, integration/apps/rails-seven/docker-compose.yml, integration/apps/rails-six/.envrc.sample, integration/apps/rails-six/README.md, integration/apps/rails-six/docker-compose.yml, integration/apps/rspec/.envrc.sample, integration/apps/rspec/README.md, integration/apps/rspec/docker-compose.yml, integration/apps/ruby/.envrc.sample, integration/apps/ruby/README.md, integration/apps/ruby/docker-compose.yml, integration/apps/sinatra2-classic/.envrc.sample, integration/apps/sinatra2-classic/README.md, integration/apps/sinatra2-classic/docker-compose.yml, integration/apps/sinatra2-modular/.envrc.sample, integration/apps/sinatra2-modular/README.md, integration/apps/sinatra2-modular/docker-compose.yml, integration/script/build-images
While testing some of the [integration](https://github.com/DataDog/dd-trace-rb/tree/master/integration) apps I noticed a couple things:
- We do not respect the `-v` when building the ruby images. So we have to manually remove the ruby images from the list.
- When running `docker-compose up` from inside the different apps the ruby version is hardcoded. I made it so we can changed  the version using the `RUBY_VERSION` env var from each app folder.
=> Update integrations documentation

ext/ddtrace_profiling_native_extension/native_extension_helpers.rb, spec/datadog/profiling/native_extension_helpers_spec.rb
This PR tweaks the ruby platform check prior to compiling the profiling native extension to allow compilation on arm64 macOS.
We already allowed for arm64 on Linux, but the architecture is reported differently on macOS than on Linux (aarch64 vs arm64). (Because of course it would be reported differently!)
We don't officially support the Continuous Profiler on macOS BUT it actually mostly works, and so we have a toggle to enable it for development and testing purposes.
But up until now all macOS development had been on x86-64, and thus I had not noticed that our checks were too restrictive to allow development on arm64 macOS.
If there's enough customer interest, we may explore officially supporting profiling on macOS at some …
=> Allow profiler development on arm64 macOS

ext/ddtrace_profiling_native_extension/native_extension_helpers.rb
This PR slightly tweaks the error message that users get presented with when the `pkg-config` tool is missing from:
```
Profiling was requested but is not supported, profiling disabled: Your
ddtrace installation is missing support for the Continuous Profiler
because the `pkg-config` system tool is missing. This issue can usually
be fixed by installing: 1. the `pkg-config` package on Homebrew and
Debian/Ubuntu-based Linux; 2. the `pkgconf` package on Arch and
Alpine-based Linux; 3. the `pkgconf-pkg-config` package on
Fedora/Red Hat-based Linux.
```
to:
```
Profiling was requested but is not supported, profiling disabled: Your
dtrace installation is missing support for the Continuous Profiler
because the `pkg-config` system tool is missing. This issue can usually …
```
=> Minor: Tweak profiling error message when pkg-config is missing

ext/ddtrace_profiling_native_extension/private_vm_api_access.c
This PR imports the fix in https://github.com/ruby/ruby/pull/7116 into the custom version of `rb_profile_frames` that we ship inside ddtrace.
As I mention in the inline comments, I don't expect this extra safety check to ever be triggered, but just in case I decided to add it anyway, since the cost of getting my expectation wrong is a VM crash.
N/A
Adding test coverage for this is... difficult. Our current test of this logic is indirect (e.g. via our own code for sampling), and reproducing the state to trigger this is hard.
So for now I only added the check without extra testing.
=> Minor: Import upstream safety check into the profiler custom `rb_profile_frames`

.rubocop.yml
The `Style/WordArray` cop
(<https://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Style/WordArray>) by default enforces this:
```ruby
%w[foo bar baz]
['foo', 'bar', 'baz']
```
In #2572 both me, @lloeki and @tonycthsu agreed that we didn't particularly like the `%w[]` style, so I'm opening a PR to disable it.
Rubocop has a lot of extremely opinionated cops that even the Rubocop authors disable (which is why there are as many Rubocop config variants as there are Ruby projects...), so we shouldn't get too stuck on the defaults.
This cop could be configured in a flipped way (e.g. consider `%w[]` bad and `['foo']` good but I don't think it's worth enabling it.
I can live with either, and we can change our minds at any time. …
=> Disable Rubocop's `Style/WordArray` cop

lib/datadog/tracing/distributed/b3_single.rb, lib/datadog/tracing/distributed/fetcher.rb, lib/datadog/tracing/distributed/helpers.rb, spec/datadog/tracing/distributed/fetcher_spec.rb, spec/datadog/tracing/distributed/helpers_spec.rb
Change method signature to keyword arguments with default, a bit more explicit during invokation and easier to be extended with more arguments
=> Change base to keyword argument

lib/datadog/profiling.rb, spec/datadog/profiling_spec.rb
The `google-protobuf` gem is a dependency needed by the profiler (that we plan on removing when we fully move to libdatadog), but that is not a dependency of the `ddtrace` gem.
Because it's not a dependency of `ddtrace`, we need to gracefully handle the case where this gem is missing. Thus, before requiring any files from this gem, the profiler uses rubygems to check if the gem is available.
But, in #1506, a customer asked us to allow skipping this API call to rubygems, since it didn't work on their setup. Instead, we added an extra check -- if the `::Google::Protobuf` module is available, then we assume protobuf is installed.
**Very very unfortunately**, there's actually another gem, called `protobuf` (or `protobuf-cucumber`, its fork) that is not compatible …
=> Fix profiler wrongly detecting that google-protobuf is installed

ext/ddtrace_profiling_native_extension/private_vm_api_access.c
In #2583 we added a very small check to our custom `ddtrace_rb_profile_frames` to match a similar fix added to upstream Ruby.
But I've just spotted this caused one of the profiling tests to become flaky:
```
$ bundle exec rspec spec/datadog/profiling --seed 14514
Failures:
1) Datadog::Profiling::Collectors::Stack when sampling a thread with empty locations gathers a one-element stack with a "In native code" placeholder
Failure/Error: expect(gathered_stack).to contain_exactly({ base_label: '', path: 'In native code', lineno: 0 })
expected collection contained:  [{:base_label=>"", :lineno=>0, :path=>"In native code"}]
actual collection contained:    []
the missing elements were:      [{:base_label=>"", :lineno=>0, :path=>"In native code"}]
2) …
```
=> Fix profiler sometimes not adding the "In native code" placeholder

ext/ddtrace_profiling_native_extension/extconf.rb, lib/datadog/core/configuration/components.rb, spec/datadog/core/configuration/components_spec.rb
This PR includes two small changes:
* Log libdatadog version when buidling the profiling native extension
This is not visible by default when installing the gem, it only shows up in logs or when installation breaks.
* Tweak banner when new Ruby profiler is enabled 
We are still in beta, but we have had enough feedback from internal and external testing that we are now recommending trying the new profiler out in production.
**Motivation**
Clarify and improve our logging.
(N/A)
Change includes test coverage.
=> Minor: Log libdatadog version while building profiler + Tweak banner when new profiler is enabled 

lib/datadog/appsec/contrib/rack/reactive/request.rb, lib/datadog/appsec/contrib/rack/reactive/request_body.rb, lib/datadog/appsec/contrib/rack/reactive/response.rb, lib/datadog/appsec/contrib/rails/reactive/action.rb, lib/datadog/appsec/contrib/sinatra/reactive/routed.rb, sig/datadog/appsec/contrib/rack/reactive/request.rbs, sig/datadog/appsec/contrib/rack/reactive/request_body.rbs, sig/datadog/appsec/contrib/rack/reactive/response.rbs, sig/datadog/appsec/contrib/rails/reactive/action.rbs, sig/datadog/appsec/contrib/sinatra/reactive/routed.rbs
Extract the `addresses` array creation from the critical path of appsec subscription. 
We now store it in a private constant with each of the files.
Also: 
- Update rbs files
- Added frozen string literal comment 
**Motivation**
Reduce the number of allocations in the critical path 
Split from https://github.com/DataDog/dd-trace-rb/pull/2588
CI
=> Appsec extract array creation from critical path

lib/datadog/core/configuration.rb, lib/datadog/core/configuration/components.rb, lib/datadog/profiling/component.rb, lib/datadog/tracing/component.rb
Move component-specific code out of `Core::Configuration::Components`
**Motivation**
Reduce coupling. Core should be unaware of component details.
Using the [noop noop noop interface maneuver](https://www.dotconferences.com/2016/10/katrina-owen-the-scandalous-story-of-the-dreadful-code-written-by-the-best-of-us).
As a first step I simply moved the most obvious code out of `lib/datadog/core/configuration/components` into `lib/datadog/{tracing,profiling}`, inside their own module, and then `include`'d these modules right back where the methods used to be.
Second step should be:
- changing these modules to classes that create the tracer and profiler instances and their dependencies
- swapping the tracing and profile instances in …
=> Extract tracing and profiling components out of the core namespace

lib/datadog/tracing/contrib/configuration/settings.rb
Remove a stray `OnlyOnce` instance that is no longer in use. There are no references to it anymore in the entire codebase.
Remove something not in use.
(N/A)
CI stays green!
=> Minor: Remove leftover `OnlyOnce` instance

lib/datadog/appsec/contrib/rack/request_middleware.rb, spec/datadog/appsec/contrib/rack/integration_test_spec.rb
When calling the waf with the response result if a rule matches and
the action is to block we record the appsec event but, the customer
will see a 403 on the result.
I rename some variables to better reflect what the stored information is. 
CI
=> [APPSEC-7801] Appsec block request base on response addresses matches

ddtrace.gemspec, ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time.c, ext/ddtrace_profiling_native_extension/collectors_stack.c, ext/ddtrace_profiling_native_extension/http_transport.c, ext/ddtrace_profiling_native_extension/libdatadog_helpers.h, ext/ddtrace_profiling_native_extension/native_extension_helpers.rb, ext/ddtrace_profiling_native_extension/stack_recorder.c, ext/ddtrace_profiling_native_extension/stack_recorder.h, spec/datadog/profiling/collectors/cpu_and_wall_time_spec.rb, spec/datadog/profiling/collectors/stack_spec.rb, spec/datadog/profiling/stack_recorder_spec.rb
This PR updates the profiler to use the new libdatadog v2.0.0 APIs.
In particular:
* The "local root span id" is now attached to samples as a number
* The error reporting API changed, and I tweaked how we got error messages from libdatadog
* Some of the libdatadog memory release methods ("drop" methods") were replaced, and I've adopted the new ones where needed.
Enable the Ruby profiler to use the latest libdatadog release.
A few of the changes were committed incrementally, so it may be easier to review commit-by-commit.
The changes are covered by our existing test suite. In fact, this branch helped pinpoint a libdatadog bug that was fixed before release.
=> Upgrade profiler to use libdatadog v2.0.0

ddtrace.gemspec
Update libddwaf version to 1.6.2.0.0
Check the [CHANGELOG](https://github.com/DataDog/libddwaf-rb/blob/master/CHANGELOG.md#2023-02-03-v16200) for the updates related to libddwaf.
=> [APPSEC-7804] update libddwaf version to 1.6.2.0.0

lib/datadog/appsec/configuration.rb, lib/datadog/appsec/configuration/settings.rb, lib/datadog/appsec/extensions.rb, lib/datadog/appsec/processor.rb, sig/datadog/appsec/configuration.rbs, sig/datadog/appsec/configuration/settings.rbs, sig/datadog/appsec/extensions.rbs, sig/datadog/appsec/processor.rbs, spec/datadog/appsec/configuration/settings_spec.rb, spec/datadog/appsec/extensions_spec.rb, spec/datadog/appsec/processor_spec.rb
Introduce a new appsec configuration option `user_id_denylist`
That list would be use to populate the waf rules data at the initialization of a the `AppSec::Processor`. 
Changes in `AppSec::Processor`:
Previously we had a public method called `update_ip_denylist` which populated the waf rule data just for the IP denylist. Now that we have multiple configuration points for deny lists we have to change the code to account for that. 
I created a new private method `update_rules_data_with_static_configured_values` that creates all the necessary waf rule data for the different deny list configurations and call the waf handle `update_rule_data` function once with all the data. I made that change to reduce the number of calls to the handle. 
Also, I remove the public …
=> [APPSEC-8112] Appsec allow to set user id denylist

lib/datadog/tracing/contrib/ext.rb, lib/datadog/tracing/contrib/sneakers/tracer.rb, spec/datadog/tracing/contrib/sneakers/tracer_spec.rb
Adds the mandatory tag `messaging.rabbitmq.routing_key` for rabbitmq integrations (only `sneakers`).
**Motivation**
Unify span tags across tracers.
Updated unit tests.
=> Add mandatory tags for rabbitmq integrations

spec/datadog/core/environment/cgroup_spec.rb
This PR fixes a flaky spec for Ruby 3.2 I observed in CI in <https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/8878/workflows/f72fda28-a30a-4349-b567-def2b0c94679/jobs/330338>
This issue can also be reproduced locally (again on 3.2) by running `bundle exec rspec ./spec/datadog/core/environment/cgroup_spec.rb:17`.
```
Datadog::Core::Environment::Cgroup
::descriptors
when the '/proc/self/cgroup' file is not present
is expected to receive exist?("/proc/self/cgroup") 1 time (FAILED - 1)
Failures:
1) Datadog::Core::Environment::Cgroup::descriptors when the '/proc/self/cgroup' file is not present is expected to receive exist?("/proc/self/cgroup") 1 time
Failure/Error: super
#<File (class)> received :exist? with unexpected arguments
expected: …
```
=> Fix flaky spec on Ruby 3.2

spec/datadog/core/diagnostics/environment_logger_spec.rb, spec/datadog/core/telemetry/collector_spec.rb, spec/datadog/profiling/profiler_spec.rb
This PR tweaks two specs in the `spec/datadog/core` folder (for the environment logger and the telemetry collector) so that they don't actually start a real profiler during the test.
The changed tests are validating that the environment logger and the telemetry collector report if profiling was enabled or not, which is why they enable profiling.
But we don't need to actually profile during these specs, and actually doing so slows them down and can generate logging noise (profiler starting, trying to report, etc.).
In the future, when we separate out the components, we'll probably have a better way of doing this than `allow_any_instance_of`, but for now I couldn't come up with a simpler solution. …
=> Minor: Don't actually start profiling in core specs

ext/ddtrace_profiling_native_extension/collectors_stack.c, ext/ddtrace_profiling_native_extension/stack_recorder.h, spec/datadog/profiling/stack_recorder_spec.rb
This PR enables an additional "value type" attached to profiling samples -- the `alloc-samples` metric. This will be used to expose more profiling information in follow-up PRs.
I've extracted this from a bigger branch, but this is in good shape for merging already.
(N/A)
Change includes test coverage.
=> [PROF-7192] Minor: Extend stack collector to be able to record the alloc-samples metric

lib/datadog/tracing/contrib/dalli/instrumentation.rb, spec/datadog/tracing/contrib/dalli/instrumentation_spec.rb
Adds `span.kind:client` for dalli
**Motivation**
Unify span tags across tracers
=> Adds span.kind:client for dalli

spec/datadog/appsec/contrib/rack/reactive/request_body_spec.rb, spec/datadog/appsec/contrib/rack/reactive/request_spec.rb, spec/datadog/appsec/contrib/rack/reactive/response_spec.rb, spec/datadog/appsec/contrib/rails/reactive/action_spec.rb, spec/datadog/appsec/contrib/sinatra/reactive/routed_spec.rb
Adds unit tests for the reactive components in the appsec folder: `appsec/contrib/*/reactive/*.rb`
**Motivation**
Having unit test would allow us to more easily refactor some pieces without fear of breaking the existing logic. 
CI
=> Add specs for appsec contrib reactive components

Rakefile
https://github.com/DataDog/dd-trace-rb/issues/2602
Sidekiq version with 6.5.8 is updated at https://github.com/DataDog/dd-trace-rb/pull/2615. Now we can enable the test on CI
=> Enable sidekiq test for ruby 3.2

lib/datadog/core/configuration/agent_settings_resolver.rb
This PR removes a `merge` method that is no longer in use. This is safe to remove because it is not part of ddtrace's public API.
This was only used by the legacy profiling transport (as hinted in the comment attached to the code), and the legacy profiling transport was removed in https://github.com/DataDog/dd-trace-rb/pull/2062 (search for `configure_for_agent` inside `lib/datadog/profiling/transport/http.rb`).
Remove unused code :)
N/A
Check that CI is still green.
=> Minor: Remove unused AgentSettings#merge method

docs/GettingStarted.md, integration/apps/rails-seven/config/initializers/datadog.rb, lib/datadog/tracing/contrib/rack/ext.rb, lib/datadog/tracing/contrib/rack/middlewares.rb, lib/datadog/tracing/metadata/ext.rb, spec/datadog/tracing/contrib/rack/configuration_spec.rb, spec/datadog/tracing/contrib/rack/distributed_spec.rb, spec/datadog/tracing/contrib/rack/integration_test_spec.rb
This is an attempt at resolving the inconsistency raised in #2064 between `http_server.queue`'s duration and real world server queuing time by introducing an outer `http_server.request` span, which contains `http_server.queue` and `rack.request` as sibling spans, rather than the current parent/child relationship that exists between the 2 of them.
**Motivation**
If you have a request that spends 10ms in queue, and 5s being executed, you currently end up with these 2 spans in APM:
* `http_server.queue` (duration: 5.01s)
* `rack.request` (duration: 5s)
However, that isn't really semantically correct. The queuing itself did not take 5.01s, the entire lifecycle of the request took 5.01s, with queueing making up 10ms of that time.
After this change, you should end up …
=> Only count time spent in queue as part of the `http_server.queue` span

Gemfile, sorbet/rbi/hidden-definitions/hidden.rbi
When running bundle install in the new Mac Ventura OS, sorbet fails to install:
```
Could not find compatible versions
Because sorbet >= 0.5.9672, < 0.5.9680 depends on sorbet-static = 0.5.9672
and sorbet-static = 0.5.9672 could not be found in rubygems repository
https://rubygems.org/ or installed locally for any resolution platforms
(x86_64-darwin-22),
sorbet >= 0.5.9672, < 0.5.9680 is forbidden.
So, because Gemfile depends on sorbet = 0.5.9672,
version solving has failed.
The source contains the following gems matching 'sorbet-static (= 0.5.9672)':
* sorbet-static-0.5.9672-java
* sorbet-static-0.5.9672-universal-darwin-14
* sorbet-static-0.5.9672-universal-darwin-15
* sorbet-static-0.5.9672-universal-darwin-16
* sorbet-static-0.5.9672-universal-darwin-17
* …
```
=> Bump sorbet version to one compatible with Mac Ventura

Gemfile, spec/datadog/core/workers/polling_spec.rb, spec/spec_helper.rb
Fixes flaky test ["Datadog::Core::Workers::Polling when included into a worker #perform when #enabled? is true is expected to have received perform(*(any args)) 1 time"](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/8907/workflows/0f3a873c-3af7-427c-864e-c80b4add5adc/jobs/331375) with the use of a new gadget:
```
Failure/Error: expect(worker_spy).to have_received(:perform).at_least(:once)
(Double "worker spy").perform(*(any args))
expected: at least 1 time with any arguments
received: 0 times with any arguments
./spec/datadog/core/workers/polling_spec.rb:43:in `block (5 levels) in <top (required)>'
./spec/spec_helper.rb:220:in `block (2 levels) in <top (required)>'
./spec/spec_helper.rb:112:in `block (2 levels) in <top (required)>' …
```
=> flaky:Datadog::Core::Workers::Polling

spec/datadog/core/workers/runtime_metrics_spec.rb, spec/spec_helper.rb
Fixes this flaky test (to the best of my abilities): https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/8829/workflows/d051131f-b5fe-4967-aa7d-e99b8773996b/jobs/328470/tests
```
Failure/Error: expect(metrics).to have_received(:flush).twice
(InstanceDouble(Datadog::Core::Runtime::Metrics) (anonymous)).flush(*(any args))
expected: 2 times with any arguments
received: 1 time with any arguments
./spec/datadog/core/workers/runtime_metrics_spec.rb:289:in `block in <main>'
./spec/spec_helper.rb:220:in `block in <main>'
./spec/spec_helper.rb:112:in `block in <main>'
/usr/local/bundle/gems/webmock-3.13.0/lib/webmock/rspec.rb:37:in `block in <main>'
```
=> flaky:Datadog::Core::Workers::RuntimeMetrics integration test

spec/datadog/integration_spec.rb, spec/spec_helper.rb
I can't reproduce the flaky test [Datadog integration graceful shutdown for threads closes tracer threads](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/8871/workflows/78282204-4709-4f46-8a2e-2a864c911a23/jobs/330031/tests).
For now, I'm adding additional debug information: the stack trace of all running threads before and after the test runs.
=> Add better error information to flaky thread-leak detection test

spec/datadog/tracing/contrib/ethon/integration_context.rb
This PR attempts to address flaky Ethon tests.
Some Ethon test have been flaking for quite some time, but not away on the same test.
I'm not able to 100% reproduce the issue without making code changes, but I was able to get the exact same error as the recent flaky Ethon test,
https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/8928/workflows/ea1be057-92b7-420c-af6a-3a60e087c8b7/jobs/332182/tests:
```
Failure/Error: expect(request.body).to eq('response')
expected: "response"
got: ""
(compared using ==)
Shared Example Group: "instrumented request" called from ./spec/datadog/tracing/contrib/ethon/integration_test_spec.rb:81
./spec/datadog/tracing/contrib/ethon/shared_examples.rb:79:in `block in <main>'
./spec/datadog/tracing/contrib/ethon/integration_context.rb:82:in `block in …
```
=> Increase timeout on flaky Ethon test

benchmarks/profiler_sample_loop_v2.rb, ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time.c, ext/ddtrace_profiling_native_extension/collectors_stack.c, ext/ddtrace_profiling_native_extension/collectors_stack.h, ext/ddtrace_profiling_native_extension/stack_recorder.c, ext/ddtrace_profiling_native_extension/stack_recorder.h, lib/datadog/profiling/component.rb, lib/datadog/profiling/stack_recorder.rb, spec/datadog/core/configuration/components_spec.rb, spec/datadog/profiling/collectors/cpu_and_wall_time_spec.rb, spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb, spec/datadog/profiling/collectors/stack_spec.rb, spec/datadog/profiling/spec_helper.rb, spec/datadog/profiling/stack_recorder_spec.rb
Up until now, the profiler always included all sample value types in the resulting profile, even if some value is was expected to always be zero.
(Why would a value always be zero? The `cpu-time` value is only available on Linux, and would always be zero on macOS; and we plan to have a way to disable allocation profiling, and thus `alloc-samples` will also be zero.)
This PR:
* Abstracts away from all components other than the `StackRecorder` which sample value types are enabled, by introducing a new `sample_values` struct that every other component can use instead of having to deal with the old array and other implementation details.
* Extends the `StackRecorder` to allow `cpu-time` and `alloc-samples` to be disabled
* Updates the profiler component creation to …
=> [PROF-7251] Exclude disabled profiling sample value types from output

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c, lib/datadog/core/configuration/settings.rb, lib/datadog/profiling.rb, lib/datadog/profiling/collectors/cpu_and_wall_time_worker.rb, lib/datadog/profiling/component.rb, spec/datadog/core/configuration/components_spec.rb, spec/datadog/core/configuration/settings_spec.rb, spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb, spec/datadog/profiling_spec.rb
This PR adds a new profiler public API: `Datadog::Profiling.allocation_count`.
The public documentation for this API is as follows:
> Returns an ever-increasing counter of the number of allocations observed by the profiler in this thread.
>
> Note 1: This counter may not start from zero on new threads. It should only be used to measure how many allocations have happened between two calls to this API:
> ```ruby
> allocations_before = Datadog::Profiling.allocation_count
> do_some_work()
> allocations_after = Datadog::Profiling.allocation_count
> puts "Allocations during do_some_work: #{allocations_after - allocations_before}"
> ```
> (This is similar to some OS-based time representations.)
>
> Note 2: All fibers in the same thread will share the same counter …
=> [PROF-7252] Add `Profiling.allocation_count` API for new profiler

.rubocop.yml, Steepfile, lib/datadog/appsec.rb, lib/datadog/appsec/assets.rb, lib/datadog/appsec/autoload.rb, lib/datadog/appsec/component.rb, lib/datadog/appsec/contrib/rack/request_middleware.rb, lib/datadog/appsec/processor.rb, lib/datadog/core/configuration/components.rb, lib/ddtrace.rb, sig/datadog/appsec.rbs, sig/datadog/appsec/component.rbs, sig/datadog/core/configuration/agent_settings_resolver.rbs, sig/datadog/core/configuration/settings.rbs, sorbet/config, spec/datadog/appsec/component_spec.rb, spec/datadog/appsec/extensions_spec.rb, spec/datadog/core/configuration/components_spec.rb, spec/datadog/core/diagnostics/environment_logger_spec.rb, spec/datadog/tracing/buffer_spec.rb
Add an AppSec component, encapsulating the processor independently of the Rack integration.
Another significant change we introduce is that customers no longer need to `require ddtrace/appsec` to enable appsec specific settings.  The autoloading feature of appsec still works as expected. 
When booting ddtrace and when creating the appsec component, if appsec is not enabled, the component will not be instantiated. 
**Motivation**
Enabling AppSec lifecycle management outside of the Rack integration
The value of this component will increase as reconfiguration, notably through remote configuration, becomes a requirement.
Unit tests have been added for the new appsec components and modified existing tests in the core.
=> Add appsec component

lib/datadog/appsec/component.rb, lib/datadog/appsec/contrib/rack/request_middleware.rb, sig/datadog/appsec/component.rbs, spec/datadog/appsec/component_spec.rb
After merging https://github.com/DataDog/dd-trace-rb/pull/2632, we got alerted that our system tests were failing. 
The scenario that is failing is when the appsec processor fails to parse the WAF rules. 
The test fails when the app wants tries to shout down and we try to finalize the appsec component. The problem is that the processor was never ready, so finalizing a non-ready processor caused an error. 
This PR fix that case by making sure to check if the processor is ready to assign to the appsec component. 
Should we make the `AppSec::Component.new` method private and only allow to use `build_appsec_component`? 
=> make sure to assign a valid processor to the appsec component

spec/datadog/tracing/integration_spec.rb
This [flaky test](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/9045/workflows/6841a910-893c-4922-93af-6e4948a13d04/jobs/336502/tests) happens because the wait condition for a forked process is time-dependent, and short:
```
Failure/Error: it { expect(terminated_process).to eq(graceful_signal) }
expected: "graceful"
got: ""
(compared using ==)
./spec/datadog/tracing/integration_spec.rb:572:in `block (4 levels) in <top (required)>'
./spec/spec_helper.rb:225:in `block (2 levels) in <top (required)>'
./spec/spec_helper.rb:117:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/webmock-3.13.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
``` …
=> Flaky:Remove race condition from integration test

spec/datadog/tracing/workers_integration_spec.rb
This PR changes the timing constraints for the test for the timely shutdown of `Datadog::Tracing::Workers::AsyncTransport`. 
This is the worker used by the tracer's transport.
[This test has flaked recently in CI](https://github.com/DataDog/dd-trace-rb/actions/runs/4245838791/jobs/7381877786):
```
1) Datadog::Workers::AsyncTransport integration tests when terminating the worker which overruns the timeout is expected to be within 0.5 of 1
Failure/Error:
expect(@shutdown_end - @shutdown_beg)
.to be_within(0.5).of(
Datadog::Tracing::Workers::AsyncTransport::SHUTDOWN_TIMEOUT
)
expected 1.762315 to be within 0.5 of 1
```
This PR uses our test default timeout of 5 seconds for this.
=> Flaky:Increase worker shutdown timing tolerance

lib/datadog/appsec/contrib/rack/request_middleware.rb, lib/datadog/appsec/ext.rb, lib/datadog/appsec/monitor/gateway/watcher.rb, lib/datadog/kit/identity.rb, sig/datadog/appsec/ext.rbs, spec/datadog/appsec/contrib/rack/integration_test_spec.rb, spec/datadog/appsec/contrib/rails/integration_test_spec.rb, spec/datadog/appsec/contrib/sinatra/integration_test_spec.rb, spec/datadog/kit/identity_spec.rb
This PR works on top of the previous work done to introduce the [`AppSec::Component`](https://github.com/DataDog/dd-trace-rb/pull/2632) and the [`Appsec::Monitor`](https://github.com/DataDog/dd-trace-rb/pull/2617)
The new code added does the following:
- When calling `Kit::Identity.set_user` if appsec is enabled, we would propagate the user information to the appsec reactive engine
- If the reactive engine considers that we should react based on the information provided, we are going to `throw`
- The appsec rack middleware listens for the throw from the reactive engine if it encounters it. We would interrupt the request and return a 403
I had to add `Datadog::AppSec.settings.send(:reset!)` after all the integration contrib tests to avoid having leaky tests. …
=> [APPSEC-8112] Appsec block request when user ID matches rules data 

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time.c, ext/ddtrace_profiling_native_extension/private_vm_api_access.c, ext/ddtrace_profiling_native_extension/private_vm_api_access.h, spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
This PR changes the `ddtrace_thread_list` method to, instead of creating a new Ruby array to contain its result, receive a pre-existing array for it to use.
Then, it changes the `CpuAndWallTime` collector to always reuse the same array for this list.
The thread list array was the one single Ruby object allocation that the profiler always did on every sample. Now that we're exposing object counts and experimenting with allocation profiling, this regular allocation was really annoying to deal with when looking at data and writing tests.
By reusing the same object, this problem goes away, and even some specs can be simplified.
N/A
This change is covered by the existing unit tests.
=> Reuse array for listing threads instead of creating one every time

ext/ddtrace_profiling_native_extension/native_extension_helpers.rb
This PR adds the following tip to the error message that customers see when trying to enable profiling but the `pkg-config` system tool is missing:
> (Tip: When fixing this, ensure `pkg-config` is installed **before** running `bundle install`, and remember to clear any installed gems cache).
We've had a couple of customers so far run into this issue -- they install `pkg-config`, and can see it running on their container, but they still see the error, because when `bundle install` runs, the tool is not there yet.
Hopefully this tip will avoid other customers running into this issue.
Improve customer UX when enabling the profiler.
I've been considering reimplementing what we need out of `pkg-config` so that we stop requiring …
=> Minor: Tweak profiling error guidance when pkg-config is missing

.github/workflows/lib-injection.yml
I figured out that the commit SHA must be on existing master branch, since the previous sha fails after PR merged/branch deleted.
=> Fix system test runner commit sha

lib/datadog/appsec/assets/waf_rules/recommended.json, lib/datadog/appsec/assets/waf_rules/strict.json
Update appsec ruleset to 1.5.1.
Here are the rules from the [appsec-event-rules repo](https://github.com/DataDog/appsec-event-rules/tree/1.5.1/build) for version 1.5.1
=> [APPSEC-8475] appsec update ruleset to 1.5.1

ext/ddtrace_profiling_native_extension/collectors_idle_sampling_helper.c, ext/ddtrace_profiling_native_extension/extconf.rb, ext/ddtrace_profiling_native_extension/ruby_helpers.c, lib/datadog/appsec/autoload.rb, lib/datadog/kit/enable_core_dumps.rb, lib/datadog/profiling.rb
While reviewing another PR, I noticed that we're somewhat inconsistent when we prefix logging messages:
* In a few cases we used `[DDTRACE]` instead of `[ddtrace]`
* In a few cases we prefixed the `[ddtrace]` with a space, others we didn't
This PR tweaks all messages to use the same `[ddtrace]` prefix and to not use a space before it.
Improve consistency of user-visible messages.
N/A
Some of the messages do have test coverage; for others, we'll need to rely on the PR review to make sure the change is correct.
=> Fix small inconsistencies in ddtrace logging

.github/workflows/test-macos.yaml
This PR changes the `Test macOS` github action to only use the latest macOS for testing, rather than testing with multiple versions of macOS.
We don't currently support macOS on production environments, as documented in
<https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md#apple-macos-support>
It's still valuable to "keep an eye on" macOS, since we do want to be able to use it in development.
BUT our test matrix is rather complex, so I think not testing older macOS versions * 10 Ruby versions we support is a worthy simplification.
Additionally, once github adds support for macOS 13, we'll automatically start testing on that one as well, which should match what most macOS-based developers are using.
N/A …
=> Simplify macOS testing matrix

lib/datadog/appsec/assets/waf_rules/recommended.json, lib/datadog/appsec/assets/waf_rules/strict.json
Update appsec ruleset to 1.5.2.
Here are the rules from the [appsec-event-rules repo](https://github.com/DataDog/appsec-event-rules/tree/1.5.2/build) for version 1.5.2
=> [APPSEC-8492] Appsec update ruleset to 1.5.2

lib/datadog/tracing/contrib/grpc/integration.rb, spec/datadog/tracing/contrib/grpc/integration_spec.rb
This PR fixes the error 
```
Failed to apply Datadog::Tracing::Contrib::GRPC::Patcher patch. Cause: uninitialized constant GRPC::Interceptor
```
when gRPC was partially loaded.
This has been reported to us by users of the Google [Calendar User Availability API](https://developers.google.com/calendar/api/user-availability/reference/rest) gem. That gem is not publicly available yet, but its dependency on the public [`gapic-common` gem](https://rubygems.org/gems/gapic-common) is where the issue lies, allowing us to address this issue.
`gapic-common` only loads [a couple file from gPRC](https://github.com/googleapis/gapic-generator-ruby/blob/f1c2e73219453e497b6ec2dc807a907e939e1342/gapic-common/lib/gapic/common.rb#L15-L16), which only contain constants and error classes.
There's nothing of …
=> Fix 'uninitialized constant GRPC::Interceptor' when with the 'gapic-common' gem

lib/datadog/ci/ext/environment.rb, spec/datadog/ci/ext/fixtures/ci/teamcity.json
Adds a test for TeamCity and updates the env var extraction to match the spec.
Also fixes a small and harmless copy-paste error that caused to try to read Azure Pipelines env vars in other providers.
**Motivation**
Improve support for TeamCity.
Updated the fixtures generated from the ciapp spec.
=> Update TeamCity env var extraction

docs/GettingStarted.md
This PR clarifies that the `Ruby applications` category of apps does not refer to all Ruby applications, but instead to applications with frameworks we don't have special integration for.
Also, this fix fixes all the broken internal markdown links in `docs/GettingStarted.md`.
=> Clarify non-framework instrumentation use case

LICENSE-3rdparty.csv, lib/datadog/appsec/contrib/rack/gateway/request.rb, lib/datadog/core/utils/network.rb, lib/datadog/core/vendor/ipaddr.rb, lib/datadog/tracing/client_ip.rb, sig/datadog/core/header_collection.rbs, sig/datadog/core/utils/network.rbs, sig/datadog/tracing/client_ip.rbs, spec/datadog/core/utils/network_spec.rb, spec/datadog/tracing/client_ip_spec.rb
- Update the list of HTTP headers to look for IP information 
- Add support to parsing HTTP IP Headers with multiple IP addresses
- Update specs
- Change `Tracing::ClientIp` module methods visibility
- Create `Datadog::Core::Utils::Network` module. Main functionality is parsing and extraction IP information for HTTP request headers 
- Update `rbs` files
I had to vendor the code from IPAddr default gem into the re; Because the ruby version below 2.5 does not have the methods: `private?`, `link_local?`, and `loopback?` 
That code should be temporary until we deprecated those old ruby versions
**Motivation**
Fixing a bug found with the IP extraction resolution logic. Not supporting an HTTP header with multiple IPs …
=> [APPSEC-7946] Update the client IP extraction  resolution base on the latest RFC.

lib/datadog/core/vendor/ipaddr.rb, spec/datadog/core/vendor/ipaddr_spec.rb
This PR fixes a bug in the recently-introduced `IPAddr` module.
During review of #2665 the `IPAddr` module was introduced, and while experimenting with the steep type checker, I noticed there was a collision between our `IPAddr` module and the `IPAddr` module where we were looking for execptions.
I'm not sure if this would happen in production, since we always created an `IPAddr` instance with an IP, never a specific `family`, but let's fix this anyway.
Less bugs!
(N/A)
This module is a backport of `IPAddr` to older Rubies. Previously, we only tested it indirectly.
I added a minimal test to validate this change.
=> Fix "NameError: uninitialized constant Datadog::Core::Vendor::IPAddr::AddressFamilyError"

lib/ddtrace/transport/http/traces.rb, lib/ddtrace/transport/traces.rb, spec/ddtrace/transport/http/traces_spec.rb, spec/ddtrace/transport/traces_spec.rb
Move a generically named method out of the way.
**Motivation**
The transport infrastructure is mostly generic, except for a few choke points. This addresses one of them.
The `send_payload` method, while defined in a trace-specific module, is included at the class level.
When attempting to reuse transport for other use cases, the method conflicts with other modules extending the generic client class.
Luckily its use is very limited and self-contained to a trace transport specific scope. By renaming it additional modules are able to be included and can follow a consistent pattern without conflict.
This has been discovered while implementing additional transport facilities for remote configuration, from an AppSec impetus.
The whole transport …
=> Rename conflicting `send_payload` method

lib/datadog/kit/appsec/events.rb, spec/datadog/kit/appsec/events_spec.rb
Fixes what appears to be a bug
**Motivation**
1. The original code looks as though this was the intention[1]
2. It's bad practice to unintentionally modify the parameters of a function
*1: In the original code:
```ruby
user_options = user.dup
user_id = user.delete(:id)
raise ArgumentError, 'missing required key: :user => { :id }' if user_id.nil?
Kit::Identity.set_user(trace, id: user_id, **user_options)
```
`Kit::Identity.set_user(trace, id: user_id, **user_options)` would be redundant as `:id` exists in `user_options` and would replace the previously specified argument
Additionally, if this was intended, then the following is equivalent and better:
```ruby
user_id = user.delete(:id)
raise ArgumentError, 'missing required key: :user => { :id }' if user_id.nil? …
```
=> fix: prevent unintentional modification of arguments

docs/GettingStarted.md
This PR adds a few important details about how the Processing Pipeline behaves when activate by the user.
These concerns have been brought up in the past and can cause confusion when not known by the application maintainer.
=> Capture user-relevant implementation details for the Processing Pipeline

lib/datadog/appsec/component.rb, lib/datadog/core/configuration/components.rb, spec/datadog/appsec/component_spec.rb
fix https://github.com/DataDog/dd-trace-rb/issues/2677
The issue is that trying to access `settings.appsec` when configuring `Datadog` is that if the `appsec` hasn't being required or if the customer did not require `ddtrace` the error we would get is `undefined method `appsec' for #<Datadog::Core::Configuration::Settings>`
The appsec setting is loaded here:
https://github.com/DataDog/dd-trace-rb/blob/28c3c3e1b19a625efe7ba3e107cadea3da0a75c5/lib/ddtrace.rb#L7
https://github.com/DataDog/dd-trace-rb/blob/28c3c3e1b19a625efe7ba3e107cadea3da0a75c5/lib/datadog/appsec.rb#L32
The fix makes sure to double check before if the appsec configuration module has been loaded, and if it hasn't, we will no-op. 
I tested this change loading just `datadog/ci` in an `irb` session and calling …
=> Do not try accessing the appsec settings if the appsec module is not loaded

Steepfile, sig/datadog/core/utils/object_set.rbs, sig/datadog/core/utils/sequence.rbs, sig/datadog/profiling/load_native_extension.rbs, sig/datadog/profiling/native_extension.rbs
The other day I started adding a few types to the profiling code base, but then ran out of time. I decided to extract the things that already worked, even if they are quite small.
Improve type checking coverage in dd-trace-rb.
I wish steep was a bit less cryptic in the errors it emits :/
Validate that type checking in CI still passes.
=> Minor: Add type declarations and enable type checking for a few profiling classes

Steepfile
In #2672 we changed our type checking configuration to be on by default for new files.
While not a bad idea for regular contributors to the core and products, it's an awful experience for people contributing new integrations, since getting type checking going for contrib is quite hard at this moment.
Thus, this PR tweaks the type checking configuration to disable the dd-trace-rb contrib folders by default. In the future, we can always make these ignore rules more finer-grained, when we're feeling brave enough to start adding types to those classes.
Make sure that contributors have a good experience and balance that with gently pushing people to add type signatures to more classes.
N/A
Add an …
=> Disable typechecking contrib folders by default

lib/ddtrace/transport/http/adapters/net.rb, lib/ddtrace/transport/request.rb, spec/ddtrace/transport/http/adapters/net_spec.rb, spec/ddtrace/transport/request_spec.rb
Implement GET support for HTTP transport.
**Motivation**
Some endpoints respond to GET, which was not implemented.
In addition, since GET can't have a body, a `Request` parcel can be omitted. It is therefore made optional.
CI should be green.
=> Add support for GET in transport

.github/workflows/test-macos.yaml, Gemfile
This PR tweaks the workaround added in #2675 for the failing combination of steep 1.3.1 with Ruby 3.0 and 3.1 on GitHub Actions (GHA).
In the prior PR, I just excluded `steep` from all macOS configurations running Ruby 3.0 and 3.1, which was a lot more than was needed. In this PR I tweak this to only exclude `steep` when running on GHA, since we have not seen this issue elsewhere.
The previous workaround broke the local development setup for one of our colleagues :(
I also tried bumping to the latest version of the `ruby/setup-ruby` prebuilt action, but that didn't help (but it doesn't hurt either, so I left it in).
Validate that the "test macOS" GitHub Action, along with all others, are green. …
=> Use workaround for steep issue only in GitHub Actions

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c, spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
In rare cases (such as when throwing exceptions), the profiler may need to allocate Ruby objects during sampling.
This object allocation will trigger the `object_allocation_tracepoint` but we don't want to try to sample in the middle of sampling.
To avoid any issues altogether, I've introduced a `during_sample` flag that can be used to detect this and avoid trying to do sampling during sampling.
Note that the functions modified all run while holding on to the global VM lock, which is why this flag does not need any special concerns re: concurrency.
I've also chosen to keep a counter for how often this happens that may come in handy when debugging any issues around this (and should be cheap enough to keep).
This PR is one more piece on the path to …
=> [PROF-7307] Avoid triggering allocation sampling during sampling

Steepfile, lib/datadog/core/remote/configuration/content.rb, lib/datadog/core/remote/configuration/path.rb, lib/datadog/core/remote/configuration/target.rb, sig/datadog/core/remote/configuration/content.rbs, sig/datadog/core/remote/configuration/path.rbs, sig/datadog/core/remote/configuration/target.rbs, spec/datadog/core/remote/configuration/content_spec.rb, spec/datadog/core/remote/configuration/path_spec.rb, spec/datadog/core/remote/configuration/target_spec.rb
Add PORO objects for remote configuration response data coming from #2678
**Motivation**
Remote configuration
These objects correspond to the data being received by the `/v0.7/config` endpoint.
The parse class methods whould probably move out to be part of transport, but:
- having them here makes the implementation simpler
- transport is due for a redesign, and the responsibility of it is a bit unclear currently
Directly:
```
require 'datadog/core/remote/configuration/path'
require 'datadog/core/remote/configuration/target'
require 'datadog/core/remote/configuration/content'
path = Datadog::Core::Remote::Configuration::Path.parse('datadog/42/PRODUCT/foo/config')
path.config_id
path.name
path.org_id
path.product …
```
=> Add remote configuration PORO objects

lib/datadog/core/remote/configuration/repository.rb, sig/datadog/core/remote/configuration/repository.rbs, spec/datadog/core/remote/configuration/respository_spec.rb
Add configuration repository, using PORO from #2687
**Motivation**
This is an initial basic implementation. It is notably missing:
- storing digests for each bit of content
- reporting a summary of which paths have been updated and their corresponding data for taking action on the newly received configuration
- error tracking and reporting
- a content caching mechanism and cache state reporting
These will be added progressively.
```
require 'datadog/core/remote/configuration/path'
require 'datadog/core/remote/configuration/target'
require 'datadog/core/remote/configuration/content'
path = Datadog::Core::Remote::Configuration::Path.parse('datadog/42/PRODUCT/foo/config')
content = …
```
=> Add remote configuration repository

Gemfile, lib/datadog/tracing/contrib/rails/utils.rb, spec/datadog/tracing/contrib/rails/utils_spec.rb
The `Rails::VERSION::MAJOR >= 3` condition evalutes to `false`, but `false` is not `nil?`, so railtie_supported? was returning true, causing the code to attempt to load the railties on Rails version prior to 3. To fix this, I've removed the explicit `.nil?` check and replaced it with a boolean coercion (which will return false for both `nil` and `false`, rather then returning false for `nil` and true for `false`.
**Motivation**
We're integrating ddtrace into an application that uses Rails 2 in production while also supporting Rails 3 in development. 
This change lets the gem at least boot fully enough to instrument some of our ancillary gems (postgres, redis) and run the continuous profiler, which was our biggest goal. There may be more PRs …
=> Fix Rails < 3 conditional check in Utils#railtie_supported?

benchmarks/profiler_sample_loop_v2.rb, ext/ddtrace_profiling_native_extension/collectors_thread_context.c, lib/datadog/profiling/collectors/cpu_and_wall_time_worker.rb, lib/datadog/profiling/collectors/thread_context.rb, lib/datadog/profiling/component.rb, spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb, spec/datadog/profiling/collectors/thread_context_spec.rb, spec/datadog/profiling/component_spec.rb
This PR updates the new CPU Profiling 2.0 profiler to honor the existing `profiling.advanced.endpoint.collection.enabled` setting.
This setting defaults to enabled. When disabled, the profiler will omit endpoint names in the collected data.
Not supporting this was an oversight; the new profiler (still in beta) should honor this setting.
I'm opening this PR on top of #2697 to avoid conflicts, but both PRs are conceptually independent.
Change includes test coverage.
=> [PROF-6555] Support disabling endpoint names collection in new profiler

lib/datadog/core/remote/client.rb, lib/datadog/core/remote/configuration.rb, lib/datadog/core/transport/config.rb, lib/datadog/core/transport/http/config.rb, sig/datadog/core/configuration.rbs, sig/datadog/core/configuration/settings.rbs, sig/datadog/core/remote/client.rbs, sig/datadog/core/remote/configuration/content.rbs, sig/datadog/core/remote/configuration/repository.rbs, sig/datadog/core/transport/config.rbs, spec/datadog/core/remote/client_spec.rb
Implement the remote configuration client class.
**Motivation**
Remote configuration
Barebones implementation, some questions remain to be solved:
- there is AppSec-specific code in there (products and capabilities declaration)
- the callback system is missing because the repository does not yet report changes
- caching is not handled
There is an issue where the backend appears not to report any `client_configs` nor `target_files`, and `targets` may have targets but they may not correspond and/or include to the active client id.
In such gases, calling `client.sync` multiple times ends up getting the configuration. At this stage it is unknown whether this is expected API endpoint behaviour (e.g a delay in creating entries for a new client id, …
=> Add remote configuration client

lib/datadog/appsec/processor/rule_merger.rb, sig/datadog/appsec/processor/rule_merger.rbs, spec/datadog/appsec/processor/rule_merger_spec.rb
In Appsec, there has to be some transformation when the remote configuration client is going to merge existing information with the provided by the agent. 
The agent can provide multiple pieces of information regarding new rules data, rules override, or entirely new rules set. 
Before being able to instantiate a new `AppSec::Processor` we need to make sure the rules payload has the correct format. 
The correct format is:
```
{
version: ...,
metadata: ...,
rules: [...],
exclusions: [...],
rules_override: [...],
rules_data: [...]
}
```
There is also some merging logic we need to account for when merging `rules_data`
When combining rules data with the same id, type and value, we need to keep the one with the highest expiration or if no expiration is provided.
=> [APPSEC-8287] Add AppSec::Processor::RuleMerger

benchmarks/profiler_sample_loop.rb, ext/ddtrace_profiling_native_extension/private_vm_api_access.c, integration/apps/rack/spec/integration/basic_spec.rb, integration/apps/sinatra2-classic/spec/integration/basic_spec.rb, integration/apps/sinatra2-modular/spec/integration/basic_spec.rb, lib/datadog/core/configuration/settings.rb, lib/datadog/profiling/component.rb, lib/datadog/profiling/tasks/setup.rb, sig/datadog/profiling/component.rbs, spec/datadog/core/configuration/settings_spec.rb, spec/datadog/profiling/component_spec.rb, spec/datadog/profiling/tasks/setup_spec.rb
This PR graduates the new CPU Profiling 2.0 profiler from being in beta to being GA (general availability).
For reference on the advantages brought by the new profiler, check the [dd-trace-rb 1.10.0 release notes](https://github.com/DataDog/dd-trace-rb/releases/tag/v1.10.0).
Whenever profiling is enabled, the CPU Profiling 2.0 profiler will now be used by default unless:
1. The `mysql2` gem is installed. Older versions of libmysqlclient (the C library used by the mysql2 gem) have a bug in their signal handling code that the profiler can trigger. This bug (https://bugs.mysql.com/bug.php?id=83109) is fixed in libmysqlclient versions 8.0.0 and above.
Because currently we don't (yet?) have a way to detect which version of libmysqlclient is in use by the `mysql2` …
=> [PROF-7360] Enable CPU Profiling 2.0 by default

lib/datadog/core/remote/worker.rb, sig/datadog/core/remote/worker.rbs, spec/datadog/core/remote/worker_spec.rb, spec/spec_helper.rb
Implement a polling worker for remote configuration.
**Motivation**
Remote configuration
This is a simple generic polling worker:
- pass it a block via `new` and it'll call it every `interval`
- it can be stopped and started in a thread safe way
There is no fork protection: it is supposed to start on demand when the first request comes in.
Example to use it in conjunction with the remote configuration client is below.
Note that the agent may not reply immediately with a full configuration, but it happens eventually.
```
c.agent.host = '192.168.135.133'
#c.tracing.enabled = true
#c.diagnostics.debug = true
end
transport_options = {
agent_settings: …
```
=> Add remote configuration worker

docs/GettingStarted.md
Cherry-pick https://github.com/DataDog/dd-trace-rb/pull/2703 back to master. This is a docs-only update.
Make sure the change in #2703 doesn't get lost on the next release.
N/A
Use eyes to look at diff. Click link to see if it works ;)
=> Cherry-pick PR2703 "[DOCS-5086] Update link text in Ruby tracing setup" to master

lib/datadog/core/remote/client.rb, lib/datadog/core/remote/configuration/content.rb, lib/datadog/core/remote/configuration/repository.rb, sig/datadog/core/remote/configuration/content.rbs, sig/datadog/core/remote/configuration/repository.rbs, spec/datadog/core/remote/configuration/content_spec.rb, spec/datadog/core/remote/configuration/respository_spec.rb
Add a reporting of which paths were touched, what the content was before and what it is after the transaction.
**Motivation**
Remote configuration.
Contrary to transactions which are a sequential list of operations to apply in order, for mutative usage internal to the repository, a changeset is a report of state change, for a consumer external to the repository (more precisely the upcoming dispatcher).
Using an `Array`-based `ContentList` may not be the most optimal data structure. I am considering changing it to a `Hash`-based `ContentMap` instead in the future. Nonetheless, `ContentList` does the job for this PR.
```
require 'datadog/core/remote/configuration/path'
require …
```
=> Add remote configuration changeset

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c, lib/datadog/profiling/collectors/cpu_and_wall_time_worker.rb, sig/datadog/profiling/collectors/cpu_and_wall_time_worker.rbs, spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb, spec/spec_helper.rb
This PR attempts to fix a flaky profiling spec that was last seen in <https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/9405/workflows/89cdfecc-0767-4fc9-85ab-1caa0abda773/jobs/349752>
This spec has some inherent flakiness, as it runs the profiler for a short while and then asserts on some of the counters. Since all this is asynchronous, values could be off.
In fact, this is not the first time this spec was changed to try to resolve flakiness:
* e194ec68dc5841d7dae68cc53c1d81e34ac9cea3
* #2539
* 7d22e545c2a1adc4856faf1956c1b5bab1338396
The last time this caused flakiness, the source was the dynamic sampling rate component. If for some reason the CI machine is having a slow day, sampling takes longer, and then the dynamic sampling rate component kicks …
=> Fix (hopefully for good) flaky profiling "sampling while VM is idle" spec

.github/workflows/system-tests.yml
This PR installs python 3.9 for system tests jobs.
**Motivation**
System test executor will run on the host rather than inside a container (see https://github.com/DataDog/system-tests/pull/958). It will allow users to do step-by-step debugging, and will allow to unify architecture with parametric tests.
=> Setup python 3.9 for system tests

Steepfile, lib/datadog/core/telemetry/collector.rb, lib/datadog/core/telemetry/v1/application.rb, lib/datadog/core/telemetry/v1/dependency.rb, lib/datadog/core/telemetry/v1/host.rb, lib/datadog/core/telemetry/v1/integration.rb, lib/datadog/core/telemetry/v1/product.rb, lib/datadog/core/telemetry/v1/telemetry_request.rb, lib/datadog/core/utils/hash.rb, spec/datadog/core/telemetry/collector_spec.rb, spec/datadog/core/telemetry/v1/app_event_spec.rb, spec/datadog/core/telemetry/v1/telemetry_request_spec.rb
Our V1 telemetry implementation returns `nil` values in key/value mappings, when telemetry dictates that `nil` values should be omitted from the flushed payload.
This behaviour is enforced by system-tests, which started failing recently:
```
tests/test_schemas.py::Test_Library::test_full - Exception: Schema is invalid in logs/interfaces/library/000__...
tests/test_schemas.py::Test_Library::test_non_regression - Exception: Schema is invalid in logs/interfaces/lib...
tests/test_schemas.py::Test_Agent::test_full - Exception: Schema is invalid in logs/interfaces/agent/003__api_...
tests/test_schemas.py::Test_Agent::test_non_regression - Exception: Schema is invalid in logs/interfaces/agent...
```
This PR addresses these system-tests failures by removing empty values from the returned payload. …
=> Telemetry:Remove nil values from payload

lib/datadog/core/environment/variable_helpers.rb, spec/datadog/core/environment/variable_helpers_spec.rb
We currently only support the string `true` as a truthy boolean configuration value (case insensitive).
Our standard for APM Tracing configuration is actually to allow either `true` or `1`.
This PR changes the logic to accept `1` as a valid true value for environment variable configuration.
There are no other functional changes to configuration parsing.
=> Allow `1` as true value in environment variables

spec/spec_helper.rb
Minor typo on `String#start_with?` method. Does not affect test correctness, but breaks deadline thread.
=> Test:Fix start_with typo

integration/images/ruby/2.1/Dockerfile, integration/images/ruby/2.2/Dockerfile
Try solving:
```
== Building base images... ==
Sending build context to Docker daemon  3.072kB
Step 1/2 : FROM datadog/agent
---> 0a6ebf8b0c00
Step 2/2 : COPY agent.yaml /etc/datadog-agent/datadog.yaml
---> Using cache
---> ecdcbe083e51
Successfully built ecdcbe083e51
Successfully tagged datadog/dd-apm-demo:agent
Sending build context to Docker daemon  53.76kB
Step 1/14 : FROM ruby:2.1
---> 223d1eaa9523
Step 2/14 : RUN printf "deb http://archive.debian.org/debian/ jessie main\ndeb-src http://archive.debian.org/debian/ jessie main\ndeb http://security.debian.org jessie/updates main\ndeb-src http://security.debian.org jessie/updates main" > /etc/apt/sources.list
---> Using cache
---> edc10e20ecba
Step 3/14 : ENV DEBIAN_FRONTEND=noninteractive
---> Using cache
---> 7bbfb5633f35
Step 4/14 : …
```
=> fix debian sources for old ruby images

ddtrace.gemspec, lib/datadog/appsec.rb, lib/datadog/appsec/component.rb, lib/datadog/appsec/contrib/rack/gateway/request.rb, lib/datadog/appsec/contrib/rack/gateway/response.rb, lib/datadog/appsec/contrib/rack/request_middleware.rb, lib/datadog/appsec/contrib/rails/gateway/request.rb, lib/datadog/appsec/contrib/sinatra/gateway/route_params.rb, lib/datadog/appsec/instrumentation/gateway/argument.rb, lib/datadog/appsec/processor.rb, lib/datadog/core/configuration/settings.rb, lib/datadog/core/remote/client.rb, lib/datadog/core/remote/component.rb, lib/datadog/core/remote/ext.rb, sig/datadog/appsec.rbs, sig/datadog/appsec/component.rbs, sig/datadog/appsec/processor.rbs, sig/datadog/core/configuration/settings.rbs, sig/datadog/core/remote/client.rbs, sig/datadog/core/remote/component.rbs, sig/datadog/core/remote/configuration.rbs, sig/datadog/core/remote/ext.rbs, sig/datadog/core/remote/worker.rbs, spec/datadog/appsec/component_spec.rb, spec/datadog/appsec/processor_spec.rb, spec/datadog/core/configuration/settings_spec.rb, spec/datadog/core/remote/client_spec.rb, spec/datadog/tracing/integration_spec.rb
Ties all the things together to Make It Work.
See commit messages for the details.
**Motivation**
Remote configuration
- This mostly handles only the happy path of things (e.g agent with endpoint, no agent disappearing, etc...)
- There is AppSec stuff in Core still. This will be moved away shortly.
Interactively:
```
docker run --rm -it -e DD_APM_ENABLED=true -e DD_ENV=${your_env} -e DD_HOSTNAME=lloeki.cassini -e DD_BIND_HOST=0.0.0.0 -e DD_APM_NON_LOCAL_TRAFFIC=true -e DD_API_KEY=${your_api_key} -e DD_REMOTE_CONFIGURATION_ENABLED=true -p 8126:8126 datadog/agent:7.42.0
```
Then:
```
env DD_AGENT_HOST=${agent_ip} DD_APPSEC_ENABLED=true DD_REMOTE_CONFIGURATION_ENABLED=true …
```
=> Glue remote config together

lib/datadog/appsec/component.rb, lib/datadog/appsec/processor.rb, lib/datadog/appsec/processor/rule_loader.rb, lib/datadog/core/remote/client.rb, sig/datadog/appsec/processor.rbs, sig/datadog/appsec/processor/rule_loader.rbs, spec/datadog/appsec/component_spec.rb, spec/datadog/appsec/processor/rule_loader_spec.rb, spec/datadog/appsec/processor_spec.rb, spec/datadog/core/remote/client_spec.rb
During Remote Client sync, there could be occasions when the rules information from `ASM_DD` product is not present or not available. 
In those situations, we should default to the ones defined on the appsec settings. By default is `:recommended`
I had to extract away the parsing of the ruleset from the `AppSec::Processor`, so I could reuse it in other places in the code base. I like it because it removes that functionality from `Processor`, which is only responsible for ensuring a valid processor and context are created, with the `ruleset` provided.
CI
=> [APPSEC-8867] Appsec reuse rules when ASM_DD is empty

docs/GettingStarted.md, integration/apps/rails-seven/app/controllers/basic_controller.rb, integration/apps/rails-seven/app/controllers/errors_controller.rb, integration/apps/rails-seven/config/application.rb, integration/apps/rails-seven/config/routes.rb, integration/apps/rails-six/app/controllers/basic_controller.rb, integration/apps/rails-six/app/controllers/errors_controller.rb, integration/apps/rails-six/config/application.rb, integration/apps/rails-six/config/routes.rb, lib/datadog/tracing/contrib/action_pack/action_controller/instrumentation.rb, lib/datadog/tracing/contrib/action_pack/configuration/settings.rb, lib/datadog/tracing/contrib/rails/configuration/settings.rb, spec/datadog/tracing/contrib/action_pack/action_controller/metal_spec.rb, spec/datadog/tracing/contrib/action_pack/configuration/settings_spec.rb, spec/datadog/tracing/contrib/rails/configuration/settings_spec.rb, spec/datadog/tracing/contrib/rails/rack_spec.rb
This PR addresses issues (https://github.com/DataDog/dd-trace-rb/issues/2709 , https://github.com/DataDog/dd-trace-rb/issues/2611 , https://github.com/DataDog/dd-trace-rb/issues/2567) we've had for instrumenting an exception handling controller.
1. The trace resource being overwritten by the exception handling controller, make it hard understand the origin of error.
2. Configuration for `exception_controller` with constant does not work properly with zeitwerk autoloading.
----
After careful examination of the problem, I have concluded that the current behaviour of option `exception_controller` is bringing more harm than benefit, because of the fundamental problem to answer the question about what is the strategy to decide whether to overwrite trace resource?
🚫  It should not be made by …
=> Improve controller instrumentation and deprecate option `exception_controller`

.github/workflows/lib-injection.yml, .github/workflows/test-macos.yaml
https://github.com/DataDog/system-tests/pull/1034
Update the github action commit hash to pin ruby image
In addition to fixing the `lib-injection` GH action, we added the code from this [PR](https://github.com/DataDog/dd-trace-rb/pull/2736). The PR removes the ruby 2.1 from the `test-macos` matrix
=> Update lib injection github action commit hash

lib/datadog/appsec/configuration.rb, lib/datadog/appsec/configuration/settings.rb, sig/datadog/appsec/configuration.rbs, sig/datadog/appsec/configuration/settings.rbs, spec/datadog/appsec/configuration/settings_spec.rb, spec/datadog/appsec/extensions_spec.rb, spec/datadog/appsec/spec_helper.rb, spec/datadog/appsec_spec.rb
This PR creates an internal API for `Datadog::AppSec` to query if the customer has configured a setting via the `Datadog.configure` block or via a ENV variable. 
Internally the AppSec module would be able to query that information using `Datadog::AppSec.default_setting?`
**Motivation**
For enabling remote configuration, we need to make sure the customer hasn't set a ruleset option manually. Currently, we can only check for the existence of the ENV variable `DD_APPSEC_RULES`, but that is not enough. We also need to know if the `appsec.ruleset` has been set manually vi the customer. 
This new internal API would be use [here](https://github.com/DataDog/dd-trace-rb/pull/2733/files#diff-af9353ccefa8c307f715dae7907301f1b04a6a2d05b2a20b841a0af6dc5199a7R105-R112) …
=> [APPSEC-8868] Store if a specific appsec configuration option has been configured by customer using `Datadog.configure` block or an ENV variable

spec/spec_helper.rb
This PR tags `Timeout.ensure_timeout_thread_created` as a known leaky thread: this one is created internally by the `Timeout` class.
This ensures this `Timeout` thread is not reported as a leaky thread from `ddtrace`.
=> Tag known leaky Timeout internal thread

spec/spec_helper.rb
Following the work of @marcotc on https://github.com/DataDog/dd-trace-rb/pull/2742
After pulling the latest master, I noticed that when executing the tests with `ENV['CI']` we would get an error:
I fixed the `require` issue. The leak thread detection still reports the thread created within `Timeout.ensure_timeout_thread_created`. I would like to investigate more on that, but for now I think fixing running specs locally is more important
=> make sure ThreadHelpers.with_leaky_thread_creation is available when called

.github/workflows/yard.yml, README.md
This PR publishes `ddtrace` YARD docs to this repository's GitHub page: https://datadog.github.io/dd-trace-rb/ (currently not published).
This is done by a  GitHub Action that runs on pushes to the `release` branch, which is the branch we use to publish documentation to our official website.
Here's the published page from my personal repository, using the same `yard.yml` GitHub Action from this PR: https://marcotc.github.io/dd-trace-rb/
=> Doc:Publish YARD docs to GitHub pages

.gitignore, shell.nix, spec/ddtrace/release_gem_spec.rb
This is entirely optional to use but for nixpkgs users this is a really easy way to get things up and running. With just:
```
nix-shell
```
All needed dependencies get automatically pulled in, dropping the user in a ready-to-use shell. It gets extra-nice with `direnv`.
Then as usual:
```
bundle install
```
Puts everything in a `vendor/bundle` directory, which behaves as usual regarding `gem install` and `bundle` in general. Should it need to be cleaned up, e.g to start form scratch, a simple `rm -rf vendor/bundle` is sufficient.
Also, gem commands can typically be run with or without `bundle exec`.
It also pins to a specific commit for the channel, so that tool versions are always consistent across platforms (incl. CPU arches and OSes).
**Motivation**
- It gets …
=> Add a basic `shell.nix` file

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c, lib/datadog/profiling/component.rb, spec/datadog/profiling/component_spec.rb
This PR adds the `rugged` gem to the list of gems that prevent the new CPU Profiling 2.0 profiler from being auto-enabled.
This is needed because the `rugged` gem (more specifically, its C-level dependencies) do not correctly handle the unix signals that the new profiler uses.
We plan to do more than just add this workaround, but until we do so, this change will prevent customers from being bitten by the issue.
Make sure that customers being moved to the new CPU Profiling 2.0 profiler have a smooth experience.
N/A
The snippet shared by the customer in <https://github.com/DataDog/dd-trace-rb/issues/2721> reproduces the issue for me every time.
With this change, as expected, the issue no longer …
=> [PROF-7409] Do not auto-enable new profiler when rugged gem is detected

.github/workflows/system-tests.yml
Enable more system test scenarios to be run in CI
**Motivation**
The default scenario covers only a limited number of tests
- Validate new developments
- Guarantee no regression
Probably the system tests repo should provide an cross-repo reusable GitHub workflow so that we don't have to update this one manually.
CI
=> Add more scenarios to system tests

spec/datadog/appsec/contrib/rack/integration_test_spec.rb, spec/datadog/appsec/contrib/rails/integration_test_spec.rb, spec/datadog/appsec/contrib/sinatra/integration_test_spec.rb
Set libddwaf timeout to a high value for AppSec specs
**Motivation**
This removes a frequent cause of flakiness
For these test cases we want libddwaf to always run to completion. 10s per request should be enough!
CI should be green. Hopefully it removes most of the flakiness, which can only be observed over time.
=> Set libddwaf timeout to a high value for AppSec specs

spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
This PR disables a profiler spec that is flaky, as seen in these recent test runs:
* <https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/9486/workflows/2fa85a35-19c0-4bdf-ac66-4a872080f7ab/jobs/352689>
* <https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/9471/workflows/cb7224c5-2896-415c-a1fd-b0c64eacb953/jobs/352129>
* <https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/9677/workflows/9ddbbdfc-3a2f-40b9-8076-6b6a47a34d1f/jobs/359559>
Make sure there are no flaky tests in our test suite.
I still plan to gather additional information on what is causing this flakiness; it's not clear to me what's happening with the current output. But until I do so, let's stop annoying everyone else.
In …
=> Temporarily disable flaky profiler spec

.gitlab/benchmarks.yml
This PR adds a workaround for the GitLab benchmark jobs configuration that was causing them to show up on GitHub as "Pending" and never completing for every PR.
| Screenshot without fix |
| ---------- |
| ![image (6)](https://user-images.githubusercontent.com/2785847/231196868-c949c801-68da-47e6-9d6d-98dccc769da9.png) |
Currently the jobs don't run on every PR so this fixes the "Pending" issue.
Hopefully soon we'll start running the benchmarks on every PR and so we'll be able to remove this workaround.
Thanks @ddyurchenko for the help setting this so far.
Verify that you no longer see "Pending" jobs on the GitHub CI status.
=> Add workaround for pending gitlab benchmark jobs

lib/datadog/core/remote/configuration/path.rb, spec/datadog/core/remote/configuration/path_spec.rb
Fix remote configuration path parsing
**Motivation**
Turns out `config` hardcodedness was kind of ambiguous in the spec and I misunderstood it as being general. This now fails as `blocked_ips` has the config name be some kind of hash.
RFC has been clarified.
RC should now work with `blocked_ips` from `ASM_DATA` as sent from the backend.
=> Fix remote configuration path parsing

lib/datadog/tracing/contrib/semantic_logger/instrumentation.rb, spec/datadog/tracing/contrib/semantic_logger/instrumentation_spec.rb
`SemanticLogger` provides interface which is fully compatible with `Logger` interface
It is possible to use `SemanticLogger#add` and `SemanticLogger#log` instance methods on `SemanticLogger` as it would be just plain `Logger`
Datadog instrumentation doesn't expect that first argument in method `#log` might be not `SemanticLogger::Log` but severity level like `Logger::WARN` as result fails with error `NoMethodError: undefined method 'named_tags' for 2:Integer`.
Originally met issue in Rails project, here is specs:
- rails 6.1.7.3
- rails_semantic_logger 4.12.0 
- semantic_logger 4.13.0
- ddtrace 1.4.2
When have configuration for datadog:
```ruby
Datadog.configure do |conf|
conf.env = Rails.env
conf.service = 'my_service'
conf.tracing.instrument :rails
conf.tracing.sampling.default_rate = …
```
=> Fix using SemanticLogger#log(severity, message, progname)

.gitlab/benchmarks.yml
Scope the benchmarking service account to benchmarking jobs only
**Motivation**
Ruby deployments to the reliability environment have been broken for a week. The cause was traced to https://github.com/DataDog/dd-trace-rb/commit/65459510a66ef8ce11550b3df0e720dc4ad42065
* Validate deploys to the reliability env are fixed
* Validate running benchmarks still works
=> Scope the benchmarking service account to benchmarking jobs only

README.md
After making changes to `README.md` recently, I noticed some of the links have been mislabeled for a while.
This PR now correctly points users to our [public docs](https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/ruby/) and [YARD docs](https://datadoghq.dev/dd-trace-rb/).
Also, the APM Terminology page has been re-titled in the public docs, so this Readme now reflects that.
=> Docs:Update Readme links

lib/datadog/appsec/contrib/rack/gateway/request.rb, spec/datadog/appsec/contrib/rack/gateway/response_spec.rb
Fixes https://github.com/DataDog/dd-trace-rb/issues/2724
The easiest solution rather than checking for the existence of `each_header` method for a rack request is to simply use `request.env.each_with_object`.
Removing that code fixes the load time issue when using `dd-trace-rb` on a non rack base application
=> Remove check for `::Rack::Request.instance_methods.include?(:each_header)` at load time

lib/datadog/core/remote/configuration/content.rb, lib/datadog/core/remote/configuration/digest.rb, lib/datadog/core/remote/configuration/repository.rb, lib/datadog/core/remote/configuration/target.rb, sig/datadog/core/remote/configuration/content.rbs, sig/datadog/core/remote/configuration/digest.rbs, sig/datadog/core/remote/configuration/repository.rbs, sig/datadog/core/remote/configuration/target.rbs, spec/datadog/core/remote/configuration/content_spec.rb, spec/datadog/core/remote/configuration/digest_spec.rb, spec/datadog/core/remote/configuration/respository_spec.rb, spec/datadog/core/remote/configuration/target_spec.rb
The `cached_target_files` field intends to signal to the agent what files the tracer has seen and subsequent requests. We do not have to pull that information from the agent.
We can retrieve that information from the `repository.contents`
To do that, we have to tweak a little the different remote configuration components. The `Digest` and `DigestList` are no longer private classes under `Target`. 
We will use the `Digest` class to compute the hash value of the content on demand and store that information on the `Content` instances. That way, we do not have to calculate the hash of the content over an over. 
Another quick addition is adding support for `:sha512`. The remote configuration backend supports hashing the content using that algorithm.
=> [APPSEC-8957] Populate remote client cached_target_files payload field

lib/datadog/appsec/processor.rb, sig/datadog/appsec/processor.rbs, vendor/rbs/libddwaf/0/datadog/appsec/waf.rbs
Protect Processor::Context#run with a mutex
**Motivation**
`ddwaf_run` mutates `ddwaf_context` in a non-thread-safe way.
Sicne there is a 1:1:1 context - request - web worker thread mapping it should very rarely happen in typical apps so the lock will just fly through.
This aims to protect from code that spawns threads within a request and that would theoretically trigger a context run (e.g [ActionController::Live](https://github.com/rails/rails/blob/2675c906b1cc4cc877ddee4d62dc33f544adc748/actionpack/lib/action_controller/metal/live.rb)). There is currently none but there could be in the future.
Difficult since there's no such real case currently. Even synthetically (e.g in a spec) it would be hard as it would …
=> Protect Processor::Context#run with a mutex

.github/workflows/system-tests.yml
This PR enables Telemetry test scenarios from `system-tests` to run on `dd-trace-rb` commits.
The scenarios are all currently passing with an XPASS status: they can't be fully enabled because telemetry changes to make them pass are not yet released in a public version of `ddtrace`.
=> Test:Enable Telemetry system-test

lib/datadog/tracing/distributed/trace_context.rb, spec/datadog/tracing/distributed/trace_context_spec.rb
This PR fixes three w3c `tracecontext` propagation issues:
1. If the provided `TraceDigest#trace_distributed_tags` contained Hash values that needed to be escaped during distributed trace injection, those value were being modified leaving the original `TraceDigest#trace_distributed_tags` changed. The provided `TraceDigest#trace_distributed_tags` does not change anymore on injection. This never affected distributed header extraction.
2. `:` is not considered an invalid `trace_distributed_tags` value anymore, thus it is not going to be escaped.
3. `=` is now serialized as `~`, instead of `:`.
These issues were caught by our tracestate headers system tests: https://github.com/DataDog/system-tests/blob/92064c6af29562f2962176767c417fc2b0eda867/parametric/test_headers_tracestate_dd.py
=> Fix w3c propagation special character handling

lib/datadog/core/remote/configuration/digest.rb
**Motivation**
Saw a bunch of these locally:
```
D, [2023-04-13T23:08:57.783586 #4664] DEBUG -- ddtrace: [ddtrace] (/Users/lloeki/Source/github.com/DataDog/dd-trace-rb/lib/datadog/core/remote/worker.rb:89:in `call') remote worker perform
E, [2023-04-13T23:08:57.842171 #4664] ERROR -- ddtrace: [ddtrace] (/Users/lloeki/Source/github.com/DataDog/dd-trace-rb/lib/datadog/core/remote/component.rb:32:in `rescue in block in initialize') remote worker error: NameError uninitialized constant Digest
::Digest::SHA256.new
^^^^^^^^ location: /Users/lloeki/Source/github.com/DataDog/dd-trace-rb/lib/datadog/core/remote/configuration/digest.rb:31:in `hexdigest'
```
Dunno exactly when I started my Puma process so I can't say for sure which branch triggered it. I think it's …
=> Fix missing digest require

lib/datadog/tracing/contrib/utils/quantization/http.rb
Fix quadratic backtracking on invalid URI
**Motivation**
- CVE-2023-28755: ReDoS vulnerability in URI
- We vendor a partial version of the affected `RFC3986_URL` regex
Because we only quantize URLs that are typically valid and in control of the ddtrace user instead of the general arbitrary URI case, impact should be lower than of the linked CVE.
Still, worth a fix.
Upstream details:
- CVE report: https://www.ruby-lang.org/en/news/2023/03/28/redos-in-uri-cve-2023-28755/
- Taken from: https://github.com/ruby/uri/commit/eaf89cc31619d49e67c64d0b58ea9dc38892d175
- Full changeset: https://github.com/ruby/uri/compare/v0.12.0...v0.12.1
Should still pass CI.
I did not [port the …
=> Fix quadratic backtracking on invalid URI

lib/datadog/core/remote/client.rb, lib/datadog/core/remote/configuration/repository.rb, sig/datadog/core/remote/configuration/repository.rbs, spec/datadog/core/remote/configuration/respository_spec.rb
On the previous PR https://github.com/DataDog/dd-trace-rb/pull/2771 we populate `config_states` but we wanted to populate `cached_target_files`.
I validated this changes works against our system-tests
=> Fix cached_target_files.

lib/datadog/core/remote/component.rb
Check info endpoint for remote configuration availability in the agent
**Motivation**
RC should not even start if the agent is unreachable or not configured properly.
This should also warn the user so that corrective action can be taken self-served.
Either one of:
- Do not start agent
- Start agent without `DD_REMOTE_CONFIGURATION_ENABLED=false` env var
And then start an app with `DD_REMOTE_CONFIGURATION_ENABLED=true`
=> Check info endpoint for remote configuration availability in the agent

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c, spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
This PR is a follow-up of the saga of the "sampling while VM is idle" flaky spec.
In #2708 after analyzing previous failed specs, I determined that the profiler dynamic sampling rate mechanism was kicking in on this spec and making if flaky -- if e.g. CI was busy that day and some of the samples took longer than expected.
To combat this, #2708 introduced a way to disable the dynamic sampling rate mechanism, so we could still assert on the correctness of the profiler in this test.
But unfortunately I did not properly disable the mechanism, and this meant that the flaky test came back to haunt us, leading us to disable it in #2759.
This PR fixes the missing disable step in
`rescued_sample_from_postponed_job`, and re-enables the flaky spec.
This check was missing …
=> Fix profiler flaky test due to incomplete dynamic sampling rate disable mechanism

lib/datadog/core/remote/configuration/content.rb, lib/datadog/core/remote/configuration/repository.rb, lib/datadog/core/remote/configuration/target.rb, sig/datadog/core/remote/configuration/content.rbs, sig/datadog/core/remote/configuration/repository.rbs, sig/datadog/core/remote/configuration/target.rbs, spec/datadog/appsec/remote_spec.rb, spec/datadog/core/remote/configuration/respository_spec.rb, spec/datadog/core/remote/configuration/target_spec.rb
Stores and set remote configuration content version. Is that information to populate the client `config_state`
@lloeki will work on the remaining portion of `config_state`, which is adding the information if any error occurred during the remote configuration sync 
**Motivation**
Here are the [system test assertions](https://github.com/DataDog/system-tests/blob/main/tests/remote_config/rc_expected_requests_asm_dd.json) on the expected values for `config_states`
CI
=> [APPSEC-6712] Remote configuration `config_state`

lib/datadog/core/workers/async.rb, lib/datadog/core/workers/interval_loop.rb
Fixes Mutex assignment to be thread-safe.
**Motivation**
Tried to find what might be causing https://github.com/DataDog/dd-trace-rb/issues/2045 and found (unfortunately unrelated) but somewhat problematic code. We've tried this patch in production, unfortunately as I said, it's not fixing #2045, but still worth fixing.
This is a simple demo, why `@mutex ||= Mutex.new` is a bad idea. Save the below ruby script as `demo.rb`:
``` ruby
module BeforePatch
def mutex
@mutex ||= Mutex.new
end
end
module AfterPatch
def self.included(base)
base.prepend(PrependMethods)
end
module PrependMethods
def initialize(...)
@mutex = Mutex.new
super(...)
end
attr_reader :mutex
end
end
class Demo
include(ENV["FIXED"] ? AfterPatch : BeforePatch)
end
demo    = …
```
=> fix: Correctly set mutex

README.md
The previous link to our badge image had a `circle-token` parameter that is no longer valid.
This PR removes the `circle-token` altogether, given it's not required for public repositories.
The diff looks funny, ![Screenshot 2023-04-13 at 1 46 05 PM](https://user-images.githubusercontent.com/583503/231879026-00208a25-7817-49fe-9bd0-389b54a6fa88.png), but clicking "View file" will show you the actual result.
=> Fix CircleCI badge image

lib/datadog/core/remote/client.rb, sig/datadog/core/configuration/settings.rbs, spec/datadog/core/remote/client_spec.rb
The remote configuration specs say `app_version` MUST be set if present. The `configuration.version` is populated by the customer and provides no sane fallback. For that, in the case of it being `nil`, we do not include the `app_version` property
More context on the `configuration.version` tag can be found [here](https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/)
Also, adds specs to validate that the payload has all the necessary attributes.
**Motivation**
CI
=> Remote client use app version on request payload

Gemfile
Fix steep parallel crash
**Motivation**
Parallell 1.23 seems to annoy steep:
```
cannot load such file -- parallel/processor_count (LoadError)
```
Maybe an upgrade to steep could help.
This should not crash:
```
bundle exec steep check
```
=> Fix steep parallel crash

ddtrace.gemspec
Add `changelog_uri` to the gem metadata.
**Motivation**
Changelog URLs have been valid [metadata](https://guides.rubygems.org/specification-reference/#metadata) since 2017 on RubyGems.org. Setting `changelog_uri` will add a "Changelog" link to the Rubygems page for ddtrace https://rubygems.org/gems/ddtrace/
=> Set 'changelog_uri' in gemspec to point to CHANGELOG.md

lib/datadog/core/remote/client.rb, lib/datadog/core/remote/component.rb, spec/datadog/core/remote/client_spec.rb, spec/datadog/core/remote/component_spec.rb
Whenever a Client::SyncError is raised when calling `client.sync` the remote component rescues it, logs the sync error information and continues with the execution.
The remote configuration backend expects to maintain the state between requests even if there is a SyncError.
In the case of an unhandled error, we are still resting the client's state.
**Motivation**
CI
=> Remote configuration handle Client SyncError

lib/datadog/core/configuration/settings.rb, lib/datadog/core/remote/component.rb, sig/datadog/core/remote/component.rbs, spec/datadog/core/configuration/settings_spec.rb, spec/datadog/core/remote/component_spec.rb, spec/datadog/tracing/integration_spec.rb
Even with remote configuration enabled by default,  on this version of remote configuration and appsec. 
If AppSec is disabled, the remote configuration worker thread won't start.
Since in AppSec, we do not support the feature of remote activation. There is no need to have a background thread opening HTTP connections to the agent to request remote configuration information.
This might change once we support ASM remote activation or other components, such as tracer, start using remote configuration since there would be remote configuration information to listen to. 
**Motivation**
CI
=> [APPSEC-9177] Enable Remote configuration by default

README.md
This PR removes the CircleCI badge from the README.
I don't think this badge provides a lot of value:
* We do a lot of validation that is not reflected in this badge, e.g. in GitHub Actions, as well as other internal validations
* The status of master doesn't really tell a lot about released versions
* We're still hunting down a few flaky tests, which make the badge show red from time to time.
...so my suggestion is to remove it.
N/A
Validate that badge is not there anymore ;)
=> RFC: Remove CircleCI badge from README

lib/datadog/core/configuration/agent_settings_resolver.rb, spec/datadog/core/configuration/agent_settings_resolver_spec.rb
This PR extends the `AgentSettingsResolver` to allow the `DD_TRACE_AGENT_URL` to contain a Unix Domain Socket (UDS) configuration string, for instance `unix:///some/path/to/the/apm.socket`.
It also adds a warning if there's configuration for both http and unix domain socket (and in that case it will prioritize the http variant).
This was missing for feature parity with other Datadog client libraries, and it was annoying a lot of customers in #1967 (thanks for the patience, folks!).
The change is quite small because dd-trace-rb already supported using unix domain sockets -- you just couldn't configure them via this environment variable. Thus, the only thing that changed was parsing it correctly. …
=> Add support for Unix Domain Socket (UDS) configuration via `DD_TRACE_AGENT_URL`

.gitlab/benchmarks.yml
Add the necessary DD_* Env variables to tweak the configuration of dd-trace-rb on the benchmark platform. 
The new scenario `tracing-and-appsec-and-no-remote-configuration-benchmarks` depends on this PR https://github.com/DataDog/benchmarking-platform/pull/1
**Motivation**
=> Add necessary DD_* Env variables for benchamrk scenarios

.gitlab/benchmarks.yml
Fix the problem with our GitLab pipeline. It complains that the value definition must be a string or a hash
**Motivation**
=> make sure ENV variables are strings

lib/datadog/core/remote/client.rb, sig/datadog/core/remote/client.rbs, spec/datadog/core/remote/client_spec.rb
Add remote configuration tags
**Motivation**
- version is mangled through semver, report the exact original gem version string
- ruby runtime information is gold to debug issues
Ideally runtime information should go through telemetry but it is currently lacking in some departments.
- Automatically: CI
- Manually: start a process with RC, go to the RC admin, and see the tags.
=> Add remote configuration tags

lib/datadog/core/environment/identity.rb, lib/datadog/core/remote/client.rb, sig/datadog/core/environment/identity.rbs, spec/datadog/core/environment/identity_spec.rb, spec/datadog/core/remote/client_spec.rb
Fix version format in remote configuration payload.
**Motivation**
RFC mandates Semantic Versioning 2.0.0. Without this format, the payload gets silently rejected and RC response is always lacking targets, thus inoperative.
A workaround specifically for the already published `1.11.0.beta1` version which is affected has been deployed backend-side.
The implementation hinges on the version pattern being enforced by `[MAJOR, MINOR, PATH, PRE].compact.join('.')`
Side note: I'm wondering why we have so many constants regarding versions, all computed from one another. I feel it makes it hard to test and refactor.
A bit tough since a fix has been deployed:
- alter version to have PRE be e.g `'beta2'`
- start an app with RC …
=> Fix version format in remote configuration payload

lib/datadog/core/remote/client.rb, sig/datadog/core/remote/client.rbs
Memoize tracer_version_semver2
**Motivation**
Followup to https://github.com/DataDog/dd-trace-rb/pull/2795#discussion_r1178058677
Memoized in client instead of `Core::Environment::Identity` because the latter would make it global in the module singleton, and complicates testing. Also, none are memoized in there.
CI
=> Memoize tracer_version_semver2

lib/datadog/core/configuration/components.rb, lib/datadog/core/telemetry/client.rb, lib/datadog/core/telemetry/http/transport.rb, spec/datadog/core/configuration/components_spec.rb
This PR addresses the debug error log that happens when `ddtrace` is configured to communicate with the agent through UDS: `Unable to send telemetry event to agent: Failed to open TCP connection to :80 (Connection refused - connect(2) for nil port 80)`.
This PR does not enable the `Telemetry` client when UDS connection is used, instead disabling Telemetry.
=> Telemetry:Disable for non-HTTP agent connection

lib/datadog/appsec/assets/blocked.html, lib/datadog/appsec/response.rb, sig/datadog/appsec/response.rbs, spec/datadog/appsec/response_spec.rb
Reimplement response negotiation
This covers:
- unparseable Accept headers
- missing Accept headers
- proper ordering to handle priority
- defaulting to the first map element
- specs to avoid regressions
**Motivation**
A swapped argument prompted a deeper analysis of the response negotiation implementation, which uncovered many corner case issues.
Specs were added to cover the most important main and corner cases 
Perform a request that generates a blocking response, e.g (with remote configuration disabled) using:
```
c.appsec.ip_denylist = [
'127.0.0.1',
'::1',
]
```
=> Fix block response content negotiation

lib/datadog/tracing/buffer.rb, lib/datadog/tracing/contrib/patcher.rb, lib/datadog/tracing/contrib/roda/patcher.rb, lib/datadog/tracing/contrib/status_code_matcher.rb, lib/datadog/tracing/correlation.rb, lib/datadog/tracing/event.rb, lib/datadog/tracing/pipeline.rb, lib/datadog/tracing/runtime/metrics.rb, lib/datadog/tracing/sampling/rate_by_service_sampler.rb, lib/datadog/tracing/sampling/rate_sampler.rb, lib/datadog/tracing/sampling/rule.rb, lib/datadog/tracing/sampling/rule_sampler.rb, lib/datadog/tracing/span_operation.rb, lib/datadog/tracing/sync_writer.rb, lib/datadog/tracing/trace_operation.rb, lib/datadog/tracing/tracer.rb, lib/datadog/tracing/workers.rb, lib/datadog/tracing/workers/trace_writer.rb, lib/datadog/tracing/writer.rb
This is to fix an issue we're seeing when running tests in our codebase. It should not be necessary to include core everywhere since these files should not be required directly as far as I understand.
**Motivation**
To fix this warning:
```
Users/michaelscrivo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ddtrace-1.11.0/lib/datadog/tracing/trace_operation.rb:1: warning:
/Users/michaelscrivo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ddtrace-1.11.0/lib/datadog/tracing/trace_operation.rb:1: warning: loading in progress, circular require considered harmful -
/Users/michaelscrivo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ddtrace-1.11.0/lib/datadog/core.rb
from -e:1:in  `<main>'
from <internal:/Users/michaelscrivo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems …
```
=> Fix circular requires

lib/datadog/appsec/contrib/rack/request_middleware.rb, spec/datadog/appsec/contrib/rails/integration_test_spec.rb
Fix https://github.com/DataDog/dd-trace-rb/issues/2722
I tested the code against a local Rails app that mounts a Sinatra App.
The configuration on the Rails app looks like this:
```ruby
c.tracing.instrument :rails, service_name: 'gustavo-nested-apps'
c.appsec.enabled = true
c.appsec.instrument :rails
c.appsec.instrument :sinatra
end
```
```ruby
require_relative '../app/rack_apps/my_sinatra_app'
Rails.application.routes.draw do
root "home#index"
mount RackApps::MySinatraApp.new => '/api'
end
```
To ensure we are not re-executing the request middleware code multiple times with the context of nested apps, we need to make sure we bail out at the proper time. 
That removes the 🐛 that some customers are experiencing, which raises …
=> [APPSEC-9343] Appsec support nested apps

spec/datadog/appsec/contrib/rack/integration_test_spec.rb, spec/datadog/appsec/contrib/rails/integration_test_spec.rb, spec/datadog/appsec/contrib/sinatra/integration_test_spec.rb
Improve CI time for appsec integration specs. 
We have divided all specs into single specs. The way tests were organized meant that for every assertion, we were making a new request to the test app. By groping the specs into a bigger block we can improve CI time.
For future we can extract those shared examples into a separate file
**Motivation**
=> make sure to not execute to many request for appsec integration specs

ddtrace.gemspec, lib/datadog/appsec/processor/rule_merger.rb, lib/datadog/appsec/remote.rb, sig/datadog/appsec/processor/rule_merger.rbs, spec/datadog/appsec/processor/rule_merger_spec.rb, spec/datadog/appsec/remote_spec.rb, spec/datadog/core/remote/client/capabilities_spec.rb
**Motivation**
We add support for In-App WAF Custom Rules. AppSec customers are going to be able to provide there own custom rules via remote configuration 🎉 
I did an integration test using my local sandbox app. 
Here is the custom rule I created: 
After getting the update on my app from the remote configuration. 
Hitting the app with `curl -H "User-Agent: Gustavo" 'localhost:3000'`, and we can see in the logs the WAF reacting to that value:
```bash
DEBUG -- ddtrace: [ddtrace] (/Users/gustavo.caso/src/github.com/DataDog/dd-trace-rb/lib/datadog/appsec/contrib/rack/reactive/request.rb:57:in `block in subscribe') WAF: #<Datadog::AppSec::WAF::Result:0x000000010775edd0 @status=:match, @data=[{"rule"=>{"id"=>"3c3e5dbc-0ad3-439d-9a98-1304393c0cdf", …
```
=> [APPSEC-9340] Appsec add support for custom rules

.github/workflows/system-tests.yml
Since the system-tests changed to run their test in the host, rather than on a Docker container, rather than on a Docker container.
https://github.com/DataDog/system-tests/pull/958
We can no longer build the runner as a Docker image and push it to the registry.
This PR removes the step that builds the runner image as a Docker image and ensures all Python dependencies are still before running the tests.
The biggest downside of not being able to have the runner image as a Docker image, is that for every test scenario we have, we need to download the python packages. Making the tests suite take longer than before 😢 
With the fix the total time for the jobs is 15min. Not bad, but I will like to try other improvements on subsequent PRs, for now I think is important to …
=> Fix system tests CI jobs

ext/ddtrace_profiling_native_extension/NativeExtensionDesign.md, ext/ddtrace_profiling_native_extension/extconf.rb, ext/ddtrace_profiling_native_extension/native_extension_helpers.rb, ext/ddtrace_profiling_native_extension/private_vm_api_access.c
Ruby 3.3.0-preview1 is the first release of the 3.3 branch. It includes a pretty big change: it drops MJIT (one of the two JIT implementations being shipped, the other being YJIT).
This affects the profiler because we were (ab)using an internal header that Ruby included only for supporting MJIT, and this header is no more.
The solution here is to use the same solution we were using for Ruby < 2.6. Quoting the `NativeExtensionDesign.md` file:
> Because these private header files are not included in regular Ruby installations, we have two different workarounds:
>
> 1. for Ruby versions >= 2.6 we make use use the Ruby private MJIT header
> 2. for Ruby versions < 2.6 (legacy Rubies) we make use of the `debase-ruby_core_source` gem
Thus, the strategy going forward …
=> [PROF-7622] Add support for profiling Ruby 3.3.0-preview1

lib/datadog/core/telemetry/collector.rb, lib/datadog/core/telemetry/v1/dependency.rb, spec/datadog/core/telemetry/v1/dependency_spec.rb
`Datadog::Core::Telemetry::V1::Dependency` is currently report both gem `version` and gem `hash` values.
The spec states that `hash` should only be used when the value for `version` cannot be provided, which doesn't happen with Ruby Gems.
This PR removes `hash`, cleaning up our telemetry data and preventing issues during data processing.
=> Telemetry:Do not send Dependency `hash` when `version` is present

Gemfile, spec/datadog/ci/ext/environment_spec.rb
I Updated the rubocop version for the newer version of Ruby. 
I primarily work on the latest version of ruby, and my IDE was complaining the rubocop version installed did not recognise ruby `3.2`
I added a condition on our `Gemfile` to fix that. 
Here is the [rubocop file](https://github.com/rubocop/rubocop/blob/v1.33.0/lib/rubocop/target_ruby.rb#L7) that specifies which ruby version is supported. The update I did was a bit on the conservative side. There is a newer version of Rubocop [1.51.0](https://github.com/rubocop/rubocop/releases/tag/v1.51.0). 
If we feel courageous, we can try the latest version 😄 
**Motivation**
=> Update robocop version to work with ruby 3.2

Gemfile, Steepfile
This PR upgrades the `steep` typechecker gem to version 1.4.
This version no longer uses the `pathname` nor `parallel` gems that previously required workarounds, which I've also removed.
Additionally, it drops the `set` library from the `Steepfile`, since it's now built-in and was causing warnings:
```
W, [2023-05-22T14:09:26.592230 #373829]  WARN -- rbs: `set` has been
moved to core library, so it is always loaded. Remove explicit
loading `set`
```
Use latest typechecking goodness, drop painful workarounds.
N/A
Validate that type checking still passes.
=> Upgrade to steep 1.4 and remove workarounds

lib/datadog/core/configuration/settings.rb, spec/datadog/core/configuration/settings_spec.rb, spec/datadog/core/utils/safe_dup_spec.rb
1. Make `env` and `service` configuration backward compatible for symbol
2. Add missing spec for `SafeDup`
=> Fix symbol configuration for `env` and `service`

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c, integration/apps/rack/spec/integration/basic_spec.rb, integration/apps/rails-five/spec/integration/basic_spec.rb, integration/apps/rails-six/spec/integration/basic_spec.rb, integration/apps/sinatra2-classic/spec/integration/basic_spec.rb, integration/apps/sinatra2-modular/spec/integration/basic_spec.rb, lib/datadog/core/configuration/settings.rb, lib/datadog/profiling/collectors/cpu_and_wall_time_worker.rb, lib/datadog/profiling/component.rb, sig/datadog/profiling/collectors/cpu_and_wall_time_worker.rbs, sig/datadog/profiling/component.rbs, spec/datadog/core/configuration/settings_spec.rb, spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb, spec/datadog/profiling/component_spec.rb
This PR adds a new mode to the profiler, which we're calling the "no signals" workaround.
It also makes the new CPU Profiling 2.0 the default for Ruby 2.3, 2.4 and 2.5, and automatically enables the "no signals" workaround on these Ruby versions.
This mode is a workaround for a few incompatibility issues with the new CPU Profiling 2.0 profiler. In #2702, when we made CPU Profiling 2.0 the default mode, we listed two cases where we were falling back to the legacy profiler:
* [Some gems use native libraries that don't handle the `EINTR` error code that can be caused by a signal handler interrupting a system call](https://docs.datadoghq.com/profiler/profiler_troubleshooting/ruby/#unexpected-run-time-failures-and-errors-from-ruby-gems-that-use-native- …
=> [PROF-7361] Implement "no signals" workaround for running CPU Profiling 2.0 without signals

lib/datadog/appsec/contrib/rack/gateway/request.rb, lib/datadog/appsec/contrib/rack/reactive/request.rb, spec/datadog/appsec/contrib/rack/gateway/request_spec.rb, spec/datadog/appsec/contrib/rack/reactive/request_spec.rb
Reduce the raw URI to a relative URI
**Motivation**
Rules for path passlisting match against `server.request.uri.raw` but do not take into account absolute URIs (that include scheme and authority), instead assuming path only (or rather, relative URI, since strangely they could technically match against the query string, which is not part of the URI path definition). Witness the `regex:` key of such a rule:
```
"conditions": [
{
"operator": "match_regex",
"parameters": {
"inputs": [
{
"address": "server.request.uri.raw"
}
],
"options": {
"case_sensitive": false
},
"regex": "^/error.*"
}
}
],
```
Which should have read something like:
```
"regex": "^([a-z]+://[^/]+)?/error.*"
```
As a workaround we partially parse the URI and strip the scheme and authority …
=> Use relative URI for server.request.uri.raw

ext/ddtrace_profiling_native_extension/extconf.rb
This PR adds a new log message to the profiling native extension build log (`mkmf.log`) containing the pkg-config command detected by Ruby.
I'm currently debugging a customer issue where Ruby does not seem to be detecting the correct path for `pkg-config`.
I'm adding this extra logging so we can figure out where Ruby thinks `pkg-config` is.
N/A
Check that new log message shows up in `mkmf.log`.
Here's an example where Ruby doesn't find `pkg-config`:
```
[ddtrace] Ruby detected the pkg-config command is nil
```
...and here's one where it does:
```
[ddtrace] Ruby detected the pkg-config command is "pkg-config"
```
=> Log pkg-config command when building profiling native extension

lib/datadog/profiling.rb, lib/datadog/profiling/component.rb, sig/datadog/profiling/component.rbs, spec/datadog/profiling/component_spec.rb, spec/datadog/profiling/encoding/profile_spec.rb, spec/datadog/profiling/spec_helper.rb
This PR changes the `datadog/profiling.rb` top-level file to not load the `datadog/profiling/pprof/pprof_pb.rb` file unless the legacy profiler is in use (aka don't load it when the new CPU Profiling 2.0 is in use).
The legacy profiler's pprof support conflicts with the ruby-cloud-profiler gem.
This is not a problem for almost all customers, since we now default everyone to use the new CPU Profiling 2.0 profiler. But the issue was still triggered, because currently we still _load_ both the legacy and new profiling code paths.
To work around this issue, and because we plan on deleting the old profiler soon, rather than poking at the pprof support code, we only load the conflicting file when the old profiler is in use. This way customers using the …
=> [PROF-7625] Add workaround for legacy profiler incompatibility with ruby-cloud-profiler gem

lib/datadog/appsec/contrib/rack/gateway/watcher.rb, lib/datadog/appsec/contrib/rack/request_middleware.rb, lib/datadog/appsec/contrib/rails/gateway/watcher.rb, lib/datadog/appsec/contrib/sinatra/gateway/watcher.rb, lib/datadog/appsec/monitor/gateway/watcher.rb, sig/datadog/appsec/contrib/rack/gateway/watcher.rbs, sig/datadog/appsec/contrib/rails/gateway/watcher.rbs, sig/datadog/appsec/contrib/sinatra/gateway/watcher.rbs, sig/datadog/appsec/monitor/gateway/watcher.rbs
Use the `scope.service_entry_span` when tagging a span with appsec related tags.
**Motivation**
Make sure AppSec features work as expected, and confront to the system tests specs 
CI
=> [APPSEC-9935] AppSec, make sure to use service entry span.

lib/datadog/appsec/response.rb, sig/datadog/appsec/response.rbs, spec/datadog/appsec/response_spec.rb
Based on the [internal] specs. The default content type and the response of the blocked page should be `JSON`. 
I update the code that handles that, I also added a bunch os new specs. I fixed an issue in which spaces between the `,` for separating multiple HTTP accept values.
**Motivation**
CI
=> [APPSEC-9936] Update AppSec response content_type resolution

lib/datadog/core/configuration/settings.rb, lib/datadog/core/remote/client.rb, sig/datadog/core/configuration/settings.rbs, sig/datadog/core/remote/client.rbs, spec/datadog/core/configuration/settings_spec.rb, spec/datadog/core/remote/client_spec.rb
Allow setting remote configuration service name
**Motivation**
Service name set by `DD_SERVICE` or `Datadog.configure { |c| c.service = ... }` may be absent or differ from integration service name configuration in advanced sub-service naming configuration cases.
Having it default to Rack's service name could be a thing, but was found to be a bit unreliable in such advanced configurations. It needs a bit more testing so we'll land this as a stopgap.
This does not address the case of `request_queuing`.
CI
=> [APPSEC-9989] Allow setting remote configuration service name

lib/datadog/appsec.rb, lib/datadog/appsec/component.rb, lib/datadog/appsec/configuration.rb, lib/datadog/appsec/configuration/settings.rb, lib/datadog/appsec/contrib/devise/ext.rb, lib/datadog/appsec/contrib/devise/integration.rb, lib/datadog/appsec/contrib/devise/patcher.rb, lib/datadog/appsec/contrib/devise/patcher/authenticatable_patch.rb, lib/datadog/appsec/contrib/devise/patcher/registration_controller_patch.rb, lib/datadog/appsec/contrib/devise/resource.rb, lib/datadog/appsec/contrib/devise/tracking.rb, lib/datadog/appsec/extensions.rb, lib/datadog/kit/appsec/events.rb, sig/datadog/appsec/configuration.rbs, sig/datadog/appsec/configuration/settings.rbs, sig/datadog/appsec/contrib/devise/ext.rbs, sig/datadog/appsec/contrib/devise/integration.rbs, sig/datadog/appsec/contrib/devise/patcher.rbs, sig/datadog/appsec/contrib/devise/patcher/authenticatable_patch.rbs, sig/datadog/appsec/contrib/devise/patcher/registration_controller_patch.rbs, sig/datadog/appsec/contrib/devise/resource.rbs, sig/datadog/appsec/contrib/devise/tracking.rbs, sig/datadog/appsec/extensions.rbs, spec/datadog/appsec/configuration/settings_spec.rb, spec/datadog/appsec/contrib/devise/patcher/authenticatable_patch_spec.rb, spec/datadog/appsec/contrib/devise/patcher/registration_controller_patch_spec.rb, spec/datadog/appsec/contrib/devise/resource_spec.rb, spec/datadog/appsec/contrib/devise/tracking_spec.rb, spec/datadog/appsec/extensions_spec.rb, spec/datadog/kit/appsec/events_spec.rb
The PR adds a new AppSec integration `devise`. The integration is responsible for instrumenting User events: `login`, and `singup`. 
The PR also adds a couple of things:
- A new AppSec configuration `automated_track_user_events`
- Add a AppSec user event `track_signup`
**Motivation**
CI
=> [APPSEC-9545] Devise integration and automatic user events 

lib/datadog/appsec/contrib/rack/request_middleware.rb, lib/datadog/appsec/event.rb, lib/datadog/kit/appsec/events.rb, lib/datadog/kit/identity.rb, spec/datadog/appsec/contrib/rack/integration_test_spec.rb, spec/datadog/appsec/contrib/rails/integration_test_spec.rb, spec/datadog/appsec/contrib/sinatra/integration_test_spec.rb, spec/datadog/appsec/contrib/support/integration/shared_examples.rb, spec/datadog/appsec/event_spec.rb, spec/datadog/kit/appsec/events_spec.rb, spec/datadog/kit/identity_spec.rb
With `1.11.x`, we introduce a new way to manage the AppSec scope: https://github.com/DataDog/dd-trace-rb/pull/2858, which fundamentally changed how we tag spans and traces. Before that change, we used to tag traces rather than spans. 
When tracing is disabled, fetching the `active_trace` works, but the `active_span` is `nil`. So to keep working as before, we need to ensure that appsec works as expected when tracing is disabled, making everything a no-op as contradicting as it sounds since AppSec needs tracing as the transport layer. So in those weird cases where someone disable tracing and not appsec, things should not break. 
**Motivation**
CI
=> [APPSEC-10049] Appsec handle tracing disabled and appsec events

lib/datadog/profiling.rb
This PR documents the profiler `require` strategy, as a follow-up to the discussion in
<https://github.com/DataDog/dd-trace-rb/pull/2891#discussion_r1219151733>.
Make it easier to maintain by clearly documenting our expectations.
N/A
Nothing to test, only comments added.
=> Document profiler `require` strategy

lib/datadog/appsec/contrib/devise/ext.rb, lib/datadog/appsec/contrib/rack/ext.rb, lib/datadog/appsec/contrib/rails/ext.rb, lib/datadog/appsec/contrib/sinatra/ext.rb
Based on the thread https://github.com/DataDog/dd-trace-rb/pull/2877#discussion_r1231102591 
Removed unused constants from appsec contrib folder 
**Motivation**
=> Removed unused constants from Appsec::Contrib::*::Ext modules

integration/images/ruby/3.1/Dockerfile, integration/images/ruby/3.2/Dockerfile, integration/images/ruby/3.3/Dockerfile
This PR replaces `netcat` with `netcat-openbsd` in the `Dockerfile`s used for the Ruby 3.1, 3.2 and 3.3 integration images.
I did this change after running into the following issue in one of my latest PRs
(<https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/10471/workflows/398f98c3-8d84-4d94-afff-8c92370be60d/jobs/389184>):
```
===> Installing dependencies
+ echo ===> Installing dependencies
+ apt-get -y update
Get:1 http://deb.debian.org/debian bookworm InRelease [147 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8904 kB]
Get:5 http://deb.debian.org/debian-security …
```
=> Fix integration apps ruby image build for Ruby 3.1/3.2/3.3

lib/datadog/profiling/collectors/cpu_and_wall_time_worker.rb, lib/datadog/profiling/collectors/idle_sampling_helper.rb, spec/datadog/profiling/collectors/idle_sampling_helper_spec.rb
This PR tweaks the way we set the thread names in the profiler threads.
Previously, each worker thread set its own name; now, the caller thread also sets the name.
Because Ruby threads cannot be named at creation (which is weird -- Java allows this), setting the name of a thread is always a race: there's a period after the `Thread` object is created where the thread will have no name.
In that period, calling `Thread.list` will not see the name.
I suspect this is the issue that led to a flaky test reported by @tonycthsu
(<https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/10382/workflows/ed4867b5-aa41-4179-a27c-fdb73b8d86c2/jobs/385644>): the integration tests check that all profiler threads are alive by checking for their names, but …
=> Fix flaky profiler integration test due to thread naming race

.github/workflows/test-yjit.yaml, Rakefile, Steepfile, docs/GettingStarted.md, lib/datadog/core/environment/yjit.rb, lib/datadog/core/runtime/ext.rb, lib/datadog/core/runtime/metrics.rb, sig/datadog/core/environment/yjit.rbs, spec/datadog/core/runtime/metrics_spec.rb
Adds YJIT runtime stats to the Ruby Runtime Metrics.
**Motivation**
YJIT was [deemed production ready in Ruby 3.2](https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/). YJIT includes its own [runtime stats](https://github.com/ruby/ruby/blob/master/doc/yjit/yjit.md#other-statistics), which would be useful to gauge. 
Of particular use is the `OBJECT_SHAPE_COUNT` metric. Ruby has a ceiling on the total number of unique shapes but we currently don't have a convenient way of keeping track of those figures to determine if optimizations need to be made.
The comments in `lib/datadog/core/environment/yjit.rb` I mostly copied directly from the [YJIT source code](https://github.com/ruby/ruby/blob/2759cf46f28b1f5ba52f6b7686fd23cb8d792ede/yji …
=> Gauge primitive RubyVM::YJIT.runtime_stats, if YJIT is enabled

lib/datadog/core/workers/async.rb, lib/datadog/profiling.rb, lib/datadog/tracing/metadata/ext.rb, lib/datadog/tracing/trace_operation.rb, lib/datadog/tracing/trace_segment.rb, lib/datadog/tracing/tracer.rb, lib/ddtrace/transport/trace_formatter.rb, spec/datadog/profiling_spec.rb, spec/datadog/tracing/trace_operation_spec.rb, spec/datadog/tracing/trace_segment_spec.rb, spec/datadog/tracing/tracer_spec.rb, spec/ddtrace/transport/trace_formatter_spec.rb
This PR implements the Datadog-internal
"RFC: Identifying whether a span’s host has profiling enabled" similar to what
[dd-trace-java](https://github.com/DataDog/dd-trace-java/pull/5395) does by including a `_dd.profiling.enabled` tag when profiling is enabled.
This is similar to the existing `_dd.appsec.enabled` tag.
This enables a better user experience in the "Code Hotspots" tab, e.g. for users that run profiling in a subset of their fleet.
This way we can immediately tell them "hey, there's no profiling data" rather than making them wait a few minutes and then telling them that we didn't find anything.
N/A
Validate that the `_dd.profiling.enabled` tag shows up in the UX.
=> [PROF-7786] Include _dd.profiling.enabled tag

spec/datadog/tracing/benchmark/support/benchmark_helper.rb, spec/datadog/tracing/contrib/mongodb/regression_issue_1235_spec.rb, spec/datadog/tracing/integration_spec.rb, spec/support/synchronization_helpers.rb
While trying to debug the flaky test https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/10532/workflows/2959b319-e444-4122-927c-b8055d338d69/jobs/391689:
```
Server internal tracer
traces the looping scheduled push
rake aborted!
SignalException: SIGTERM
/app/Rakefile:260:in `declare'
/app/Rakefile:317:in `block in <top (required)>'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.3.26/lib/bundler/cli.rb:486:in `exec'
/usr/local/bundle/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/command.rb:27 …
```
=> Prevent fork tests from hanging test suite

lib/datadog/core/configuration/option.rb, lib/datadog/core/configuration/options.rb, spec/datadog/core/configuration/base_spec.rb
This PR adds  the `using_default?` to `Core::Configuration` 
**Motivation**
I will port AppSec (ASM) configuration to use the one in `Core::Configuration`. The one key feature that the ASM configuration has that the core configuration has is the ability to check if a value has been set or if it is using the default value.
Here is the code ASM:
https://github.com/DataDog/dd-trace-rb/blob/f7d1e5e42419e9adced5e05d82eda8bdd59d5b48/lib/datadog/appsec/configuration.rb#L88-L90
https://github.com/DataDog/dd-trace-rb/blob/cbbd7490274f0b483fa59486647a78be45979d82/lib/datadog/appsec/remote.rb#L107-L109
Once the code is merged, we can migrate the ASM configuration to use the core configuration 
=> Add `using_default?` method to Core::Configuration

lib/datadog/tracing/contrib/grpc/datadog_interceptor/client.rb, spec/datadog/tracing/contrib/grpc/datadog_interceptor/client_spec.rb
Datadog::Tracing::Contrib::GRPC::DatadogInterceptor::Client#trace is currently causing all GRPC client operations to return 0.0 instead of whatever they were supposed to return. This is a bit of a Ruby gotcha.
This method returns :three
```ruby
def broken_method
begin
:one
rescue => e
:two
else
:three
end
end
```
So when `#trace` is putting `yield` in a `begin` block with an `else`, it's not actually returning the result of yield; it's returning the result of the else block. I guess this was broken in https://github.com/DataDog/dd-trace-rb/pull/2620
Fix it by explicitly returning the result of yield.
**Motivation**
All my GRPC client methods started returning `0.0` after upgrading ddtrace 😱 
Now my GRPC client …
=> Make sure the GRPC client interceptor actually returns the response

.github/workflows/check.yml
All external PRs are stuck because "Check types" does run for external contributors, not even after manual approval (see https://github.com/DataDog/dd-trace-rb/pull/2928, for example):
Interestingly CodeQL does work correctly, running on approval:
My research was not 100% conclusive, but I believe that the `on` trigger is the reason.
This PR change the `on` trigger to look more similar to CodeQL's, specifically regarding having an explicit `pull_request` trigger.
=> Actions:Allow type check to run at PR level

lib/datadog/tracing/configuration/ext.rb, lib/datadog/tracing/contrib/aws/ext.rb, lib/datadog/tracing/contrib/aws/instrumentation.rb, lib/datadog/tracing/contrib/ext.rb, lib/datadog/tracing/contrib/kafka/ext.rb, lib/datadog/tracing/contrib/sneakers/ext.rb, lib/datadog/tracing/contrib/sneakers/tracer.rb, lib/datadog/tracing/contrib/span_attribute_schema.rb, lib/datadog/tracing/metadata/ext.rb, sig/datadog/tracing/configuration/ext.rbs, sig/datadog/tracing/contrib/aws/ext.rbs, sig/datadog/tracing/contrib/ext.rbs, sig/datadog/tracing/contrib/kafka/ext.rbs, sig/datadog/tracing/contrib/sneakers/ext.rbs, sig/datadog/tracing/contrib/span_attribute_schema.rbs, spec/datadog/tracing/contrib/aws/instrumentation_spec.rb, spec/datadog/tracing/contrib/span_attribute_schema_examples.rb, spec/datadog/tracing/contrib/span_attribute_schema_spec.rb
Adds `peer.service` extraction logic and implements it in the AWS integration
`peer.service` is a tag that needs to be set by extracting some values from certain "precursor" tags which vary based on span type and of which the complete list is already agreed upon internally which are checked for in this PR but may need to be fully implemented in the future for certain integrations. This PR implements the logic of checking and extracting these values within the `set_peer_service_from_source` method which checks span type and the existence of various "precursor" tags before setting `peer.service` and the source from which it was extracted.
Note however that `peer.service` is only extracted when not explicitly set by the user which is checked by the `should_set_peer_service` method which …
=> `peer.service` extraction logic w/AWS

ext/ddtrace_profiling_native_extension/collectors_thread_context.c, spec/datadog/profiling/collectors/thread_context_spec.rb
This PR adds a fallback name of "main" to the main Ruby thread.
The main Ruby thread is first thread created in the VM, and the one that is returned by `Thread.main` (when in the main Ractor).
As more profiling features start to show the name in the UX, it's annoying to often have the main thread not have a name.
This PR sits atop #2937 to avoid any merge conflicts (since both touch labels and the `ThreadContext` collector state), but is otherwise completely independent of that one.
This change includes test coverage.
You can see it in action by profiling a Ruby app that never names its main thread, and then confirming that profiling data for that thread is shown under the name `main` in the …
=> Add fallback name for main thread in profiling data

Appraisals, Rakefile, docs/GettingStarted.md, lib/datadog/ci.rb, lib/datadog/ci/contrib/minitest/configuration/settings.rb, lib/datadog/ci/contrib/minitest/ext.rb, lib/datadog/ci/contrib/minitest/integration.rb, lib/datadog/ci/contrib/minitest/patcher.rb, lib/datadog/ci/contrib/minitest/test_helper.rb, sig/datadog/ci/contrib/minitest/configuration/settings.rbs, sig/datadog/ci/contrib/minitest/ext.rbs, sig/datadog/ci/contrib/minitest/integration.rbs, sig/datadog/ci/contrib/minitest/patcher.rbs, sig/datadog/ci/contrib/minitest/test_helper.rbs, spec/datadog/ci/contrib/minitest/instrumentation_spec.rb, spec/datadog/ci/contrib/minitest/integration_spec.rb, spec/datadog/ci/contrib/minitest/patcher_spec.rb
Add CI Visibility support for the Minitest framework.
**Motivation**
Datadog doesn't currently support using Minitest with the CI Visibility feature. It's easy enough to add your own custom integration, but I think it makes sense for `dd-trace-rb` to provide first-class support for Minitest given that it's the default testing framework for Ruby on Rails.
- RSpec uses a relative path with the `./` prefix for the test suite name. Right now, we're using `Pathname.new(path).relative_path_from(Pathname.pwd).to_s` which doesn't include the `./` prefix. Should we mirror the RSpec setup?
- Currently, it only supports `minitest/unit`, I haven't dug into what it would take to support `minitest/spec`.
- Minitest supports skip reasons, but provides a …
=> Add Minitest CI integration

spec/datadog/tracing/contrib/elasticsearch/transport_spec.rb
fix test flakiness by reverting to not sending traces to apm-test-agent
=> fix flaking elasticsearch contrib test flakiness

ext/ddtrace_profiling_native_extension/extconf.rb, ext/ddtrace_profiling_native_extension/private_vm_api_access.c
This PR fixes a theoretical line number calculation bug in the profiler.
Why theoretical?
Because the `! pc` branch it's under is never called by the profiler currently (the `ddtrace_rb_profile_frames` checks for a valid `pc` before calling the line number calculation). Nevertheless, I think it's worth fixing as in the future our code may change.
Since Ruby 3.2.0+ (<https://github.com/ruby/ruby/pull/6430>) the `first_lineno` that Ruby stores for a set of instructions is stored as a regular `int` and not as a Ruby `VALUE`.
The `calc_pos` function inside `private_vm_api_access.c` was copied from the Ruby sources before that refactoring, and thus was still trying to convert the Ruby `VALUE` to an `int`, which is not correct for modern Rubies.
Since this code path …
=> Fix theoretical line number calculation bug in profiler for Ruby 3.2+

ddtrace.gemspec, ext/ddtrace_profiling_native_extension/http_transport.c, ext/ddtrace_profiling_native_extension/native_extension_helpers.rb, spec/datadog/profiling/http_transport_spec.rb
This PR bumps the libdatadog dependency on dd-trace-rb to version 3 (specifically, '~> 3.0.0.1.0').
It also includes small changes to code/tests to adapt to changes in libdatadog and get a green CI.
Libdatadog 3 includes the new "internal metadata" feature which we'll use in #2927.
Despite the jump in major version, the changes between libdatadog 2 and 3 were minimal. The version was bumped because the library is following semantic versioning, and a public API was changed.
Running the profiling specs exercises libdatadog, and thus we have quite a lot of test coverage for it.
=> [PROF-7654] Bump libdatadog dependency to version 3

lib/datadog/ci/contrib/minitest/configuration/settings.rb
The PR that introduced the minitest integration https://github.com/DataDog/dd-trace-rb/pull/2932 and the PR that removed the `lazy` options from the settings DSL https://github.com/DataDog/dd-trace-rb/pull/2931 got merged in parallel. Causing a deprecation warning to show up:
```
W, [2023-07-06T09:48:06.238562 #150779]  WARN -- ddtrace: [ddtrace] Defining an option as lazy is deprecated for removal. Options now always behave as lazy. Please remove all references to the lazy setting.
Non-lazy options that were previously stored as blocks are no longer supported. If you used this feature, please let us know by opening an issue on: https://github.com/datadog/dd-trace-rb/issues/new so we can better understand and support your use case. This will be enforced in the …
```
=> remove lazy call for minitest settings

ext/ddtrace_profiling_native_extension/collectors_thread_context.c, ext/ddtrace_profiling_native_extension/extconf.rb, ext/ddtrace_profiling_native_extension/private_vm_api_access.c, ext/ddtrace_profiling_native_extension/private_vm_api_access.h, spec/datadog/profiling/collectors/thread_context_spec.rb
Naming Ruby threads is optional, and a lot of Ruby code still creates threads and doesn't name them.
As a workaround for Ruby threads that have no name, this PR makes the profiler use the "thread invoke location", which is what Ruby shows in the `to_s`/`inspect` of a thread, for instance:
```
[1] pry(main)> Thread.list.last.name
=> nil
[2] pry(main)> Thread.list.last.to_s
=> "#<Thread:0x00005934cc0143e8 thread-name.rb:3 sleep>"
```
The "invoke location" is the file and line where the block that starts the thread is defined (`thread-name.rb:3` for the example above).
Having nameless threads is annoying because we show this information in several places of our UX, and with the timeline feature this will be even more visible. …
=> [PROF-7440] Use invoke location as a fallback for nameless threads in the profiler

lib/datadog/tracing/contrib/span_attribute_schema.rb, spec/datadog/tracing/contrib/aws/instrumentation_spec.rb, spec/datadog/tracing/contrib/integration_examples.rb, spec/datadog/tracing/contrib/span_attribute_schema_examples.rb, spec/datadog/tracing/contrib/span_attribute_schema_spec.rb
Changes existing and future `peer.service` logic to follow the new v1 version instead.
Removes all usage of old `peer.service` values
Updates all tests accordingly
=> Change `peer.service` logic

Steepfile, lib/datadog/profiling/component.rb, spec/datadog/profiling/component_spec.rb, vendor/rbs/mysql2-aurora/0/mysql2-aurora.rbs
This PR tweaks the libmysqlclient version detection code added in #2770 to also work when the `mysql2-aurora` gem is in use.
The way that the mysql2-aurora gem installs itself leads to the "no signals" workaround (#2873) being incorrectly enabled for customers that do have a modern version of libmysqlclient.
The mysql2-aurora gem likes to monkey patch itself in replacement of `Mysql2::Client`, and uses `method_missing` to delegate to the original BUT unfortunately does not implement `respond_to_missing?` and thus one of our checks (`respond_to?(:info)`) was incorrectly failing.
This change includes code coverage. This can also be reproduced easily by adding the `mysql2-aurora` gem to the …
=> Fix profiler libmysqlclient version detection with mysql2-aurora gem

lib/datadog/profiling/load_native_extension.rb
This PR tweaks the error message for when `ddtrace_profiling_loader` fails to load to suggest to customers that they reinstall ddtrace.
This came out of a customer running into this issue in <https://github.com/DataDog/dd-trace-rb/issues/2242#issuecomment-1620191535>
Here's how it looks now when it fails:
```
$ DD_PROFILING_ENABLED=true bundle exec ruby -e "require 'datadog/profiling/preload'"
WARN -- ddtrace: [ddtrace] Profiling was requested but is not supported,
profiling disabled: There was an error loading the profiling native extension due to
'LoadError Failed to load the profiling loader extension. To fix this, please remove
and then reinstall ddtrace (Details: cannot load such file --
ddtrace_profiling_loader.2.7.7_x86_64-linux)' at …
```
=> Minor: Improve error message when ddtrace_profiling_loader fails to load

.circleci/config.yml, docker-compose.yml
Changes OpenSearch version from 2.8.0 to 1.3.6 in order to resolve flaky CircleCI tests.
**Motivation**
Previous version was occasionally causing the OpenSearch container to error out.
N/A
Changes can be tested by pushing to CircleCI. Previous run results are located [here](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb?branch=feature%2Fopensearch_from_scratch). Note that the test runs are currently all showing as errors due to google-protobuf dropping support for Ruby 2.6. This causes `build_and_test_integration-2.6` to fail each time. There are other flaky tests present as well (see [here](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/10882/workflows/59ec0697-665b-4a5d-adc4-9227cc184 …
=> OpenSearch Integration Version Update

lib/datadog/core/telemetry/http/transport.rb, lib/datadog/tracing/contrib/http/circuit_breaker.rb, lib/ddtrace/transport/ext.rb, sig/datadog/tracing/contrib/http/circuit_breaker.rbs, spec/datadog/core/telemetry/http/transport_spec.rb, spec/datadog/tracing/contrib/http/circuit_breaker_spec.rb, spec/datadog/tracing/contrib/http/request_spec.rb, spec/support/network_helpers.rb
Telemetry has its own custom transport, and it was missing a flag that lets the `Net::HTTP` tracing integration know to skip instrumenting the telemetry request.
This PR adds that flag, as an HTTP header, similar to how other `ddtrace` components operate.
There is also a bit of refactoring around this flag, to easy clarity during future use and simplify the circuit breaker implementation.
=> Prevent telemetry requests from being traced

docs/GettingStarted.md
This PR updates our public documentation to reflect our support for the latest stable version of Ruby: 3.2.
=> Doc:Add Ruby 3.2 support to our compatibility matrix

Steepfile, lib/datadog/profiling/component.rb, spec/datadog/profiling/component_spec.rb, vendor/rbs/passenger/0/passenger.rbs
This PR adds one more case where we automatically need to apply the profiler "no signals" workaround (added in #2873): when the Ruby app is running inside the passenger web server.
This makes sure the profiler does not cause issues out-of-the-box for customers running passenger.
Passenger detection was inspired on https://stackoverflow.com/a/12246652/4432562 .
This was reported in https://github.com/datadog/dd-trace-rb/issues/2976 and ~I suspect~ (now confirmed) at least one other customer has ran into this issue.
Separate from this PR, I plan to improve our documentation, as well as try to get in touch with the passenger folks to get a fix upstream. I'm tracking that work in the mentioned issue.
I'm also considering …
=> Automatically enable profiler "no signals" workaround for passenger web server

.rubocop.yml, lib/datadog/profiling/flush.rb
`!!` is the de facto way in Ruby to cast an Object to boolean.
We should allow this pattern in the repository.
=> Lint:Disable double negation cop

lib/datadog/tracing/contrib/grpc/datadog_interceptor/client.rb, lib/datadog/tracing/contrib/grpc/ext.rb, lib/datadog/tracing/contrib/grpc/formatting.rb, sig/datadog/tracing/contrib/grpc/ext.rbs, spec/datadog/tracing/contrib/grpc/datadog_interceptor/client_spec.rb, spec/datadog/tracing/contrib/grpc/integration_test_spec.rb, spec/datadog/tracing/contrib/grpc/interception_context_spec.rb
Continuing off of #2943, this PR implements `peer.service` in grpc utilizing the newly added `rpc.service` tag.
Updates all tests to use proper GRPC methods such that `peer.service` can be properly tested as well
As usual for this feature, feel free to review but please do not merge without @delner explicitly approving it
=> Implement `peer.service` for grpc

lib/datadog/core/configuration/base.rb, lib/datadog/core/configuration/option.rb, lib/datadog/core/configuration/option_definition.rb, lib/datadog/core/configuration/options.rb, sig/datadog/core/configuration/option.rbs, sig/datadog/core/configuration/option_definition.rbs, spec/datadog/core/configuration/base_spec.rb, spec/datadog/core/configuration/option_definition_spec.rb, spec/datadog/core/configuration/option_spec.rb
This PR extracts the logic for adding support for `env`, `deprecated_env`, `env_parser`, and `type` validation from https://github.com/DataDog/dd-trace-rb/pull/2970
For a more detail discussion on these changes please refer to the PR linked above 
**Motivation**
=> Core configuration add env and type backend logic

lib/datadog/core/telemetry/client.rb, lib/datadog/core/telemetry/emitter.rb, lib/datadog/core/telemetry/event.rb, lib/datadog/core/telemetry/v2/app_client_configuration_change.rb, lib/datadog/core/telemetry/v2/request.rb, sig/datadog/core/telemetry/client.rbs, sig/datadog/core/telemetry/emitter.rbs, sig/datadog/core/telemetry/event.rbs, sig/datadog/core/telemetry/http/adapters/net.rbs, sig/datadog/core/telemetry/http/transport.rbs, sig/datadog/core/telemetry/v2/app_client_configuration_change.rbs, sig/datadog/core/telemetry/v2/request.rbs, spec/datadog/core/telemetry/client_spec.rb, spec/datadog/core/telemetry/emitter_spec.rb, spec/datadog/core/telemetry/event_spec.rb, spec/datadog/core/telemetry/v2/app_client_configuration_change_spec.rb, spec/datadog/core/telemetry/v2/request_spec.rb
This PR adds the telemetry event `app-client-configuration-change`, which reports that configuration at the Client Library (`ddtrace`) has changed.
This event captures the changes themselves and a change source (called `origin` in the event).
The first use case is reporting changes from Dynamic Configuration. These have the origin `remote_config`.
The changes are a list of 2-tuples (`List<String, Integer | Boolean | String>`) representing the configuration that was just set.
One thing to noticed is that `app-client-configuration-change` is a Telemetry V2 event, but `ddtrace` currently implements Telemetry V1.
To aid with the migration to V2, the Datadog backend supports a few V2 events through the V1 pipeline. This is one of them.
This PR does not actually report the new event, only …
=> Telemetry:add app-client-configuration-change event

lib/datadog/core/remote/configuration/content.rb, lib/datadog/core/remote/configuration/repository.rb, sig/datadog/core/remote/configuration/content.rbs, spec/datadog/core/remote/configuration/content_spec.rb, spec/datadog/core/remote/configuration/respository_spec.rb
This PR adds the `apply_state` and `apply_error` fields to the configuration content payload we sent back to the agent.
This allows downstream systems to know if the configuration was correctly applied, and if not, why.
This is used to display to users that Remote Configuration was correctly applied, or if it was not, what was the reason.
=> RC:Add apply state and apply error

CHANGELOG.md
In #2711, I forgot to include an update to the CHANGELOG.
Only updates the CHANGELOG.
**Motivation**
Wanting to mention the YJIT stat tracking so that folks interested in tracking them don't miss it.
n/a
n/a documentation only
=> Update CHANGELOG to mention YJIT stat tracking

lib/datadog/tracing/correlation.rb, spec/datadog/tracing/correlation_spec.rb
https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/ruby/#for-logging-in-ruby-applications
We exposed `Datadog::Tracing.correlation#trace_id` as public API, which user ends up with different injection result from manual log injection(returning the entire 128 bit trace ID).
This PR enforce the coercion of lower 64 bits trace ID on this API to ensure the correctness of manual log injection.
=> Fix manual log injection for 128 bit trace_id

lib/datadog/appsec/configuration/settings.rb, sig/datadog/appsec/configuration/settings.rbs, sig/datadog/core/configuration/option_definition.rbs, spec/datadog/appsec/configuration/settings_spec.rb
Build on top of https://github.com/DataDog/dd-trace-rb/pull/2983
Update the AppSec settings to use `env`, and `type` options to improve appsec settings integrity
**Motivation**
=> Update AppSec Settings to use the `env`, and `type` options

spec/datadog/tracing/contrib/elasticsearch/transport_spec.rb
Elasticsearch tests started failing due to Webmock assertions recently.
This is caused by Elasticsearch using Webmock, but other processes like Telemetry still being executed in the background. This PR allows agent calls to go through, while still respecting Elasticsearch Webmock stubs.
=> Fix:Elasticsearch Webmock testing

CHANGELOG.md
Fix the format of CHANGELOG of v1.12.1.
**before**
**after**
**Motivation**
To make changes easier to read.
None
Doc change only.
=> Fix a format of CHANGELOG

ext/ddtrace_profiling_native_extension/collectors_thread_context.c, spec/datadog/profiling/collectors/thread_context_spec.rb
This PR adds a fallback invoke location (which gets used as a name) for threads that a) Are unnamed, and b) Were started from native code.
The added invoke location is the fixed string ~`(Unnamed thread from native gem)`~ `(Unnamed thread from native code)`.
We previously (in #2950) started using invoke location for threads that do not have a name BUT when a thread is started from native code it would have an empty name.
Having an empty name is not particularly helpful, so I decided to instead have a simple placeholder that at least provides an hint on what the thread may be.
We don't yet do any resolving of symbols from native code, but in the future I guess we may try to see if the native code has a name at the C level, …
=> [PROF-7440] Add fallback name/invoke location for unnamed threads started in native code

integration/apps/rack/Gemfile, integration/apps/rack/README.md, integration/apps/rack/bin/run, integration/apps/rack/script/ci
This PR adds one more webserver to the rack integration testing app: Phusion Passenger.
In #2976 a customer reported an issue with profiling apps running on passenger. I'm adding passenger to our test suite to avoid any future regressions.
I've actually tested that the customer issue does show up on our integration app if I revert the changes from #2978.
Validate that the rack CI app is running with passenger as well.
=> [PROF-7966] Add passenger testing to rack integration app

lib/datadog/core/configuration/option.rb, spec/datadog/appsec/configuration/settings_spec.rb, spec/datadog/core/configuration/option_spec.rb, spec/datadog/core/configuration/options_spec.rb
Extracted from https://github.com/DataDog/dd-trace-rb/pull/2988/commits/ce03d1921fe2f2ee561ac8750fec76b4fba03239#r1273320023
The PR ensures that the default values get duplicated before storing as the setting value 
**Motivation**
=> Make sure to dup the default value when setting it

spec/datadog/core/remote/component_spec.rb
We have failures like
```
1) Datadog::Core::Remote::Component::Barrier#wait_next with an instance timeout unblocks on timeout
Failure/Error: expect(record).to eq [:one, :two, :three]
expected: [:one, :two, :three]
got: [:one, :two, :lift, :three]
(compared using ==)
Diff:
@@ -1 +1 @@
-[:one, :two, :three]
+[:one, :two, :lift, :three]
```
in our MacOS GitHub actions sometimes.
These happen in our Barrier tests because
* Tests have background thread that tries to race each RSpec example:
```ruby
Thread.new do
loop do
sleep delay
record << :lift
barrier.lift
end
end
```
* `delay` is 0.5 seconds.
* The flaky test in question calls `barrier.wait_next` 3 times, with a timeout of `delay/4` or `0.5/4=0.125` seconds on each `#wait_next` call.
* This leaves little time for the test to finish before …
=> Try to fix race condition on Barrier

lib/datadog/appsec/contrib/rails/patcher.rb, lib/datadog/core/utils.rb, lib/datadog/tracing/contrib/active_job/log_injection.rb, lib/datadog/tracing/contrib/active_job/patcher.rb, lib/datadog/tracing/contrib/rails/log_injection.rb, lib/datadog/tracing/contrib/rails/patcher.rb, lib/datadog/tracing/contrib/rails/railtie.rb, sig/datadog/appsec/contrib/rails/patcher.rbs, sig/datadog/tracing/contrib/rails/patcher.rbs, spec/datadog/tracing/contrib/rails/rails_active_job_spec.rb, spec/datadog/tracing/contrib/rails/rails_log_auto_injection_spec.rb
Fixes #2542
As part of Dynamic Configuration, we want to allow users to enable or disable log injection at any time.
The main limitation we have in Ruby Tracing is that we need to patch an integration to enable log injection.
This PR enables all integrations that perform log correlation to always inject the correlation patch methods, but allow it to be safely disabled when `Datadog.configuration.tracing.log_injection` is set to `false` at runtime.
Rails, for example, was making decision at the application startup that couldn't be changed later. This PR addresses that.
We still depend on users having instrumented the integration itself for correlation to work.
Our `SemanticLogger` and `Lograge` integrations already support dynamic configuration of log injection; only `Rails` core logger …
=> Allow for dynamic log injection configuration

lib/datadog/core/remote/component.rb, spec/datadog/core/remote/component_spec.rb
This PR removes the `Barrier#wait_next` functionality which we ended up not making use of.
In #2990 we ran into issues with its current specs, and since we're not using this functionality, it seems like removing it for now seems to be easier than investing more time to fix flakiness in the specs.
N/A
Existing tests already cover the `Barrier` APIs.
=> Remove unused Barrier#wait_next functionality

lib/datadog/core/configuration/components.rb, lib/datadog/tracing/contrib/rack/middlewares.rb, spec/datadog/core/configuration/components_spec.rb, spec/datadog/tracing/contrib/suite/integration_spec.rb
Start RC on demand.
**Motivation**
System tests fail on Sinatra because of corrupted RC state + unfortunate timing when a forking puma is involved. Starting on demand ensures that it happens in the process that needs RC + that no resource is wasted when RC is not needed.
The above can be reevaluated.
System tests should pass
=> Start RC on demand

spec/datadog/tracing/contrib/suite/integration_spec.rb
This PR makes the integration tests for dynamic configuration a bit less noisy and a bit less flaky.
The tests only fail for JRuby 9.2, but the noisy threads is for all versions of Ruby.
=> Improve integration testing for dynamic configuration

lib/datadog/profiling/http_transport.rb, sig/datadog/profiling/http_transport.rbs, spec/datadog/profiling/http_transport_spec.rb
This PR tweaks the `HttpTransport` error logging to include the configuration being used.
For instance, it will now look like:
```
ERROR (lib/datadog/profiling/http_transport.rb:58:in `export') Failed to report profiling data ({:agent=>"unix:///fake-apm-socket.socket"}): failed ddog_prof_Exporter_send: error trying to connect: No such file or directory (os error 2): No such file or directory (os error 2)
```
...I did notice the libdatadog error message seems to be repeated and isn't particularly great; that's a separate issue for a future fix (on the libdatadog side).
While investigating #3037 I noticed this information was not being logged when the profiler failed to report, and I thought it would be come in handy when debugging future issues. …
=> Minor: Improve Datadog::Profiling::HttpTransport error logging

Steepfile, lib/datadog/core/environment/execution.rb, sig/datadog/core/environment/execution.rbs, spec/datadog/core/environment/execution_spec.rb
This PR adds a utility to detect if `ddtrace` is running in a development environment (an environment that is unlikely to need to send traces, profiles, perform appsec checking).
This will enable us to selectively disable heavy features (background workers, network requests) performed by `ddtrace` when the environment does not need it. This is especially helpful when running tests with `ddtrace` installed.
=> Add development environment detection

spec/datadog/tracing/contrib/suite/integration_spec.rb
This PR fixes a race condition that happens when Remote Configuration runs before we are able to install the reconfiguration check in `spec/datadog/tracing/contrib/suite/integration_spec.rb`. [Example CI failures](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/11429/workflows/f0394859-3aa5-43d0-8d54-da40707e0760/jobs/428683):
```
1) contrib integration testing dynamic configuration with dynamic configuration data for tracing_sampling_rate changes default sampling rate and sampling decision
Failure/Error: raise('Wait time exhausted!')
RuntimeError:
Wait time exhausted!
```
I was able to reproduce the issue by adding a sleep between `stub_rc!` and `allow(Datadog::Tracing::Remote).to receive(:process_config)`.
After this PR, I cannot reproduce the issue anymore.
=> Test:Fix race condition on spec:suite

lib/datadog/tracing/contrib/http/instrumentation.rb, spec/datadog/tracing/contrib/ethon/easy_patch_spec.rb, spec/datadog/tracing/contrib/excon/instrumentation_spec.rb, spec/datadog/tracing/contrib/faraday/middleware_spec.rb, spec/datadog/tracing/contrib/http/request_spec.rb, spec/datadog/tracing/contrib/httpclient/instrumentation_spec.rb, spec/datadog/tracing/contrib/httprb/instrumentation_spec.rb, spec/datadog/tracing/contrib/rest_client/request_patch_spec.rb
Exclude query string for `http.url` tag from `net/http` instrumentation
=> Tracing: Exclude query string for `http.url` tag from `net/http` instrumentation 

.gitlab/benchmarks.yml
This PR does two changes to the benchmark configuration related to profiling:
* Force-disable the no signals workaround for gitlab testing
* Add benchmarking configurations for profiling w/timeline
See individual commit message for details.
Increase coverage for profiler testing.
N/A
I've manually triggered runs for the benchmarks with this configuration. See [gitlab (datadog-internal link only)](https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-rb/-/pipelines/18616381) for details.
=> Tweak profiling benchmark settings + add timeline testing

docs/GettingStarted.md
This PR adds the "Resque workers hang on exit" issue discussed in https://github.com/DataDog/dd-trace-rb/issues/3015 to the "Known issues and suggested configurations" section of our docs.
This issue seems to come up a few times, e.g. in:
* https://github.com/DataDog/dd-trace-rb/issues/466
* https://github.com/DataDog/dd-trace-rb/issues/2379
* https://github.com/DataDog/dd-trace-rb/issues/3015
...so I've decided to document the issue and the best-known workaround so that other customers than unfortunately run into it may find our suggested solution.
N/A
Docs-only change.
=> Document issue with Resque workers hanging

lib/datadog/core/configuration/settings.rb, spec/datadog/core/configuration/components_spec.rb, spec/datadog/core/configuration/settings_spec.rb, spec/datadog/core/remote/component_spec.rb, spec/datadog/tracing/contrib/suite/integration_spec.rb, spec/support/core_helpers.rb, spec/support/test_helpers.rb
By default, it disables the Telemetry and Remote Configuration background workers, which can send HTTP requests, in any environment that is detected as a development environment. See https://github.com/DataDog/dd-trace-rb/pull/3036 for the information about the detection logic.
**Motivation**
Fixes https://github.com/DataDog/dd-trace-rb/issues/2823
`ddtrace` can cause the test suite for the application to fail when `ddtrace` sends unexpected HTTP requests in the background. These requests are rarely desired and only cause noise add overhead.
It's still possible to enable these features in a development environment by using their respective environment variables.
Without the agent running, run any project's test …
=> Disable Telemetry and Remote Configuration in development environments

lib/datadog/tracing/contrib/elasticsearch/patcher.rb
This PR updates the Elasticsearch patcher. Originally, the patcher was using an alias and remove method to instrument the `perform_request` method; now it uses the more modern prepend technique.
**Motivation**
In an effort to update the codebase, the new patcher should be cleaner and clearer.
No changes were made to the patcher_spec file.
These changes can be tested by running the unit tests in `spec/datadog/tracing/contrib/elasticsearch/patcher_spec.rb`, by passing Github tests, and by checking CircleCI.
=> Update Elasticsearch patcher from using alias method to prepend method

benchmarks/profiler_http_transport.rb, lib/datadog/profiling/component.rb, lib/datadog/profiling/exporter.rb, lib/datadog/profiling/flush.rb, sig/datadog/profiling/component.rbs, sig/datadog/profiling/exporter.rbs, sig/datadog/profiling/flush.rbs, spec/datadog/profiling/component_spec.rb, spec/datadog/profiling/exporter_spec.rb, spec/datadog/profiling/flush_spec.rb, spec/datadog/profiling/http_transport_spec.rb, spec/datadog/profiling/integration_spec.rb
This PR adds support for reporting the status of the timeline feature together with profiles, via the internal metadata field.
I ended up doing a bunch of refactoring to make it easier to adds new reported fields as internal metadata; it may be easier to review this PR commit-by-commit.
While this feature is off-by-default, having this internal metadata makes it easier to spot profiles that have/don't have this data without actually opening them up in the UX.
N/A
This change includes test coverage. It's possible internally at Datadog to see this information in profile listings (ping me if you'd like to know more).
=> [PROF-7440] Report status of timeline feature as internal metadata

lib/datadog/tracing/contrib/utils/quantization/http.rb, spec/datadog/tracing/contrib/utils/quantization/http_spec.rb
Small bits of improvement to quantization and obfuscation.
**Motivation**
Stumbled upon a few areas that were lacking.
Regex has been checked for linearity with the new Ruby 3.3 `Regexp.linear_time?`.
```
env SKIP_SIMPLECOV=1 bundle exec rspec spec/datadog/tracing/contrib/utils/quantization/http_spec.rb
```
=> Improve quantization

spec/support/synchronization_helpers.rb
For the currently flaky Sidekiq test, https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/11471/workflows/136d17b9-9561-4937-b59c-66fb2dbadd0c/jobs/430307, the failure information is a rather generic `Wait time exhausted!` error.
I can make Sidekiq tests fail with `Wait time exhausted!` locally, by not having Redis running.
But this doesn't explain the CI failures because only a single Sidekiq test failes, while if Redis wasn't running virtually all of them would fail.
Also, the Redis containers' output in CircleCI's log looks nominal.
One thing that I notice lacking in the Sidekiq tests is any useful output during a failure.
This happens because tests executed in a forked process, and that fork's STDOUT and STDERR are not directly printed in the RSpec process.
This PR captures …
=> Test:Capture output on fork test failures

Rakefile, ext/ddtrace_profiling_native_extension/native_extension_helpers.rb, integration/apps/rack/spec/integration/basic_spec.rb, integration/apps/rails-five/spec/integration/basic_spec.rb, integration/apps/rails-seven/spec/integration/basic_spec.rb, integration/apps/rails-six/spec/integration/basic_spec.rb, integration/apps/sinatra2-classic/spec/integration/basic_spec.rb, integration/apps/sinatra2-modular/spec/integration/basic_spec.rb, integration/images/include/build_ddtrace_profiling_native_extension.rb, spec/datadog/profiling/native_extension_helpers_spec.rb, spec/datadog/profiling/spec_helper.rb
In #3053 I reported the discovery that the profiler is currently not working on Ruby 3.3-head (reported by a customer that tests with head in CI).
A full fix for #3053 seems like it may take a while, so until it's available, let's gracefully disable the profiler in Ruby 3.3, so that instead of a compilation failure, customers just get a nice message saying we don't support 3.3 right now.
Improve experience for current customers testing with 3.3-head and future customers trying to profile 3.3.
Customers will be shown the following message when trying to profile on Ruby 3.3:
> WARN -- ddtrace: [ddtrace] Profiling was requested but is not supported, profiling disabled: Your ddtrace installation is missing support for the …
=> Disable profiler on Ruby 3.3 due to incompatibility

Steepfile, lib/datadog/core/environment/execution.rb, sig/datadog/core/environment/execution.rbs, spec/datadog/core/environment/execution_spec.rb, spec/support/synchronization_helpers.rb, vendor/rbs/spring/0/spring.rbs
Helps address #3050 
This PR ensures that applications preloaded with [Spring](https://github.com/rails/spring) are considered as a "development environment" application, and thus `ddtrace` skips background worker initialization on Spring-enabled environments.
Spring [**must not** be installed in production environments](https://github.com/rails/spring#deployment), giving us confidence that detecting Spring loading won't cause false positives for development environment detection.
=> Ensure Rails running on Spring is considered a development environment

lib/datadog/appsec/configuration/settings.rb, sig/datadog/appsec/configuration/settings.rbs, spec/datadog/appsec/configuration/settings_spec.rb
The automated user events feature has two settings: `enable` and `mode` both can be configured via code or using a single ENV var `DD_APPSEC_AUTOMATED_USER_EVENTS_TRACKING` 
The corner case found is that setting `DD_APPSEC_AUTOMATED_USER_EVENTS_TRACKING=extended|safe` is disabling automated user events. 
This PR ensures the `enabled` setting supports `extended` and `safe` as valid values.
**Motivation**
=> Fix ASM setting for automated user events.

lib/datadog/tracing/contrib/active_support/cache/instrumentation.rb
While trying to make improvements to the ActiveSupport::Cache instrumentation, I noticed that there was a lot of repeated code, and that it used a custom message passing pattern that is not strictly necessary.
This PR refactors this integration by moving all the duplicate behavior into encapsulated methods and removing a bunch of lines in the process :)
=> Refactor ActiveSupport Cache instrumentation

.github/PULL_REQUEST_TEMPLATE.md
This PR updates the pull request template with a security-related question, so we make sure folks remember to loop in the correct team if the PR can have an impact on "code that signs or publishes builds or packages, or handles credentials of any kind".
We're moving to standardize this on all Datadog libraries.
For Datadog employees, you can find the discussion on the internal "RFC: Security review for ci/cd changes in public repos" RFC.
N/A
Once this is merged, open a new PR, validate that the new items show up.
=> Update the pull request template with a security-related section

ext/ddtrace_profiling_native_extension/collectors_thread_context.c, ext/ddtrace_profiling_native_extension/collectors_thread_context.h, ext/ddtrace_profiling_native_extension/extconf.rb, ext/ddtrace_profiling_native_extension/libdatadog_helpers.c, ext/ddtrace_profiling_native_extension/libdatadog_helpers.h, spec/datadog/profiling/collectors/thread_context_spec.rb
This PR builds extends the existing support for the `ThreadContext` collector to sample allocations to also record the "ruby vm type" of sampled objects.
This "ruby vm type" is what Ruby internally represents in its `enum ruby_value_type`, see
https://github.com/ruby/ruby/blob/84a12d657848dfb54f8cc556d344f017a793e95a/include/ruby/internal/value_type.h#L112
I'm working on tagging stacks of sampled objects with both the object class, as well as the ruby vm type.
I'm not yet sure how we may expose the ruby vm type in the UX, but having it is useful for development and debugging, and I can imagine it being useful in advanced use cases (e.g. a customer downloading a pprof to look at this data).
As libdatadog interns labels …
=> [PROF-7307] Include 'ruby vm type' in profiler allocation samples

lib/datadog/tracing/component.rb, sig/datadog/profiling/component.rbs, spec/datadog/core/configuration/components_spec.rb, spec/datadog/profiling/component_spec.rb
Fixes a bug introduced in 94158dbfa631cba05bae43f5bdea10e7d99a2ec8 where the tracing component was passing the AgentSettingsResolver `@logger` which isn't initialized at that point. It should be passing AgentSettingsResolver the `logger` passed to the method instead.
Also, re-add types that were accidentally removed in 94158dbfa631cba05bae43f5bdea10e7d99a2ec8 for profiling/component.rbs.
**Motivation**
CI is emitting warnings about `@logger` not being initialized.
CI should no longer emit warnings. Spec tests added to make sure correct logger is passed.
=> Fix bug where Tracing::AgentSettingsResolver wasn't being passed param logger

spec/datadog/tracing/contrib/sidekiq/server_internal_tracer/job_fetch_spec.rb
Acting on the existing comment about the `sidekiq.job_fetch` test taking a minimum of 2 seconds, this PR overrides the internal, hard-coded timeout to minimize test execution time.
After this change, this test takes ~200ms instead of 2.2s.
With this PR plus #3077, the complete Sidekiq test suite will run in ~1.3 seconds, down from ~6.3 seconds.
=> Test:Reduce wait on long Sidekiq test

lib/datadog/core/configuration/option.rb, lib/datadog/core/configuration/option_definition.rb, sig/datadog/core/configuration/option_definition.rbs, spec/datadog/core/configuration/option_definition_spec.rb, spec/datadog/core/configuration/option_spec.rb
In our initial discussion, we agreed that the `delegate_to` option's main functionality was not to cache the result when configuring. For that reason, renaming it to `cache` would express with more accuracy the intent of the option. 
I started by renaming it, but after seeing how much the option code has evolved since the initial conversation with the introduction of precedence, parsing env vars, etc... While trying to rename it to `cache` I realized that it would be more complicated than it seems, more importantly we have no idea how an option would work using `delegate_to` in the current system. 
For the reason outlined above I think is best to remove the option since no configuration definition is using it, and if we ever want to introduce the ability to …
=> remove `delegate_to` configuration option from our DSL
