DataDog/dd-trace-rb

lib/datadog/core/configuration/option.rb
lib/datadog/core/configuration/option_definition.rb
lib/datadog/core/configuration/settings.rb
lib/datadog/tracing/contrib/active_job/configuration/settings.rb
lib/datadog/tracing/contrib/delayed_job/configuration/settings.rb
lib/datadog/tracing/contrib/faraday/configuration/settings.rb
lib/datadog/tracing/contrib/grpc/configuration/settings.rb
lib/datadog/tracing/contrib/que/configuration/settings.rb
lib/datadog/tracing/contrib/resque/configuration/settings.rb
lib/datadog/tracing/contrib/shoryuken/configuration/settings.rb
lib/datadog/tracing/contrib/sidekiq/configuration/settings.rb
lib/datadog/tracing/contrib/sneakers/configuration/settings.rb
sig/datadog/core/configuration/option_definition.rbs
spec/datadog/core/configuration/option_definition_spec.rb
spec/datadog/core/configuration/option_spec.rb

Rename `experimental_default_proc` to `default_proc`
Check this thread for more context https://github.com/DataDog/dd-trace-rb/pull/2988#discussion_r1273366809

rename experimental_default_proc to default_proc

---

ext/ddtrace_profiling_native_extension/collectors_thread_context.c
lib/datadog/profiling/collectors/thread_context.rb
sig/datadog/profiling/collectors/thread_context.rbs
spec/datadog/profiling/collectors/thread_context_spec.rb

This PR extends the `Profiling::Collectors::ThreadContext` support for sampling allocated objects to also record the object's class.
This will enable us to provide the "Allocations by Allocated Type" feature in the Datadog UX.
N/A
This change includes test coverage. Right now, there's no way to exercise this code other than through tests, because we haven't yet wired it up to trigger during actual Ruby VM allocations. This will come at a later date.

[PROF-7307] Record allocation type when sampling objects

---

lib/datadog/profiling/collectors/cpu_and_wall_time_worker.rb
lib/datadog/profiling/component.rb
sig/datadog/profiling/collectors/cpu_and_wall_time_worker.rbs
spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
spec/datadog/profiling/component_spec.rb

This PR separates the initialization of the `Profiling::Collectors::ThreadContext` component from the initialization for the `Profiling::Collectors::CpuAndWallTimeWorker`.
Now, both are created in `Datadog::Profiling::Component`.
Historically, these two classes have been moving apart, as the profiler development evolves.
As more settings need to get added to the `ThreadContext`, it became very awkward to keep changing the `CpuAndWallTimeWorker` to forward more and more things.
N/A
The existing test coverage already covers this.

Refactor: Separate Profiling ThreadContext initialization from CpuAndWallTimeWorker

---

Steepfile
lib/datadog/profiling/collectors/cpu_and_wall_time_worker.rb
sig/datadog/profiling/collectors/cpu_and_wall_time_worker.rbs

This PR adds the type signatures and enables type checking for the `Profiling::Collectors::CpuAndWallTimeWorker` class.
I've extracted this from another branch I was working on, as it can be cleanly merged right away.
This PR is on top of #3094 to avoid any conflicts, since that PR changed some of the arguments to this class.
Validate that type checking still passes!

Enable type checking for `Profiling::Collectors::CpuAndWallTimeWorker`

---

lib/datadog/tracing/distributed/propagation.rb
spec/datadog/tracing/distributed/propagation_spec.rb

Currently, when extracting from multiple contexts, our propagation would validate against each other to ensure the trace id and span id are identical. This approach ensure that if user includes `Datadog` proprietary propagation, those proprietary tags would be propagated and the user will remain having full functionalities that Datadog offers.
If there is a mismatched being detected, since we are not able to identify the source of truth, it would leads to a broken distributed trace. The third scenario on the right illustrated a possible scenario with a mismatched detected given 128 bits trace ID upstream.
This PR changes the propagation behaviour by removing the validation phase for multiple extractions. This means the first successful extraction would always …

Use first valid extracted style for distributed tracing

---

lib/datadog/tracing/metadata/tagging.rb
spec/datadog/tracing/metadata/tagging_spec.rb

fixes https://github.com/DataDog/dd-trace-rb/issues/3088
An object includes Tagging module, but `#tags` method raise `NoMethodError: undefined method 'merge' for nil:NilClass` or `TypeError: no implicit conversion of nil into Hash` 
Because the instance variables are `nil`. 
The fix is to replace instance variable with protected attribute reader.

Fix tagging with empty data

---

lib/datadog/ci/ext/environment.rb
lib/datadog/core/git/ext.rb
sig/datadog/core/git/ext.rbs
spec/datadog/ci/ext/environment_spec.rb

In cases when it is not possible to automatically extract git environment information for CI visibility we allow users to supply this info via environment variables, see docs [here](https://docs.datadoghq.com/continuous_integration/troubleshooting/#data-appears-in-test-runs-but-not-tests). 
DD_GIT_REPOSITORY_URL and DD_GIT_COMMIT_SHA are required but currently not validated. When these values are not provided or SHA is not valid CI-APP backend silently drops these traces. End users get no feedback in these cases.
We add the following validations to these tags:
- DD_GIT_REPOSITORY_URL must be present
- DD_GIT_COMMIT_SHA must be present, must be 40 characters long must be a valid hex number
In case these values are incorrect we continue to send traces but we log an …

[CIAPP-5371] CI visibility: validate git tags

---

.github/workflows/system-tests.yml
lib/datadog/appsec/contrib/rack/request_middleware.rb

Fix a bug introduced on https://github.com/DataDog/dd-trace-rb/pull/3087
Reported the loaded rules count on the `_dd.appsec.event_rules.error_count` tag. 
I also, added a new system test scenario on our GH actions to avoid introducing a regression again.  

Fix a bug with ASM span tags reporting the number of WAF failed loaded rules

---

lib/datadog/core/configuration/option.rb
lib/datadog/core/configuration/option_definition.rb
lib/datadog/core/configuration/settings.rb
lib/datadog/tracing/configuration/settings.rb
lib/datadog/tracing/contrib/action_pack/configuration/settings.rb
lib/datadog/tracing/contrib/rails/configuration/settings.rb
lib/datadog/tracing/contrib/rake/configuration/settings.rb
lib/datadog/tracing/distributed/propagation.rb
sig/datadog/core/configuration/option_definition.rbs
spec/datadog/core/configuration/option_definition_spec.rb
spec/datadog/core/configuration/option_spec.rb

Rename the configuration `on_set` to `after_set` to better reflect the nature of it. It is a callback executed after the value has been set. 

rename core configuration option on_set to after_set

---

Rakefile

When `bundle exec rake -T test`, the information is missing because the rake task does not have a description. So I added a description with example to help people understand how to invoke the task. 
```
dd-trace-rb tonycthsu/add-test-task-description % bundle exec rake -T test
rake spec:minitest              # Run RSpec code examples
rake test[rake_task,task_args]  # Run test with its coresponding dependencies, example: `bundle exec rake test[spec:redis]`
```

Add description for test task

---

.github/workflows/system-tests.yml

Rename the system test GH action to a single word to test if we can use this action in our branch protection. Currently, we can select individual jobs, but not the entire action.

rename system test action to a single word

---

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c
ext/ddtrace_profiling_native_extension/collectors_thread_context.c
lib/datadog/profiling/collectors/cpu_and_wall_time_worker.rb
lib/datadog/profiling/component.rb
sig/datadog/profiling/collectors/cpu_and_wall_time_worker.rbs
spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
spec/datadog/profiling/component_spec.rb

In #2657 we added support for the `Collectors::ThreadContext` to sample a given object allocation.
But until now, triggering these kinds of allocations was only done in our test suite.
This PR adds the missing part: actually sampling objects as Ruby allocates them.
In the `Collectors::CpuAndWallTimeWorker`, we already had a `TracePoint` that is called on every new object allocation (`RUBY_INTERNAL_EVENT_NEWOBJ`), but we were only using it to count allocations.
This PR changes the `TracePoint` code to actually call into the `Collectors::ThreadContext` and thus allow allocation sampling to happen.
(Also included is a crash fix + another tiny tweak. I suggest reviewing commit-by-commit as it makes more sense!)
This PR is another step towards the …

[PROF-7307] Wire up allocation sampling into `CpuAndWallTimeWorker`

---

Steepfile
lib/datadog/core/environment/execution.rb
sig/datadog/core/environment/execution.rbs
spec/datadog/core/environment/execution_spec.rb
vendor/rbs/webmock/0/webmock.rbs

It has been reported by the community that `ddtrace` is breaking test suite with `WebMock`, since some components are sending http request in the background with `net/http` .
Hence this PR make an effort the detect `WebMock` to provide a better default value for `ddtrace` telemetry and remote configuration. 
`WebMock` does not offer an public API such as `WebMock.enabled?` to check the status. When `WebMock.enable!`, it iterates through http adapters to enable them. The net/http  adapter implements enablement by swapping the reference for `Net::HTTP`

Detect WebMock to disable telemetry and remote configuration 

---

.github/workflows/system-tests.yml

Working on setting branch protection to avoid having broken system tests. My previous attempt did not work https://github.com/DataDog/dd-trace-rb/pull/3110
Having a dummy job works I believe it might be a good solution. We do not have to select all the system test jobs, but rather just this dummy job check that only is successful if the `test` is successful. the `test` would run all the scenarios.

Use dummy job to know when all the system test are successful 

---

ext/ddtrace_profiling_native_extension/collectors_thread_context.c
spec/datadog/profiling/collectors/thread_context_spec.rb

This PR tweaks the logic that decides if the profiler should collect the resource from an active trace to also consider the span type `proxy`, which is used when the `request_queuing` feature is in use in the rack instrumentation.
Without this fix, the endpoint profiling feature (e.g. allowing customers to drill into their profiles by endpoint) does not work in combination with `request_queuing`, and the feature is hidden in the profiler UX.
Make sure that customers that enable `request_queuing` are still able to look at their profiles per-endpoint.
N/A
The change includes test coverage. If you're interested in testing it out with a real http app, you can do so by enabling the `request_queuing` …

Fix missing endpoint profiling when request_queuing is enabled in rack instrumentation

---

Rakefile

This mistake is introduce from https://github.com/DataDog/dd-trace-rb/pull/3111
Which JRuby runner only checks for `.include?('✅ jruby')` , it should check for ruby version as well
This could be reproduce with `bundle exec rake test:cucumber` in a Jruby container

Fix test runner for jruby

---

lib-injection/Dockerfile

Change the base library injection image from `busybox` to `alpine` to make the image more compatible with other software environments.
`libdl.so.2: cannot open shared object file: No such file or directory` errors have been reported in customer environments which prevents application containers from starting up when using [library injection](https://docs.datadoghq.com/tracing/trace_collection/library_injection_local/?tab=kubernetes#step-3---tag-your-pods-with-unified-service-tags). Likely this is due to some other software such as instrumentation or security that modifies the command run in the container. The modified command fails as the `libdl.so.2` shared library isn't present in the `busybox`-based image.
The `busybox` image [lacks many …

Use alpine base for lib-injection image

---

.github/workflows/system-tests.yml
.github/workflows/test-macos.yaml

Previously it was only running for Datadog employees. So PRs from the community were not running those GH actions.

Run the MacOS and System Test actions for every pull request.

---

benchmarks/profiler_sample_loop.rb
lib/datadog/profiling.rb
lib/datadog/profiling/component.rb
lib/datadog/profiling/profiler.rb
sig/datadog/profiling/profiler.rbs
spec/datadog/profiling/component_spec.rb
spec/datadog/profiling/profiler_spec.rb

This PR simplifies the `Profiler` class to receive only a single `worker`, instead of a `collectors` array.
The `collectors` array was added a long time ago when we expected that we may add more `collectors` in the future.
We never ended up making use of this extra flexibility, so I've decided to simplify the code to remove this feature.
N/A
This change includes code coverage. Since this is the core of starting the profiler, it's pretty visible when it doesn't work ;)

Refactor: Simplify `Profiler` instance

---

.github/workflows/semgrep.yml

Fixes the excluded rule name.
I miscopied a truncated rule name from a shell `semgrep` run: it was missing the lats part.
Master Semgrep CI action is correctly failing because of this: https://github.com/DataDog/dd-trace-rb/actions/runs/6177220252

Action:Fix semgrep truncated rule name

---

lib/datadog/tracing/contrib/grpc/configuration/settings.rb
lib/datadog/tracing/contrib/grpc/datadog_interceptor.rb
lib/datadog/tracing/contrib/grpc/datadog_interceptor/client.rb
lib/datadog/tracing/contrib/grpc/datadog_interceptor/server.rb
spec/datadog/tracing/contrib/grpc/datadog_interceptor/client_spec.rb
spec/datadog/tracing/contrib/grpc/datadog_interceptor/server_spec.rb
spec/datadog/tracing/contrib/grpc/datadog_interceptor/shared_examples.rb

In https://github.com/DataDog/dd-trace-rb/pull/1583, the option of passing a custom error_handler to gRPC interceptors was added. This is useful for e.g. selectively marking certain gRPC status codes as an APM error.
However, the change was implemented only for gRPC **server** interceptors. This patch:
* updates `DatadogInterceptor::Client` to pass the `error_handler` into the `Tracing.trace` call
* updates `DatadogInterceptor::Base` to read the error_handler from the interceptor itself (i.e. what's passed [here](https://github.com/DataDog/dd-trace-rb/blob/22d20fbd94a490d6a260b9f92c824b5cfd7122d4/lib/datadog/tracing/contrib/grpc/datadog_interceptor.rb#L20)) instead of the default/global configuration. It's not clear why this wasn't needed for the Server …

fix(grpc): allow custom error_handler for client interceptor

---

integration/apps/rails-five/Gemfile

Fixes a flaky `rails-five` dependency version issue affecting [build_and_test_integration-2.3](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/11850/workflows/1be5e47a-aea2-4d81-9806-a32fbf9fc389/jobs/445272) and 
[build_and_test_integration-2.4](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/11850/workflows/1be5e47a-aea2-4d81-9806-a32fbf9fc389/jobs/445285):
```
app_1                 | NameError: uninitialized constant Nokogiri::HTML4
app_1                 | /usr/local/bundle/gems/loofah-2.21.1/lib/loofah/html4/document.rb:10:in `<module:HTML4>'
```
This happens because there were issues between specific `loofah` and `nokogiri` (a `loofah` dependency)
around `loofah` 2.20. We can't upgrade both `loofah` and `nokogiri` to their latest …

Test:Fix flaky loofah+nokogiri version mismatching

---

tasks/appsec.rake

Add simple task to update rules to a specific version
It's cumbersome and error prone to do it manually.
Usage is:
rake appsec:ruleset:update[x.y.z]
Possible future improvements:
- without argument, download the last released version (not `master`)
- run the above automatically in CI and check if there's a git diff and be warned that there is
- automatically open a PR with everything ready for review
Try the above!

Add simple task to update rules to a specific version

---

.github/CODEOWNERS

Adds Documentation team as reviewers to single sourced docs files.
This is part of our process for all docs single sourced from other repos.
Once we work on restructuring the docs more, we should put the public docs, currently GettingStarted and Compatibility, into a new folder point the CODEOWNERS to that whole folder. We'll have to reformat a few links before we do this though. 

Add Docs team as code owners for single sourced docs 

---

Steepfile
lib/datadog/core/environment/execution.rb
sig/datadog/core/environment/execution.rbs
spec/datadog/core/environment/execution_spec.rb
vendor/rbs/cucumber/0/cucumber.rbs

Ensures [`cucumber`](https://github.com/cucumber/cucumber-ruby) test execution is considered a development environment for the host application.
We do not want production-tailored features to pollute developers' test environments.
We already detect RSpec and Minitest test runs and skip some of our production features. This PR adds Cucumber to the detection list.
There's an integration test in this PR.

Detect Cucumber as a development environment

---

lib/datadog/core/workers/polling.rb
lib/datadog/tracing/component.rb
lib/datadog/tracing/configuration/settings.rb
lib/datadog/tracing/workers.rb
lib/datadog/tracing/workers/trace_writer.rb
lib/datadog/tracing/writer.rb
sig/datadog/tracing/component.rbs
spec/datadog/core/configuration/components_spec.rb
spec/datadog/core/workers/polling_spec.rb
spec/datadog/tracing/configuration/settings_spec.rb
spec/datadog/tracing/workers/trace_writer_spec.rb
spec/datadog/tracing/workers_integration_spec.rb
spec/datadog/tracing/workers_spec.rb
spec/datadog/tracing/writer_spec.rb

This PR extends Tracer's configurability:
1. `settings.tracing.test_mode.async` configuration is added. When `async` is set to true, Datadog::Tracer is created with async writer (currently `Datadog::Tracing::Writer`) in test mode
2. SHUTDOWN_TIMEOUT (determines how long to wait until worker's thread is stopped on shutdown) can be now configured via writer_options (supported both by `Datadog::Tracing::Writer` and `Datadog::Tracing::Workers::TraceWriter`)
Sometimes SyncWriter can cause performance issues in test mode for several reasons:
1. It doesn't support batching and sends traces one by one
2. It doesn't use additional threads and blocks on IO operation when using HTTP connection
An example when this behaviour is problematic is CI visibility …

[Tracer] Introduce async configuration for test mode to use standard writer when needed

---

spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb

This PR adds more logging to a flaky test reported by @marcotc ( https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/11866/workflows/08660eeb-0746-4675-87fd-33d473a3f479/jobs/445903 ).
I'm not sure what may have caused the test to fail, so I've added a bunch of extra information so that we can look into the issue the next time it shows up.
Hunt down every last flaky test!
If you see any profiling flaky tests, always let me know! I'm aiming to have ZERO flaky tests, so anything you find is new to me!
Change only affects tests :)

Add more logging to profiling flaky test

---

lib/datadog/appsec/assets.rb
lib/datadog/appsec/assets/waf_rules/processors.json
lib/datadog/appsec/assets/waf_rules/scanners.json
lib/datadog/appsec/processor/rule_merger.rb
sig/datadog/appsec/assets.rbs
sig/datadog/appsec/processor/rule_merger.rbs
spec/datadog/appsec/processor/rule_merger_spec.rb
spec/datadog/appsec/processor_spec.rb
spec/datadog/appsec/remote_spec.rb

Add the default scanners to the WAF. The scanners are used to tag extracted schema information. 

[APPSEC-10967] add defaults scanners to the WAF ruleset

---

lib/datadog/core/telemetry/collector.rb
lib/datadog/opentracer.rb
spec/datadog/core/telemetry/collector_spec.rb

Adds telemetry to measure usage of the OpenTracing integration.
[OpenTracing has been superseded by OpenTelemetry.](https://www.cncf.io/blog/2022/01/31/cncf-archives-the-opentracing-project/)
We want to measure its usage going forward to make decisions regarding how support for OpenTracing.

Add telemetry for opentracing

---

ext/ddtrace_profiling_native_extension/collectors_stack.c
ext/ddtrace_profiling_native_extension/collectors_stack.h
ext/ddtrace_profiling_native_extension/collectors_thread_context.c
ext/ddtrace_profiling_native_extension/extconf.rb
ext/ddtrace_profiling_native_extension/stack_recorder.c
ext/ddtrace_profiling_native_extension/stack_recorder.h
spec/datadog/profiling/collectors/stack_spec.rb
spec/datadog/profiling/collectors/thread_context_spec.rb
spec/datadog/profiling/stack_recorder_spec.rb

This PR adds a new feature to the Ruby profiler: thread state categorization.
When taking a cpu/wall-time sample, the profiler will peek at the top of the stack, and then add a `state` label to the sample that categorizes what the thread was doing.
By categorizing what threads are doing when they're not on the cpu, we can synthesize nice events for timeline, e.g. paint a big rectangle when a thread was blocked on some mutex, or was waiting for the network.
Because we're matching only on "name of method at the top of the stack" + "is this method a native method" this approach is approximate, and we hope to replace it with a more accurate mechanism soon.
For now, we will only expose this information as part of the timeline …

[PROF-7440] Add approximate thread state categorization for timeline

---

.gitlab/benchmarks.yml

Reenable nightly deploy to RelEnv without changing logic of BP pipelines.
Bug fix for CI/CD pipeline.
The newest commit should be deployed to RelEnv nightly. BP should not run nightly.

Disable schedule rule for BP and reenable nightly deploy to RelEnv

---

lib/datadog/core/configuration/settings.rb
spec/datadog/core/configuration/settings_spec.rb

This PR enables the Profiler's `allocation_counting_enabled` feature by default for some Ruby 3 versions.
(This feature depends on the profiler itself being enabled).
TL;DR we were already enabling this feature by default on Ruby 2, but did not do it on Ruby 3 because of a VM bug
( https://bugs.ruby-lang.org/issues/18464 ).
Now that this VM bug has been fixed for some Ruby versions (3.1.4, 3.2.3, 3.3.0), we can enable it by default again.
The allocation counting feature is required to enable other features in the future (including allocation profiling) and thus we want to allow as many customers as possible to have it.
There's a second annoying VM bug that can also break `allocation_counting_enabled` …

[PROF-7307] Enable allocation counting feature by default for some Ruby 3 versions

---

spec/datadog/profiling/collectors/stack_spec.rb

The spec
> Datadog::Profiling::Collectors::Stack in a background thread
> approximate thread state categorization based on current stack when
> sampling a thread blocked on Thread#join is expected
> to include {:state => "blocked"}
proved to be flaky in
https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/12189/workflows/78612cd5-3173-4faf-a034-5cb172ed4549/jobs/458502
```
Failure/Error: expect(sample_and_decode(background_thread, :labels)).to include(state: 'blocked')
expected {:label_a => "value_a", :label_b => "value_b", :state => "unknown"} to include {:state => "blocked"}
Diff:
@@ -1,3 +1,5 @@
-:state => "blocked",
+:label_a => "value_a",
+:label_b => "value_b",
+:state => "unknown",
```
I'm not entirely sure what happened here -- if the thread we …

Add more logging to profiling flaky to thread state categorization spec

---

ext/ddtrace_profiling_native_extension/collectors_thread_context.c
spec/datadog/profiling/collectors/helper/lib/logging/diagnostic_context.rb
spec/datadog/profiling/collectors/thread_context_spec.rb

In #2950, we added a fallback for nameless threads: we use their "invoke location", as shown by Ruby in the default `Thread#to_s`. The invoke location is the file and line of the first method of the thread.
This fallback has an issue: when thread creation is monkey patched. One common source of this is the `logging` gem. When the `logging` gem monkey patches thread creation, every thread will have the same invoke location, which will point to the `logging` gem.
This made the fallback invoke location worse than not having anything.
To work around this, this PR changes the profiler so that when the invoke location belongs to the `logging` gem, it's not used, and a simpler `(Unnamed thread)` placeholder is used instead.
This issue came up when …

[PROF-7440] Add workaround for incorrect invoke location when logging gem is in use

---

lib/datadog/core/configuration/settings.rb

This PR adds a reference to https://bugs.ruby-lang.org/issues/19482 / https://github.com/ruby/ruby/pull/7464 to the reasons why `allocation_counting_enabled` should not be enabled on Ruby 3.2.0 to 3.2.2.
No code needs to be changed since we were already excluding those Ruby versions due to a different bug.
I like having this in the code as it may be relevant in the future (e.g. if the issue reappears).
N/A
No code is changed!

Profiling: Add note about Ruby 3.2 bug

---

lib/datadog/appsec/processor.rb
sig/datadog/appsec/processor.rbs
spec/datadog/appsec/processor_spec.rb

We remove empty and nil WAF Addresses before sending it to the WAF to be processed.

skip passing waf addresses when the value is empty

---

Gemfile
Steepfile
sig/datadog/appsec/processor/rule_merger.rbs

This PR upgrades the steep typechecker to the latest version available, 1.5.3.
It also disables type-checking one of the appsec files that started failing typechecking with this version.
Use latest version of typechecker.
~Here's the full error message for the failing appsec file:~
The issue with the ASM file has been fix with https://github.com/DataDog/dd-trace-rb/pull/3198/commits/7f147ecc2736a14b40b31f00675387e42782f8a8
Observe that typecheck still passes in CI.

Upgrade steep typechecker to latest version 1.5.3

---

.github/workflows/add-milestone-to-pull-requests.yml

This PR reduces the permission of the `add-milestone-to-pull-requests` GitHub Action to the minimum possible.
This is specially important on GitHub Actions that use the `pull_request_target` trigger, because it can run on pull requests by external contributors (which is what we want for this tagger action). More details about the dangers of `pull_request_target` here: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
Despite these concerns, `pull_request_target` is the trigger we want because we do want external pull requests to trigger this Action and have permission to edit the milestone of a pull request (a write permission).
The only other action using, the `pull-request-labeler`, already has minimum permissions declared, thanks to well-documented default …

Reduce permission for milestone GitHub Action

---

.github/workflows/create-next-milestone.yml

Similar to #3193, this PR reduces the permission to the `create-next-milestone` GitHub Action.
This action does not carry the same concern as #3193 because it does not execute based on external pull requests, but this is a step towards changing our default GitHub Actions token to read only.

Reduce permissions to Action for creating next milestone

---

lib/ddtrace/version.rb
spec/datadog/profiling/tag_builder_spec.rb

Based on the discussions from the team, we agree to use the master branch as the new tip for all the work that is going to land for 2.0.0 🎉 
This PR just changes the version to `2.0.0.aplha1`

update version to 2.0.0.aplha1 on master

---

.gitlab/benchmarks.yml
lib/datadog/appsec/configuration/settings.rb
lib/datadog/appsec/contrib/rack/gateway/response.rb
lib/datadog/appsec/contrib/rack/reactive/response.rb
lib/datadog/appsec/contrib/rack/request_middleware.rb
spec/datadog/appsec/configuration/settings_spec.rb
spec/datadog/appsec/contrib/rack/gateway/response_spec.rb
spec/datadog/appsec/contrib/rack/reactive/response_spec.rb

Parsed the response body and passed it to the waf as `server.response.body`.
We only parse bodies that are either an `Array` or a `Rack::BodyProxy`. Since we might not be the last middleware in the customer application, we can not consume the response body directly by calling `each`. To circumvent that, we make a copy of the body. 
Parsing the response body could lead to performance implications for our customers. Since we have yet to learn how this would impact our customers, I added a configuration entry for them to skip the response body parsing altogether. 
This documentation would remain undocumented, and we would only mention it to customers if they experience any performance degradation. …

[APPSEC-10967] ASM parse response body 

---

lib/datadog/profiling/collectors/cpu_and_wall_time_worker.rb
lib/datadog/profiling/profiler.rb
lib/datadog/profiling/scheduler.rb
sig/datadog/profiling/collectors/cpu_and_wall_time_worker.rbs
sig/datadog/profiling/profiler.rbs
sig/datadog/profiling/scheduler.rbs
spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
spec/datadog/profiling/profiler_spec.rb
spec/datadog/profiling/scheduler_spec.rb

This PR changes the profiler `Collectors::CpuAndWallTimeWorker` and `Scheduler` components to signal the top `Profiler` instance when they failed, so the `Profiler` can stop the other component as well.
While never reported by a customer, it ocurred to me that right now if one of the component fails, the other will keep working in a weird state.
Of particular concern, if the scheduler failed, the `StackRecorder` would trigger a memory leak: it would start accumulating samples and never flush them.
This PR changes the profiler so that if one component stops with a failure, the other will do so as well.
I'm not especially happy with how this change turned out.
1. The error handling in the scheduler somewhat duplicates similar …

Shut down profiler if any components failed

---

lib/datadog/core/remote/worker.rb
spec/datadog/core/remote/worker_spec.rb

This PR sets the name of the thread started by the `Datadog::Core::Remote::Worker` class (to be the name of the class).
This follows the same pattern we use for other dd-trace-rb internal threads.
The profiler shows thread names in multiple places, and nameless threads make it harder to see the data in several cases, so as much as possible we want to avoid them.
One particular case is that for the timeline feature, we collapse all dd-trace-rb threads by default, but that collapsing feature relies on thread names, and so the remote worker thread was not being properly collapsed (which is how I spotted it).
I've chosen to still include the Ruby 2.2/2.1 support because I plan to backport this to the 1.x branch.
**How to test the …

Name `Datadog::Core::Remote::Worker` thread

---

.circleci/config.yml

Disable integration test for Ruby 3.3. that cannot install its gemfiles until https://github.com/protocolbuffers/protobuf/issues/14509 is addressed.

Disable Ruby 3.3 integration due to protobuf compilation error

---

.github/workflows/update-gemfiles.yml

After merging #3149, the job ran on the `master` merge commit.
This was not intended, and happened because the GH Action was able to find a PR associated with the commit, making it think that `master` is a branch the user is currently working on.
This PR ensures that the Action does not run for commits that belong to a PR that is not longer active (e.g. merged or closed).

Action:Prevent Update Gemfiles running on merge target

---

shell.nix

- Update nixpkgs to use today's latest 23.05
- Update compilers (clang, gcc)
Keeping things up to date
Nope
- If not done already, install nixpkgs (Linux, macOS):
```
$ sh <(curl -L https://nixos.org/nix/install) --daemon
```
This quickly installs basic nix commands out of the way in `/nix` and does not conflict with anything (incl. Homebrew)
- Enter Nix shell:
```
$ cd /path/to/dd-trace/clone
$ nix-shell
```
- Try the usual Ruby stuff:
```
nix-shell$ bundle install
nix-shell$ bundle exec rake test:main
```

Update Nix shell to use today's latest 23.05 + updated compilers

---

.gitlab/benchmarks.yml
lib/datadog/appsec/configuration/settings.rb
spec/datadog/appsec/configuration/settings_spec.rb
spec/datadog/appsec/contrib/rack/gateway/response_spec.rb
spec/datadog/appsec/contrib/rack/reactive/response_spec.rb

After discussing with the team, we decided to remove the `EXPERIMENTAL` qualifier for the ASM api security response body parsing configuration 

rename ENV var for ASM API Security response body parsing and enable by default

---

lib/datadog/tracing/diagnostics/environment_logger.rb

`Datadog::Tracing::Diagnostics::EnvironmentLogger::EnvironmentCollector.instrumented_integrations` check if tracing config responds to `instrumented_integrations` method and returns an empty hash otherwise.
When using Tracer manually without tracing integrations in CI mode, the following error is getting spammed to logs:
```
WARN -- ddtrace: [ddtrace] Failed to collect tracing environment information: undefined method `instrumented_integrations' for #<#Class:0x00000001034942e8:0x0000000103798a48 @options={:enabled=>#<Datadog::Core::Configuration::Option:0x000000010388b4a0 @definition=#<Datadog::Core::Configuration::OptionDefinition:0x00000001034924e8 @default=true, @default_proc=nil, @env="DD_TRACE_ENABLED", @deprecated_env=nil, @env_parser=nil, …
```

[CIVIS-7720] instrumented_integrations returns empty hash if tracing config is not extended by Tracing::Contrib::Extensions

---

lib/datadog/core/remote/worker.rb
spec/datadog/core/remote/worker_spec.rb

This is a backport of https://github.com/DataDog/dd-trace-rb/pull/3207 to the 1.x-stable branch.
I merely rebased the commits on top of the other branch, with no other changes.

Backport #3207 to 1.x-stable: Name `Datadog::Core::Remote::Worker` thread

---

.github/workflows/add-milestone-to-pull-requests.yml

This PR fixes the permission for the `.github/workflows/add-milestone-to-pull-requests.yml` workflow, which attaches milestones to PRs.
I think there's something weird going on here because the octokit calls from the workflow returned 200, but did not modify the milestone AND the listed permission required for updating a pull request do not seem to coincide with reality: I think it's a GH bug.
It also upgrades the GitHub actions used in the workflow as it was using a very very old version, which used node12 and GitHub has been complaining that node12 is deprecated:
```
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/github-script@0.9.0. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-in …
```

Action:Fix PR milestone action

---

lib/datadog/tracing/diagnostics/environment_logger.rb

Backport changes from https://github.com/DataDog/dd-trace-rb/pull/3209
Release this fix in the next 1.x release

return empty hash if tracing config is not extended by Tracing::Contrib::Extensions

---

.circleci/config.yml

Backports #3211: Disable integration test for Ruby 3.3. that cannot install its gemfiles until https://github.com/protocolbuffers/protobuf/issues/14509 is addressed.
CI is breaking for 1.x-stable

Disable Ruby 3.3 integration due to protobuf compilation error (#3211)

---

lib/datadog/profiling/collectors/cpu_and_wall_time_worker.rb
lib/datadog/profiling/profiler.rb
lib/datadog/profiling/scheduler.rb
sig/datadog/profiling/collectors/cpu_and_wall_time_worker.rbs
sig/datadog/profiling/profiler.rbs
sig/datadog/profiling/scheduler.rbs
spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
spec/datadog/profiling/profiler_spec.rb
spec/datadog/profiling/scheduler_spec.rb

This is a backport of https://github.com/DataDog/dd-trace-rb/pull/3197 to the 1.x-stable branch.
I merely rebased the commits on top of the other branch, with no other changes.

Backport #3197 to 1.x-stable: Shut down profiler if any components failed

---

spec/datadog/integration_spec.rb
spec/spec_helper.rb

~~Instead of checking number of threads before and after tracer is started and shutdown, we grab the object IDs for the threads the tracer creates and check that they are no longer present after the tracer shuts down. This test has been flaky for some time.~~
Add back `Timeout.ensure_timeout_thread_created if Timeout.respond_to?(:ensure_timeout_thread_created)` to spec_helper.rb that was removed in https://github.com/DataDog/dd-trace-rb/pull/2991. The Timeout thread can lead to flaky tests where we are checking what threads are present before and after actions as it could be created during a test. This ensures the thread is always there before a test starts for consistent observation.
Also, improve the existing test for tracing thread shutdown by checking the …

Attempt to remove flaky test for checking that tracer threads are correctly shutdown

---

.github/workflows/system-tests.yml
lib/datadog/appsec/contrib/rack/gateway/response.rb
spec/datadog/appsec/contrib/rack/gateway/response_spec.rb

Fix regression introduce in https://github.com/DataDog/dd-trace-rb/pull/3153/commits/b1952740df7b27ffcbb1d4547caf03cab92c4546
Make sure that the function that checks if the content-type header
is valid for parsing the response body
and supports when there is no content-type header information.

Make sure function that checks content-type header value accepts nil content-type header value

---

lib/datadog/tracing/contrib/concurrent_ruby/context_composite_executor_service.rb
lib/datadog/tracing/contrib/concurrent_ruby/future_patch.rb
lib/datadog/tracing/contrib/concurrent_ruby/integration.rb
lib/datadog/tracing/contrib/concurrent_ruby/patcher.rb
lib/datadog/tracing/contrib/concurrent_ruby/promises_future_patch.rb
sig/datadog/tracing/contrib/concurrent_ruby/promises_future_patch.rbs
spec/datadog/tracing/contrib/concurrent_ruby/integration_spec.rb
spec/datadog/tracing/contrib/concurrent_ruby/integration_test_spec.rb

Argument passing is preserved through the composited executor.
`Concurrent::Future` has been moved to a prepend style to resolve an infinite call loop situation.

Propagate trace through Concurrent::Promises.future

---

lib/ddtrace/version.rb
spec/datadog/profiling/tag_builder_spec.rb

Reverts DataDog/dd-trace-rb#3201
Let's go back to master being 1.x until we have a more concrete timeline for the release of 2.x changes.
We've seen very frequent backporting (pretty much all changes so far) because current development is still intended for 1.x.
Until the first 2.x prerelease has a concrete timeline, we'll keep master as 1.x.

Revert "update version to 2.0.0.alpha1 on master"

---

docs/GettingStarted.md
lib/datadog/tracing/contrib/redis/configuration/settings.rb
lib/datadog/tracing/contrib/redis/instrumentation.rb
lib/datadog/tracing/contrib/redis/tags.rb
lib/datadog/tracing/contrib/redis/trace_middleware.rb
spec/datadog/tracing/contrib/rails/redis_cache_spec.rb
spec/datadog/tracing/contrib/redis/instrumentation_spec.rb
spec/datadog/tracing/contrib/redis/redis_spec.rb
spec/datadog/tracing/contrib/redis/shared_examples.rb

This PR changes the value of `span.resource` for the Redis tracing instrumentation to only capture the [command name](https://redis.io/commands/) by default (e.g. `GET`, `BLPOP`).
It's possible to revert back to the previous default, capturing command arguments, with the environment variable `DD_REDIS_COMMAND_ARGS` or option `command_args`.
Redis command arguments can contain sensitive information and thus must not be captured by default.

Redis:Omit command arguments from span.resource by default

---

lib/datadog/appsec/contrib/rack/gateway/request.rb
spec/datadog/appsec/contrib/rack/gateway/request_spec.rb
spec/datadog/appsec/contrib/rack/reactive/request_spec.rb
spec/datadog/appsec/event_spec.rb

On ASM, append HTTP request information as part of the top-level span. 
The code that collects the request header assumes we are interested in all header requests starting with `HTTP_`.  Those headers are set by the client following the [RFC3875 section 4.1.18](https://tools.ietf.org/html/rfc3875#section-4.1.18) 
Unfortunately, that is not the case for specific headers that are specified by the server. For example, `Content-Type` and `Content-Length` are not prefixed with `HTTP_`  
The variables are called CGI server variables. [Here is the list](https://www6.uniovi.es/~antonio/ncsa_httpd/cgi/env.html)
This PR appends the content type and content length information and improves our specs.
**For …

ASM make sure to append content type and length information

---

lib-injection/host_inject.rb

Variable `failure_prefix` is obsolete and causing error when handling exception. 
Remove an obsolete variable from host inject script .

Fix host injection error handling 

---

lib/datadog/tracing/contrib/concurrent_ruby/context_composite_executor_service.rb
spec/datadog/tracing/contrib/concurrent_ruby/integration_test_spec.rb

Concurrent ruby propagation breaks with `NoMethodError` when there is no `active_trace` to propagates. 
Fix with conditionals.

Fix concurrent ruby future propagation without `active_trace`

---

lib/datadog/core/configuration/settings.rb

Fixes an incorrect comment; the bug being discussed is going to be fixed in the upcoming Ruby 3.2.3 release; not on 3.2.2.
Fix incorrect information.
N/A
N/A

Minor: Fix incorrect comment

---

.github/PULL_REQUEST_TEMPLATE.md

This PR ensures that developers are prompted with describing how 2.0 changes will affect users, and how users can migrate their applications successfully to 2.0.

Update PULL_REQUEST_TEMPLATE with 2.0 release notes section

---

.gitlab-ci.yml
.gitlab/Dockerfile-2.7.8
.gitlab/Dockerfile-3.0.6
.gitlab/Dockerfile-3.1.4
.gitlab/Dockerfile-3.2.2
lib-injection/README.md

This PR changes our Gitlab pipeline to create jobs for building lib injection package for ARM64 architecture. 
The steps involves: 
1. Rebuilt our custom ruby image with ARM64 and promote them
2. Create new Gitlab job to run the existing flow with ARM64 machine and image

Support lib injection for ARM64 acrhitecture

---

lib/datadog/opentelemetry/sdk/span_processor.rb
lib/datadog/opentelemetry/sdk/trace/span.rb
spec/datadog/opentelemetry_spec.rb

This PR adds support for using reserved OpenTelemetry span attributes to override Datadog Span fields.
Normally, OpenTelemetry span attributes are simply converted to Datadog Span tags, but some attributes should change other properties of the Datadog Span:
* "operation.name" => dd_span.name
* "service.name" => dd_span.service
* "resource.name" => dd_span.resource
* "span.type" => dd_span.type
* "analytics.event" => dd_span.set_metric("_dd1.sr.eausr")
There are unit tests and system-tests for this change.

OTel:Support reserved attribute overrides

---

lib/datadog/tracing/configuration/settings.rb
spec/datadog/tracing/configuration/settings_spec.rb

Add back b3 extraction which was removed from https://github.com/DataDog/dd-trace-rb/pull/3248
This would prevent breaking changes for user application while upgrading.

Tracing: Add b3 for default extraction

---

lib/datadog/profiling/component.rb
sig/datadog/profiling/component.rbs
spec/datadog/profiling/component_spec.rb

This PR is the last step to fully fixing the issue reported in #2976.
In that issue, we discovered that he passenger web server had an incompatibility with the profiler. At the time, we added code to detect when passenger was in use and apply the "no signals" workaround to avoid this issue out-of-the-box.
Upstream passenger has since accepted our PR to fix the issue, allowing us in this PR to change our detection logic to:
a) Not enable the "no signals" workaround on passenger 6.0.19+
b) Provide an actionable error message to customers on older passenger versions to tell them that the best option is to upgrade
Improve the out-of-the-box experience of profiler users that use the passenger web server.
N/A
**How to test the …

Allow profiler to run without "no signals" workaround on passenger 6.0.19+

---

lib/datadog/core/configuration.rb
lib/datadog/core/remote/worker.rb
lib/datadog/core/workers/async.rb
lib/datadog/profiling/collectors/cpu_and_wall_time_worker.rb
lib/datadog/profiling/collectors/idle_sampling_helper.rb
lib/datadog/tracing/workers.rb
spec/datadog/core/configuration_spec.rb
spec/datadog/core/remote/worker_spec.rb
spec/datadog/core/workers/async_spec.rb
spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
spec/datadog/profiling/collectors/idle_sampling_helper_spec.rb
spec/datadog/tracing/workers_spec.rb

This PR applies to all relevant ddtrace threads a pattern pioneered by rails: set the `:fork_safe` thread variable to indicate that it's OK if ddtrace threads are started before a Ruby app calls fork.
This PR fixes the issue reported in #3203. The puma webserver in clustering mode has a check where it will warn when it detects that threads were started before the webserver has fork'd the child processes, see:
https://github.com/puma/puma/blob/32e011ab9e029c757823efb068358ed255fb7ef4/lib/puma/cluster.rb#L353-L359
This is not a problem for ddtrace (as discussed in #3203), but the warning is annoying.
While looking into the issue again today, I spotted that actually there's a way to tell puma that a thread is fine and is it's not a problem if it's …

Mark ddtrace threads as fork-safe

---

ext/ddtrace_profiling_native_extension/clock_id_from_pthread.c
ext/ddtrace_profiling_native_extension/extconf.rb
ext/ddtrace_profiling_native_extension/private_vm_api_access.c
ext/ddtrace_profiling_native_extension/private_vm_api_access.h
ext/ddtrace_profiling_native_extension/profiling.c

This PR detects when Ruby (>= 3.3) is running with `RUBY_MN_THREADS=1` and disables the profiler.
It also includes fixes to make sure to not crash the Ruby VM when `RUBY_MN_THREADS` is in use. Without this PR, the profiler was crashing when this setting is enabled.
Ruby 3.3 introduces the M:N thread scheduler (see
<https://www.ruby-lang.org/en/news/2023/11/12/ruby-3-3-0-preview3-released/>).
Think Java's Virtual Threads, but for Ruby.
In short, this means that Ruby threads no longer have a 1:1 mapping to actual kernel threads.
By default, this new mode of working applies only to the non-main Ractor, which means it doesn't impact the profiler since we don't yet support profiling non-main ractors (they are detected and skipped).
But, there's a …

Disable profiler on Ruby 3.3 when running with RUBY_MN_THREADS=1

---

.circleci/config.yml

This reverts commit f9ebce90b92fbb0fec14f0865504610b31b51a04.
In #3211 we disabled our CI integration testing on Ruby 3.3 because one of the dependencies (protobuf) had an incompatibility at the time (see protocolbuffers/protobuf#14509 for details).
Upstream has since fixed the issue, so we're good to go.
N/A
Check that CircleCI is now also running the `build_and_test_integration-3.3` test.

Revert "Disable Ruby 3.3 integration due to protobuf compilation error"

---

ext/ddtrace_profiling_native_extension/collectors_thread_context.c
ext/ddtrace_profiling_native_extension/extconf.rb
ext/ddtrace_profiling_native_extension/private_vm_api_access.c
ext/ddtrace_profiling_native_extension/private_vm_api_access.h
spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb

This PR extends the code that generates a description for an object during allocation to include the specific kind of `T_IMEMO` object.
On Ruby < 3, the `rb_imemo_name` function we're relying on does not exist, so I chose to just not gather this information for legacy Rubies. (It's posssible to still get it, but I didn't want to spend more time).
During discussion of #3282 the question of what a `T_IMEMO` is came up, and since it turns out it can represent different kinds of things in the Ruby VM, I decided to see if there was a way of spelling those out, and it turns out there is.
Is this going to be useful for most customers? Probably not, but even for our internal debugging/learning, it may come in handy, so it was a bit of a "why not" kinda …

Profiling: Include specific kind of VM-internal T_IMEMO object in allocation info

---

lib/datadog/tracing/configuration/settings.rb
spec/datadog/tracing/configuration/settings_spec.rb

This reverts commit a08db1a3fe9c26547150fb507ea7ffc0b3c14f74.
The default distributed tracing propagation extraction style is now `Datadog,tracecontext`.

Revert "Add b3 default extraction"

---

lib/datadog/kit/enable_core_dumps.rb

This PR tweaks the `enable_core_dumps` helper to also print the code dump status (maximum size and output pattern) even when core dumps are already enabled. This will allow us to know where to find the core dump files in such situations.
Simplify diagnostics when using this helper.
N/A
This class already has test coverage. To quickly test it manually, running `load '.../enable_core_dumps.rb'` more than once will trigger the multiple messages.

[NO-TICKET] Minor: Print core dump status info even when already enabled

---

ext/ddtrace_profiling_native_extension/extconf.rb

This PR removes the workaround we add to not use the `-Wunused-parameter` warning on Ruby 3.3.
This means we'll have those warnings when compiling the profiler native extension on that Ruby version.
The issue was that some of the internal Ruby headers in Ruby 3.3 have unused parameters. If we applied the warning before checking these internal headers, the header detection check (`have_header`) would fail not because the headers were missing, but because they have warnings.
(Why do they fail due to warnings? Because by default `have_header` tries to compile a tiny app that includes the header AND tries to compile that app with `-Werror`, turning any warning into an error -- thus making the combination fail)
To fix this issue, we need to enable these warnings after …

[NO-TICKET] Remove unused parameter warning workaround for Ruby 3.3

---

ext/ddtrace_profiling_native_extension/extconf.rb
ext/ddtrace_profiling_native_extension/private_vm_api_access.c

This PR imports the changes from upstream
https://github.com/ruby/ruby/pull/8415 into our copy of `rb_profile_frames`.
I'm not entirely sure if this crash could happen for ddtrace because unlike other Ruby profilers (like stackprof) we are not (yet?) sampling from the signal handler.
Make sure our `rb_profile_frames` matches upstream in terms of validation/safety.
N/A
Good question -- I'll admit I don't quite know how to trigger the issue reported upstream. In any case, the change is quite small, so at most we'll report line 0 in a few cases where we previously weren't.

Fix potential crash by importing upstream `rb_profile_frames` fix

---

lib/datadog/tracing/contrib/pg/instrumentation.rb
spec/datadog/tracing/contrib/pg/patcher_spec.rb

This PR fixes the pg instrumentation to respect the `enable` option from configuration settings. 

Fix disabling pg instrumentation configuration

---

lib/datadog/tracing/configuration/ext.rb
lib/datadog/tracing/configuration/settings.rb
spec/datadog/opentelemetry_spec.rb
spec/datadog/opentracer/rack_propagator_spec.rb
spec/datadog/tracing/configuration/settings_spec.rb
spec/datadog/tracing/contrib/grpc/distributed/propagation_spec.rb
spec/datadog/tracing/contrib/http/distributed/propagation_spec.rb
spec/datadog/tracing/distributed/propagation_spec.rb

The the values for the environment variables `DD_TRACE_PROPAGATION_STYLE`, `DD_TRACE_PROPAGATION_STYLE_INJECT`, and `DD_TRACE_PROPAGATION_STYLE_EXTRACT` are now considered case-insensitive.
The major impact of this change is that, previously, `B3` would configure Tracing with the [B3 Multiple Headers](https://github.com/openzipkin/b3-propagation/tree/7c6e9f14d6627832bd80baa87ac7dabee7be23cf#multiple-headers) propagator. Now `B3` will configure it with the [B3 Single Header](https://github.com/open-telemetry/opentelemetry-specification/blob/62effed618589a0bec416a87e559c0a9d96289bb/specification/configuration/sdk-environment-variables.md?plain=1#L102) propagator.
This change aligns the Ruby tracer with all other Datadog Tracers.
**Additional …

Case-insensitive propagation style configuration

---

.gitlab-ci.yml
.gitlab/Dockerfile-2.7.8
.gitlab/Dockerfile-3.0.6
.gitlab/Dockerfile-3.1.4
.gitlab/Dockerfile-3.2.2
lib-injection/README.md

Reverts DataDog/dd-trace-rb#3272
This PR reverts the revert PR. Other teams from Datadog are prepared to support ARM64.

Revert "Revert "Support lib injection for ARM64 architecture""

---

lib/datadog/tracing/trace_operation.rb
spec/datadog/tracing/integration_spec.rb
spec/datadog/tracing/trace_operation_spec.rb

`Datadog::Tracing.reject!` now only changes the priority sampling, as documented, instead of preventing the trace from reaching the Datadog Agent. Now, rejected traces will correctly count towards [trace metrics](https://docs.datadoghq.com/tracing/metrics/#trace-metrics).
This was always the intended behavior, but was incorrectly implemented.

Ensure traces reach the agent

---

Rakefile
spec/datadog/core/configuration/components_spec.rb
spec/datadog/core/configuration_spec.rb
spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
spec/datadog/profiling/native_extension_spec.rb

* Separate the profiling test suite from main to allow for profiling-specific customizations.
* Tag all tests that use `Ractor.new` with `ractors => true` tag.
* Introduce two spec tasks for profiling:
* `profiling:main` - Run all tests EXCLUDING `ractors` tagged tests.
* `profiling:ractors` - Run all `ractors` tagged tests.
As soon as you execute `Ractor.new`, the VM [transitions to a multi-ractor state](https://github.com/ruby/ruby/blob/b9f2c67106ac8277b0e83a5701a43d016d829131/ractor.c#L1877-L1892). This transition cannot be reversed and will change the behaviour of the VM. For example, [`ObjectSpace::_id2ref` will start to raise errors on unshareable objects](https://github.com/ruby/ruby/blob/b9f2c67106ac8277b0e83a5701a43d016d829131/gc.c#L4746C1 …

[PROF-8667] Split profiling tests into ractor and non-ractor suites.

---

benchmarks/profiler_sample_loop_v2.rb
ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c
ext/ddtrace_profiling_native_extension/collectors_gc_profiling_helper.c
ext/ddtrace_profiling_native_extension/collectors_gc_profiling_helper.h
ext/ddtrace_profiling_native_extension/collectors_stack.c
ext/ddtrace_profiling_native_extension/collectors_stack.h
ext/ddtrace_profiling_native_extension/collectors_thread_context.c
ext/ddtrace_profiling_native_extension/collectors_thread_context.h
ext/ddtrace_profiling_native_extension/helpers.h
ext/ddtrace_profiling_native_extension/stack_recorder.c
ext/ddtrace_profiling_native_extension/stack_recorder.h
lib/datadog/profiling/component.rb
lib/datadog/profiling/stack_recorder.rb
sig/datadog/profiling/component.rbs
sig/datadog/profiling/stack_recorder.rbs
spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
spec/datadog/profiling/collectors/stack_spec.rb
spec/datadog/profiling/collectors/thread_context_spec.rb
spec/datadog/profiling/component_spec.rb
spec/datadog/profiling/spec_helper.rb
spec/datadog/profiling/stack_recorder_spec.rb

This PR redesigns the garbage collection profiling feature to add support for timeline and reduce its overhead.
Here's how it looks in timeline mode:
Here's how it looks in flamegraph mode:
A TL;DR description of how it works now is below:
1. Wiring it up
* Ruby exposes native-level tracepoint events for when it starts/stops doing GC (`RUBY_INTERNAL_EVENT_GC_ENTER`/`RUBY_INTERNAL_EVENT_GC_EXIT`).
* Inside the `CpuAndWallTimeWorker` we create a tracepoint that listens for these events and calls the `on_gc_start` and `on_gc_finish` events on the `ThreadContext` collector.
* The `RUBY_INTERNAL_EVENT_GC_ENTER`/`RUBY_INTERNAL_EVENT_GC_EXIT` tracepoint events are emitted while Ruby is doing GC, which means we can't allocate anything. The code we use is thus built to …

[NO-TICKET] Redesign GC profiling to add timeline support and reduce overhead

---

lib/datadog/core/configuration/settings.rb
spec/datadog/core/configuration/settings_spec.rb

The configuration settings `c.env` and `c.service` now have to be Strings.
There's no reason to be lenient for these two core configuration settings, they can only be meaningful text provided by the user.

Ensure service and env are strings

---

ext/ddtrace_profiling_native_extension/collectors_stack.c
ext/ddtrace_profiling_native_extension/collectors_stack.h
ext/ddtrace_profiling_native_extension/heap_recorder.c
ext/ddtrace_profiling_native_extension/heap_recorder.h
ext/ddtrace_profiling_native_extension/profiling.c
ext/ddtrace_profiling_native_extension/ruby_helpers.c
ext/ddtrace_profiling_native_extension/ruby_helpers.h
ext/ddtrace_profiling_native_extension/stack_recorder.c
lib/datadog/profiling/component.rb
spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
spec/datadog/profiling/component_spec.rb
spec/datadog/profiling/spec_helper.rb
spec/datadog/profiling/stack_recorder_spec.rb

This PR follows https://github.com/DataDog/dd-trace-rb/pull/3281 by actually implementing the heap recorder native module to support tracking the number (not size yet) of live heap objects.
**How does it work?**
The heap recorder essentially plugs into the allocation sampling mechanism and will record the object ids (via `Object::object_id`) and allocation stacktraces of all objects whose allocation we sampled.
At profile serialization time, we flush/update the heap recorder, at which point we make use of [`ObjectSpace::_id2ref`](https://github.com/ruby/ruby/blob/57748ef2a26cbdfe075347c6f7064eb419b4949a/gc.c#L4683) to try to obtain an object reference from our stored ids. This will fail only in these cases:
1. The id isn't valid (shouldn't happen since we record …

[PROF-8667] Heap Profiling - Part 2 - Heap Recorder

---

.circleci/images/primary/Dockerfile-3.3.0
integration/images/ruby/3.3/Dockerfile

This PR updates our dockerfiles so that the Ruby 3.3 stable release (currently 3.3.0) gets used for CI testing, replacing the RC releases.
Make sure dd-trace-rb is working correctly on 3.3 .
The docker image under `.circleci` doesn't get automatically picked up by CI.
I'll make sure to manually run the "Build Ruby" workflow (https://github.com/DataDog/dd-trace-rb/actions/workflows/build-ruby.yml) with the "Push images" option after this PR gets merged.
Validate that the following CI steps still pass:
* Ruby 3.3 integration (will pick up the new Ruby)
* Build Ruby (will be able to build the new Ruby)
credentials of any kind, I've requested a review from …

[NO-TICKET] Use Ruby 3.3 stable for CI testing

---

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c
ext/ddtrace_profiling_native_extension/extconf.rb
spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
spec/datadog/profiling/stack_recorder_spec.rb

This PR includes two changes:
* Skip flaky tests on Ruby 3.3 to unblock CI
* Use rb_postponed_job_preregister/rb_postponed_job_trigger on Ruby 3.3
See individual commit messages for details.
These fixes were needed to bring CI back to green now that it's running with the stable Ruby 3.3.0.
N/A
Existing test coverage should mostly be enough, or in the cases it's not, the feature affected is off by default and still experimental.

[NO-TICKET] Fix Ruby 3.3 CI being broken in master due to profiler

---

ext/ddtrace_profiling_native_extension/collectors_thread_context.c
ext/ddtrace_profiling_native_extension/heap_recorder.c
ext/ddtrace_profiling_native_extension/heap_recorder.h
ext/ddtrace_profiling_native_extension/libdatadog_helpers.h
ext/ddtrace_profiling_native_extension/stack_recorder.c
ext/ddtrace_profiling_native_extension/stack_recorder.h
spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
spec/datadog/profiling/stack_recorder_spec.rb

This PR follows https://github.com/DataDog/dd-trace-rb/pull/3328 by adding `allocation class` and `gc gen age` labels to the heap samples included in the Ruby profiles.
**How does it work?**
For `allocation class`, we simply hold on to the resolved class that was already being computed during the normal allocation sampling path.
For `gc gen age`, we record the GC Generation/Epoch (i.e. `GC.count`) when we saw the allocation happening. Then, when writing the heap samples in a new profile, we calculate the difference between the allocation generation and the current generation and that gives us the age of the recorded object in terms of "how many GCs have run since we saw this object being allocated".
* Understand the type of objects that are being …

[PROF-8667] Heap Profiling - Part 4 - Labels

---

ext/ddtrace_profiling_native_extension/private_vm_api_access.c

This PR imports an upstream fix to `rb_profile_frames` from https://github.com/ruby/ruby/pull/9310 into our own custom copy of that function.
As explained in the comment, the situation being handled does not yet happen with dd-trace-rb in practice since we don't support profiling with MN threads enabled, but since we want to try supporting it at some point, I've gone ahead and imported the fix.
N/A
This is a bit awkward to test, so didn't add any coverage.

[NO-TICKET] Import upstream `rb_profile_frames` fix

---

benchmarks/profiler_sample_loop_v2.rb
ext/ddtrace_profiling_native_extension/heap_recorder.c
ext/ddtrace_profiling_native_extension/heap_recorder.h
ext/ddtrace_profiling_native_extension/ruby_helpers.c
ext/ddtrace_profiling_native_extension/ruby_helpers.h
ext/ddtrace_profiling_native_extension/stack_recorder.c
lib/datadog/profiling/component.rb
lib/datadog/profiling/stack_recorder.rb
sig/datadog/profiling/stack_recorder.rbs
spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
spec/datadog/profiling/spec_helper.rb
spec/datadog/profiling/stack_recorder_spec.rb

This PR follows https://github.com/DataDog/dd-trace-rb/pull/3329 by adding `live-heap-size` values to heap samples. These values give an idea of how much estimated heap memory the weighted samples tracked by `live-heap-samples` are using.
**How does it work?**
On each `heap_recorder_flush`, for all object records associated with objects that were deemed to be still alive, we call `rb_obj_memsize_of` to get an updated value for that object's estimated size in memory.
When writing a heap sample to a profile on serialization, we use the weighted object size (i.e. multiplied by the sampling weight of that object) as the value for the `heap-live-size` profile type for that sample.
Go one step further from understanding the approximate number of objects …

[PROF-8667] Heap Profiling - Part 5 - Size

---

lib/datadog/core/telemetry/collector.rb
lib/datadog/tracing/component.rb
lib/datadog/tracing/configuration/settings.rb
lib/datadog/tracing/diagnostics/environment_logger.rb
sig/datadog/core/telemetry/collector.rbs
spec/datadog/core/configuration/components_spec.rb
spec/datadog/tracing/configuration/settings_spec.rb
spec/datadog/tracing/diagnostics/environment_logger_spec.rb
spec/datadog/tracing/integration_spec.rb

The configuration setting `c.tracing.priority_sampling` has been removed. This option was used to disable priority sampling, which was enabled by default.
To disable priority sampling, you now have to create a custom sampler.
Priority sampling is the preferable way to store a sampling decision at Datadog.
Disabling it also disables features in the Datadog Agent and creates subpart reporting in the [Ingestion Control](https://docs.datadoghq.com/tracing/guide/ingestion_sampling_use_cases/) page.
There are unit and integration tests for all changes.

Remove configuration for priority_sampling

---

spec/datadog/tracing/contrib/lograge/instrumentation_spec.rb
spec/datadog/tracing/contrib/semantic_logger/instrumentation_spec.rb
spec/datadog/tracing/contrib/sidekiq/distributed_tracing_spec.rb
spec/datadog/tracing/correlation_spec.rb
spec/datadog/tracing/span_operation_spec.rb
spec/datadog/tracing/trace_digest_spec.rb

Replace random 64 bits trace ID with 128 bits generation in our test suite. 
This better simulates the reality with our default.

Use 128 bits trace id in test

---

benchmarks/profiler_sample_loop_v2.rb
ext/ddtrace_profiling_native_extension/heap_recorder.c
ext/ddtrace_profiling_native_extension/heap_recorder.h
ext/ddtrace_profiling_native_extension/ruby_helpers.c
ext/ddtrace_profiling_native_extension/ruby_helpers.h
ext/ddtrace_profiling_native_extension/stack_recorder.c
lib/datadog/core/configuration/settings.rb
lib/datadog/profiling/component.rb
lib/datadog/profiling/stack_recorder.rb
sig/datadog/profiling/component.rbs
sig/datadog/profiling/stack_recorder.rbs
spec/datadog/core/configuration/settings_spec.rb
spec/datadog/profiling/component_spec.rb
spec/datadog/profiling/spec_helper.rb
spec/datadog/profiling/stack_recorder_spec.rb

* When an object id conflict is not allowed, raise with a more informative error message.
* Allow configuration of heap size collection (`DD_PROFILING_EXPERIMENTAL_HEAP_SIZE_ENABLED`) and heap sample rate (`DD_PROFILING_EXPERIMENTAL_HEAP_SAMPLE_RATE`).
* Debugging profiler shutdown on Ruby 2.7 workloads due to obj id conflicts.
* More knobs to enable different benchmarking flavours.

[prof-heap] Misc improvements/fixes

---

lib/datadog/tracing/contrib/excon/configuration/settings.rb
lib/datadog/tracing/contrib/faraday/configuration/settings.rb
lib/datadog/tracing/contrib/http/configuration/settings.rb
lib/datadog/tracing/contrib/httpclient/configuration/settings.rb
lib/datadog/tracing/contrib/httprb/configuration/settings.rb
lib/datadog/tracing/contrib/status_range_env_parser.rb
lib/datadog/tracing/contrib/status_range_matcher.rb
spec/datadog/tracing/contrib/excon/instrumentation_spec.rb
spec/datadog/tracing/contrib/faraday/middleware_spec.rb
spec/datadog/tracing/contrib/http/request_spec.rb
spec/datadog/tracing/contrib/http_examples.rb
spec/datadog/tracing/contrib/httpclient/instrumentation_spec.rb
spec/datadog/tracing/contrib/httprb/instrumentation_spec.rb
spec/datadog/tracing/contrib/shared_settings_examples.rb
spec/datadog/tracing/contrib/status_code_matcher_spec.rb
spec/datadog/tracing/contrib/status_range_env_parser_spec.rb
spec/datadog/tracing/contrib/status_range_matcher_spec.rb

Fix and standardize the way to configure an array of ranges for `error_status_codes` from environment variables.

Fix  `error_status_codes` options

---

docs/Compatibility.md

as it has been added in
https://github.com/DataDog/dd-trace-rb/pull/3167

List Ruby 3.3 as supported in the docs

---

docs/Compatibility.md

This PR backports https://github.com/DataDog/dd-trace-rb/pull/3371 to the `master` branch. It updates our docs to mark that Ruby 3.3 is fully supported.
Because https://github.com/DataDog/dd-trace-rb/pull/3371 was merged to the `release` branch directly (so as to update the docs immediately), we need to copy it to master as otherwise it would be clobbered the next time we make a release of the gem.
Thanks @gdubicki for the original PR.
Look at the markdown ;)

Backport "List Ruby 3.3 as supported in the docs" to master branch

---

spec/spec_helper.rb

This PR tweaks the RSpec configuration to skip any tests that make use of ractors (that are tagged with `:ractor => true`) unless RSpec is run with `-t ractors`.
As discussed in https://github.com/datadog/dd-trace-rb/pull/3320, ractors have a few bugs which cause flaky behavior on other specs we currently have.
And thus in the above PR, we changed the way we run the profiling specs in CI and via rake to make sure to separate tests using ractors out.
BUT, such a separation did not apply to when running rspec directly, which I do all the time. I even got confused at some point and thought we had flaky tests, when what I was seeing was the flakiness that happened when I ran all tests, together, including the ractor ones.
To improve this, this PR adds …

[NO-TICKET] Minor: Skip testcases using ractors when calling RSpec directly

---

lib/datadog/tracing/contrib/http/instrumentation.rb
sig/datadog/tracing/contrib/http/instrumentation.rbs
spec/datadog/tracing/contrib/http/request_spec.rb

The undocumented HTTP hook `Datadog::Tracing::Contrib::HTTP::Instrumentation.after_request` has been removed. This hook was intrusive, only restricted to the `net/http` client, and was not generalizable to other HTTP client gems.
If you require this hook, please [open a "Feature request"](https://github.com/DataDog/dd-trace-rb/issues/new/choose) stating your use case so we can asses how to best support it.
We are open to adding similar capabilities in the future, but we should asses the concrete user needs for such hook.
All changes are covered by unit testing. In this case, the tests are removed due to the removal of the feature.
credentials of any kind, I've requested a review from …

Remove `Datadog::Tracing::Contrib::HTTP::Instrumentation.after_request`

---

spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb

This PR re-enables a garbage collection profiling spec in the `CpuAndWallTimeWorker` that was disabled on Ruby 3.
This test was disabled in #2354 as this caused flaky tests due to a Ruby VM bug related to Ractor GC.
Recently, this "flaky when combined with Ractors" behavior started showing up in other places and @AlexJF came up with a better solution in #3320 of separating out the Ractor tests.
Thus, we can now run this spec on Ruby 3.
Recently, while working on #3356, I noticed that if I commented out the calls to `rb_postponed_job_[trigger|register_one]` in `on_gc_event`, no specs failed.
This was pretty surprising to me -- as it was weird that we didn't have test coverage for it.
After looking into it, I realized we did have specs for it -- but …

[NO-TICKET] Minor: Re-enable gc profiling spec on Ruby 3

---

ddtrace.gemspec

Adds `base64` to the gemspec
Requiring `base64` from stdlib is deprecated in Ruby v3.3 and will be removed in v3.4
N/A
N/A (drop-in replacement)

add base64 gem

---

integration/apps/sinatra2-classic/Gemfile
integration/apps/sinatra2-modular/Gemfile

This PR pins our sinatra integration apps to make sure they use sinatra 2. They were otherwise picking up sinatra 3 and 4.
It also tweaks a few of the gems to avoid future troubles when trying to run this app with newer sinatra/rack versions.
This PR is an alternative to #3390. Our sinatra apps are broken in CI as they picked up sinatra 4 and started breaking due to a minor incompatibility (`rack` 3 no longer includes `rackup` by default).
We could've opted to use newer sinatra versions for these apps, but our current pattern with rails is to have a different app for different versions, so for now let's keep with it.
N/A
Validate that CI is green.
credentials of any kind, …

[NO-TICKET] Pin sinatra integration apps to sinatra 2

---

docs/GettingStarted.md
lib/datadog/tracing/contrib/sidekiq/configuration/settings.rb
lib/datadog/tracing/contrib/sidekiq/ext.rb
lib/datadog/tracing/contrib/sidekiq/server_tracer.rb
sig/datadog/tracing/contrib/sidekiq/ext.rbs
spec/datadog/tracing/contrib/sidekiq/server_tracer_spec.rb

🚨 Sidekiq: `tag_args` option is removed, use `quantize` instead
If you were setting this option with true, change your code from 
```
c.tracing.instrument :sidekiq, tag_args: true
end
```
to
```
c.tracing.instrument :sidekiq, quantize: { args: { show: :all } }
end
```

`Sidekiq`: Remove `tag_args` option 

---

lib/datadog/tracing/contrib/sidekiq/server_tracer.rb
spec/datadog/tracing/contrib/sidekiq/server_tracer_spec.rb

🚨 Remove Sidekiq worker specific configuration
Defining `datadog_tracer_config` on Sidekiq worker is never documented and publicly supported. Hence removing the code.

`Sidekiq` : Remove worker specific configuration

---

lib/datadog/tracing/contrib/sinatra/ext.rb
sig/datadog/tracing/contrib/sinatra/ext.rbs

🚨 Remove following constants
```ruby
Datadog::Tracing::Contrib::Sinatra::Ext::RACK_ENV_REQUEST_SPAN
Datadog::Tracing::Contrib::Sinatra::Ext::RACK_ENV_MIDDLEWARE_START_TIME
Datadog::Tracing::Contrib::Sinatra::Ext::RACK_ENV_MIDDLEWARE_TRACED
```

`Sinatra` :Remove deprecated constants

---

lib/datadog/core/configuration/components.rb
lib/datadog/core/configuration/settings.rb
lib/datadog/core/diagnostics/environment_logger.rb
spec/datadog/core/configuration/components_spec.rb
spec/datadog/core/configuration/settings_spec.rb
spec/datadog/core/configuration_spec.rb
spec/datadog/core/diagnostics/environment_logger_spec.rb
spec/datadog/integration_spec.rb

Programmatic configuration options have been made more consistent with their respective environment variables:
| Previous | New | Environment Variable (unchanged) |
|-|-|-|
| `diagnostics.health_metrics.enabled` | `health_metrics.enabled` | `DD_HEALTH_METRICS_ENABLED` |
| `diagnostics.health_metrics.statsd` | `health_metrics.statsd` | (none) |
Environment variable naming is standard across all Datadog languages.
Our programmatic configuration API is an extra avenue for configuration for Ruby clients, and reflects the same options as the ones provided by environment variables.
The naming between the programmatic variant and the environment variable variant of the same option should be as close as possible.
**Additional …

Consistent option naming for health metrics

---

lib/datadog/core/configuration/option.rb
spec/datadog/appsec/contrib/support/integration/shared_examples.rb
spec/datadog/core/configuration/option_spec.rb
spec/datadog/core/configuration/settings_spec.rb
spec/datadog/tracing/configuration/settings_spec.rb
spec/datadog/tracing/contrib/shared_settings_examples.rb

Configuration options of types ':int' and ':float' now have stricter type validation:
* Fractional numbers are no longer considered valid for ':int' options.
* Empty values (nil or empty string) are no longer considered valid for ':int' or ':float' options.
This applies to both environment variable and programmatic configuration.
Here's the list of all affected options:
[Insert all :int and :float options at release time!!!]
The environment variable `DD_EXPERIMENTAL_SKIP_CONFIGURATION_VALIDATION` has been removed.
It was possible to configure options with empty values (e.g. `DD_TRACE_SAMPLE_RATE=`) and end up with a sampling rate of `0.0`, because of the logic `value.to_f`. The same applies to integer options (`value.to_i`).
Non-numeric values …

Stricter validation for integer and float configuration

---

Gemfile
lib/datadog/opentelemetry.rb
lib/datadog/opentelemetry/sdk/propagator.rb
lib/datadog/tracing/contrib/http/distributed/fetcher.rb
sig/datadog/tracing/contrib/http/distributed/fetcher.rbs

This PR fixes two issues:
* When loading `datadog/opentelemetry` before `ddtrace`, `tracing/contrib` files are not loaded.
* There are two default OpenTelemetry propagation getters, `text_map_getter` and `rack_env_getter`, but we only supported `text_map_getter` before. All our propagation code works correctly with `rack_env_getter`, so we allow it during configuration.
These two issues were found during the setup of https://github.com/DataDog/opentelemetry-demo/pull/42/files#diff-6f62dcc2d3fa2ec6fa2c3529d3d9357ae69c771fca911e87e2e982a45b50fa71

Fix OpenTelemetry internal loading

---

lib/datadog/tracing/configuration/ext.rb
lib/datadog/tracing/configuration/settings.rb
spec/datadog/tracing/configuration/settings_spec.rb

🚨 Breaking change: Configuration with `ENV['DD_TRACE_CLIENT_IP_HEADER_DISABLED']` is removed, use `ENV['DD_TRACE_CLIENT_IP_ENABLED']` instead.

Remove `client_ip` disabled env

---

.github/workflows/check.yml

Always run checks.
The workflow fails to run for PRs targeting 2.0, and x.y-stable branches. It should always run instead.
They're cheap enough. "Always" sounds like a good plan.

Fix check workflow branches

---

gemfiles/ruby_3.3_activesupport.gemfile.lock
gemfiles/ruby_3.3_aws.gemfile.lock
gemfiles/ruby_3.3_core_old.gemfile.lock
gemfiles/ruby_3.3_elasticsearch_7.gemfile.lock
gemfiles/ruby_3.3_elasticsearch_8.gemfile.lock
gemfiles/ruby_3.3_graphql_1.13.gemfile.lock
gemfiles/ruby_3.3_graphql_2.0.gemfile.lock
gemfiles/ruby_3.3_graphql_2.1.gemfile.lock
gemfiles/ruby_3.3_graphql_2.2.gemfile.lock
gemfiles/ruby_3.3_http.gemfile.lock
gemfiles/ruby_3.3_opensearch_2.gemfile.lock
gemfiles/ruby_3.3_opensearch_3.gemfile.lock
gemfiles/ruby_3.3_opentelemetry.gemfile.lock
gemfiles/ruby_3.3_opentracing.gemfile.lock
gemfiles/ruby_3.3_rack_1.gemfile.lock
gemfiles/ruby_3.3_rack_2.gemfile.lock
gemfiles/ruby_3.3_rack_3.gemfile.lock
gemfiles/ruby_3.3_rails61_mysql2.gemfile.lock
gemfiles/ruby_3.3_rails61_postgres.gemfile.lock
gemfiles/ruby_3.3_rails61_postgres_redis.gemfile.lock
gemfiles/ruby_3.3_rails61_postgres_sidekiq.gemfile.lock
gemfiles/ruby_3.3_rails61_semantic_logger.gemfile.lock
gemfiles/ruby_3.3_redis_3.gemfile.lock
gemfiles/ruby_3.3_redis_4.gemfile.lock
gemfiles/ruby_3.3_redis_5.gemfile.lock
gemfiles/ruby_3.3_relational_db.gemfile.lock
gemfiles/ruby_3.3_resque2_redis3.gemfile.lock
gemfiles/ruby_3.3_resque2_redis4.gemfile.lock
gemfiles/ruby_3.3_sinatra.gemfile.lock

Fix the lockfiles that were bundled with 2.3.27, https://github.com/DataDog/dd-trace-rb/pull/3410

Update ruby 3.3 bundler version in lockfiles

---

lib/datadog/core/configuration/ext.rb

I don't have confidence that this comment I wrote in the past has an accurate recommendation anymore, so I'm removing it to avoid possibly inaccurate advice coming from it.

Remove possibly inaccurate comment

---

tasks/appraisal.rake

The deprecated `:install_appraisal_gemfiles` and `:update_appraisal_gemfiles` are now removed.
This PR removes rake tasks that were marked to be removed in 2.0.
Just came across this looking at docker-compose configuration.

Remove obsolete rake tasks slated for removal in 2.0

---

docs/GettingStarted.md
lib/datadog/tracing/contrib/active_record/events/instantiation.rb
spec/datadog/tracing/contrib/active_record/app.rb
spec/datadog/tracing/contrib/active_record/instantiation_spec.rb

This is an extraction of tests from #3184.
This PR adds a test for ActiveRecord instantiation events. This is functionality already provided by the library but apparently untested.
The change is in test suite only.

Test for active_record.instantiation events

---

docs/OpenTelemetry.md

This PR fixes headings in the OpenTelemetry doc page.
I was looking through documentation and the headings on pages aren't always written consistently. This issue affects other pages also, this PR only tackles OpenTelemetry where I think the change is straightforward.
Render the markdown page to HTML and look at the headings' appearance.

Fix OpenTelemetry doc headings

---

lib/datadog/tracing/contrib/rack/middlewares.rb
spec/datadog/tracing/contrib/rack/disabled_spec.rb

closes #3389 
When `tracing` and `distributed_tracing` both disabled, The reference of `Datadog::Tracing.active_trace` in rack 
instrumentation returns `nil`. 
Causing
```
NoMethodError: undefined method `resource_override?' for nil:NilClass
```

Rack: Fix missing active trace

---

lib/datadog/tracing.rb
spec/datadog/tracing_spec.rb

This PR fixes #3385 by preventing components initialization when calling the `Datadog::Tracing.correlation` API.
Instead, we use the `allow_initialization: false` option, which was added exactly to help break these kinds of initialization cycles.
This fixes a deadlock issue such as:
```
lib/datadog/core/configuration.rb:228:in `synchronize': deadlock; recursive locking (ThreadError)
from lib/datadog/core/configuration.rb:228:in `safely_synchronize'
from lib/datadog/core/configuration.rb:195:in `components'
from lib/datadog/tracing.rb:134:in `components'
from lib/datadog/tracing.rb:138:in `tracer'
from lib/datadog/tracing.rb:76:in `correlation'
from repro.rb:5:in `add'
from logger-1.6.0/lib/logger.rb:691:in `debug'
from …
```

Fix deadlock when logger tries to use correlation

---

docs/GettingStarted.md
lib/datadog/tracing/sampling/all_sampler.rb
lib/datadog/tracing/sampling/matcher.rb
lib/datadog/tracing/sampling/priority_sampler.rb
lib/datadog/tracing/sampling/rate_by_key_sampler.rb
lib/datadog/tracing/sampling/rate_by_service_sampler.rb
lib/datadog/tracing/sampling/rate_limiter.rb
lib/datadog/tracing/sampling/rate_sampler.rb
lib/datadog/tracing/sampling/rule.rb
lib/datadog/tracing/sampling/rule_sampler.rb
lib/datadog/tracing/sampling/sampler.rb
lib/datadog/tracing/sampling/span/rule.rb
lib/datadog/tracing/sampling/span/sampler.rb
spec/datadog/tracing/integration_spec.rb
spec/datadog/tracing/sampling/rate_sampler_spec.rb
spec/datadog/tracing/sampling/rule_sampler_spec.rb
spec/datadog/tracing/sampling/rule_spec.rb
spec/datadog/tracing/sampling/span/rule_spec.rb

The following sampling classes have been removed from the public API:
```ruby
Datadog::Tracing::Sampling::AllSampler
Datadog::Tracing::Sampling::Matcher
Datadog::Tracing::Sampling::SimpleMatcher
Datadog::Tracing::Sampling::ProcMatcher
Datadog::Tracing::Sampling::PrioritySampler
Datadog::Tracing::Sampling::RateByKeySampler
Datadog::Tracing::Sampling::RateByServiceSampler
Datadog::Tracing::Sampling::RateLimiter
Datadog::Tracing::Sampling::TokenBucket
Datadog::Tracing::Sampling::UnlimitedLimiter
Datadog::Tracing::Sampling::RateSampler
Datadog::Tracing::Sampling::Rule
Datadog::Tracing::Sampling::SimpleRule
Datadog::Tracing::Sampling::RuleSampler
Datadog::Tracing::Sampling::Sampler
```
Most custom sampling can be accomplished with a combination of [Ingestion …

Minimize sampling API

---

docs/GettingStarted.md
lib/datadog/tracing/contrib/faraday/configuration/settings.rb
lib/datadog/tracing/contrib/faraday/middleware.rb
spec/datadog/tracing/contrib/faraday/middleware_spec.rb

From a closed PR: https://github.com/DataDog/dd-trace-rb/pull/3306
Backport the changes for `Faraday` with `on_error` option

Faraday: Add `on_error` option

---

spec/datadog/core/environment/execution_spec.rb

Fix failing spec on MacOS and CircleCI, where `steep` is bundled. 
`steep` depends on  `activesupport`, which depends on `minitest`. So the test is activated on CI. 
With no version constraint on the version, Minitest release 5.22.1 on Feb 6
https://github.com/minitest/minitest/blob/master/History.rdoc#label-5.22.1+-2F+2024-02-06
Our test suite failed with such change. 
To fix it, add a dummy test case so the process status would be successful.
**Note**: This is something we should be working on continuing improving our environment.

Fix minitest detection spec

---

lib/datadog/core/diagnostics/environment_logger.rb
lib/datadog/profiling/diagnostics/environment_logger.rb
lib/datadog/tracing/diagnostics/environment_logger.rb
sig/datadog/core/diagnostics/environment_logger.rbs
spec/datadog/core/diagnostics/environment_logger_spec.rb
spec/datadog/profiling/diagnostics/environment_logger_spec.rb
spec/datadog/tracing/diagnostics/environment_logger_spec.rb

In 1.x startup logs would emit only once during initial configuration of the library. In 2.0 these logs will now emit whenever the library reconfigures itself, which may occur multiple times during startup. The increased verbosity in logging better represents the configuration state of the library at the time the logs are generated. 
The default setting has not changed for startup logs. It remains `nil`, which generates startup logs for non-dev environments. To turn off startup logs completely you can set:
```ruby
Datadog.configure { |c| c.diagnostics.startup_logs.enabled = false }
```
Remove the `log_once` restriction on startup logs. …

do not restrict startup logs to emit only once

---

gemfiles/ruby_2.5_graphql_1.12.gemfile.lock
gemfiles/ruby_2.6_graphql_1.12.gemfile.lock
gemfiles/ruby_2.7_graphql_1.12.gemfile.lock
gemfiles/ruby_3.0_graphql_1.12.gemfile.lock
gemfiles/ruby_3.0_rails61_trilogy.gemfile.lock
gemfiles/ruby_3.1_graphql_1.12.gemfile.lock
gemfiles/ruby_3.1_rails61_trilogy.gemfile.lock
gemfiles/ruby_3.2_graphql_1.12.gemfile.lock
gemfiles/ruby_3.2_rails61_trilogy.gemfile.lock
lib/datadog/tracing/contrib/extensions.rb

🚨 Breaking change: Remove `use` method for configuration, replace with `instrument`. 
For example
```ruby
c.tracing.use :mysql2
end
```
to
```ruby
c.tracing.instrument :mysql2
end
```

Remove `use` alias for `instrument`

---

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c
ext/ddtrace_profiling_native_extension/collectors_discrete_dynamic_sampler.c
ext/ddtrace_profiling_native_extension/collectors_discrete_dynamic_sampler.h
lib/datadog/profiling/collectors/cpu_and_wall_time_worker.rb
lib/datadog/profiling/component.rb
lib/datadog/profiling/exporter.rb
lib/datadog/profiling/flush.rb
sig/datadog/profiling/collectors/cpu_and_wall_time_worker.rbs
sig/datadog/profiling/component.rbs
sig/datadog/profiling/exporter.rbs
spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
spec/datadog/profiling/exporter_spec.rb
spec/datadog/profiling/flush_spec.rb
spec/datadog/profiling/http_transport_spec.rb

Ship extra information about the profile that is helpful for developers to understand the workings of certain internal processes such as allocation sampling statistics and state in a non-impactful manner.
Having information such as sampling statistics accompanying uploaded profiles enables a multitude of things:
* Extra data to facilitate troubleshooting/debugging of weird edge cases or as data-sources for profiling insights.
* Creation of anonymised wide-range telemetry for studying systems operating in practice (e.g. "what is the min/max/avg/pxx allocation sampling probability/allocated samples per profile").
Profiles uploaded with this change will have extra fields in their metadata, looking …

[PROF-9036] Include profiling worker and GC stats in profiles

---

lib/datadog/core/transport/ext.rb
lib/datadog/tracing/transport/http.rb
sig/datadog/core/transport/ext.rbs
spec/datadog/tracing/transport/http_spec.rb

Add the required field to allow us to differentiate between the different Ruby interpreters in internal reporting.
We currently have to distinguish between CRuby and JRuby in our reporting by trying to guess which one is which from the Ruby language version number they support.
But because JRuby and CRuby version numbers overlap, it is not possible to make a conclusive decision on such data.

Add interpreter vendor to trace headers

---

spec/datadog/profiling/stack_recorder_spec.rb

Increases the probability to re-use a recycled object slot.
Reduce flakiness seen in gc_force_recycle tests.

Fix flakiness of gc_force_recycle tests

---

lib/datadog/tracing/contrib/sinatra/tracer.rb

Removes comment of `binding.pry` that was mistakenly merged in #3345

Remove `binding.pry` comment

---

lib/datadog/core/configuration/option_definition.rb
spec/datadog/core/configuration/option_definition_spec.rb

Configuration options can no longer be defined as `lazy`. All options are lazily evaluated, making this redundant. 
Removes a deprecated method on option_definition for defining a configuration option as lazy. 

remove deprecated lazy method for option_definition

---

.gitlab/benchmarks.yml

This PR adds a new configuration to for testing in the benchmarking platform.
This configuration enables the "GC profiling" (on top of timeline), and will be used to validate when we're good to enable this feature by default.
Validate performance impact of "GC profiling" feature, especially when used together with timeline.
I'm preparing a similar PR to add this configuration also to the reliability environment configurations.
Validate that benchmarking platform profiling runs now include a variant where GC information shows up in the flamegraph, as well as in the timeline visualization.
credentials of any kind, I've requested a review from …

[NO-TICKET] Add Ruby profiler benchmark with GC profiling

---

lib/datadog/core/environment/git.rb
lib/datadog/core/git/ext.rb
lib/datadog/core/utils/url.rb
lib/datadog/profiling/ext.rb
lib/datadog/profiling/tag_builder.rb
lib/datadog/tracing/transport/trace_formatter.rb
sig/datadog/core/environment/git.rbs
sig/datadog/core/git/ext.rbs
sig/datadog/core/utils/url.rbs
sig/datadog/profiling/ext.rbs
sig/datadog/tracing/transport/trace_formatter.rbs
spec/datadog/core/environment/git_spec.rb
spec/datadog/core/utils/url_spec.rb
spec/datadog/profiling/tag_builder_spec.rb
spec/datadog/tracing/transport/trace_formatter_spec.rb

In order to use the new source code integration feature set the following environment variables:
- DD_GIT_REPOSITORY_URL
- DD_GIT_COMMIT_SHA 
Adds source code integration tags to APM traces according to the following requirements:
- if DD_GIT_REPOSITORY_URL env var is defined, its value should be sanitized by removing possible URL credentials (user/password information if it can be successfully parsed into an URL) and set in the _dd.git.repository_url of the first span of every trace chunk
- if DD_GIT_COMMIT_SHA env var is defined, its value should be set in _dd.git.commit.sha of the first span of every trace chunk
Why are we not using trace_operation.set_tags?
Trace-level tags are being set in the **root span** …

[CIVIS-8604] APM source code integration

---

lib/datadog/core/environment/git.rb
lib/datadog/core/git/ext.rb
lib/datadog/core/utils/url.rb
lib/datadog/profiling/ext.rb
lib/datadog/profiling/tag_builder.rb
lib/datadog/tracing/transport/trace_formatter.rb
sig/datadog/core/environment/git.rbs
sig/datadog/core/git/ext.rbs
sig/datadog/core/utils/url.rbs
sig/datadog/profiling/ext.rbs
sig/datadog/tracing/transport/trace_formatter.rbs
spec/datadog/core/environment/git_spec.rb
spec/datadog/core/utils/url_spec.rb
spec/datadog/profiling/tag_builder_spec.rb
spec/datadog/tracing/transport/trace_formatter_spec.rb

Backporting [APM source code integration](https://github.com/DataDog/dd-trace-rb/pull/3424) previously merged to 2.0
Release source code integration as fast as possible

Backport "APM source code integration"

---

lib/datadog/core/transport/ext.rb
lib/datadog/tracing/transport/http.rb
sig/datadog/core/transport/ext.rbs
spec/datadog/tracing/transport/http_spec.rb

This PR backports https://github.com/DataDog/dd-trace-rb/pull/3451 "Add interpreter vendor to trace headers" from the 2.0 branch to master.
Having this metadata seems very relevant. Backporting it to master, means the last of the 1.x releases should have it, which will allows to measure how many customers staying on 1.x are on JRuby/other runtimes.
N/A
This change includes test coverage. I also gave it a quick local check and can confirm I see the `"datadog-meta-lang-interpreter-vendor"=>["jruby"]` showing up.

Backport "Add interpreter vendor to trace headers" to master

---

lib/datadog/profiling/exporter.rb

The name `uncompressed_pprof` is a legacy of a time when that was true, but actually for a few releases now libdatadog has emitted compressed profiles.
Fix misleading name.
N/A
Existing tests cover this functionality.

[NO-TICKET] Minor: Fix misnamed variable in profiler

---

lib/datadog/core/configuration/settings.rb
lib/datadog/profiling/component.rb
spec/datadog/core/configuration/settings_spec.rb
spec/datadog/profiling/component_spec.rb

This PR enables the timeline feature for the Continuous Profiler by default.
It introduces a new setting, `timeline_enabled`, which can also be controlled by setting the `DD_PROFILING_TIMELINE_ENABLED` environment variable.
It also deprecates the old `experimental_timeline_enabled` + it's environment variable counterpart.
With the latest round of improvements to libdatadog, we're confident about enabling this feature by default.
~~I'm opening this PR as a draft as it still depends on https://github.com/DataDog/libdatadog/pull/293 being released + a few more rounds of internal validation.~~ ✅ Fixed
~~This PR also will need to be updated with the changes from https://github.com/DataDog/dd-trace-rb/pull/3357 OR the reverse will …

[PROF-8942] Enable Ruby timeline by default

---

.gitlab/benchmarks.yml

As soon as we merge https://github.com/datadog/dd-trace-rb/pull/3428 the profiler will default to timeline being enabled.
This means that the "profiler" configurations will all have timeline, so having separate configurations for timeline does not make any sense.
Remove timeline testing configurations that no longer make sense.
For the configuration with GC profiling, I've removed the `DD_PROFILING_EXPERIMENTAL_TIMELINE_ENABLED` environment variable, since, again, timeline is on by default.
We could potentially keep a configuration without timeline around, but we already have a lot of configurations, so for now I've chosen not to do so.
This can be tested by manually triggering a deploy to the …

[PROF-8942] Remove separate benchmarking configurations for profiling timeline

---

.gitignore
.gitlab-ci.yml
.gitlab/benchmarks.yml
benchmarks/Dockerfile
benchmarks/tracing_trace.rb
spec/datadog/profiling/validate_benchmarks_spec.rb
spec/datadog/tracing/validate_benchmarks_spec.rb

Adds a tracing microbenchmark that measures the total time the tracing takes to create a custom trace, until it reaches the writer. This does not measure the writer cost (it's stubbed out).
Microbenchmarks allows us to quickly compare the performance between two commits, making it feasible to run on every PR change. It also allows for quick iteration when performing performance improvements.
You can see the [PR comment below](https://github.com/DataDog/dd-trace-rb/pull/3472#issuecomment-1958201602) with the results for this PR, which are uninteresting because it doesn't make Ruby prod changes.
When merged, the [2.0 PR](https://github.com/DataDog/dd-trace-rb/pull/3421) will continuously display the performance changes …

Add tracing microbenchmarks

---

benchmarks/tracing_trace.rb

Adds a benchmark that stubs the network adapter, but includes everything else: writer, serialization, transport.
This new benchmark is in addition to the one testing to tracer critical path only, introduced in #3472.
There's quite a bit of work done by the library besides the main critical path work. This new benchmark captures that.

Add benchmark that only excludes network

---

benchmarks/tracing_trace.rb

Follow up to #3474
Adds a benchmark that measures the process of generating a `TraceDigest` from an active trace.
This happens whenever distributed tracing propagation happens.

Add benchmark for TraceDigest generation

---

benchmarks/tracing_trace.rb

Follow up to https://github.com/DataDog/dd-trace-rb/pull/3474
Adds a benchmark that measures the process of generating a log correlation information from an active trace.
This happens whenever a log line is generated in a traced application.

Add benchmark for log correlation

---

.github/workflows/build-gem.yml
.gitlab-ci.yml
.gitlab/patch_gem_version.sh
lib/datadog/core/environment/identity.rb
spec/datadog/core/environment/identity_spec.rb

This PR changes the gem version for our test/prerelease gem. 
The build metadata starts with a git branch hash which can be helpful to group artifacts per branch.

Change prerelease gem version pattern

---

benchmarks/tracing_trace.rb

Add benchmarking for distributed trace propagation round-trip: extracting distributed headers from the active trace, then passing those headers back into a trace digest.
This PR has benchmarks for both the Datadog propagation style and W3C Trace Context style.
It also has a benchmark for a basic, digest generation and continuation.
This captures the complete overhead of distributed tracing.

Add benchmark for distributed trace propagation

---

lib/datadog/tracing/trace_operation.rb
spec/datadog/tracing/integration_spec.rb
spec/datadog/tracing/trace_operation_spec.rb

`Datadog::Tracing.reject!` now only changes the priority sampling, as documented, instead of preventing the trace from reaching the Datadog Agent. Now, rejected traces will correctly count towards [trace metrics](https://docs.datadoghq.com/tracing/metrics/#trace-metrics).
This was always the intended behavior, but was incorrectly implemented.

Fix `Datadog::Tracing.reject!` with correct metrics

---

.gitlab-ci.yml

I want to validate Relenv deployment without waiting on prerequisites during development.

Allows deployment without prerequisites

---

benchmarks/tracing_trace.rb

This PR documents why the benchmark that includes the writer yields unstable results.
This PR also fixes test comparisons with `master` branch running `1.x`. This is only needed because the benchmarks are run against both `1.X` and `2.X`. If benchmarks already existed `1.x` this wouldn't be an issue, but because they were recently introduced, they do not exist in master branch. We can revert this fix when `2.x` is merged to `master` but we need minor changes to ensure immediately compatibility.

Fix unstable benchmarks and comparison with 1.x

---

lib/datadog/core/remote/negotiation.rb
sig/datadog/core/remote/negotiation.rbs
spec/datadog/core/remote/negotiation_spec.rb

Adds `suppress_logging` keyword argument that makes it possible to skip logging error messages for selected error cases.
Usage: 
```ruby
negotiation = Datadog::Core::Remote::Negotiation.new(
settings, 
agent_settings, 
suppress_logging: { no_config_endpoint: true }
)
negotiation.endpoint?("/evp_proxy/v4/") # => false
```
`datadog-ci` gem uses `Datadog::Core::Remote::Negotiation` to check if agent has certain endpoints available(`/evp_proxy/v4` and `/evp_proxy/v2/`) to configure the correct transport for citestcycle events. We do not treat the absence of any of these endpoints as error, just an information for us to choose the correct way to send events. 
Currently, this class treats this situation as an error and logs error message thus creating …

Allow suppresing error logs for Core::Remote::Negotiation

---

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c
ext/ddtrace_profiling_native_extension/private_vm_api_access.c
ext/ddtrace_profiling_native_extension/private_vm_api_access.h

This PR adds a workaround for a VM bug (https://bugs.ruby-lang.org/issues/19991) that has affected at least two customers (the other being https://github.com/DataDog/dd-trace-rb/issues/3430).
The workaround is... not very pretty... but I believe will get the job done, for the reasons explained in the big comment I added.
The good thing about this crash is that it seems extremely rare.
The bad thing is that without this workaround, only moving to Ruby 3.3+ is the fix, and we still have a lot of customers on older Ruby versions.
We've documented in https://docs.datadoghq.com/profiler/profiler_troubleshooting/ruby/#segmentation-faults-in-gc_finalize_deferred-in-ruby-versions-26-to-32 that the no signals workaround can be used to work around the issue …

[PROF-9147] Add workaround for Ruby VM bug causing crash in gc_finalize_deferred

---

lib/ddtrace/version.rb
spec/datadog/profiling/tag_builder_spec.rb

This PR changes the version of the library to 2.0.0.rc1.
This is needed as we have started deploying 2.x to our internal environments, and we've started to see traces produced by 2.x being ingested. Without this version bump, it's impossible to tell if the trace was produced by `ddtrace` 1.x or 2.x.

Bump version to 2.0.0.dev

---

lib/datadog/tracing/tracer.rb

Streamline the method calling by removing private `build_span_events`
This private method `build_span_events` is only invoked without any arguments

Remove private `build_span_events`

---

.gitlab/benchmarks.yml
benchmarks/profiler_memory_sample_serialize.rb
spec/datadog/profiling/validate_benchmarks_spec.rb

Adds sample+serialize ruby microbenchmark and a benchmarking platform configuration focused on allocation profiling.
Understand overheads of allocation profiling.
```
❯ bundle exec ruby benchmarks/profiler_memory_sample_serialize.rb
Libdatadog from: /Users/alexandre.fonseca/Projects/DataDog/libdatadog/build/arm64-darwin-23/lib/pkgconfig
Current pid is 48717
DogStatsD reporting ❌ disabled
Warming up --------------------------------------
sample+serialize 
1.000  i/100ms
Calculating -------------------------------------
sample+serialize 
4.526  (± 0.0%) i/s -     46.000  in  10.164368s
```
Unsure? Have …

[PROF-9180] Benchmarks for allocation profiling

---

docs/Compatibility.md

We have updated our [compatibility page](https://docs.datadoghq.com/tracing/trace_collection/compatibility/ruby/) to include our library [support policy](https://docs.datadoghq.com/tracing/trace_collection/compatibility/ruby/#support-policy). 
Adds a support policy to our [compatibility document](https://docs.datadoghq.com/tracing/trace_collection/compatibility/ruby) and make minor tweaks to compatibility content to conform to the accepted support policy RFC (a non-public doc I can share via private means) to avoid duplicating content.
Better communicate Ruby language version and architecture support for ddtrace.
The support policy does not explain how long previous library major versions will be …

update compatibility doc with support policy

---

Steepfile
ext/datadog_profiling_native_extension/http_transport.c
ext/datadog_profiling_native_extension/ruby_helpers.c
ext/datadog_profiling_native_extension/ruby_helpers.h
lib/datadog/core/configuration/components.rb
sig/datadog/profiling/flush.rbs
spec/datadog/core/configuration/components_spec.rb
spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
spec/datadog/profiling/component_spec.rb
vendor/rbs/libdatadog/0/libdatadog.rbs

This PR pulls in a few small fixes that I originally included in #3384. See individual commits for details.
Since #3384 is still blocked on a few libdatadog changes/a libdatadog release, I decided to extract these fixes so we can have them already in master.
N/A
These changes are covered by existing test coverage.

[PROF-8917] Misc fixes from crashtracker branch

---

lib/datadog/core/remote/worker.rb
sig/datadog/core/remote/worker.rbs
spec/datadog/core/remote/worker_spec.rb

This PR fixes the remote configuration worker thread leak that is discussed in more detail in the internal
"dd-trace-rb Remote::Worker thread leak investigation" doc.
In a nutshell, there's a potential race between threads that call `Datadog::Core::Remote::Tie.boot` and threads that call `Datadog.configure` that can, in really unlucky situations, mean that the `Remote::Worker thread gets leaked during library reconfiguration.
This rare issue is O(number of times Datadog.configure gets called) while requests are being processed in a web-app.
I was only able to reproduce it with the weird reproducer below, and by adding `sleep` to some parts of our code, so while we have observed it in production, we expect it to be rare.
Being more specific, this issue is related …

[PROF-9136] Fix rare remote configuration worker thread leak

---

lib/datadog/core/configuration/settings.rb
lib/datadog/profiling/component.rb
spec/datadog/core/configuration/settings_spec.rb
spec/datadog/profiling/collectors/info_spec.rb
spec/datadog/profiling/component_spec.rb

In the next dd-trace-rb release, allocation profiling is no longer experimental. To reflect this, this PR includes two changes:
* It replaces the `profiling.advanced.experimental_allocation_enabled` with the new `profiling.allocation_enabled` option
* It turns the previous warning when turning on allocation profiling into a debug log message
Update code to match non-experimental status of feature.
I've decided to move the new setting outside the `advanced` configuration group, as enabling allocation profiling is not considered an "advanced" option.
To allow for smooth upgrades, I've left `profiling.advanced.experimental_allocation_enabled` in place with a deprecation warning, but unfortunately I was not able to find a nice …

[NO-TICKET] Replace `profiling.advanced.experimental_allocation_enabled` with `profiling.allocation_enabled` and remove experimental warning

---

.gitlab-ci.yml

This PR fixes the following error in our nightly deploys of test builds:
```
Unable to create pipeline
'install-dependencies-amd64: [2.7.8]' job needs 'build-gem' job, but 'build-gem' is not in any previous stage
'install-dependencies-amd64: [3.0.6]' job needs 'build-gem' job, but 'build-gem' is not in any previous stage
'install-dependencies-amd64: [3.1.4]' job needs 'build-gem' job, but 'build-gem' is not in any previous stage
'install-dependencies-amd64: [3.2.2]' job needs 'build-gem' job, but 'build-gem' is not in any previous stage
'install-dependencies-arm64: [2.7.8]' job needs 'build-gem' job, but 'build-gem' is not in any previous stage
'install-dependencies-arm64: [3.0.6]' job needs 'build-gem' job, but 'build-gem' is not in any previous stage …
```

[NO-TICKET] Fix nightly test build deploys

---

lib/datadog/tracing/contrib/active_record/configuration/resolver.rb
lib/datadog/tracing/contrib/configurable.rb
spec/datadog/tracing/contrib/active_record/configuration/resolver_spec.rb
spec/datadog/tracing/contrib/active_record/multi_db_spec.rb

closes #3522 
When an invalid string is provided for multiplexing configuration, although it logs an error, it still add the matcher `true` to the configuration. Later during resolving, an exception will be raised.
In this PR, the mitigation is to skip adding the matcher if the input is invalid, also reduce the log message.

Fix ActiveRecord resolve function

---

lib/datadog/tracing/contrib/action_mailer/events/deliver.rb

I noticed a typo and corrected it, changing "email date" to "email data."

Fix typo in ActionMailer deliver event comments

---

.gitlab/build-deb-rpm.sh

The change moved the packaging into /tmp the file permissions there [default to being wide open](https://unix.stackexchange.com/questions/71622/what-are-correct-permissions-for-tmp-i-unintentionally-set-it-all-public-recu). This PR changes the permission to `drwxr-xr-x`

Fix lib injection artifact file permission

---

Rakefile
spec/ddtrace/gem_packaging_spec.rb
tasks/release_gem.rake

This PR adds validation so we catch the issue from #3529 before the incorrect packages are published on rubygems.org.
Specifically, it checks that every file in packaged `.gem` file has the expected permissions.
Avoid #3529 happening again.
N/A
You can run `bundle exec rake build` to trigger this validation. Try setting incorrect permissions on one of the files and running, and you should see the validation failing.

[NO-TICKET] Add validation for gem file permissions

---

.github/PULL_REQUEST_TEMPLATE.md
lib/datadog/opentelemetry/trace.rb
lib/datadog/tracing/distributed/b3_multi.rb
lib/datadog/tracing/distributed/b3_single.rb
lib/datadog/tracing/distributed/datadog.rb
lib/datadog/tracing/distributed/trace_context.rb
lib/datadog/tracing/trace_digest.rb
lib/datadog/tracing/trace_operation.rb
lib/datadog/tracing/tracer.rb
sig/datadog/tracing/trace_digest.rbs
sig/datadog/tracing/trace_operation.rbs
spec/datadog/tracing/distributed/b3_multi_spec.rb
spec/datadog/tracing/distributed/b3_single_spec.rb
spec/datadog/tracing/distributed/datadog_spec.rb
spec/datadog/tracing/distributed/propagation_spec.rb
spec/datadog/tracing/distributed/trace_context_spec.rb
spec/datadog/tracing/trace_operation_spec.rb
spec/datadog/tracing/tracer_spec.rb

Adds a mechanism to track whether a TraceDigest represents a remote span or if it is local to a host. This change is analogous to a change made in NodeJS: https://github.com/DataDog/dd-trace-js/pull/4153.
`is_remote` or `trace_remote` is an opentelemetry concept and is defined here: https://opentelemetry.io/docs/specs/otel/trace/api/#isremote.
This new field will be used to propagate the last datadog parent id in w3c tracecontext headers. This change blocks: https://github.com/DataDog/dd-trace-rb/pull/3488 

chore(tracing): Adds trace_remote field to TraceDigest

---

.circleci/images/primary/Dockerfile-2.1.10
.circleci/images/primary/Dockerfile-2.2.10
.circleci/images/primary/Dockerfile-2.3.8

Make Dockerfiles for 2.1, 2.2 and 2.3 work with debian bookworm (2.2 with bullseye due to https://github.com/ruby/setup-ruby/issues/496) rather than stretch, whose repos have been archived.
@ivoanjo pointed out we could have just rerouted the repos to debian archive but this way we stop relying on such old setups which makes things like docker setup and any eventual changes much easier since we're less likely to run into more unsupported/broken things.
Make github CI jobs work for 2.1, 2.2 and 2.3 again.

[ci] Fix 2.1, 2.2 and 2.3 Dockerfiles

---

.github/workflows/lib-injection.yml

We generate the latest snapshot of lib init image in order to be tested from other pipelines (system-tests nightly build)

k8s-lib-injection: Generate latest_snapshot lib init image

---

.rubocop_todo.yml
lib/datadog/auto_instrument.rb

Add an auto instrument shim
In Gemfile
```ruby
gem 'ddtrace', require: 'ddtrace/auto_instrument'
gem 'ddtrace', require: 'datadog/auto_instrument'
```
Smoother upgrade for 2.0

Add auto instrument shim

---

.circleci/images/primary/Dockerfile-2.3.8

This PR changes our Ruby 2.3 docker image to use Debian 11 "bullseye" as a base instead of Debian 12 "buster".
In https://github.com/DataDog/dd-trace-rb/pull/3534 we updated this image but this broke system-tests
(https://github.com/DataDog/dd-trace-rb/actions/runs/8346827939/job/22845592152) because they use an old nokogiri version that fails to build on modern systems (https://github.com/sparklemotion/nokogiri/issues/2105):
```
$ gem install nokogiri -v '= 1.10.10'
xml_document.c:495:14: error: conflicting types for 'canonicalize'; have 'VALUE(int,  VALUE *, VALUE)' {aka 'long unsigned int(int,  long unsigned int *, long unsigned int)'}
495 | static VALUE canonicalize(int argc, VALUE* argv, VALUE self)
|              ^~~~~~~~~~~~
In file included from …
```

[NO-TICKET] Fix Ruby 2.3 system tests by using Debian 11 bullseye as a base

---

.circleci/images/primary/Dockerfile-2.1.10
.circleci/images/primary/Dockerfile-2.2.10
.circleci/images/primary/Dockerfile-2.3.8

This PR is a slightly tweaked revert of
https://github.com/DataDog/dd-trace-rb/pull/3534 .
TL;DR after updating our Ruby 2.1/2.2/2.3 images to a newer debian, we discovered that some of our CI testing requires the `mysql` gem, which breaks on newer Debian versions (due to a newer libmysqlclient/libmariadb).
With these reverts, I was able to locally rebuild the images and install both mysql and nokogiri:
```
$ docker run -ti -v `pwd`:/working ivoanjo/docker-library:ddtrace_rb_2_3_8_testing_t6  /bin/bash
root@255fe2dc2374:/app# ruby -v
ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-linux]
root@255fe2dc2374:/app# docker-compose -v
docker-compose version 1.8.0, build unknown
root@255fe2dc2374:/app# bundle -v
Bundler version 1.17.3
root@255fe2dc2374:/app# gem …
```

[PROF-9368] Revert Ruby 2.1/2.2/2.3 CI images to older Debian to support mysql gem

---

.github/workflows/release-lib-injection.yml
.gitlab-ci.yml

On the verge of releasing `2.0.0.beta1`, disable publishing lib injection artifacts since they are not safe to be publicly available.

Temp disable publishing lib injection artifacts

---

.github/workflows/system-tests.yml

Add Rails 7.1
missing coverage
- followup to https://github.com/DataDog/system-tests/pull/2242
- more to come with subsequent https://github.com/DataDog/system-tests/pull/2246
CI should pass

Add Rails 7.1 to the system test matrix

---

.github/workflows/system-tests.yml

Enable docker mode for system tests
This allows hoisting runner build out of the test run job
~Tentative. May or may not work.~ It works now.
CI should pass system tests.

Enable docker mode for system tests

---

lib/datadog/appsec/contrib/rack/request_middleware.rb
spec/datadog/appsec/contrib/rack/integration_test_spec.rb

Add WAF vendors headers in traces tags according to this [RFC](https://docs.google.com/document/d/1xf-s6PtSr6heZxmO_QLUtcFzY_X_rT94lRXNq6-Ghws)
This will enable the ASM Respond team to parse the value of these headers and check that they are in the correct format
I used a hash to access traces-formatted headers and rack-formatted headers at the same time, and this hash is created from a list of string, corresponding to the HTTP-formatted header. Maybe these operations can add overhead time, and manually creating the hash would be faster
1. Use Rspec (`-e 'with WAF vendor headers'`)
2. Use [system-tests](https://github.com/DataDog/system-tests)
- Enable Test_ExternalWafRequestsIdentification in ruby …

Added WAF vendors headers in traces tags

---

spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb

Fix 3 flaky tests that have surfaced this week:
* `Datadog::Profiling::Collectors::CpuAndWallTimeWorker ._native_allocation_count when CpuAndWallTimeWorker has been started when allocation profiling is enabled returns the number of allocations between two calls of the method`
* https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/14119/workflows/cbefa69c-c16e-41fd-a601-2e951a5264ab/jobs/525211
* `expect(after_allocations - before_allocations).to be 100 | expected #<Integer:201> => 100 | got #<Integer:215> => 107`
* TL;DR: Rare GC occurrence in the middle of the test would count extra array allocations due to execution of finalizer functions with complex arguments (`*rest`) which are expected to come from usage of `Tempfile` in previous tests in the run. …

[profiling] Fix 3 flaky tests

---

.github/workflows/lib-injection.yml

We are migrating the lib injection tests in order to use Kubernetes Python Client instead of bash script. With this change we integrate the new lib injection tests into system-tests lifecycle. For example, we can push the test results to FPD.

New k8s lib injection tests

---

Steepfile
datadog.gemspec
lib/datadog/appsec/event.rb
lib/datadog/core/remote/client/capabilities.rb
lib/datadog/core/remote/transport/http/config.rb
lib/datadog/core/utils/base64.rb
sig/datadog/core/utils/base64.rbs
spec/datadog/core/remote/client_spec.rb
spec/datadog/core/remote/transport/http_spec.rb
spec/datadog/core/remote/transport/integration_spec.rb
spec/datadog/tracing/contrib/suite/integration_spec.rb

Remove the runtime dependency on the base64 gem.
#3364 added a dependency on the base64 gem to silence warnings on Ruby >= 3.4
The used portions of the base64 gem are just wrappers around the pack/unpack methods ([see here](https://github.com/ruby/base64/blob/9669a7d3b0e3b9a739969404daf58f912c58c6b3/lib/base64.rb)). These can be added to a module to keep their descriptive names and allow the gem to drop a dependency.
I've done something quite similar for the newrelic agent [here](https://github.com/newrelic/newrelic-ruby-agent/pull/2378), and other gems did something like that as well:
* https://github.com/rack/rack/pull/2110
* https://github.com/rubocop/rubocop/pull/12313
* …

Remove dependency on base64 gem

---

benchmarks/profiler_gc.rb
lib/datadog/core/configuration/settings.rb
lib/datadog/profiling/component.rb
spec/datadog/core/configuration/settings_spec.rb
spec/datadog/profiling/component_spec.rb

This PR turns the Garbage Collection profiling feature on by default.
Specifically it:
1. Introduces a new `c.profiling.advanced.gc_enabled` setting, which defaults to `true` (can also be toggled using the `DD_PROFILING_GC_ENABLED` env var)
2. Deprecates the previous `c.profiling.advanced.force_enable_gc_profiling` setting. This setting only served to turn the feature on, not turn it off, so it no longer makes sense to exist.
3. Does not turn on GC profiling on Rubies affected by https://bugs.ruby-lang.org/issues/18464 . Specifically, GC profiling can now only be turned on in Ruby versions 2.x, 3.1.4+, 3.2.3+ and 3.3+ . This avoids impacting known-buggy Rubies.
We've done through validation that this feature is working nicely and with low …

[PROF-9370] Enable Garbage Collection profiling by default

---

.gitlab/benchmarks.yml

This PR removes the benchmarking configuration for testing GC profiling.
This is because in https://github.com/DataDog/dd-trace-rb/pull/3558 GC profiling was enabled by default and so the `only-profiling` configuration now includes GC profiling (and thus we don't need a separate one).
Remove benchmarking configurations that no longer make sense to have.
N/A
Validate this configuration is no longer tested.

[PROF-9370] Remove separate configuration for benchmarking GC profiling

---

.gitlab/benchmarks.yml
benchmarks/profiler_memory_sample_serialize.rb

Adds knobs to existing memory profile benchmark to allow benchmarks of different heap profiler configurations.
Because heap profiling is stateful, I've had to tweak the benchmark a bit to ensure each run uses an independent profiler. I bumped the benchmark time to try and compensate for any noise this might add.
Understand overheads of heap profiling against allocation alone.
Commands:
```
bundle exec ruby benchmarks/profiler_memory_sample_serialize.rb
HEAP_SAMPLES=true bundle exec ruby benchmarks/profiler_memory_sample_serialize.rb
HEAP_SAMPLES=true HEAP_SIZE=true bundle exec ruby benchmarks/profiler_memory_sample_serialize.rb
RETAIN_EVERY=1 HEAP_SAMPLES=true HEAP_SIZE=true bundle exec ruby …
```

[PROF-8669] Benchmarks for heap profiling

---

lib/datadog/tracing/contrib/action_pack/integration.rb
lib/datadog/tracing/contrib/action_view/integration.rb
lib/datadog/tracing/contrib/active_record/integration.rb
lib/datadog/tracing/contrib/active_support/integration.rb

This PR removes a few circular `require`s in the Rails integrations, like the following example:
```
from ddtrace/lib/datadog.rb:5:in  `<top (required)>'
from ddtrace/lib/datadog.rb:5:in  `require_relative'
from ddtrace/lib/datadog/tracing/contrib.rb:35:in  `<top (required)>'
from ddtrace/lib/datadog/tracing/contrib.rb:35:in  `require_relative'
from ddtrace/lib/datadog/tracing/contrib/action_pack/integration.rb:6:in  `<top (required)>'
from ddtrace/lib/datadog/tracing/contrib/action_pack/integration.rb:6:in  `require_relative'
from ddtrace/lib/datadog/tracing/contrib/rails/integration.rb:7:in  `<top (required)>'
from ddtrace/lib/datadog/tracing/contrib/rails/integration.rb:7:in  `require_relative'
from ddtrace/lib/datadog/tracing/contrib/rails/patcher.rb:5:in …
```

 Rails: Remove circular require 

---

.github/PULL_REQUEST_TEMPLATE.md

Removing reference of Security Design and Guidance team in PR review template as the team no longer exists. We will work with the trace team to understand the requirements of review.

ASEC-131:Remove reference to SDG as the team no longer exists

---

lib/datadog/appsec/event.rb
lib/datadog/core/remote/client/capabilities.rb
lib/datadog/core/remote/transport/http/config.rb
spec/datadog/appsec/event_spec.rb

Use strict base64 encoding. 
MIME-style newlines in the middle of base64 makes for some unhappy results.
Reported case was with compressed data on appsec derivative results (e.g schema), introduced in https://github.com/DataDog/dd-trace-rb/commit/8c52213e047cde29a773714fc304135635d8dedd
This also applies to a few areas like RC capabilities, although the contents was smaller thus not affected (a trailing newline was handled with a `chomp`.
CI covers it (added a non-regression test)

Use strict base64 encoding (no newline)

---

ext/datadog_profiling_native_extension/collectors_cpu_and_wall_time_worker.c
lib/datadog/profiling/collectors/cpu_and_wall_time_worker.rb
sig/datadog/profiling/collectors/cpu_and_wall_time_worker.rbs
spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb

This PR improves the test coverage we have around taking samples in the profiler using signals.
While prototyping something yesterday I was surprised by the discovery that if I commented out triggering profiler samples via a signal:
```c
pthread_kill(owner.owner, SIGPROF);
```
that actually only one test of the test suite failed! (Yay, at least one!)
This is because our tests were *waiting* on a loop, and because most of the time they were waiting, sampling was happening via the idle sampling code path, not via the signal sending code path.
But this is a dangerous state to be in -- we don't want accidental changes to such core logic to not be caught clearly in tests.
Thus, this PR tightens out testing around sampling, to make sure we check for the existence of …

[NO-TICKET] Improve testing coverage for profiler sampling via signals

---

ext/datadog_profiling_native_extension/stack_recorder.c

This PR avoids referencing `rb_gc_force_recycle` on Rubies where this method is a no-op.
This method will be removed in Ruby 3.4
( https://github.com/ruby/ruby/pull/10324 ) so we should stop referencing it.
N/A

[NO-TICKET] Do not reference `rb_gc_force_recycle` on Ruby 3.1+

---

benchmarks/profiler_memory_sample_serialize.rb
ext/datadog_profiling_native_extension/heap_recorder.c
ext/datadog_profiling_native_extension/heap_recorder.h
ext/datadog_profiling_native_extension/stack_recorder.c
spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
spec/datadog/profiling/stack_recorder_spec.rb

Skip updating and serialization of heap samples for objects that were allocated in the current GC epoch/generation. The fact that these objects are still alive is usually just a happy accident from the fact that GC hasn't run yet and thus just add noise when you want to understand long-term heap usage and, more specifically, memory leaks.
In fact, allocation profiles alone can give you a rather accurate description of what the population of age == 0 should look like at any-one time. If no GCs ever ran, allocation profiles would be === to heap profiles as all objects would be technically alive.
* Objects with age == 0 tend to be mostly noise when investigating heap usage.
* Unless GCs occur at intervals <1 minute or you have big memory leaks, …

[PROF-9469] Skip heap samples with age 0

---

ddtrace.gemspec

This PR fixes the workflow `test-head`.
While looking into Ruby 3.4 issue, I found the `test-head` workflow that tries to use the latest ruby version. Upon inspecting further, I noticed that the [builds were not successful due to gemspec parse error](https://github.com/DataDog/dd-trace-rb/actions/runs/8615489955/job/23611138121).
```bash
[!] There was an error parsing `Gemfile`: 
[!] There was an error while loading `ddtrace.gemspec`: syntax error, unexpected ']', expecting 'end' or dummy end - ...ERSION::MAXIMUM_RUBY_VERSION}"]
...                              ^
. Bundler cannot continue.
>                                  "< #{DDTrace::VERSION::MAXIMUM_RUBY_VERSION}"]
. Bundler cannot continue.
```
This is because the …

Fix version range for required_ruby_version

---

lib/datadog/profiling/load_native_extension.rb
spec/datadog/profiling/load_native_extension_spec.rb
vendor/rbs/gem/0/gem.rbs

This PR tweaks our existing logic for loading the profiling native extension to try to find the file in two directories:
1. The lib/ directory
2. The Ruby extensions directory
Previously we would only check 1.
I'll admit I don't 100% understand when one or the other folder gets used.
For instance, on a fresh install of `ddtrace` on my machine I get
```
$ bundle exec gem contents ddtrace | grep so$
.rvm/gems/ruby-3.1.4/gems/ddtrace-1.21.1/lib/datadog_profiling_loader.3.1.4_x86_64-linux.so
.rvm/gems/ruby-3.1.4/gems/ddtrace-1.21.1/lib/datadog_profiling_native_extension.3.1.4_x86_64-linux.so
```
(this is 1., above)
but also...
```
$ find `bundle exec ruby -e "require 'ddtrace'; puts Gem::loaded_specs['ddtrace'].extension_dir"` | grep so$ …
```

[NO-TICKET] Check extension dir as well when loading profiler

---

.github/workflows/release-lib-injection.yml
.gitlab-ci.yml

1. Skip publishing lib injection artifacts for prereleases
2. Tag `latest` from `master`

Skip publishing lib injection artifacts for prereleases

---

gemfiles/ruby_2.5_rails4_mysql2.gemfile.lock
gemfiles/ruby_2.5_rails4_postgres.gemfile.lock
gemfiles/ruby_2.5_rails4_postgres_redis.gemfile.lock
gemfiles/ruby_2.5_rails4_postgres_sidekiq.gemfile.lock
gemfiles/ruby_2.5_rails4_semantic_logger.gemfile.lock
gemfiles/ruby_3.1_multi_rack_app.gemfile.lock
lib/datadog/tracing/correlation.rb
lib/datadog/tracing/trace_operation.rb
lib/datadog/tracing/tracer.rb
spec/datadog/tracing/correlation_spec.rb
spec/datadog/tracing/trace_operation_spec.rb

Inspired by https://github.com/DataDog/dd-trace-rb/pull/3447
This is a performance improvement for correlation object. 
1. Creating correlation object from trace operation (skipping TraceDigest)
2. Improve `version`, `env` and `service` without duplicate in memory

Improve log correlation performance

---

spec/ddtrace/release_gem_spec.rb

Add a test to identify if where is a change for dependencies, which might leads to a broken pipeline for lib injection artifacts
When building lib injection artifacts, we need to include all the dependencies. Dependencies  changes in gemspec could leads to a broken pipeline.

Add spec for dependencies

---

lib/datadog/core/configuration.rb
spec/datadog/core/configuration_spec.rb

Fixes system test failure `Test_Telemetry.test_app_started_is_first_message` for Rails applications that use auto-instrument: https://github.com/DataDog/dd-trace-rb/actions/runs/8703916892/job/23871310217?pr=3591

Fix telemetry app-started event on auto instrument

---

CHANGELOG.md

* Add Agent configuration option: `timeout_seconds`, `uds_path`, and `use_ssl` (#3350)
* Tracing: Add lightweight log correlation generation (#3486)
* Tracing: Add span links (#3546)
* Tracing: Add `span_remote` field to `TraceDigest` (#3516)
* Tracing: Add `_dd.parent_id` to `tracestate` (#3488)
* Tracing: Allow `RateSampler` with zero sampling rate (#3295)
* Grape: Add `on_error` settings (#3370)
* Rename gem from `ddtrace` to `datadog` (#3490)
* Require Ruby `>= 2.5` (#3291)
* Frozen string literals (#3392)
* Startup logs emit when reconfigures (#3441)
* Enhance validation for configuration (#3332, #3326)
* Tracing: Propagation style configuration becomes case-insensitive (#3299)
* Tracing: Return string for `#trace_id` and `#span_id` from `Correlation::Identifier` (#3322)
* …

Update changelog with release 2.0.0.beta2

---

docs/UpgradeGuide2.md
lib/datadog/core/configuration/settings.rb
spec/datadog/core/configuration/settings_spec.rb

This profiler removes a number of profiler settings that have been deprecated for a while.
On the 1.x series, we were keeping these settings around, even though they didn't do anything; for the 2.0 release, we're taking the opportunity to delete them, as, again, they don't do anything.
I've included the needed changes to the upgrade guide as well.
These settings were already not in use, so the only change is really to delete any references to them.

[NO-TICKET] Remove deprecated profiler settings

---

ext/datadog_profiling_native_extension/collectors_cpu_and_wall_time_worker.c
ext/datadog_profiling_native_extension/heap_recorder.c
ext/datadog_profiling_native_extension/heap_recorder.h
ext/datadog_profiling_native_extension/ruby_helpers.h
ext/datadog_profiling_native_extension/stack_recorder.c
lib/datadog/profiling/exporter.rb
lib/datadog/profiling/stack_recorder.rb
sig/datadog/profiling/stack_recorder.rbs
spec/datadog/profiling/exporter_spec.rb
spec/datadog/profiling/stack_recorder_spec.rb

Make use of the internal metadata mechanism to ship some statistics about the profile itself and the stack recorder. 
We first introduced this back in https://github.com/DataDog/dd-trace-rb/pull/3429 but that was scoped to worker stats which capture sampling-related statistics. This PR focuses on the serialization side of things + heap recorder if enabled.
Easier understanding of some of the internal ops that are otherwise hard/impossible to gather from the final pprof.
Look at the `event.json` produced by any app being profiled with this PR and notice the extra fields in `internal`:

[PROF-9472] Add recorder_stats and profile_stats to internal metadata

---

lib/datadog/tracing/span_link.rb
sig/datadog/tracing/span_link.rbs
spec/datadog/tracing/span_link_spec.rb
spec/datadog/tracing/transport/serializable_trace_spec.rb

Currently the `SpanLink.trace_flags`  is set using `TraceDigest.trace_flags`. The `trace_flag` field in a trace_digest store sampling decisions propagated by tracecontext distributed headers. Therefore for non-remote spans and spans generated via datadog/b3 distributed tracing headers will have a `trace_flag` of `nil` even when a sampling decision exists. 
`SpanLink.trace_flag` must have one of the following values:
- `nil` If there is NO sampling decision on the linked span
-  `1` If the linked span is sampled
- `0` If the linked span is NOT sampled (span will be dropped by the agent)
Since trace_flag is ONLY a function of sampling priority, we can ignore `TraceDigest.trace_flags` and always use sampling_priority to compute the valid when a span link is …

fix(span_links): ensures trace_flags is consistent with the sampling priority

---

lib/datadog/core/telemetry/emitter.rb
lib/datadog/core/telemetry/http/response.rb
spec/datadog/core/telemetry/emitter_spec.rb

This PR fixes the following debug error log that would happen when enabling debug logging + not having an agent running locally.
```
$ DD_TRACE_DEBUG=true bundle exec ruby -e "require 'datadog'; Datadog.configure {}; sleep 1"
...
DEBUG -- datadog: [datadog] (lib/datadog/core/telemetry/http/adapters/net.rb:47:in `rescue in post') Unable to send telemetry event to agent: Failed to open TCP connection to 127.0.0.1:8126 (Connection refused - connect(2) for "127.0.0.1" port 8126)
DEBUG -- datadog: [datadog] (lib/datadog/core/telemetry/emitter.rb:32:in `rescue in request') Unable to send telemetry request for event `app-started`: undefined method `code' for Datadog::Core::Telemetry::Http::InternalErrorResponse ok?: unsupported?:, not_found?:, client_error?:, …
```

[NO-TICKET] Fix error during telemetry debug logging attempt

---

docs/Compatibility.md
docs/GettingStarted.md
docs/legacy/Compatibility-v1.md
docs/legacy/GettingStarted-v1.md

- Created new legacy folder to house v1.x content.
- Duplicated content from release branch, so it reflects v1 and not v2.
- Added warning banners indicating that this is for the old gem. Link to latest docs for v2 datadog gem.
- In a separate [Datadog/documentation PR](https://github.com/DataDog/documentation/pull/23005), I'm single sourcing this content to the docs site.

Create Folder for Legacy v1.x Documentation

---

lib/datadog/tracing/component.rb
sig/datadog/tracing/component.rbs
spec/datadog/tracing/component_spec.rb

This PR fixes that repeated log entries for `DATADOG CONFIGURATION - TRACING` they were introduced in 2.0.
Running the following command before and after this change we will allow to see that the repeated log entries are gone:
```console
DD_TRACE_AGENT_TIMEOUT_SECONDS=1 bundle exec ruby -e "require 'datadog'; Datadog::Tracing.trace('a'){}; sleep 2; Datadog::Tracing.trace('a'){}; sleep 2"
```

Fix environment logger repeated entries

---

ext/datadog_profiling_native_extension/collectors_thread_context.c
spec/datadog/profiling/collectors/thread_context_spec.rb

This PR backports https://github.com/DataDog/dd-trace-rb/pull/3610 to the 1.x-stable branch. See original PR for more details.
We want to release this profiling feature in the 1.x-stable series as well.
I cherry-picked the upstream commits with no other changes.
See original PR for details.

Backport "[PROF-9650] Enable endpoint profiling for Sidekiq and similar background job processors" to 1.x-stable

---

ext/datadog_profiling_native_extension/collectors_cpu_and_wall_time_worker.c
ext/datadog_profiling_native_extension/heap_recorder.c
ext/datadog_profiling_native_extension/heap_recorder.h
ext/datadog_profiling_native_extension/ruby_helpers.h
ext/datadog_profiling_native_extension/stack_recorder.c
lib/datadog/profiling/exporter.rb
lib/datadog/profiling/stack_recorder.rb
sig/datadog/profiling/stack_recorder.rbs
spec/datadog/profiling/exporter_spec.rb
spec/datadog/profiling/stack_recorder_spec.rb

This PR backports https://github.com/DataDog/dd-trace-rb/pull/3583 to the 1.x-stable branch. See original PR for more details.
This tweak also makes sense to apply on the 1.x-stable series.
I cherry-picked the upstream commits with no other changes.
See original PR for details.

Backport "[PROF-9472] Add recorder_stats and profile_stats to internal metadata" to 1.x-stable

---

lib/datadog/core/telemetry/emitter.rb
lib/datadog/core/telemetry/http/response.rb
spec/datadog/core/telemetry/emitter_spec.rb

This PR backports https://github.com/DataDog/dd-trace-rb/pull/3617 to the 1.x-stable branch. See original PR for more details.
This fix also makes sense to apply on the 1.x-stable series.
I cherry-picked the upstream commit with no other changes.
See original PR for details.

Backport "[NO-TICKET] Fix error during telemetry debug logging attempt" to 1.x-stable

---

ext/datadog_profiling_native_extension/NativeExtensionDesign.md
ext/datadog_profiling_native_extension/extconf.rb
ext/datadog_profiling_native_extension/native_extension_helpers.rb
ext/datadog_profiling_native_extension/private_vm_api_access.c
ext/datadog_profiling_native_extension/ruby_helpers.h
integration/apps/rack/app/acme.rb
integration/apps/rack/app/resque_background_job.rb
integration/apps/rack/app/sidekiq_background_job.rb
integration/apps/rack/spec/integration/basic_spec.rb
integration/apps/rails-five/config/initializers/resque.rb
integration/apps/rails-seven/config/initializers/resque.rb
integration/apps/rails-seven/spec/integration/basic_spec.rb
integration/apps/rails-six/config/initializers/resque.rb
integration/apps/rails-six/spec/integration/basic_spec.rb
integration/apps/sinatra2-classic/Gemfile
integration/apps/sinatra2-classic/app/acme.rb
integration/apps/sinatra2-classic/spec/integration/basic_spec.rb
integration/apps/sinatra2-modular/Gemfile
integration/apps/sinatra2-modular/app/health.rb
integration/apps/sinatra2-modular/spec/integration/basic_spec.rb
integration/images/include/build_datadog_profiling_native_extension.rb
lib/datadog/profiling/component.rb
spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
spec/datadog/profiling/collectors/stack_spec.rb
spec/datadog/profiling/collectors/thread_context_spec.rb
spec/datadog/profiling/component_spec.rb
spec/datadog/profiling/native_extension_helpers_spec.rb
spec/datadog/profiling/scheduler_spec.rb
spec/datadog/profiling/spec_helper.rb

This PR removes the code for supporting Ruby 2.3 and 2.4 from the profiler.
This matches the minimum version for the datadog gem which is now Ruby 2.5 (e.g. this was dead code -- you couldn't actually use it anymore).
We opted not to do this earlier on in the 2.x release cycle, but as we are getting close to the final release, and given that the diff is not that big, I decided to go ahead and do it now.
In some cases, because a conditional was removed, indentation was adjusted. I suggest reviewing this diff with "Hide whitespace" turned on (or `-w` in the git cli).
In ddtrace 1.x, the gem supported Ruby 2.1+ whereas the profiler was supporting 2.3+. We still had some awkward support code to deal with this difference, which I …

[NO-TICKET] Remove profiler support for Ruby 2.3 and 2.4

---

.github/CODEOWNERS

The IDM team would like to have a clean notification inbox when it comes to code reviews in `dd-trace-rb`. This is being done across all languages.

Add apm-idm-ruby as CODEOWNERS to contrib

---

lib-injection/host_inject.rb

* Fix adding gem mechanism in host injection by invoking with `Bundler::CLI::Add`. 
* This reduce the overhead that previously need to resolved multiple times for each dependency.

Fix bundle add mechanism 

---

lib/datadog/tracing/contrib/active_record/configuration/resolver.rb
lib/datadog/tracing/contrib/active_record/integration.rb
lib/datadog/tracing/contrib/configuration/resolver.rb
spec/datadog/tracing/contrib/active_record/configuration/resolver_spec.rb
spec/datadog/tracing/contrib/active_record/instantiation_spec.rb
spec/datadog/tracing/contrib/configuration/resolver_spec.rb

This PR adds caching to the ActiveRecord configuration resolver, resulting in only the first request with a specific ActiveRecord configuration performing the Rails resolution lookup.
This virtually eliminates the for ActiveRecord configuration resolution. This will improve the performance on every ActiveRecord span.
I can provide better performance numbers when this change has had a chance to run in our internal testing environment.
#3581
All changes are covered by testing.

Cache ActiveRecord configuration resolver

---

.gitlab/install_datadog_deps.rb
lib-injection/host_inject.rb

**Why**
Implementation in https://github.com/DataDog/dd-trace-rb/pull/3638 has caveats.
Edge case: When community releases a new version of dependency. The dependencies bundled together become outdated. Hence the Bundler's `Add` command would resolve with the latest version which the artifact does not include. 
This scenario can be mimicked by preparing an older version of dependency.
1. Fix PR reverts the implementation in https://github.com/DataDog/dd-trace-rb/pull/3638 
2. Run bundle cli commands with updated GEM_PATH to resolve correctly.
3. Delay in propagating ENV after successful injection.

Fix lib injection with outdated dependencies

---

lib/datadog.rb
lib/datadog/core/configuration/components.rb
lib/datadog/debugger.rb
lib/datadog/debugger/component.rb
lib/datadog/debugger/configuration.rb
lib/datadog/debugger/configuration/settings.rb
lib/datadog/debugger/extensions.rb
sig/datadog/core/configuration/settings.rbs
sig/datadog/debugger.rbs
sig/datadog/debugger/component.rbs
sig/datadog/debugger/configuration.rbs
sig/datadog/debugger/configuration/settings.rbs
sig/datadog/debugger/extensions.rbs
spec/datadog/core/configuration/components_spec.rb
spec/datadog/debugger/component_spec.rb
spec/datadog/debugger/configuration/settings_spec.rb

This adds a component for Dynamic Instrumentation / Live Debugger using AppSec component as the model.
Included is a 'debugger' setting to turn the component on, and handling of DD_DYNAMIC_INSTRUMENTATION_ENABLED environment variable which is equivalent to the setting.
The component is not used by anything at this point and is/will remain off by default.
Unit tests only at this time.

DEBUG-2334 Add Debugger component

---

.gitlab/install_datadog_deps.rb

From https://github.com/DataDog/dd-trace-rb/pull/3641
Forgot to remove before merging.

Ship with latest msgpack for lib injection artifacts

---

lib/datadog/core/remote/client.rb
lib/datadog/core/remote/dispatcher.rb
sig/datadog/core/remote/dispatcher.rbs
spec/datadog/core/remote/dispatcher_spec.rb

There is only one call site of Dispatcher and the caller immediately copies the receivers into the newly created dispatcher.
Instead pass the dispatchers directly into the constructor to make it clear that dispatchers are part of initialization.
- More clearly convey what is needed to initialize dispatcher
- Encapsulate data better (no more mutating receivers)
Unit tests

DEBUG-2334 Change Dispatcher constructor to directly accept receivers

---

lib/datadog/appsec/contrib/devise/tracking.rb
shell.nix

Make appsec work without tracing
Fixes https://github.com/DataDog/dd-trace-rb/issues/3564
Probably will need to be backported.

Make appsec work without tracing

---

lib/datadog/opentelemetry/sdk/span_processor.rb
spec/datadog/opentelemetry_spec.rb

This PR fixes an issue with the tracing OpenTelemetry integration where OpenTelemetry span `attributes` were processed and converted to Datadog span tags, but not correctly converted back into a Hash object; they were left as an Array of key/value pairs.
Because an Array of key/value pairs is not what `Tracing.trace(tags:)` expects, this should have failed much earlier. But it actually has a chance of successfully setting span tags in the scenario that:
1. There are no global `DD_TAGS`. In this case, we don't need to merge the existing tag array with the provided Array of key/value pairs. https://github.com/DataDog/dd-trace-rb/blob/7ca30420a6315323343f9f1d9a895f53078c6ca3/lib/datadog/tracing/tracer.rb#L423
2. `set_tags` iterates over the provided tags in a way …

OpenTelemetry:Fix attribute merge with Datadog tags

---

.circleci/images/primary/Dockerfile-jruby-9.4.7.0
.github/workflows/build-ruby.yml
docker-compose.yml

Updates outdated jruby-9.4 image to JRuby version version 9.4.7.0 by:
- using eclipse-temurin:11-jammy as base image
- installing 9.4.7.0 from maven
- also it updates jruby image version in docker-compose
datadog-ci pipelines fail because of jruby incompatibility with latest versions of gems:
https://app.circleci.com/pipelines/github/DataDog/datadog-ci-rb?branch=main
`docker buildx build . -f Dockerfile-jruby-9.4.7.0 -t ghcr.io/datadog/dd-trace-rb/jruby:9.4.7.0-dd`
`docker compose run --rm tracer-jruby-9.4 /bin/bash`
`bundle exec rake ci`

build jruby-9.4 image with 9.4.7.0 version

---

.github/workflows/test-macos.yaml

**What?**
MacOS test is failing due to dependencies
```
/Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/runtime.rb:308:in `check_for_activated_spec!': You have already activated strscan 1.0.3, but your Gemfile requires strscan 3.1.0. Since strscan is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports strscan as a default gem. (Gem::LoadError)
from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/runtime.rb:25:in `block in setup'
from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/spec_set.rb:155:in `each'
from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems …
```

Remove bundler cache in for `setup-ruby` 

---

.circleci/images/primary/Dockerfile-jruby-9.4.7.0
.github/workflows/build-ruby.yml
docker-compose.yml

Backports https://github.com/DataDog/dd-trace-rb/pull/3654 to 1.x-stable

Backport "Build jruby-9.4 image with 9.4.7.0 version"

---

.gitlab-ci.yml
.gitlab/check_gem_presence.rb
.gitlab/prepare_image_destinations.rb

This PR backports https://github.com/DataDog/dd-trace-rb/pull/3643 to `1.x-stable` 
In addition, it does not tagged `latest` on this branch

Backport adding `latest_major` and `latest_minor` tags

---

.gitlab-ci.yml
.gitlab/check_gem_presence.rb
.gitlab/prepare_image_destinations.rb

**What**
Currently, images for docker init container are tagged with the semantic version (ie: `v2.1.1`) and `latest`. 
This PR would add 2 more tags
1. latest major, ie: `v2`
2. latest minor, ie: `v2.1`

Implement `latest_major` and `lastest_minor` tag for docker init container

---

lib/datadog/tracing/correlation.rb
spec/datadog/tracing/correlation_spec.rb

Extract trace id format for log correlation 

---

.github/labeler.yml

This PR updates the [Labeler GitHub bot](https://github.com/DataDog/dd-trace-rb/blob/master/.github/workflows/pull-request-labeler.yml) to tag some new directories created by recent products.
Having the correct labels help us craft a rich changelog file.

GitHub: Update Labeler bot with new products

---

docs/OpenTelemetry.md

The OpenTelemetry has been considered stable for some time now.

Remove experimental warning from OpenTelemetry.md

---

.gitlab-ci.yml
.gitlab/Dockerfile-2.7.8
.gitlab/Dockerfile-3.0.6
.gitlab/Dockerfile-3.1.4
.gitlab/Dockerfile-3.2.2
.gitlab/install_datadog_deps.rb
.vscode/settings.json
spec/datadog/release_gem_spec.rb

`ffi` 1.17.0 ships binary gems for many platforms, which breaks our lib injection artifact pipeline.
https://github.com/ffi/ffi/blob/master/CHANGELOG.md#1170rc1--2024-04-08
The error was first discovered with 
```
ffi-1.17.0-x86_64-linux-musl requires rubygems version >= 3.3.22, which is
incompatible with the current version, 3.1.6
```
After updating the gem version in our images. Lib injection artifacts can be built but the injection won't work with error 
```
Jun 04 12:19:47 ip-172-29-134-46 bash[26468]: /var/lib/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/definition.rb:507:in `materialize': Could not find ffi-1.17.0 in locally installed gems (Bundler::GemNotFound)
```
To mitigate this: lock `ffi` version with `1.16.3` for now

Fix ffi version 1.16.3 in lib injection artifacts 

---

ddtrace.gemspec
spec/ddtrace/release_gem_spec.rb

Update gemspec with versioned uri 
* changelog_uri
* source_code_uri

Update gemspec with `source_code_uri` 

---

README.md

Points to the 2.x guide instead of the 1.x guide.

Update UpgradeGuide in README.md

---

.github/workflows/test-yjit.yaml

Ruby 3.3 has already been released last year and has mayn improvement changes on yjit.
Thus, I added Ruby 3.3 to matrix test target in test-yjit.
https://github.com/ruby/ruby/blob/029d92b8988d26955d0622f0cbb8ef3213200749/doc/NEWS/NEWS-3.3.0.md?plain=1#L401

Add Ruby 3.3 to matrix target in test-yjit

---

spec/ddtrace/release_gem_spec.rb

Update tests to allow different destination for `allowed_push_host`, which is overwritten by automated scripts

Update spec for allowed_push_host for different destination

---

datadog.gemspec
spec/datadog/release_gem_spec.rb

See #3684
If you compare https://rubygems.org/gems/datadog and https://rubygems.org/gems/ddtrace you will notice that `datadog` is missing the GitHub star count, and the "Source Code" link. Right now you can only go to source through the "Changelog" link. This should fix that, though the GitHub badge may depend on `spec.homepage`, not entirely sure. Either way, a bit better than now.

Include `source_code_uri` in gemspec, version `changelog_uri`

---

ext/datadog_profiling_native_extension/extconf.rb
ext/datadog_profiling_native_extension/native_extension_helpers.rb
spec/datadog/profiling/native_extension_helpers_spec.rb

This PR is a follow-up to
https://github.com/DataDog/dd-trace-rb/pull/3582 .
In that PR, we fixed loading the profiling native extension so that it could be loaded from the Ruby extensions directory (see the original PR for more details).
It turns out this was not enough! Specifically, the customer reported that they saw the following error
> Profiling was requested but is not supported, profiling disabled: There was an error loading the profiling
> native extension due to 'RuntimeError Failure to load datadog_profiling_native_extension.3.2.2_x86_64-linux
> due to libdatadog_profiling.so: cannot open shared object file: No such file or directory
Specifically, what this message tells is that we're finding the profiling native extension BUT it's failing to load …

[PROF-9926] Fix rpath for linking to libdatadog when loading from extension dir

---

spec/datadog/profiling/crashtracker_spec.rb

This PR adds an additional test case to the profiling crashtracker as discussed in
https://github.com/DataDog/dd-trace-rb/pull/3384#discussion_r1595866807 (thanks @lloeki for the suggestion).
Improve test coverage for the feature.
The diff looks more noiser than it is because of whitespace changes, I recommend reviewing this PR without them.
Check that the new test passes!

[NO-TICKET] Minor: Use fiddle to simulate crash in spec

---

ext/datadog_profiling_native_extension/extconf.rb
ext/datadog_profiling_native_extension/native_extension_helpers.rb
spec/datadog/profiling/native_extension_helpers_spec.rb

This is a cherry-pick of #3683 which was first applied to the 1.x-stable branch. See that PR for details.
The diff is slightly different in the spec file since 1.x-stable needed a few tweaks to support older Rubies, which 2.x doesn't need. Everything else is the same.
Fix the rpath issue.
N/A
See #3683 && and additional integration test for this was added on https://github.com/DataDog/prof-correctness/pull/39 .

[PROF-9926] Fix rpath for linking to libdatadog when loading from extension dir (cherry-pick from 1.x-stable)

---

lib/datadog/opentelemetry/sdk/propagator.rb
lib/datadog/opentelemetry/sdk/span_processor.rb
lib/datadog/tracing.rb
lib/datadog/tracing/span_operation.rb
lib/datadog/tracing/trace_operation.rb
lib/datadog/tracing/tracer.rb
spec/datadog/opentelemetry_spec.rb
spec/datadog/profiling/collectors/thread_context_spec.rb
spec/datadog/profiling/spec_helper.rb
spec/datadog/tracing/span_operation_spec.rb
spec/datadog/tracing_spec.rb

- Ensures span_ids and trace_ids are encoded/decoded (integer <-> bytes) in a manner that is [consistent with the OpenTelemetry API](https://github.com/open-telemetry/opentelemetry-ruby/blob/5b2cc8ffe7614c27fd69f0b40d34368f0c06ff53/api/lib/opentelemetry/trace/span_context.rb#L41-L50)
- Ensures 128bit trace_ids are not truncated to 64bits in the OpenTelemetry propagator
- Ensures OpenTelemetry spans generate a corresponding Datadog span with the same Span ID and TraceID. This ensures OtelSpan.context returns the expected value. Regression test: https://github.com/DataDog/system-tests/pull/2548

fix: ensure the correct ids are serialized and propagated

---

lib/datadog/core/telemetry/event.rb
lib/datadog/core/telemetry/metric.rb
sig/datadog/core/telemetry/event.rbs
sig/datadog/core/telemetry/metric.rbs
spec/datadog/core/telemetry/event_spec.rb
spec/datadog/core/telemetry/metric_spec.rb

This PR is a first step towards full metrics support for internal Datadog telemetry. 
It handles data model for the future metrics implementation:
- Adds `generate-metrics` and `distributions` events to telemetry
- Adds Ruby classes for every metric type we are going to support
This PR does not handle (subject for subsequent PRs):
- metrics buffering in memory
- multi-threaded synchronization
- sending metrics events to the backend
Add telemetry metrics support in bite-sized and digestible fashion.
Pay attention to `#track` method in each of the metrics implementations: this is the aggregations logic that is different for every metric type.
Only unit tests currently.

[SDTEST-409] Telemetry metrics data model

---

lib-injection/Dockerfile

Backport https://github.com/DataDog/dd-trace-rb/pull/3665 to address https://github.com/advisories/GHSA-xw78-pcr6-wrg8.

chore(lib-injection): update base image to alpine 3.20

---

.gitlab-ci.yml
.gitlab/build-oci-package.sh
.gitlab/onboarding_tests.yml

Backports #3662 so we can have OCI builds for 1.X
Make sure CI setup in 1.x-stable stays in good shape.
N/A
If Gitlab CI is green then we are good

backport(OCI): Backport OCI build (#3662) in 1.x-stable

---

lib-injection/host_inject.rb

This PR adds some guard rails for host injection
1. Checking  Ruby runtime
2. Checking Ruby platform
3. Send telemetry with the provided executable from `ENV['DD_TELEMETRY_FORWARDER_PATH']`
In additionally, 
1. Fix false positive result while checking whether the dependency exists in the bundle
2. Write to another Gemfile instead of the existing Gemfile and swap the bundled Gemfile in order to make lib injection transactional to prevent corrupted file.

Injection guard rails

---

lib/datadog/core/telemetry/worker.rb
spec/datadog/core/telemetry/worker_spec.rb

Fix deadlock issue that was happening in telemetry component when stopping the Datadog context right after start.
The reason for the deadlock was this overridden `#stop` method:
```ruby
def stop(force_stop = false, timeout = @shutdown_timeout)
buffer.close if running?
flush_events(dequeue) if work_pending?
super
end
```
This method is called by the main thread when `Component#shutdown!` is called: it tries to acquire TELEMETRY_STARTED_ONCE lock possibly already acquired by a telemetry worker, which with some unfortunate timing could cause deadlock. I added this `#flush_events` call to ensure that pending events in the queue are flushed before worker is stopped (it was not happening for a reason unknown to me).
It turned out that Worker with `Core::Workers::Queue` …

[SDTEST-409] fix deadlock issue: don't flush_events in main thread when calling stop, override #work_pending? instead

---

CHANGELOG.md
ddtrace.gemspec
spec/ddtrace/release_gem_spec.rb

1. Add post_install_message in gemspec
2. Update unrelease comparison in changelog

Add post_install_message in gemspec

---

lib/datadog/profiling/component.rb
spec/datadog/profiling/component_spec.rb
vendor/rbs/passenger/0/passenger.rbs

In https://github.com/DataDog/dd-trace-rb/pull/2978 because of an incompatibility with Phusion Passenger, we added autodetection code to enable the "no signals" workaround when this web server is in use.
This code was later extended in https://github.com/DataDog/dd-trace-rb/pull/3280 once an upstream fix was released, so that the "no signals" workaround was only applied on old Passenger versions.
But in https://github.com/DataDog/dd-trace-rb/issues/3721 we got a report that our version detection code did not work correctly in setups where Passenger was not installed via `Gemfile`/`gems.rb`.
This PR fixes the version detection in these situations.
Make sure the "no signals" workaround does not get enabled in setups where it does not need to be. …

[PROF-10015] Fix Phusion Passenger detection when not in `Gemfile`/`gems.rb`

---

lib/datadog/core/telemetry/event.rb
lib/datadog/core/telemetry/request.rb
lib/datadog/core/telemetry/worker.rb
sig/datadog/core/telemetry/emitter.rbs
sig/datadog/core/telemetry/event.rbs
spec/datadog/core/telemetry/event_spec.rb
spec/datadog/core/telemetry/worker_spec.rb

Optimises telemetry events sending by sending them in batches using `message-batch` event type.
I expect the number of telemetry events to grow as soon as products start using metrics. We can save time by batching the list of events into a single event.
System tests pass for telemetry events.
Logs from rails app with DD_TRACE_DEBUG=1:
```bash
D, [2024-07-01T16:08:58.970222 #20478] DEBUG -- datadog: [datadog] (/Users/andrey.marchenko/p/dd-trace-rb/lib/datadog/core/telemetry/worker.rb:88:in `flush_events') Sending 2 telemetry events
D, [2024-07-01T16:08:59.137402 #20478] DEBUG -- datadog: [datadog] (/Users/andrey.marchenko/p/dd-trace-rb/lib/datadog/core/telemetry/emitter.rb:29:in `request') Telemetry sent for event …
```

[SDTEST-409] Send telemetry events in batches

---

docs/UpgradeGuide2.md

Fix a small typo in `UpgradeGuide2.md`
Allow to understand the change of `Datadog::Tracing::Correlation::Identifier`.

Fix a small typo about `Datadog::Tracing::Correlation::Identifier` in UpgradeGuide2.md

---

.github/workflows/datadog-sca.yml
.github/workflows/datadog-static-analysis.yml
sig/datadog/core/environment/git.rbs
spec/datadog/release_gem_spec.rb
static-analysis.datadog.yml

Adds Datadog static analysis and static composition analysis
Dogfooding software delivery tooling and increasing code quality
Here are the issues found:
https://app.datadoghq.com/ci/code-analysis/github.com%2Fdatadog%2Fdd-trace-rb/anmarchenko%2Fdd_sca_sa/e1f1babe0c3221c106960cf60cc853a9dc5eb112/code-vulnerabilities?query=%40git.repository.id%3Agithub.com%2Fdatadog%2Fdd-trace-rb%20%40git.branch%3Aanmarchenko%2Fdd_sca_sa%20%40git.commit.sha%3Ae1f1babe0c3221c106960cf60cc853a9dc5eb112%20%40static_analysis.result.category%3Asecurity%20-%40static_analysis.result.item_type%3Asecret&fromUser=false&index=cicodescan&start=1719929424577&end=1720016245719&paused=false

[NO TICKET] add datadog static analysis and SCA

---

lib/datadog/core/telemetry/metric.rb
lib/datadog/core/telemetry/metrics_collection.rb
lib/datadog/core/telemetry/metrics_manager.rb
sig/datadog/core/telemetry/metric.rbs
sig/datadog/core/telemetry/metrics_collection.rbs
sig/datadog/core/telemetry/metrics_manager.rbs
spec/datadog/core/telemetry/metric_spec.rb
spec/datadog/core/telemetry/metrics_collection_spec.rb
spec/datadog/core/telemetry/metrics_manager_spec.rb

Adds entities to collect metrics and flush them to telemetry events:
- `MetricsCollection` aggregates metrics per **namespace** and on demand flushes them to a queue passed as a param - this is going to be `Telemetry::Worker`. At most 2 events are created on flush: one for metrics, one for distributions. The methods of `MetricsCollection` are synchronized, protecting access to at most one thread at a time.
- `MetricsManager` is a central piece of metrics aggregation: it manages collections, one per namespace. It synchronizes access to a hashmap with all collections, but allows concurrent access to a collection after it's fetched from the map. The method `flush!` locks access to the collections map and flushes each collection in order.
The concerns of managing …

[SDTEST-409] Add metrics management capabilities

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md

This PR adds a quick link to talk to Datadog support as part of the issue creation flow. Of course, folks still can (and are very much encouraged to) file tickets as needed, but often support will be faster and can delve into account specifics to provide better help.
I borrowed this idea from https://github.com/DataDog/test-template/issues/new/choose and you can see it working live in there.
Improve support experience for Ruby users.
I've also added some cool emoji to the existing issue types.
Other than looking at the template repo, I'm not sure if there's a way to see these changes live before we merge them.
But, on the other hand, it's very easy to check and revert, so the risk is very low.

Add quick link to support in issue creation form

---

lib-injection/host_inject.rb

From: https://github.com/DataDog/dd-trace-rb/pull/3676
In the previous PR, I implement `Bundler::CLI::Common.select_spec(gem)` to avoid false positive result. However, this implementation has side effect with loading specs. Causing multiple injection and missing environment variables.
To mitigate this I encapsulate this check in a forked process to prevent side effect.
It is supposed to work with different command variants
```
rails
bin/rails
bundle exec rails
```

Fix lib injection with fork

---

docs/GettingStarted.md
docs/legacy/GettingStarted-v1.md

In https://github.com/DataDog/dd-trace-rb/pull/3761 we fixed a couple of links in our docs. 
That PR was only applied to the release branch, so this PR backports the changes to master.
Make sure that docs fixes are not lost when we release the next `datadog` gem version.
N/A
Look at the docs! :)

Propagate docs fixes from #3761 to master

---

lib/datadog/profiling/collectors/code_provenance.rb

This PR replaces a `Hash#find` with a `Hash#any?` in the Profiler `CodeProvenance` collector.
This seemingly innocuous change actually gets rid of a bunch of memory allocations.
It turns out that when `Hash#find` is being used, Ruby allocates an array to contain the `[key, value]` pair that's passed into the block, for each entry in the hash (on top of a few more objects -- but this is the biggest offender unless the hash is empty/almost empty).
The VM actually has an optimization for a lot of operations, including `Hash#any?` that avoids allocating any extra memory, but because `Hash#find` is actually inherited from `Enumerable`, this optimization does not kick in.
Eliminate unneeded memory allocations.
Here's a very simple …

[NO-TICKET] Optimize CodeProvenance#record_loaded_files to avoid allocations

---

ext/datadog_profiling_native_extension/collectors_stack.c
spec/datadog/profiling/collectors/stack_spec.rb

Rails's ActionView likes to dynamically generate method names with suffixed hashes/ids, resulting in methods with names such as `_app_views_layouts_explore_html_haml__2304485752546535910_211320`.
This makes these stacks not aggregate well, as well as being not-very-useful data.
This PR modifies the stack collector to detect such methods and simplify them by slicing the hash/id suffix.
Improve quality of aggregated flamegraph.
N/A
Change includes test coverage. Also, all of our internal Rails test apps use templates, so by searching by methods with `erb` or `haml` we'll be able to validate they no longer end with the ids.

[PROF-10112] Simplify method names from actionview templates in profiler

---

ddtrace.gemspec

This PR is a follow-up on #3723.
For the 1.23.3 dd-trace-rb release, we included a quite detailed post-install message to tell customers that the new release was out:
```
Thank you for installing ddtrace. We have released our next major version!
As of version 2, `ddtrace` gem has been renamed to `datadog`.
The 1.x series will now only receive maintenance updates for security and critical bug fixes.
To upgrade, please replace gem `ddtrace` with gem `datadog`.
For detailed instructions on migration, see: https://dtdg.co/ruby-v2-upgrade
```
My thinking is -- some customers may not be able to move to 2.x as quickly as they wanted, and thus seeing that message again and again may start to be slightly annoying.
Thus, this PR replaces with with the minimalistic
```
The …
```

Use minimalistic post-install upgrade message

---

spec/datadog/tracing/contrib/active_record/instantiation_spec.rb

Fix leaky db tests
```
Failures:
1) Rails database on record creation with instantiation support is expected to eq 1
Failure/Error: expect(span.get_tag('active_record.instantiation.record_count')).to eq(1)
expected: 1
got: 34.0
(compared using ==)
Finished in 3 minutes 9.6 seconds (files took 6.69 seconds to load)
269 examples, 1 failure, 8 pending
Failed examples:
rspec ./spec/datadog/tracing/contrib/rails/database_spec.rb:79 # Rails database on record creation with instantiation support is expected to eq 1
```
**How to reproduce**
In Jruby 9.4 environment
```bash
echo "--seed 43133" >> .rspec
bundle exec appraisal jruby-9.4-relational_db rake spec:active_record
bundle exec appraisal jruby-9.4-rails61-mysql2 rake spec:rails
```
After the spec task for active …

Fix leaky db test

---

.github/workflows/system-tests.yml

Switch system-tests to python 3.12
System-tests won't support python 3.9 by end of month.

Switch system-tests to python 3.12

---

lib/datadog/core.rb
lib/datadog/core/deprecations.rb
sig/datadog/core.rbs
sig/datadog/core/deprecations.rbs
spec/datadog/core/deprecations_spec.rb
spec/datadog/core_spec.rb

This adds a limiting feature to the `log_deprecation` function. By default, there is no limit. However, if you provide a `key:`, then it will prevent any other message logged with the same key thereafter.
Some deprecated behavior may be on a frequently used path that could produce a lot of noise. Instead of logging every time, or never logging at all, make it possible to warn once.
I extracted the existing `log_deprecation` function into its own module (`Core::Deprecations`) and recomposed it back into the original `Core` module. Now that the deprecation behavior was becoming more sophisticated, I didn't want the `core.rb` file to scope creep; thus I isolated the behavior to its own file and module.
**How to test the …

Add limits to #log_deprecation

---

spec/datadog/profiling/crashtracker_spec.rb

This PR changes the crashtracking specs to use `wait_for` when asserting on the `libdatadog-crashtracking-receiver` process still being alive or not.
While experimenting with moving our test suite to GitHub Actions, this seemed to trigger a lot.
Also, we saw it trigger at least once for CircleCI as well: https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/15402/workflows/d3d6f9ad-7d9f-4845-9f6b-bc92eaf88b74/jobs/563014
Fixes https://github.com/DataDog/ruby-guild/issues/176 .
I'll see if there's something we can improve on the libdatadog side to avoid this flakiness, but let's not live with the flaky specs until we do so.

[NO-TICKET] Switch libdatadog-crashtracking-receiver checks to wait_for

---

ext/datadog_profiling_native_extension/collectors_cpu_and_wall_time_worker.c
ext/datadog_profiling_native_extension/collectors_stack.c
ext/datadog_profiling_native_extension/collectors_thread_context.c
ext/datadog_profiling_native_extension/collectors_thread_context.h
ext/datadog_profiling_native_extension/heap_recorder.c
ext/datadog_profiling_native_extension/heap_recorder.h
ext/datadog_profiling_native_extension/stack_recorder.c
ext/datadog_profiling_native_extension/stack_recorder.h
lib/datadog/profiling/profiler.rb
lib/datadog/profiling/scheduler.rb
sig/datadog/profiling/scheduler.rbs
spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
spec/datadog/profiling/collectors/thread_context_spec.rb
spec/datadog/profiling/profiler_spec.rb
spec/datadog/profiling/scheduler_spec.rb
spec/datadog/profiling/stack_recorder_spec.rb

This PR fixes a corner case issue with the allocation profiler: if too many objects get allocated, we "clamp" the weight of every individual sample (to avoid introducing bias) to a maximum value.
But we previously did not in any way represent the clamping on the profile itself, which meant that the total number of allocations reported by the profiler would be missing any object counts that were clamped.
In practice, we don't expect this to happen very often, as we have a high clamping value `MAX_ALLOC_WEIGHT = 65535` (it's in `collectors_cpu_and_wall_time_worker.c`).
This PR then introduces an extra placeholder sample, when needed, to represent allocations that went over the clamped value.
Thus the total amount of objects allocated reported by the profiler now …

[PROF-10123] Add placeholder for skipped samples in allocation profiler

---

ext/datadog_profiling_native_extension/collectors_stack.c
ext/datadog_profiling_native_extension/collectors_thread_context.c
ext/datadog_profiling_native_extension/stack_recorder.c
ext/datadog_profiling_native_extension/stack_recorder.h
spec/datadog/profiling/collectors/thread_context_spec.rb
spec/datadog/profiling/stack_recorder_spec.rb

This PR extends the allocation profiler to also track the unscaled allocation counts.
Specifically, like other profile types, the allocation profiler assigns a weight to every sample, making it "represent" all the objects that weren't sampled.
For debugging, in corner cases, it comes in handy to know exactly how many samples the profiler observed, and what was the impact of scaling.
As part of preparing the allocation profiler feature for GA, I'm adding this feature so we can use it to confirm the exact sample counts whenever needed.
Note also this is something we do for the cpu/wall-time profiler, where we track the `cpu_or_wall_samples` as an exact count of how many samples were taken (and again, without the weight -- which in the case of those …

[PROF-10125] Track unscaled allocation counts in allocation profiler

---

ext/datadog_profiling_native_extension/collectors_stack.c
spec/datadog/profiling/collectors/stack_spec.rb

This PR is a small fix on top of #3759. In that PR, we added code to detect method names dynamically generated by Rails actionview templates, slicing the parts of the method name that have random ids.
E.g. `_app_views_layouts_explore_html_haml__2304485752546535910_211320` became `_app_views_layouts_explore_html_haml`.
When looking at one of our example applications, I realized that I was seeing methods that ended with both `__number_number` as well as `___number_number` (three vs two underscores), e.g.:
* `_app_views_articles_index_html_erb___2022809201779434309_12900`
* `_app_views_articles_index_html_erb__3816154855874711207_12920`
On closer inspection of the actionview template naming code in https://github.com/rails/rails/blob/4fa56814f18fd3da49c83931fa773caa7 …

[PROF-10112] Also simplify actionview templates with three underscores

---

ext/datadog_profiling_native_extension/collectors_cpu_and_wall_time_worker.c
ext/datadog_profiling_native_extension/collectors_stack.c
ext/datadog_profiling_native_extension/collectors_thread_context.c
ext/datadog_profiling_native_extension/collectors_thread_context.h
ext/datadog_profiling_native_extension/heap_recorder.c
ext/datadog_profiling_native_extension/heap_recorder.h
ext/datadog_profiling_native_extension/stack_recorder.c
ext/datadog_profiling_native_extension/stack_recorder.h
lib/datadog/profiling/profiler.rb
lib/datadog/profiling/scheduler.rb
sig/datadog/profiling/scheduler.rbs
spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
spec/datadog/profiling/collectors/thread_context_spec.rb
spec/datadog/profiling/profiler_spec.rb
spec/datadog/profiling/scheduler_spec.rb
spec/datadog/profiling/stack_recorder_spec.rb

This PR reverts the change from #3760.
While we still want to add this feature, the implementation in #3760 can cause heap profiler to fail with an exception.
This failure also uncovered a few other potential bugs in our error handling code.
Thus, to be on the safe side, and because we want to get a new release out, I'm reverting the whole PR, until I can re-open a fixed version.
Remove blockers from the 2.2.0 release.
This reverts commit 7732142aacd95f78f33c4a7d9e7d0af8067d660d, reversing changes made to ca006e96e9a5bbb40dee78a481329e42dcd57877.

[PROF-3760] Revert "Merge pull request #3760 from DataDog/ivoanjo/prof-10123-placeholder-missing-allocations"

---

lib/datadog/tracing/contrib/active_support/cache/event.rb
lib/datadog/tracing/contrib/active_support/cache/events.rb
lib/datadog/tracing/contrib/active_support/cache/events/cache.rb
lib/datadog/tracing/contrib/active_support/cache/instrumentation.rb
lib/datadog/tracing/contrib/active_support/cache/patcher.rb
lib/datadog/tracing/contrib/active_support/cache/redis.rb
lib/datadog/tracing/contrib/active_support/notifications/event.rb
lib/datadog/tracing/contrib/active_support/notifications/subscriber.rb
lib/datadog/tracing/contrib/active_support/notifications/subscription.rb
sig/datadog/tracing/contrib/active_support/cache/event.rbs
sig/datadog/tracing/contrib/active_support/cache/events.rbs
sig/datadog/tracing/contrib/active_support/cache/events/cache.rbs
sig/datadog/tracing/contrib/active_support/cache/instrumentation.rbs
spec/datadog/tracing/contrib/active_support/notifications/event_spec.rb
spec/datadog/tracing/contrib/active_support/notifications/subscriber_spec.rb
spec/datadog/tracing/contrib/active_support/notifications/subscription_spec.rb
spec/datadog/tracing/contrib/rails/cache_spec.rb
spec/datadog/tracing/contrib/rails/redis_cache_spec.rb

Fixes #3607, fixes #3549, fixes #858
For tracing `ActiveSupport::Cache`, this PR moves away from monkey-patching to subscribing to `ActiveSupport::Notifications` events [emitted by ActiveSupport Caching](https://guides.rubyonrails.org/v7.1/active_support_instrumentation.html#active-support-%E2%80%94-caching).
We are still required to keep some monkey-patching to ensure backwards compatibility, and to support a few specific methods in old versions of Rails.
This improves the maintainability of the instrumentation, given the events we subscribe to are Rails' public APIs.
It is also more consistent across different caching backends (e.g. Redis, Memcached), allowing us to simplify our implementation.
All changes are covered in the test suite.

Use ActiveSupport events to instrument ActiveSupport::Cache

---

.vscode/extensions.json
Appraisals
Gemfile

- Add a `:dev` `Gemfile` group for development-oriented gems.
- Add the `ruby-lsp` gem to that group.
- Remove the gem/group for appraisals.
- Suggest the Ruby LSP VSCode extension for this workspace.
This gem is used by the VSCode `Ruby LSP` extension from Shopify, and possibly other IDEs as well. Having it in the `Gemfile` for development provides a good out-of-the-box experience.
A few other extensions are recommended as well:
- EditorConfig: since we use that
- Steep and RBS: the official extensions
The suggestion should only pop up once and the user is free to install or dismiss.
Using VS Code with the Ruby LSP extension should provide an immediate OOTB experience that uses the LSP.
If not …

Add Ruby LSP support for VSCode (and possibly others)

---

lib/datadog/core.rb
lib/datadog/core/deprecations.rb
sig/datadog/core.rbs
sig/datadog/core/deprecations.rbs
spec/datadog/core/deprecations_spec.rb
spec/datadog/core_spec.rb

Backports #3675 to `1.x-stable`. I intend to rebase #3647 on top of it to leverage the limit feature.

Backport (1.x): Add limits to #log_deprecation

---

lib/datadog/tracing.rb
spec/datadog/tracing_spec.rb

Backport: Return empty log correlation when tracing is disabled #3731 

---

lib/datadog/core/diagnostics/environment_logger.rb
lib/datadog/tracing/diagnostics/environment_logger.rb
spec/datadog/tracing/diagnostics/environment_logger_spec.rb

This PR reduces the amount of logging emitted by default by the tracing environment logger.
It does this by breaking what was previously a single log message -- containing tracing settings and a list of all the loaded intergration settings -- into two:
* One info-level message with tracing settings + list of loaded integrations
* One debug-level message with only the integrations settings
I've also gone ahead and did two small tweaks:
* Omitted the prefix `integration_` from every integration setting, since the whole message is now prefixed with "TRACING INTEGRATIONS" anyway
* Did a few optimizations around the code to gather settings to avoid allocating so many intermediate objects
The main objective of this change is to reduce the logging that …

[NO-TICKET] Move tracing integrations logging under a debug log

---

.gitlab/benchmarks.yml

This PR adds a new benchmarking configuration for testing allocation profiling with `ddprof` enabled.
(As a reminder, `ddprof` is the Datadog native profiler).
The intention is to allow us to use ddprof to profile the Ruby profiler, so we can identify optimization opportunities and validate any changes we make.
N/A
I've tried to test this PR locally using the `bp-runner` tool, but for some reason I get benchmark results, but no profiles. Nevertheless, this change is harmless so I'm thinking of merging this in and seeing if it shows up correctly on the next nightly run.

[PROF-10198] Add benchmark config with allocation profiling + ddprof

---

lib/datadog/appsec/contrib/rack/gateway/request.rb
spec/datadog/appsec/contrib/rack/gateway/request_spec.rb

This fixes a crash when malformed headers are sent (e.g. headers with numbers)
This fixes issue #3782 
`bundle exec appraisal ruby-x.x-rack-x rake spec:appsec:rack`

Fix AppSec crash when parsing integer http headers

---

ext/datadog_profiling_native_extension/collectors_cpu_and_wall_time_worker.c

This PR lowers the profiling internal constant `MAX_ALLOC_WEIGHT` from 65535 to 10000.
This value is used when clamping very high allocation profiling weights.
Aka: Each allocation sample taken by the profiler has a weight assigned to it; this weight is clamped (e.g. limited to) this maximum value. The remaining weight is assigned to a separate "skipped samples" placeholder (see #3792).
Very large weights on samples can produce biased results; by lowering the maximum we reduce the maximum bias that can ever be introduced.
I've gathered data from a number of apps when choosing this value, see <https://docs.google.com/document/d/1lWLB714wlLBBq6T4xZyAc4a5wtWhSmr4-hgiPKeErlA/edit> for details (Datadog-only link, sorry!).
**How to …

[PROF-10124] Lower value used to clamp very high allocation profiling weights

---

ext/datadog_profiling_native_extension/collectors_cpu_and_wall_time_worker.c
lib/datadog/core/configuration/settings.rb
lib/datadog/profiling.rb
lib/datadog/profiling/collectors/cpu_and_wall_time_worker.rb
lib/datadog/profiling/component.rb
sig/datadog/profiling/collectors/cpu_and_wall_time_worker.rbs
spec/datadog/core/configuration/settings_spec.rb
spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
spec/datadog/profiling/component_spec.rb

This PR introduces a new setting for the profiler: `profiling.advanced.allocation_counting_enabled` which controls the profiler allocation counting feature.
This setting is off by default, enabling us to reduce allocation profiling overhead slightly.
We actually used to have this setting back in the ddtrace 1.x series. We introduced it in #2635 and removed it in #3281 -- by tieing it directly to allocation profiling.
I decided to re-introduce it so we can disable this feature by default.
This PR sits atop #3797 because it makes sense to measure both overhead improvements together, but is otherwise completely independent.
Here's the results for running the `profiler_allocation` benchmark:
```
ruby …
```

[PROF-10201] Disable profiler allocation counting feature by default

---

ext/datadog_profiling_native_extension/collectors_cpu_and_wall_time_worker.c
ext/datadog_profiling_native_extension/collectors_stack.c
ext/datadog_profiling_native_extension/collectors_thread_context.c
ext/datadog_profiling_native_extension/collectors_thread_context.h
ext/datadog_profiling_native_extension/heap_recorder.c
ext/datadog_profiling_native_extension/heap_recorder.h
ext/datadog_profiling_native_extension/stack_recorder.c
ext/datadog_profiling_native_extension/stack_recorder.h
lib/datadog/profiling/profiler.rb
lib/datadog/profiling/scheduler.rb
sig/datadog/profiling/scheduler.rbs
spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
spec/datadog/profiling/collectors/thread_context_spec.rb
spec/datadog/profiling/profiler_spec.rb
spec/datadog/profiling/scheduler_spec.rb
spec/datadog/profiling/stack_recorder_spec.rb

This PR fixes a corner case issue with the allocation profiler: if too many objects get allocated, we "clamp" the weight of every individual sample (to avoid introducing bias) to a maximum value.
But we previously did not in any way represent the clamping on the profile itself, which meant that the total number of allocations reported by the profiler would be missing any object counts that were clamped.
In practice, we don't expect this to happen very often, as we have a high clamping value `MAX_ALLOC_WEIGHT = 65535` (it's in `collectors_cpu_and_wall_time_worker.c`).
This PR then introduces an extra placeholder sample, when needed, to represent allocations that went over the clamped value.
Thus the total amount of objects allocated reported by the profiler now …

[PROF-10123] Add placeholder for skipped samples in allocation profiler, second try

---

ext/datadog_profiling_native_extension/collectors_cpu_and_wall_time_worker.c

This PR reduces the allocation profiling overhead by replacing the Ruby tracepoint API with the lower-level `rb_add_event_hook2` API.
The key insight here is that while benchmarking allocation profiling and looking at what the VM was doing, I discovered that tracepoints are just a thin user-friendlier wrapper around the lower-level API.
The lower level API is publicly-available (in "debug.h") but it's listed as "undocumented advanced tracing APIs".
As we're trying to squeeze every bit of performance from the allocation profiling hot-path, it makes sense to make use of the lower-level API.
I'm considering experimenting with moving the tracepoint we use for GC profiling to this lower-level API as well, since that's another …

[PROF-10201] Reduce allocation profiling overhead by replacing tracepoint with lower-level API

---

spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb

This PR [fixes a flaky test](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/15605/workflows/5b32e4bb-155e-4a94-bf8b-980599eaafae/jobs/568892) introduced by #3792:
```
Failures:
1) Datadog::Profiling::Collectors::CpuAndWallTimeWorker#start when allocation profiling is enabled with dynamic_sampling_rate_enabled records skipped allocation samples when weights are clamped
Failure/Error: raise('Wait time exhausted!')
RuntimeError:
Wait time exhausted!
2) Datadog::Profiling::Collectors::CpuAndWallTimeWorker#start when all threads are sleeping (no thread holds the Global VM Lock) is able to sample even when all threads are sleeping
Failure/Error:
expect(simulated_signal_delivery.to_f / trigger_sample_attempts).to (be >= 0.8), \
"Expected at least 80% of …
```

[NO-TICKET] Fix profiler flaky test

---

.gitlab/benchmarks.yml

This PR sets the `DD_SERVICE` and `DD_ENV` for the gitlab benchmark in the benchmarking platform.
While testing a few changes, I realized these benchmarks were running with no name, thus ending up with `gitlab-runner` which is not a very clear name (and makes it hard to know what it is).
To align with the reliability environment (`rp-ruby-gitlab`) I've explicitly set a matching name.
N/A
I've tested this with the `bp-runner`:
> ![image](https://github.com/user-attachments/assets/148e549c-0b4d-4182-93da-361d3fc7e129)

[PROF-10198] Set service/env for GitLab runs in benchmark platform

---

lib-injection/host_inject.rb

In order to minimize side effect of the injection script. Wrap it with a fork.

Fork injection 

---

static-analysis.datadog.yml

This a static analysis check that does not align with our current Rubocop cops, and goes againts the standard Ruby Hash access syntax:

Disable "Consider using fetch on hash key" cop

---

docs/GettingStarted.md

Documents #2012 
Adds documentation, with a workaround, for corrupted log lines created by the combination of Rails' `ActiveSupport::TaggedLogging` and `lograge`.
I plan on also adding dynamic code warnings for this issue.

Add log instructions for Lograge users

---

lib/datadog/tracing/metadata/errors.rb
spec/datadog/tracing/metadata/errors_spec.rb

https://github.com/DataDog/dd-trace-rb/pull/3776 renamed the Error.set_error method to set_error_tags. Renaming a method in the public api is a breaking change. This PR reverts this breaking change and adds deprecation warning.  

fix(errors): revert breaking change

---

lib/datadog/appsec/contrib/graphql/gateway/multiplex.rb
sig/datadog/appsec/contrib/graphql/gateway/multiplex.rbs
spec/datadog/appsec/contrib/graphql/appsec_trace_spec.rb
spec/datadog/appsec/contrib/graphql/integration_test_spec.rb
spec/datadog/tracing/contrib/graphql/support/application.rb
spec/datadog/tracing/contrib/graphql/support/application_schema.rb
vendor/rbs/graphql/0/graphql.rbs

This add support for directive on GraphQL Threats protection
This was missed during development and found using system-tests
This also reorganize the integration tests a bit, and add a custom directive to the test schema.
This includes integration tests accordingly. This can also be tests using this branch of system-tests :
https://github.com/DataDog/system-tests/tree/vpellan/ruby-graphql-threats

Add directives support for graphql appsec

---

.gitlab/benchmarks.yml

This PR tweaks the `ADD_TO_GEMFILE` environment variable for benchmarking configurations where only the profiler should be active to not include `require: 'datadog/auto_instrument'`.
It turns out this change was added in #3614 when we fixed the benchmarks not running. Loading the instrumentation code and then disabling tracing has a measurable performance overhead vs not loading it at all (20% regression of median throughput in high load gitlab tests).
I expect that with this change, the `only-profiling` configuration will reflect historical data we had before the change in #3614.
This is relevant because we use this data as basis for comparison with other profiling features (e.g. allocation) and thus it's important to have a correct baseline. …

[PROF-10128] Fix profiling benchmarking configuration still having auto_instrument overhead

---

.gitlab/benchmarks.yml
lib/datadog/core/configuration/settings.rb
lib/datadog/profiling/component.rb
spec/datadog/core/configuration/settings_spec.rb
spec/datadog/profiling/component_spec.rb

This PR enables the crashtracking telemetry feature by default when the profiler is enabled.
This feature can be disabled using the `DD_PROFILING_EXPERIMENTAL_CRASH_TRACKING_ENABLED` environment variable or the `c.profiling.advanced.experimental_crash_tracking_enabled`  setting via code.
This setting is not very well-named, as the feature is no longer experimental. But as we're actually considering separating crashtracking from profiling, I decided to leave the current setting in place until we can decide where this is going to live, since that's going to influence where the new setting without "experimental" on its name should land.
Crashtracking allows us to identify issues that may otherwise go unnoticed. We've been deploying it on other …

[PROF-10275] Enable crashtracking telemetry by default when profiler is enabled

---

integration/apps/rack/Gemfile

Fix integration test on Ruby 2.5
```
[36mapp_1                 |[0m 
[36mapp_1                 |[0m [1m[31mSome required software is not installed.[0m[37m[40m
[36mapp_1                 |[0m But don't worry, this installer will tell you how to install them.
[36mapp_1                 |[0m [1mPress Enter to continue, or Ctrl-C to abort.[0m[37m[40m
```

Pin passenger version for integration test

---

.gitlab/prepare-oci-package.sh

From
```
~ % docker run -ti --rm ghcr.io/datadog/dd-trace-rb/dd-lib-ruby-init:latest_snapshot sh
/datadog-init $ ls -al package/
total 36
drwxr-xr-x    1 datadog  datadog       4096 Jul 30 20:08 .
drwxr-xr-x    1 root     root          4096 Jul 30 20:08 ..
drwxr-xr-x    1 datadog  datadog       4096 Jul 30 20:07 2.7.0
drwxr-xr-x    1 datadog  datadog       4096 Jul 30 20:08 3.0.0
drwxr-xr-x    1 datadog  datadog       4096 Jul 30 20:08 3.1.0
drwxr-xr-x    1 datadog  datadog       4096 Jul 30 20:08 3.2.0
lrwxrwxrwx    1 datadog  datadog         22 Jul 30 20:08 auto_inject.rb -> sources/host_inject.rb
-rw-r--r--    1 datadog  datadog       7868 Jul 30 20:08 host_inject.rb
-rw-r--r--    1 datadog  datadog         42 Jul 30 20:08 version
/datadog-init $ cat …
```

Fix symlink from injection artifact

---

.gitlab-ci.yml

After publishing docker image for init container, trigger a job to perform injection on various scenarios.

Add vaccine job for injection artifacts

---

lib/datadog/core/utils/at_fork_monkey_patch.rb
spec/datadog/core/utils/at_fork_monkey_patch_spec.rb

This PR solves the long-standing "TODO" we had on the `at_fork` monkey patch where on Ruby 3.1+ there's a VM hook for instrumenting fork operations that avoids us needing to monkey patch `Kernel` and `Object`.
To use the new hook we need to monkey patch `Process._fork` instead (see https://github.com/ruby/ruby/pull/5017 and
https://bugs.ruby-lang.org/issues/17795).
Thus, I've added this monkey patch and disabled patching of `Kernel` and `Object` on Ruby 3.1+.
Avoid monkey patching core classes that no longer need to.
I'm not quite happy with either the AtForkMonkeyPatch or its specs, but I decided to not do a full revamp for now.
TIP: I recommend reviewing this PR with no whitespace in the diff. …

[PROF-10241] Use Process._fork hook in `at_fork` monkey patch on Ruby 3.1+

---

lib/datadog/core/diagnostics/environment_logger.rb
sig/datadog/core/diagnostics/environment_logger.rbs
sig/datadog/core/environment/execution.rbs
spec/datadog/core/diagnostics/environment_logger_spec.rb
spec/datadog/tracing/diagnostics/environment_logger_spec.rb

Fixes #3807
This PR aligns the development environment detection for remote configuration, telemetry and, now, startup logs.
The development environment detection for startup logs now includes test environments and local development environments.

Suppress startup logs in test and development environments

---

lib/datadog/core/utils/at_fork_monkey_patch.rb
lib/datadog/profiling/tasks/setup.rb
spec/datadog/core/utils/at_fork_monkey_patch_spec.rb
spec/datadog/profiling/tasks/setup_spec.rb

This PR fixes an issue that we identified in the
`profiling/tasks/setup_spec.rb` that was triggered by applying the at_fork monkey patch before running that spec.
This issue could be triggered by adding
```ruby
Datadog::Core::Utils::AtForkMonkeyPatch.apply!
```
to the top of the `setup_spec.rb` (before the `RSpec.describe`).
```
Datadog::Profiling::Tasks::Setup
#run
actives the forking extension before setting up the at_fork hooks
only sets up the extensions and hooks once, even across different instances
#setup_at_fork_hooks
when Process#datadog_at_fork is available
sets up an at_fork hook that restarts the profiler (FAILED - 1)
when there is an issue starting the profiler
logs an exception (FAILED - 2)
does not raise any error (FAILED - 3)
when #datadog_at_fork …
```

[PROF-10241] Fix issue in tests by simplifying `at_fork` monkey patch

---

benchmarks/library_gem_loading.rb
benchmarks/profiler_allocation.rb
benchmarks/profiler_gc.rb
benchmarks/profiler_hold_resume_interruptions.rb
benchmarks/profiler_http_transport.rb
benchmarks/profiler_memory_sample_serialize.rb
benchmarks/profiler_sample_loop_v2.rb
benchmarks/profiler_sample_serialize.rb
benchmarks/tracing_trace.rb

This PR tweaks the configuration for benchmark output results to place result files in the current directory the benchmark gets executed from, instead of placing the results in the benchmarks directory.
In #3810 we standardized the results output file name in benchmarks to match the benchmark name.
In that PR, we used `__FILE__` as a prefix. This changed where results are placed: where previously they were placed in the current folder where the benchmarks were run from (often the root of the repo), with this PR, they started getting placed in the benchmarks directory.
This clashes with our `validate_benchmarks_spec.rb` that look for files in those directories, e.g. running a benchmark and then running the test suite will make the test suite fail …

[NO-TICKET] Don't put results in benchmarking folder directly

---

lib/datadog/kit/appsec/events.rb
spec/datadog/kit/appsec/events_spec.rb

Fixes #3840.
This PR fixes a bug when `Datadog::Kit::AppSec::Events.track_login_failure` is raising an `ArgumentError` when `user_id` is not provided and `user_exists` flag is set to false.
[Issue #3840](https://github.com/DataDog/dd-trace-rb/issues/3840)

Make user_id optional for track_login_failure

---

ext/datadog_profiling_native_extension/collectors_discrete_dynamic_sampler.c
ext/datadog_profiling_native_extension/collectors_stack.c
ext/datadog_profiling_native_extension/collectors_stack.h
ext/datadog_profiling_native_extension/collectors_thread_context.c
ext/datadog_profiling_native_extension/datadog_ruby_common.h
ext/datadog_profiling_native_extension/extconf.rb
ext/datadog_profiling_native_extension/heap_recorder.c
ext/datadog_profiling_native_extension/private_vm_api_access.c
ext/datadog_profiling_native_extension/private_vm_api_access.h
ext/libdatadog_api/datadog_ruby_common.h
ext/libdatadog_api/extconf.rb
spec/datadog/profiling/stack_recorder_spec.rb

This PR refactors the way the profiler samples the Ruby stack, and then builds on that refactoring to speed up sampling.
It also opens the door to future speedups once libdatadog allows us to skip re-interning strings, frames and stacks that we know have been sampled before.
Specifically this PR does the following:
1. It tweaks the data that `ddtrace_rb_profile_frames` returns from sampling the Ruby stack so that the stack collector can use cheaper APIs to get the same information as before.
2. It changes the sampling buffer we put stack traces in to be per-thread. This allows us to reuse some of the work we do from sample to sample, in cases where frames on the stack are the same. Thus sampling the same stack over and over will be slightly cheaper.
3. It adds a …

[PROF-10128] Refactor and speed up profiler stack sampling

---

lib/datadog/tracing/contrib/lograge/patcher.rb
spec/datadog/tracing/contrib/lograge/patcher_spec.rb

Closes #2012
This PR emits an error-level log message when the `lograge` gem is used with Rails tagged logging, which is configured by default in Rails since Rails 5.
We can't practically fix the issue here in `dd-trace-rb`, since the issue is a log formatting conflict between `lograge` and `Rails`.
The reason this affects APM Tracing is because it breaks trace-log correlation.
The only alternatives are to either: disable Rails tagged logging; or not use `lograge`.
The investigation and suggest alternatives are well documented here: https://github.com/DataDog/dd-trace-rb/issues/2012#issuecomment-2038438494

 Emit log message for incompatible Lograge setup 

---

ext/datadog_profiling_native_extension/clock_id.h
ext/datadog_profiling_native_extension/clock_id_from_pthread.c
ext/datadog_profiling_native_extension/clock_id_noop.c

* Add missing include to `clock_id_noop.c`.
* Move `ruby.h` include to `clock_id.h` since that file already references `VALUE`.
Fix a compilation error on mac:
```
❯ rake compile                     
/opt/homebrew/bin/gmake install sitearchdir=../../../../lib sitelibdir=../../../../lib target_prefix=
compiling ../../../../ext/datadog_profiling_native_extension/clock_id_from_pthread.c
compiling ../../../../ext/datadog_profiling_native_extension/clock_id_noop.c
../../../../ext/datadog_profiling_native_extension/clock_id_noop.c:14:43: error: unknown type name 'DDTRACE_UNUSED'
thread_cpu_time_id thread_cpu_time_id_for(DDTRACE_UNUSED VALUE _thread) {
^
../../../../ext/datadog_profiling_native_extension/clock_id_noop.c:14:64: error: expected ')' …
```

Add missing includes to fix build and LSP errors on Mac

---

lib/datadog/core/crashtracking/tag_builder.rb
spec/datadog/core/crashtracking/tag_builder_spec.rb

This PR adds the following tags to crashtracker reports:
* language
* ~~severity~~
* ~~profiler_version~~ library_version
~~Severity is similar to what we do in Python in
https://github.com/DataDog/dd-trace-py/pull/10199 .~~ Update: We decided to not go with this one for now.
The other two tags seem redundant, but right now if we don't pass them as tags to libdatadog they don't get picked up correctly.
In the future, this won't be needed by libdatadog, but for now this makes it easier for us to analyze reported crashes.
Improve crash reports.
N/A
Change includes test coverage.
For Datadog folks: With this branch, if you crash Ruby, you'll see the crash show up in the usual dashboards. Crashes were …

[PROF-10241] Add extra tags to crash reports

---

spec/datadog/profiling/stack_recorder_spec.rb

This PR is a second attempt at a workaround for this flaky spec:
* https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/15742/workflows/9da2d5f2-3a15-4659-9643-219f52b56b5d/jobs/572636
* https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/15799/workflows/983ab3f8-2b83-4fd7-b0bc-43f257b924c3/jobs/574214
* https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/15817/workflows/e67525cd-b5d3-435e-9eb2-ee345a8a344d/jobs/574731
```
Failures:
1) Datadog::Profiling::StackRecorder#stats with heap profiling enabled includes heap recorder snapshot
Failure/Error:
expect(stack_recorder.stats).to match(
hash_including(
:heap_recorder_snapshot => hash_including(
:num_object_records => live_heap_samples + age0_heap_samples,
:num_heap_records => 2, …
```

[PROF-10128] Workaround heap profiling flaky spec on Ruby 3.3+

---

lib/datadog/core/telemetry/component.rb
lib/datadog/core/telemetry/event.rb
lib/datadog/core/telemetry/logging.rb
sig/datadog/core/telemetry/component.rbs
sig/datadog/core/telemetry/event.rbs
sig/datadog/core/telemetry/logging.rbs
spec/datadog/core/telemetry/component_spec.rb
spec/datadog/core/telemetry/event_spec.rb
spec/datadog/core/telemetry/logging_spec.rb

This PR enables developer to send telemetry logs for internal observability.

Implement telemetry log

---

ext/datadog_profiling_native_extension/collectors_discrete_dynamic_sampler.c
ext/datadog_profiling_native_extension/datadog_ruby_common.h
ext/datadog_profiling_native_extension/helpers.h
ext/datadog_profiling_native_extension/http_transport.c
ext/datadog_profiling_native_extension/libdatadog_helpers.h
ext/datadog_profiling_native_extension/private_vm_api_access.c
ext/datadog_profiling_native_extension/time_helpers.h
ext/libdatadog_api/datadog_ruby_common.h
ext/libdatadog_api/extconf.rb

This PR makes sure that every `inline` helper in the profile is marked as `static inline`.
As documented in <https://gcc.gnu.org/onlinedocs/gcc/Inline.html#Inline>:
> When a function is both inline and static, if all calls to the function
> are integrated into the caller, and the function’s address is never
> used, then the function’s own assembler code is never referenced.
this is different from just `inline`:
> When an inline function is not static, then the compiler must assume
> that there may be calls from other source files; since a global
> symbol can be defined only once in any program, the function must not
> be defined in the other source files, so the calls therein cannot
> be integrated. Therefore, a non-static inline function is always
> compiled on …

[NO-TICKET] Fix profiler `inline` helpers not working when optimization disabled

---

lib/datadog/tracing/pipeline/span_filter.rb

The docstring was claiming that a truthy value from the filter block keeps the span, but in fact it's the other way around, a truthy value drops the span.
Found this by accident, and given that "truthy to filter" is already unintuitive enough, having the docs lie doesn't exactly help :D
Nope.
Visual review should suffice.

Fix confusion in the SpanFilter docstring

---

.github/workflows/system-tests.yml

Add `persist-credentials: false` to checkout jobs in system-tests workflow

ci: disable persist-credentials for actions/checkout in system-tests

---

lib/datadog/appsec/configuration/settings.rb

This PR updates default obfuscation regexps for AppSec.
RFC "AppSec Events - Sensitive Data Obfuscation"
None
Send AppSec events in a local environment with key/value that has to be obfuscated.

Update default AppSec obfuscation regex

---

lib/datadog/core/telemetry/logging.rb
lib/datadog/profiling/component.rb
lib/datadog/profiling/http_transport.rb
lib/datadog/profiling/scheduler.rb
lib/datadog/profiling/stack_recorder.rb
sig/datadog/core/telemetry/logging.rbs
spec/datadog/core/telemetry/logging_spec.rb
spec/datadog/profiling/http_transport_spec.rb
spec/datadog/profiling/scheduler_spec.rb
spec/datadog/profiling/stack_recorder_spec.rb

Report internal error via telemetry logs for Profiling

Send telemetry logs for Profiling 

---

.github/workflows/test-memory-leaks.yaml
Gemfile
Rakefile
benchmarks/profiler_gc.rb
ext/datadog_profiling_native_extension/collectors_stack.c
ext/datadog_profiling_native_extension/collectors_thread_context.c
ext/datadog_profiling_native_extension/private_vm_api_access.c
spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
spec/datadog/profiling/collectors/thread_context_spec.rb
spec/datadog/profiling/native_extension_spec.rb
spec/datadog/profiling/validate_benchmarks_spec.rb
spec/datadog/release_gem_spec.rb
suppressions/ruby-3.4.supp

The [`ruby_memcheck`](https://github.com/Shopify/ruby_memcheck) gem provides a Ruby-specific user-friendly wrapper around valgrind.
This PR sets up this gem to run the profiling test suite in CI with this gem, thus helping us catch memory leaks during development.
It also fixes a few memory leaks:
* We were leaking a small amount of memory when the Ruby process forked with the profiler enabled (we cleaned up the per-thread context hashtable, but did not call free on the things it contained)
* The stack collector native test code was a bit YOLO with exceptions and would not release memory in a few cases when exceptions were raised. This code was only used for running specs, so it did not impact actual usage, but solving it allows us to have a 100% clean …

[NO-TICKET] Add memory leak testing for profiling + fix (small) memory leak in profiler

---

ext/datadog_profiling_loader/datadog_profiling_loader.c
ext/datadog_profiling_loader/extconf.rb
ext/datadog_profiling_native_extension/collectors_cpu_and_wall_time_worker.c
ext/datadog_profiling_native_extension/collectors_discrete_dynamic_sampler.c
ext/datadog_profiling_native_extension/collectors_stack.c
ext/datadog_profiling_native_extension/collectors_thread_context.c
ext/datadog_profiling_native_extension/extconf.rb
ext/datadog_profiling_native_extension/heap_recorder.c
ext/datadog_profiling_native_extension/profiling.c

I've been experimenting with building the profiler with [AddressSanitizer](https://clang.llvm.org/docs/AddressSanitizer.html) (aka ASAN).
So far, I did not discover any issue in the profiler, but I ended up collecting a few tweaks and improvements:
* Compiling the profiler with Clang 18 got me extra warnings to fix that I hadn't seem before
* I needed to add a tiny asan-specific workaround for extension loading
* I ended up doing a cleanup of our `extconf.rb`
Since I'm not sure I'll have the full ASAN testing working on CI soon, I decided to open up a PR with the fixes I had collected.
Although the PR is not big/particularly complex, it may be even easier to review commit-by-commit.
This PR is atop #3852 as it was easier for …

[NO-TICKET] Small set of profiler cleanups from ASAN testing branch

---

.github/workflows/test-memory-leaks.yaml
ext/datadog_profiling_native_extension/extconf.rb
suppressions/lsan.supp

This PR builds atop the work from #3852 and #3862 to enable running the profiler test suite using the AddressSanitizer ("asan") tool (see https://github.com/google/sanitizers/wiki/AddressSanitizerLeakSanitizer ).
This check will enable us to find bugs in the profiler that may not be otherwise caught.
Improve validation of the profiler native extension.
The "asan" tool is built into the clang compiler toolchain, and needs Ruby to be built with a special configuration.
The special configuration is not yet available in the upstream `ruby/setup-ruby` github action, so I needed to fork it and push a small tweak to make it available.
(The Ruby builds were added in https://github.com/ruby/ruby-dev-builder/pull/10 ).
**How to test …

[NO-TICKET] Add more memory leak testing for profiling using asan

---

lib/datadog/appsec/processor.rb
lib/datadog/appsec/processor/rule_loader.rb
lib/datadog/appsec/processor/rule_merger.rb
sig/datadog/appsec/processor/rule_merger.rbs
spec/datadog/appsec/processor/rule_loader_spec.rb
spec/datadog/appsec/processor/rule_merger_spec.rb
spec/datadog/appsec/processor_spec.rb
spec/datadog/appsec/remote_spec.rb

Send telemetry logs about AppSec errors. The errors are mostly related to load waf rules and related data. 
I refactor constant `DEFAULT_WAF_PROCESSORS `and `DEFAULT_WAF_SCANNERS` to methods with instance variable cache in order to avoid eager loading before telemetry component becomes ready during the components initialization lifecycle.

Telemetry logs for AppSec

---

.github/workflows/update-gemfiles.yml

Fix update-gemfiles workflow permissions
No permission is declared in the workflow file, when a switch to a more restrictive global setting would cause the workflow to fail.
None.
**JIRA:**
- [VULN-8195](https://datadoghq.atlassian.net/browse/VULN-8195)
[VULN-8195]: https://datadoghq.atlassian.net/browse/VULN-8195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix update-gemfiles workflow permissions

---

.github/workflows/system-tests.yml

Fixes permissions for system-tests Github Workflow.
System tests failing for PR #3849
https://github.com/DataDog/dd-trace-rb/actions/runs/10633708151/job/29479572745?pr=3849
Similar to https://github.com/DataDog/dd-trace-rb/pull/3878
System tests should not fail.

Fix permissions system-tests workflow

---

.github/workflows/lib-injection.yml
.github/workflows/system-tests.yml

Backport: https://github.com/DataDog/dd-trace-rb/pull/3860

Backport disable persist credentials

---

.github/workflows/system-tests.yml

Add build-harness and build-apps to the list of needs for aggregate job so it won't run if a build job fails

Fix system tests

---

lib/datadog/core/rate_limiter.rb
lib/datadog/tracing/sampling/rule_sampler.rb
lib/datadog/tracing/sampling/span/rule.rb
spec/datadog/core/rate_limiter_spec.rb
spec/datadog/tracing/sampling/rule_sampler_spec.rb

The only usage of token bucket rate limiter currently in our code uses a size of 1 (to perform one action). Default the size parameter to 1 to simplify the API for using token bucket on the caller side.
Dynamic instrumentation will also use token bucket and will also call allow? with the size of 1.
Unit tests

DEBUG-2334 default token bucket allow? size to 1

---

tasks/appsec.rake

This PR modifies `appsec:ruleset:update` rake task to use `GITHUB_TOKEN` env variable for fetching AppSec rulesets.
Repository `appsec-event-rules` is now private, so we can't download ruleset files without a token.
\-
Run `GITHUB_TOKEN=... bundle exec rake appsec:ruleset:update[1.13.1]`

Add Github Token as argument to `appsec:ruleset:update` task

---

Steepfile
lib/datadog/core/telemetry/request.rb
spec/datadog/core/telemetry/request_spec.rb
vendor/rbs/datadog-ci/0/datadog_ci.rbs

As discussed before, we will extend tracer_version reported for internal telemetry with datadog-ci gem version if tracing is running in CI mode.
The monkey patch should be removed in the next release: https://github.com/DataDog/datadog-ci-rb/pull/228
We need a better solution to distinguish datadog-ci versions when examining telemetry metrics emitted from the datadog-ci gem.
The original idea with `+ci-X.Y.Z` doesn't work perfect - it gets replaced by `_`:
`-ci-X.Y.Z` works fine though:
Tested using staging (see reported tracer versions above). I didn't add unit tests because it would require bringing datadog-ci in appraisals which would be an overkill.

[SDTEST-756] add +ci-X.Y.Z to the tracer_version reported to internal telemetry if datadog-ci is present and CI mode is enabled

---

.github/workflows/add-milestone-to-pull-requests.yml

Adds additional permissions to a github actions workflow that adds milestones to merged PRs
"Add milestone to PR" workflow is broken after recent settings change

[NO-TICKET] add missing permissions for add-milestone gha workflow

---

tasks/edge.rake

Provides a task to update a gem to the latest version for an integration. 
Update the all the predefined integration of current runtime version.
```
bundle exec rake edge:update
```
It takes variables:
```
bundle exec rake edge:update[elasticsearch,opensearch]
``` 
PS. I do not commit the diff from the lockfiles because we are working on automation for that.

Update dependency tasks

---

lib/datadog/tracing/contrib/action_cable/instrumentation.rb
lib/datadog/tracing/contrib/httpclient/patcher.rb
lib/datadog/tracing/contrib/httprb/patcher.rb
lib/datadog/tracing/contrib/lograge/patcher.rb
lib/datadog/tracing/contrib/presto/patcher.rb
spec/datadog/tracing/contrib/lograge/patcher_spec.rb

Internal refactoring for some instrumentation
1. Remove redundant `OnlyOnce` guard for during patching `httprb`, `httpclient` and `presto`
2. Remove redundant `ActionCable` rescue 
3. Change lograge incompatibility to warn

Remove obsolete OnlyOnce during patching

---

lib/datadog/tracing/contrib/action_pack/action_controller/instrumentation.rb
lib/datadog/tracing/contrib/active_record/configuration/resolver.rb
lib/datadog/tracing/contrib/elasticsearch/patcher.rb
lib/datadog/tracing/contrib/grape/endpoint.rb
lib/datadog/tracing/contrib/http/instrumentation.rb
lib/datadog/tracing/contrib/httpclient/instrumentation.rb
lib/datadog/tracing/contrib/httprb/instrumentation.rb
lib/datadog/tracing/contrib/opensearch/patcher.rb
lib/datadog/tracing/contrib/patcher.rb
spec/datadog/tracing/contrib/active_record/configuration/resolver_spec.rb
spec/datadog/tracing/contrib/grape/tracer_spec.rb
spec/datadog/tracing/contrib/patcher_spec.rb

Send Telemetry logs among instrumentation.

Add telemetry logs for instrumentations

---

spec/datadog/di/redactor_spec.rb

This tests specifically @ sign in identifier names which has special meaning in Ruby but is considered generic punctuation in Redactor.
Adds unit tests.
Better test coverage of DI.
Unit tests

DEBUG-2334 Add more redaction test cases

---

lib/datadog/tracing/remote.rb
spec/datadog/core/remote/client/capabilities_spec.rb
spec/datadog/tracing/remote_spec.rb

This PR reports dynamic configuration capabilities that are already supported, but were not reported as such. These missing capabilities are: `APM_TRACING_SAMPLE_RATE`, `APM_TRACING_LOGS_INJECTION`, `APM_TRACING_HTTP_HEADER_TAGS`.
System tests have been enabled for these capabilities: https://github.com/DataDog/system-tests/pull/3011

Add missing RC capabilities

---

lib/datadog/core/configuration/settings.rb
lib/datadog/profiling/component.rb
spec/datadog/profiling/component_spec.rb

This PR disables the Dir interruption bug workaround that was added in
#3720 for Ruby versions 3.4 and above.
The bug has been fixed upstream (see
https://bugs.ruby-lang.org/issues/20586 ) and thus is no longer needed!
N/A
This change includes test coverage.

[NO-TICKET] Disable Dir interruption bug workaround on Ruby 3.4+

---

lib/datadog/core/telemetry/logger.rb
lib/datadog/core/telemetry/logging.rb
spec/datadog/core/telemetry/logger_spec.rb

It is still far too dangerous for `Telemetry::Logger` to hit a deadlock. This is the risk should be mitigated especially for telemetry which is considered to be a kind of best effort utility.

Prevent telemetry deadlock with no-op

---

lib/datadog/di/serializer.rb
sig/datadog/di/serializer.rbs
spec/datadog/di/redactor_spec.rb
spec/datadog/di/serializer_spec.rb
spec/datadog/di/spec_helper.rb

Adds the Serializer component which is responsible for converting arbitrary Ruby objects to object trees made up of basic types.
Ruby DI implementation
Unit tests only in this PR.

DEBUG-2334 Dynamic Instrumentation Serializer component

---

.github/workflows/test-memory-leaks.yaml

This PR disables the memory leak asan testing job in CI. This job started failing because the upstream ruby-dev-builder has been failing to produce Ruby asan builds in the past few days.
Hopefully this will be corrected soon, but for now the easiest thing for us is to disable this. I've also reached out to a few contacts to see if we can get this fixed :)
Disable non-working CI step for now.
N/A
Validate that all CI jobs are green in this PR.

[NO-TICKET] Temporarily disable memory leak asan testing in CI

---

Rakefile
docs/GettingStarted.md
lib/datadog/tracing/contrib/graphql/patcher.rb
lib/datadog/tracing/contrib/graphql/trace_patcher.rb
lib/datadog/tracing/contrib/graphql/tracing_patcher.rb
lib/datadog/tracing/contrib/graphql/unified_trace.rb
lib/datadog/tracing/contrib/graphql/unified_trace_patcher.rb
spec/datadog/tracing/contrib/graphql/patcher_spec.rb
spec/datadog/tracing/contrib/graphql/test_schema_examples.rb
spec/datadog/tracing/contrib/graphql/trace_patcher_spec.rb
spec/datadog/tracing/contrib/graphql/tracing_patcher_spec.rb
spec/datadog/tracing/contrib/graphql/unified_trace_patcher_spec.rb

This PR fixes an issue where it is not possible to reconfigure the GraphQL integration.
This is especially important when using auto instrumentation (`gem 'datadog', require: 'datadog/auto_instrument'`) because any configuration inside a `Datadog.configure{}` block in an auto instrumented application is in fact a reconfiguration.
The main use case for this PR is supporting changing the service name for GraphQL spans.
One important caveat I found while working on this PR is that it is not possible to change GraphQL instrumentation strategies at runtime, as instrumentation pollutes internal GraphQL classes in irreversible ways. 
This was already the case before this PR, and I was not able to address this without a breaking change, thus this limitation remains.
I add …

Allow GraphQL integration reconfiguration

---

benchmarks/profiler_sample_serialize.rb

This PR tweaks the default duration of the
`benchmarks/profiler_sample_serialize.rb` benchmark. This duration gets used when we run benchmarks on every PR.
We've been seeing quite a bit of variance in the benchmarks from run-to-run which makes it seem like there are regressions/improvements even when nothing of consequence is touched (e.g. PR that changes docs even).
This got better when we adjusted the thresholds used by the benchmarking platform, but I'm still seeing this benchmark in particular show up quite often in a "flaky" way.
I suspect this behavior may be because each step on this benchmark can take ~takes~ more than one second (since it simulates 60 seconds of profiling data) and thus the low number of iterations creates more noise.
I'm …

[NO-TICKET] Tweak duration of profiler_sample_serialize benchmark

---

.github/workflows/add-milestone-to-pull-requests.yml
.github/workflows/build-gem.yml
.github/workflows/pull-request-labeler.yml
.github/workflows/system-tests.yml
.github/workflows/yard.yml

Update action version for Node 20
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

Update action version for Node 20

---

spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb

This PR fixes a flaky spec introduced by #3929: a spec to check that an error was raised in a background thread implicitly depended on a race (that the background thread ran before the rspec thread did) and thus started failing when the race was lost.
By actually synchronizing with the background thread using the `on_failure_proc`, we now guarantee that the background thread has the chance to run as expected.
Our goal is to always have zero flaky specs in the profiler!
Fixes https://github.com/DataDog/ruby-guild/issues/179

[PROF-10422] Fix flaky spec in profiler due to race

---

spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb

This PR fixes a flaky specs seen in
https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/16487/workflows/df69cfde-1fd5-40dc-bff6-ac8a9d0bc713/jobs/593534 :
```
1) Datadog::Profiling::Collectors::CpuAndWallTimeWorker#start when main thread is sleeping but a background thread is working when GVL profiling is enabled records Waiting for GVL samples
Failure/Error: expect(waiting_for_gvl_time).to be_within(5).percent_of(total_time)
expected 402832467 to be within 5% of 492191168
```
I was able to reproduce this failure on my local machine in around 1 in 20 runs.
This flakiness is caused by the profiler starting after a Waiting for GVL already started, and thus the profiler does not see it and still categorizes that period as "unknown"; thus our tight …

[PROF-10422] Fix flaky GVL profiling integration spec

---

.rubocop_todo.yml
lib-injection/host_inject.rb
lib/datadog/single_step_instrument.rb
spec/datadog/single_step_instrument_spec.rb

For single step instrumentation, use a different entry point that would rescue `LoadError` and not crash the process.

Split single step instrument entry point

---

Matrixfile
Rakefile
docs/DevelopmentGuide.md
spec/datadog/tracing/contrib/graphql/tracing_patcher_spec.rb

This PR adds tests that were added as Rake tasks, but not to the Matrixfile.
It also updates the `docs/DevelopmentGuide.md` to improve a bit on how to add this information when writing new tests.

Add missing GraphQL and Hanami tests to CI

---

lib/datadog/di/probe.rb
lib/datadog/di/probe_builder.rb
sig/datadog/di/probe.rbs
sig/datadog/di/probe_builder.rbs
spec/datadog/di/probe_builder_spec.rb

Adds `ProbeBuilder` class which parses remote configuration payloads into `Probe` constructor arguments.
Initial implementation of dynamic instrumentation for Ruby.
Unit tests.

DEBUG-2334 Probe Builder for dynamic instrumentation

---

Gemfile
Steepfile
lib/datadog/core/environment/execution.rb
lib/datadog/core/remote/tie.rb
sig/datadog/appsec/configuration/settings.rbs
sig/datadog/core/remote/tie.rbs
sig/datadog/core/telemetry/event.rbs

This PR upgrades steep and rbs to current versions.
For rbs, current version is somehow a 3.6 preview - I constrained it to a 3.5 release instead of using the preview. Can upgrade to the preview if this is more desirable.
To type check the code tracking component (https://github.com/DataDog/dd-trace-rb/pull/3942) I need type definitions for RubyVM::InstructionSequence which I added in https://github.com/ruby/rbs/pull/2027 to upstream. When I tried to use master of rbs in dd-trace-rb I received several type check errors. This PR repairs the errors to permit usage of current steep & rbs.
- `defined?` returns nil or a string, not a bool. `!!` was added in several places to cast the return value to a boolean.
- "anything" in Ruby …

DEBUG-2334 upgrade steep & rbs

---

.github/workflows/test-memory-leaks.yaml

This configuration is frequently failing due to HTTP 503 error when installing valgrind. Retry the installation one time after a short break to see if this would make the configuration less flaky.
Repeated test failures

Retry apt-get install for memory-leaks config

---

lib/datadog/tracing/contrib/active_record/events/instantiation.rb
lib/datadog/tracing/contrib/active_record/events/sql.rb
lib/datadog/tracing/contrib/active_support/cache/events/cache.rb
lib/datadog/tracing/contrib/aws/instrumentation.rb
lib/datadog/tracing/contrib/faraday/middleware.rb
lib/datadog/tracing/contrib/httpclient/instrumentation.rb
lib/datadog/tracing/contrib/httprb/instrumentation.rb
lib/datadog/tracing/contrib/mongodb/subscribers.rb
lib/datadog/tracing/contrib/redis/tags.rb
spec/datadog/tracing/contrib/active_record/events/instantiation_spec.rb
spec/datadog/tracing/contrib/active_record/events/sql_spec.rb
spec/datadog/tracing/contrib/active_support/cache/events/cache_spec.rb
spec/datadog/tracing/contrib/redis/tags_spec.rb

Rescue instrumentation errors.
During instrumentation, we often annotate the span or trace based on the data available. There are risk that the assumption of existing data are not met. 
For instance, 
1. the payload from `ActiveSupport::Notifications` event, might not carry your expected data. 
2. The http response object responds to different methods
3. Fail to parse an invalid string. 
This PR tries to rescue them and fail gracefully. It is not a silver bullet. We still need to expand our test coverage to catch those failures (example: https://github.com/DataDog/dd-trace-rb/pull/3926/commits/93438f43cf2d4c5e49a3fd176224e57eb564d72b)

Rescue instrumentation errors

---

spec/datadog/di/probe_builder_spec.rb
spec/datadog/di/probe_spec.rb

Dynamic instrumentation will not work on Ruby 2.5 and JRuby. Some unit tests will pass on those configurations, but there is no reason to run them there because they run on all of the supported configurations already.
Add `di_test` declaration to all existing DI tests that do not have it.
Faster CI runs.

DEBUG-2334 run all existing DI tests only on supported configurations

---

Matrixfile
lib/datadog/appsec/contrib/rack/gateway/request.rb
spec/datadog/appsec/contrib/rack/gateway/request_spec.rb

This PR fix `spec:appsec:rack` by deleting the `#body` method from the Rack request gateway (as this method is not used anywhere in our code, and the reactive engine uses `#form_hash` to send the body to the WAF) and sets a default value of `'0'` to `headers['content-length']`
`spec:appsec:rack` was failing for Rack 3.1+. Rack is used by most, if not all of our clients, we must be sure to support the latest version (hopefully these failing tests were not critical)

Fix `spec:appsec:rack` for Rack 3.1 (latest)

---

spec/datadog/core/remote/transport/integration_spec.rb
spec/datadog/tracing/contrib/ethon/integration_test_spec.rb
spec/datadog/tracing/contrib/ethon/typhoeus_integration_spec.rb
spec/datadog/tracing/contrib/redis/instrumentation_spec.rb
spec/datadog/tracing/contrib/redis/integration_test_spec.rb
spec/datadog/tracing/contrib/redis/miniapp_spec.rb
spec/datadog/tracing/integration_spec.rb
spec/datadog/tracing/transport/http/adapters/net_integration_spec.rb
spec/datadog/tracing/transport/http/adapters/unix_socket_integration_spec.rb
spec/datadog/tracing/transport/http/integration_spec.rb
spec/support/core_helpers.rb
spec/support/test_helpers.rb

DRY the logic to skip integration tests into a class-level helper
Adds `integration_test` helper method to mark test cases that require a running agent.
Testing of DI network clients.
No code changes in this PR.

DEBUG-2334 Add integration_test helper

---

.github/workflows/system-tests.yml

This PR adds all system-tests available weblogs to system-tests GH workflow file.
Rails 4.2 weblog should be uncommented before merging this PR, when [this system-tests PR](https://github.com/DataDog/system-tests/pull/3142) will be merged
GH Actions should test it automatically

Add all supported weblogs to system-tests GH Workflow file

---

docs/ProfilingDevelopment.md
ext/datadog_profiling_native_extension/collectors_cpu_and_wall_time_worker.c
ext/datadog_profiling_native_extension/collectors_thread_context.c
ext/datadog_profiling_native_extension/collectors_thread_context.h
ext/datadog_profiling_native_extension/extconf.rb
ext/datadog_profiling_native_extension/gvl_profiling_helper.c
ext/datadog_profiling_native_extension/gvl_profiling_helper.h
ext/datadog_profiling_native_extension/private_vm_api_access.c
lib/datadog/core/configuration/settings.rb
lib/datadog/profiling/component.rb
spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
spec/datadog/profiling/collectors/thread_context_spec.rb
spec/datadog/profiling/component_spec.rb
spec/datadog/profiling/spec_helper.rb

This PR builds atop #3929 that added support for GVL profiling for Ruby 3.3+ and makes GVL profiling also work for Ruby 3.2 .
Supporting GVL profiling on Ruby 3.2 needed special additional work. That's because while in Ruby 3.2 we have the GVL instrumentation API giving us the events we need to profile the GVL, we're missing:
1. Getting the Ruby thread `VALUE` as an argument in GVL instrumentation API events
2. The `rb_internal_thread_specific` API that allows us to attach in a thread-safe way data to Ruby thread objects
Both 1 and 2 were only introduced in Ruby 3.3, and our implementation of GVL profiling relies/relied on them.
This PR... reimplements 1 & 2 in an alternative way, allowing us to keep our existing design for 3.3+, while also supporting the older …

[PROF-10588] Support GVL profiling preview on Ruby 3.2

---

lib/datadog/appsec/component.rb
spec/datadog/appsec/component_spec.rb

Ruby 3.3.0 and above has a memory leak when using `libddwaf-rb` with `ffi` gem older than 1.16.0.
We want to avoid forcing our customers to update `ffi` gem by setting the minimum version in `libddwaf-rb`, since prebuilt `ffi` extension is incompatible with rubygems version supplied with ruby 2.7 and below.
The memory leak happens because `ffi` gem used untyped DATA API prior to this commit (which is part of 1.16.0 release):
https://github.com/ffi/ffi/commit/ca2744aed44da7486b3839b879388af3f6307a88
Memory leak that occurs when enabling `appsec` for applications running on ruby 3.3.x and an old version of `ffi` gem locked in Gemfile.lock (older than `1.16.0`).

Add a force disable of appsec when using Ruby >= 3.3 with old ffi

---

.standard_todo.yml

This PR changes standard.rb rules to not enforce particular string quoting style.
I usually use single-quoted strings because they are easier to type (one use of pinky per quote instead of two). standard.rb is currently used by profiler and dynamic instrumentation and @ivoanjo is OK with string quote style being left alone.
None
Not applicable

Permit single-quoted strings in standard.rb

---

lib/datadog/profiling/http_transport.rb
sig/datadog/profiling/http_transport.rbs
spec/datadog/profiling/http_transport_spec.rb

This PR does a very small refactoring to the tests and code in the profiler to print errors when talking to the backend.
In Ruby 3.4, the printing of arrays is being slightly tweaked, and so our tests started failing.
Regardless of that change sticking or being reverted (it does seem like it could cause a bit of annoyance across the ecosystem), I've decided to simplify a bit our code to provide our own printing rather than rely on the Ruby defaults, and thus work everywhere.
Also I decided to remove the specs for
`HttpTransport#config_without_api_key` since it's only used internally for error printing (which did not use to be the case!).
There's a few more things not working on Ruby head due to changes in rubygems/bundler, …

[NO-TICKET] Profiling: Minor cleanup to error messages

---

spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb

I've been hunting down a flaky profiler test that was added as part of the new GVL profiling feature.
Here's how it looks:
https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/16712/workflows/f2e30fe0-c1e5-4e87-b228-4eec53d41017/jobs/599762
I haven't been able to reproduce the issue locally, so I'm adding more information that will hopefully point the way the next time the spec is flaky again.
Hunt down flaky spec.
Thanks for the patience for the other folks on the team. If I really can't figure this one, I'll disable the spec, but I'm hoping this extra info points the way to solving the issue and keeping the spec (since I do believe this spec offers value -- as it tests the GVL profiling feature end-to-end, …

[PROF-10589] Add more details to flaky profiler spec

---

lib/datadog/tracing/distributed/propagation.rb
lib/datadog/tracing/trace_operation.rb
lib/datadog/tracing/tracer.rb

This PR causes a trace to be sampled upon digest creation with the intent of making sampling lazy. The benefit of this approach is that we only create digests right before either propagation or context changes like forking or threading. Therefore it covers multiple exits. The downside is having sampling run as a side effect of creating a digest.

chore: sample before digest

---

lib/datadog/tracing/tracer.rb

By not sampling at span start we are essentially enabling lazy sampling once the groundwork has been merged:
https://github.com/DataDog/dd-trace-rb/pull/3945
https://github.com/DataDog/dd-trace-rb/pull/3946
By enabling lazy sampling we can sample on tags and resource

feat: enable lazy sampling

---

lib/datadog/appsec/component.rb
spec/datadog/appsec/component_spec.rb

Follow-up for #3969 
It fixes `Appsec::Component` building in case when `ffi` gem was not loaded.
It was mentioned during review of #3969 that `ffi` gem might not be loaded, and in this case `ffi_version` would be `nil`:
https://github.com/DataDog/dd-trace-rb/pull/3969#discussion_r1789852584

Fix AppSec::Component building when ffi gem is not loaded

---

Steepfile
lib/datadog/appsec/event.rb
lib/datadog/appsec/rate_limiter.rb
sig/datadog/appsec/rate_limiter.rbs
sig/datadog/core/rate_limiter.rbs
spec/datadog/appsec/event_spec.rb
spec/datadog/appsec/rate_limiter_spec.rb

This allows us to be more precise in throttling of outgoing AppSec traces and removes additional custom logic for rate limiting.
We can re-use recently moved to core `BucketLimiter`. It will eliminate of logic implementation and improve rate limiting. Existing limiter is too aggressive (correct number is `10` traces per test run):
```console
[15:19:31] AppSec/system-tests main
❯❯❯ while true; do docker logs -f system-tests-weblog -f 2>/dev/null | rg -o '_sampling_priority_v1\W:2' | wc -l; sleep 1; done
3
3
3
3
3
3
3
```
with this PR
```console
[15:25:11] AppSec/system-tests appsec-10303-fix-rate-limiter
❯❯❯ while true; do docker logs -f system-tests-weblog -f 2>/dev/null | rg -o '_sampling_priority_v1\W:2' | wc -l; sleep 1; done
10
10
10
10
10
10 …
```

[APPSEC-10303] Replace AppSec rate limiter with core rate limiter

---

spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb

This PR temporarily disables a spec in the profiler that has proven to be flaky.
I've been trying to hunt it down, and finally got a lot of relevant info in https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/16739/workflows/fe009eb1-d942-4432-bc39-713fa9a3b751/jobs/600523
I think I have enough info to analyze the issue, but since this week there's a profiling team meetup let's disable the spec until I have a bit more time to actually sit down and fix it.
Avoid annoying folks with flaky specs.
N/A
Validate that CI is green!

[PROF-10589] Temporarily disable flaky spec for GVL profiling

---

lib/datadog/core/configuration/settings.rb
spec/datadog/core/configuration/settings_spec.rb
spec/datadog/core/crashtracking/component_spec.rb

Disable by default as a cautionary measure.
Crashtracking has been identified as causing issues with `ECHILD` and `waitpid`, and possibly anything involving `SIGCHLD` with obscure failure modes of hard to anticipate consequences.
- Mitigates #3954.
- Attempted fix for `Process.wait(pid)` at #3959, but the problem is more intricate.
- Deeper fix `libdatadog` pending.
CI

Disable crashtracking by default

---

ext/datadog_profiling_native_extension/collectors_thread_context.c
lib/datadog/core/configuration/settings.rb
lib/datadog/profiling/component.rb
spec/datadog/core/configuration/settings_spec.rb
spec/datadog/profiling/collectors/thread_context_spec.rb

This PR gathers fixes for review comments from PR #3984 . See individual commit messages and/or comments in that PR for details.
Since these comments did not impact the feature, and we wanted to get it merged ASAP, I merged that PR first, and here's the follow-up PR to address the comments.
N/A
These features already had test coverage, and this PR tweaks it as needed.

[PROF-10679] Fixes for comments from PR 3984

---

benchmarks/profiler_sample_gvl.rb
benchmarks/run_all.sh
spec/datadog/profiling/validate_benchmarks_spec.rb

This PR adds a new profiler microbenchmark that tests the performance of sampling as triggered from the GVL profiling feature.
I've created this benchmark as part of validating the performance of this feature.
Profiling the profiler with [ddprof](https://github.com/datadog/ddprof), it looks like right now the biggest performance bottleneck is the cost of stack sampling.
This can be validated easily -- changing the depth of the stack for the testing thread makes a big difference.
Validate that this benchmark gets picked up by our usual harness to run microbenchmarks.

[PROF-10589] Add microbenchmark for GVL profiling sampling

---

ext/datadog_profiling_native_extension/collectors_cpu_and_wall_time_worker.c
ext/datadog_profiling_native_extension/collectors_thread_context.c
lib/datadog/profiling/collectors/thread_context.rb
sig/datadog/profiling/collectors/thread_context.rbs
spec/datadog/profiling/collectors/thread_context_spec.rb

This PR collects the results of a quick round of cleanups I did on the profiler.
I recommend reviewing commit-by-commit.
A few of these were existing TODOs; others I spotted as I was going along.
N/A
We have existing test coverage for the tweaked bits.

[NO-TICKET] Bag of profiler cleanups

---

docs/ProfilingDevelopment.md
ext/datadog_profiling_native_extension/collectors_cpu_and_wall_time_worker.c
ext/datadog_profiling_native_extension/collectors_thread_context.c
ext/datadog_profiling_native_extension/collectors_thread_context.h
spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb

This PR introduces the following new internal metrics/counters for the profiler:
```
// How many times we skipped the after_gvl_running sampling
unsigned int gvl_dont_sample;
// Min/max/total wall-time spent on gvl sampling
uint64_t gvl_sampling_time_ns_min;
uint64_t gvl_sampling_time_ns_max;
uint64_t gvl_sampling_time_ns_total;
```
These metrics get automatically reported together with profilers, and allow us to keep an eye on/investigate/debug the performance of GVL profiling.
I needed to refactor a bit the way we trigger GVL profiling samples; the change is similar to what we were doing with regular cpu/wall-time samples.
This change includes test coverage.

[PROF-10589] Add internal metrics for GVL profiling performance

---

lib/datadog/core/workers/async.rb
spec/datadog/core/workers/async_spec.rb

I'm proposing to remove a Ruby version check on the `async.rb` file.
Since dd-trace-rb v2.0+ requires Ruby 2.5+ there are a couple of places where those checks can be removed.
I've updated the corresponding specs to also remove the version check as the test matrix is also not running ruby 2.3 anymore
- Let me know if this is ok, or if you are still releasing new versions under 1.x.x. If all is fine I would like to help with the cleanup of these checks in the future.

Remove Ruby 2.3 version check on async.rb

---

spec/datadog/tracing/contrib/active_record/app.rb
spec/datadog/tracing/contrib/active_record/instantiation_spec.rb

Remove a Rails gem version check in `spec/datadog/tracing/contrib/active_record/app.rb`
Since dd-trace-rb v2.0+ requires Rails 4+ then this check can be removed. I'm not sure if there's any additional cleanup that can be performed here (or even some gem cleanup?)
Didn't see any tests covering this feature but since the test matrix does not install Rails below 4.2 then I would assume all tests pass. Also removed a `skip` condition that does not make sense anymore given test matrix is Rails 4.2+

Remove Rails version check from active_record/app.rb

---

lib/datadog/tracing/contrib/rails/runner.rb
spec/datadog/tracing/contrib/rails/runner_spec.rb

- Resolves #3995 
This avoids an `undefined method` error on `nilClass` whenever when attempting `span.name=`. The spec correctly captures the scenario we're seeing during deploys in our Rails app.

Gracefully handle Rails runner patching whenever spans aren't instrumented

---

integration/README.md
integration/apps/hanami/README.md
integration/apps/opentelemetry/README.md
integration/apps/rack/README.md
integration/apps/rails-five/README.md
integration/apps/rails-seven/README.md
integration/apps/rails-six/README.md
integration/apps/rspec/README.md
integration/apps/ruby/README.md
integration/apps/sinatra2-classic/README.md
integration/apps/sinatra2-modular/README.md

This PR updates the integration test READMEs to address issues when running the tests on aarch64 / arm64 architecture machines (e.g. mac). 
The images by default build on x86_64 / amd64 architecture, so those not running a compatible machine need to specify the aarch64 / arm64 platform when building the image. When running the test scripts, macOS users may also need to disable the automatic use of the buildx docker command, so a fix for this is noted in the updated READMEs as well.
I was trying to run integration tests on my local mac, and I encountered issues with image architecture build incompatibilities. Notably, I found that with my macOS (aarch64 / arm64 architecture), even though I had a local image with the same name, the scripts were …

Update integration test READMEs

---

Matrixfile

Adds a comment explaining what the recently introduced code does in the `Matrixfile`.

Add comment to Matrixfile expansion

---

lib/datadog/core/configuration.rb
lib/datadog/core/remote/worker.rb
lib/datadog/tracing/workers.rb
spec/datadog/core/configuration_spec.rb
spec/datadog/core/remote/worker_spec.rb
spec/datadog/tracing/workers_spec.rb

Similar to https://github.com/DataDog/dd-trace-rb/pull/3998
Removing a couple more mentions to Ruby 2.3 now that the gem requires 2.5+
- lib/datadog/core/configuration.rb
- lib/datadog/tracing/workers.rb
- lib/datadog/core/remote/worker.rb
I've updated the corresponding specs to also remove the version check as the test matrix is also not running ruby 2.3 anymore
There are still a couple more places that I'd like to cleanup, but I'm keeping the PRs short 🤞

Remove Ruby 2.3 version checks in Configuration and workers

---

.github/workflows/test-yjit.yaml
lib/datadog/core/environment/yjit.rb
lib/datadog/core/runtime/ext.rb
lib/datadog/core/runtime/metrics.rb
sig/datadog/core/environment/yjit.rbs
spec/datadog/core/runtime/metrics_spec.rb

When ruby's extended YJIT stats are available (`--yjit-stat`), then we have access to numerous additional stats.
This adds `:ratio_in_yjit`, which is only present when additional stats are enabled.
Example:
```shell
RUBYOPT='--yjit --yjit-stats=quiet' ruby -e '
def foo = "a" * 10
300.times{foo}
puts "ratio_in_yjit: #{::RubyVM::YJIT.runtime_stats[:ratio_in_yjit]}"
'
ratio_in_yjit: 0.9550806290358625
```
This should allow for a better understanding of how to tune `--yjit-exec-mem-size`.
From https://github.com/ruby/ruby/blob/ef084cc8f4958c1b6e4ead99136631bef6d8ddba/doc/yjit/yjit.md?plain=1#L213-L223:
> If you start Ruby with `--yjit-stats`, e.g. using an environment variable `RUBYOPT=--yjit-stats`,
> `RubyVM::YJIT.runtime_stats[:ratio_in_yjit]` …

Support stats "ratio_in_yjit"

---

Gemfile
integration/apps/rack/Gemfile

Remove Ruby 2.3 version checks from Gemfiles as `dd-trace-rb` requires Ruby 2.5+.
- The issue mentioned in the redis gem version restriction has been closed so maybe it's worth looking into it in the future ?
- From what I understand the `Gemfile2-x` `Gemfile3-x` do not need to be updated
EDIT: Need to look into the protobuf failures, maybe missed something

Remove Ruby version checks from Gemfiles

---

.github/workflows/nix.yml
.gitignore
default.nix
flake.lock
flake.nix
lib/datadog/core/telemetry/logging.rb
spec/datadog/core/telemetry/logging_spec.rb
spec/datadog/release_gem_spec.rb

Migrate from classic Nix to Nix Flake.
- `flake.lock` is much more potent than simply pinning `pkgs` by commit, like `Gemfile.lock` is for Ruby.
- With evaluation caching, flakes are so much faster.
Backwards compatibility with classic `nix-build` and `nix-shell` is provided via `flake-compat` shims.
- `nix flake show --all-systems`
- `nix develop`

Migrate to Nix Flake

---

lib/datadog/di/probe.rb
lib/datadog/di/probe_builder.rb
sig/datadog/di/probe.rbs
sig/datadog/di/probe_builder.rbs
spec/datadog/di/probe_builder_spec.rb
spec/datadog/di/probe_spec.rb

None, DI is not yet shipped to customers.
Dynamic instrumentation currently supports 4 probe types (log, metric, span and span decoration). Initial implementation of Ruby DI will only support log probes.
To avoid installing the other probe types, potentially with incorrect results, add a validation of probe type and require that the probe is of the supported type
(currently, just the log probe).

DEBUG-2334 enforce probe type validity

---

.gitlab/benchmarks.yml
benchmarks/profiler_gc.rb
benchmarks/profiler_memory_sample_serialize.rb
benchmarks/profiler_sample_gvl.rb
benchmarks/profiler_sample_loop_v2.rb
benchmarks/profiler_sample_serialize.rb
ext/datadog_profiling_native_extension/collectors_thread_context.c
ext/datadog_profiling_native_extension/heap_recorder.c
ext/datadog_profiling_native_extension/heap_recorder.h
ext/datadog_profiling_native_extension/ruby_helpers.c
ext/datadog_profiling_native_extension/stack_recorder.c
ext/datadog_profiling_native_extension/stack_recorder.h
lib/datadog/core/configuration/settings.rb
lib/datadog/profiling/component.rb
lib/datadog/profiling/stack_recorder.rb
sig/datadog/profiling/stack_recorder.rbs
spec/datadog/core/configuration/settings_spec.rb
spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
spec/datadog/profiling/collectors/stack_spec.rb
spec/datadog/profiling/collectors/thread_context_spec.rb
spec/datadog/profiling/component_spec.rb
spec/datadog/profiling/spec_helper.rb
spec/datadog/profiling/stack_recorder_spec.rb

Add setting to lower heap profiling memory use/latency by cleaning up young objects after Ruby GC
This PR adds a new mechanism to lower heap profiling overhead (memory and latency): the ability to clean young objects being tracked by the heap profiler after a Ruby GC cycle runs, rather than waiting for serialization time.
This mechanism is currently off by default and controlled by the setting `c.profiling.advanced.heap_clean_after_gc_enabled` / `DD_PROFILING_HEAP_CLEAN_AFTER_GC_ENABLED`
We plan to run a bit more validation before enabling it by default.
By doing these cleanups, we lower memory usage (we don't need to wait until until next serialization to notice an object was already collected), and latency, because there's …

[PROF-9470] Align heap recorder cleanup with GC activity (second try)

---

.github/PULL_REQUEST_TEMPLATE.md

This PR clarifies change log section instructions for contributors.
Namely, contributors can skip the change log section and it will be filled out during PR review.
Also moved the change log section below explanation of changes which should make the template easier to fill out for contributors, and comment out the review request note since it doesn't need to be part of PR text.
Feedback in https://github.com/DataDog/dd-trace-rb/pull/4005

Clarify change log section instructions for contributors.

---

.gitlab/benchmarks.yml

This PR tweaks our nightly benchmark runs configuration to add a new configuration that enables GVL profiling.
This will allow us to have better coverage for testing this feature.
(Not relevant for this PR)
This was previously blocked on upgrading the gitlab image that we run in the benchmarking platform, which I finally took care of in https://github.com/DataDog/benchmarking-platform/pull/108 .
I'll trigger a manual run to validate it's running fine and report back ;)

[PROF-10589] Add benchmarking configuration for gvl profiling

---

lib/datadog/core/crashtracking/component.rb
sig/datadog/core/crashtracking/component.rbs
spec/datadog/core/crashtracking/component_spec.rb

This PR fixes a bug in the crashtracking component: because it cached all of the tags from creation, if a process forked, it would use the tags from the parent, which included a (now-incorrect) pid and runtime-id.
This makes sure we have accurate metadata in crashtracking reports.
(Internal change, not relevant for changelog)
N/A
I've added test coverage for this change. It can also be observed by using
> `$ DD_CRASHTRACKING_ENABLED=true bundle exec ruby -e 'require "datadog/auto_instrument"; puts "Parent: #{Process.pid} #{Datadog::Core::Environment::Identity.id}"; fork { puts "Child: #{Process.pid} #{Datadog::Core::Environment::Identity.id}"; Process.kill("SEGV", Process.pid) …

[NO-TICKET] Fix crashtracking sending parent pid/runtime-id when child crashes

---

lib/datadog/appsec/processor.rb
lib/datadog/appsec/processor/context.rb
lib/datadog/appsec/scope.rb
sig/datadog/appsec/processor.rbs
sig/datadog/appsec/processor/context.rbs
spec/datadog/appsec/processor/context_spec.rb
spec/datadog/appsec/processor_spec.rb

This PR will move `Processor::Context` creation inside the `Processor` to avoid leaking knowledge into the caller and fix dependency direction between `Processor`-`Context`.
A new argument will appear on the `Context` - telemetry. Later we will shift responsibilities of how we handle unsuccessful responses of the C-ext WAF and remove spread of the common logic from other classes.
Since `Context` is a part of the `Processor` it can't call handle on the injected dependency (also handle is a hidden API). Instead, `Processor` is going to create a fully operational `Context` and provide all requirements to it.
Not needed.
Just CI.

[APPSEC-55378] Move AppSec context creation into processor

---

datadog.gemspec

This PR removes the tight 1:1 version contraint we have on the `datadog-ruby_core_source` gem, replacing it with allowing any 3.x release.
The tight 1:1 constraint was a leftover from when we used `debase-ruby_core_source`. When we introduced it, in #1740, there were some concerns over validating upstream releases before dd-trace-rb adopted them, and we decided to use this approach to allow us to do so.
As we now run our own fork and have full control over releases of the gem, there's no longer any reason to pin to specific versions.
(Not needed IMO)
We've never had to do it so far, but having the looser version constraint means that if, e.g. a new patch version of Ruby 3.3/3.4 comes out that needs …

[NO-TICKET] Remove tight version contraint on datadog-ruby_core_source

---

integration/apps/opentelemetry/script/build-images
integration/apps/rack/script/build-images
integration/apps/rails-five/script/ci
integration/apps/rails-seven/Gemfile
integration/apps/rails-seven/script/build-images
integration/apps/rails-six/Gemfile
integration/apps/rails-six/script/build-images
integration/apps/rspec/script/build-images
integration/apps/ruby/script/build-images
integration/apps/sinatra2-classic/script/build-images
integration/apps/sinatra2-modular/script/build-images
integration/images/ruby/3.4/Dockerfile
integration/script/build-images

This PR adds Ruby 3.4.0-preview2 support for integration apps. The PR adds a "3.4" version to every file under `integration` that needs to be modified to provide support (indicated with "ADD NEW RUBIES HERE").
Though the official Ruby 3.4 is not yet released, we can temporarily add Ruby 3.4.0-preview2. This allows us to start testing with Ruby 3.4 in our CI and spot -> address issues early. After Ruby 3.4 is officially released post-Dec 25, 2024, we can replace the preview with it.
No change log entry for now. Thinking to have a "Ruby 3.4.0-preview2 support added" update after it is fully supported.
More Ruby 3.4.0-preview2 support is needed. This PR is one step toward full support and only addresses …

Add Ruby 3.4.0-preview2 support for integration apps

---

.gitlab/install_datadog_deps.rb

This PR reduces the artifacts size by removing the cached gems. 
| base (`7f64645565f4967fa1a6b6c047665b04acbc1384`) | branch (`fe76de905f07c8a5e9322cca4563e7a45aa742d6`)| 
|---|---|
| 240 mb |  203.3 mb |

Remove cached gems from artifacts

---

.gitlab/install_datadog_deps.rb

This PR reduces the artifacts size by removing `ext` directories for `ffi` gems
Comparing to the previous PR: https://github.com/DataDog/dd-trace-rb/pull/4042
| base (`fe76de905f07c8a5e9322cca4563e7a45aa742d6`)|  branch(`c803ac20fe15014e56585e7d0119e9a07535f8bf`) | 
|---|---|
|203.3 mb | 173.7 mb |

Remove ffi ext directory from artifacts

---

lib/datadog/appsec/processor/context.rb
sig/datadog/appsec/processor/context.rbs
spec/datadog/appsec/processor/context_spec.rb

Wrap `Processor::Context#run` with an error handling and telemetry reporting.
Is some specific situations, our `libddwaf-rb` is going to throw an exception when it fails to convert C-object into Ruby-object and some other low-level occasions.
Not needed.
Likely we would change the interface of libddwaf-rb soon™️, but in foreseen future we need to be able to land on feet when something wrong happen with our FFI binding.
CI is enough.

[APPSEC-55194] Handle low-level libddwaf exceptions

---

.gitlab/install_datadog_deps.rb

This PR reduces the artifacts size by removing `musl` code from `libdatadog` gems
Comparison to previous PR: https://github.com/DataDog/dd-trace-rb/pull/4043
|  base(`c803ac20fe15014e56585e7d0119e9a07535f8bf`) |  branch (`064cdb5561946cc2faeb2b3791f8f0220cb6f896`)|
|---|---|
| 173.7 mb |  130.1 mb |

Remove libdatadog musl from artifacts

---

.circleci/images/primary/Dockerfile-3.4.0

This PR updates the Ruby 3.4 image for CI from `preview1-bookworm` to `preview2`.
I am progressively adding Ruby 3.4.0-preview2 support to our library. This PR will help push the new image to our ghcr.io.
No change log entry for now. Thinking to have a "Ruby 3.4.0-preview2 support added" update after it is fully supported.
The "Build Ruby" CI step passes for the PR.

Update Ruby 3.4 image to preview2

---

.github/workflows/build-ruby.yml

Adds permissions to `read contents` and `write packages`.
Given tightened restrictions from the Datadog security team on public repositories, we can no longer push images to `ghcr.io`. The change in this PR should address this issue by giving explicit permission to read contents and write packages.
N/A
N/A
All CI tests should pass, and we should be able to push images to `ghcr.io` after this change.

Add permissions for publishing Ruby image

---

spec/datadog/di/probe_notifier_worker_spec.rb

Disables flaky DI specs
Stable CI
None

DEBUG-2334 disable flaky DI specs

---

benchmarks/di_instrument.rb
benchmarks/run_all.sh
benchmarks/support/di_target.rb
spec/datadog/di/validate_benchmarks_spec.rb

The benchmarks in this PR contain code for line probes and method probes, only method probes are currently enabled becuase more DI code is needed to have line probes work.
None
This entire PR was part of #4012 but benchmarks were failing there because master (baseline) didn't have enough DI code to run the benchmarks.
CI

DEBUG-2334 DI benchmarks extracted from #4012

---

.gitlab-ci.yml
.gitlab/prepare-oci-package.sh
lib-injection/requirements.json
lib-injection/test_allow.json
lib-injection/test_block.json

None
Add `requirement.json` for injection.
Prevent injection when:
- we know system dependencies (libc, arch) aren't satisfied
- we know there's no point in injecting into a program (not useful, not effective, blocked by security policy)
- we know injecting into a program would be detrimental (breaking it due to incompatibility or security policy)
**JIRA**
- [INPLAT-103](https://datadoghq.atlassian.net/browse/INPLAT-103)
Should be tested by CI in the added JSON test cases.
[INPLAT-103]: https://datadoghq.atlassian.net/browse/INPLAT-103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Implement `requirement.json` for injection

---

lib/datadog/core/configuration/agent_settings_resolver.rb
spec/datadog/core/configuration/agent_settings_resolver_spec.rb

Ensures uds configurations are parsed in a manner that is consistent with other libraries. 
- Ensures `DD_TRACE_AGENT_URL` is applied in a consistent manner.

fix: ensure uds always takes precedence over http if both configurations are defined

---

.circleci/config.yml
.github/workflows/check.yml

Migrating CircleCI lint job to Github Actions

Migrate Lint job from CircleCI to Github Action

---

.circleci/config.yml

Our CircleCI configuration contains a lot of unnecessary indirections. 
For instance, plenty of `&` variable is only been used ONCE!
This PR tries to streamline the process to make the configuration a bit more expressive

Streamline CircleCI config

---

Rakefile
docs/DevelopmentGuide.md

appraisal binary appears to be incompatible with bundler 2.4+ that set BUNDLER_SETUP environment variable.
In some cases developers are already using BUNDLE_GEMFILE manually to invoke appraisal configurations, probably those using ruby 3.3 and newer.
This PR changes the rakefile to always use BUNDLE_GEMFILE approach, making it work for all Ruby versions, and adds documentation stating that appraisal binary does not work and to use the BUNDLE_GEMFILE manual approach.
Fixing CI in #4040
None
Tested in #4059

Use BUNDLE_GEMFILE directly instead of appraisal binary

---

appraisal/ruby-3.4.rb
gemfiles/ruby_3.4_contrib.gemfile
gemfiles/ruby_3.4_contrib.gemfile.lock
spec/datadog/tracing/contrib/suite/integration_spec.rb

rack 3.1.0 deletes Rack::VERSION constant (in
https://github.com/rack/rack/pull/1966),
causing our tests to fail.
Use Rack::RELEASE instead of Rack::VERSION
to work around the issue
Repairing CI in #4040 
None, changes are in test suite only.
I am assuming currently the tests lock rack to pre-3.1.0 therefore there aren't any failures on master, however #4059 exposed this failure when trying to get a new ruby 3.4 configuration going in circleci.

fix rack 3/rackup situation on ruby 3.4

---

spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb

This PR fixes a profiler flaky spec from
https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/17279/workflows/bafa8b55-7fee-414f-8875-c7a8ef8b56dd/jobs/615562 :
```
1) Datadog::Profiling::Collectors::CpuAndWallTimeWorker#start Process::Waiter crash regression tests can sample an instance of Process::Waiter without crashing
Failure/Error: expect(sample.locations.first.path).to eq "In native code"
NoMethodError:
undefined method `locations' for nil
```
The fix in this case is to make sure that we keep running the profiler until we observe a sample for the thread we expect, not just for any thread.
We aim to always have zero flaky specs in the profiler.
(No entry needed for this one)
If for some …

[NO-TICKET] Fix flaky profiler spec by adjusting wait condition

---

.github/CODEOWNERS

This PR relaxes the GitHub `CODEOWNERS` file rules for things related to profiling.
Specifically, it adds `@DataDog/ruby-guild` as a second owner on top of just `@DataDog/profiling-rb`.
Now that we've enableed the "Require review from Code Owners" feature on GitHub, since there's not a lot of us working on profiling, it hasn't worked very well.
Specifically, for very small PRs (#4072 is a good example where we slightly tweaked a test to avoid flakiness), it's annoying to have to wait for a very small reviewer pool, when most folks that are on the Ruby guild can help out review such changes.
(Not relevant, internal change)
N/A
Check that future PRs affecting profiling can be …

[NO-TICKET] Relax profiling CODEOWNERS configuration

---

.github/workflows/test-macos.yaml
.github/workflows/test-yjit.yaml
spec/datadog/core/environment/execution_spec.rb
spec/datadog/core/error_spec.rb
spec/datadog/tracing/metadata/tagging_spec.rb
spec/datadog/tracing/remote_spec.rb

This PR adds Ruby 3.4.0-preview2 support for github workflow tests, specifically macos and yjit, by adding a "3.4" version to the `test-yjit.yaml` and `test-macos.yml` files under `.github`. It also updates the Dockerfile-3.4.0 base image to `ruby:3.4.0-preview2` and adjusts a few of the spec tests, given new Ruby output changes (see [here](https://www.ruby-lang.org/en/news/2024/10/07/ruby-3-4-0-preview2-released/)).
Though the official Ruby 3.4 is not yet released, we can temporarily add Ruby 3.4.0-preview2. This allows us to start testing with Ruby 3.4 in our CI and spot -> address issues early. After Ruby 3.4 is officially released post-Dec 25, 2024, we can replace the preview with it.
No change log entry for now. Thinking …

Add Ruby 3.4.0-preview2 support for github workflow tests

---

lib/datadog/appsec/processor/context.rb

Remove unintentional require libddwaf library from the Context class.
This was a mistake which slipped through the review and coding.
Related: https://github.com/DataDog/dd-trace-rb/issues/4077
Yes.
Fix: Remove unnecessary require of libddwaf library which may cause crashing.
Probably this should be released as 2.5.1 patch release
Ideally just CI.

Remove unintentional libddwaf require

---

lib/datadog/core/configuration/settings.rb
spec/datadog/core/configuration/settings_spec.rb

This reverts commit c8a2165607cba186b3a3b23742448dc94e53f224 from https://github.com/DataDog/dd-trace-rb/pull/3970
https://github.com/DataDog/dd-trace-rb/pull/4082 fixed the root cause.
Default crashtracking to enabled.
CI

Revert "Disable crashtracking by default"

---

.gitlab/benchmarks.yml
lib/datadog/core/configuration/settings.rb
spec/datadog/core/configuration/settings_spec.rb

This PR changes the optimization added in #4020 to be enabled by default.
I've collected a fresh set of benchmarking results for this feature in [this google doc](https://docs.google.com/document/d/143jmyzB7rMJ9W2hKN0JoDbjo2m3oCVCzvPToHVjLRAM/edit?tab=t.0#heading=h.f00wz5x8kwg6).
The TL;DR is that results seem to be... very close. E.g. sometimes we slightly improve things, but often the numbers seem too close to tell.
But on the other hand this also means that there are no regressions, and thus no reason not to enable the feature by default.
As a recap, without this optimization, the Ruby heap profiler works by sampling allocated objects, collecting and keeping metadata about these objects (stack trace, etc). Then, at serialization time (every 60 …

[PROF-9470] Enable "heap clean after GC" profiler optimization by default

---

.github/workflows/test-memory-leaks.yaml

This PR re-enables the memory leak testing using the asan tool job in CI.
For context, we added this testing in #3864 (more details about what asan is can be found in that PR), but had to disable it in #3915 as the upstream Ruby builds we were using were broken and unavailable for a while.
This has since been fixed upstream, and so let's re-enable this CI job.
In fact, upstream now officially allows these builds to be used, so we no longer even need our fork of `setup-ruby` to enable them.
Improve our testing for native memory leaks.
(Not relevant, testing-only)
N/A
Validate that the "test-asan" is now running in CI. Here's a successful run on "test-asan" in CI with this …

[NO-TICKET] Re-enable ASAN memory leaks testing

---

lib/datadog/di/transport.rb
sig/datadog/di/transport.rbs
spec/datadog/di/transport_spec.rb

"input" endpoint requires a JSON payload, not a
multipart form post.
Initial DI implementation
None
A better unit  test is included to verify this functionality.

DEBUG-2334 repair DI transport

---

tasks/dependency.rake

Providing dependency task for each group is not ideal, because
- `Dir.glob(AppraisalConversion.gemfile_pattern)` is cached for tasks definition.
- Adding/removing gemfiles makes the cache obsolete. 
Glob gemfile at runtime instead. 
PS. There will be follow up PR to replace `appraisal`

Remove static dependency task for each group

---

.standard_todo.yml
lib/datadog/di.rb
lib/datadog/di/code_tracker.rb
lib/datadog/di/component.rb
lib/datadog/di/probe.rb
lib/datadog/di/probe_manager.rb
lib/datadog/di/probe_notification_builder.rb
lib/datadog/di/transport.rb
sig/datadog/di.rbs
sig/datadog/di/component.rbs
sig/datadog/di/probe_manager.rbs
sig/datadog/di/probe_notification_builder.rbs
spec/datadog/di/component_spec.rb
spec/datadog/di/integration/instrumentation_integration_test_class.rb
spec/datadog/di/integration/instrumentation_integration_test_class_2.rb
spec/datadog/di/integration/instrumentation_integration_test_class_3.rb
spec/datadog/di/integration/instrumentation_integration_test_class_4.rb
spec/datadog/di/integration/instrumentation_spec.rb
spec/datadog/di/integration/probe_notification_builder_spec.rb
spec/datadog/di/probe_manager_spec.rb
spec/datadog/di/probe_notification_builder_spec.rb
spec/datadog/di/spec_helper.rb
spec/datadog/di/validate_benchmarks_spec.rb

- Adds a probe manager class whose function is to maintain the list of probes received from remote config and their state (pending/instrumented/failed).
- Probe manager drives Instrumenter (already in master) to perform instrumentation.
- Probe manager keeps track of when instrumentation fails for reasons other than the target is not yet loaded, adds such probes to the list of failed probes and does not attempt to instrument them again.
- Integration tests for instrumentation of the supported cases (method/line probes, basic/enriched, target is loaded/is loaded later) are included and comprise majority of the diff
- DI Component is also part of this PR, it is needed to link Code Tracker and globally installed trace points for code loading and class definition to …

DEBUG-2334 dynamic instrumentation probe manager + instrumentation integration tests

---

lib/datadog/di/probe.rb
spec/datadog/di/probe_spec.rb

Adds checks that a line probe contains a file, which is required to instrument such a probe.
While testing manually I encountered an exception due to a line probe missing the file. This should not happen and such a configuration is not usable since we don't know which file to instrument. Add extra guards and a unit test to handle this case.
None
Unit tests

DEBUG-2334 require file presence for line probe

---

spec/datadog/tracing/contrib/suite/integration_spec.rb

This PR specifies `Rackup::Handler::WEBrick` for versions of Rack >= 3.
`Rack::Handler::WEBrick` was extracted to the `rackup` gem in Rack 3.0. We were already requiring `rackup` for relevant Rack versions, so this propagates that change in the code below.
No change log needed.
CI

Update use of rack vs rackup

---

lib/datadog/tracing/tracer.rb
spec/datadog/tracing/tracer_spec.rb

Addresses a broken edge case introduced by: https://github.com/DataDog/dd-trace-rb/pull/4027. 
Edge Case: When a global service name and a global version are set (for example via DD_SERVICE and DD_VERSION) and a span is initialized without a service name, the global version MUST be set on the span. As of v2.5.0 this is no longer the case.
This bug was detected when v2.5.0 was released and the following system failed: [Test_Config_UnifiedServiceTagging::test_specific_version](https://github.com/DataDog/system-tests/actions/runs/11689546728/job/32553275066). 
Fix
- Tracing: Ensure the global version tag is set on spans that have the global service name.

fix: Apply DD_VERSION on all spans that use the default or global service name

---

spec/datadog/opentelemetry_spec.rb

Removes the beginning ":in `" in three tests.
Ruby 3.4 changes ` to ' at the beginning of strings. See [here](https://www.ruby-lang.org/en/news/2024/10/07/ruby-3-4-0-preview2-released/). This PR adjusts our spec to account for this change.
No change log needed.
Green CI.

Adjust OTel Spec for new Ruby 3.4 syntax

---

.github/workflows/test-memory-leaks.yaml

Temporarily disable due to ruby asan changes
from: `ruby 3.4.0dev (2024-11-07T14:35:19Z :detached: fca07d73e3) +PRISM [x86_64-linux]`
to:    `ruby 3.4.0dev (2024-11-11T18:38:40Z :detached: 8672e88cd2) +PRISM [x86_64-linux]`

Temporarily disable asan ruby job

---

lib/datadog/di/instrumenter.rb
spec/datadog/di/integration/instrumentation_integration_test_class.rb
spec/datadog/di/integration/instrumentation_spec.rb

This PR adds `return` and `b_return` trace point types to the `line` trace point, permitting targeting `end` lines of blocks and methods with line probes.
Initial DI implementation for Ruby.
None
The `return` trace point types have the unfortunate side effect of always installing even if the target line has no executable ruby code (e.g. a comment line). This means users will not be getting notified when they try to instrument non-executable code lines. I think it is worthwhile to permit instrumenting `end` lines even if it means no diagnostics when trying to instrument non-instrumentable lines, in other words, it is better to make more use cases work at the expense of worse diagnostics when something that …

DEBUG-2334 Use :return/:b_return trace points to target 'end' line of methods and blocks with line probes

---

.github/dependency_filters.yml

We've update our flow for dependency management in https://github.com/DataDog/dd-trace-rb/pull/4112, we should update the dependency filter to better allow our [automated detection](https://github.com/DataDog/dd-trace-rb/actions/workflows/lock-dependency.yml) for updating lock files.

Update filter with splitted  gemfile and task

---

.github/workflows/system-tests.yml

Fix system-tests CI flakiness by adding Dockerhub login
> Docker has a rate limit based on your IP when you docker pull without being logged. This limit is pretty low. If you make the same command, but being authenticated before, the rate limit docker applies is way higher.
None.
Variables added as repository secrets.
I suppose that you could launch system-tests GH workflow a lot of time and see that it does not fail because of dockerhub rate limit

Fix system-tests CI flakiness by adding Dockerhub login

---

spec/datadog/core/remote/transport/http_spec.rb

Tries to fix failing CI due to missing OpenStruct.
Example error:
```
1) Datadog::Core::Remote::Transport::HTTP.v7 #send_config 
253
Failure/Error:
254
OpenStruct.new(
255
{
256
root_version: 1,              # unverified mode, so 1
257
targets_version: 0,           # from scratch, so zero
258
config_states: [],            # from scratch, so empty
259
has_error: false,             # from scratch, so false
260
error: '',                    # from scratch, so blank
261
opaque_backend_state: '',     # from scratch, so blank
262
}
263
)
264
265
NameError:
266
uninitialized constant OpenStruct
267
268
269
270
271
272
```
None

Try requiring ostruct explicitly to fix missing OpenStruct exception

---

.github/workflows/system-tests.yml

This PR adds Rails 7.2 and Rails 8.0 weblogs to system-tests workflow in our CI.
Rails 8.0 has been released this week, it is the most used Ruby framework among our clients (and in the Ruby community) so it is important that we support it and see if any of our feature breaks on the newest release of Rails. While doing that, I also saw that we are not running system-tests against Rails 7.2, which still receives frequent updates.
None.
You can check the CI, there should be new steps for system-tests on Rails 7.2 and Rails 8.0

Add Rails 7.2 and Rails 8.0 weblogs to system-tests workflow

---

lib/datadog/di/probe_notification_builder.rb
lib/datadog/di/transport.rb

This PR fixes serialization of debugger "input" endpoint payloads. The serialization must be to JSON, previously simple stringification was used which is not JSON.
System tests (under development) revealed the issue.
The incorrect behavior also renders DI inoperable in demos.
None
There is no test coverage in the library for this change, however it is covered by system tests that I am currently working on.

DEBUG-2334 correctly serialize debugger input payloads

---

benchmarks/di_instrument.rb
lib/datadog/di/instrumenter.rb
spec/datadog/di/validate_benchmarks_spec.rb

Enables line probe benchmarks for dynamic instrumentation.
Initial DI implementation in Ruby.
None
The code being benchmarked must be in master for the benchmarks to work, which is why the benchmarks were committed but turned off.

DEBUG-2334 enable dynamic instrumentation line probe benchmarks

---

spec/datadog/core/environment/execution_spec.rb

Cucumber is broken on ruby 3.4 currently, requires the fix in https://github.com/cucumber/cucumber-ruby/pull/1757 (not released yet).
Use their master from git on ruby 3.4 and unpend the test.
Investigating intermittent failure in that test on the other Ruby versions.
None
Existing test is unpended.

Fix execution spec with cucumber on ruby 3.4

---

lib/datadog/di/probe_notification_builder.rb
spec/datadog/di/probe_notification_builder_spec.rb

This PR  changes the probe notification builder to set duration to 0 in the generated payload if it was not supplied by the caller.
Line probes do not have a meaningful duration, however schema validation in system tests demands a numeric value.
Follow the behavior of other tracers and send 0 instead of nil in this case.
None
This PR also includes additional assertions in the unit test for probe notification builder to make that test in general way more useful. Some of these assertions already exist in integration tests but here they are closer to the code.
Tested by system tests (to be committed in a later PR) and by the unit tests in this PR.

DEBUG-2334 Set duration to 0 for DI line probes

---

lib/datadog/di/transport.rb

This PR adds a require for ostruct to the file which uses OpenStruct.
When testing locally, the corresponding unit test fails without the require.
None
Same situation as https://github.com/DataDog/dd-trace-rb/pull/4126

DEBUG-2334 require ostruct for OpenStruct dependency

---

.gitlab-ci.yml
lib-injection/README.md
lib-injection/host_inject.rb

Followup with https://github.com/DataDog/dd-trace-rb/pull/4137
1. Update Injection guard to allow Ruby 3.3 runtime
2. Exclude Ruby 3.4 installation
3. Update documentation with runtime and glibc support

Update injection guard for Ruby 3.3

---

spec/datadog/core/environment/execution_spec.rb

Reverts DataDog/dd-trace-rb#4130
I missed that there was already a request to run the command in unbundled environment two lines below, thus the original PR did not add any value.

Revert "Run the cucumber test in unbundled environment"

---

lib/datadog/di/instrumenter.rb
lib/datadog/di/probe.rb
lib/datadog/di/probe_builder.rb
lib/datadog/di/probe_notification_builder.rb
lib/datadog/di/serializer.rb
sig/datadog/di/probe.rbs
sig/datadog/di/serializer.rbs
spec/datadog/di/instrumenter_spec.rb
spec/datadog/di/integration/probe_notification_builder_spec.rb
spec/datadog/di/probe_builder_spec.rb

Maximum capture attribute count can be specified in the probe,
This PR implements support for it in DI.
System tests exposed the fact that Ruby DI did not read & propagate max field count from probe specification to the serializer.
None
Tested by https://github.com/DataDog/system-tests/pull/3516 + unit tests in this PR.

DEBUG-2334 respect maxFieldCount in probe specification

---

spec/datadog/core/environment/execution_spec.rb

This PR tries to fix intermittent failures in cucumber development? spec by explicitly loading *some* `psych` gem in the cucumber launcher.
The cucumber test is intermittently failing on Ruby 3.0 through 3.2. When it fails, there are two copies of psych being loaded, and the second copy fails during loading (psych can't overwrite itself).
We haven't figured out what is triggering the second load, but it seems to happen during package installation (i.e., cucumber-*) which requires YAML to parse gem metadata.
https://github.com/DataDog/dd-trace-rb/pull/4130 has additional investigation.
This PR offers a workaround for the issue by always configuring psych to be loaded from (some) gem, thus avoiding the error case where it's loaded from a gem and …

Attempt to fix psych test flakiness

---

.circleci/config.yml
.circleci/test_agent_check.rb

I asked my friend Claude to write me a ruby script to replace `jq` installation.

Improve reliability by removing `jq` installation from CircleCI

---

spec/datadog/core/environment/execution_spec.rb

Attempts to fix the flaky environment execution spec.
In the previous PR (#4145) I mistakenly placed the 'gem' instruction into a spring test. It was intended to be in the cucumber test.
Noticed this while reading the diff in https://github.com/DataDog/dd-trace-rb/pull/4150.
None

psych fix attempt #3

---

lib/datadog/di/instrumenter.rb
spec/datadog/di/hook_method.rb
spec/datadog/di/instrumenter_spec.rb

Implements/repairs instrumentation of methods that yield. Previously attempting to call such a method after instrumenting it would produce infinite recursion.
Initial Ruby DI implementation.
None
Unit tests are included.

DEBUG-2334 correctly instrument methods that yield

---

spec/datadog/di/hook_method.rb
spec/datadog/di/instrumenter_spec.rb
spec/datadog/di/spec_helper.rb

Adds test coverage for Ruby 2 pattern of defining a method with an "options" last argument that keyword arguments are squashed into.
Additional test coverage for DI.
None
Unit tests are included.

DEBUG-2334 test argument squashing into hashes on ruby 2

---

Matrixfile
Rakefile

https://github.com/DataDog/dd-trace-rb/actions/runs/12011727682/job/33481379194
Update with an exception case which was absent from matrix

Update Action with JRuby9.2, Rails 4 exception

---

.github/workflows/system-tests.yml

Adds the Dynamic Instrumentation system tests to the list of tests in system tests workflow.
Initial DI implementation in Ruby.
None
This PR goes with https://github.com/DataDog/system-tests/pull/3531 which enables the tests from the system tests' side.
This PR previously executed against the branch in https://github.com/DataDog/system-tests/pull/3531 which ran the added tests.

DEBUG-2334 Run Dynamic Instrumentation system tests

---

.github/workflows/test-memory-leaks.yaml
ext/datadog_profiling_native_extension/extconf.rb
ext/datadog_profiling_native_extension/private_vm_api_access.c
ext/datadog_profiling_native_extension/profiling.c
ext/datadog_profiling_native_extension/ruby_helpers.c
ext/datadog_profiling_native_extension/ruby_helpers.h
spec/datadog/profiling/native_extension_spec.rb

This PR fixes a bug introduced in #4020, specifically in f581076c0f927 .
We started using the `rb_obj_info` to print debug information about objects in some cases, BUT I failed to notice that this API is not really available on Ruby 2.5 and 3.3 (but is on all others, which is why it tripped me).
This manifested in the following error reported by a customer:
``WARN -- datadog: [datadog] Profiling was requested but is not supported, profiling disabled: There was an error loading the profiling native extension due to 'RuntimeError Failure to load datadog_profiling_native_extension.3.3.5_x86_64-linux-musl due to Error relocating /app/vendor/bundle/ruby/3.3.0/gems/datadog-2.6.0/lib/datadog/profiling/../../datadog_profiling_native_extension.3.3.5_x86_64-linux-musl.so: …

[PROF-10967] Fix profiler not loading due to "rb_obj_info" symbol not found

---

.github/workflows/test-memory-leaks.yaml
suppressions/ruby-3.4.supp

This PR updates the suppressions file to make the "Test for memory leaks" check pass, after #4161 broke it by upgrading the Ruby version used to run this check.
Make sure master is squeaky clean.
(Not relevant to customers)
This was supposed to go together with #4161, but even though the "Test for memory leaks" failed, the auto-merge still merged my PR while I was preparing this extra commit to make it pass CI.
Validate the "Test for memory leaks", CI validation passes again.

[PROF-10967] Fix missing suppressions after PR 4161 got merged

---

lib/datadog/di/contrib/active_record.rb
spec/datadog/di/contrib/active_record/serializer_active_record_spec.rb

Dynamic Instrumentation ships with a custom serializer for ActiveRecord models which lifts the interesting fields (i.e. attributes) to the top level of the serialized object.
This PR adds the new_record? flag to the serialized object.
The current rendering of AR models in dynamic instrumentation UI is somewhat "weird" because the attributes are nested under the "attributes" field, but there are no other fields. It's confusing why the attributes aren't just rendered on the top level.
Adding the new_record flag, in my opinion, improves the UI to where it looks more polished and doesn't look like something is wrong with it.
None (part of initial DI release)
Unit tests are included

DEBUG-2334 add new_record flag to ActiveRecord model custom serializer

---

lib/datadog/di/code_tracker.rb
lib/datadog/di/probe.rb
lib/datadog/di/probe_manager.rb
lib/datadog/di/utils.rb
spec/datadog/di/code_tracker_pending_load.rb
spec/datadog/di/code_tracker_pending_require.rb
spec/datadog/di/code_tracker_spec.rb

Fixes incorrect placement of the call to install pending probes in script_compiled trace point handler. The call should only be made if there is a path corresponding to the code having been compiled (i.e., code was required or loaded but not evaled). Previously the call was outside of the conditional checking if path is present and would be made also for eval'd code, subsequently failing in path suffix matching.
The failure manifested in my local testing with "propagate all exceptions" flag set which I normally have on.
None
The existing exception boundaries prevent the issue being repaired in this PR from having customer impact - it would only generate noise in the log. The exception boundary at trace …

DEBUG-2334 do not try to install pending probes on eval'd code

---

.github/workflows/system-tests.yml
lib/datadog/appsec/response.rb
spec/datadog/appsec/response_spec.rb

Custom actions for AppSec can have status codes that are strings and not integers. We need to handle them properly.
This PR adds conversion of response status code for AppSec actions.
Failing system tests:
https://github.com/DataDog/system-tests/pull/3586
None
None
CI is enough

Fix handling of non integer response status code in AppSec

---

.gitlab/benchmarks.yml

Our Gitlab pipeline is basically namespaced with stages.
However, this means the benchmark job requires previous stages to finish and runs last. The job itself took plenty of time (around 20 min) before it could add a PR comment.
However, those stages are not dependent on each other and should run in parallel 
Make the job without requirement.

No requirement for benchmarks

---

.github/workflows/add-milestone-to-pull-requests.yml
.github/workflows/build-gem.yml
.github/workflows/check.yml
.github/workflows/codeql-analysis.yml
.github/workflows/datadog-sca.yml
.github/workflows/datadog-static-analysis.yml
.github/workflows/lock-dependency.yml
.github/workflows/pull-request-labeler.yml
.github/workflows/semgrep.yml
.github/workflows/system-tests.yml
.github/workflows/test-yjit.yaml
.github/workflows/update-latest-dependency.yml
.github/workflows/yard.yml

https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/#ubuntu-latest-upcoming-breaking-changes
>We will migrate the ubuntu-latest label to ubuntu 24 starting on December 5, 2024 and ending on January 17, 2025. The ubuntu 24 image has a different set of tools and packages than ubuntu 22. We have made cuts to the list of packages so that we can maintain our SLA for free disk space. This may break your workflows if you depend on certain packages that have been removed. Please review this [list](https://github.com/actions/runner-images/issues/10636) to see if you are using any affected packages.
Pin to ubuntu 22 instead of `latest`

Replace `ubuntu-latest` with pinned version

---

ext/datadog_profiling_native_extension/heap_recorder.c

This PR adds a `RUBY_GC_GUARD` call to the Ruby heap profiler, making sure that the object being pointed by the `ref` local variable does not get garbage collected too early.
This is a speculative fix:
We've seen a crash coming from calls to `ruby_obj_memsize_of` (line 654). Adding this `RUBY_GC_GUARD` is a very-low-cost "just in case" until we can fully get to the bottom of this crash, and even if it wasn't needed, it's very harmless to have.
(Internal change, not relevant for changelog)
N/A
This is part of the challenge -- it's extremely hard to test this change, as in many compilers it may even turn out to be a no-op.
We'll need to wait for more info on the crash to go …

[PROF-10987] Add Ruby GC guard to heap profiler as a preventative measure

---

.github/workflows/ensure-changelog-entry.yml

Adds new PR check which will notify either author or DataDog/ruby-guild about missing "Change log entry" section.
Automate work which could be automated, less personal, more efficient.
None.
It will trigger only on PR open/re-open/edit events which makes sense. After "Change log entry" is filled in it will update its comment with a "Thank You" message.
Warning message:
Thank you message:
_P.S This PR is using regex to solve the problem_ :trollface:
Create a branch based on this and open PR with incomplete "Change log entry" section. Alternatively `act` from Github.

Warn on missing "Change log entry" section

---

.github/workflows/ensure-changelog-entry.yml

Fix condition (leftover after small refactoring) on when to write "Thank you" message on correct "Change log entry"
I've noticed that in this PR https://github.com/DataDog/dd-trace-rb/pull/4193 after a failed membership check action wasn't writing "Thank you" message when should. It turn out I have some leftovers in condition when to write a warning message.
No.
Good news - it works, bad news - it's impolite 🥸 
Make your profile private, open PR with no "Change log entry", correct it and don't receive any "Thank you"

Fix change log action condition to write warning

---

spec/datadog/di/component_spec.rb
spec/datadog/di/integration/everything_from_remote_config_spec.rb
spec/datadog/di/integration/instrumentation_spec.rb
spec/datadog/di/probe_notifier_worker_spec.rb
spec/datadog/di/remote_spec.rb
spec/datadog/di/spec_helper.rb

Replaces double(...) with instance_double(...) usage in DI test suite, except for (non-agent) settings which I don't think can be mocked this way since they use anonymous classes?
Feedback on earlier PRs
None
Existing unit tests

DEBUG-2334 replace double() with instance_double() in DI test suite

---

tasks/appsec.rake

This PR fixes error handling in `appsec:ruleset:update` rake task.
Exception when fetching the ruleset with invalid github access token.
None
None
Run the task:
```bash
GITHUB_TOKEN=... bundle exec rake appsec:ruleset:update[1.13.3]
```

Fix appsec:ruleset:update rake task

---

docs/GettingStarted.md
lib/datadog/tracing/configuration/settings.rb

This PR updates our documentation to clarify what test mode does:
1. I've tweaked the wording to make it clear that this feature is used for testing distributed tracing behavior
2. I've explicitly mentioned that traces will still be sent; the previous version of the docs erroneously claimed a no-op transport would be applied, which is not true
3. I've left hints for folks that search for "test" while trying to disable dd-trace-rb in their test suites, that they should look at `tracing.enabled` instead
4. I've removed the bigger code examples for this feature, as it's a very niche thing that almost nobody will want to use, and having the code examples invites copy-paste of something that is probably not what the customer wants
The fact this doc is …

[NO-TICKET] Update documentation to clarify what test mode does

---

lib/datadog/di/instrumenter.rb
spec/datadog/di/hook_method.rb
spec/datadog/di/instrumenter_spec.rb

Fixes a bug in dynamic instrumentation where once a method was instrumented with a method probe and the rate limit for the probe was reached, the block would not be passed to target method from DI.
Code inspection when implementing snapshot benchmarks (https://github.com/DataDog/dd-trace-rb/pull/4207).
No.
*Reason: while this issue would have affected customer applications, DI has not yet been shipped.*
I added many tests but could not yet reproduce the scenario where the separated calls to `super` were necessary as they are in the non-rate limited path. I added the separated calls in case they are indeed required.
Unit tests are included.

DEBUG-2334 DI: method probes: pass block to target method when rate limited

---

.github/workflows/system-tests.yml

Update debugger system tests scenarios.
Depends on https://github.com/DataDog/system-tests/pull/3616
Sync with removed/added tests
None

[Debugger] Update debugger system tests scenarios

---

lib/datadog/appsec/assets/waf_rules/recommended.json
lib/datadog/appsec/assets/waf_rules/strict.json

This PR updates AppSec WAF rules to version 1.13.3.
New version of rules is released.
None.
This ruleset is already being pushed via remote config, so it's safe to update.
CI is enough.

Update appsec WAF rules to version 1.13.3

---

.github/workflows/ensure-changelog-entry.yml

Adjusting regex to match different variants of the answers.
Based on observations since the initial release, it would be cool to adjust the matcher a bit. Now it will allow to write answers like: `No - reason` and some other.
No
Open PR from the branch to see it in action

Adjust matcher for template change log section

---

lib/datadog/core/telemetry/logging.rb
spec/datadog/core/telemetry/logging_spec.rb

Correct internal Telemetry logging stacktrace and error name reporting.
Without that change stacktrace doesn't show up correctly which also leads to ErrorTracking being impossible. In addition an extra space added between Error name and description.
No.
CI and [ErrorTracking example](https://app.datadoghq.com/error-tracking?query=%40lib_language%3Aruby&et-viz=sample&fromUser=true&issueId=5c4d2828-b7cb-11ef-ab88-da7ad0900002&refresh_mode=sliding&source=backend&from_ts=1733926089112&to_ts=1733926989112&live=true)

Fix Core::Telemetry stacktrace and error logging

---

lib/datadog/tracing/span_event.rb
lib/datadog/tracing/span_operation.rb
lib/datadog/tracing/transport/serializable_trace.rb
sig/datadog/tracing/span_event.rbs
sig/datadog/tracing/transport/serializable_trace.rbs
spec/datadog/tracing/span_event_spec.rb
spec/datadog/tracing/transport/serializable_trace_spec.rb

Add native serialization for the `Datadog::Tracing::SpanEvent` object, when serialized as MessagePack.
This code disabled today, through the `native_events_supported` variable, so this PR is just adding the serialization code that will be activated in a future PR.
None
I've also changed the returned keys from `to_hash` to have String keys, instead of Symbols from before, because both the MessagePack and JSON serialization will convert all this Symbols to Strings immediately. Making this change avoids an unnecessary Symbol -> String conversion. 
All changes are tested, as well as some improved testing for existing Span Events methods.

Internal: Add span events native serialization

---

lib/datadog/di/error.rb
lib/datadog/di/instrumenter.rb
sig/datadog/di/error.rbs
sig/datadog/di/instrumenter.rbs
spec/datadog/di/instrumenter_spec.rb

Ruby stores the list of loaded files in $LOADED_FEATURES. Use this list to detect line probes that attempt to instrument files that have been loaded prior to code tracking being active, and report error to the user when instrumenting those files (since they won’t ever be instrumented in production).
Better diagnostics for DI.
Report instrumentation error in dynamic instrumentation when attempting to instrument line probes and the target file is loaded but not in code tracker registry.
The check can be expensive because it performs path suffix matching for potentially thousands of file paths corresponding to the loaded files.
Unit tests are included

DEBUG-3176 DI: report an error when instrumenting a loaded file that is not in registry

---

spec/datadog/core/configuration/settings_spec.rb

This PR introduces a single shared example to replace approximately ONE BILLION copy pasted test cases to test a binary setting that can be read from an env variable.
I've gotten tired of copy-pasting this again and again and decided to finally clean this up.
None.
My only regret is not having cleaned this up earlier.
Validate tests still pass.

[NO-TICKET] Extract spec for binary setting

---

datadog.gemspec

This PR adds an extra version restriction to our `datadog-ruby_core_source` dependency to ensure that version 3.3.7 or newer gets used.
Version 3.3.7 ships support for Ruby 3.4 (using 3.4.0-rc1 headers) and has a nice on-disk footprint reduction so we want to make sure that it gets used, instead of an older version.
Yes. Require datadog-ruby_core_source >= 3.3.7 to ensure Ruby 3.4 support
N/A
If CI is still green, we're almost good. The final part is testing this with 3.4.0-rc1 -- which we don't yet have in CI.
For now I did that locally and got a green build; once we pick up 3.4.0-rc1 (or 3.4.0 stable) in CI, we'll be able to validate this part in CI as well.

[PROF-11035] Require datadog-ruby_core_source >= 3.3.7 to ensure Ruby 3.4 support

---

.github/workflows/test-memory-leaks.yaml

This PR tries again to re-enable the memory leak testing with AddressSanitizer ("ASAN").
We previously had disabled it since it was failing due to an unrelated issue (specifically, the asan builds are based on Ruby master, and Ruby master was slightly incompatible with the profiler until the `datadog-ruby_core_source` 3.3.7 brought a newer set of headers).
The ASAN tool is quite powerful at detecting memory issues and other problems in native extensions, so if we can keep it running it can help flag issues before they make it to our customers.
None.
We can always disable again later if needed.
Hopefully once Ruby 3.4 stable is out, we can see if it's possible to have a "stable ASAN" build that's not based …

[PROF-11305] Enable memory leak testing with ASAN, try 3

---

lib/datadog/di/component.rb
lib/datadog/di/init.rb
lib/datadog/di/probe_notification_builder.rb
lib/datadog/di/transport.rb
sig/datadog/di/probe_notification_builder.rbs
spec/datadog/di/code_tracker_spec.rb
spec/datadog/di/instrumenter_spec.rb
spec/datadog/di/probe_manager_spec.rb
spec/datadog/di/probe_notifier_worker_spec.rb
spec/datadog/di/remote_spec.rb
spec/datadog/di/spec_helper.rb
spec/datadog/di/transport_spec.rb
spec/spec_helper.rb

Removes hard dependency of DI on Tracing.
- Existing requires of tracing components from DI removed
- DI will check if Datadog::Tracing exists before referencing current_span & current_trace
- Unit tests adjusted to require their dependencies explicitly and to use local CodeTracker instances rather than the global one
DI code tracker must be loaded early in application boot process. Tracing must be loaded late to instrument third-party libraries. Currently, DI requires some tracing components which may result in tracing not loading correctly.
None - I am currently not aware of specific issues with DI or tracing loading.
I intend to add a test in a separate PR that loads DI code tracking in a forked …

DEBUG-3182 DI: remove hard dependency on tracing

---

benchmarks/di_snapshot.rb
benchmarks/support/di_snapshot_target.rb
lib/datadog/di/configuration/settings.rb
lib/datadog/di/probe_notifier_worker.rb
spec/datadog/di/probe_notifier_worker_spec.rb
spec/datadog/di/validate_benchmarks_spec.rb

Adds dynamic instrumentation benchmarks verifying that the rate at which probes can capture, serialize and submit snapshots to the agent are below the rate limits.
It also makes the probe notifier worker queue capacity configurable via an internal setting. With default DI settings, DI will permit no more than 30 snapshots/second on average across all probes which is well short of the 5000/second/probe that this benchmark is aiming to achieve. The benchmark raises the limit (and makes flushes more frequent) to demonstrate theoretical performance of DI implementation, however more work is needed to permit higher limits by default - flushing logic must be carefully written to not starve the application of CPU. The default limits are very conservative in this regard. …

DEBUG-3175 DI snapshot/rate limit benchmark

---

ext/libdatadog_api/crashtracker.c
lib/datadog/core/crashtracking/agent_base_url.rb
sig/datadog/core/crashtracking/agent_base_url.rbs
spec/datadog/core/crashtracking/agent_base_url_spec.rb
spec/datadog/core/crashtracking/component_spec.rb

- Repairs the crash in crashtracker due to insufficient error handling - adds a check for the endpoint construction failing (returning NULL) and raises an exception in this case
- Repairs incorrect agent URL construction from IPv6 addresses - the IPv6 addresses must be bracketed when put into the hostname of a URL
Crash reported by system tests
Yes: fix a crash in crashtracker when agent hostname is an IPv6 address
The code that this PR touches may have more missing error handling (of other situations), I didn't check it exhaustively.
Unit tests are added. 
I also wrote https://github.com/DataDog/libdatadog/pull/809 for libdatadog to verify it works OK with our provided input …

APMLP-350 fix crash in crashtracker when agent url is an ipv6 address

---

.circleci/config.yml
.github/workflows/test-memory-leaks.yaml
integration/images/ruby/3.4/Dockerfile
ruby-3.5.gemfile
suppressions/ruby-3.4.supp

Fixes previously failing test-memcheck job by using released Ruby version 3.4.1 instead of Ruby 3.4.0-preview
CI started to fail
none
CI is green

[NOTICKET-1] use Ruby 3.4.1 for test-memcheck GHA + other fixes to bring master CI to green with 3.4

---

docs/Compatibility.md
docs/DevelopmentGuide.md

Add Ruby 3.4 to the list of compatibilities and update the DevelopmentGuide doc.
Keep our public docs updated to reflect new support.
Yes. Support for Ruby 3.4 is added.
N/A
N/A

Update docs for 3.4 support

---

ext/datadog_profiling_native_extension/clock_id.h
ext/datadog_profiling_native_extension/collectors_cpu_and_wall_time_worker.c
ext/datadog_profiling_native_extension/collectors_discrete_dynamic_sampler.c
ext/datadog_profiling_native_extension/collectors_discrete_dynamic_sampler.h
ext/datadog_profiling_native_extension/collectors_idle_sampling_helper.c
ext/datadog_profiling_native_extension/collectors_stack.c
ext/datadog_profiling_native_extension/collectors_thread_context.c
ext/datadog_profiling_native_extension/heap_recorder.h
ext/datadog_profiling_native_extension/http_transport.c
ext/datadog_profiling_native_extension/private_vm_api_access.h
ext/datadog_profiling_native_extension/profiling.c
ext/datadog_profiling_native_extension/ruby_helpers.c
ext/datadog_profiling_native_extension/stack_recorder.c
ext/datadog_profiling_native_extension/stack_recorder.h
ext/datadog_profiling_native_extension/time_helpers.h

In C, when you declare a `struct foo { ... };` (a bag of fields), you need to always call it `struct foo` by default.
But, using the `typedef` keyword instead, e.g.
`typedef struct { ... } foo;` you can now refer to the type as `foo`.
I've done a big pass and converted almost all structs we have to a typedef. Some already had both names (`struct foo` and `foo`), and in those cases I left only the typedef.
Historically the profiler codebase has used structs both with and without the typedef in a quite inconsistent way. I've been meaning to fix this inconsistency.
No
There's a few structs in the heap profiler I did not touch. That's because I'm working on a PR that has a number of big changes to the heap …

[NO-TICKET] Profiling refactor: typedef most structures

---

lib/datadog/di/code_tracker.rb
lib/datadog/di/component.rb
lib/datadog/di/instrumenter.rb
lib/datadog/di/probe_manager.rb
lib/datadog/di/probe_notifier_worker.rb
lib/datadog/di/remote.rb
spec/datadog/di/component_spec.rb
spec/datadog/di/instrumenter_spec.rb
spec/datadog/di/integration/everything_from_remote_config_spec.rb
spec/datadog/di/probe_manager_spec.rb
spec/datadog/di/remote_spec.rb
spec/datadog/di/spec_helper.rb

Replaces #4230
Changes logging levels used in DI:
- Failure to enable DI is now a warning (since enabling it must have been requested by the customer).
- Remaining logging calls are now emitted at debug level, making those entries not visible in customer logs.
All log messages have `datadog: di:` prefix to make it easy for customers to understand what is generating them.
DI currently uses the logger for reporting its internal issues. However, the logger normally logs to customer logs, and as such the default logging should be customer-centric, meaning log entries should only be created for matters that the customers understand and can fix.
Dynamic instrumentation: logging of internal conditions is now done on debug level, and …

DEBUG-3210 DI: change logging to be appropriate for customer inspection

---

.github/ISSUE_TEMPLATE/feature_request.yaml

This PR adds a "How does Datadog help you?" question to the feature request template.
We've had it in the past, but it got removed as part of some cleanups in #4235, but we'd like to keep it for the reasons discussed in https://github.com/datadog/dd-trace-rb/pull/4235/files#r1891447495 .
None
N/A
I'm not actually sure if there's any way to preview this before it's merged. But, you can check that
1. It's copy-pasted from https://github.com/DataDog/dd-trace-rb/blob/e3ea38f741bf936fda5b9e41c1271c38e6c61e8a/.github/ISSUE_TEMPLATE/bug_report.yaml
2. How that one looks in https://github.com/DataDog/dd-trace-rb/issues/new?template=bug_report.yaml

[NO-TICKET] Add "How does Datadog help you?" to feature request template

---

spec/datadog/tracing/validate_benchmarks_spec.rb

I got this [flaky test recently](https://github.com/DataDog/dd-trace-rb/actions/runs/12323376519/job/34398857257?pr=4154):
```
1) Tracing benchmarks tracing_trace runs without raising errors
Failure/Error: raise('Wait time exhausted!')
RuntimeError:
Wait time exhausted!
```
It looks like this benchmark validation test has a timeout of 10 seconds that was _just_ exceeded in the MacOS CI.
This PR increases it to 30 seconds.
None.

Increase benchmark validation timeout

---

spec/datadog/core/remote/component_spec.rb

This PR disables a spec that's been flaky for a very long time (see https://github.com/DataDog/ruby-guild/issues/191, but I suspect I saw it back in https://github.com/DataDog/ruby-guild/issues/50#issuecomment-1874210356 ) and it just failed on me again:
https://github.com/DataDog/dd-trace-rb/actions/runs/12706052002/job/35418238631?pr=4234
I'm not sure this test is getting us a lot of value, so let's stop the flaky impact until we can dedicate time to fixing it.
(Maybe @lloeki can help here as the original author of the class and tests?)
Get to zero flaky tests in our codebase!
None
N/A
Validate spec is now skipped.

[NO-TICKET] Disable flaky barrier spec

---

lib/datadog/appsec/contrib/graphql/gateway/watcher.rb
lib/datadog/appsec/contrib/rack/gateway/watcher.rb
lib/datadog/appsec/contrib/rails/gateway/watcher.rb
lib/datadog/appsec/contrib/sinatra/gateway/watcher.rb
lib/datadog/appsec/monitor/gateway/watcher.rb

This `:monitor` event that we are adding to the response in every gateway watcher is not used anywhere. We are only looking for `:block` events in the method callers and ignoring the rest.
Removes dead code in gateway watchers for different integrations.
Simplifying AppSec code.
None.
Here you can check how the response from `Gateway#watch` is being used:
https://github.com/DataDog/dd-trace-rb/blob/master/lib/datadog/appsec/contrib/rack/request_middleware.rb#L80-L81
https://github.com/DataDog/dd-trace-rb/blob/master/lib/datadog/appsec/contrib/rack/request_middleware.rb#L111-L112
https://github.com/DataDog/dd-trace-rb/blob/master/lib/datadog/appsec/contrib/rails/patcher.rb#L87-L88 …

Remove obsolete code from gateway watchers

---

integration/README.md
integration/apps/rails-seven/.gitignore

Adds instructions for running integration tests locally
Testing of #4272 
None
N/A

Instructions for running integration tests

---

.gitlab-ci.yml
.gitlab/scripts/vaccine.sh

Currently, each commit is triggering a vaccine workflow run in GitLab. However, where are some caveats:
* When token is invalid, the 403 response does not failed the Gitlab job.
* Gitlab job does not acknowledge vaccine workflow failure.
Hence, the validation is included into our decision to whether a pull request can be merged.
I am improving our cross CI system by implementing a polling model to report workflow status. 
This is far from ideal, but at least we get a signal from vaccine for each pull request. Current limitations of polling approach:
- Resource intensive (constant API calls)
- Potential rate limiting issues
- High latency in status updates
- Maintenance overhead
- Difficulty in handling errors or retries
- No built-in audit trail …

Polling vaccine

---

lib/datadog/appsec/contrib/rack/gateway/watcher.rb
lib/datadog/appsec/contrib/rack/request_body_middleware.rb
lib/datadog/appsec/contrib/rack/request_middleware.rb
lib/datadog/appsec/monitor/gateway/watcher.rb

We want to have a unified way of blocking in AppSec and separate `catch` return arguments from `Gateway#watch` return arguments.
Reducing code complexity.
None.
None.
CI and manual testing with app generator.

Switch AppSec rack blocking to throw

---

spec/datadog/di/code_tracker_spec.rb
spec/datadog/di/code_tracker_test_class_4.rb
spec/datadog/di/code_tracker_test_class_5.rb

Adds test coverage that dynamic instrumentation code tracking works in forked processes.
Verification of DI functionality in various environments
None
Unit tests are included

DEBUG-3316 verify code tracking works in forked processes

---

ruby-3.5.gemfile

Apparently `ostruct` gem is removed by `bundle clean` before the memory leak check.
This PR moves `ostruct` gem out from the test group.
CI failing:
https://github.com/DataDog/dd-trace-rb/actions/runs/12713392872/job/35441183658?pr=4236
None.
None.
CI is enough

Move `ostruct` gem out from test group for Ruby 3.5

---

lib/datadog/core/configuration/components.rb
spec/datadog/core/configuration/components_spec.rb

Adds the state of dynamic instrumentation to environment logger summary reporting.
For troubleshooting it would be helpful to see whether DI is effectively turned on (i.e. it's requested to be on programmatically or via an environment variable, and environmental conditions are appropriate (environment, Ruby version, etc.))
Yes: library will report whether dynamic instrumentation is enabled in startup summary report
Unit tests are included

DEBUG-3328 report DI status in environment logger summary

---

Steepfile
integration/apps/hanami/Gemfile
integration/apps/rails-five/Gemfile
integration/apps/rails-five/app/controllers/di_controller.rb
integration/apps/rails-five/bin/run
integration/apps/rails-five/config/initializers/datadog.rb
integration/apps/rails-five/config/routes.rb
integration/apps/rails-five/spec/integration/di_spec.rb
integration/apps/rails-five/spec/support/integration_helper.rb
integration/apps/rails-seven/Gemfile
integration/apps/rails-seven/app/controllers/di_controller.rb
integration/apps/rails-seven/bin/run
integration/apps/rails-seven/config/initializers/datadog.rb
integration/apps/rails-seven/config/routes.rb
integration/apps/rails-seven/spec/integration/di_spec.rb
integration/apps/rails-seven/spec/support/integration_helper.rb
integration/apps/rails-six/Gemfile
integration/apps/rails-six/app/controllers/di_controller.rb
integration/apps/rails-six/bin/run
integration/apps/rails-six/config/initializers/datadog.rb
integration/apps/rails-six/config/routes.rb
integration/apps/rails-six/spec/integration/di_spec.rb
integration/apps/rails-six/spec/support/integration_helper.rb
integration/images/include/datadog/demo_env.rb
lib/datadog/auto_instrument.rb
lib/datadog/di.rb
lib/datadog/di/contrib.rb
lib/datadog/di/contrib/railtie.rb
sig/datadog/di/contrib.rbs
sig/datadog/di/contrib/railtie.rbs

Adds a Railtie for dynamic instrumentation. The railtie delays loading of DI contrib code (currently, ActiveRecord serializer) until Rails components have been loaded.
Also adds an integration test verifying AR serialization works correctly.
Improving DI reliability 
Yes: improve loading of dynamic instrumentation components
An integration test is added in this PR

DEBUG-3182 DI railtie

---

.github/scripts/find_gem_version_bounds.rb
.github/scripts/generate_table_versions.rb

Update supported versions workflow from #4210
There was a bug with not correctly parsing lines such as `gem "rest-client"`, which should be treated as using `latest`. 
Additionally, fix hardcoded versions for `makara` `httpx`

update supported versions workflow

---

lib/datadog/di/redactor.rb

Remove `env` from list of tokens to redact from Dynamic Instrumentation probe snapshots.
Depends on: https://github.com/DataDog/system-tests/pull/3827
Feature parity
Yes: Dynamic instrumentation: Variables named `env` are no longer redacted

[Debugger] Don't redact env tokens from probe snapshots

---

integration/apps/rails-five/Gemfile
integration/apps/rails-seven/Gemfile
integration/apps/rails-six/Gemfile

Downgrades concurrent-ruby to 1.3.4 to stop rails 6.1 from failing during bootstrap with the following error:
```
app_1                 | Run: bin/rails db:create
app_1                 | Traceback (most recent call last):
app_1                 |         14: from bin/rails:9:in `<main>'
app_1                 |         13: from bin/rails:9:in `require'
app_1                 |         12: from /usr/local/bundle/gems/railties-6.1.7.10/lib/rails/commands.rb:3:in `<top (required)>'
app_1                 |         11: from /usr/local/bundle/gems/railties-6.1.7.10/lib/rails/commands.rb:3:in `require'
app_1                 |         10: from /usr/local/bundle/gems/railties-6.1.7.10/lib/rails/command.rb:3:in `<top (required)>'
app_1                 |          9: from …
```

Work around missing logger dependency in Rails 6.1 and 7.0

---

.github/workflows/system-tests.yml

It switches system-tests ref back to `main`
I forgot to change the ref in this [PR](https://github.com/DataDog/dd-trace-rb/pull/4300) before merging
None.
This PR has to be merged first:
https://github.com/DataDog/system-tests/pull/3843
CI should be green.

Switch system-tests back to main branch

---

lib/datadog/tracing/contrib/extensions.rb
spec/datadog/tracing/contrib/extensions_spec.rb

This PR fixes #2851 . As explained in the original bug report, there's a concurrency issue that can be triggered by the environment logger running concurrently with activating an instrumentation.
Fix a long-standing concurrency issue.
Yes. Fix breaking application boot due to concurrency issue in tracing 
To fix this issue, I've made two changes:
1. Introduced a mutex to protect the `@instrumented_integrations`, thus making sure no two threads can be touching it at the same time
2. Took advantage of the fact that `#instrumented_integrations` was marked as private, and only being used by the environment logger and telemetry (e.g. read-only usage) to return a copy of the data.
This way, we can safely …

[NO-TICKET] Fix breaking application boot due to concurrency issue in tracing

---

docs/DevelopmentGuide.md

Adds new section in the readme and remove duplicated section about how to add new test group into your setup, step by step.
I was able to do it only after the call, it makes sense to share that knowledge
No.
Might need some wording advice
Follow instructions, and if it works - everything is correct then.

[NO-TICKET] Update README section on how to add new dependency group

---

.github/workflows/system-tests.yml

This reverts commit 94f3d65421f3433a6227f2b839962bb249ba3b37, thus undoing the work in https://github.com/DataDog/dd-trace-rb/pull/4306 .
We're seeing the reverse of the attempted effect in #4306: more images are now failing to pull and hitting rate limits. [Example of issue](https://github.com/DataDog/dd-trace-rb/actions/runs/12911000274/job/36002386092?pr=4299).
Let's revert this to avoid impacting master while we figure out the next steps.
No.
N/A
We should stop hitting rate limits again, or at least not as often.

[NO-TICKET] Revert "Merge pull request #4306 from DataDog/ivoanjo/cache-system-tests-images"

---

.circleci/config.yml
.github/CODEOWNERS

This PR removes the `/` prefix from the `CODEOWNERS` paths and the `./` prefix from the JUnit XML testcase source file paths.
Currently, all of our testcase codeowner tags in CI are incorrectly marked as the default @DataDog/ruby-guild. This is because the JUnit XML testcase source file paths do not match the `CODEOWNERS` paths. By removing the prefixes above, the paths will match and testcase codeowner tags will be properly set. See [this reference](https://docs.datadoghq.com/tests/setup/junit_xml/?tab=linux#adding-code-owners) for how testcase codeowner tag assignments work.
With proper codeowners assigned, we can better see the distribution and ownership of tests. This especially will help with identifying flaky test ownership.
**Change log …

Edit CODEOWNERS and JUnit XML file paths to match

---

lib/datadog/appsec.rb
lib/datadog/appsec/configuration/settings.rb
lib/datadog/appsec/contrib/active_record/instrumentation.rb
spec/datadog/appsec/configuration/settings_spec.rb
spec/datadog/appsec/contrib/active_record/mysql2_adapter_spec.rb
spec/datadog/appsec/contrib/active_record/postgresql_adapter_spec.rb
spec/datadog/appsec/contrib/active_record/sqlite3_adapter_spec.rb

It adds `DD_APPSEC_RASP_ENABLED` setting to AppSec for disabling RASP.
This [RFC](https://datadoghq.atlassian.net/wiki/spaces/SAAL/embed/4385407620)
Yes. AppSec: Add setting to disable RASP checks
None.
CI is enough

Add Datadog.configuration.appsec.rasp_enabled

---

lib/datadog/appsec/context.rb
lib/datadog/appsec/ext.rb
lib/datadog/appsec/metrics.rb
lib/datadog/appsec/metrics/telemetry.rb
sig/datadog/appsec/context.rbs
sig/datadog/appsec/ext.rbs
sig/datadog/appsec/metrics/telemetry.rbs
spec/datadog/appsec/context_spec.rb
spec/datadog/appsec/metrics/telemetry_spec.rb

Introduce telemetry metrics reporting for rasp calls.
We catching up with the rest of the libs.
No.
Here you can see [how it is displayed](https://app.datadoghq.com/metric/explorer?fromUser=true&state=H4sIAAAAAAAAE12R4aqDMAyF3yU_L2XoHDr6KpdRikYXaK23iQMnvvsluu3C_Zccvp6cpCs8MDOlESyci_PFlaUrSjAwZD_dGez3Ch32NJLs0ApCEhAsgDlKx_TUvqw_ig80qGHAXlRcJgWEIjJmQgYDGX9mZDkGZOQpjYyuTzl6-c_-zEel6Oijeqm0aMzOi3ec5tyqHFEyte83C1jwj8HywoLx1E7zaWbM69cG282ADpuDP3xfzZ_1dttum2I8BRLXUcRR76T4R23T2NOwGwSKJGDLwgCnLHqplDvMYKFDbmH30rX6vK-wAotXrmyqpq6uRVNc64sBHLuP1tRlVV30WH1GvruYOt1y8jNjB-ZdWMkzbgZ6CoL5FfAT2D3o6d5fkKZALLD9AhZeSLz3AQAA&start=1737638070864&end=1737638761334&paused=true#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbg …

[APPSEC-56456] Add telemetry metrics to rasp calls

---

lib/datadog/appsec/contrib/active_record/instrumentation.rb
spec/datadog/appsec/contrib/active_record/mysql2_adapter_spec.rb
spec/datadog/appsec/contrib/active_record/postgresql_adapter_spec.rb
spec/datadog/appsec/contrib/active_record/sqlite3_adapter_spec.rb
spec/datadog/appsec/contrib/integration/active_record_sql_injection_spec.rb

This PR adds action handling to AppSec `ActiveRecord` instrumentation.
Currently we are only monitoring WAF events for SQLi.
Yes. AppSec: Add reporting of stack trace when SQL Injection attack is detected.
None.
CI and app generator.

Add action handling to AppSec ActiveRecord instrumentation

---

lib/datadog/di/component.rb
lib/datadog/di/probe_notification_builder.rb
lib/datadog/di/remote.rb
sig/datadog/di/component.rbs
sig/datadog/di/probe_notification_builder.rbs
sig/datadog/di/probe_notifier_worker.rbs
spec/datadog/core/configuration/components_spec.rb
spec/datadog/di/integration/everything_from_remote_config_spec.rb
spec/datadog/di/integration/instrumentation_integration_test_class.rb
spec/datadog/di/integration/instrumentation_spec.rb
spec/datadog/di/probe_notification_builder_spec.rb
spec/datadog/di/remote_spec.rb
spec/datadog/di/spec_helper.rb

Reports probe status as errored if the probe fails to instrument.
Manual testing revealed that failure to instrument due to code not being in code tracker did not update UI with probe status.
Yes: fix UI notifications when dynamic instrumentation probes fail to instrument
Tests are included

DEBUG-3317 report probe status errored if probe fails to instrument

---

.github/workflows/system-tests.yml

Ignore `docs/**` in system tests workflow.
An action item from the last guild meeting, we don't need to run whole test suite for documentation changes. This is exactly [documentation-like changes](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-excluding-paths).
No.
My auto-correction made a few adjustments for consistency, I decide to keep it.
Open PR with documentation changes only, system tests should not be present. Not sure about the required checks, probably we need to configure something there too.

[NO-TICKET] Ignore docs changes in system tests workflow

---

.github/workflows/test.yml
spec/datadog/core/environment/execution_spec.rb
tasks/github.rake

1. Replace `compute_tasks` matrix with templating to have finer control of dependency management between jobs
2. Replace bundle cache with artifacts from build stage.
3. Use JRuby to understand the worst performant job
4. Dynamically batch tests with limited concurrency
None

Refactor and dynamically batch test tasks

---

.github/workflows/system-tests.yml

Use official parametric scenario parameters
previously known as experimental, those parameters are now officials, and old ones are removed

Use official parametric scenario parameters

---

.github/workflows/publish.yml
.gitlab-ci.yml

Publish to rubygems.org via Trusted Publishing
Ref: https://guides.rubygems.org/trusted-publishing/
None.

Publish via Trusted Publishing

---

.github/workflows/cache-cleanup.yml
.github/workflows/test.yml
lib/datadog/version.rb
tasks/github.rake

1. Cache root dependencies to improve speed.
2. Purge caches when PR close
None.

Use bundled cache from root

---

.github/workflows/test.yml
tasks/github.rake

1. Generate batch summary for the workflow job
2. Enable workflow for pull requests.
None.

Generate batch summary

---

.github/dependabot.yml
.github/workflows/add-milestone-to-pull-requests.yml
.github/workflows/build-gem.yml
.github/workflows/check.yml
.github/workflows/codeql-analysis.yml
.github/workflows/ensure-changelog-entry.yml
.github/workflows/generate-supported-versions.yml
.github/workflows/lock-dependency.yml
.github/workflows/nix.yml
.github/workflows/publish.yml
.github/workflows/pull-request-labeler.yml
.github/workflows/system-tests.yml
.github/workflows/test-macos.yaml
.github/workflows/test-memory-leaks.yaml
.github/workflows/test-yjit.yaml
.github/workflows/test.yml
.github/workflows/update-latest-dependency.yml
.github/workflows/yard.yml

- **Add dependabot for github actions**
- **Pin actions by hash**
Pinning 3rd-party GitHub Actions by commit SHA makes them less vulnerable to compromise of the 3rd party. To avoid outdating and non-verbosity, versions are commented after the SHA and updating via dependabot is introduced that will automatically update the commented version tag as well.
In case of a false commit SHA, this change could break the corresponding workflow. Typically, this does not cause major interruptions, but it can for example affect a release pipeline and require restart causing delays.
None.

ci: pin all GitHub Actions by SHA and update via dependabot

---

.github/workflows/system-tests.yml
lib/datadog/appsec/remote.rb
spec/datadog/appsec/remote_spec.rb

Before we were not setting `apply_state` to ACKNOWLEDGED on remote config content, which caused some system tests to fail.
This PR adds setting of `apply_state` on remote config content to `ACKNOWLEDGED` after successful processing.
Failing system tests for full denylist blocking: https://github.com/DataDog/system-tests/pull/3937
None, this is internal change. Changes via remote config were applied before too, it's just the status that wasn't set correctly.
None.
CI should be enough.

Fix remote config handling for AppSec

---

.circleci/config.yml

Increases number of curl retries from 3 to 5, and also adds `-e` flag to the shell scripts to make them stop when a command fails
Looking at this failure: https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/18427/workflows/74c5b5dd-981f-40ad-ac8b-476decd6c636/jobs/648546
- datadog-ci was attempted to be run even though it wasn't downloaded
- There was a network failure which happened 3 times
When curl retries, it waits 1 second before the first retry and doubles the waiting time before each subsequent retry. For 3 retries that is a total of 7 seconds between the first and the last attempt (1+2+4). Perhaps 7 seconds is not enough for the network to fix itself - this PR proposes increasing the number of retries to 5 which increases the …

Increase curl retries to attempt to fix transient network failures

---

.github/workflows/system-tests.yml

It switches system-tests back to `main` ref
This PR: https://github.com/DataDog/dd-trace-rb/pull/4345
None. This is internal change.
None.
CI is enough.

Switch system-tests ref back to main

---

lib/datadog/di/code_tracker.rb
lib/datadog/di/probe.rb
lib/datadog/di/utils.rb
sig/datadog/di/utils.rbs
spec/datadog/di/integration/everything_from_remote_config_spec.rb
spec/datadog/di/utils_spec.rb

Loosens the restrictions on path matching to also try to match prefixes of probe paths to the paths that exist at runtime.
For example, suppose at runtime we have:
`/app/app/controllers/hello_controller.rb`
Previously, either exact full path or suffixes of the path were accepted:
- `/app/app/controllers/hello_controller.rb`
- `app/controllers/hello_controller.rb`
- `hello_controller.rb`
Now, paths that have extra subdirectories in front will also be accepted:
- `local/hello_controller.rb`
- `local/controllers/hello_controller.rb`
For projects that are stored in subdirectories in their source code repositories (e.g. monorepos), source code integration is providing a full path that has extra prefixes from the application's standpoint (and also …

DEBUG-3439 DEBUG-3440 remove prefixes from probe paths when path matching

---

lib/datadog/di/probe_notifier_worker.rb

Changes probe notifier worker to send both status and snapshot events in each iteration
When a probe executes for the first time, it emits a status event (that it is emitting) and the snapshot event (execution result). Currently these events are submitted to agent in different processing iterations, which upon reflection is not good - there was one action that caused both events to happen (probe execution), therefore both events should be submitted together.
There is also an issue in debugger-demo-ruby where the snapshot events are dropped between iterations for some reason. The root cause of this issue has not yet been identified but sending both events together works around the problem.
Yes: improve dynamic instrumentation …

DEBUG-3472 send snapshot and status events together

---

tasks/github.rake

Mitigate JRuby 9.2 flakiness for bundle install
None.

Retry `bundle install` flakiness for JRuby 9.2

---

spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb

This PR fixes the following flaky profiler spec
(seen in
https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/19126/workflows/00361a70-d216-4fa9-9ce9-0f87e5f033f1/jobs/669239):
```
Failures:
1) Datadog::Profiling::Collectors::CpuAndWallTimeWorker._native_allocation_count when CpuAndWallTimeWorker has been started when allocation profiling and allocation counting is enabled returns different numbers of allocations for different threads
Failure/Error: expect(after_t1 - before_t1).to be 100
expected #<Integer:201> => 100
got #<Integer:217> => 108
Compared using equal?, which compares object identity,
but expected and actual are not the same object. Use
`expect(actual).to eq(expected)` if you don't care about
object identity in this example.
```
We had …

[NO-TICKET] Fix flaky profiler object counting spec

---

static-analysis.datadog.yml

This rule has been mostly ignored, since it doesn't always provide idiomatic Ruby.
No.

Remove linting rule for list first/last

---

.github/workflows/test.yml
tasks/github.rake

This PR increases our GHA Unit Tests scheduled runs to once every 4 hour.
By increasing our scheduled runs, we will get a larger sample size of test runs on `master` -- helpful for discovering (and then addressing) flaky tests! GHA runs are free, so this should not increase CI costs.
None.
Unit Tests on GHA will run once every 4 hour.

Schedule our GHA Unit Tests to run every hour

---

spec/datadog/core/environment/execution_spec.rb

This PR un-skips a core environment spec. 
We want to enable all tests for our migration to GHA: https://github.com/DataDog/ruby-guild/issues/214.
None.
This spec is known to be flaky. See this issue that was resolved for CircleCI: https://github.com/DataDog/ruby-guild/issues/185. However, we should still enable the test. If it flakes for GHA, then we will address it in another PR (or this one if it flakes now).
Consistently green GHA Unit Tests. I tested this by running GHA Unit Tests five times.

Un-skip spec in core environment

---

.circleci/config.yml
.github/workflows/test.yml
tasks/github.rake

Upload coverage report to `codecov` from Github Actions
None

Upload coverage to codecov

---

spec/datadog/core/environment/execution_spec.rb

Cucumber release 9.2.1 that break our CircleCI Ruby 3.3 tests
https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/19242/workflows/95bce82e-302e-463f-96f2-eb8fbbfe8e30
1. Remove loading `psych` first to mitigate the failure (This solves the broken spec but not sure if this is inviting problems from 3.0 - 3.2 )
3. Remove fetching from master branch since it is included in 9.2.1
None

Remove loading `psych` gem early to fix cucumber spec

---

.circleci/config.yml
.github/workflows/test.yml
tasks/github.rake

1. Use the docker image instead of install the binaries
2. Clear git metadata by avoid checking out of the repo
3. Manually provide git metadata with the commit sha for the pull request event 
None

Provide git metadata for junit

---

lib/datadog/core/transport/response.rb
spec/datadog/core/transport/response_spec.rb

Adds the causing exception information to InternalErrorResponse class that is used by Remote Config client.
When an error happens, it is currently reported as follows:
```
E, [2025-02-11T16:00:52.781351 #24] ERROR -- datadog: [datadog] (/usr/local/bundle/gems/datadog-2.9.0/lib/datadog/core/remote/component.rb:53:in `rescue in block in initialize') remote worker error: Datadog::Core::Remote::Client::TransportError #<Datadog::Core::Transport::InternalErrorResponse:0x00007df67ff5b128> location: /usr/local/bundle/gems/datadog-2.9.0/lib/datadog/core/remote/client.rb:34:in `sync'. reseting client state
```
There is no information as to the actual issue.
With this PR, the report is as follows:
```
W, [2025-02-13T12:46:53.334734 #645]  WARN -- datadog: …
```

DEBUG-3498 Add exception information to the InternalErrorResponse stringification

---

docker-compose.yml
spec/datadog/tracing/contrib/mongodb/client_spec.rb

This PR adds a comment for why the mongodb spec is still skipped for GHA.
Tried to un-skip this spec, but resolving the underlying issue noted in the comment without a better solution would increase overhead by too much for this one spec. The goal is to eventually unskip this spec! We want to enable all tests for our migration to GHA: https://github.com/DataDog/ruby-guild/issues/214.
None.
Issue: https://github.com/DataDog/ruby-guild/issues/216.
The PR change itself is just adding a comment. However, for the spec that is being skipped, it fails when running in a docker container (like for our GHA workflow) but passes when running locally.

Add comment for skipped mongodb spec

---

.github/workflows/build-gem.yml
.github/workflows/cache-cleanup.yml
.github/workflows/check.yml
.github/workflows/generate-supported-versions.yml
.github/workflows/nix.yml
.github/workflows/test-macos.yaml
.github/workflows/test-memory-leaks.yaml
.github/workflows/test-yjit.yaml

From this previous run for cleaning cache: https://github.com/DataDog/dd-trace-rb/actions/runs/13317290722
I learn that:
1. The cache clean summary is not accurate with the status
2. The cache clean does not fetch all the caches associate with the branch because the trigger event is PR closed. 
1. Remove status and createdAt field from the summary since they are less useful. 
2. Since cache size is limited (10Gb), modify jobs what are using caches to be triggered only with PR context instead of just branch pushes. 
None

Improve cache clean summary and trigger event

---

.github/workflows/cache-cleanup.yml

Update cache clean permission with `actions: write`
None.

Update cache clean permission with `actions: write`

---

sig/datadog/appsec/contrib/faraday/patcher.rbs

It fixes type signatures for `Datadog::AppSec::Contrib::Faraday::Patcher`.
Follow up for [PR #4391](https://github.com/DataDog/dd-trace-rb/pull/4391).
None.
None.
CI is enough

Fix AppSec faraday instrumentation type signatures

---

lib/datadog/tracing/contrib/rack/middlewares.rb
spec/datadog/tracing/contrib/rack/distributed_spec.rb

Currently Rack always tries to continue from distributed trace when distributed tracing is enabled, even when there is no distributed trace present.
It causes Rack to always start a new trace, which causes issues with tracing during rails integration tests: controller spans are never appended to a test trace.
A bug reported by Datadog Test Optimization customer: spans from rails instrumentation are not appearing in trace view with a test like that:
```ruby
class WelcomeControllerTest < ActionDispatch::IntegrationTest
test "should get index" do
get root_url
assert_response :success
end
end
```
Yes. Fix: rails spans now appear in test trace view when using Datadog Test Optimization with ActionDispatch::IntegrationTest
**How to …

rack instrumentation: continue trace from distributed trace digest only when distributed trace is present

---

lib/datadog/core/configuration/settings.rb
lib/datadog/profiling/component.rb
spec/datadog/profiling/component_spec.rb

This PR updates the documentation and logs to mark that the heap profiling feature is no longer alpha, and is now considered a preview feature.
We still very much welcome all feedback on this feature.
Graduate feature.
Yes. Graduate heap profiling from alpha to preview
Also, here's a snippet for the release highlights:
````markdown
The heap profiling feature is now in preview. With this release, we've done extensive performance improvements and improved data accuracy.
This feature requires Ruby 3.1+. You can enable it by using the `DD_PROFILING_EXPERIMENTAL_HEAP_ENABLED=true` environment variable, or via code:
```ruby
c.profiling.advanced.experimental_heap_enabled = true
end
```
(Note that this feature …
```

[PROF-11394] Graduate heap profiling from alpha to preview

---

.gitlab-ci.yml
.gitlab/scripts/vaccine.sh

- Pass pipeline information
- Select workflow by run name and properly identify it with absolute certainty
- Fix a lot of corner cases
- Enhance logging feedback for debugging
- Prevent token leaks
Given that we run across repos and across CIs, there was a significant probability to pick incorrect workflows, that would be entirely unrelated to the `dd-trace-rb` item that triggered a workflow here.
On the `vaccine` side this is addressed by:
- allowing an additional `trigger-id` input
- reflecting that `trigger-id` in the workflow run name
As a bonus this allows direct identification of `vaccine` workflow runs straight from GitHub Actions UI.
The image is pulled by `vaccine` by tag containing only the commit SHA and so remains vulnerable to race …

Fix cross-repo race condition

---

.github/workflows/parametric-tests.yml
.github/workflows/system-tests.yml

Split parametric tests away
Parametric tests are independent from System Tests in many ways, notably they have an entirely different run profile, both in runners used and time spent.
Instead of blocking system tests workflow final result visibility we split parametric tests away to their own workflow.
This also allows for better trackability of CI costs.
None.
Post-merge, `Parametric Tests` should be made required in GitHub settings.
CI should still pass.

Split parametric tests away

---

.gitlab/benchmarks.yml
lib/datadog/core/configuration/settings.rb
lib/datadog/profiling/component.rb
spec/datadog/core/configuration/settings_spec.rb
spec/datadog/profiling/component_spec.rb

This PR graduates the GVL profiling feature from preview to GA, and turns it on by default.
This means the old `preview_gvl_enabled` setting and its corresponding `DD_PROFILING_PREVIEW_GVL_ENABLED` environment variable are now deprecated.
Roll out this cool feature to customers ;)
Yes. Enable GVL profiling by default on Ruby 3.2+
Also, here's a snippet for the release highlights:
```markdown
GVL profiling means the profiler gathers information from threads waiting to acquire the Ruby "Global VM Lock" (GVL).
This waiting can be a big a source of latency for Ruby applications: a thread "Waiting on the GVL" is a thread that's ready to make progress, but can't start because Ruby is busy doing something else.
For more details on …
```

[PROF-11385] Enable GVL profiling by default on Ruby 3.2+

---

.gitlab-ci.yml

Adds a notification channel for the build pipeline
One-pipeline added notification messages for failed releases. More notifications may be added in the future

Add notification channel for build pipeline

---

Matrixfile
ext/datadog_profiling_native_extension/collectors_thread_context.c
ext/datadog_profiling_native_extension/extconf.rb
ext/datadog_profiling_native_extension/gvl_profiling_helper.c
ext/datadog_profiling_native_extension/gvl_profiling_helper.h
ext/datadog_profiling_native_extension/private_vm_api_access.c
ext/datadog_profiling_native_extension/private_vm_api_access.h
ext/datadog_profiling_native_extension/profiling.c

This PR adds support for correlating profiling wih otel-api 1.5+.
Context storage was moved in https://github.com/open-telemetry/opentelemetry-ruby/pull/1807 and we needed to update the profiler to account for this.
Keep profiling + otel correlation working.
Yes. Support correlating profiling with otel-api 1.5+
N/A
In #4421 I had already bootstrapped the new appraisal groups needed for testing this. This PR enables them, and our existing test coverage will cover the new code path when used with otel-api 1.5+.

[PROF-11412] Support correlating profiling with otel-api 1.5+

---

.github/workflows/nix.yml

Use `ubuntu-24.04-arm`.
As visible in repo `Insights` `Actions Usage Metrics` the `arm-4core-linux-ubuntu24.04` variant is a `hosted-larger` which may not be free.
None.
See: https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
Parametric tests would be the last one using a `hosted-larged` runner type:
https://github.com/DataDog/system-tests/blob/abb550d5ea74ff1cc4c9f455bb18dc0fa085e1d4/.github/workflows/run-parametric.yml#L46-L48
To get control over `runs-on:` it would need a change like:
```
on:
workflow_call:
inputs:
runs_on:
description: "How many job should be spawned for the parametric test"
default: '{ "group": ""APM …
```

Use non-large arm runner

---

.github/workflows/test-memory-leaks.yaml

This PR will hopefully fix almost [all of the the
flakiness](https://github.com/DataDog/dd-trace-rb/pulls?q=is%3Apr+asan) we've seen from the test-memory-leaks GitHub workflow.
The previous "asan" builds we were using were built from ruby-head, which means that any instability or early breakage in ruby-head would make test-memory-leaks fail.
To fix this, I've worked with upstream to create these 3.4-asan builds: these are Ruby builds that are built **from the latest 3.4 stable Ruby** with asan. Thus any breakages we see in them, should also exist in regular 3.4 builds.
With this change, the test-memory-leaks workflow becomes a lot more valuable, since it's now never expected to fail.
Thus, any failures we see in it are worth investigating. …

[PROF-11151] Fix test-memory-leaks flaky behavior

---

lib/datadog/core/remote/transport/http.rb
lib/datadog/core/transport/http.rb
lib/datadog/di/transport/http.rb
lib/datadog/tracing/transport/http.rb
sig/datadog/core/transport/http.rbs

Moves the adapter registration code to core, since the adapters and the registry where the adapters are added to are both core components. 
As far as I can tell, in master this registration is performed 3 times (once for each component) and each of the registrations are the same exact operation.
Making the transport code smaller so that it is easier to use.
None
None
Existing unit tests

DEBUG-3568 DRY transport adapter registration

---

.github/workflows/_unit_test.yml
.github/workflows/add-milestone-to-pull-requests.yml
.github/workflows/build-gem.yml
.github/workflows/check.yml
.github/workflows/codeql-analysis.yml
.github/workflows/generate-supported-versions.yml
.github/workflows/lock-dependency.yml
.github/workflows/nix.yml
.github/workflows/parametric-tests.yml
.github/workflows/publish.yml
.github/workflows/pull-request-labeler.yml
.github/workflows/system-tests.yml
.github/workflows/test-macos.yaml
.github/workflows/test-memory-leaks.yaml
.github/workflows/test-yjit.yaml
.github/workflows/test.yml
.github/workflows/update-latest-dependency.yml
.github/workflows/yard.yml

Use `zizmor` to lint our Github Actions.
- Add a job for `zizmor`
- Set `zizmor` with minimum severity with low
- Fix most issues.
None.

Scan with zizmor

---

.github/workflows/_unit_test.yml
.github/workflows/add-milestone-to-pull-requests.yml
.github/workflows/build-gem.yml
.github/workflows/cache-cleanup.yml
.github/workflows/check.yml
.github/workflows/publish.yml
.github/workflows/system-tests.yml
.github/workflows/test-memory-leaks.yaml
.github/workflows/test.yml

- Add `actionlint` job 
- Fix issues
None.

Scan with `actionlint`

---

.github/workflows/add-milestone-to-pull-requests.yml

The job is broken because the previous change  https://github.com/DataDog/dd-trace-rb/pull/4457/files#diff-aef600c7d513d344ec6a22c6780e7555f28e946db6685f4c2151500961b2780b
None.

Fix milestone job

---

lib/datadog/appsec/contrib/rack/ext.rb
lib/datadog/appsec/contrib/rack/gateway/watcher.rb
lib/datadog/appsec/contrib/rack/request_middleware.rb
sig/datadog/appsec/contrib/rack/ext.rbs
spec/datadog/appsec/contrib/integration/rack/request_headers_collection_for_identity_spec.rb

Two things:
1. Add new event for Rack contrib named `rack.request.finish`
2. Add subscriber to the said event to set tags of [identity related headers](https://datadoghq.atlassian.net/wiki/spaces/SAAL/pages/2186870984/HTTP+header+collection) (see User event)
This will be a part of the #4433 and could be extracted without a fear of breaking anything.
No. It will be announced as of #4433 release
Unfortunately, we don't have time to go over the current published/subscriber model and it has very odd limitations. Hence the code is placed in the most convenient way, but not in the most right.
CI is good enough.

[APPSEC-56960] Add collection of request headers for identity

---

spec/spec_helper.rb

This will fix the warning about the leaking threads in the tests for `ActiveRecord` connection reaper.
Result of the discussion with guild regarding that issue. It turns out we already was ignoring the reaper, but only for the older versions of `ActiveRecord`.
No. Internal change
None.
CI

[NO-TICKET] Adjust leaking thread detection for new Rails

---

.github/workflows/system-tests.yml
.github/workflows/test.yml

Add a tmp push event trigger for some workflows
None.

Add tmp branch push event

---

tasks/steep.rake

Add ignored files from `Steepfile` into our GHA steep/typecheck summary. Here is an example of a [steep/typecheck summary](https://github.com/DataDog/dd-trace-rb/actions/runs/13544586301#summary-37853098486).
We have a lot of files that are ignored by steep type-checking, so this will provide visibility in our summary of which files are ignored.
None.
See the ignored files in the GHA `steep/typecheck summary` for this PR.

Add ignored files to GHA steep summary.

---

.github/dependabot.yml

Currently, dependabot only updating `.github/workflows` , however, there are some composite actions should be subject to updated as well.
None.

Update dependabot for composite actions

---

ext/datadog_profiling_native_extension/private_vm_api_access.c

This PR adds a few extra checks when getting the line number during stack trace gathering in the profiler.
We got one automated report of a crash in the `rb_iseq_line_no` function, and we couldn't reproduce it, so this is the first attempt at avoiding the issue -- let's see if we ever observe this crash again or not.
Improve stability of the profiler.
None.
See the internal PROF-11475 ticket for more details.
Our existing test coverage already validates that stack trace gathering works fine and matches the Ruby APIs. If this condition was not correct, we'd get more lines set to 0, and our unit tests would fail. (I did some quick manual testing to check this was the case -- and …

[PROF-11475] Add extra safety checks when getting line number in profiler

---

.github/workflows/update-latest-dependency.yml
tasks/edge.rake

Failure: https://github.com/DataDog/dd-trace-rb/actions/runs/13742684776
Fix the broken update latest deps job
```
rake aborted!
KeyError: key not found: "rest-client"
Did you mean?  "rest_client"
/__w/dd-trace-rb/dd-trace-rb/tasks/edge.rake:55:in `fetch'
```
`persist-credentials: false` was introduced in https://github.com/DataDog/dd-trace-rb/pull/4456 to improve our Github Actions security posture. However, this job actually depends on git operations, hence persisted credential is needed.
The fix can be verified with: https://github.com/DataDog/dd-trace-rb/pull/4490
None

Fix update latest deps job

---

lib/datadog/appsec/processor/rule_merger.rb
lib/datadog/appsec/remote.rb
sig/datadog/appsec/processor/rule_merger.rbs
spec/datadog/appsec/processor/rule_merger_spec.rb
spec/datadog/appsec/remote_spec.rb

This PR fixes parsing of actions that were passed via Remote Config for `ASM` product.
Custom configuration for blocking response done in Datadog UI was not parsed by our library.
Yes. AppSec: Fixed: Custom In-App WAF blocking response that was configured in the UI is now applied correctly.
None.
CI and manual testing with app generator.

Fix handling of AppSec actions passed with Remote Config

---

Steepfile
ruby-3.1.gemfile
ruby-3.2.gemfile
ruby-3.3.gemfile
ruby-3.4.gemfile
ruby-3.5.gemfile

Locks steep to version 1.9
Also skip type checking of probe_notifier_worker.rb  because it is failing with the following errors that look like a steep bug:
```
Error: adog/di/probe_notifier_worker.rb:205:20: [error] Type `self` does not have method `send`
│ Diagnostic ID: Ruby::NoMethod
│
└             queue = send("#{event_type}_queue")
~~~~
Error: adog/di/probe_notifier_worker.rb:[20](https://github.com/DataDog/dd-trace-rb/actions/runs/13927375143/job/38975462509?pr=4510#step:7:21)6:30: [error] Type `self` does not have method `settings`
│ Diagnostic ID: Ruby::NoMethod
│
└             if queue.length > settings.dynamic_instrumentation.internal.snapshot_queue_capacity
~~~~~~~~
Error: adog/di/probe_notifier_worker.rb:207:14: [error] Type `self` does not have …
```

lock steep to 1.9.x

---

lib/datadog/appsec/instrumentation/gateway/argument.rb
lib/datadog/appsec/monitor/gateway/watcher.rb
lib/datadog/kit/appsec/events.rb
lib/datadog/kit/identity.rb
sig/datadog/appsec/instrumentation/gateway/argument.rbs
spec/datadog/kit/appsec/events_spec.rb

1. Always set AppSec tag `appsec.events.<event>.usr.login` with a fallback value as `usr.id`
2. Pass `usr.login` when available to `libddwaf`
This is an intermediate step to comply with v3 ATO behavior in which it is expected (by the backend) that we alway pass login data `appsec.events.<event>.usr.login` and in addition we pass `usr.login` to `libddwaf` when available.
No. Announcement will be done as a part of #4433 
Unfortunately, in the current state the `Kit::AppSec::Events` and `Kit::Identity` are coupled, which led to some questionable areas.
CI should be fine

[APPSEC-57032] Add `usr.login` to Kit::AppSec::Events

---

lib/datadog/appsec/actions_handler.rb
lib/datadog/appsec/actions_handler/serializable_backtrace.rb
lib/datadog/appsec/configuration/settings.rb
lib/datadog/appsec/ext.rb
sig/datadog/appsec/actions_handler/serializable_backtrace.rbs
sig/datadog/appsec/ext.rbs
spec/datadog/appsec/actions_handler/serializable_backtrace_spec.rb
spec/datadog/appsec/actions_handler_spec.rb
spec/datadog/appsec/configuration/settings_spec.rb

This PR adds Stack Trace reporting to the Datadog Agent in case of an AppSec event with `generate_stack` action.
We are not handling `generate_stack` action yet.
Yes. AppSec: Add stack trace reporting for security events.
None.
CI and local testing with app-generator (SSRF or SQLi variants).

Add Stack Trace reporting for AppSec actions

---

lib/datadog/core/configuration/settings.rb
spec/datadog/core/configuration/settings_spec.rb

Ensures the ruby tracer parses ddtags in a manner that is consistent with the trace agent and other datadog sdks.
Configuration consistency
Improves DD_TAGS configuration loading for consistent handling of whitespace and key-value pairs across all Datadog libraries and the Datadog Agent. Key-value pairs in the format `key:` or `key` are now stored as {"key": ""} instead of being ignored.

fix(global_tags): update ddtags to align with other sdks

---

lib/datadog/tracing/distributed/datadog.rb
spec/datadog/tracing/distributed/datadog_spec.rb

- Ensures only 16 character hexadecimals are extracted from the `_dd.p.tid` distributed tracing tag. This ensures the ruby tracer does not propagate invalid/unexpected trace ids. 
- Ensure the ruby tracer propagates 128bit trace ids in a manner that is consistent with other datadog libraries.
Ensures the Ruby tracer extracts only 16-character hex values from the _dd.p.tid tag in x-datadog-tags, preventing invalid trace ID propagation.

fix(datadog-headers): ignore invalid tid values in x-datadog-tags

---

appraisal/generate.rb
appraisal/ruby-2.5.rb
appraisal/ruby-2.6.rb
gemfiles/ruby_2.5_devise_min.gemfile
gemfiles/ruby_2.5_devise_min.gemfile.lock
gemfiles/ruby_2.6_devise_min.gemfile
gemfiles/ruby_2.6_devise_min.gemfile.lock

Extend `build_coverage_matrix` method to allow us less boilerplate for auto-generated appraisal groups.
in addition devise group was adjusted to follow the actual state with older Ruby versions (reduce coverage to 2.5 and 2.6 and define specific bigdecimal gem versions)
I don't want to define manually appraisal groups and I find that `meta` argument allows you to add gems to all auto-generated groups, but I guess it will be cool to give it a bit more flexibility.
Of course any tool could be abused, but it will be obvious to spot in PR.
No.
I hope you like it folks, I've added some examples, but want to have a bit more
CI is good enough

[NO-TICKET] Adjust build coverage matrix method

---

spec/datadog/appsec/contrib/integration/rack/blocking_with_deny_and_pass_list_spec.rb

Adds fast running integration tests for Rack with deny/pass list and blocking
We have more intensive tests, but they are very slow and not well maintained and hopefully we could deprecate some of them soon
No.
No.
CI.

[NO-TICKET] Add Rack integration tests with deny/pass list

---

docs/GettingStarted.md
lib/datadog/core/configuration/components.rb
lib/datadog/core/configuration/settings.rb
lib/datadog/core/runtime/metrics.rb
spec/datadog/core/configuration/components_spec.rb
spec/datadog/core/runtime/metrics_spec.rb

Adds a new flag `DD_TRACE_EXPERIMENTAL_RUNTIME_ID_ENABLED` to enable runtime ID collection for runtime metrics. This flag is disabled by default.
We ultimately want to collect the `runtime-id` tag by default, so this will allow us to collect these tags on an opt-in basis and give us better data to evaluate its impact on metrics collection.
Since this adds a feature flag, 
This avoids adding the name `DD_TRACE_EXPERIMENTAL_RUNTIME_ID_ENABLED` to a const because this flag may not be necessary if we determine we can enable this by default. If that's an issue, I can change that.
[APMAPI-1225]
This PR contains unit tests to assert that the `runtime-id` tag is included in the set of …

Add a new experimental flag DD_TRACE_EXPERIMENTAL_RUNTIME_ID_ENABLED flag

---

flake.lock
flake.nix
spec/datadog/tracing/contrib_spec.rb

- Keep nix shell up to date
- Fix incorrect direct `pkgs` reference instead of the desired pinned `llvm`
- Add more ruby versions
Up to date nix shell
Nope

Nix hygiene

---

.github/CODEOWNERS

The bus factor is too low for `apm-idm-ruby` today.
With only two members:
* A PR from one of the two members HAS to be approved by the other; no replacement reviewer qualifies. If one member is away, the other cannot merge their work.
* If both members are away, no PR touching `tracing/contrib` can be merged.
This PR changes the ownership of `tracing/contrib` files to `tracing-ruby`, which has four members and already owns `tracing` and `opentelemetry`. The members `tracing-ruby` are: both `apm-idm-ruby` members plus two other very smart and handsome Ruby engineers.
No

Move `apm-idm-ruby` ownership to `tracing-ruby`

---

lib/datadog/appsec/actions_handler/serializable_backtrace.rb

It fixes a following warning:
```bash
dd-trace-rb/lib/datadog/appsec/actions_handler/serializable_backtrace.rb:14: warning: character class has duplicated range: /\b([\w+:{2}]*\w+)?[#|.]?\b(\w+)\z/
```
We don't want any warnings to be triggered by our library code.
None. This change is internal.
None.
```bash
ruby -W lib/datadog/appsec/actions_handler/serializable_backtrace.rb
```

Fix a warning related to regular expression in AppSec

---

sig/datadog/tracing/correlation.rbs

Makes type checking pass on master by adding  format_trace_id_128 to types
Red CI on master
None: I added the change log entry to https://github.com/DataDog/dd-trace-rb/pull/4499 which would also cover the changes in this PR
The issue was the combination of https://github.com/DataDog/dd-trace-rb/pull/4499 and https://github.com/DataDog/dd-trace-rb/pull/4528 - the first PR enabled type checking of correlation.rb and the second one added a method but not a type signature when type checking ignored the file.
Existing CI

repair type check on master: add format_trace_id_128 to types

---

lib/datadog/di/component.rb
lib/datadog/di/probe_notifier_worker.rb
lib/datadog/tracing/trace_operation.rb

Fixes the following warnings:
```
big% irb -w -Ilib -rdatadog   
/home/w/apps/dd-trace-rb/lib/datadog/tracing/trace_operation.rb:5: warning: /home/w/apps/dd-trace-rb/lib/datadog/tracing/trace_operation.rb:5: warning: loading in progress, circular require considered harmful - /home/w/apps/dd-trace-rb/lib/datadog/tracing/tracer.rb
from /home/w/.rbenv/versions/3.3/bin/irb:25:in  `<main>'
from /home/w/.rbenv/versions/3.3/bin/irb:25:in  `load'
from /home/w/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/irb-1.14.1/exe/irb:9:in  `<top (required)>'
from /home/w/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/irb-1.14.1/lib/irb.rb:898:in  `start'
from /home/w/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/irb-1.14.1/lib/irb/init.rb:56:in  `setup'
from …
```

Fix warnings in DI and tracing generated with -w

---

lib/datadog/profiling.rb

Repairs the warning generated with `ruby -w`:
```
/home/w/apps/dd-trace-rb/lib/datadog/profiling.rb:81: warning: method redefined; discarding old allocation_count
/home/w/apps/dd-trace-rb/lib/datadog/profiling.rb:57: warning: previous definition of allocation_count was here
```
Warning-clean library
Yes: repair `ruby -w` warning in profiler
PRs fixing warnings in other components: #4547, #4548 
Tested manually with:
```
irb -Ilib -rdatadog/profiliing
```

Fix method override warning in profiler

---

lib/datadog/tracing/component.rb
spec/loading_spec.rb

Adds a test that the tracer can be configured when only core part of the code is loaded.
Also adds a require from tracing to its contrib to avoid leaking tracing internals to core/customers.
A customer reported an exception when initializing dd-trace-rb 2.12.2 which I was able to reproduce with the following code:
```
require 'datadog/core'
require 'datadog/tracing/contrib'
Datadog.configure do
end
```
The above code worked on 2.4.0 and is failing from 2.5.0 through 2.12.2 with the following exception:
```
/home/w/apps/dd-trace-rb/lib/datadog/core/remote/transport/http.rb:105:in `block in default_headers': undefined method `appsec' for an instance of Datadog::Core::Configuration::Settings (NoMethodError)
if …
```

APMS-15322 Reproducer for loading core only and configuring the library

---

lib/datadog.rb
spec/loading_spec.rb

Adds a test that no warnings (`ruby -v`) are emitted when the tracer is loaded (#4548, #4547, #4548)
Customer feedback that they don't want tracer to emit warnings
None (warnings removed by the other PRs, this PR only adds test coverage)
Tests are added in this PR

Add tests verifying library is -w warning-clean

---

benchmarks/run_all.sh
ext/datadog_profiling_native_extension/http_transport.c
ext/datadog_profiling_native_extension/stack_recorder.c
lib/datadog/profiling/http_transport.rb
sig/datadog/profiling/http_transport.rbs
spec/datadog/profiling/http_transport_spec.rb
spec/datadog/profiling/stack_recorder_spec.rb

This PR changes the `StackRecorder` so that instead of relying on libdatadog to track a profile's `start_time` (by passing `NULL` -- aka "use current timestamp") it now explicitly gets the current timestamp and passes it along to libdatadog.
This then means that we no longer need to read the `start_time` from libdatadog, because we're tracking it on our side.
Starting with libdatadog 17, we'll no longer be able to read the `start_time` from libdatadog, and this PR leaves us ready for that change.
None.
As I "was in the neighbourhood" I also did a few cleanups on the `HttpTransport` class which will also make it easier to upgrade to libdatadog 17.
We had some existing test …

[PROF-11524] Refactor: Avoid reading profile start_time + Remove indirections during reporting

---

lib/datadog/core/diagnostics/environment_logger.rb
lib/datadog/core/telemetry/metric.rb
lib/datadog/core/telemetry/request.rb
lib/datadog/di/probe_notification_builder.rb
lib/datadog/profiling/collectors/info.rb
lib/datadog/tracing/contrib/rack/request_queue.rb
lib/datadog/tracing/contrib/sidekiq/server_tracer.rb
lib/datadog/tracing/span_event.rb

Changes existing `Time.now` calls in `lib` to instead use `Core::Utils::Time.now`.
The time provider is overridable by users but not all code uses the time provider mechanism. I think everything under `lib` should use the time provider except for the one location where the time is retrieved at class definition.
Yes: Use time provider consistently
Existing tests

Use Core::Utils::Time.now instead of Time.now

---

ext/datadog_profiling_native_extension/collectors_thread_context.c
spec/datadog/profiling/collectors/thread_context_spec.rb

This PR fixes flaky tests such as
[this one](https://github.com/DataDog/dd-trace-rb/actions/runs/14359324310/job/40256546138?pr=4570):
```
Failures:
1) Datadog::Profiling::Collectors::ThreadContext#sample timeline support when timeline is enabled when thread starts Waiting for GVL records a second sample to represent the time spent Waiting for GVL
Failure/Error:
expect(second_sample.labels).to include(
state: "waiting for gvl",
end_timestamp_ns: be_between(time_before_sample, time_after_sample),
)
expected {:end_timestamp_ns => 1744208274700408014, :state => "waiting for gvl", :"thread id" => "10030 (29328)", :"thread name" => "/__w/dd-trace-rb/dd-trace-rb/spec/spec_helper.rb:276"} to include {end_timestamp_ns: (be between 1744208274700440756 and …
```

[NO-TICKET] Fix profiling flaky tests due to time conversions, second try

---

lib/datadog/appsec/event.rb
spec/datadog/appsec/event_spec.rb

It adds `blocked: true` meta tag to spans when redirecting the request because of an AppSec event.
We want to mark blocked requests in Datadog dashboard for customers who configured AppSec to redirect blocked requests.
Yes. AppSec: Fix for blocked requests not marked correctly when using custom redirect blocking action.
None.
Manual testing with app-generator. You have to add a custom blocking action via remote config for your test application.

Add marking of spans as blocked on redirect_request action

---

lib/datadog/appsec/contrib/active_record/integration.rb

This PR enables auto-patching of ActiveRecord.
We want to have SQL Injection detection turned on by default for AppSec users.
Yes. AppSec: Add auto-patching of ActiveRecord for SQL Injection detection.
None.
CI

Enable AppSec auto-patching of ActiveRecord

---

.github/workflows/system-tests.yml
lib/datadog/appsec/remote.rb
sig/datadog/appsec/remote.rbs
spec/datadog/appsec/remote_spec.rb

This PR adds a remote capability for AppSec SQL injection exploit prevention.
We have instrumentation for ActiveRecord to detect SQL injection.
None. This is internal change.
**Don't merge before #4269**
CI is enough.

Add AppSec RASP SQLI remote capability

---

spec/datadog/core/crashtracking/component_spec.rb
spec/datadog/di/integration/probe_notifier_worker_spec.rb
spec/datadog/profiling/http_transport_spec.rb
spec/datadog/tracing/contrib/ethon/integration_context.rb
spec/datadog/tracing/contrib/ethon/integration_test_spec.rb
spec/datadog/tracing/contrib/ethon/typhoeus_integration_spec.rb
spec/datadog/tracing/contrib/httpclient/instrumentation_spec.rb
spec/datadog/tracing/contrib/httprb/instrumentation_spec.rb
spec/datadog/tracing/contrib/suite/integration_spec.rb
spec/datadog/tracing/transport/http/adapters/unix_socket_integration_spec.rb
spec/spec_helper.rb
spec/support/http_server_helpers.rb

Creates a `http_server` helper that holds all of the webrick setup.
The helper combines functionality from the setup I used for DI (namely, if there is an exception in the webrick server thread during initialization, it won't hang the test suite) and the rest of the tracer (which was hiding log output by default).
Previously, some tests created the webrick server for each test individually, and some for "all" tests. The current implementation in this PR creates the server per-test. This is easier to follow and I think the actual performance difference is minimal because there are very few tests that actually use webrick.
For replacing telemetry transport with the core transport we need some integration tests to ensure everything is working …

DEBUG-3700 DRY webrick usage in test suite

---

.github/workflows/publish.yml
.github/workflows/update-latest-dependency.yml

Before releasing, in order to prevent accidentally merging, master branch is locked and auto-merge is disable. 
This configuration breaks to step that enable auto-merge for auto generated pull requests which leads to broken status blocking release.
1. Add option to bypass checks that are blocking release
2. Remove step that enable auto-merge 
None.

Publish gem improvement

---

ext/libdatadog_api/crashtracker.c
ext/libdatadog_api/crashtracker.h
ext/libdatadog_api/init.c
ext/libdatadog_api/process_discovery.c
ext/libdatadog_api/process_discovery.h
lib/datadog/core.rb
lib/datadog/core/configuration/components.rb
lib/datadog/core/crashtracking/component.rb
lib/datadog/core/process_discovery.rb
sig/datadog/core.rbs
sig/datadog/core/crashtracking/component.rbs
sig/datadog/core/process_discovery.rbs
spec/datadog/core/crashtracking/component_spec.rb
spec/datadog/core/process_discovery_spec.rb
spec/spec_helper.rb
spec/support/crashtracking_helpers.rb
spec/support/libdatadog_helpers.rb

Store tracer configuration in an in-memory file using libdatadog.
Service Discovery will become the primary entry point of all products built on top of tracing libraries.
Yes. Add Service Discovery capability, enabling the tracer to reliably determine which process are instrumented using Datadog's tracer.
This PR cannot be merged until libdatadog 17.1 and its corresponding gem is released, and libdatadog gem is updated on dd-trace-rb.
Parametric system-tests (cannot be force-enabled yet)

[APMAPI-1068] Process discovery

---

lib/datadog/profiling/exporter.rb

After JSON release 2.11.0, we found this failure: 
https://github.com/DataDog/dd-trace-rb/actions/runs/14641122329/job/41083646804
**What**
Replace JSON.fast_generate with JSON.generate
Yes.  Fix ArgumentError from JSON.fast_generate for old Ruby version

Replace JSON.fast_generate with JSON.generate

---

lib/datadog/tracing/contrib/karafka/monitor.rb
spec/datadog/tracing/contrib/karafka/monitor_spec.rb

This pull request introduces a fix to the `Karafka` integration for Datadog tracing. The `EMPTY_HASH` error is happening intermittently in some of my projects due to inconsistent loaders. In some Ruby projects, we used declarative require, hence they have `EMPTY_HASH`, but some don’t, e.g Rails Railtie, which would load `karafka.rb` file before the EMPTY_HASH is available.
Despite there are some workaround solutions, e.g monkey patch our datadog gem and define the `EMPTY_HASH`, or just define it somewhere globally, but eventually, this error should be fixed asap.
Yes. Tracing: Fix Karafka contrib monitor to avoid referencing Karafka-specific constants that may raise errors due to load order. (updated by @Strech)
**How to test …

[Bug] declaring the missing EMPTY_HASH

---

.github/scripts/publish/verify_check_runs.js
.github/scripts/publish/verify_commit_status.js
.github/workflows/publish.yml

It was slow and hard to debug.
1. Improve the checks in a more performant way (scoped with Github Actions App ID)
2. Enrich debug info with annotation 
3. Extract JS scripts
None.

Refine quality checks before publication

---

lib/datadog/tracing/span_operation.rb
spec/datadog/tracing/span_operation_spec.rb

Adds a warning when customer provides `on_error` argument which is not a `Proc`. Previously the argument was silently ignored.
Better diagnostics of unexpected/incorrect usage of the library
Yes: warn when `on_error` argument is not a `Proc` (and would therefore be ignored)
The existing tests for on_error behavior had incorrect setup and did not actually test the path when on_error argument was not a proc.
Repaired unit tests in this PR.

Warn when ignoring on_error argument due to it not being a proc

---

lib/datadog/core/configuration/option.rb
sig/datadog/core/configuration/option.rbs
sig/datadog/core/configuration/options.rbs
spec/datadog/core/configuration/option_spec.rb

This PR decouples environment variables and programmatic configuration precedence value by adding an environment precedence value.
in https://github.com/DataDog/dd-trace-rb/pull/4592, I need to add a new precedence value higher than environment but lower than programmatic.
Yes. Change behaviour of programmatic configurations previously overwriting environment variables. Unsetting a programmatic configuration will now restore the environment variable value.
I'm not sure if this is considered a breaking change, it seems like this was a bug in the first place (booting an app with an env var, a programmatic config and unsetting that programmatic config previously dismissed the env var too)
**How to test the …

[NO-TICKET] Decouple environment variable from programmatic config precedence

---

spec/datadog/core/configuration/settings_shared_examples.rb
spec/datadog/core/configuration/settings_spec.rb
spec/datadog/tracing/configuration/settings_spec.rb

Refactors the examples to avoid this warning:
```
WARNING: Shared example group 'a binary setting with' has been previously defined at:
/home/w/apps/dd-trace-rb/spec/datadog/core/configuration/settings_spec.rb:12
...and you are now defining it at:
/home/w/apps/dd-trace-rb/spec/datadog/core/configuration/settings_spec.rb:12
```
Warning-clean test suite
None
N/A
Tested manually by running the relevant examples:
```
rspec spec/datadog/core/configuration/settings_spec.rb spec/datadog/tracing/configuration/settings_spec.rb
```

Avoid example redefinition warning in test suite

---

.github/workflows/system-tests.yml

Changes usage of DD_APPSEC_SYSTEM_TESTS_API_KEY GH secret to DD_API_KEY.
Profiling system test is failing due to missing DD_API_KEY. This key is taken from the  DD_APPSEC_SYSTEM_TESTS_API_KEY secret even though we also have the DD_API_KEY secret. The DD_API_KEY secret appears to work therefore let's use it to avoid having to create a second API key.
None
N/A
Existing CI

Try DD_API_KEY instead of DD_APPSEC_SYSTEM_TESTS_API_KEY

---

lib/datadog/tracing/span_operation.rb
lib/datadog/tracing/trace_operation.rb
lib/datadog/tracing/tracer.rb
sig/datadog/tracing/span_operation.rbs
sig/datadog/tracing/trace_operation.rbs
sig/datadog/tracing/tracer.rbs

Replaces global references `Datadog.logger` with injected `logger` instances in tracing operations
Continuing to inject logger into tracer classes
None
N/A
Existing unit tests

Inject logger into tracing operations

---

lib/datadog/core/configuration/agentless_settings_resolver.rb
sig/datadog/core/configuration/agentless_settings_resolver.rbs
spec/datadog/core/configuration/agentless_settings_resolver_spec.rb
spec/support/core_helpers.rb

Adds an agentless settings resolver, which performs the same function as the agent settings resolver to go from settings/Datadog configuration to agent settings, but for agentless operations (currently only telemetry).
Existing code (telemetry transport) did not have the agent settings resolution as an encapsulated concept. As a result, there was low test coverage for this code and for example the timeout was always fixed at 30 seconds.
With the upcoming PR that will change telemetry to use core transport code, telemetry will need to provide agent settings to the transport even in agentless mode. The agentless settings resolver that this PR adds provides the required bridge.
Yes: improve agentless mode telemetry configuration …

DEBUG-3700 agentless settings resolver

---

lib/datadog/core/telemetry/component.rb
lib/datadog/core/telemetry/worker.rb
lib/datadog/core/workers/async.rb
lib/datadog/core/workers/interval_loop.rb
sig/datadog/core/telemetry/worker.rbs
sig/datadog/core/workers/interval_loop.rbs
spec/datadog/core/telemetry/integration/telemetry_spec.rb
spec/datadog/core/telemetry/worker_spec.rb
spec/datadog/di/integration/probe_notifier_worker_spec.rb
spec/support/core_helpers.rb

Adds integration tests for agent and agentless telemetry
Test coverage for upcoming code changes to the core transport within telemetry
None
I added a wait to the termination code for async worker, without it the workers were not terminated within the test's scope and the thread leak checker was complaining.
I added a flushing feature to telemetry worker, since there was no way to wait for the events to be sent before asserting on them being received.
To implement flushing  I added a flag that is set when one iteration of the interval loop is being processed, without it the sending would be happening concurrently with the assertions.
Some of the existing telemetry tests were not properly preparing global …

DEBUG-3700 Telemetry integration test

---

lib/datadog/core/configuration.rb
spec/datadog/core/configuration_spec.rb

This PR adds a default logger during configuration initialization.
During config initialization, stable config will be able to log errors related to reading or parsing config files. But when doing this, configuration isn't loaded. `logger_without_components` still rely on configuration, and will create an infinite loop.
None.
CI.

[NO-TICKET] Add logging during configuration initialization

---

spec/datadog/core/crashtracking/component_spec.rb
spec/datadog/profiling/http_transport_spec.rb
spec/support/http_server_helpers.rb

DRY the code to set up a Webrick server listening on a unix domain socket
UDS testing for telemetry (in https://github.com/DataDog/dd-trace-rb/pull/4630) + DRY existing test code
None
Existing CI

DEBUG-3700 UDS HTTP server helper for test suite

---

.github/workflows/all-green.yml

Add a job in the CI that runs in PR. The job will be a success if all other jobs are skipped/success, and fails otherwise
While it's possible to enforce a green CI policy using GitHub's native "required status checks" feature, doing so requires explicitly listing all job names under branch protection rules. This approach has two key drawbacks:
- It does not support optional jobs
- It introduces ongoing maintenance overhead as the job list evolves
We can also add "job that runs at the end of each workflows", and make them a requirement, but we need to do so for each workflow. This jobs achieve the same, but all-in-one by checking all jobs that are executed for a PR. 
The action used offers a `ignored-name-patterns` parameters`, but right now, …

Add a gatekeeper job for PR

---

.github/workflows/system-tests.yml
lib/datadog/appsec/monitor/gateway/watcher.rb
sig/datadog/appsec/monitor/gateway/watcher.rbs
spec/datadog/appsec/contrib/integration/rack/session_fingerprint_collection_for_business_events_spec.rb

Adds handling of business logic events to be able to finish fingerprinting feature.
The last bits of fingerprinting is to act on business logic events that produced during sign in via auto-instrumentation or SDK.
Yes. AppSec: Add session tracking and fingerprinting support to `devise` and `rails` contribs.
I would like to restructure integration tests to better separate specifically contrib tests from general logic tests. Hence you would see test in the rack contrib (for now)
Second - we have an issue in libddwaf-rb which converts provided `nil` values into empty strings. Another option is to give a value `invalid` which doesn't make much sense, but it is what it is.
This is what's new in system-tests …

[APPSEC-57237] Handle business logic events

---

lib/datadog/core/configuration.rb
spec/datadog/core/configuration_spec.rb

Fix `logger_without_configuration` always being set to DEBUG.
It makes datadog-ci-rb's CI fail.
None.
CI.

[NO-TICKET] Fix logger_without_configuration always being on DEBUG level

---

lib/datadog/core/workers/async.rb

Repairs warning message to reflect the actual timeout
In https://github.com/DataDog/dd-trace-rb/pull/4588 I changed 0.5 second timeout to SHUTDOWN_TIMEOUT per review comments but forgot to update the warning message
None

Repair warning message when worker does not end promptly

---

spec/datadog/core/telemetry/integration/telemetry_spec.rb
spec/spec_helper.rb
spec/support/telemetry_helpers.rb

Adds an integration test for AppHeartbeat telemetry event with payload assertions
Debugging why telemetry is not working properly for dynamic instrumentation - the UI requires telemetry heartbeats to show correct information but these are not seen by the backend 
None
This PR duplicates the `mark_telemetry_started` helper from https://github.com/DataDog/dd-trace-rb/pull/4640
PR is tests only

DEBUG-3573 Add integration test for telemetry app-heartbeat event payloads

---

.github/workflows/parametric-tests.yml

It adds support for PARAMETRIC scenario in forced-tests-list.json
I needed to force execute some parametric tests for StableConfig and ProcessDiscovery
None.

[NO-TICKET] Enable forcing parametric tests

---

lib/datadog.rb
lib/datadog/core/telemetry/event.rb
lib/datadog/di.rb
lib/datadog/di/boot.rb
lib/datadog/di/remote.rb
sig/datadog/di.rbs
spec/datadog/core/telemetry/event_spec.rb
spec/datadog/core/telemetry/integration/telemetry_spec.rb
spec/datadog/di/code_tracker_spec.rb
spec/datadog/di/integration/probe_notifier_worker_spec.rb
spec/loading_spec.rb

Adds the enabled status of dynamic instrumentation to telemetry app-started event
Reporting of DI status is required for DI UI to work correctly as well as for internal DI monitoring/troubleshooting tools
None
To make DI always reportable via telemetry I had to make its configuration defined on all Ruby runtimes including the ones where the product itself does not work (Ruby 2.5, JRuby). Additional loading test was added to verify ability to set DI configuration options on all runtimes; this test mirrors failures I've gotten on rails42 and rails50 system test configurations which use Ruby 2.5 once I started sending DI status to telemetry.
Unit tests  + system tests enabled in …

DEBUG-3573 Report state of dynamic instrumentation to telemetry

---

lib/datadog/core/configuration/components.rb
lib/datadog/core/metrics/client.rb
lib/datadog/core/runtime/metrics.rb
lib/datadog/core/workers/runtime_metrics.rb
sig/datadog/core/metrics/client.rbs
spec/datadog/core/configuration/components_spec.rb
spec/datadog/core/metrics/client_spec.rb
spec/datadog/core/metrics/logging_spec.rb
spec/datadog/core/runtime/metrics_spec.rb
spec/datadog/core/workers/runtime_metrics_spec.rb
spec/datadog/tracing/diagnostics/health_spec.rb

Injects telemetry into metrics client instead of retrieving it from the components tree.
References to the components tree currently create the tree if it does not exist by default (`allow_initialization` option to `components`). This creation is problematic in the test suite (see https://github.com/DataDog/dd-trace-rb/pull/4619). Some components appear to rely on this automatic instantiation (profiling, possibly tracing), therefore removing it is non-trivial. In the meantime, metrics client can have telemetry injected into it to avoid the issue altogether (and remove what is effectively a global variable reference).
None
Existing CI

DEBUG-3700 Inject telemetry into metrics client

---

lib/datadog/core/telemetry/worker.rb
lib/datadog/core/workers/async.rb
spec/datadog/core/telemetry/integration/telemetry_spec.rb
spec/datadog/core/telemetry/worker_spec.rb
spec/datadog/core/workers/async_spec.rb
spec/support/telemetry_helpers.rb

For tests that expect telemetry to be started, the run once state still needs to be reset before setting it to true - because a previous test may have failed initialization (intentionally), and without resetting that failure stays around for subsequent tests.
This PR also adds additional assertions on return values I used for debugging to ensure workers are started and events are accepted.
Flaky telemetry tests in CI
None
Existing CI

Properly reset telemetry state in tests

---

spec/datadog/profiling/stack_recorder_spec.rb

This PR adds more context and validation to two tests that we've seen failing in test-asan CI:
* https://github.com/DataDog/dd-trace-rb/actions/runs/14973937437/job/42061305617?pr=4638
* https://github.com/DataDog/dd-trace-rb/actions/runs/14697248627/job/41240596719?pr=4588 (same as above)
* https://github.com/DataDog/dd-trace-rb/actions/runs/14783286431/job/41506701640?pr=4619
It's not clear to me exactly what's wrong and why they are failing, so I'm adding more details so I can debug the issue the next time it happens.
Always aim to have zero flaky specs.
None.
N/A
These extra assertions/info will only show up when the tests fail again -- for now all we can validate is that …

[NO-TICKET] Add more context to profiling specs that failed in test-asan

---

.github/workflows/test-memory-leaks.yaml

This PR removes the `test-asan` step in CI as it's currently flaky and I wasn't able to debug the issue or skip it.
This run
https://github.com/DataDog/dd-trace-rb/actions/runs/15112212122/job/42474072954?pr=4664 shows this step failing:
```
Randomized with seed 3003
......................................................1.8.1
==2610==Running thread 2303 was not suspended. False leaks are possible.
==2610==Running thread 2304 was not suspended. False leaks are possible.
==2610==Processing thread 2606.
==2610==Stack at 0x7fff7be8d000-0x7fff7ce8d000 (SP = 0x7fff7ce81630).
==2610==TLS at 0x7f0d63c88b80-0x7f0d63c89cc0.
==2610==DTLS 5 at 0x512000597940-0x512000597a78.
==2610==DTLS 6 at 0x5020000d0e30-0x5020000d0e38.
==2615==Running thread 2303 was not suspended. False …
```

[NO-TICKET] Remove "test-asan" profiler check due to flakiness

---

docs/GettingStarted.md

Address the comments of [Update document v2.16.0](https://github.com/DataDog/dd-trace-rb/pull/4662#issuecomment-2897973252)
No.

chore: improve error tracking getting started doc

---

lib/datadog/core/telemetry/event.rb
lib/datadog/core/telemetry/event/app_client_configuration_change.rb
lib/datadog/core/telemetry/event/app_closing.rb
lib/datadog/core/telemetry/event/app_dependencies_loaded.rb
lib/datadog/core/telemetry/event/app_heartbeat.rb
lib/datadog/core/telemetry/event/app_integrations_change.rb
lib/datadog/core/telemetry/event/app_started.rb
lib/datadog/core/telemetry/event/base.rb
lib/datadog/core/telemetry/event/distributions.rb
lib/datadog/core/telemetry/event/generate_metrics.rb
lib/datadog/core/telemetry/event/log.rb
lib/datadog/core/telemetry/event/message_batch.rb
sig/datadog/core/telemetry/event.rbs
sig/datadog/core/telemetry/event/app_client_configuration_change.rbs
sig/datadog/core/telemetry/event/app_closing.rbs
sig/datadog/core/telemetry/event/app_dependencies_loaded.rbs
sig/datadog/core/telemetry/event/app_heartbeat.rbs
sig/datadog/core/telemetry/event/app_integrations_change.rbs
sig/datadog/core/telemetry/event/app_started.rbs
sig/datadog/core/telemetry/event/base.rbs
sig/datadog/core/telemetry/event/distributions.rbs
sig/datadog/core/telemetry/event/generate_metrics.rbs
sig/datadog/core/telemetry/event/log.rbs
sig/datadog/core/telemetry/event/message_batch.rbs

Changes `Datadog::Core::Telemetry::Event` to be a module instead of a class
https://github.com/DataDog/dd-trace-rb/pull/4671 split the individual event classes, and now it is clear that the `Event` container itself doesn't have any code and should be a module for namespacing.
None
N/A
Existing unit tests

DEBUG-3573 Change telemetry event class into module

---

spec/datadog/core/telemetry/event/app_client_configuration_change_spec.rb
spec/datadog/core/telemetry/event/app_closing_spec.rb
spec/datadog/core/telemetry/event/app_dependencies_loaded_spec.rb
spec/datadog/core/telemetry/event/app_heartbeat_spec.rb
spec/datadog/core/telemetry/event/app_integrations_change_spec.rb
spec/datadog/core/telemetry/event/app_started_spec.rb
spec/datadog/core/telemetry/event/distributions_spec.rb
spec/datadog/core/telemetry/event/generate_metrics_spec.rb
spec/datadog/core/telemetry/event/log_spec.rb
spec/datadog/core/telemetry/event/message_batch_spec.rb
spec/support/telemetry_helpers.rb

Addresses review feedback in https://github.com/DataDog/dd-trace-rb/pull/4685:
. removed `event_class` alias that no longer has logic
. added `describe payload` blocks to clarify what the subject is for those tests
. added a configuration reset after the test that enables SCA
Review comments in https://github.com/DataDog/dd-trace-rb/pull/4685
None
Existing tests

DEBUG-3573 improve telemetry event tests

---

benchmarks/profiling_http_transport.rb
lib/datadog/profiling/collectors/code_provenance.rb
lib/datadog/profiling/flush.rb
spec/datadog/profiling/collectors/code_provenance_spec.rb
spec/datadog/profiling/flush_spec.rb
spec/datadog/profiling/http_transport_spec.rb

Replace all `JSON.fast_generate` with `JSON.generate` following `JSON.fast_generate`'s deprecation since [ruby/json v2.11.0](https://github.com/ruby/json/releases/tag/v2.11.0)
Related: https://github.com/DataDog/dd-trace-rb/pull/4602
After our app updated `ruby/json` to `>= 2.11.0`, Datadog's profillers start to output a lot of warnings to puma/sidekiq logs (once per minute).
```
.../datadog-2.16.0/lib/datadog/profiling/collectors/code_provenance.rb:45: warning: JSON.fast_generate is deprecated and will be removed in json 3.0.0, just use JSON.generate
.../datadog-2.16.0/lib/datadog/profiling/flush.rb:35: warning: JSON.fast_generate is deprecated and will be removed in json 3.0.0, just use JSON.generate
```
Yes. Fix triggering …

Replace all JSON.fast_generate with JSON.generate

---

spec/datadog/core/telemetry/integration/full_integration_spec.rb
spec/spec_helper.rb
spec/support/platform_helpers.rb

Skips telemetry integration tests making use of `any_instance_of` on JRuby 9.2.
The tests are failing with the following error:
```
2025-06-02T18:44:11.0859185Z Datadog::Core::Telemetry::Worker
2025-06-02T18:44:11.0865028Z   #stop
2025-06-02T18:44:11.1007491Z warning: thread "Datadog::Core::Telemetry::Worker (Ruby-0-Thread-1529@Datadog::Core::Telemetry::Worker: /__w/dd-trace-rb/dd-trace-rb/spec/spec_helper.rb:290)" terminated with exception (report_on_exception is true):
2025-06-02T18:44:11.1008845Z NoMethodError: undefined method `send_event' for #<Datadog::Core::Telemetry::Worker:0x1a61064d>
2025-06-02T18:44:11.1009429Z       started! at /__w/dd-trace-rb/dd-trace-rb/lib/datadog/core/telemetry/worker.rb:183
2025-06-02T18:44:11.1009967Z …
```

Skip telemetry integration tests using any_instance_of on JRuby 9.2

---

.github/scripts/update_reference.rb
.github/workflows/parametric-tests.yml
.github/workflows/system-tests.yml
.github/workflows/update-system-tests.yml

Pointing at system tests `main` branch creates inconsistent result.
An workflow to automate the update process with a pinned version 
For testing, it creates: https://github.com/DataDog/dd-trace-rb/pull/4701
None.

Auto update system tests

---

benchmarks/profiling_string_storage_intern.rb

This reverts commit 569bf568b80e9615027a8d0c41a8a941deeb9981.
We had previously reverted that commit in
https://github.com/DataDog/dd-trace-rb/pull/4376 but due to a bug had to undo all the heap profiling-related changes in https://github.com/DataDog/dd-trace-rb/pull/4409 .
After https://github.com/DataDog/dd-trace-rb/pull/4460 gets merged, we can finally enable this benchmark again.
The benchmark was disabled for the reason mentioned in the comment.
None.
I'm going to open this PR stacked on top of
https://github.com/DataDog/dd-trace-rb/pull/4460, but this PR should only be merged after that other PR is merged to master.
Validate this benchmark is now running in the …

[PROF-11405] Revert "Temporary disable benchmark to make CI happy", second try

---

.github/workflows/parametric-tests.yml
.github/workflows/system-tests.yml

Switches system tests reference to https://github.com/DataDog/system-tests/pull/4719 to run our CI against that PR, which retries docker pull in cases when docker pull says the image was not found.
Flaky CI
None
You would expect that pulling the image would not end with 'image not found" on the destination (localhost, in this case) as the problem. Might be something within docker racing with itself, such that it does retrieve the image but then fails to see the image in some other code?
This PR also incorporates the fix in https://github.com/DataDog/system-tests/pull/4718.
I would like this PR  to merged to master and stay in master for a week or so, and observe if the number …

Retry postgres:alpine docker pulls in system tests

---

ext/datadog_profiling_native_extension/heap_recorder.c
ext/datadog_profiling_native_extension/ruby_helpers.c
ext/datadog_profiling_native_extension/ruby_helpers.h
ext/datadog_profiling_native_extension/stack_recorder.c
lib/datadog/profiling/stack_recorder.rb
sig/datadog/profiling/stack_recorder.rbs
spec/datadog/profiling/stack_recorder_spec.rb

This PR fixes a rare situation where the profiler would stop during serialization of heap profiling samples with an error message:
```
WARN -- datadog: [datadog] Profiling::Scheduler thread error. Cause: RuntimeError BUG: full_update should not be triggered during another update Location: .../lib/datadog/profiling/stack_recorder.rb:63:in `_native_serialize'
```
This issue happened due to an unexpected thread switch during heap profiling metadata operations.
Fix rare heap profiling bug, which is extra important now that we're eclaring it as preview with the next release.
Yes. Fix profiler stopping due to bug in heap profiling serialization.
Understanding this rare bug took some amount of staring at the …

[PROF-11956] Fix profiler stopping due to bug in heap profiling serialization

---

.github/forced-tests-list.json
.vscode/settings.json
ext/libdatadog_api/library_config.c
lib/datadog/core/configuration/stable_config.rb

Uncomments code related to hands off config. Removes a call to outdated libdatadog API.
This PR relies solely on system-tests as there are no unit tests. It passes all `Test_Stable_Config_Default` system-tests when run locally. See: https://github.com/DataDog/system-tests/pull/4653
Enable Hands Off Config
Yes. Add configuration from local file and from fleet automation.
Once this PR is merged, please merge this one: https://github.com/DataDog/system-tests/pull/4653

[APMAPI-1116] Enable Hands Off Config

---

lib/datadog/core/configuration/components.rb
lib/datadog/core/process_discovery.rb
lib/datadog/core/process_discovery/tracer_memfd.rb
sig/datadog/core/process_discovery/tracer_memfd.rbs
spec/datadog/core/configuration/components_spec.rb

This PR moves call to native code that was originally located in `core/configuration/components.rb` to `core/process_discovery/tracer_memfd.rb`
[Comment](https://github.com/DataDog/dd-trace-rb/pull/4649#discussion_r2161162931) on "Enable Service Discovery" PR 
None.
CI should still work the same

[NO-TICKET] Hide native code for memfd close

---

benchmarks/profiling_sample_loop_v2.rb

This PR enables the native filenames benchmark that was added in https://github.com/DataDog/dd-trace-rb/pull/4745 but not enable [because of](https://github.com/DataDog/dd-trace-rb/pull/4745#discussion_r2167144621):
> So... our current benchmarking setup is... weird in this regard.
>
> Specifically, it checks out this branch, runs the benchmarks, and then it copies the benchmarks to a temp folder, and then checks out master, and runs the benchmarks from this branch with master.
>
> That's.... cool if you add a new benchmark for something, and then modify some existing code to make things faster, and boom, in your PR you can see the before/after right away.
>
> But whenever the benchmark is not backwards-compatible with master (e.g. some new arguments get added, …

[NO-TICKET] Minor: Enable native filenames benchmark

---

ext/datadog_profiling_native_extension/collectors_cpu_and_wall_time_worker.c
ext/datadog_profiling_native_extension/collectors_stack.c
ext/datadog_profiling_native_extension/collectors_stack.h
ext/datadog_profiling_native_extension/collectors_thread_context.c
ext/datadog_profiling_native_extension/collectors_thread_context.h
ext/datadog_profiling_native_extension/ruby_helpers.h
lib/datadog/core/configuration/settings.rb
lib/datadog/profiling/collectors/cpu_and_wall_time_worker.rb
lib/datadog/profiling/component.rb
sig/datadog/profiling/collectors/cpu_and_wall_time_worker.rbs
spec/datadog/core/configuration/settings_spec.rb
spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb
spec/datadog/profiling/component_spec.rb

This PR picks up from where https://github.com/DataDog/dd-trace-rb/pull/4750 left off and finishes the new "sample from inside the signal handler" feature.
Most of the preparation work was already included in the prior PR so this PR:
* Adds a new setting `c.profiling.advanced.sighandler_sampling_enabled` / `DD_PROFILING_SIGHANDLER_SAMPLING_ENABLED` environment variable
* Uses this setting to decide when to use `thread_context_collector_prepare_sample_inside_signal_handler`
* ...and it sprinkles a few compiler barriers to make sure we get a consistent view of the state of the profiler from inside the signal handler.
On older Ruby versions, the profiler wasn't able to sample from inside the signal handler. This is no longer the case since …

[PROF-12098] Profiler: Allow sampling from inside the signal handler to improve accuracy

---

lib/datadog/core/configuration/settings.rb
spec/datadog/core/configuration/settings_spec.rb

In https://github.com/DataDog/dd-trace-rb/pull/4785 we added a setting to enable sampling from inside the signal handler, but made it off by default.
The plan was to wait for validation in our test apps before flipping the default. The test apps have now been running for a while with this feature without issue, so we're ready to enable it.
This PR changes the setting to be on by default on Ruby 3.2.5+/3.3.4+.
The Ruby versions listed include https://github.com/ruby/ruby/pull/11036 (as well as other prior fixes) and thus it's safe to use this feature, which improves accuracy of profiling data.
See [original PR](https://github.com/DataDog/dd-trace-rb/pull/4785) for more details.
Yes. Profiler: Enable sample from inside signal …

[PROF-12098] Profiler: Enable sample from inside signal handler by default on modern Rubies

---

lib/datadog/appsec/api_security/route_extractor.rb
sig/datadog/appsec/api_security/route_extractor.rbs
spec/datadog/appsec/api_security/route_extractor_spec.rb

This PR fixes an exception in AppSec RouteExtractor that happens in Rails 8.0 and above for not-found routes. The error only happens if the application has any routes with constraints, such as the subdomain.
Issue #4784 
Yes. AppSec: Fix an error in RouteExtractor for not-found routes.
None.
Manual testing with app generator and CI.

Fix an error in AppSec route extractor for not-found routes in Rails 8

---

lib/datadog/profiling.rb
lib/datadog/profiling/exporter.rb
lib/datadog/profiling/sequence_tracker.rb
lib/datadog/profiling/tag_builder.rb
sig/datadog/profiling/exporter.rbs
sig/datadog/profiling/sequence_tracker.rbs
sig/datadog/profiling/tag_builder.rbs
spec/datadog/profiling/exporter_spec.rb
spec/datadog/profiling/sequence_tracker_spec.rb
spec/datadog/profiling/tag_builder_spec.rb

This PR adds a new tag to reported profiles: `profile_seq`. This tag provides a sequence number for reported profiles for a given runtime-id.
This tag has already been adopted by the Go and .NET profilers, and is useful for use-cases such as:
* Focus on, or exclude application boot time (which usually has quite different profiles)
* Clearly identify when profiles are missing (because e.g. they failed to be reported and there's gaps in the sequence)
Yes. Profiling: Tag profiles with sequence number
This feature is quite straightforward, the only weird part is that we carry state across profiler reconfigurations (e.g. state is a singleton), and we also need to reset it after the app forks, because …

[NO-TICKET] Tag profiles with sequence number

---

lib/datadog.rb
lib/datadog/di.rb
spec/loading_spec.rb

Rearranges DI code so that the trigger for DI initialization is in `datadog` require rather than `datadog/di`.
If `DD_DYNAMIC_INSTRUMENTATION_ENABLED` is set to true and we require `datadog/di`, there was an error:
```
1) loading of products datadog/di produces no output
Failure/Error: raise("Test script failed with exit status #{status.exitstatus}:\n#{out}") unless status.success?
RuntimeError:
Test script failed with exit status 1:
/home/w/apps/dd-trace-rb/lib/datadog/di/boot.rb:28:in `<top (required)>': undefined method `logger' for module Datadog (NoMethodError)
Datadog.logger.debug("di: activating code tracking")
^^^^^^^
from /home/w/apps/dd-trace-rb/lib/datadog/di.rb:43:in `require_relative'
from …
```

Repair loading of DI code when DI is enabled via environment variable

---

lib/datadog/appsec/instrumentation/gateway/argument.rb
lib/datadog/kit/appsec/events/v2.rb
sig/datadog/appsec/instrumentation/gateway.rbs
sig/datadog/appsec/instrumentation/gateway/argument.rbs
sig/datadog/kit/appsec/events/v2.rbs
sig/datadog/kit/identity.rbs
spec/datadog/kit/appsec/events/v2_spec.rb

Introduces second version of the Business Logic Events SDK.
We are pushing better SDK API that will suite to the actual data most of the time available at hand when emitting business logic events.
Yes. AppSec: Added Business Logic Events SDK v2.
There is a shortcut we take in order to compute service entry trace/span. In V2 you can control it, but in V2 there is no such functionality. Unfortunately, tracer doesn't support such information, even tho there is a functionality we would like to have, but it's hidden on different layer of the stack.
CI + ST should cover 99% 😬

[APPSEC-58115] Add Business Logic Events SDK v2

---

lib/datadog/profiling/collectors/info.rb
sig/datadog/profiling/collectors/info.rbs
spec/datadog/profiling/collectors/info_spec.rb

This PR tweaks the information that gets attached to every profile to include any GC tuning settings that were present.
This information can be seen in the "System Info" section of the single profile view.
As more GC tuning settings get added to Ruby, it's useful for performance reasons to know if a given app is operating with the defaults or something has been tweaked.
See <https://mailchi.mp/railsspeed/stop-tuning-rubys-gc> for an interesting discussion of this.
We want to make it easier to spot these GC tuning settings (maybe even automatically in the future?).
Yes. Report GC tuning environment variables with profiles.
Note that only settings that have been changed from the default are sent, as it …

[PROF-12143] Report GC tuning environment variables with profiles

---

benchmarks/profiling_sample_loop_v2.rb
ext/datadog_profiling_native_extension/collectors_stack.c
ext/datadog_profiling_native_extension/private_vm_api_access.c
ext/datadog_profiling_native_extension/private_vm_api_access.h
spec/datadog/profiling/collectors/stack_spec.rb

This PR changes how we do stack sampling and truncation in the profiler by:
1. Removing the count of frames truncated from the reported stack. This allows us to get rid of the `stack_depth_for` which actually had an off-by-one bug (at least -- there may have been other bugs hiding in there because it calculated the number of frames differently from `rb_profile_frames`)
2. Moving the truncated frames marker to the leaf frame, mirroring the behavior in the Python profiler
3. Reverse the direction of stack sampling to improve cache hit performance
I started this PR to fix the off-by-one in the "frames omitted frame" and to align the Ruby stack truncation behavior with Python, and realized that the new truncation logic could also be taken advantage of …

[PROF-11898] Switch profiler stack truncation strategy and improve sampling performance

---

.github/workflows/parametric-tests.yml
.github/workflows/system-tests-official.yml
.github/workflows/system-tests.yml
.gitlab-ci.yml
CHANGELOG.md

* AppSec: Added Business Logic Events SDK v2. (#4802)
* Tracing: Add `record_exception` API to capture and attach error information to spans via span events. (#4771)
* Tracing: Add `:cache_store` option to ActiveSupport integration to allow tracing only specified cache backends. (#4693)
* SSI: Rework SSI from the ground up. (#4366)
* Profiling: Switch profiler stack truncation strategy and improve sampling performance (#4819)
* Profiling: Report GC tuning environment variables with profiles (#4813)
* Profiling: Tag profiles with sequence number (#4794)
* Profiling: Enable sample from inside signal handler by default on modern Rubies (#4786, #4785)
* Core: Fix emitting duplicate warnings on agent configuration mismatch (#4814)
* Appsec: Fix an error in AppSec route extractor for not-found …

Bump to version 2.19.0

---

docs/GettingStarted.md

Adds documentation for how to add SpanEvents to APM spans. This feature has exited for a bit, but was undocumented.
No

Add span events documentation

---

docs/DevelopmentGuide.md

Adds documentation so that new users are not stuck running `bundle exec rake test:main` when they make a change in a single file.
No.

Document how to run individual tests in the DevelopmentGuide

---

.github/workflows/system-tests-official.yml

Adds the id-token permission to system tests.
This will allow requesting an OIDC token which is needed to get the current ref from a separate repository.
None.

add id-token write permission to system tests

---

.github/workflows/system-tests.yml
.gitlab-ci.yml
CHANGELOG.md

* Tracing: Add capability to add [W3C Baggage](https://www.w3.org/TR/baggage/#example) headers to the local root span as span tags (#4716)
* AppSec: Add WAF analysis of the responses with JSON body (#4848)
* Dynamic Instrumentation: Live Debugger: Add support for specifying probes in a file via `DD_DYNAMIC_INSTRUMENTATION_PROBE_FILE` environment variable (#4838)
* Core: Expand generated warning and error messages during `libdatadog` build (#4831)
* AppSec: Rework handling of Remote Config updates for multi-threaded web servers (#4833)
* AppSec: Update security tags for Business Logic Events and User Events SDK v1 and v2 (#4851)
* Tracing: Fix constants resolution for Rails runner (#4863)

Bump to version 2.20.0

---

lib/datadog/di/probe_notification_builder.rb
spec/datadog/di/probe_notification_builder_spec.rb

Changes `gsub` usage to block form from string second argument, which performs unwanted interpolation.
`gsub` with string arguments still runs them through the regular expression engine and interpolates backslashes and some special characters in the replacement string. The desired behavior was a simple string replacement.
Yes: DI: fix incorrect template expression evaluation in some cases
The existing code did not grant access to anything that shouldn't have been accessible (i.e. the #{} syntax). It would replace double backslashes with single backslashes, escapes like `\n` with the corresponding literals like the newline, and include parts of the string into the string via `\\``. 
Additionally, the UI …

Dynamic Instrumentation: fix gsub usage in evaluate_template

---

spec/datadog/di/serializer_spec.rb

Adds unit tests for serializing exception classes.
Exception capture would include the exceptions into dynamic instrumentation payloads, yet there was no existing test coverage for how they would be serialized.
None
For safety reasons we do NOT serialize exception messages - I don't see how to do so while guaranteeing that we do not call customer code. It is expected that custom exceptions may have their `message` method overwritten.
Unfortunately this means only the exception class would be available in dynamic instrumentation along with any instance variables set by the custom exception classes.

DI: add exception serialization tests

---

.github/PULL_REQUEST_TEMPLATE.md

Expands the instructions for the change log entry in pull request template to state that the entries should be self-contained and readable by customers.
When we release, the person doing the releasing often has to edit change log entries, but this person has not made the relevant code changes and is often not familiar with all of the details.
The goal of this PR is to encourage higher quality change log entries in PRs, ideally such that they can be copied into release notes without further editing.
None

Clarify expectations of change log entries

---

.github/workflows/system-tests.yml

This PR just cleans up the pipeline by removing the reference to the no-longer-existing scenario.
The scenario APPSEC_REQUEST_BLOCKING has been merged into APPSEC_BLOCKING_FULL_DENYLIST in the system-tests project. This means tests that were previously run under APPSEC_REQUEST_BLOCKING will now execute using APPSEC_BLOCKING_FULL_DENYLIST (https://github.com/DataDog/system-tests/pull/5277)
No. (updated by @Strech)

Remove APPSEC_REQUEST_BLOCKING as was merged into APPSEC_BLOCKING_FULL_DENYLIST

---

lib/datadog/di/instrumenter.rb
lib/datadog/di/serializer.rb
sig/datadog/di/serializer.rbs
spec/datadog/di/instrumenter_spec.rb

Implements condition evaluation for method probes: if condition for the probe was set in UI, the instrumentation will only be called if the condition is met.
Feature parity with other languages.
Yes: dynamic instrumentation: support conditions for method probes
Tests added

DI: Condition evaluation for method probes

---

spec/datadog/di/hook_method.rb
spec/datadog/di/instrumenter_spec.rb

Renames a method called `exception` in the test suite to `exception_method`.
The previous name was confusing when it was mentioned in e.g. trace point inspection.
None

DI: rename test exception method to exception_method

---

.github/workflows/system-tests.yml

This PR just cleans up the pipeline by removing the reference to the no-longer-existing scenario (REMOTE_CONFIG_MOCKED_BACKEND_ASM_DD_NOCACHE) and adds the new one (APPSEC_API_SECURITY_RC)
The scenario REMOTE_CONFIG_MOCKED_BACKEND_ASM_DD_NOCACHE has been merged into APPSEC_API_SECURITY_RC in the system-tests project. This means tests that were previously run under REMOTE_CONFIG_MOCKED_BACKEND_ASM_DD_NOCACHE will now execute using APPSEC_API_SECURITY_RC (https://github.com/DataDog/system-tests/pull/5363)

Replace merged REMOTE_CONFIG_MOCKED_BACKEND_ASM_DD_NOCACHE with APPSEC_API_SECURITY_RC

---

.github/workflows/_unit_test.yml
tasks/github.rake

This PR adds a seed input to the CI Unit tests workflow, which should give the same batches output, and same RSpec seeds.
It should be easier to reproduce flaky tests
None.
Once merged, workflow_dispatch

[NO-TICKET] Add seed to CI unit tests

---

lib/datadog/core/remote/component.rb

Uses Mutex#synchronize instead of manual  lock & unlock calls to (hopefully) properly unlock the mutex in remote config worker.
Flaky tests on JRuby: https://github.com/DataDog/ruby-guild/issues/256, https://datadoghq.atlassian.net/browse/LANGPLAT-871
The issue is that sometimes mutex is attempted to be unlocked when it is not locked.
Yes: core/fix: improve locking code for remote configuration worker
I also attempted this alternate diff which also fixed the issue:
```
diff --git a/lib/datadog/core/remote/component.rb b/lib/datadog/core/remote/component.rb
index 18e33bea25..f73d9742b6 100644
--- a/lib/datadog/core/remote/component.rb
+++ b/lib/datadog/core/remote/component.rb
@@ -137,11 +137,13 @@ module …
```

Use Mutex#synchronize to solve JRuby mutex not locked error

---

spec/datadog/di/hook_line_load.rb
spec/datadog/di/hook_line_recursive.rb
spec/datadog/di/hook_line_targeted.rb
spec/datadog/di/hook_method.rb
spec/datadog/di/instrumenter_spec.rb
spec/datadog/di/integration/everything_from_remote_config_spec.rb
spec/datadog/di/integration/instrumentation_integration_test_class.rb
spec/datadog/di/integration/instrumentation_integration_test_class_2.rb
spec/datadog/di/integration/instrumentation_integration_test_class_3.rb
spec/datadog/di/integration/instrumentation_integration_test_class_4.rb
spec/datadog/di/probe_file_loader_spec.rb

Adjusts test suite code to not produce Ruby warnings
Many Ruby warnings emitted when running DI tests
None
Existing CI

DI: eliminate Ruby warnings in test suite

---

lib/datadog/appsec/api_security/endpoint_collection/rails_routes_serializer.rb
lib/datadog/appsec/configuration/settings.rb
lib/datadog/appsec/contrib/rails/patcher.rb
lib/datadog/core/configuration/supported_configurations.rb
sig/datadog/appsec/api_security/endpoint_collection/rails_routes_serializer.rbs
sig/datadog/appsec/contrib/rails/patcher.rbs
spec/datadog/appsec/api_security/endpoint_collection/rails_routes_serializer_spec.rb
spec/datadog/appsec/configuration/settings_spec.rb
spec/datadog/appsec/integration/contrib/rails/endpoint_collection_spec.rb
supported-configurations.json

This PR adds Endpoint Collection feature for AppSec.
We want to collect routing information for Rails apps even for endpoints that don't get traffic.
None. This is internal change.
This PR fixes flakyness in the integration test by adding Devise.
APPSEC-59522
CI

Add Endpoint Collection for AppSec

---

integration/images/ruby/2.1/Dockerfile
integration/images/ruby/2.2/Dockerfile
integration/images/ruby/2.3/Dockerfile
integration/images/ruby/2.4/Dockerfile
integration/images/ruby/2.5/Dockerfile
integration/images/ruby/2.6/Dockerfile
integration/images/ruby/2.7/Dockerfile
integration/images/ruby/3.0/Dockerfile
integration/images/ruby/3.1/Dockerfile
integration/images/ruby/3.2/Dockerfile
integration/images/ruby/3.3/Dockerfile
integration/images/ruby/3.4/Dockerfile

Change the base images of integrations to use our https://github.com/DataDog/images-rb images.
Propagating @lloeki 's suggestion in #4924!
No
Green CI.

Use images-rb base images for integrations
