.rubocop.yml, ddtrace.gemspec, lib/ddtrace/encoding.rb, lib/ddtrace/transport.rb, lib/ddtrace/writer.rb, test/benchmark_test.rb, test/encoding_test.rb, test/helper.rb, test/transport_test.rb
Adds support to the ``trace-agent`` API version ``0.3``. This new API uses msgpack as a new communication format by default. The API also support JSON encoding if users want to send their traces manually.
If a ``404`` is hit, it means that the API is not available and so we have to downgrade the API level to a stable version (``JSONEncoder`` with the ``v0.2`` API at the time of writing).
The flow is:
* use ``MsgpackEncoder`` as default
* at the first call (services or traces are the same), read the status code
* if the response is a ``404`` or a ``415``, downgrade and re-try the call with the stable version
* in any other cases, keep the current encoder and API version (a ``5xx`` or ``4xx`` doesn't mean we should change the encoder because probably we've a different problem)
I includes …
=> [core] provide support for trace-agent API v0.3

lib/ddtrace/version.rb
Just a bumping for master release. The use of a single thread has been not included in the ``0.2.0``
=> bumping version 0.1.5 => 0.2.0

lib/ddtrace/tracer.rb, test/tracer_test.rb
Fixes https://github.com/DataDog/dd-trace-rb/issues/41
When calling Datadog::Tracer#trace with a block, the return value of the
block will be used as the return value.
=> Use return value of block

lib/ddtrace/contrib/rails/core_extensions.rb, test/contrib/rails/redis_cache_test.rb
The bug did not show up yet, but technically, `fetch` should forward a block to `super()` when monkey-patched. See https://github.com/rails/rails/blob/master/activesupport/lib/active_support/cache.rb#L283
=> [redis/rails] passing block when calling fetch

lib/ddtrace/contrib/rails/action_controller.rb, lib/ddtrace/contrib/rails/action_view.rb, lib/ddtrace/contrib/rails/active_support.rb
This PR does two things:
- address a possible issue on `process_action.action_controller`, when `:status` is not defined
- in a more general manner, try and finish spans whatever happens. Still log errors, but at least flush and send spans once they've been created.
=> [rails] fix non-finishing span problem

.rubocop.yml, test/helper.rb
Tests which used to pass on CI now fail due to rubocop update. This patch should fix it.
=> Rubocop fixes

docs/GettingStarted, lib/ddtrace.rb, lib/ddtrace/contrib/rails/framework.rb, test/contrib/rails/apps/application.rb, test/contrib/rails/apps/rails3.rb, test/contrib/rails/apps/rails4.rb, test/contrib/rails/apps/rails5.rb, test/contrib/rails/redis_cache_test.rb, test/contrib/redis/redis_test.rb, test/helper.rb
Disables Rails auto-instrumentation by default. This means that adding the gem to the ``Gemfile`` is not enough to enable the tracing. Users must add the initializer file so that:
```ruby
Rails.configuration.datadog_trace = {
auto_instrument: true,
auto_instrument_redis: true,
default_service: 'my-rails-app'
}
```
If users want to activate the tracing only for some environments, they may:
```ruby
tracer_status = Rails.env.staging? || Rails.env.production?
Rails.configuration.datadog_trace = {
auto_instrument: tracer_status,
auto_instrument_redis: tracer_status,
default_service: 'my-rails-app'
}
```
In this way, is up to users in which environment enable the Rails auto-instrumentation, so that installing our gem will not have any kind of side-effect until users enable the gem.
As a side …
=> [rails] Rails auto-instrumentation is disabled by default

circle.yml
JRuby is currently in the experimental support and an incompatibility issue was fixed but not deployed in the latest version of the agent. Because the current Ruby CI doesn't run our integration tests with the ``trace-agent`` master branch, it will always fail.
* enable the JRuby CI before making a new ``dd-trace-rb`` release
* test Ruby integrations with the master branch and the latest released version
=> [ci] disable JRuby tests; it should be tested with the agent master branch

lib/ddtrace/contrib/rails/active_record.rb, lib/ddtrace/contrib/rails/framework.rb
Related to: #40 
Avoids conditional require for ``ddtrace/contrib/rails/active_record`` module. In some configuration (and/or for order import), it's possible that the constant ``Datadog::Contrib::Rails::ActiveRecord`` is not initialized:
```
Detected Rails >= 3.x. Enabling auto-instrumentation for core components.
.../dd-trace-rb-1b724b8af03c/lib/ddtrace/contrib/rails/framework.rb:97:in `auto_instrument': uninitialized constant Datadog::Contrib::Rails::ActiveRecord (NameError)
```
The loading / auto instrumentation behavior is not changed and everything behaves like before.
=> [rails] avoid conditional require for active_record contrib module

circle.yml, docs/GettingStarted, lib/ddtrace/contrib/rails/action_view.rb, lib/ddtrace/contrib/rails/active_support.rb, lib/ddtrace/contrib/rails/core_extensions.rb, lib/ddtrace/contrib/rails/framework.rb
Adds cache support to Passenger. Because of an implementation detail related to how Rails 3.x [stores the cache instrumentation][1], Passenger didn't work properly. Spans were correctly created using the ``start_cache_*.active_support`` signals, but they were never closed because ``cache_*.active_support`` were not activated.
This patch ensures that cache instrumentation is activated if the ``auto_instrument`` flag is on.
[1]: https://github.com/rails/rails/blob/v3.2.22.5/activesupport/lib/active_support/cache.rb#L175-L177
=> [rails] adding cache support for Passenger

lib/ddtrace.rb, lib/ddtrace/contrib/rails/framework.rb
Reduces the logger verbosity, making clear that if ``redis-rails`` module is not found, only ``redis-rails`` is not instrumented. Redis will be instrumented as usual (if available).
=> [rails] reduce logs verbosity

Appraisals, circle.yml, ddtrace.gemspec, docs/GettingStarted, gemfiles/rails5_mysql2.gemfile, gemfiles/rails5_postgres.gemfile, gemfiles/rails5_postgres_redis.gemfile, lib/ddtrace/contrib/rails/framework.rb, test/contrib/rails/test_helper.rb
* Ruby ``2.4.0`` is officially supported
* updates the test matrix to support Rails ``5.0.1``
* Rails tests are not launched for Ruby 2.4.0 until new versions are released
* updates development dependencies
=> [ci] updating testing matrix

circle.yml, ddtrace.gemspec, docs/GettingStarted
* CircleCI **will not** publish a stable version after a new tag is pushed
* to publish a new version use the built-in ``rake release`` command
* the ``rake release`` command should be launched by our CI
=> [packaging] RubyGems is used to publish stable versions

Rakefile, circle.yml
* overrides system rubies so that cache should not be invalidated (if a new version of bundler is available, the package will be updated and the right version is used)
* uses x3 parallel execution reducing execution time
[Example execution][1]
[1]: https://circleci.com/gh/DataDog/dd-trace-rb/588
The workload is manually configured so a better approach is preferred. Anyway it's good enough at this time and it improves tests execution. Further improvement should include caching Docker containers (and maybe using Ruby containers to run tests), but actually CircleCI doesn't support a good docker layers caching. It only provides a workaround. Fair enough for now.
=> Improving CI testing time

lib/ddtrace/span.rb, lib/ddtrace/tracer.rb, test/workers_test.rb
It's technically possible to create a span without a service, and this is valid, it should inherit the service from its parent in that case. However root spans have no parent so it's impossible to infer/guess a valid name. This patch provides a default value (`ruby`) in that case.
=> [span] adding a default 'ruby' service is none is given

lib/ddtrace/contrib/rails/active_support.rb, test/contrib/rails/cache_test.rb, test/contrib/rails/redis_cache_test.rb
Discards parameters like:
```
[:redis_store, "redis://localhost:6379/0", {:expires_in=>60 minutes}]
```
The ``rails.cache.backend`` will only contains ``redis_store`` value.
=> [rails] discard parameters from the cache_store configuration

.rubocop.yml, lib/ddtrace/contrib/elasticsearch/core.rb, lib/ddtrace/contrib/http/patcher.rb, lib/ddtrace/contrib/sinatra/tracer.rb, test/contrib/elasticsearch/transport_test.rb
* if the Elasticsearch `perform_request` fails for our instrumentation, `ensure` the original method is called
* handles the case where the `body` is already encoded as a string; in that case the `JSON.generate()` will fail so we use it as is
Third party libraries encode the `body` as a String (i.e. [Chewy][1]) so we should handle that case
[1]: https://github.com/toptal/chewy
=> [elasticsearch] safe-guard when the body is already encoded

.rubocop.yml, docs/GettingStarted.md, lib/ddtrace/sampler.rb, lib/ddtrace/span.rb, test/contrib/sinatra/tracer_test.rb, test/sampler_test.rb, test/span_test.rb, test/transport_test.rb
* tests `set_metric` for valid and invalid values
* enforces that the `value` used in `set_metric` is stored as `float`
* invalid values can be safely discarded before sending the trace
=> [core] add metrics testing

circle.yml, docker-compose.yml, docs/GettingStarted.md, lib/ddtrace/writer.rb, test/integration_test.rb, test/transport_test.rb
**Breaking change**
*drop legacy port `7777` in favor of `8126`
* the `datadog/docker-dd-agent ` container is launched via `docker-compose`
=> [core] drop legacy port 7777

lib/ddtrace/contrib/rails/active_record.rb, test/contrib/rails/database_test.rb
Keeps track of the ``:cached`` attribute in the ``active_record`` instrumentation payload. This is a best effort support for the moment, since this change [has been deployed][1] in the Rails master but it has not been released.
Having ``rails.db.cached`` meta is useful to explain users why some SQL queries has 0ns of duration.
[1]: https://github.com/rails/rails/blob/ff9999babf00dce6491a9bbf830abf4bc4ff9f9d/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb#L101-L117
=> [rails] active_record keeps track of the :cached key if it's available

docs/GettingStarted.md, lib/ddtrace/contrib/rails/framework.rb, lib/ddtrace/tracer.rb, test/contrib/rails/tracer_test.rb, test/tracer_test.rb
Rebase of contribution #92 (thanks @intelekshual!).
This PR adds the ability to set global tags on a `Tracer` instance. These tags are applied to every `Span` created by the Tracer. This is useful when instrumenting applications in different environments (ex. staging and production), which is why the Rails contrib app has been updated to set the env tag to the Rails environment.
=> add global tags to the Tracer class

docs/GettingStarted.md, lib/ddtrace/contrib/rails/framework.rb, test/contrib/rails/tracer_test.rb
Users can set tracer global tags using Rails settings like:
```ruby
Rails.configuration.datadog_trace = {
enabled: true,
auto_instrument: true,
auto_instrument_redis: true,
tags: { 'component' => 'API', 'another' => 'with_value' }
}
```
All created spans will have both `component` and `another` tags.
Follow-up of #100.
=> [rails] provide tags setting to include global tags from Rails settings

docs/GettingStarted.md, lib/ddtrace/contrib/rails/framework.rb, test/contrib/rails/tracer_test.rb
Should fix the side effects described in #92
=> [env] using Rails environment only when asked to do so

lib/ddtrace/span.rb, test/span_test.rb
Calling `span.finish()` multiple times doesn't have any effect.
=> [core] Span class can be finished only once

lib/ddtrace/contrib/rails/action_controller.rb, lib/ddtrace/span.rb, test/contrib/rails/controller_test.rb, test/span_test.rb
There's a bug when joining the stacktrace which makes them be joined with the string '\n' instead of an actual newline character. As a consequence, the Datadog UI shows an awkward long line with a lot of \n displayed, instead of the expetected view of a line per frame in the stacktrace.
Example of stacktrace before the fix:
Example of stacktrace in the UI after this fix:
=> Make stacktraces be constructed with proper newline characters

lib/ddtrace/logger.rb, test/logger_test.rb
We might want to explicitly repeat the `progname` within the log message, as some loggers (and especially when using frameworks, Rails, Passenger etc.) do not display the information within the standard output, making it very hard to "grep-isolate" our logs.
=> [logger] explicitely writing progname in message body

lib/ddtrace/contrib/rack/middlewares.rb
Uses directly the `env` object (we have one `env` per request) instead of the Rack `Request`. This is required because in some frameworks (like Rails) the `request.path_info` could be changed at runtime, especially during exception handling. This makes results not reliable for our `http.url` tag. For instance:
```ruby
request = ::Rack::Request.new(env)
assert_equal(request.path_info, '/error')
status, headers, response = @app.call(env)
assert_equal(request.path_info, '/error')  # this fails!
```
The stored value now is `/500`.
=> [rack] use the Rack env instead of the Rack request object

docs/GettingStarted.md, lib/ddtrace.rb, lib/ddtrace/contrib/rails/action_controller.rb, lib/ddtrace/contrib/rails/framework.rb, test/contrib/rails/apps/application.rb, test/contrib/rails/apps/rails3.rb, test/contrib/rails/controller_test.rb, test/contrib/rails/errors_test.rb, test/contrib/rails/rack_middleware_test.rb, test/contrib/rails/rails_sidekiq_test.rb, test/contrib/rails/tracer_test.rb
Major change about how Rails applications are traced. Now the Rack `TraceMiddleware` is used and so an high overview of the whole request is available. Changes include:
* the `TraceMiddleware` is added at initialization time, before the middleware stack is built
* the `rails.request` now becomes `rails.action_controller` and is not the root span anymore
* because the `TraceMiddleware` is used, `rack.request` is the root span for all traces and it includes all http-related tags
* the `rails.request` is now part of the `rails-controller` service (it's user configurable)
* when we're inside a Rails controller, the `process_action.action_controller()` changes the `rack.request` resource so that it has a meaningful name
* if Rails is not hit, the `rack.request` keeps the default resource name …
=> [rails] Rails action_controller is part of the rack request

lib/ddtrace.rb, lib/ddtrace/contrib/rack/middlewares.rb, test/contrib/rack/middleware_test.rb, test/contrib/rails/rack_middleware_test.rb
Rack middleware cannot be initialized before `:build_middleware_stack` because at that time we don't have users' initializers (and so the settings). We're initializing the configuration later, after the first call.
=> [rails] Rack middleware configuration is delayed

docs/GettingStarted.md
Tries to make it clear that Grape instrumentation with Rails can be activated using Rails settings.
=> [docs] minor update for Rails

lib/ddtrace/transport.rb, test/tracecountheader_test.rb
Pre-sampling on the agent side requires this header to be here,
to know how many traces are in the payload without decoding the
payload for real.
=> [presampler] Adding X-Datadog-Trace-Count header

circle.yml
Our builds stop working when using the latest `2.6.12` release of rubygems. The issue is:
```
Updating rubygems-update
ERROR:  While executing gem ... (TypeError)
no implicit conversion of nil into String
```
Pinning all versions to a previous one, fixes the problem.
=> [ci] pin rubygems system version

docs/GettingStarted.md
In [our documentation][1] we have broken links; this fixes all of them. This is a temporary build: http://www.rubydoc.info/github/DataDog/dd-trace-rb/cd96a3a
**Note**
When merged it will be released immediately.
[1]: http://www.rubydoc.info/github/DataDog/dd-trace-rb/
=> [docs] fixed documentation links to web frameworks and libraries

.gitignore, ddtrace.gemspec, gemfiles/contrib.gemfile, gemfiles/contrib_old.gemfile, gemfiles/rails3_mysql2.gemfile, gemfiles/rails3_postgres.gemfile, gemfiles/rails3_postgres_redis.gemfile, gemfiles/rails3_postgres_sidekiq.gemfile, gemfiles/rails4_mysql2.gemfile, gemfiles/rails4_postgres.gemfile, gemfiles/rails4_postgres_redis.gemfile, gemfiles/rails4_postgres_sidekiq.gemfile, gemfiles/rails5_mysql2.gemfile, gemfiles/rails5_postgres.gemfile, gemfiles/rails5_postgres_redis.gemfile, gemfiles/rails5_postgres_sidekiq.gemfile
Recent version of minitest (5.10.2, was released yesterday May 9th) breaks our CI. This pins it to previous version, from December, which works for our usage.
=> [ci] pin minitest version

docs/GettingStarted.md
```use Datadog::Contrib::Rack::TraceMiddleware, default_service: 'rack-stack'```
=> [docs] missing comma for Rack example

lib/ddtrace/tracer.rb, test/concurrent_test.rb
Some real-world examples clearly show different traces packed together in payloads. While this never happens within our test suites and, generally speaking, linear, sequential mono-thread-process environments, it happens. I did not really see where, elsewhere in the code, we ensure this never happens (two different traces concurrently sharing the same tracer instance).
=> [tracer:idmismatch] ensuring submitted spans belong to the same trace.

docs/GettingStarted.md, lib/ddtrace/span.rb
Updates docs and docstrings to be more clear.
=> [docs] be more explicit in docs

docs/GettingStarted.md
There is no class level `onto` method - it appears from my troubleshooting that one uses `pin#onto` instead (which makes sense, since the method assigns the `pin` variable).
=> Correct use of Datadog;:Pin object in doc example

README.md
Makes Sinatra's instrumentation more easier and clear.
Related to #139
=> Add Sinatra::Base tracing instructions into README.md

lib/ddtrace/contrib/rack/middlewares.rb, lib/ddtrace/contrib/rails/action_controller.rb, test/contrib/rails/apps/application.rb, test/contrib/rails/apps/controllers.rb, test/contrib/rails/errors_test.rb
As mentionned in https://github.com/DataDog/dd-trace-rb/issues/103 -> do not pull the red flag when error is not a `5xx` status code.
=> [contrib:rails] only treat 5xx errors as real errors

lib/ddtrace/contrib/rails/framework.rb
It crashes when using rails without active record. Also currently there are at least 3 places where we apply stuff to active record:
- `contrib/rails/framework`
- `contrib/rails/active_record`
- `contrib/active_record`
It would be probably best to have one place for this eval, or just use some kind of wrapper method around `connection_config` that would handle this instead of patching AR
=> Patch ActiveRecord only when it's available.

lib/ddtrace.rb, lib/ddtrace/contrib/rack/middlewares.rb, lib/ddtrace/contrib/rails/action_controller.rb, lib/ddtrace/contrib/rails/middlewares.rb, test/contrib/rack/middleware_test.rb, test/contrib/rails/apps/controllers.rb, test/contrib/rails/controller_test.rb, test/contrib/rails/rack_middleware_test.rb
Rails instrumentation does not report correct stack traces (see #110 which also referred to this point). This patch introduces a new way to populate this stack trace (heavily inspired by @Ferdy89 work), not relying on `caller` any more which, indeed, is not want we want.
=> [tracer:stacktrace] fix error stack traces

Rakefile, docs/GettingStarted.md, lib/ddtrace.rb, test/contrib/rails/controller_test.rb, test/contrib/rails/disable_env_test.rb
=> [rails] introduced DISABLE_DATADOG_RAILS env var to skip Rails magic

Appraisals, gemfiles/contrib_old.gemfile
`redis 4.0.0` has been released and requires `ruby >= 2.2.2`
=> Lock `redis` dependency for old ruby versions

lib/ddtrace.rb, lib/ddtrace/contrib/rails/action_controller.rb, lib/ddtrace/contrib/rails/action_view.rb, lib/ddtrace/contrib/rails/active_support.rb, lib/ddtrace/contrib/sinatra/tracer.rb, lib/ddtrace/error.rb, lib/ddtrace/ext/errors.rb, lib/ddtrace/span.rb, test/error_test.rb
This ensures all error-related data is properly encoded.
=> Add `Datadog::Error` value-object

lib/ddtrace/provider.rb, lib/ddtrace/tracer.rb, test/helper.rb, test/provider_test.rb, test/tracer_test.rb
Also:
* Add `DefaultContextProvider#context=` method
=> Enable access to context provider

lib/ddtrace/contrib/rack/middlewares.rb, test/contrib/rack/helpers.rb, test/contrib/rack/middleware_test.rb
Depends on #183 
This PR provides a temporary fix to a memory leak associated with unfinished spans, which are retained in the context object instead of being flushed. This issue is happening because we currently rely on thread local variables for context propagation across multiple spans, and these variables are not necessarily garbage collected at the end of each request – they might return to a thread pool instead and be reused in following the requests.
This PR ensures that each HTTP request has a clean context object.
=> Fix trace leak across multiple requests

ddtrace.gemspec
With the latest version >= 0.50, we have a lot of complains from Rubocop. This pins the version to the latest accepted style. We'll update Rubocop (and our style) as soon as we release the 0.9.0.
=> [ci] pin Rubocop version to avoid code style changes

lib/ddtrace/utils.rb, test/utils_test.rb
This PR fixes ID collisions that might arise in applications that make use of process forking (`unicorn`, `resque` etc.).
Here we basically ensure that `parent` and `children` processes don't share the same `seed` for the random number generator.
=> Fix ID collision for forked processes

Rakefile, docs/GettingStarted.md, lib/ddtrace/contrib/faraday/middleware.rb, lib/ddtrace/contrib/faraday/patcher.rb, lib/ddtrace/ext/http.rb, lib/ddtrace/monkey.rb, test/contrib/faraday/middleware_test.rb, test/monkey_test.rb
This PR enables instrumentation for HTTP requests made through `faraday`.
```ruby
connection = Faraday.new('https://example.com') do |builder|
builder.use(:ddtrace, options)
builder.adapter Faraday.default_adapter
end
connection.get('/foo')
```
Where `options` is an optional `Hash` that accepts the following parameters:
| Key | Type | Default | Description |
| --- | --- | --- | --- |
| `split_by_domain` | Boolean | `false` | Uses the request domain as the service name when set to `true`. |
| `distributed_tracing` | Boolean | `false` | Propagates tracing context along the HTTP request when set to `true`. |
| `error_handler` | Callable | [Click Here](https://github.com/DataDog/dd-trace-rb/blob/4fe3bc9df032eac3cd294b0bebcc866080dbe04f/lib/ddtrace/contrib/faraday/middleware.rb#L11-L13) | A …
=> Add `faraday` integration

lib/ddtrace/contrib/rails/action_view.rb, lib/ddtrace/contrib/rails/core_extensions.rb, test/contrib/rails/apps/controllers.rb, test/contrib/rails/controller_test.rb, test/contrib/rails/errors_test.rb
Many code paths around our Rails instrumentation are not very robust, especially if for any reason a `Span` is not properly finished. In that case, we rely in the opening/closing order, keeping the `Trace` opened (so it's not flushed). While wrong manual instrumentation may lead to that case too, we must enforce the stability of our code
* [Template instrumentation]: we patch directly the class `ActionView::TemplateRenderer`, creating a `tracing_context` to carry the template span. Some tags are computed after the rendering so that we don't compute them twice.
* (others are WIP)
The goal of this PR is to improve our internal instrumentation, so **NO IMPACT** must be expected. It should *simply work* without any change.
=> [rails] improve instrumentation stability for Template/Partial rendering

lib/ddtrace/contrib/rails/action_controller.rb, lib/ddtrace/contrib/rails/core_extensions.rb
Before this patch, the `ActionController` instrumentation relied in the span order to find the request active `Span`. This patch makes use of a `tracing_context` that propagates the `rails.action_controller` span so that it can be retrieved when the request processing ends.
No breaking changes are expected. Backward compatibility with Rails 3.0 still applies.
=> [rails] improve safety of ActionController instrumentation

lib/ddtrace/contrib/aws/patcher.rb
In ruby-1.9.3 `Module#constant_get` doesn't support nested constants (e.g., `const_get(A::B::C)`).
This was causing `Datadog::Contrib::Aws::Patcher` to misbehave in certain cases in which the `Patcher` runs *after* a service client is auto-loaded:
```rb
Aws::S3::Client.new
Datadog::Monkey.patch_module(:aws)
```
=> Fix constant-lookup for ruby-1.9.3

lib/ddtrace/tracer.rb, lib/ddtrace/workers.rb, lib/ddtrace/writer.rb, test/contrib/rails/tracer_test.rb, test/contrib/redis/redis_test.rb, test/contrib/sidekiq/tracer_configure_test.rb, test/helper.rb, test/workers_test.rb
The current implementation involves saving the previously sent services in order to compare with the new batch to ensure that old services are not sent again. In addition to this, the interval for sending services is much longer than that for sending traces - running the risk of not sending a service at all. Improvements made in this PR include not saving services in memory for comparison, but instead sending services along with the first trace. One single `flush_interval` of 1 second replaces the two different `span_interval` and `service_interval`
=> Service flushing improvements

lib/ddtrace.rb, lib/ddtrace/buffer.rb, lib/ddtrace/tracer.rb, lib/ddtrace/workers.rb, lib/ddtrace/writer.rb, test/buffer_test.rb, test/integration_test.rb
Fix for a problem found when implementing the Resque integration - the Resque process would end before the thread could finish sending the traces. This PR is to implement a shutdown method similar to that of the Python client: https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/writer.py#L104-L121 
To ensure trace sending is completed before a process exits, call the `shutdown` method after the span should be `finished`.
```
Datadog.tracer.trace('web.request', service: 'my-web-site') do |span|
do_something
end
Datadog.shutdown
```
You can pass it in a tracer or the method will just use the default `Datadog.tracer`: 
`def self.shutdown(tracer = Datadog.tracer)`
Trace sending completion is ensured for short-running processes
=> Ensure traces sent before process ends 

lib/ddtrace/contrib/faraday/middleware.rb, test/contrib/faraday/middleware_test.rb
The current version sends the wrong value via headers when doing distributed tracing (`span.parent_id` instead of the `span.span_id`).
Closes #210
=> [faraday] update the HTTP_HEADER_PARENT_ID to send the span_id instead of parent_id

docs/GettingStarted.md
* adds `Resque` doc
* reorder paragraphs since they were wrong
* removed the _Glossary_ since we have official docs
=> [docs] update integrations docs

Rakefile, ddtrace.gemspec
Without this patch, the `Faraday` table is not correctly rendered when using `rake docs` command.
=> [docs] use redcarpet provider when building with rake

lib/ddtrace/contrib/resque/resque_job.rb
If DataDog::Monkey.patch_all isn't called (running in a dev environment) resque jobs are still attempted to be traced leading to the following error:
`NoMethodError/undefined method 'tracer'` for nil:NilClass
=> Guard against resque tracing if pin is nil

lib/ddtrace.rb, lib/ddtrace/contrib/active_record/patcher.rb, lib/ddtrace/contrib/aws/patcher.rb, lib/ddtrace/contrib/base.rb, lib/ddtrace/contrib/dalli/patcher.rb, lib/ddtrace/contrib/elasticsearch/patcher.rb, lib/ddtrace/contrib/faraday/patcher.rb, lib/ddtrace/contrib/grape/patcher.rb, lib/ddtrace/contrib/http/patcher.rb, lib/ddtrace/contrib/mongodb/patcher.rb, lib/ddtrace/contrib/redis/patcher.rb, lib/ddtrace/contrib/resque/patcher.rb, lib/ddtrace/contrib/sucker_punch/patcher.rb, lib/ddtrace/monkey.rb, lib/ddtrace/registry.rb, lib/ddtrace/registry/registerable.rb, test/registry_test.rb
This PR provides the `Registry` abstraction that will help us to refactor the configuration API. The idea is to provide a clear interface for adding/retrieving different integrations and to decouple the `Datadog::Monkey` from it.
The PR also includes a `Registerable` module that provides a `#register_as` convenience method to let different integrations to "self-register" themselves.
=> Add `Datadog::Registry`

lib/ddtrace.rb, lib/ddtrace/configurable.rb, lib/ddtrace/configuration.rb, lib/ddtrace/configuration/proxy.rb, lib/ddtrace/configuration/resolver.rb, lib/ddtrace/contrib/base.rb, test/configurable_test.rb, test/configuration/proxy_test.rb, test/configuration/resolver_test.rb, test/configuration_test.rb
This PR provides the core components that will power the new configuration API. All integrations should include the `Base` module which in turn includes the `Registerable` and the `Configurable` modules.
By doing so, the integration will be globally accessible through the name specified in `.register_as` method call and all of its configuration parameters can be exposed through a series of `.option` declarations.
As a result, users will be able to configure everything within a single configuration block such as:
```rb
c.use :rails, default_service_name: 'foobar'
c.use :aws
c.use :http, distributed_tracing_enabled: true
c.use :dalli
end
```
And the integrations will look like:
```rb
module Datadog
module Contrib
module HTTP
include Base
register_as :http
option …
```
=> Add `Configuration` API

.gitignore
Since it's a library, `.ruby-version` is not required.
=> [tool] add .ruby-version to gitignore

lib/ddtrace/contrib/rails/action_controller.rb, lib/ddtrace/contrib/rails/action_view.rb, lib/ddtrace/contrib/rails/active_support.rb, lib/ddtrace/contrib/rails/core_extensions.rb
Since most of the methods require wrapping Rails internals execution, it's useless relying in Rails instrumentation just to keep the code separated. With this patch, We're not relying in the Rails instrumentation anymore, keeping a subscriber only for ActiveRecord.
The following benchmark hits the `:index` available in the testing app to see the benefit of this change:
```
```
=> [rails] use direct instrumentation instead of Rails instrumentation

lib/ddtrace/tracer.rb
Same filtering happens at the beginning of `Tracer#start_span`
=> Remove duplicate filter on `Trace#trace`

lib/ddtrace/contrib/resque/resque_job.rb, lib/ddtrace/writer.rb, test/contrib/resque/hooks_test.rb, test/contrib/resque/test_helper.rb
The child process created when Resque forks to work on a new job receives a copy of the parent process's buffers and `writer`. This clears it out after the fork to ensure a clean slate and may help with performance. For example, if a span is not finished and a `worker` thread not created, the buffers will never be cleared and the process will sleep in the `shutdown!` method until it times out at 5 seconds. 
No breaking changes
=> [Resque] Cleanup after fork

lib/ddtrace/contrib/resque/resque_job.rb
Ensure the class extension works even if the `Pin` is not available. Follow-up of #223
=> [resque] add Pin guard to Resque.after_fork

lib/ddtrace/contrib/rails/core_extensions.rb, test/contrib/rails/cache_test.rb
Closes #243
Fixed a bug when an `Exception` was raised in the cache layer.
=> [rails] fixed error reporting when exceptions happen in the cache layer

lib/ddtrace/contrib/sidekiq/tracer.rb
We're still keeping some of the configurations in Rails, but it's the first step to the newer API.
=> Migrate `sidekiq` to new configuration API

lib/ddtrace/monkey.rb
Not every integration provides a *patcher*. This PR makes sure `Datadog::Monkey` handles these cases as well.
=> Handle integrations that don't implement `#patch`

lib/ddtrace/contrib/active_record/patcher.rb, lib/ddtrace/contrib/sinatra/tracer.rb, test/contrib/sinatra/tracer_activerecord_test.rb, test/contrib/sinatra/tracer_disabled_test.rb, test/contrib/sinatra/tracer_test.rb
This PR migrates the `sinatra` integration to the new configuration API.
```rb
require 'sinatra'
require 'ddtrace/contrib/sinatra/tracer'
c.use :sinatra, default_service: 'my-sinatra-app'
end
get '/' do
'Hello, World!'
end
```
=> Migrate `sinatra` to new configuration API

ddtrace.gemspec, lib/ddtrace/contrib/rails/framework.rb, lib/ddtrace/tracer.rb, lib/ddtrace/transport.rb, lib/ddtrace/writer.rb, test/helper.rb, test/writer_test.rb
This PR provides the feedback loop between the `datadog-trace-agent` and the `PrioritySampler`. The purpose of it is to adjust dynamically the sampling rates of each service after each flush.
=> Create priority sampler feedback loop

lib/ddtrace/buffer.rb, lib/ddtrace/tracer.rb, lib/ddtrace/workers.rb, test/integration_test.rb, test/workers_test.rb
This PR improves the shutdown process by leveraging the concept of [condition variables](https://en.wikipedia.org/wiki/Monitor_(synchronization)#Condition_variables). This way we can get rid of the busy waits in the termination process altogether.
Closes #246
=> Improve shutdown process

Appraisals, gemfiles/rails32_postgres_redis.gemfile
`redis >= 4.0` doesn't support `ruby 1.9.3`.
=> Lock `redis` version for `rails32_postgres_redis` appraisal

lib/ddtrace/contrib/resque/patcher.rb, lib/ddtrace/contrib/resque/resque_job.rb, lib/ddtrace/sync_writer.rb, lib/ddtrace/tracer.rb, lib/ddtrace/transport.rb, test/contrib/resque/hooks_test.rb, test/contrib/resque/test_helper.rb, test/sync_writer_test.rb
Adds a sync writer so that no threads are used to flush data. This means that when the `Tracer` finishes a trace (calling the `write()` method under the hood), the call is blocking. It's not meant to be used as a default tracer, but instead a good replacement in processes that forks and dies at the end (i.e. Resque).
It reduces a lot the overhead since no signals / timeouts must be waited.
=> [core] add `SyncWriter`

ddtrace.gemspec, docs/GettingStarted.md, lib/ddtrace/context.rb, lib/ddtrace/contrib/faraday/middleware.rb, lib/ddtrace/contrib/rails/framework.rb, lib/ddtrace/contrib/rails/patcher.rb, lib/ddtrace/ext/distributed.rb, lib/ddtrace/propagation/http_propagator.rb, lib/ddtrace/sampler.rb, lib/ddtrace/span.rb, lib/ddtrace/tracer.rb, lib/ddtrace/transport.rb, lib/ddtrace/writer.rb, test/helper.rb, test/integration_test.rb, test/priority_sampler_test.rb, test/propagation/http_propagator_test.rb, test/rate_by_service_sampler_test.rb, test/writer_test.rb
Introduces Priority Sampling to force the sampler to keep a trace (or to discard it). This includes Distributed Tracing propagation for the priority sampling attribute.
=> Enable priority sampling

lib/ddtrace/contrib/faraday/middleware.rb, lib/ddtrace/contrib/http/patcher.rb, test/contrib/faraday/middleware_test.rb, test/contrib/http/request_test.rb, test/integration_test.rb
When the tracer is disabled, the traces/spans are not sent, so we
should not set the distributed tracing headers, else children called
with these would refer to non-existing (never sent) parent traces.
=> [distributed tracing] disabling tracer disables distributed headers

docs/GettingStarted.md
Sinatra PR #226 introduced a breaking change. This PR updates the documentation with the newer API.
=> [docs] update Sinatra documentation with the new API

docs/GettingStarted.md, lib/ddtrace/contrib/sinatra/tracer.rb, test/contrib/sinatra/tracer_test.rb
We're introducing a breaking change, and so we should change the option value too. In that we we're consistent with the future configuration common to all integrations.
To change the service name we should use `service_name` option instead of the old `default_service`.
=> [sinatra] change the name with service_name instead of default_service

lib/ddtrace/configuration.rb, lib/ddtrace/contrib/sinatra/tracer.rb, test/configuration_test.rb
This PR ensures that custom option setters are triggered even for default values. For more information about custom option setters, see https://github.com/DataDog/dd-trace-rb/pull/203
=> Ensure all setters are triggered when calling `Configuration#use`

lib/ddtrace/contrib/active_record/patcher.rb, lib/ddtrace/contrib/aws/patcher.rb, lib/ddtrace/contrib/dalli/patcher.rb, lib/ddtrace/contrib/elasticsearch/patcher.rb, lib/ddtrace/contrib/faraday/patcher.rb, lib/ddtrace/contrib/grape/patcher.rb, lib/ddtrace/contrib/mongodb/patcher.rb, lib/ddtrace/contrib/rack/middlewares.rb, lib/ddtrace/contrib/rails/action_controller.rb, lib/ddtrace/contrib/rails/active_record.rb, lib/ddtrace/contrib/rails/active_support.rb, lib/ddtrace/contrib/rails/framework.rb, lib/ddtrace/contrib/rails/patcher.rb, lib/ddtrace/contrib/redis/patcher.rb, lib/ddtrace/contrib/resque/patcher.rb, lib/ddtrace/contrib/sidekiq/tracer.rb, lib/ddtrace/contrib/sucker_punch/patcher.rb, test/contrib/rack/helpers.rb, test/contrib/rack/middleware_test.rb, test/contrib/rails/cache_test.rb, test/contrib/rails/database_test.rb, test/contrib/rails/rack_middleware_test.rb, test/contrib/rails/rails_sidekiq_test.rb, test/contrib/rails/tracer_test.rb, test/contrib/sidekiq/tracer_configure_test.rb, test/contrib/sidekiq/tracer_test.rb
This PR let service names be set through the `configure` block, obviating the need for `Pin` objects.
All integrations (except for `rails`, see example below) have now a `service_name` option.
```rb
c.use :rails, service_name: 'my-app', controller_service: 'rails-controller', database_service: 'postgresql', cache_service: 'rails-cache'
c.use :sidekiq, service_name: 'sidekiq'
c.use :grape, service_name: 'grape-api'
c.use :aws, service_name: 'aws'
c.use :dalli, service_name: 'memcached'
c.use :faraday, service_name: 'http'
c.use :elasticsearch, service_name: 'external-cache'
c.use :redis, service_name: 'redis'
end
```
The configuration above would be equivalent to:
```rb
Rails.configuration.datadog_trace = {
default_service: 'my-app',
default_controller_service: …
```
=> Expose service names in configuration block

lib/ddtrace/configuration.rb, lib/ddtrace/contrib/rails/framework.rb, lib/ddtrace/contrib/rails/patcher.rb, lib/ddtrace/contrib/sidekiq/tracer.rb, lib/ddtrace/contrib/sinatra/tracer.rb, test/configuration_test.rb, test/contrib/rails/rails_sidekiq_test.rb, test/contrib/rails/tracer_test.rb, test/contrib/sidekiq/disabled_tracer_test.rb, test/contrib/sidekiq/tracer_configure_test.rb, test/contrib/sinatra/tracer_activerecord_test.rb, test/contrib/sinatra/tracer_disabled_test.rb, test/contrib/sinatra/tracer_test.rb
This PR let's `Datadog.tracer` be configured through `Datadog.configure` block. Options originally associated to the tracer domain (`hostname`, `port`, `debug` etc.) are no longer part of the contributions. The example below summarizes the changes:
```rb
Rails.initializer.datadog_tracer = {
enabled: true,
debug: true,
trace_agent_hostname: 'localhost',
trace_agent_port: 7777
}
```
Should now be replaced by:
```rb
c.tracer enabled: true, debug: true, hostname: 'localhost', port: 7777
c.use :rails
end
```
=> Provide tracer configuration

lib/ddtrace/contrib/rack/middlewares.rb, lib/ddtrace/contrib/rails/framework.rb, lib/ddtrace/contrib/rails/patcher.rb, test/contrib/rails/rails_sidekiq_test.rb, test/contrib/rails/tracer_test.rb, test/helper.rb
This PR puts `rack` and `rails-controller` spans under the same service name by default. For distinct service names, use the `controller_service` option as it follows:
```rb
c.use :rails, service_name: 'rack-handler', controller_service: 'rails-controller'
end
```
**Breaking change**
It's worth mentioning this is a breaking change since it will affect metrics associated with rails controllers and rack middleware, so make sure to update any monitors that rely on these services, or use the `controller_service` option to have the same name you're using now.
=> Merge rack and rails services

lib/ddtrace/contrib/rails/framework.rb, lib/ddtrace/contrib/rails/patcher.rb, lib/ddtrace/contrib/rails/utils.rb, test/contrib/rails/default_service_test.rb, test/contrib/rails/rack_middleware_test.rb, test/contrib/rails/rails_sidekiq_test.rb, test/contrib/rails/redis_cache_test.rb, test/contrib/rails/test_helper.rb, test/contrib/rails/tracer_test.rb
Instead of using static defaults (`rails-app`, `rails-controller`), we prepend the Rails app name to that value. The app name is retrieved using `::Rails.application.class` if you didn't set it. In both cases, you'll have:
```
intake
intake-controller
intake-cache
...
```
You can still override each value if you want to keep different names than the ones provided by default.
=> Provide better default names for `rails` services

lib/ddtrace/contrib/active_record/patcher.rb, lib/ddtrace/contrib/http/patcher.rb, lib/ddtrace/contrib/rack/middlewares.rb, lib/ddtrace/contrib/rails/active_record.rb, lib/ddtrace/contrib/rails/framework.rb, lib/ddtrace/contrib/rails/patcher.rb, lib/ddtrace/contrib/rails/railtie.rb, lib/ddtrace/contrib/rails/utils.rb, test/contrib/http/request_test.rb, test/contrib/rack/distributed_test.rb, test/contrib/rails/rack_middleware_test.rb, test/contrib/rails/rails_sidekiq_test.rb, test/contrib/rails/tracer_test.rb, test/helper.rb
This PR removes both dead and deprecated code associated to the old configuration API and renames the `distributed_tracing_enabled` configuration parameter to `distributed_tracing`.
For enabling both inbound and outbound distributed tracing, just do as follows:
```rb
Datadog.configure do
c.use :rails, distributed_tracing: true # inbound distributed tracing
c.use :http, distributed_tracing: true # outbund distributed tracing
end
```
=> Configuration cleanup

lib/ddtrace/contrib/dalli/quantize.rb, test/contrib/dalli/quantize_test.rb
Since `memcached` is frequently used to store marshaled objects and other blob types, the Ruby VM might interpret `dalli` request arguments as strings with incompatible encodings. This PR adds a safe-guard for that case.
=> Fix `dalli` instrumentation encoding issue

circle.yml, ddtrace.gemspec
`msgpack` 1.2.0 for `jruby` [was shipped with missing files](https://github.com/msgpack/msgpack-ruby/commit/a0210280ecb049c9af937a55589d2d78a0977cd0), so CI is breaking for `jruby` tests. 
A `1.2.1` version was published with a fix for `java` platform only, but unfortunately `bundle` doesn't resolve dependencies correctly for multiple platforms (that is, we can't have a `Gemfile.lock` with `msgpack` set to `1.2.1` for java and `1.2.0` for `ruby` platform).
For this reason, we're locking `msgpack` dependency on our CI environment.
*UPDATE*: we're also temporarily ignoring the exit status from `appraisal install`
=> lock msgpack dependency for CI environment

lib/ddtrace/configurable.rb, lib/ddtrace/configuration/proxy.rb, lib/ddtrace/contrib/faraday/middleware.rb, lib/ddtrace/contrib/faraday/patcher.rb, test/configuration_test.rb, test/contrib/faraday/middleware_test.rb
This PR let's `faraday` be customized globally and on a *per-connection* basis.
```rb
c.use :faraday, service_name: 'http'
end
```
```rb
connection = Faraday.new('http://example.com') do |builder|
builder.use(:ddtrace, service_name: 'example-request')
end
```
=> Improve `faraday` configuration

lib/ddtrace/contrib/rails/active_record.rb, lib/ddtrace/contrib/rails/utils.rb, test/contrib/rails/database_test.rb, test/helper.rb
This pull request adds the database name as a tag (`rails.db.name`) to ActiveRecord traces.
=> Add 'rails.db.name' tag to ActiveRecord

docs/GettingStarted.md, lib/ddtrace/contrib/rack/middlewares.rb, test/contrib/grape/rack_app.rb, test/contrib/rack/distributed_test.rb, test/contrib/rack/helpers.rb, test/contrib/rack/middleware_test.rb
Refactoring Rack middleware:
* removing the `configure` method since we can use `Datadog.configuration` directly
* remove `begin-ensure` block for distributed tracing and `tracer.trace()`
* return `[status, headers, response]` list
=> [rack] middleware refactoring; Context cleaning happens at the end of the request

Rakefile, circle.yml
This PR provides a couple of optimizations speed up our builds. I've observed a`~35%` improvement.
Notice we should migrate our pipeline to CircleCI 2.0 which will yield greater improvements.
=> Reduce CI building time

lib/ddtrace/contrib/sinatra/tracer.rb, test/contrib/sinatra/first_test_app.rb, test/contrib/sinatra/multi_app_test.rb, test/contrib/sinatra/second_test_app.rb
This pull request prepends `request.script_name` to Sinatra trace resource names, if available and enabled. e.g. `get '/endpoint'` from a Sinatra app rooted in Rack via `map '/foo'` would change the trace `resource` from `/endpoint` to `/foo/endpoint`.
This new behavior is disabled by default. It can be enabled by adding the `resource_script_names` flag to the configuration. e.g.
```
c.use :sinatra, resource_script_names: true
end
```
Or via `Datadog.configuration[:sinatra][:resource_script_names] = true`
This flag is useful for particular cases where there are multiple Sinatra apps configured in a `config.ru` that have overlapping endpoints rooted at different namespaces. Take for example the following app:
**config.ru:**
```
require 'bundler'
Bundler.require …
```
=> Add script name to resource for Sinatra if available

lib/ddtrace/contrib/aws/patcher.rb, lib/ddtrace/contrib/dalli/patcher.rb, lib/ddtrace/contrib/elasticsearch/patcher.rb, lib/ddtrace/contrib/sidekiq/tracer.rb, lib/ddtrace/contrib/sinatra/tracer.rb, lib/ddtrace/contrib/sucker_punch/patcher.rb, lib/ddtrace/ext/app_types.rb
This pull request ensures we're correctly tagging our spans for each service integration, for a better UI experience. After these changes are applied, the following integrations should have these service and span types:
```
Service         Span
X ActiveRecord  - DB              SQL::TYPE
X AWS           - WEB             WEB
X Dalli         - CACHE           CACHE
X ElasticSearch - DB              DB
X Faraday       - WEB             HTTP::TYPE
X Grape         - WEB             HTTP::TYPE
? HTTP          - ???             HTTP::TYPE
X MongoDB       - DB              Mongo::TYPE
X Rack          - WEB             HTTP::TYPE
X Rails         - WEB, CACHE, DB  HTTP::TYPE, HTTP::TEMPLATE, SQL::TYPE, CACHE
X Redis         - DB              Redis::TYPE
X Resque        - WORKER          WORKER
X …
```
=> Set span types for integrations

lib/ddtrace/contrib/active_record/patcher.rb, lib/ddtrace/contrib/rails/active_record.rb, lib/ddtrace/contrib/rails/utils.rb, test/contrib/rails/database_test.rb, test/contrib/sinatra/tracer_activerecord_test.rb, test/helper.rb
This pull request adds the `out.host` and `out.port` tags to SQL traces in Rails ActiveRecord implementations. It additionally adds `active_record.db.name`, `out.host`, and `out.port` to Sinatra ActiveRecord implementations.
=> Add out.host and out.port to ActiveRecord

lib/ddtrace/contrib/elasticsearch/patcher.rb, test/contrib/elasticsearch/transport_test.rb
This pull request adds the `out.host` and `out.port` tags to traces for Elasticsearch.
=> Add out.host and out.port to Elasticsearch

lib/ddtrace/contrib/redis/quantize.rb, test/contrib/redis/quantize_test.rb
This PR ensures all byte sequences considered invalid/undefined in by UTF-8 are removed from `redis` spans before they get flushed.
=> Drop invalid byte sequences on `Redis::Quantize`

lib/ddtrace/contrib/resque/patcher.rb, test/contrib/resque/hooks_test.rb, test/helper.rb
This PR basically obviates need for extending our module for instrumenting `resque` workers.
With this change, you can simply do:
```rb
c.use :resque, workers: [PseudoWorker, FooWorker]
end
```
=> Provide `workers` option for `resque` integration

lib/ddtrace/contrib/rack/middlewares.rb, lib/ddtrace/contrib/rack/patcher.rb, lib/ddtrace/monkey.rb, test/contrib/rack/resource_name_test.rb, test/helper.rb, test/monkey_test.rb
This PR is an attempt to provide better resource names for `rack`.
Currently, rack resource names are `<REQUEST_METHOD> <RESPONSE_STATUS>`.
We're providing an alternative that should generate more meaningful names. The approach taken here is to return the name of the middleware that effectively generated the response.
Let's say you have an `AuthenticationMiddleware`. In a Rails application context, an unauthorized request would never hit the Rails stack and it would surface as something like a`GET 401` resource name.
By enabling the `middleware_names` option will you get a `AuthenticationMiddleware#GET` resource name instead.
```rb
c.use :rack, middleware_names: true
end
```
Also worth noting here that in case the HTTP request ever "hits" your Sinatra/Rails …
=> Improve rack resource names

ddtrace.gemspec, test/helper.rb
Adds `pry` and `pry-stack_explorer` to development dependencies to aid debugging.
=> Add pry to development dependencies

lib/ddtrace/contrib/rails/active_support.rb, lib/ddtrace/contrib/redis/quantize.rb, lib/ddtrace/ext/cache.rb, test/contrib/rails/cache_test.rb, test/contrib/redis/quantize_test.rb, test/contrib/redis/redis_test.rb
This PR enforces a hard-limit on the meta-data that's embedded in spans generated by `rails` cache instrumentation.
I'm also lowering the maximum size of `redis` commands.
=> Truncate cache metadata

lib/ddtrace/contrib/sidekiq/patcher.rb, lib/ddtrace/contrib/sidekiq/tracer.rb, lib/ddtrace/monkey.rb, test/monkey_test.rb
This PR simplifies the process of configuring tracing for `sidekiq`.
```rb
require 'ddtrace/contrib/sidekiq/tracer'
Sidekiq.configure_server do |config|
config.server_middleware do |chain|
chain.add(
Datadog::Contrib::Sidekiq::Tracer,
sidekiq_service: 'sidekiq-notifications'
)
end
end
```
```rb
c.use :sidekiq, service_name: 'sidekiq-notifications'
end
```
=> Use new configuration API `sidekiq`

lib/ddtrace/contrib/active_record/patcher.rb, lib/ddtrace/contrib/rails/active_record.rb, test/contrib/rails/database_test.rb, test/contrib/sinatra/tracer_activerecord_test.rb
Add the `cached` tag to ActiveRecord query spans that are cached.
The old implementation was not correctly tagging ActiveRecord queries that were resolved through the query cache. This pull requests fixes that implementation, adds the same tag for ActiveRecord integrations outside of Rails, and adds test coverage for both scenarios.
Still need to ascertain what milestone this should be applied to.
=> Add ActiveRecord cached tag

lib/ddtrace.rb, lib/ddtrace/pin.rb, test/pin_test.rb
In order to provide a single entry point for all configuration, we're providing this wrapper around `Pin` objects, so we can "hide" this implementation detail. Objects that carry a `Pin` can now be configured through the same `Datadog.configure` method.
```rb
client = Net::HTTP.new(host, port)
Datadog.configure(client) do |c|
c.service_name = 'external-api'
end
```
=> Enable `Pin` configuration through `Datadog.configure`

lib/ddtrace/configuration.rb, test/configuration_test.rb
As the title says, we're letting `Datadog::Tracer.log` be set through our `Datadog.configure` method, for the sake of providing a more standardized way of configuring tracing options.
```rb
c.tracer log: Logger.new(STDOUT)
end
```
=> Allow `Datadog::Tracer.log` to be set through `Datadog.configure`

Rakefile
Racecar tests weren't running in our CI pipeline, evidently. This pull request remedies that.
=> Fix missing CI test for racecar

lib/ddtrace.rb, lib/ddtrace/configuration.rb, lib/ddtrace/configuration/pin_setup.rb, test/configuration/pin_setup_test.rb, test/pin_test.rb
This PR is one step further towards a more standardized configuration API.
* We're hiding the `Pin` object altogether instead of yielding it in a block;
* The options must now be provided as a hash instead of setter methods, matching the current `c.use :integration, option1: value1, option2: value2` syntax;
* All configurations are provided as a "flat" hash, instead of a set of attributes AND a `config` hash (see example below).
Per-connection configuration must now be done following this API:
```rb
client = Net::HTTP.new(host, port)
Datadog.configure(client, service_name: 'external-api', distributed_tracing: true)
```
Instead of
```rb
client = Net::HTTP.new(host, port)
Datadog.configure(client) do |c|
c.service_name = 'external-api'
c.config = { distributed_tracing: true }
end
```
=> Add `Configuration::PinSetup`

lib/ddtrace/contrib/rails/core_extensions.rb, test/contrib/rails/apps/controllers.rb, test/contrib/rails/controller_test.rb
If you nest partials in a Rails application, one within another, e.g.:
```
render 'template'
--> render 'partials/outer'
--> render 'partials/inner'
```
You will receive an error that looks something like `root span closed but has 1 unfinished spans`. Those traces affected won't be written or propagated to your account. The bug is confirmed to affect Rails 3.2.
This was occurring because when partials were nested in one another, a certain contextual state object (whose purpose was to describe one partial) was being shared, then overwritten by its nested partial children. Overwriting this state effectively corrupted at least one span within the trace, thus causing it to not complete correctly.
This pull request implements a hash of contexts, which are each tied to an individual span by ID. …
=> Fix Rails nested partial tracing

Appraisals, gemfiles/rails4_postgres.gemfile, gemfiles/rails4_postgres_redis.gemfile, gemfiles/rails4_postgres_sidekiq.gemfile, gemfiles/rails5_postgres.gemfile, gemfiles/rails5_postgres_redis.gemfile, gemfiles/rails5_postgres_sidekiq.gemfile
Yesterday, they released the `pg` gem version 1.0.0, a major version change, which breaks ActiveRecord.
https://bitbucket.org/ged/ruby-pg/issues/270/pg-100-x64-mingw32-rails-server-not-start
The issue might be resolved in a future version of of ActiveRecord, but for now, it's breaking our CI which uses edge versions of gems. This pull request restricts the use of Postgres to < 1.0.0 when it runs with ActiveRecord.
=> Don't support Postgres 1.0+ with ActiveRecord in CI

ddtrace.gemspec, docs/GettingStarted.md, lib/ddtrace/ext/priority.rb, test/context_test.rb
Allow usage of  `-1` as a priority sampling value. Here there's no real impact, it's mostly about writing tests ensuring this works and updating the docs.
=> [dual sampling] support -1 as a priority sampling value

Appraisals, Gemfile, ddtrace.gemspec, gemfiles/contrib.gemfile, gemfiles/contrib_old.gemfile, gemfiles/rails30_postgres.gemfile, gemfiles/rails30_postgres_sidekiq.gemfile, gemfiles/rails32_mysql2.gemfile, gemfiles/rails32_postgres.gemfile, gemfiles/rails32_postgres_redis.gemfile, gemfiles/rails32_postgres_sidekiq.gemfile, gemfiles/rails4_mysql2.gemfile, gemfiles/rails4_postgres.gemfile, gemfiles/rails4_postgres_redis.gemfile, gemfiles/rails4_postgres_sidekiq.gemfile, gemfiles/rails5_mysql2.gemfile, gemfiles/rails5_postgres.gemfile, gemfiles/rails5_postgres_redis.gemfile, gemfiles/rails5_postgres_sidekiq.gemfile
This pull request adds `pry-nav` to the development dependencies to add `next`, `continue`, `step` commands to debugging sessions. It's a "nice to have" thing, so just a suggestion for tooling improvement.
=> Add pry-nav for development tools

lib/ddtrace/contrib/dalli/quantize.rb, lib/ddtrace/contrib/redis/quantize.rb, lib/ddtrace/error.rb, lib/ddtrace/utils.rb, test/error_test.rb, test/utils_test.rb
This PR provides `Datadog::Utils.utf8_encode` utility method.
We're also refactoring parts of the code that used to perform encoding operations.
=> Better handle different encodings

Appraisals
The latest release for Mongo introduces a new field making all our test fail. While I could update tests including the new field, I prefer to address the problem of testing the tracer for multiple library versions alter in a new PR.
This change doesn't mean Mongo 2.5 isn't supported, but we need to investigate the issue more.
=> [ci] pin mongo driver to < 2.5

lib/ddtrace/contrib/rails/action_controller.rb, test/contrib/rails/apps/controllers.rb, test/contrib/rails/controller_test.rb
You can modify the resource of a span in a controller by doing the following:
```ruby
class FooController < ApplicationController
def index
tracer = Datadog.configuration[:rails][:tracer]
tracer.active_span.resource = "custom-resource-name"
end
end
```
However this wasn't working because resource names were being overridden by default names when the span was completed.
This pull request allows the above to work, by not applying default resource names if a custom resource name has already been set.
Example of it working:
=> Allow customization of Rails controller resource names

lib/ddtrace/contrib/racecar/patcher.rb, spec/ddtrace/contrib/racecar/patcher_spec.rb
This allows us to respond to the start and finish of instrumented blocks of code without the need for a separate instrumentation event.
A subscriber object that responds to `start` and `finish` will use this advanced API, as per https://github.com/rails/rails/blob/d25c2e7c4c88440154087a08fa79ba0bf3038ba3/activesupport/lib/active_support/notifications/fanout.rb#L73-L77
=> Use the advanced AS::Notifications subscriber API

docs/GettingStarted.md, lib/ddtrace/contrib/rails/action_controller.rb, lib/ddtrace/contrib/rails/core_extensions.rb, lib/ddtrace/contrib/rails/patcher.rb, test/contrib/rails/apps/controllers.rb, test/contrib/rails/rack_middleware_test.rb
If a Rails app has a custom error controller defined via `config.exceptions_app=` for the purpose of rendering errors, the name of this custom error controller and action will supersede the name of the controller that originally raised the exception for the trace. This is because the errors controller runs afterwards, and replaces the name on the parent span, no matter what. Ultimately, it results in all error traces being listed under "ErrorsController#internal_server_error" or similarly named resource, which isn't a great experience.
This pull request introduces the `exception_class` option to Rails configuration, which allows a user to specify a class or module to identify a custom exception controller with. Spans for any controller that matches this definition will not override the …
=> Add exception_controller option to Rails

gemfiles/contrib.gemfile
I think someone might have dropped this?
=> Add missing version number for mongo in Gemfile

docs/GettingStarted.md, lib/ddtrace/contrib/sinatra/tracer.rb, test/contrib/sinatra/tracer_test.rb
Currently Sinatra doesn't support distributed tracing out of the box. It required the user to configure Rack as a service first, e.g.:
```ruby
c.use :sinatra, resource_script_names: true, service_name: 'knowledge-api',
c.use :rack, distributed_tracing: true
end
```
This pull request implements `distributed_tracing` as an option for Sinatra, so you only have to:
```ruby
c.use :sinatra, distributed_tracing: true
end
```
=> Add distributed_tracing option to Sinatra

Appraisals, Rakefile, gemfiles/contrib.gemfile, gemfiles/contrib_old.gemfile, lib/ddtrace/contrib/active_record/patcher.rb, spec/ddtrace/contrib/active_record/app.rb, spec/ddtrace/contrib/active_record/tracer_spec.rb
Closes #328.
When ActiveRecord is used standalone it should work without expecting other integrations to be activated. The following must be a legit instrumentation:
```ruby
Datadog.configure do |config|
config.use :active_record, service_name: 'random-service'
config.use :grape, service_name: 'random-service'
end
```
=> [active_record] decouple ActiveRecord and Sinatra integrations

lib/ddtrace/contrib/rack/middlewares.rb, lib/ddtrace/ext/http.rb, test/contrib/rack/middleware_test.rb
This pull request adds the `http.base_url` tag for Rack integrations, which is the equivalent of `Rack::Request#base_url`, e.g. "http://example.org" Addresses #301
=> Add http.base_url tag to Rack

lib/ddtrace/contrib/rack/middlewares.rb, lib/ddtrace/ext/http.rb, test/contrib/rack/middleware_test.rb
HTTP requests sometimes have a `X-Request-Id` header with a UUID or other identifier as a means of tracing requests in logs.
This pull request adds the `http.request_id` tag to Rack spans if Rack tracing is enabled (which is default for Rails applications.) Typically, if a `X-Request-Id` header is set, it will use that value. If it's a Rails application, and no `X-Request-Id` header is set, Rails automatically generates one, which will then be used as the value for this tag.
Sample output:
=> Add http.request_id tag to Rack spans

docs/GettingStarted.md, lib/ddtrace/contrib/active_record/patcher.rb, lib/ddtrace/contrib/rails/active_record.rb, lib/ddtrace/contrib/rails/patcher.rb, lib/ddtrace/ext/ruby.rb, spec/ddtrace/contrib/active_record/tracer_spec.rb, test/contrib/rails/controller_test.rb, test/contrib/rails/database_test.rb, test/contrib/rails/rack_middleware_test.rb, test/contrib/sinatra/tracer_activerecord_test.rb
For #311 , sometimes ActiveRecord can take significant time instantiating records.
This pull request traces the `instantiation.active_record` event, for versions of ActiveRecord 4.2+. The additional span has two tags associated with it: `active_record.instantiation.class_name` and `active_record.instantiation.record_count`.
Sample output:
=> Instrument ActiveRecord instantiations

README.md
Update README.md by removing extra indentation in the examples.
=> Remove extra indentation

lib/ddtrace/contrib/rack/middlewares.rb
While working on improvements for our exception handling support in Rails, I discovered that our `http.url` was sometimes being given bad URLs after Rails handled exceptions.
At core of this issue, the Rack tracer needs a source of truth for the `http.url` value. Looking at the `env` hash, it has a few possible options which to derive this value:
- `PATH_INFO`: Must be present on Rack requests. Starts as relative URL value, e.g. `/article/1?foo=bar`. It's often overwritten by Rails whenever an exception occurs, to the new path its rendering e.g. `/500`. At end of the trace, this value isn't very useful.
- `REQUEST_URI`: Equal to relative URL value, e.g. `/article/1?foo=bar`. Appears to be provided depending on the web server, may not always be present (for example, when using IIS instead …
=> Bad `http.url` when Rails raises exceptions

lib/ddtrace/contrib/rails/action_controller.rb, lib/ddtrace/contrib/rails/action_view.rb, lib/ddtrace/contrib/rails/active_record.rb, lib/ddtrace/contrib/rails/active_support.rb, lib/ddtrace/contrib/rails/core_extensions.rb, lib/ddtrace/patcher.rb, spec/ddtrace/patcher_spec.rb
In our current implementation, although there are guards around the Rails::Patcher module, there are no such guards around the constituent modules (e.g. in `CoreExtensions`) it uses to actually patch Rails code. It's possible to call these and overpatch Rails methods, causing infinite loops and other nasty behaviors. This has actually occurred when Railties reload, as they do in our test suite.
This pull request adds a helper function to `Datadog::Patcher` called `do_once` which is a really simple singleton-like function that prevents a function being called more than once. It's equivalent to the old `return @patched if @patched; patcher.patch_code; @patched = true`, just a little nicer looking and abstracts away the pattern.
I think this one could warrant some critical opinion, since the …
=> Prevent overpatching Rails

lib/ddtrace/contrib/rack/middlewares.rb, test/contrib/rack/middleware_test.rb
This recent pull request https://github.com/DataDog/dd-trace-rb/pull/351 effectively removed query strings from `http.url` in the process of trying to address an edge case concerning exception handling. We don't want to change this behavior right now; this pull request partially reverts the change, while retaining a secondary preference for the original PATH_INFO, which should retain the bugfix from the previous PR.
=> Re-add query string to http.url tag

Rakefile, spec/ddtrace/contrib/rails/middleware_spec.rb, spec/ddtrace/contrib/rails/rails_helper.rb, spec/ddtrace/contrib/rails/support/application.rb, spec/ddtrace/contrib/rails/support/base.rb, spec/ddtrace/contrib/rails/support/configuration.rb, spec/ddtrace/contrib/rails/support/controllers.rb, spec/ddtrace/contrib/rails/support/core_extensions.rb, spec/ddtrace/contrib/rails/support/database.rb, spec/ddtrace/contrib/rails/support/middleware.rb, spec/ddtrace/contrib/rails/support/models.rb, spec/ddtrace/contrib/rails/support/rails3.rb, spec/ddtrace/contrib/rails/support/rails4.rb, spec/ddtrace/contrib/rails/support/rails5.rb, spec/spec_helper.rb, spec/support/log_helpers.rb
This pull request adds middleware specs for Rails, and tests for behavior when custom middleware is injected.
Due to limitations of the Minitest setup where we can't modify Rails middleware stacks after the application loads, this pull request implements some Rails environment setup in RSpec.
From a mechanical perspective, the biggest difference between the two concerns application lifecycle. The Minitest suite depends upon a static Rails application, defined at load time, and then that application is used for all examples. By contrast the RSpec test suite dynamically recreates and reinitializes Rails apps per example.
The benefit we derive from this, that was necessary for this set of feature tests, is that we can now modify application initialization and middleware on an example by …
=> Rails middleware specs

Rakefile, lib/ddtrace/contrib/rails/action_controller.rb, lib/ddtrace/contrib/rails/middlewares.rb, lib/ddtrace/contrib/rails/railtie.rb, lib/ddtrace/contrib/rails/utils.rb, spec/ddtrace/contrib/rails/middleware_spec.rb, spec/ddtrace/contrib/rails/rails_helper.rb, spec/ddtrace/contrib/rails/support/application.rb, spec/ddtrace/contrib/rails/support/base.rb, spec/ddtrace/contrib/rails/support/configuration.rb, spec/ddtrace/contrib/rails/support/controllers.rb, spec/ddtrace/contrib/rails/support/core_extensions.rb, spec/ddtrace/contrib/rails/support/database.rb, spec/ddtrace/contrib/rails/support/middleware.rb, spec/ddtrace/contrib/rails/support/models.rb, spec/ddtrace/contrib/rails/support/rails3.rb, spec/ddtrace/contrib/rails/support/rails4.rb, spec/ddtrace/contrib/rails/support/rails5.rb, spec/spec_helper.rb, spec/support/log_helpers.rb, test/contrib/rails/controller_test.rb, test/contrib/rails/rack_middleware_test.rb
There are currently two issues with Rails middleware errors:
1. Exceptions raised in Rails middleware which sits above `Datadog::Contrib::Rails::ExceptionMiddleware` but below `ActionDispatch::ShowExceptions` can result in the exception stack trace being excluded from the trace.
2. Exceptions raised in Rails middleware that are equivalent to 4XX errors (e.g. `ActionController::RoutingError`) can cause the trace to incorrectly be tagged as an error.
This pull request aims to address both of these, respectively by:
1. Placing `Datadog::Contrib::Rails::ExceptionMiddleware` directly below `ActionDispatch::ShowExceptions` middleware. Users should take care to avoid placing custom middleware between these two, otherwise they'll see this issue re-occur.
2. Changing the …
=> Improve Rails middleware error handling

lib/ddtrace/contrib/rails/core_extensions.rb
/cc @delner @palazzem 
Here's the stack trace:
```
/gems/ddtrace-0.12.0.beta1/lib/ddtrace/contrib/rails/core_extensions.rb:313:in `reload_cache_store': undefined method `patched?' for nil:NilClass (NoMethodError)
from /gems/ddtrace-0.12.0.beta1/lib/ddtrace/contrib/rails/core_extensions.rb:193:in `patch_cache_store'
from /gems/ddtrace-0.12.0.beta1/lib/ddtrace/contrib/rails/active_support.rb:11:in `instrument'
from /gems/ddtrace-0.12.0.beta1/lib/ddtrace/contrib/rails/railtie.rb:16:in `block in <class:Railtie>'
from /gems/activesupport-3.2.22.4/lib/active_support/lazy_load_hooks.rb:34:in `call'
from /gems/activesupport-3.2.22.4/lib/active_support/lazy_load_hooks.rb:34:in `execute_hook'
from /gems/activesupport-3.2.22.4/lib/active_support/lazy_load_hooks.rb:26:in `block in on_load'
from …
```
=> Guard the rails core extensions against null Redis registry

lib/ddtrace/contrib/rails/core_extensions.rb, lib/ddtrace/version.rb
Hotfix release for 0.12.0.beta2.
- Addresses an issue for loading ddtrace after a Rails app that has been fully initialized.
=> Release 0.12.0.beta2

lib/ddtrace/contrib/grape/endpoint.rb, lib/ddtrace/contrib/rack/middlewares.rb, test/contrib/rack/helpers.rb
Currently ddtrace is setting keys in env in the form `:datadog_rack_request_span`. This caused some issues in some of our code as we wrote expecting that all the keys in a request env would be strings rather than symbols.
I took a quick look at the [docs for rack](http://www.rubydoc.info/github/rack/rack/master/file/SPEC) and they don't explicitly say that env should be strings except for responses which it does explicitly require it. However it does say that keys should be named to include a `.` in them e.g. `rack.version` which suggests strings are probably the way to go anways.
Based on this I've changed the key that datadog is using from a symbol to a string and included a dot. So `:datadog_rack_request_span` becomes `'datadog.rack_request_span'` instead.
I've replaced all occurrences …
=> Use rack compliant keys

lib/ddtrace/contrib/grape/endpoint.rb, lib/ddtrace/contrib/rack/middlewares.rb, test/contrib/rack/helpers.rb
Although we'd like to apply this change at some point, we merged it too early. This constitutes a breaking change, since some users might be depending upon Rack's `env[:datadog_rack_request_span]`.
We'll roll this out again for a minor release as a breaking change, perhaps in 0.12.0 or a future version.
Reverts DataDog/dd-trace-rb#338
=> Revert "Use rack compliant keys"

Appraisals, gemfiles/contrib.gemfile, gemfiles/rails4_mysql2.gemfile, gemfiles/rails5_mysql2.gemfile
`mysql2` version 0.5.0 was released yesterday, and following in ActiveRecord tradition, new adapter versions break ActiveRecord, which in turn is breaking our CI build.
This pull request pins the gem version to < 0.5.0, until the Rails guys fix the issue. See https://github.com/rails/rails/pull/32310.
=> Pin mysql2 < 0.5.0 to prevent CI build from breaking

lib/ddtrace/contrib/racecar/patcher.rb, spec/ddtrace/contrib/racecar/patcher_spec.rb
This pull request refactors the Racecar integration to use the `ActiveSupport::Notifications::Subscriber` module.
Is currently base on the parent PR #380, which must be merged first.
=> Use ActiveSupport::Notifications::Subscriber with Racecar

lib/ddtrace/transport.rb, lib/ddtrace/writer.rb, spec/ddtrace/writer_spec.rb, spec/support/http_helpers.rb
If priority sampling is enabled, and HTTPTransport attempts to write service spans to the agent, it will trigger the sampling updater callback which will try to process the services response (which is `OK`) as a traces response (which is JSON), resulting in lots of parse errors.
This pull request passes the action as a parameter to the callback, so it can use that information to change how it handles responses.
Should be rebased and merged after #369.
Side note; this should probably be considered a stop-gap measure. There's a lot of coupling between Writer, Transport, and the concept of "API" which makes this design fairly brittle. Would recommend a refactor in the future.
=> Fix HTTPTransport sampling callback for services

docs/GettingStarted.md, lib/ddtrace/contrib/rack/middlewares.rb, lib/ddtrace/contrib/rack/patcher.rb, test/contrib/rack/middleware_test.rb
Adds quantization for Rack URL query string parameters. This behavior is activated by default, but can be configured with:
```
c.use :rack, quantize: { query: { show: ['category_id'] } }
c.use :rack, quantize: { query: { show: :all } }
c.use :rack, quantize: { query: { exclude: ['sort_by'] } }
c.use :rack, quantize: { query: { exclude: :all } }
c.use :rack, quantize: { fragment: :show }
end
```
=> Add URL query string quantization to Rack

lib/ddtrace/contrib/active_record/patcher.rb, lib/ddtrace/contrib/rails/active_record.rb, lib/ddtrace/contrib/rails/utils.rb, test/contrib/rails/tracer_test.rb
Our previous implementation of connection configuration was always getting a default adapter configuration and using that to populate host, port and database tags for `sql.active_record` events.
This pull request adds functionality to retrieve more accurate information when the connection object ID is available, which is supplied in the payload for `sql.active_record`. With this change, we use that connection to populate the tags for ActiveRecord traces.
Such a change should represent a step forward in supporting multi-DB setups although we have yet to add support for configuring different DB connections as different services.
For a request that creates the following records into different databases with sharding via `active_record_shards`:
The resulting trace which tags different DB …
=> Use correct ActiveRecord connection for `sql.active_record` events

docs/GettingStarted.md, lib/ddtrace/contrib/elasticsearch/patcher.rb, lib/ddtrace/contrib/elasticsearch/quantize.rb, test/contrib/elasticsearch/quantize_test.rb, test/contrib/elasticsearch/transport_test.rb
Adds enhanced quantization for ElasticSearch body tags. This behavior is activated by default, but can be configured with:
```ruby
c.use :elasticsearch, quantize: { show: [:category_id], exclude: [:edit_date] }
end
```
Which would change:
```
{"query":{"match":{"title":"?","category_id":"?","edit_date":"?"}}}
```
Into:
```
{"query":{"match":{"title":"?","category_id":"285"}}}
```
=> ElasticSearch body quantization

lib/ddtrace/contrib/grape/endpoint.rb, lib/ddtrace/contrib/rack/middlewares.rb, test/contrib/rack/helpers.rb
This pull request is a reissue of #338 , which fixed an issue with use of symbols with Rack, by converting a key to a string instead.
That pull request had to be reverted since it introduced a breaking change for anyone dependent on `env[:datadog_rack_request_span]`. This pull request seeks to re-add those changes, but with backwards compatibility and a deprecation warning.
In a future version, likely 0.13.0, we will remove both the deprecation warning and the backwards compatibility present here.
=> Use Rack compliant keys with deprecation

README.md, docs/GettingStarted.md
Our documentation needs some love. In an effort to consolidate information, and make features and API descriptions more discoverable, this pull request reworks README and GettingStarted.
Our documentation collection should henceforth look like:
- Quick start instructions: https://docs.datadoghq.com/tracing/setup/ruby/
- Development and contributing: https://github.com/DataDog/dd-trace-rb/blob/master/README.md
- Installation, configuration, API details: https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md
- Using the APM UI: https://docs.datadoghq.com/tracing/visualization/
- Current gem documentation (same as GettingStarted): http://gems.datadoghq.com/trace/docs/
=> Make documentation more consistent

lib/ddtrace/contrib/active_support/notifications/subscription.rb, lib/ddtrace/contrib/racecar/patcher.rb, spec/ddtrace/contrib/active_support/notifications/subscription_spec.rb
When we extracted `Datadog::Contrib::ActiveSupport::Notifications::Subscription` from our Racecar integration, we migrated a `ensure_clean_context!` method along with it. This was in error; this method is specific to Racecar, and is causing side-effects for other subscription based integrations.
This pull request removes `ensure_clean_context!` from the subscription, and replaces it with `before_trace`/`after_trace` callbacks. Racecar then uses this new set of callbacks to re-implement  `ensure_clean_context!` in its own patcher.
Should unblock #340.
=> Extract #ensure_clean_context! from ActiveSupport::Notifications subscription

docs/GettingStarted.md, lib/ddtrace/context.rb, lib/ddtrace/context_flush.rb, lib/ddtrace/tracer.rb, test/context_flush_test.rb, test/context_test.rb, test/span_test.rb
For big traces (typically, long-running traces with one enclosing span and many sub-spans, possibly several thousands) the library could keep everything in memory waiting for an hypothetical flush.
This patch partially flushes consistent parts of traces, so that they don't fill up the RAM.
=> [tracer] reduce memory usage on high-cardinality traces

lib/ddtrace/contrib/rails/core_extensions.rb
Some gems patch ActionController by overriding `process_action`, which creates a conflict that can result in either gem not working properly.
The problem can manifest as traces that are missing ActionController traces:
This pull request adds a `prepend` patching strategy for applications that use Ruby 2.0+, which prevents this from happening. Applications that use Ruby < 1.9.3 that also have a gem that conflicts with ours, will *not* be fixed by this change.
=> Fix ActionController patching conflict

lib/ddtrace/contrib/active_support/notifications/subscription.rb, lib/ddtrace/contrib/racecar/patcher.rb, lib/ddtrace/tracer.rb, spec/ddtrace/contrib/active_support/notifications/subscription_spec.rb, spec/support/log_helpers.rb
This pull request fixes two bugs:
- Integrations implementing ActiveSupport::Notifications subscriptions whose block raises an error could raise exceptions breaking application flow. Error handling around the block traps and logs these errors now.
- `ensure_clean_context!` wasn't working; fixes use of `tracer`.
Also adds support for `call` for 3.x ActiveSupport implementations and refactors the internals of Subscription a little (should improve extensibility.)
=> Add ActiveSupport::Notifications subscription error handling

lib/ddtrace/contrib/rack/middlewares.rb
Change target removal version from 0.13.0 to 0.14.0.
=> Change deprecation warning for Rack request span

lib/ddtrace/tracer.rb
Looks like we accidentally gave this setting the wrong value.
=> Fix min_spans_before_partial_flush option setting

docs/GettingStarted.md, lib/ddtrace/contrib/rack/middlewares.rb, lib/ddtrace/contrib/rack/patcher.rb, lib/ddtrace/contrib/rack/request_queue.rb, test/contrib/rack/request_parser_test.rb, test/contrib/rack/request_queueing_test.rb, test/contrib/rack/request_queuing_test.rb
Provides the request queuing time from the Rack middleware if a frontend web server or load balancer sets a specific header. This is considered an **experimental** feature and may have breaking changes in the future.
* your web server should set the `x-request-start` header
* your Rack integration should be configured with the following options
```ruby
c.use :rack, request_queuing: true, web_service_name: 'nginx'
end
```
At the time of writing, only `nginx` headers are supported in the format of `t=1512379167.574`.
=> [rack] add request queuing option to the Rack middleware

lib/ddtrace/contrib/active_record/event.rb, lib/ddtrace/contrib/active_record/events.rb, lib/ddtrace/contrib/active_record/events/instantiation.rb, lib/ddtrace/contrib/active_record/events/sql.rb, lib/ddtrace/contrib/active_record/patcher.rb, lib/ddtrace/contrib/active_support/notifications/event.rb, lib/ddtrace/contrib/racecar/event.rb, lib/ddtrace/contrib/racecar/events.rb, lib/ddtrace/contrib/racecar/events/batch.rb, lib/ddtrace/contrib/racecar/events/message.rb, lib/ddtrace/contrib/racecar/patcher.rb, spec/ddtrace/contrib/active_support/notifications/event_spec.rb, spec/ddtrace/contrib/racecar/patcher_spec.rb, test/contrib/rails/controller_test.rb, test/contrib/rails/database_test.rb, test/contrib/rails/rack_middleware_test.rb, test/contrib/sinatra/tracer_activerecord_test.rb
This pull request adds the `Datadog::Contrib::ActiveSupport::Notifications::Event` helper, which provides a pattern for modeling instrumentation events for ActiveSupport::Notifications. The goal of this is to make use of the Subscriber API a little cleaner, easier to use, and more extensible.
It also refactors ActiveRecord and Racecar to implement this pattern.
=> Add ActiveSupport::Notifications::Event helper

docs/GettingStarted.md, lib/ddtrace/contrib/rack/middlewares.rb, lib/ddtrace/contrib/rack/patcher.rb, lib/ddtrace/ext/http.rb, test/contrib/rack/helpers.rb, test/contrib/rack/middleware_test.rb
This pull requests allows users to define which HTTP headers appear as tags on their `rack.request` span.
To do so, add the following option to your configuration:
```ruby
c.use :rack, headers: { request: ['Accept-Encoding'], response: ['Content-Encoding'] }
end
```
Will result in the following tags:
- `http.request.headers.accept_encoding`
- `http.response.headers.content_encoding`
By default, `:headers` is set to `{ response: ['Content-Type', 'X-Request-ID'] }`.
This pull request also removes `http.request_id` in favor of `http.request.headers.x_request_id` and `http.response.headers.x_request_id`.
=> Add request and response header tags to Rack

lib/ddtrace/contrib/sequel/database.rb, lib/ddtrace/contrib/sequel/dataset.rb, spec/ddtrace/contrib/sequel/configuration_spec.rb, spec/ddtrace/contrib/sequel/instrumentation_spec.rb
As reported [here](https://github.com/DataDog/dd-trace-rb/pull/171#issuecomment-383942175), and can be replicated in [this Gist](https://gist.github.com/twe4ked/590db5a686104770a53a78b657eacc3d), if you initialize a Sequel database before patching `Sequel` with `Datadog.configure`, then the already initialized databases will be missing pins, and fail to trace.
This pull request bumps Pin setup out of the `initialize` method and into the `datadog_pin` method, where it's lazily instantiated. It adds a test for it, and refactors some of the existing configuration tests for Sequel.
=> Fix no Sequel pin when initialized before patched

spec/ddtrace/contrib/grpc/support/grpc_helper.rb
Approximately 5% of server streams complete and exit before the FauxWriter can grab the mutex to record the server spans. This fix adds a 10ms sleep at the end of the server~>client stream to give the
FauxWriter enough time to record the span.
This happens only during the integration test. I verified both the rate of failure and the fix by running the following several times:
```shell
for i in {1..100}; do
BUNDLE_GEMFILE=/Users/jared/code/dd-trace-rb/gemfiles/contrib.gemfile bundle exec rspec spec/ddtrace/contrib/grpc
done
```
=> prevent race condition while running tests

Appraisals, Rakefile, gemfiles/contrib.gemfile, gemfiles/contrib_old.gemfile, lib/ddtrace.rb, lib/ddtrace/contrib/active_model_serializers/event.rb, lib/ddtrace/contrib/active_model_serializers/events.rb, lib/ddtrace/contrib/active_model_serializers/events/render.rb, lib/ddtrace/contrib/active_model_serializers/events/serialize.rb, lib/ddtrace/contrib/active_model_serializers/patcher.rb, spec/ddtrace/contrib/active_model_serializers/helpers.rb, spec/ddtrace/contrib/active_model_serializers/patcher_spec.rb, spec/ddtrace/contrib/active_support/notifications/subscription_spec.rb
I'm currently using ActiveModelSerializers on a few different Rails projects, and want to be able to trace the serialization like a rails view. This implementation borrows heavily from the racecar patcher.
* Subscribe to the appropriate event for AMS 0.10 and AMS 0.9
* 0.10 - https://github.com/rails-api/active_model_serializers/blob/v0.10.6/docs/general/instrumentation.md
* 0.9 - https://github.com/rails-api/active_model_serializers/blob/v0.10.6/docs/general/instrumentation.md
* Trace a span with the serializer as the name
I still need to write tests, but wanted to open the PR early to get feedback on the implementation. Thanks!
=> Instrument ActiveModelSerializers

docker-compose.yml, gemfiles/rails5_mysql2.gemfile, gemfiles/rails5_postgres.gemfile, gemfiles/rails5_postgres_redis.gemfile, gemfiles/rails5_postgres_sidekiq.gemfile, spec/ddtrace/contrib/active_record/tracer_spec.rb, spec/ddtrace/contrib/dalli/instrumentation_spec.rb, spec/ddtrace/contrib/redis/integration_spec.rb, spec/ddtrace/contrib/redis/method_replaced_spec.rb, test/contrib/elasticsearch/integration_test.rb, test/contrib/http/integration_test.rb, test/contrib/http/miniapp_test.rb, test/contrib/http/request_test.rb, test/contrib/rack/helpers.rb, test/contrib/rails/apps/application.rb, test/contrib/rails/apps/rails3.rb, test/contrib/sinatra/tracer_activerecord_test.rb
In order to more faithfully recreate a development environment that mirrors our CI pipeline and environment, we can use Docker compose to run tests locally in Docker containers.
This pull request uses the same images from our CI pipeline for use in `docker-compose.yml`, making it easy to spin up and run tests in a local environment. Now to debug a broken CI test locally, you can just:
1. Run `docker-compose run --rm tracer-2.3` (or whatever Ruby version you wish.)
2. In the container, run `bundle install` then `appraisal install`.
3. Run `rake ci` to run the same tests Circle runs.
=> Dockerize the test suite

lib/ddtrace/contrib/rails/core_extensions.rb, spec/ddtrace/contrib/rails/action_controller_spec.rb
When `ActionController::Metal#response` was an `Array` instead of a `ActionDispatch::Response`, tracing raised an error. This manifested in Devise's `FailureApp` which is [overriding the value of `response`](https://github.com/plataformatec/devise/blob/master/lib/devise/failure_app.rb#L75) with an Array, in an unexpected way. You can reproduce this by attempting to login with bad credentials.
Only affects users who use Devise and ddtrace 0.12.0.
This pull request attempts to handle both `ActionDispatch::Response` and `Array` responses, and if it doesn't receive either, it doesn't set a status.
Addresses https://github.com/DataDog/dd-trace-rb/issues/419
=> Fix NoMethodError when ActionController::Metal#response is an Array

lib/ddtrace/contrib/elasticsearch/patcher.rb, test/contrib/elasticsearch/dummy_faraday_middleware.rb, test/contrib/elasticsearch/transport_test.rb
`Elasticsearch::Client` is a convenience wrapper for `Elasticsearch::Transport::Client`.
Which provides the ability to initialize the client with a block while allowing
to configure the faraday instance directly.
Now, because `Datadog::Contrib::Elasticsearch` monkey patches this behavior,
and calls the parent/original `initialize` function (aliased as `initialize_without_datadog`),
it however misses to pass in the block, and only sends the arguments.
Which means, using the dd-trace gem in applications which initialize `Elasticsearch::Client`
with block becomes risky, as custom faraday configurations are lost.
This PR fixes the issue.
=> Make sure to correctly preserve block for Elasticsearch::Transport::Client

.rubocop.yml, Rakefile, ddtrace.gemspec, spec/ddtrace/contrib/active_record/tracer_spec.rb, spec/ddtrace/contrib/active_record/utils_spec.rb, spec/ddtrace/contrib/active_support/notifications/subscriber_spec.rb, spec/ddtrace/contrib/active_support/notifications/subscription_spec.rb, spec/ddtrace/contrib/faraday/middleware_spec.rb, spec/ddtrace/contrib/graphql/tracer_spec.rb, spec/ddtrace/contrib/racecar/patcher_spec.rb, spec/ddtrace/contrib/rails/middleware_spec.rb, spec/ddtrace/contrib/rails/rails_helper.rb, spec/ddtrace/contrib/rails/support/base.rb, spec/ddtrace/contrib/rails/support/configuration.rb, spec/ddtrace/contrib/rails/support/database.rb, spec/ddtrace/contrib/rails/support/middleware.rb, spec/ddtrace/contrib/rails/support/rails3.rb, spec/ddtrace/contrib/rails/support/rails4.rb, spec/ddtrace/contrib/rails/support/rails5.rb, spec/ddtrace/contrib/redis/integration_spec.rb, spec/ddtrace/contrib/redis/quantize_spec.rb, spec/ddtrace/contrib/redis/redis_spec.rb, spec/ddtrace/patcher_spec.rb, spec/ddtrace/quantization/http_spec.rb, spec/ddtrace/registry_spec.rb, spec/ddtrace/transport_spec.rb, spec/ddtrace/writer_spec.rb, test/contrib/rack/helpers.rb, test/contrib/rails/rack_middleware_test.rb
I've found out spec files are not following Rubocop linting configuration. 
This PR aligns the code in spec with Rubocop configuration. Its mostly a product of running `rubocop -a ` in a loop.
=> Cleanup Rubocop warnings for spec files

docs/GettingStarted.md, lib/ddtrace/contrib/rails/action_controller_patch.rb, lib/ddtrace/contrib/rails/core_extensions.rb, test/contrib/rails/apps/controllers.rb, test/contrib/rails/controller_test.rb
While implementing possible alternative solution to https://github.com/DataDog/dd-trace-rb/pull/436
I've found that we already support tagging spans from within Controller methods.
This PR is meant to salvage some of that work
Todo:
=> Add tests to verify active_span can be tagged from within controller methods

lib/ddtrace/contrib/aws/instrumentation.rb, test/contrib/aws/instrumentation_test.rb
As per issue https://github.com/DataDog/dd-trace-rb/issues/374, this PR goal is to make the AWS service page behave in a similar way to other services such as Rails/Web/Redis... 
As I see it `aws.command` label does not add any value in either the service page or trace view, since AWS service will alread be defined by `AWS` by default, we can easily find out that traces are coming from there.
On the service page what we want to see is a list of methods/actions and how they are performing, each method can then be further drilled down for related traces.
The current behaviour :
With this PR the service be would have each method listed :
=> Change span.resource to use AWS command name

lib/ddtrace/contrib/sidekiq/tracer.rb, test/contrib/sidekiq/tracer_test.rb
Delay represent the time for a job spent in queue waiting to be taken by a worker, in millisecond. Such metric is useful to tell if sidekiq is under too much load and can't keep up with the throughput of new jobs being created.
cc @delner I've based commits against 0.13-dev
=> Adds delay metric to sidekiq traces

lib/ddtrace/contrib/rails/action_view.rb, lib/ddtrace/contrib/rails/core_extensions.rb, test/contrib/rails/errors_test.rb
As revealed by #445, when the hard-cap span limit is reached for a trace (~100K), the Rails renderer tracing starts mishandling spans. This is because it was relying on `tracer.call_context.current_span` which returns the last span in the context when the context fills, as opposed to the most recently instantiated span.
Although addressing the behavior of `tracer.call_context.current_span` and its equivalent `tracer.active_span` remains an issue at large, we can avoid this altogether in the Rails code.
This pull request removes "tracing context" management and context-specific code from the Rails patch altogether, and opts for a much simpler `tracer.trace` approach instead. This should resolve #445 by simply avoiding the code path in question altogether.
=> Fix ActionView tracing contexts when span limit is reached

lib/ddtrace/contrib/elasticsearch/quantize.rb, test/contrib/elasticsearch/quantize_test.rb
This PR fixes quantization of URLs in ES client. It does so by replacing any path segment that has numbers in them with '?'.
https://github.com/DataDog/dd-trace-rb/blob/20eda5d1597ecf442a9621cac6ce64fcc12e5a63/test/contrib/elasticsearch/quantize_test.rb#L12
=> [elasticsearch] Expand quantization, to cut out all request segments containing numbers

lib/ddtrace/opentracer.rb, lib/ddtrace/opentracer/global_tracer.rb, lib/ddtrace/opentracer/tracer.rb, spec/ddtrace/opentracer/global_tracer_spec.rb, spec/ddtrace/opentracer/tracer_spec.rb
This pull request allows users to configure the `Datadog::OpenTracer::Tracer` with configuration settings to get the most out of their tracer setup.
```ruby
Datadog::OpenTracer::Tracer.new(options).tap do |tracer|
OpenTracing.global_tracer = tracer
tracer.datadog_tracer
tracer.configure(options)
c.use :rails
end
end
```
A more abbreviated, practical example might look like:
```ruby
OpenTracing.global_tracer = Datadog::OpenTracer::Tracer.new(options)
c.use :rails
end
```
=> [OpenTracing] Add OpenTracing configuration

lib/ddtrace/opentracer.rb, lib/ddtrace/opentracer/span.rb, lib/ddtrace/opentracer/span_context.rb, lib/ddtrace/opentracer/span_context_factory.rb, spec/ddtrace/opentracer/span_context_factory_spec.rb, spec/ddtrace/opentracer/span_context_spec.rb, spec/ddtrace/opentracer/span_spec.rb
This pull request implements the OpenTracing `Span` and `SpanContext`. In their current forms, they are very simple, and may not represent the full scope of what will ultimately be supported.
Some worthwhile notes:
- The constructors for `Span` and `SpanContext` are still somewhat undetermined. They may require changes depending on how and where we actually construct and configure spans. The current plan is that they are treated like simple data structs, that are not responsible for building sophisticated Spans or SpanContexts. That logic is anticipated to be a part of the Tracer, or some kind of factory pattern.
- There's some ambiguity as to how `log` and `log_kv` should be implemented. For now, they simply set errors, if provided with one. Otherwise they do nothing. We didn't interpret …
=> [OpenTracing] Span and SpanContext implementation

.circleci/config.yml
Since CircleCI 2.0, we haven't been building for tag pushes, or generating and releasing documentation for them.
This pull request adds a deploy step at the end of the build, that runs only when a tag is pushed that matches a version pattern.
=> Fix release docs in CI pipeline

lib/ddtrace/opentracer.rb, lib/ddtrace/opentracer/scope.rb, lib/ddtrace/opentracer/thread_local_scope.rb, lib/ddtrace/opentracer/thread_local_scope_manager.rb, spec/ddtrace/opentracer/scope_spec.rb, spec/ddtrace/opentracer/thread_local_scope_manager_spec.rb, spec/ddtrace/opentracer/thread_local_scope_spec.rb
This pull request implements Scope and ScopeManager. It's more or less based off what was done in https://github.com/opentracing/opentracing-python/pull/77 for consistency.
=> [OpenTracing] Scope and ScopeManager implementation

docs/GettingStarted.md
Our default was changed in a prior version and so docs are updated now.
=> [docs] update Rails default in docs

lib/ddtrace/writer.rb
On certain linux systems there seems to be a bug in libc which causes deadlock of Ruby interpreter. 
It only happens when ruby tries to resolve a hostname and its specifically triggered with many short-lived Ruby processes e.g. Resque. 
See issue - https://github.com/DataDog/dd-trace-rb/issues/466 - where the solution was to use IP address instead of hostname. 
Also [this comment](https://github.com/DataDog/dd-trace-rb/issues/466#issuecomment-400322260) that contains GDB trace of all threads seems to directly point to libc call to resolve hostname.
=> Use IP address instead of hostname to avoid a bug in libc

lib/ddtrace/workers.rb, lib/ddtrace/writer.rb
- Avoid using mutex when Pids are the same, reduces lock contention improving throughput 2-3x in processes using more threads
- For short running processes we were capped at the worker timeout which was 1s. With this change the worker is shut down immediately once data is flushed. Increasing throughput of applications like resque.
=> Improve performance of multithreaded operation in short running processes

lib/ddtrace/contrib/sequel/configuration/settings.rb, lib/ddtrace/contrib/sequel/database.rb, lib/ddtrace/contrib/sequel/integration.rb, lib/ddtrace/contrib/sequel/patcher.rb, spec/ddtrace/contrib/sequel/configuration_spec.rb, spec/ddtrace/contrib/sequel/instrumentation_spec.rb
This pull request implements the configuration core from #450 in the Sequel integration.
=> Implement Sequel integration configuration

lib/ddtrace/workers.rb, spec/ddtrace/workers_spec.rb
When running the gem in production, we came across the following error:
```
09:24:55.681 .../bundle/ruby/2.5.0/gems/ddtrace-0.13.0/lib/ddtrace/workers.rb:46:in `rescue in callback_traces': undefined local variable or method `items' for #<Datadog::Workers::AsyncTransport:0x000055cecd711640> (NameError)
09:24:55.681 .../bundle/ruby/2.5.0/gems/ddtrace-0.13.0/lib/ddtrace/workers.rb:38:in `callback_traces'
09:24:55.681 .../bundle/ruby/2.5.0/gems/ddtrace-0.13.0/lib/ddtrace/workers.rb:111:in `block in perform
```
And noticed that [this commit](https://github.com/DataDog/dd-trace-rb/commit/43d67d5063a37647468f1ac3a3da40157bc3c828?diff=split#diff-0aa40585cc9b770a220ef7fc86b6655fR30) changed the variable name in the method body but not in the rescue block.
This PR updates the variable names to the …
=> Fix variable names in rescue blocks

lib/ddtrace/tracer.rb, spec/ddtrace/tracer_spec.rb
When tracing code with block syntax such as:
```ruby
tracer.trace('http.request') do |span|
client.get
end
```
...the tracer automatically creates a span and yields to the block. However, if the tracer were to raise an error before the block were invoked, the instrumented code might never run (in this example `client.get`.) This could break application behavior in an undesirable way.
This pull request treats the block as an `ensure`: it should always run regardless of whether tracing is working or not. If an error occurs when the tracing begins, it catches it, logs it in debug, then yields `nil` to the block to continue execution. This should make for less intrusive behavior if tracing were to somehow malfunction.
=> Ensure trace yield on #start_span error

docs/GettingStarted.md, lib/ddtrace/tracer.rb, spec/ddtrace/tracer_spec.rb
In a number of integrations, particularly HTTP integrations, instrumented can raise errors that are considered non-critical, or even quite normal. e.g. 404s, 403s, etc.
When provided a block, `Datadog::Tracer#trace` adds some default error handling. It catches any exception, adds it to the active span, then re-raises. This is desirable in most cases, but for non-critical errors like those mentioned above, this can cause spans to be tagged as errors in a way that's undesirable. Currently the only way to work around this is to use the non-block syntax, which creates some repetition, and is generally not preferred.
This pull request adds the `on_error` option to the `#trace` function, which allows users to provide a `Proc` to define custom error behavior.
For example:
```ruby
def get …
```
=> Add on_error callback option for tracing

docs/GettingStarted.md
The MySQL2 integration traces any SQL command sent through `mysql2` gem.
```ruby
require 'mysql2'
c.use :mysql2, options
end
client = Mysql2::Client.new(:host => "localhost", :username => "root")
client.query("SELECT * FROM users WHERE group='x'")
```
Where `options` is an optional `Hash` that accepts the following parameters:
| Key | Description | Default |
| --- | --- | --- |
| ``service_name`` | Service name used for MySQL2 instrumentation | `mysql2` |
| ``tracer`` | A ``Datadog::Tracer`` instance used to instrument the application. Usually you don't need to set that. | ``Datadog.tracer`` |
=> Add missing MySQL2 documentation

lib/ddtrace/contrib/active_support/notifications/subscription.rb, spec/ddtrace/contrib/active_support/notifications/subscription_spec.rb
In multithreaded setup and when using connection pool while performing many SQL queries, the `active_span` in finishing of event was not always the same to span created at the start of an event.
This caused some odd spans to not properly close - leaking memory in the process. Benchmark application memory use did baloon 2-4x in a matter of minutes
This PR addresses this issue.
Its possible it might one of the causes of #431, as this regression was introduced in 0.12.0 and affects multithreaded apps - i.e. Sidekiq.
Todo:
=> Make sure spans are closed when processing notifications

lib/ddtrace/monkey.rb, lib/ddtrace/pin.rb
remove unnecessary duplicated code that caused Ruby to issue warnings.
=> No more ruby warnings

lib/ddtrace/contrib/active_record/integration.rb, lib/ddtrace/contrib/patchable.rb, lib/ddtrace/contrib/sequel/integration.rb, spec/ddtrace/contrib/patchable_spec.rb
This pull request adds `#version` and `#present?` to `Datadog::Contrib::Patchable` to expose version numbers in a more consistent manner.
=> Add version to Integration

lib/ddtrace/propagation/http_propagator.rb, spec/ddtrace/propagation/http_propagator_spec.rb, spec/ddtrace/propagation/propagation_integration_spec.rb
If you provide `HttpPropagator#inject!` a nil `Context`, it will raise an error. This pull request adds a simple check to avoid errors if traces can't be propagated for this reason.
Depends on #501 which refactors some tests.
=> Prevent HttpPropagator errors given a nil Context

lib/ddtrace/opentracer.rb, lib/ddtrace/opentracer/binary_propagator.rb, lib/ddtrace/opentracer/distributed_headers.rb, lib/ddtrace/opentracer/propagator.rb, lib/ddtrace/opentracer/rack_propagator.rb, lib/ddtrace/opentracer/text_map_propagator.rb, lib/ddtrace/opentracer/tracer.rb, spec/ddtrace/opentracer/binary_propagator_spec.rb, spec/ddtrace/opentracer/distributed_headers_spec.rb, spec/ddtrace/opentracer/propagation_integration_spec.rb, spec/ddtrace/opentracer/propagator_spec.rb, spec/ddtrace/opentracer/rack_propagator_spec.rb, spec/ddtrace/opentracer/text_map_propagator_spec.rb, spec/ddtrace/opentracer/tracer_spec.rb
This pull request implements context propagation using `Propagator` classes, which serialize/deserialize trace context from carriers.
It provides full implementation for `Rack` and `TextMap` formats. `Binary` format is still a no-op.
=> [OpenTracing] Context propagation implementation

docs/GettingStarted.md, lib/ddtrace/context.rb, lib/ddtrace/tracer.rb, spec/ddtrace/context_spec.rb, spec/ddtrace/tracer_integration_spec.rb, spec/ddtrace/tracer_spec.rb
To aid the traversal of active spans (for example to tag a trace with tags), this pull request introduces the `active_root_span` function to the Tracer, which works like the `active_span` function.
```ruby
current_root_span = Datadog.tracer.active_root_span
current_root_span.set_tag('my_tag', 'my_value') unless current_root_span.nil?
```
=> Add active_root_span to Tracer

lib/ddtrace/opentracer/rack_propagator.rb, lib/ddtrace/opentracer/text_map_propagator.rb, spec/ddtrace/opentracer/rack_propagator_spec.rb, spec/ddtrace/opentracer/text_map_propagator_spec.rb
While testing our Opentracer adapter with `ruby-rack-tracer`, we ran into an edge case where when the `Rack::Env` contains a symbol key, then propagation in our Opentracer adapter raises an error `undefined method 'start_with?' for :"ot-baggage-account_name":Symbol`.
This pull request coerces symbols to strings when attempting to do this kind of propagation.
=> [OpenTracing] Fix symbol propagation

lib/ddtrace/contrib/rack/middlewares.rb, spec/ddtrace/contrib/rack/middleware_spec.rb
There is a deprecation warning for the Rack integration when the Rack Env is accessed using the symbol name that was deprecated. This warning is triggered on a edge case where the same Env object is passed through the middleware multiple times; presumably because a web server is re-using the object instead of allocating new memory. This most readily manifests when using Unicorn.
This pull request adds a block around Datadog's use of the deprecated symbol (which exists for backwards compatibility) so that it doesn't raise this error if the object is re-used.
=> Fix deprecation warnings when Rack Env is re-used

lib/ddtrace/sampler.rb, test/sampler_test.rb
If sampling_priority was set on context from incoming headers or manually by the user. That value then got ignored and overwritten by `PrioritySampler`.
This PR fixes this issue.
TODO:
=> Use incoming sample priority to decide if the span should be sampled or not

lib/ddtrace/contrib/grape/endpoint.rb
As raised in #525 , this pull request adds a missing require so Grape can be loaded normally.
=> Fix missing Rack::TraceMiddleware constant for Grape

lib/ddtrace/opentracer/distributed_headers.rb, spec/ddtrace/opentracer/distributed_headers_spec.rb
Analogous to #530 , OpenTracing was discarding signed integers displayed as negative integers received via distributed tracing from other tracers. This pull request applies the same kind of conversion of signed to unsigned int, to provide compatibility.
=> [OpenTracing] Fix distributed tracing signed int ids

docs/GettingStarted.md, lib/ddtrace/contrib/rack/patcher.rb, lib/ddtrace/contrib/rails/patcher.rb, lib/ddtrace/contrib/rails/railtie.rb, spec/ddtrace/contrib/rails/railtie_spec.rb, spec/ddtrace/contrib/rails/support/application.rb, spec/ddtrace/contrib/rails/support/rails3.rb, spec/ddtrace/contrib/rails/support/rails4.rb, spec/ddtrace/contrib/rails/support/rails5.rb
As per #149, Rails instrumentation is auto-injecting a Railtie and trace middleware into the Rails application by virtue of loading. This means that it isn't really possible to disable trace middleware in this case.
This pull request seeks to make Rails instrumentation optional, by:
- Preventing the Railtie by loading automatically, and apply instrumentation from the Rails patcher instead.
- Add a `middleware` option, which defaults to `true`. When set to false, trace middleware will not be added to the application.
This would be good to have for users who want to use instrumentation in Rails apps without instrumenting Rails, and for OpenTracing users who'd want to prevent conflicting middleware from running in their Rails applications.
=> Add Rails middleware option

lib/ddtrace.rb, lib/ddtrace/contrib/active_model_serializers/configuration/settings.rb, lib/ddtrace/contrib/active_model_serializers/event.rb, lib/ddtrace/contrib/active_model_serializers/events/render.rb, lib/ddtrace/contrib/active_model_serializers/events/serialize.rb, lib/ddtrace/contrib/active_model_serializers/ext.rb, lib/ddtrace/contrib/active_model_serializers/integration.rb, lib/ddtrace/contrib/active_model_serializers/patcher.rb
This pull request implements the configuration core from #450 in the ActiveModelSerializers integration.
=> Implement ActiveModelSerializers integration configuration

docs/GettingStarted.md
In this pull request we fix a couple of issues in the documentation:
- `mysql2` supports down to version `0.3.10`, not just `>= 0.5.0`
- Removed a `databases` option in Rails, because it doesn't actually exist. This was superseded by a different implementation, which already had a correct code sample in the documentation.  See #574 for details.
=> Update docs for mysql2 and databases option

docs/GettingStarted.md, lib/ddtrace/contrib/aws/patcher.rb, lib/ddtrace/contrib/concurrent_ruby/configuration/settings.rb, lib/ddtrace/contrib/dalli/patcher.rb, lib/ddtrace/contrib/elasticsearch/patcher.rb, lib/ddtrace/contrib/faraday/configuration/settings.rb, lib/ddtrace/contrib/grape/patcher.rb, lib/ddtrace/contrib/grpc/configuration/settings.rb, lib/ddtrace/contrib/http/configuration/settings.rb, lib/ddtrace/contrib/mongodb/patcher.rb, lib/ddtrace/contrib/mysql2/configuration/settings.rb, lib/ddtrace/contrib/rake/configuration/settings.rb, lib/ddtrace/contrib/redis/configuration/settings.rb, lib/ddtrace/contrib/resque/patcher.rb, lib/ddtrace/contrib/sucker_punch/patcher.rb
There were several places in the docs describing integrations that were inconsistent. Some changes this pull request makes to address these inconsistencies is:
- Add the missing Active Model Serializers integration to documentation
- Alphabetized integrations and option lists
- Removed redundant `option :tracer` in certain configurations
- Added some options that were missing (e.g. `split_by_domain`)
- Implemented `tracer` option for some integrations that didn't (the described behavior wasn't working)
These changes should all make the documentation and behavior of the tracer a bit more consistent with what was intended.
=> Make integration options more consistent

lib/ddtrace/transport.rb
Default open_timeout is 60 s. 
This is too long.
This PR sets it to 1s.
=> Add open_timeout to http connection to the agent.

.circleci/config.yml, Rakefile, tasks/release_gem.rake
Improve sharing of build artifacts by deploying gems to a S3 bucket thats actually a gem repository.
Current its available at `http://gems.datadoghq.com/prerelease`
So on can use gems built by this CI step by writing following in the Gemfile:
```
source 'http://gems.datadoghq.com/prerelease' do
gem 'ddtrace', '>= 0.16.0.ci.bring.back.builds.17511', '< 0.16.0'
end
```
=> [ci] Deploy release and prerelease gems to private repository

lib/ddtrace/transport.rb, lib/ddtrace/writer.rb, spec/ddtrace/writer_spec.rb
While adding debugging metrics to the tracer, I discovered that when priority sampling is enabled, the writer mishandles the JSON response it receives from the agent, when trying to use it to update its sampling rates.
It was receiving a response formatted like:
```
{"rate_by_service":{"service:,env:":1,"service:rspec,env:none":1}}
```
However, the logic was written such that it didn't expect a top level key `"rate_by_service"`, so it consumes that key as a service improperly, and throws an error when trying to process the Hash like a Float.
This bug was hidden because the callback that did this was wrapped with exception handling which silently appended to a debug log, instead of raising an exception or increasing the internal error metric.
This pull request fixes the bug by consuming …
=> Fix priority sampling mishandling agent response

lib/ddtrace/ext/http.rb, lib/ddtrace/ext/meta.rb, lib/ddtrace/ext/statsd.rb, lib/ddtrace/transport.rb, lib/ddtrace/version.rb, spec/ddtrace/transport_payload_spec.rb
`HTTPTransport` defines a number of metadata HTTP headers that contain interesting information about the tracer.
This pull request extracts those metadata definitions into a `Datadog::Ext::Meta` namespace, so that other tracing components can freely re-use this metadata. It defines the following fields:
```ruby
Datadog::Ext::Meta::LANG
Datadog::Ext::Meta::LANG_VERSION
Datadog::Ext::Meta::LANG_INTERPRETER
Datadog::Ext::Meta::TRACER_VERSION
```
=> Refactor tracer metadata into Datadog::Metadata

lib/ddtrace/encoding.rb, lib/ddtrace/transport.rb, spec/ddtrace/transport_spec.rb, spec/support/spy_transport.rb, test/benchmark_test.rb, test/encoding_test.rb, test/helper.rb
As a minor improvement, this pull request converts the existing Encoder classes to modules, which primarily benefits performance and use of these modules.
The use of these don't fit the class/subclass paradigm very well, considering that different instantiations of the same encoder never vary in data, and the functions on these are often used in a more functional way (as opposed to an object oriented way.) Their behavior is more suited for module composition, so converting these to modules allows us to save a little bit on memory allocation while making it easier to use.
=> Change encoders from classes to modules

docs/GettingStarted.md, lib/ddtrace/metrics.rb, lib/ddtrace/transport.rb, lib/ddtrace/utils/time.rb, lib/ddtrace/writer.rb, spec/ddtrace/contrib/redis/integration_spec.rb, spec/ddtrace/integration_spec.rb, spec/ddtrace/metrics_spec.rb, spec/ddtrace/transport_payload_spec.rb, spec/ddtrace/transport_spec.rb, spec/ddtrace/workers_integration_spec.rb, spec/ddtrace/writer_spec.rb, spec/support/metric_helpers.rb, spec/support/statsd_helpers.rb
Building off of #594 and #595 , this pull request adds a number of other internal tracing metrics to give more insight into the health of the tracer.
The following metrics are added with the additional following tags:
- *distribution* `datadog.tracer.transport.http.encode_time`: Time to encode the payload.
- `datadog.tracer.transport.http.encoding_type`: Encoding type of data (either `application/json` or `application/msgpack`)
- `datadog.tracer.transport.http.data_type`: Type of data encoded (either `services` or `traces`)
- *distribution* `datadog.tracer.transport.http.payload_size`: Byte size of the payload.
- `datadog.tracer.transport.http.encoding_type`: Encoding type of data (either `application/json` or `application/msgpack`)
- `datadog.tracer.transport.http.data_type`: Type of …
=> Add additional tracer metrics

lib/ddtrace/contrib/rails/action_controller.rb, lib/ddtrace/contrib/rails/action_controller_patch.rb, spec/ddtrace/contrib/rails/middleware_spec.rb
Don't rely on the immediate parent being the Rack span.
=> Set the Rails controller as the Rack resource more reliably

lib/ddtrace/contrib/rest_client/configuration/settings.rb
So the UI displays the correct icon and label.
=> Fix app type configuration of RestClient

Appraisals
`timers` 4.2.0 dropped support for older versions of Ruby and broke our builds for < Ruby 2.2.1. This pull request sets version requirements to avoid this.
=> CI: Fix timers gem not supporting < Ruby 2.2.1

lib/ddtrace/contrib/sidekiq/base_tracer.rb, lib/ddtrace/contrib/sidekiq/client_tracer.rb, lib/ddtrace/contrib/sidekiq/configuration/settings.rb, lib/ddtrace/contrib/sidekiq/ext.rb, lib/ddtrace/contrib/sidekiq/patcher.rb, lib/ddtrace/contrib/sidekiq/server_tracer.rb, lib/ddtrace/contrib/sidekiq/tracing.rb, spec/ddtrace/contrib/rails/support/base.rb, spec/ddtrace/contrib/rails/support/rails3.rb, spec/ddtrace/contrib/rails/support/rails4.rb, spec/ddtrace/contrib/rails/support/rails5.rb, test/contrib/rails/apps/application.rb, test/contrib/rails/rails_active_job_test.rb, test/contrib/rails/rails_sidekiq_test.rb, test/contrib/sidekiq/client_tracer_test.rb, test/contrib/sidekiq/disabled_tracer_test.rb, test/contrib/sidekiq/server_tracer_test.rb, test/contrib/sidekiq/tracer_configure_test.rb, test/contrib/sidekiq/tracer_test_base.rb
Sidekiq enqueues are _normally_ fast, but it seems like it'd be nice to have tracing of those enqueue/push events and therefore be able to monitor the latency of enqueues in case they aren't fast (as these can often be a good warning sign of Redis issues).
Note that I made a number of guesses here, especially concerning the span name and omitting the service (ie. that client-side enqueues should inherit their parent's service).
=> Sidekiq client-side tracing

lib/ddtrace/contrib/rails/patcher.rb, lib/ddtrace/patcher.rb, spec/ddtrace/contrib/concurrent_ruby/integration_spec.rb, spec/ddtrace/contrib/rails/railtie_spec.rb, spec/ddtrace/patcher_spec.rb
After refactoring the Rails integration in #552 and #540, we applied a new patching strategy that used `ActiveSupport.on_load(:before_initialize)` to run Rails patching code once at the appropriate time.
Turns out in some applications, these load hooks can run twice, which injects the middleware twice and causes bad side effects.
Although Rails 5.0+ offers a `run_once` option for these load hooks, they aren't available for Rails 3.0 - 4.2, which we currently support. Instead, I added a `:for` option to our existing `do_once` function which adds a second dimension to the patch hash, then used the Rails application instance as a key.
=> Prevent Rails load hooks applying patch twice

docs/GettingStarted.md
We forgot to add documentation for #602 for the new client-side tracing feature. This PR adds the `client_service_name` option to the documentation.
=> Add Sidekiq `client_service_name` option to documentation

lib/ddtrace/contrib/active_record/events/sql.rb, lib/ddtrace/contrib/configurable.rb, lib/ddtrace/utils/database.rb, spec/ddtrace/contrib/configurable_spec.rb
This pull request changes a few things:
- `Datadog::Utils::Database` values to constants.
- Return the default configuration instead of `nil` when a configuration with a mismatching key is requested.
- In ActiveRecord, if the tracer settings have a service name with the default value `defaultdb`, then default instead to the adapter name.
These changes were in order to get ActiveRecord to return service names more consistently. If connections were manually established after the AR integration was activated (when it could not determine a good default service name from a connection), spans could end up with bad service names (`defaultdb`).
By always returning at minimum the default settings object, ActiveRecord could then use those settings to determine the best name for the span based on …
=> Change configuration resolution misses to return default configuration

lib/ddtrace/contrib/active_record/events/sql.rb, lib/ddtrace/contrib/active_record/patcher.rb, lib/ddtrace/contrib/active_record/patches/abstract_adapter.rb, lib/ddtrace/contrib/active_record/utils.rb, spec/ddtrace/contrib/active_record/performance_spec.rb
As an alternative implementation to #647, this adds `:connection` to Rails `sql.active_record` event, then uses that object to derive connection configuration for the trace. To accomplish this, it leverages #648 to add a `Datadog::Shim::Double` into the `AbstractAdapter` class.
`:connection` has recently been added to Rails master via https://github.com/rails/rails/pull/34602. The  behavior in this PR is for the benefit of Rails versions preceding that change on Rails.
TODO
=> Inject :connection to sql.active_record event instead of using #_id2ref

lib/ddtrace/contrib/shoryuken/tracer.rb
Shoryuken can be run in a batch mode, in which case `sqs_msg` and `body` will be arrays.
Shoryuken [monkey patches](https://github.com/phstc/shoryuken/blob/bc7938942270a1171d1597064698d88c3f36a4ec/lib/shoryuken/manager.rb#L93) in a `message_id` method, but `attributes` won't exist on an array.
=> Support Shoryuken in batch mode

docs/GettingStarted.md, lib/ddtrace/correlation.rb, lib/ddtrace/tracer.rb, spec/ddtrace/correlation_spec.rb, spec/ddtrace/tracer_spec.rb
In many cases, such as logging, it may be useful to correlate trace IDs to other events or data streams, for easier cross referencing. This pull request adds `active_correlation_ids` to the tracer which produces a `Datadog::Correlation::Identifier` for the currently active trace, which can then be used to decorate  other data sources.
An example of this for the purpose of logging:
```ruby
require 'logger'
logger = Logger.new(STDOUT)
logger.progname = 'my_app'
logger.formatter  = proc do |severity, datetime, progname, msg|
ids = Datadog.tracer.active_correlation_ids
"[#{datetime}][#{progname}][#{severity}][dd.trace_id=#{ids.trace_id} dd.span_id=#{ids.span_id}] #{msg}\n"
end
Datadog.tracer.trace('logging.example') do
logger.warn('This is a warning.')
end
logger.warn('This …
```
=> Add correlation identifier

docs/GettingStarted.md, lib/ddtrace/correlation.rb, lib/ddtrace/tracer.rb, spec/ddtrace/correlation_spec.rb, spec/ddtrace/tracer_spec.rb
Makes some minor modifications to correlations:
- Renamed `Tracer#active_correlation_ids` to `active_correlation`
- `#trace_id` and `#span_id` return `0` instead of `nil` from `Correlation::Identifier` for inactive traces.
- Added more documentation explaining explicit requirements for correlation logging.
=> Datadog::Correlation usage improvements

lib/ddtrace/contrib/mongodb/subscribers.rb, spec/ddtrace/contrib/mongodb/client_spec.rb
I noticed with debug logging on that a number of our sidekiq traces were
being lost (sub-spans were marked as incomplete, so it was dropping many
of our sidekiq spans). I was able to get it working when I disabled the
Mongo spans, so I hunted around and figured out that the
:datadog_mongo_span thread-local variable was being overwritten when a
sidekiq job had multiple Mongo queries in it. I patched the code here to
use a hash with the event.request_id as the key and I no longer see any
of our traces being dropped!
The ticket in question that I raised originally is here: https://help.datadoghq.com/hc/en-us/requests/184670?page=1
=> Fix for broken mongodb spans

lib/ddtrace/contrib/rails/active_support.rb, test/contrib/rails/cache_test.rb, test/contrib/rails/redis_cache_test.rb
* using ActiveSupport::Cache.expand_cache_key which is also
used by Rails to expand the cache key without enumerating
relations
=> fixes #630 potential performance hit logging cache key

lib/ddtrace/contrib/configuration/settings.rb, lib/ddtrace/ext/priority.rb, spec/ddtrace/contrib/configuration/settings_spec.rb
To aid sampling of interesting events, this pull request adds an `event_sample_rate` to the configuration of all integrations. This will allow integrations to tag their spans with the `event_sample_rate` and its own configured value.
=> Add event_sample_rate configuration option

lib/ddtrace/contrib/rack/middlewares.rb, spec/ddtrace/contrib/rack/middleware_spec.rb
We previously added in a deprecation warning when we moved away from `:datadog_rack_request_span` key in the Rack env.
However, even if a user isn't trying to access this key directly some third party Gems will loop over all keys in the Rack env causing this deprecation warning to be shown. If this happens on every request then we could very easily be spamming the user's logs, which is not ideal.
The solution here is to remove the deprecation warning for now.
=> [rack] Remove deprecation warning on :datadog_rack_request_span

docs/GettingStarted.md, lib/ddtrace/correlation.rb, spec/ddtrace/correlation_spec.rb
This pull request makes default setup for correlation logging with slightly simpler and adds an example for use with Rails to the documentation.
=> Easier Rails log correlation

lib/ddtrace/contrib/mongodb/subscribers.rb, spec/ddtrace/contrib/mongodb/client_spec.rb
Per #674, this pull request adds some additional safety around get/set/delete operations in the Mongo integration. Prior to this, if `completed` or `failed` events were sent before `started`, a `NoMethodError for nil` would be raised.
=> Fix Mongo NoMethodError when thread variable not set

lib/ddtrace/contrib/shoryuken/tracer.rb, spec/ddtrace/contrib/shoryuken/tracer_spec.rb
Currently all jobs are grouped within the same job wrapper, `ActiveJob::QueueAdapters::ShoryukenAdapter::JobWrapper`
With this proposal, the resource changes from:
to
=> Shoryuken: use job name as resource instead of the wrapper

docs/GettingStarted.md
Quick update to the documentation, which outlines the use of `event_sample_rate` for some integrations.
=> Added: event_sample_rate to documentation for some integrations.

Appraisals, ddtrace.gemspec
With the release of sqlite3 1.4.0, ActiveRecord fails to load sqlite as an adapter to run tests. This is because ActiveRecord has some hard checks against adapter gems, so occasionally releases like this will break most Rails user's builds. See [this issue](https://github.com/rails/rails/issues/35161) for more details.
While they fix the problem in Rails, this affixes the version number of sqlite3 to prevent conflict with the various versions of Rails we test with.
=> Fix sqlite3 1.4.0 from breaking build with ActiveRecord.

docs/GettingStarted.md
To expand on instructions for setting up trace correlation with logs, this pull request explains how to setup trace correlation in logs for Lograge, the recommended means of formatting and tagging logs in Rails applications. This should make it easier for users to setup log correlation in their applications.
=> Add Lograge correlation setup instructions

lib/ddtrace/pin.rb, spec/ddtrace/pin_spec.rb, spec/support/log_helpers.rb
In order to refactor some older integrations from Pin-based configuration to configuration objects, we need to deprecate the use of Pins in specific integrations as they migrate away.
This pull request introduces a `Datadog::DeprecatedPin` which can be mixed into an existing `Datadog::Pin`, to append warnings when it's accessed. Typically, integrations that use pins will mix in this module to add deprecation warnings, then override any behavior on their copy of the Pin to update their configuration where appropriate.
By implementing this, we can ease the transition to new configuration by notifying users of the change in behavior, while providing backwards compatibility for older configurations.
=> Add Datadog::DeprecatedPin for phasing out Datadog::Pin usage

lib/ddtrace/contrib/dalli/instrumentation.rb, lib/ddtrace/contrib/dalli/patcher.rb, spec/ddtrace/contrib/dalli/instrumentation_spec.rb, spec/ddtrace/contrib/dalli/patcher_spec.rb
Depends on https://github.com/DataDog/dd-trace-rb/pull/692
Dalli still uses `Datadog::Pin` to drive configuration. Users are likely using `Dalli.datadog_pin.service_name = 'my_service'` to set things which is something we definitely do not want to do.
This pull requests changes the integration to use the configuration API, and deprecates the use of `#datadog_pin` as a means to drive configuration, and now raises warnings when it is accessed this way. Instead, when the pin is accessed and configured, it will apply the appropriate configuration via the configuration API.
Changes here should be backwards compatible; any users using old means should receive a warning to upgrade while still preserving existing functionality.
=> Deprecate Dalli pin in favor of configuration API

lib/ddtrace/contrib/faraday/middleware.rb, lib/ddtrace/contrib/faraday/patcher.rb, spec/ddtrace/contrib/faraday/middleware_spec.rb, spec/ddtrace/contrib/faraday/patcher_spec.rb
Faraday still uses `Datadog::Pin` to drive configuration.
This pull requests changes the integration to use the configuration API, and deprecates the use of `#datadog_pin` as a means to drive configuration, and now raises warnings when it is accessed this way. Instead, when the pin is accessed and configured, it will apply the appropriate configuration via the configuration API.
Changes here should be backwards compatible; any users using old means should receive a warning to upgrade while still preserving existing functionality.
=> Deprecate Faraday pin in favor of configuration API

docs/GettingStarted.md, lib/ddtrace/contrib/grape/configuration/settings.rb, lib/ddtrace/contrib/grape/endpoint.rb, lib/ddtrace/contrib/grape/instrumentation.rb, lib/ddtrace/contrib/grape/patcher.rb, test/contrib/grape/app.rb, test/contrib/grape/rack_app.rb
Grape still uses `Datadog::Pin` to drive configuration.
This pull requests changes the integration to use the configuration API, and deprecates the use of `#datadog_pin` as a means to drive configuration, and now raises warnings when it is accessed this way. Instead, when the pin is accessed and configured, it will apply the appropriate configuration via the configuration API.
Changes here should be backwards compatible; any users using old means should receive a warning to upgrade while still preserving existing functionality.
=> Deprecate Grape pin in favor of configuration API

lib/ddtrace/contrib/grpc/datadog_interceptor.rb, lib/ddtrace/contrib/grpc/datadog_interceptor/client.rb, lib/ddtrace/contrib/grpc/datadog_interceptor/server.rb, lib/ddtrace/contrib/grpc/patcher.rb, spec/ddtrace/contrib/grpc/datadog_interceptor/client_spec.rb, spec/ddtrace/contrib/grpc/datadog_interceptor/server_spec.rb, spec/ddtrace/contrib/grpc/integration_spec.rb, spec/ddtrace/contrib/grpc/interception_context_spec.rb, spec/ddtrace/contrib/grpc/patcher_spec.rb
GRPC uses `Datadog::Pin` to drive configuration, for global settings and individual interceptors.
This pull requests changes the integration to use the configuration API instead of the global pin, and deprecates the use of `GRPC.datadog_pin` as a means to drive configuration, and now raises warnings when it is accessed this way. Instead, when the pin is accessed and configured, it will apply the appropriate configuration via the configuration API.
It will still continue to use `Datadog::Pin` objects when trace settings are configured for an individual interceptor, so this part of the API will remain the same.
Changes here should be backwards compatible; any users using the global pin directly should receive a warning to upgrade while still preserving existing functionality. Users who use …
=> Deprecate GRPC global pin in favor of configuration API

lib/ddtrace/contrib/http/instrumentation.rb, lib/ddtrace/contrib/http/patcher.rb
The HTTP integration is using a `class_eval` to rewrite methods which can cause conflicts. This pull request converts the instrumentation into a module that is prepended instead.
=> Refactor HTTP to use instrumentation module

lib/ddtrace/context.rb, lib/ddtrace/ext/distributed.rb, lib/ddtrace/opentracer/distributed_headers.rb, lib/ddtrace/opentracer/text_map_propagator.rb, lib/ddtrace/propagation/distributed_headers.rb, lib/ddtrace/propagation/grpc_propagator.rb, lib/ddtrace/propagation/http_propagator.rb, spec/ddtrace/context_spec.rb, spec/ddtrace/contrib/rack/distributed_spec.rb, spec/ddtrace/contrib/sinatra/tracer_spec.rb, spec/ddtrace/integration_spec.rb, spec/ddtrace/opentracer/propagation_integration_spec.rb, spec/ddtrace/opentracer/rack_propagator_spec.rb, spec/ddtrace/opentracer/text_map_propagator_spec.rb, spec/ddtrace/propagation/distributed_headers_spec.rb, spec/ddtrace/propagation/grpc_propagator_spec.rb, spec/ddtrace/propagation/http_propagator_spec.rb, spec/ddtrace/tracer_integration_spec.rb, test/context_test.rb, test/propagation/distributed_headers_test.rb
This PR adds support for extracting, injecting, and propagating `X-Datadog-Origin` headers as a part of distributed tracing.
- `X-Datadog-Origin` header will be parsed and attached to the context as `context.origin`.
- `X-Datadog-Origin` header will be appended to any distributed tracing request from a context with `context.origin` set.
- `_dd.origin` tag will be set on the root trace of the context set to the value from `context.origin`.
=> [core] Propagate synthetics origin headers

lib/ddtrace/contrib/mongodb/instrumentation.rb, lib/ddtrace/contrib/mongodb/patcher.rb
The MongoDB integration is using a `class_eval` to rewrite methods which can cause conflicts. This pull request converts the instrumentation into a module that is prepended instead.
=> Refactor MongoDB to use instrumentation module

Rakefile, docs/GettingStarted.md, lib/ddtrace/contrib/excon/configuration/settings.rb, lib/ddtrace/contrib/faraday/configuration/settings.rb, lib/ddtrace/contrib/http/configuration/settings.rb, lib/ddtrace/contrib/rack/configuration/settings.rb, lib/ddtrace/contrib/rails/configuration/settings.rb, lib/ddtrace/contrib/rest_client/configuration/settings.rb, lib/ddtrace/contrib/sinatra/configuration/settings.rb, spec/ddtrace/contrib/excon/instrumentation_spec.rb, spec/ddtrace/contrib/faraday/middleware_spec.rb, spec/ddtrace/contrib/http/request_spec.rb, spec/ddtrace/contrib/rack/distributed_spec.rb, spec/ddtrace/contrib/rest_client/request_patch_spec.rb, spec/ddtrace/contrib/sinatra/tracer_spec.rb
This PR updates all integrations which allow enabling distributed tracing to have it enabled by default.
=> Enable distributed tracing by default

spec/ddtrace/contrib/rest_client/request_patch_spec.rb
This pull request fixes the a RestClient test that doesn't reset configuration, causing tests to sometimes break depending which order they run in.
=> Fix RestClient test not resetting

lib/ddtrace/propagation/distributed_headers.rb, test/propagation/distributed_headers_test.rb
When testing the new synthetics integration we noticed that sending `X-Datadog-Parent-Id: 0` causes us to ignore all distributed tracing headers.
=> [core] Only require trace id for distributed tracing headers

lib/ddtrace/contrib/rack/middlewares.rb, spec/ddtrace/contrib/rack/distributed_spec.rb
If a Rack application was on the receiving end of a distributed trace (e.g. 2nd service in chain), and it had enabled `request_queuing`, then the `http_server.queue` span did not receive the distributed trace ID and parent ID because it was processed before distributed tracing was. The span would instead end up in its own trace.
This pull request moves the distributed tracing operation to the top, so `http_server.queue` spans end up with the correct distributed tracing metadata, and are included into the trace.
=> Fix Rack http_server.queue spans missing from distributed traces

CHANGELOG.md, lib/ddtrace/version.rb
Release notes: https://github.com/DataDog/dd-trace-rb/releases/tag/v0.20.0
Git diff: https://github.com/DataDog/dd-trace-rb/compare/v0.19.1...v0.20.0
This release will log deprecation warnings for any usage of `Datadog::Pin`.
These changes are backwards compatible, but all integration configuration should be moved away from `Pin` and to the configuration API instead.
- Propagate synthetics origin header (#699)
- Enable distributed tracing by default (#701)
- Fix Rack http_server.queue spans missing from distributed traces (#709)
- Refactor MongoDB to use instrumentation module (#704)
- Refactor HTTP to use instrumentation module (#703)
- Deprecate GRPC global pin in favor of configuration API (#702)
- Deprecate Grape pin in favor of configuration API (#700)
- Deprecate Faraday pin in …
=> Bump to version 0.20.0

spec/ddtrace/contrib/delayed_job/plugin_spec.rb, spec/ddtrace/contrib/racecar/patcher_spec.rb, spec/ddtrace/contrib/rack/configuration_spec.rb, spec/ddtrace/contrib/rake/instrumentation_spec.rb, spec/ddtrace/contrib/resque/instrumentation_spec.rb, spec/ddtrace/contrib/shoryuken/tracer_spec.rb
Some of our tests leave global state after they complete in the form of configuration. This lingering configuration can break some other tests, and was breaking analytics tag tests when run in a particular order after other tests.
This pull request performs resets "around" examples, so as to make sure they begin with clean state, and do not leave global configuration state after they complete.
=> Fix analytics tag specs breaking when global state lingers

lib/ddtrace/configuration.rb, lib/ddtrace/contrib/analytics.rb, spec/ddtrace/contrib/analytics_examples.rb, spec/ddtrace/contrib/rack/configuration_spec.rb, spec/ddtrace/contrib/rails/analytics_spec.rb, spec/ddtrace/contrib/sinatra/tracer_spec.rb
This pull request adds the `Datadog.configuration.analytics_enabled` setting and `DD_TRACE_ANALYTICS_ENABLED` environment variable to globally enable and disable trace analytics.
If `true`, only integrations that aren't explicitly configured to `false` will activate analytics. If `false`, only integrations that have been explicitly configured with `true` will activate analytics. If unset (left as `nil`), only integrations that have been explicitly configured with `true` will activate analytics.
Basically this means the global flag can be used to turn on certain integrations which default as `nil` (e.g. Rack, Racecar, etc), but will not activate others (such as Excon, Sequel, etc.) Those other integrations will require explicit configuration to activate analytics. By default, all analytics …
=> Add analytics global flag

lib/ddtrace/contrib/http/instrumentation.rb, spec/ddtrace/contrib/http/request_spec.rb
To aid customization of HTTP instrumentation, this pull request adds a configurable hook which can be defined and invoked after each HTTP request.
In practice, one can add the following anywhere to their Datadog configuration:
```ruby
Datadog::Contrib::HTTP::Instrumentation.after_request do |span, request, response|
case response.code.to_i
when 400...599
if response.class.body_permitted? && !response.body.nil?
span.set_error([response.class, response.body[0...4095]])
end
end
end
```
We anticipate this feature will eventually be replaced by span hooks when those are available.
=> Add #after_request hook to HTTP integration

lib/ddtrace/tracer.rb, test/logger_test.rb
Addressing https://github.com/DataDog/dd-trace-rb/issues/681  , a custom logger's log level can be unintentionally changed by Tracer configuration, which I was able to recreate locally.
- Per suggestion this PR adds a check in `self.debug_logging` assignment for whether the custom logger is an instance of the `Datadog::Logger` class and is a noop if debug logging is not enabled
- Adds a unit test in `test/logger_test.rb` for new behavior.
- While I was in there I noticed the logger unit tests could be isolated a bit more, as failed assertions would cause some of the teardown code at the end of each unit test to not get called.  Following some of the conventions used in other tests, this PR also adds setup and teardown helpers for `logger_test.rb`.
Thanks for taking a look! Happy to …
=> Fix custom log level manipulation and isolate logger unit tests

lib/ddtrace/contrib/http/instrumentation.rb, spec/ddtrace/contrib/http/request_spec.rb
Following on the #after_request hook introduced in #716, this PR changes the signature slightly, to add `http` as an argument, and the invocation from `instance_exec` to `call`.
An `after_request` span hook would now look like this:
```
Datadog::Contrib::HTTP::Instrumentation.after_request do |span, http, request, response|
case response.code.to_i
when 400...599
if response.class.body_permitted? && !response.body.nil?
span.set_error([response.class, response.body[0...4095]])
end
end
end
```
Where:
- `span` is a `Datadog::Span` after an HTTP request, and being fully annotated.
- `http` is a `Net::HTTP` object which performed the request.
- `request` is the corresponding `Net::HTTP` request object. (e.g. `Net::HTTP::Get`)
- `response` is the corresponding `Net::HTTP` response object. (e.g. …
=> Change HTTP #after_request span hook scope

lib/ddtrace/analytics.rb, lib/ddtrace/contrib/analytics.rb, lib/ddtrace/contrib/extensions.rb, lib/ddtrace/ext/analytics.rb, lib/ddtrace/span.rb, spec/ddtrace/analytics_spec.rb, spec/ddtrace/configuration_spec.rb, spec/ddtrace/span_spec.rb
This pull request refactors Analytics a bit, and adds support for `set_tag(Datadog::Ext::Analytics::TAG_ENABLED, true)` to set the analytics metric to `1.0` as a shortcut.
=> Implement set_tag shortcut for Analytics

lib/ddtrace/contrib/patchable.rb, spec/ddtrace/contrib/patchable_spec.rb
Addresses https://github.com/DataDog/dd-trace-rb/issues/457 . If an integration fails to get patched due to an incompatibility (generally a version issue) there is no indication of this and the tracing will just fail silently.  
- Per discussion of remediation options in the open issue, this PR adds a conditional `WARN` log on the `patch` method if the integration is incompatible. I used `class.name` here to refer to the integration but if there is a more appropriate way to do so please let me know.
- Also updates `patchable_spec.rb` to reflect new logging behavior using the conventions seen elsewhere in the spec.
Thanks for taking a look! Let me know if there's any feedback, happy to address anything or open to ideas if there's a better way to approach this!
=> Add warning log if an integration is incompatible

Appraisals, docker-compose.yml, spec/ddtrace/tracer_spec.rb
As reported in https://github.com/rmosolgo/graphql-ruby/issues/2235, GraphQL 1.9.4 introduced a safe navigation operator which is incompatible with Ruby 2.2.
This pull request fixes the version for GraphQL to < 1.9.4 for Ruby 2.2.
=> Fix GraphQL 1.9.4 breaking Ruby 2.2 build

Appraisals, lib/ddtrace/contrib/mongodb/instrumentation.rb, lib/ddtrace/contrib/mongodb/patcher.rb, spec/ddtrace/contrib/mongodb/client_spec.rb
Fixes: https://github.com/DataDog/dd-trace-rb/issues/729
In order to preserve backwards compatibility with older gem `mongo <= 2.4` clients and support the new `mongo > 2.4` clients we do the following:
* We pin the `Mongo::Address` class under any circumstance, so if client connections are re-created after the fork while using `mongo > 2.4` client version, those remain pined. See [here](https://docs.mongodb.com/ruby-driver/master/tutorials/ruby-driver-create-client/#usage-with-forking-servers) for further details on the MongoDB client connection issues under forking webservers.
* if the object that is being patched (`base`) is `Mongo::Client` class, then we patch it too. This is what keeps backwards compatibility with older clients.
=> Pin the Mongo::Address class to support MongoDB Ruby client version > 2.4

lib/ddtrace/opentracer/span.rb, spec/ddtrace/opentracer/span_spec.rb
Opentracing supports setting a tag `error` as a boolean. We were not doing anything with this tag, this code updates the opentracing span `set_tag` to look for `error` and translate that into setting the `datadog_span.status` property.
We also continue to set the tag as they requested, since that is what they'd expect.
=> [opentracing] Mark datadog_span.status = 1 when set_tag('error', true)

lib/ddtrace/contrib/rake/instrumentation.rb, spec/ddtrace/contrib/rake/instrumentation_spec.rb
The [Rake instrumentation](https://github.com/DataDog/dd-trace-rb/blob/v0.22.0/lib/ddtrace/contrib/rake/instrumentation.rb#L26-L35) causes the results of `#invoke` and `#execute` to be swallowed. This means, when calling one Rake task from another Rake task, the former will now always return `nil`. For example, given the following rake tasks:
```ruby
namespace :some do
task :task do
raise 'I am sad.' unless Rake::Task['some:other_task'].execute == 'I am happy!'
puts 'Yaaay!'
end
task :other_task do
'I am happy!'
end
end
```
Running `rake some:task` will fail with the "I am sad." message.
There are some instances, where it is helpful to run certain Rake tasks within others. For example, running ActiveRecord's built-in `db` tasks as part of a larger purpose-built task that sets up an …
=> Use original return values for rake methods

lib/ddtrace/sync_writer.rb, spec/ddtrace/sync_writer_spec.rb
Users using 0.22.0+ and `SyncWriter` might see `undefined method 'runtime_metrics' for #<Datadog::SyncWriter:0x0000000004dfa2b0>`. When runtime metrics was introduced with 0.22.0, it overlooked use of `SyncWriter`.
This pull request prevents this `NoMethodError` and permits normal operation of tracing. It however, does not add support for runtime metrics with `SyncWriter`, something that will be evaluated in the future.
=> Fix SyncWriter raising NoMethodError for #runtime_metrics

lib/ddtrace/contrib/aws/integration.rb
See https://github.com/DataDog/dd-trace-rb/issues/707
This PR introduces @alksl's workaround from the issue above to detect both monolithic and modular versions of the aws-sdk* gem family. This is important as AWS themselves encourage the more modular approach going forward.
Versions between the "monolithic" and "modular" gems are kept consistent (see [aws-sdk-core](https://rubygems.org/gems/aws-sdk-core/versions/) and [aws-sdk](https://rubygems.org/gems/aws-sdk/versions/)) so there shouldn't be any problems with collision.
=> Detect aws-sdk-core as well as the monolithic aws-sdk gem

lib/ddtrace/contrib/rails/utils.rb
`parent_name` will be renamed `module_parent_name` in Rails 6.1, so it displays deprecation warnings on Rails 6.0.
refs: https://github.com/rails/rails/pull/34051
=> :warning: Avoid deprecation warnings on Rails 6

CONTRIBUTING.md, README.md, docs/DevelopmentGuide.md, docs/GettingStarted.md
We'd like to make it easier for our contributors to make contributions, by giving them some guidelines and resources that add clarity to the process.
This pull request adds two documents:
1. `CONTRIBUTING.md` which describes the process and criteria for submitting contributions.
2. `DevelopmentGuide.md` which describes how-to topics such as writing/running tests, adding new integrations etc...
=> Add contribution and development guide

lib/ddtrace/contrib/configuration/settings.rb
When configuring Datadog with OpenTracing, typically the `Datadog.tracer` gets swapped for the OpenTracing instance of `Datadog::Tracer`.
Given the original code for defining a `tracer` option for integrations, it was initializing its own reference to `Datadog::Tracer` at load time, instead of at run time. This means when OpenTracing was configured, the integrations were using the old instance created at load time, and a 2nd tracer was being used just for OpenTracing. This could manifest some strange behavior, and cause the Datadog tracer to appear misconfigured.
The interim solution is to lazy initialize `tracer` for integrations. It's only a short term fix though, given if you reassign the Datadog global tracer after configuring the integrations, you'll end up with the same issue. Thus …
=> Fix integration tracers initializing too early

lib/ddtrace/configuration/settings.rb, lib/ddtrace/ext/net.rb, lib/ddtrace/runtime/socket.rb, lib/ddtrace/sync_writer.rb, lib/ddtrace/writer.rb, spec/ddtrace/runtime/socket_spec.rb, spec/ddtrace/sync_writer_spec.rb, spec/ddtrace/writer_spec.rb
This pull request adds functionality for reporting the hostname as a tag on the root span of each trace.
It can be enabled by setting `DD_TRACE_REPORT_HOSTNAME=true` or `Datadog.configuration.report_hostname = true`. It is disabled by default.
=> Add hostname reporting

.circleci/config.yml, .circleci/images/primary/Dockerfile-1.9.3, .circleci/images/primary/Dockerfile-2.0.0, .circleci/images/primary/Dockerfile-2.1.10, .circleci/images/primary/Dockerfile-2.2.10, .circleci/images/primary/Dockerfile-2.3.8, .circleci/images/primary/Dockerfile-2.4.6, docker-compose.yml
Bundler is incorrectly resolving the correct versions of gems to be compatible with the version of Ruby it is trying to install them for. This results in failed builds, claiming a gem version requires a particular version of Ruby, even though an older version of the same gem would support the current version of Ruby.
This became an issue with https://github.com/DataDog/dd-trace-rb/pull/762 when it started resolving gem dependencies incorrectly.
For this PR to work, we will need to update the Docker images on Docker Hub accordingly. (Blocked on that change.)
=> Update CI to use Bundler 1.17.3

lib/ddtrace/ext/forced_tracing.rb, lib/ddtrace/ext/manual_tracing.rb, lib/ddtrace/forced_tracing.rb, spec/ddtrace/span_spec.rb
This PR renames `Datadog::Ext::ForcedTracing` to `Datadog::Ext::ManualTracing`.
As well, we noticed that we had `TAG_KEEP = 'manual.drop'` and `TAG_DROP = 'manual.keep'`, so that is fixed as well.
=> [core] Rename Ext::ForcedTracing to Ext::ManualTracing

docs/GettingStarted.md
Had a user reach out in the community channel, confused about where the span comes from in the example code. 
Hopefully this clarifies that you'd grab it from the current context.
=> Add example of where current span comes from

lib/ddtrace/contrib/http/instrumentation.rb, spec/ddtrace/contrib/http/request_spec.rb
We were using `req.add_field` for adding distributed tracing headers for `net/http` requests.
This was a problem for a customer using `rest-client` as `rest-client` was injecting it's own headers and then `net/http` would append it's own values resulting in multiple values for distributed tracing headers.
=> [net/http] Use HTTPPropagator.inject! instead of req.add_field

docs/GettingStarted.md, lib/ddtrace/ext/metrics.rb, lib/ddtrace/ext/runtime.rb, lib/ddtrace/metrics.rb, lib/ddtrace/runtime/metrics.rb, spec/ddtrace/contrib/rack/configuration_spec.rb, spec/ddtrace/runtime/metrics_spec.rb, spec/ddtrace/tracer_integration_spec.rb, test/tracer_test.rb
We no longer need to tag runtime metrics with `runtime-id` tag.
This PR removes all references of `runtime-id`.
=> [core] Remove runtime-id tag

docs/GettingStarted.md, lib/ddtrace/transport/http.rb, lib/ddtrace/transport/http/adapters/unix_socket.rb, spec/ddtrace/transport/http/adapters/unix_socket_integration_spec.rb, spec/ddtrace/transport/http/adapters/unix_socket_spec.rb
As an extension to the new HTTP transport introduced in https://github.com/DataDog/dd-trace-rb/pull/628, this pull request adds Unix socket adapter support for the transport layer that sends trace data from the library to the agent.
```ruby
c.tracer transport_options: proc { |t|
t.adapter :unix, '/tmp/ddagent/trace.sock'
}
end
```
As it is dependent on changes from #628, we should wait for that to be merged to `0.25-dev` before merging this pull request.
=> Add Unix socket transport adapter

docs/GettingStarted.md, lib/ddtrace/configuration.rb, spec/ddtrace/configuration/settings_spec.rb, spec/ddtrace/configuration_spec.rb, spec/ddtrace/contrib/dalli/patcher_spec.rb, spec/ddtrace/contrib/faraday/patcher_spec.rb, spec/ddtrace/contrib/grpc/patcher_spec.rb
As a first step to dropping support for Ruby 1.9, this pull request adds a deprecation warning that fires only once when users invoke `Datadog.configure`.
The plan is to:
- 0.25.0: Deprecate and warn of use of Ruby 1.9
- 0.26.0: Last version to support Ruby 1.9. Will only backport and release critical bugfixes via `0.26-stable` maintenance branch.
- 0.27.0: Drop Ruby 1.9 support. Bump Ruby version requirement in gempsec to 2.0.
=> Deprecate support for Ruby 1.9

docs/GettingStarted.md
This is my audit to make sure that everything that exists currently in https://docs.datadoghq.com/tracing/setup/ruby/ is added here. Also did some small grammar and style updates to make sure this doc reflects well into the documentation site. 
Staging link: https://docs-staging.datadoghq.com/gus/ruby-doc/tracing/setup/ruby/, created in [this PR](https://github.com/DataDog/documentation/pull/4882).
The staging link reflects what is currently in this file and will update once this PR is merged in.
=> [documentation] Ruby documentation audit

lib/ddtrace/contrib/redis/quantize.rb, spec/ddtrace/contrib/redis/method_replaced_spec.rb, spec/ddtrace/contrib/redis/miniapp_spec.rb, spec/ddtrace/contrib/redis/redis_spec.rb
The Redis integration is not properly quantizing `AUTH` commands. This pull request applies quantization for `AUTH` commands.
=> Quantize Redis AUTH command

lib/ddtrace/ext/transport.rb, lib/ddtrace/runtime/cgroup.rb, lib/ddtrace/runtime/container.rb, lib/ddtrace/transport/http.rb, spec/ddtrace/runtime/cgroup_spec.rb, spec/ddtrace/runtime/container_spec.rb, spec/ddtrace/transport/http/adapters/net_integration_spec.rb, spec/ddtrace/transport/http/adapters/unix_socket_integration_spec.rb, spec/ddtrace/transport/http_spec.rb, spec/spec_helper.rb, spec/support/container_helpers.rb
To make it easier to correlate traces with infrastructure, this pull request adds container info tags to traces, if available.
TODO:
=> Add container tags to traces

lib/ddtrace/ext/metrics.rb, lib/ddtrace/metrics.rb, spec/ddtrace/metrics_spec.rb
This pull request moves some constants for `Datadog::Metrics` to the `Ext::Metrics` module, and fills in some missing unit tests for `Datadog::Metrics`.
=> Refactor Datadog::Metrics constants

lib/ddtrace/contrib/redis/quantize.rb, spec/ddtrace/contrib/redis/quantize_spec.rb, spec/ddtrace/contrib/redis/redis_spec.rb
Fixes #796
Add support for calling `redis#call` with arguments wrapped inside an array:
```ruby
require 'redis'
redis = Redis.new
redis.call([:cmd, 'arg1', ...])
```
This is a [supported call convention by `redis-rb`](https://github.com/redis/redis-rb/blob/v4.1.2/lib/redis/connection/command_helper.rb#L11-L16).
=> Support for Redis array arguments

docs/GettingStarted.md
`trace_id` and `span_id` are 63-bit unsigned integers.
When transporting these values in a `lograge` configuration hash, it is possible that this has will be converted into a JSON object, which might cause loss of precision when parsing these large integers.
This PR adds instructions to the `GettingStarted.md` guide on how to avoid this issue.
=> [Docs] Update lograge configuration to ensure full ID precision

lib/ddtrace/contrib/faraday/middleware.rb
Name span resource via method, similar to the service_name method.
=> Move span resource name to method

lib/ddtrace/contrib/dalli/instrumentation.rb, spec/ddtrace/contrib/dalli/instrumentation_spec.rb
This pull request adds multiplexing to Dalli instrumentation. Users can define configuration using the hostname port combo of the server to apply specific instrumentation settings:
```ruby
c.use :dalli, describes: 'localhost:1234', service_name: 'local-cache'
end
```
Then any Dalli client that sends to this hostname/port combo will have the trace settings applied, in this case commands sent to `'localhost:1234'` will be tagged as the `local-cache` service. Commands that don't match this exactly will use default settings instead.
=> Dalli multiplexing

spec/ddtrace/contrib/ethon/easy_patch_spec.rb, spec/ddtrace/contrib/ethon/shared_examples.rb, spec/ddtrace/contrib/ethon/typhoeus_integration_spec.rb, spec/ddtrace/contrib/excon/instrumentation_spec.rb, spec/ddtrace/contrib/faraday/middleware_spec.rb, spec/ddtrace/contrib/racecar/patcher_spec.rb, spec/ddtrace/contrib/rails/middleware_spec.rb, spec/ddtrace/contrib/resque/instrumentation_spec.rb, spec/ddtrace/contrib/rest_client/request_patch_spec.rb, spec/ddtrace/contrib/sinatra/tracer_spec.rb, spec/spec_helper.rb, spec/support/span_helpers.rb
Encapsulates error checking for `Span` instances:
```ruby
expect(span).to have_error
expect(span).to have_error_type('Error 500')
expect(span).to have_error_message('Boom!')
```
The matchers also work when negated:
```ruby
expect(span).to_not have_error
expect(span).to_not have_error_type
expect(span).to_not have_error_message
```
=> RSpec matcher for Span error checking

Appraisals, Rakefile, ddtrace.gemspec, docs/DevelopmentGuide.md, lib/ddtrace/contrib/dalli/instrumentation.rb, lib/ddtrace/contrib/ethon/integration.rb, lib/ddtrace/contrib/grape/instrumentation.rb, lib/ddtrace/contrib/grpc/integration.rb, lib/ddtrace/contrib/http/instrumentation.rb, lib/ddtrace/contrib/mysql2/instrumentation.rb, lib/ddtrace/contrib/patchable.rb, lib/ddtrace/contrib/rake/integration.rb, lib/ddtrace/contrib/rest_client/integration.rb, lib/ddtrace/contrib/rest_client/request_patch.rb, lib/ddtrace/contrib/sequel/integration.rb, lib/ddtrace/ext/runtime.rb, lib/ddtrace/span.rb, lib/ddtrace/version.rb, spec/ddtrace/contrib/patchable_spec.rb
I noticed many occurrences of `base.class_eval`, which we primarily used for Ruby 1.X support.
This PR removes all code paths for Ruby 1.X support.
During this cleanup, I noticed it was not exactly easy to track down all occurrences of explicit Ruby version checks, and I had to resort to very broad regular expressions to the results I need.
In order to improve this for the future I extract a constant containing the minimum version of Ruby we support, and this is one part specially I'd like some feedback on:
Not having this shared constant makes future Ruby version deprecation much harder, but I'm not 100% happy with how the final result looks like.
I added that constant to `version.rb`, as that allowed us to use it from our `gemspec`, `rake`, and `Appraisals`. This makes the full …
=> Additional cleanup for Ruby 1.9 support

ddtrace.gemspec, spec/spec_helper.rb, test/helper.rb
Our [test runs](https://circleci.com/gh/DataDog/dd-trace-rb/36787) are filled with interpreter errors from external libraries:
```
gems/grape-1.2.4/lib/grape/api.rb:57: warning: method redefined; discarding old inherited
gems/grape-1.2.4/lib/grape/api.rb:39: warning: previous definition of inherited was here
gems/sequel-5.24.0/lib/sequel/dataset/query.rb:84: warning: statement not reached
gems/webmock-2.3.2/lib/webmock/util/json.rb:27: warning: assigned but unused variable - pos
```
These warnings are not actionable by us, and I don't foresee us making any decisions based on information from these warnings.
This PR suppresses these four types of warnings: `:method_redefined, :not_reached, :unused_var`.
Any new warnings types introduced by Ruby in the future will be displayed.
Notably, I …
=> Ignore interpreter warnings from external libraries

lib/ddtrace/configuration/base.rb, lib/ddtrace/configuration/options.rb, lib/ddtrace/configuration/settings.rb, lib/ddtrace/contrib/configuration/settings.rb, lib/ddtrace/contrib/excon/middleware.rb, lib/ddtrace/contrib/faraday/middleware.rb, spec/ddtrace/configuration/base_spec.rb, spec/ddtrace/configuration/options_spec.rb, spec/ddtrace/configuration/settings_spec.rb, spec/ddtrace/contrib/active_record/tracer_spec.rb, spec/ddtrace/contrib/analytics_examples.rb, spec/ddtrace/contrib/configuration/settings_spec.rb, spec/ddtrace/contrib/http/patcher_spec.rb, spec/ddtrace/contrib/rake/instrumentation_spec.rb, spec/ddtrace/contrib/sequel/configuration_spec.rb, spec/ddtrace/propagation/http_propagator_spec.rb, test/contrib/grape/rack_app.rb, test/contrib/rails/rack_middleware_test.rb, test/contrib/rails/tracer_test.rb
This pull request adds the `#reset!` function to `Datadog::Configuration::Settings` to abstract away the reset procedure. This is because resetting a settings object might involve resetting the options as well as some other state.
=> Add #reset! to configuration settings

lib/ddtrace/configuration/base.rb, lib/ddtrace/configuration/settings.rb, lib/ddtrace/propagation/http_propagator.rb, spec/ddtrace/configuration/base_spec.rb
Based on #808 and #830.
This pull request adds a `settings` helper to configuration objects, allowing them to define sub-groupings of settings:
```ruby
settings :debug do
option :logging, default: false
settings :metrics do
option :enabled, default: false
option :client, default Datadog::Metrics.new
end
end
config.debug.logging = true
config.debug.metrics.enabled = true
```
=> Add configuration #settings option

lib/ddtrace.rb
During development, we load `ddtrace` by through `ddtrace.gemspec`, which in turn eager loads 'ddtrace/version'.
Users load this gem by requiring `lib/ddtrace.rb`.
We need to ensure that any files loaded in our gemspec are also loaded there.
This fixed the following issue:
```
NameError: uninitialized constant Datadog::Span::VERSION
from .../lib/ddtrace/span.rb:246:in `<class:Span>'
```
This issue was introduced in https://github.com/DataDog/dd-trace-rb/pull/819, which is still unreleased.
=> Ensure release loads the same files as  development

.circleci/config.yml
We publish pre-release builds of our CI builds for authors that are part of the @DataDog organization.
This currently causes an issue for external contributors, as our CI pipeline fails while running the `deploy prerelease Gem` step.
This PR skips that step if the commit author does not have enough access to publish a pre-release build.
That CI step will be considered successful by CircleCI, allowing external contributors to have a green ✅ on their PRs.
=> Skip pre-release CI step for external contributors

spec/ddtrace/contrib/mongodb/client_spec.rb
[mongo-ruby-driver](https://github.com/mongodb/mongo-ruby-driver) relased additional sanity checks to client authentication validation [on v2.11.0](https://github.com/mongodb/mongo-ruby-driver/pull/1496/files#diff-9b873200a76992a56a5c5fa0fd7914b2R889-R895).
This PR adds credential information that is now mandatory in our tests using `:plain` authentication.
=> MongoDB: add required credentails for plain auth

lib/ddtrace/tracer.rb, lib/ddtrace/workers.rb, lib/ddtrace/writer.rb, spec/ddtrace/configuration/settings_spec.rb
This pull request moves some default values into constants, and makes the writer configurable from `Datadog.tracer.configure` (in order to change buffer size.)
=> Move buffer size and flush interval defaults into constants

lib/ddtrace/contrib/rack/request_queue.rb, spec/ddtrace/contrib/rack/queue_time_spec.rb
This patch makes the `t=` portion of the X-Request-Start header optional so that the request queuing time can be supported on platforms like Heroku.
=> Rack: Accept generic X-Request-Start header

lib/ddtrace/distributed_tracing/headers/datadog.rb, lib/ddtrace/distributed_tracing/headers/headers.rb, lib/ddtrace/tracer.rb, spec/ddtrace/distributed_tracing/headers/datadog_spec.rb, spec/ddtrace/tracer_integration_spec.rb
The following does not produce a distributed trace with the designated trace ID:
```
curl -H "x-datadog-trace-id: 3238677264721744442" -H "x-datadog-parent-id: 0" -H "x-datadog-sampling-priority: 1" -H "x-datadog-origin: synthetics" localhost:3000
```
When synthetics traces are submitted via HTTP headers, they often are missing `parent_id` or have a value of `0`, which is not a valid span ID, and thus the context's `parent_id` becomes `nil`.
When the tracer encounters `parent_id = nil`, it assumes the context is malformed and ignores its trace ID and parent ID, opting to use the ones generated from the local span instead. Ultimately this causes synthetics traces to go missing, because the trace IDs don't match what's sent by synthetics.
This pull request ensures that the trace ID from …
=> Fix synthetics-derived contexts being ignored

docs/GettingStarted.md
We added support for Redis 4.0 in #305. This pull request corrects the documentation to reflect that support.
=> Update Redis supported versions

lib/ddtrace/workers.rb
Our default buffer size is currently 100, which can overflow with high throughput applications causing traces to drop. Increasing this limit to 1000 will allow more traces to come through before the safety limit drops traces.
=> Increase default buffer size

lib/ddtrace/sampler.rb, lib/ddtrace/tracer.rb, spec/ddtrace/contrib/excon/instrumentation_spec.rb, spec/ddtrace/contrib/rack/distributed_spec.rb, spec/ddtrace/integration_spec.rb, spec/ddtrace/sampler_spec.rb, spec/ddtrace/tracer_spec.rb
The tracer should enable priority sampling by default, but it does not; instead it's only activating priority sampling when `Tracer#configure` was called.
This pull request ensures that priority sampling is enabled by default.
=> Fix priority sampling activation

lib/ddtrace/context.rb, lib/ddtrace/diagnostics/health.rb, lib/ddtrace/ext/diagnostics.rb, lib/ddtrace/sampler.rb, lib/ddtrace/span.rb, spec/ddtrace/context_spec.rb, spec/ddtrace/debug/health_spec.rb, spec/ddtrace/sampler_spec.rb, spec/ddtrace/span_spec.rb, spec/support/health_metric_helpers.rb
To improve visibility into how the tracer performs, this pull request adds additional health metrics to monitor for some kinds of errors and other measurements.
=> Add additional health metrics

lib/ddtrace/sampling/rule_sampler.rb, spec/ddtrace/sampling/rule_sampler_spec.rb
Our initial design had our `RuleSampler` limited to 100 request/sec by default.
We've since changed our decision remove any limits by default.
=> Remove default rate limit from RuleSampler

lib/ddtrace/sampling/rate_limiter.rb, spec/ddtrace/sampling/rate_limiter_spec.rb
We started getting this warning in CI after #854 has been merged:
[`(ddtrace/sampling/rate_limiter.rb:34:in 'initialize') rate is not between 0 and 1, setting limiter to 100% as a fallback`](https://circleci.com/api/v1.1/project/github/DataDog/dd-trace-rb/45561/output/104/0?file=true&allocation-id=5de586008de98c5287eaaac7-0-build%2F6BDF3114).
This happens because our rate limiter implementation class, `TokenBucket`, was performing a ratio validation (number between 0 and 1) instead of a rate/sec validation.
This PR address this issue. `TokenBucket` now supports unlimited mode as well, to allow for graceful handling of all possible values for the `rate` parameter.
=> Fix parameter validation for rate limiter

lib/ddtrace/contrib/action_view/event.rb, lib/ddtrace/contrib/action_view/events.rb, lib/ddtrace/contrib/action_view/events/render_partial.rb, lib/ddtrace/contrib/action_view/events/render_template.rb, lib/ddtrace/contrib/action_view/instrumentation/partial_renderer.rb, lib/ddtrace/contrib/action_view/instrumentation/template_renderer.rb, lib/ddtrace/contrib/action_view/patcher.rb, test/contrib/rails/controller_test.rb, test/contrib/rails/errors_test.rb, test/contrib/rails/rack_middleware_test.rb
Fixes #857 
This PR fixes the retrieval of the `layout` property for the `ActionView` integration.
The approach I took was to use the `ActiveSupport` events that are published during template rendering.
These events have existed for all versions of Rails we support, but only since Rails 4.0 they exist in a useful state.
Before Rails 4.0, we only received one event at the end of the instrumentation, there were no separate "before" and "after" events. This prevent us from properly nesting `render_partial` spans inside their respective `render_template` span.
The reason our test suite did not capture this bug is because we explicitly set the `layout 'application'` in our controller during testing, while most users don't actually set it in their applications. A test case was added to prevent …
=> Fix Rails template layout name

spec/ddtrace/sampling/rule_spec.rb
One of our tests for the rule sampler tests whether everything still works when a rule matcher fails.
That test outputs a log message that wasn't caught properly in the test environment.
This PR addresses that, creating an assertion on calls to `Datadog::Tracer.log` for that test.
=> Address warning on Rule spec

.circleci/config.yml
[CircleCI Orbs](https://circleci.com/docs/2.0/using-orbs/) allow us create parametric `jobs` that can be reused for different versions of Ruby.
In this PR, I'm using [Inline Orbs](https://circleci.com/docs/2.0/orb-author/#example-inline-template), which don't need to be published but can only be used from inside the same `config.yml` file, which is fine for our use case.
It might be easier to review this PR with `Hide whitespace changes` enabled.
=> Use CircleCI Orbs to simplify CI configuration

lib/ddtrace.rb, lib/ddtrace/tracer.rb, lib/ddtrace/writer.rb, spec/ddtrace/contrib/resque/instrumentation_spec.rb, spec/ddtrace/integration_spec.rb
When traced Ruby processes are terminated, they may not permit the worker an opportunity to flush existing traces. This pull request adds an `at_exit` hook that calls `shutdown!` on the Tracer, so it can be cleaned up in a more graceful fashion.
=> Add at_exit hook for Tracer shutdown

lib/ddtrace/writer.rb, spec/ddtrace/contrib/rack/configuration_spec.rb, spec/ddtrace/tracer_integration_spec.rb, test/tracer_test.rb
The trace writer associates spans with runtime metrics so the metrics are assigned to the correct services. However, it was not checking if runtime metrics was enabled, meaning it would accumulate service names regardless of whether runtime metrics was on or off.
This pull request changes the writer behavior to respect the runtime metrics enabled flag when associating with traces.
=> Only associate spans with runtime metrics if enabled

lib/ddtrace/contrib/action_view/events/render_partial.rb, lib/ddtrace/contrib/action_view/events/render_template.rb, lib/ddtrace/contrib/action_view/instrumentation/partial_renderer.rb, lib/ddtrace/contrib/action_view/instrumentation/template_renderer.rb, test/contrib/rails/controller_test.rb, test/contrib/rails/errors_test.rb, test/contrib/rails/rack_middleware_test.rb
Fixes #855
Sets `span.resource` to the template name for `rails.render_template` and `rails.render_partial` spans, if the template name is available.
We were already setting tags for template name and layout, but not span resource name.
In this example you see `posts/index.html.erb` as the resource name:
=> Add resource for Rails template spans

lib/ddtrace/sampling/rule_sampler.rb
Quick update to the doc string for `RuleSampler` constructor, default `rate_limit` is not `nil` (no rate limit) rather than `100`
=> Update RuleSampler rate_limit doc string

Appraisals
The latest version of Rails 5.2, Rails 5.2.4.1, contains a bug when running uner Ruby 2.2: it is using syntax that is only available for Ruby 2.3 and above: https://github.com/rails/rails/commit/92f660b910c64176efd04d3b60af806fefe5827c#diff-0dd82841c763273551965fc0ea292a1bR96
This PR prevents us from installing this patch release of Rails for Ruby 2.2, in order to unblock our CI pipeline.
=> Skip Rails version incompatible with Ruby 2.2

Appraisals
We are currently not requiring the minimum version of `redis` required by [Rails >= 5.2](https://github.com/rails/rails/blob/v5.2.0/activesupport/lib/active_support/cache/redis_cache_store.rb#L8) to use the default `redis_cache_store` implementation.
This allows `bundler` to install `redis ~> 3` in CI sometimes, causing random test breakage.
This dependency is not a transitive requirement for Rails because using `redis` for caching is not mandatory.
=> Set Redis version for Rails >= 5.2 cache

spec/ddtrace/contrib/ethon/integration_context.rb, spec/ddtrace/transport/http/adapters/net_integration_spec.rb, spec/ddtrace/transport/http/adapters/unix_socket_integration_spec.rb
Fixes this flaky test:
```
1) Adapters::UnixSocket integration tests when sending traces through Unix socket client sends traces successfully
Failure/Error: expect(messages).to have(1).items
expected 1 items, got 0
```
This happens because we don't wait until `WEBrick::HTTPServer#start` finishes its internal socket initialization before trying to use it.
Unfortunately, `WEBrick::HTTPServer#start` is a method that never returns. We need to use a special callback parameter, `StartCallback`, to inform us that the server is ready.
=> Wait for WEBrick server start during tests

lib/ddtrace/sync_writer.rb, spec/ddtrace/sync_writer_spec.rb
Our logic in the tracer configuration code assumed a `Writer` always has a `priority_sampler` method, which is not true of the `SyncWriter`. This manifested as an error when `tracer.configure(writer: SyncWriter.new)` was called.
This pull request adds a priority sampler option to the `SyncWriter` which defaults to `nil`, as most applications of the `SyncWriter` would not benefit from priority sampling rates.
=> Fix priority_sampler NoMethodError for SyncWriter

lib/ddtrace/sampling/rule_sampler.rb, spec/ddtrace/sampling/rule_sampler_spec.rb
We want to default to 100 traces per second by default as a safety mechanism for high volume customers.
=> Set default RuleSampler rate_limit of 100

lib/ddtrace/configuration/base.rb, lib/ddtrace/configuration/settings.rb, lib/ddtrace/ext/sampling.rb, lib/ddtrace/sampling/rule_sampler.rb, spec/ddtrace/configuration/settings_spec.rb, spec/ddtrace/sampling/rule_sampler_spec.rb
Adds env vars to configure RuleSampler defaults with:
- `DD_TRACE_SAMPLE_RATE` --> `Datadog.configuration.sampling.default_rate`
- `DD_TRACE_RATE_LIMIT` --> `Datadog.configuration.sampling.rate_limit`
=> Add env vars for RuleSampler

.circleci/config.yml, .circleci/images/primary/Dockerfile-2.7.0, Appraisals, Rakefile, ddtrace.gemspec, docker-compose.yml, docs/GettingStarted.md
Fixes #805 
This PR adds a new branch to our CI pipeline and Rakefile to support testing `ddtrace` with Ruby 2.7.
No incompatibilities have been found with `ddtrace` code.
gRPC is the only gem that does not successfully install with Ruby 2.7, explicitly failing with `grpc requires Ruby version >= 2.3, < 2.7.dev`, so we skip testing it with Ruby 2.7 until an update is released.
=> Support for Ruby 2.7

spec/ddtrace/contrib/faraday/middleware_spec.rb
Faraday is missing a where the library throws an error, like when it can't establish connection to the remote server.
This PR asserts that our instrumentation properly reports all information available about this error.
The tracer already does this correctly, this PR just adds a test to cover such case.
=> Add Faraday test for library errors

lib/ddtrace/context_flush.rb, lib/ddtrace/contrib/action_cable/instrumentation.rb
When the extraction of `Datadog::Tracer.log` to `Datadog::Logger.log` happened in #880, #824 was still in progress.
Given that this changed affected #824 in non-critical error paths that are not common, they were not exercised by CI during brach rebasing.
This PR migrates all remaining reference to log methods in `Datadog::Tracer` to use `Datadog::Logger` instead.
=> Fix remaining usages of Datadog::Tracer.log

lib/ddtrace/contrib/http/instrumentation.rb, spec/ddtrace/contrib/http/request_spec.rb
This PR addresses [Issue-888](https://github.com/DataDog/dd-trace-rb/issues/888) . Currently, when a request raises an exception from a timeout(or otherwise), we don't annotate the span with any of the request or response details, since the `span_annotation!` method is called after the request is made and an exception would get raised. 
This PR splits the `annotate_span!` method into request and response specific annotation methods so that the span can be annotated with at least minimal tags in the case of an exception being raised by the request.
Per the Contribution Guidelines I've also added a test for this use case.
Let me know what you think, happy to make any changes y'all feel would be appropriate here.
=> Update net/http instrumentation span annotation

lib/ddtrace/sync_writer.rb, spec/ddtrace/sync_writer_spec.rb
Fixes #914 
`SyncWriter` was missing the contract method `#stop`, which is implemented by the async writer class `Writer`.
This causes an error to be raised during shutdown:
https://github.com/DataDog/dd-trace-rb/blob/8a9fb5529bc1491de4963542ac95b413b3bacac5/lib/ddtrace/tracer.rb#L53
I verified and no other method is missing from the writer contract for `SyncWriter`
=> Add SyncWriter#stop method

Appraisals
The newly released version of Rack, `2.1.0`, is incompatible with the latest version of Grape: https://github.com/ruby-grape/grape/issues/1966
This PR locks Rack to `< 2.1.0` until Grape updates the issue with further instructions.
This unblocks our CI builds.
=> Lock Rack version due to Grape incompatibility

LICENSE, LICENSE.Apache, LICENSE.BSD3, NOTICE
This PR adds the option to ingest the tracer as BSD3 or Apache 2. See https://github.com/DataDog/dd-trace-rb/issues/893 for discussion.
=> Add Dual License 

lib/ddtrace/configuration/settings.rb, lib/ddtrace/context_provider.rb, spec/ddtrace/context_provider_spec.rb, spec/ddtrace/contrib/action_cable/instrumentation_spec.rb, spec/ddtrace/contrib/rails/analytics_spec.rb, spec/ddtrace/contrib/sinatra/activerecord_spec.rb, spec/ddtrace/integration_spec.rb, spec/support/tracer_helpers.rb
When instantiating multiple `Datadog::Tracer`s, we currently override the thread-local `Context` with the one belonging to the latest instantiated Tracer. This happens because of this line: https://github.com/DataDog/dd-trace-rb/blob/adc046a6e38b22ab59d57868943b5063bbd0a610/lib/ddtrace/tracer.rb#L76
By creating a new `DefaultContextProvider` for each tracer, we override the previous `Context` that was present in `Thread.current[:datadog_context]`.
This PR adds support for multiple concurrent thread-local contexts.
This is done by uniquely "namespacing" the thread-local variable for each `DefaultContextProvider` instance: https://github.com/DataDog/dd-trace-rb/blob/adc046a6e38b22ab59d57868943b5063bbd0a610/lib/ddtrace/context_provider.rb#L35
This allows for the follow code to work as …
=> Improved support for multiple tracer instances

docs/GettingStarted.md, spec/ddtrace/contrib/graphql/test_types.rb, spec/ddtrace/contrib/graphql/tracer_spec.rb
_Fixes [CI failure](https://app.circleci.com/jobs/github/DataDog/dd-trace-rb/52168)_
The GraphQL gem has deprecated [`.define`-style schema definition](https://github.com/rmosolgo/graphql-ruby/blob/80da07a9545af9407c6c5fe112d4489b0e89cbf2/CHANGELOG.md#deprecations-1).
Documentation has been updated to provide configuration examples using a class-based schema definition, while also keeping the original examples as define-style is still supported.
In our test suite, were mixing class-based and .define-style schema definition, which triggered issues with the release of `graphql 1.10`.
This PR expands our CI test fixture by creating the whole schema definition with both versions (class and .define styles).
=> Update class-based GraphQL schema

lib/ddtrace/encoding.rb, lib/ddtrace/transport/io.rb, lib/ddtrace/transport/io/client.rb, lib/ddtrace/transport/io/response.rb, lib/ddtrace/transport/io/traces.rb, lib/ddtrace/transport/parcel.rb, lib/ddtrace/writer.rb, spec/ddtrace/encoding_spec.rb, spec/ddtrace/integration_spec.rb, spec/ddtrace/transport/io/client_spec.rb, spec/ddtrace/transport/io/response_spec.rb, spec/ddtrace/transport/io/traces_spec.rb, spec/ddtrace/transport/io_spec.rb, spec/ddtrace/transport/parcel_spec.rb
To support writing traces to generic outputs such as STDOUT or log files, this pull request introduces the `Datadog::Transport::IO`. This transport which encodes data (default JSON) and writes to a generic output (default STDOUT) is designed to be interchangeable with the existing `Datadog::Transport::HTTP`.
Some caveats; as it does not support two-way communication, it does not provide priority sampler updates and has a limited set of health metrics it can emit.
=> Add Datadog::Transport::IO

spec/ddtrace/metrics_spec.rb
This PR fixes this flaky `metrics_spec.rb` test: https://app.circleci.com/jobs/github/DataDog/dd-trace-rb/52268
The failure happens because a few tests reference `Datadog::Statsd` in their `before` steps without ensuring that it has been loaded:  https://github.com/DataDog/dd-trace-rb/blob/97e8e0d005ce675b1577c473146a3285304668d1/spec/ddtrace/metrics_spec.rb#L166
More often then not, `Datadog::Statsd` gets dynamically loaded by `metrics.rb` https://github.com/DataDog/dd-trace-rb/blob/97e8e0d005ce675b1577c473146a3285304668d1/lib/ddtrace/metrics.rb#L43
and tests run fine, but we shouldn't depend on the side-effects of other tests for a correct test run.
Because I explicitly `require 'datadog/statsd'` in the test file, I've added a new test to ensure that our code that dynamically loads …
=> Ensure Datadog::Statsd is loaded during test

CHANGELOG.md, lib/ddtrace/version.rb
This version bump includes changelog information from patch release [v0.31.1](https://github.com/DataDog/dd-trace-rb/releases/tag/v0.31.1).
=> Bump to version 0.32.0

Appraisals
With the release of Grape 1.3, support for the latest version of Rack has been added, allowing us to test against the latest version of both gems once again.
Unfortunately, the new version of Grape that is compatible with Rack >= 2.1 is [only available for Ruby >= 2.4](https://rubygems.org/gems/grape/versions/1.3.0). This means that we are still locking Rack for Ruby <= 2.3.
=> Unlock Rack where Graph 1.3 is available

ddtrace.gemspec, spec/support/health_metric_helpers.rb, test/helper.rb
I was looking at the warning list for the new version of Ruby and noticed quite a few new deprecations.
This PR suppresses deprecations related to the use of native `rb_tainted_str_new_cstr` and `rb_tainted_str_new` methods, which will be removed in Ruby 3.2, and are not related to our library.
I've left one new warning unsuppressed, `Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call`, as this warning might help us debug interface problems when Ruby 3.0 is released.
I've also fixed one small warning actually caused by our library:
```
health_metric_helpers.rb:11: warning: already initialized constant HealthMetricHelpers::METRICS
health_metric_helpers.rb:11: warning: previous definition of METRICS was here
```
This is the only warning that is …
=> Reduce external warnings for Ruby 2.7

lib/ddtrace/contrib/active_record/configuration/resolver.rb, lib/ddtrace/contrib/active_record/integration.rb, lib/ddtrace/contrib/configurable.rb, lib/ddtrace/contrib/configuration/resolver.rb, spec/ddtrace/contrib/configurable_spec.rb, spec/ddtrace/contrib/configuration/resolver_spec.rb
To support the expansion of "multiplexing" (having multiple configurations per integration) and its applications in #882 and #861/#937, this pull request refactors the `Datadog::Contrib::Configuration::Resolver` and adds an `#add` function to it, to allow for certain use cases to operate more efficiently. See linked issues/PRs for example cases.
This was originally a change introduced in #882 by @stormsilver, but extracted it out as a base for other PRs as well.
=> Add #add to configuration resolver

Appraisals, lib/ddtrace/contrib/sidekiq/tracing.rb, test/contrib/sidekiq/client_tracer_test.rb, test/contrib/sidekiq/server_tracer_test.rb
_Follow up from #798_
Sidekiq provides [Delayed-extensions](https://github.com/mperham/sidekiq/wiki/Delayed-extensions/c03d6d910ebb5dd7984525beac353d26b41c4ad7) to allow for any method call to be made asynchronous.
When tracing jobs scheduled with Delayed-extensions, we receive information about what class and method were invoked as a YAML argument to the job, instead of the default `job['class']` attribute: `job['class']` is always set to `Sidekiq::Extensions::DelayedClass` for delayed jobs.
This PR decodes that YAML and retrieves information about the job invoked, setting it as the trace resource.
We use `YAML.parse` (instead of `YAML.load`) as it only parses the source text into a syntax tree, without loading any native Ruby objects. `YAML.load` can lead to vulnerabilities during …
=> Instrument Sidekiq traces with Delayed Extensions

docs/GettingStarted.md, lib/ddtrace/contrib/redis/configuration/resolver.rb, lib/ddtrace/contrib/redis/integration.rb, lib/ddtrace/contrib/redis/patcher.rb, lib/ddtrace/contrib/redis/vendor/resolver.rb, lib/ddtrace/vendor/redis/connection_specification.rb, spec/ddtrace/contrib/redis/configuration/resolver_spec.rb, spec/ddtrace/contrib/redis/instrumentation_spec.rb
As discussed with @delner in #861 
Adding multiplexing support for redis patcher
It may be interesting to add an instrumentation module as it was done for other contrib integrations. This would allow to clean up a bit the patcher module.
_Disclaimer_: the only doubt that I have about this implementation is that the redis client will resolve the hostname and the mapping on the host won't be done. I will try to test on my side once I will receive a review from your team. 🙏
=> Feature: Redis multiplexing

lib/ddtrace/contrib/aws/patcher.rb
Resolves #938.
There's a scenario when AWS is partially loaded such that certain constants are not available, `const_get` will search ancestors and use any matching constant there, which results in the wrong constant being patched.
Additionally, despite providing a `false` flag to disable ancestor search, `Module#const_get` seems to ignore this sometimes when Rails autoloading is present (at least the first time), causing it to still unexpectedly return the wrong constant.
e.g.
```
module Support
class Client
end
end
module Aws
end
::Aws.const_get(:Support).const_get(:Client)
::Aws.const_get(:Support, false).const_get(:Client, false)
```
In this PR we make sure to cross check the loaded constants against the list, then only collect what's actually available, rather than depending on …
=> Fix AWS patcher loading wrong constants when AWS is partially loaded

docs/GettingStarted.md, lib/ddtrace/contrib/sidekiq/configuration/settings.rb, lib/ddtrace/contrib/sidekiq/ext.rb, lib/ddtrace/contrib/sidekiq/server_tracer.rb, test/contrib/sidekiq/server_tracer_test.rb
Sidekiq job arguments are currently not being logged. I heavily rely on the arguments to see how a job has performed. I guess not many use it, so I wrapped it as an option so the user can turn it on/off.
Here is an example:
=> Log sidekiq job arguments

lib/ddtrace/sampler.rb, lib/ddtrace/sampling/rule_sampler.rb, spec/ddtrace/sampler_spec.rb, spec/ddtrace/sampling/rule_sampler_spec.rb, test/tracer_test.rb
We want to tag the priority sampled spans with the agent's rate limit. This pull request adds that tag.
=> Add _dd.agent_psr tag to PrioritySampler

docs/GettingStarted.md
Hi!
I noticed that your docs had [Elasticsearch](https://www.elastic.co/elasticsearch) spelled incorrectly so I went ahead and fixed it. Elasticsearch is actually a single word and "search" is not capitalized. 
Please let me know if there is anything else you need for this change or if you have any questions! Thanks!
=> Documentation Update: Fix Spelling of Elasticsearch

Rakefile
CI pipeline routinely hangs and times out when running `bundle exec appraisal rails6-mysql2 rake spec:action_cable` tests for Ruby 2.5 and 2.6. e.g. [from a failing CircleCI build](https://circleci.com/gh/DataDog/dd-trace-rb/55560?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
```
bundle exec appraisal rails6-mysql2 rake spec:action_cable
>> BUNDLE_GEMFILE=/app/gemfiles/rails6_mysql2.gemfile bundle exec rake spec:action_cable
/usr/local/bin/ruby -I/usr/local/bundle/gems/rspec-core-3.9.1/lib:/usr/local/bundle/gems/rspec-support-3.9.2/lib /usr/local/bundle/gems/rspec-core-3.9.1/exe/rspec --pattern spec/ddtrace/contrib/action_cable/\*\*/\*_spec.rb
pg gem not found, trying another connector
I, [2020-02-18T18:53:06.652495 #7330]  INFO -- : Testing against …
```
=> Temporarily disable Rails 6 ActionCable tests

docs/GettingStarted.md, lib/ddtrace/contrib/rack/integration.rb, spec/ddtrace/contrib/rack/configuration_spec.rb, spec/ddtrace/contrib/rack/distributed_spec.rb, spec/ddtrace/contrib/rack/integration_spec.rb
When codifying version requirements for integrations via #944, we made Rack requirements fairly strict (1.4.7+)
This pull request relaxes that requirement to 1.1.0+, such that older integrations like Rails 3.0 (which depends on Rack 1.2.8) can still patch Rack properly. I've verified Rack 1.1.0 works with `dd-trace-rb` by running it through our unit tests, just needed to make some small alterations to make test cases compatible.
=> Support for Rack 1.1.0+

ddtrace.gemspec
Encountered while trying to setup instrumentation on host with RubyGems 1.8.23 and Ruby 2.2.0
https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/utils/time.rb#L5
Gem::Version.new with frozen string is going to crash. It was resolved in commit
https://github.com/rubygems/rubygems/commit/da4362a6644ca5a75c210677ac500bccfe75f529#diff-94d386526b8b558035d4e4c7602d647c, so version of RubyGems 2.0.0 and greater is required.
=> Specify minimum rubygems version

lib/ddtrace/sampling/rule_sampler.rb, spec/ddtrace/sampling/rule_sampler_spec.rb
Fixes #949 
Normally, the `RuleSampler` has a default sampler of `RateByServiceSampler` which responds to `#update`. When the `RuleSampler` is configured with a default sample rate, it sets a `RateSampler` as its default sampler, which does not respond to `#update`.
Thus when the transport receives priority sampling rates and attempts to update the sampler, it calls `RuleSampler` with `update` and attempts to forward to `RateSampler` which raises a `NoMethodError`.
In this pull request, we check if the default sampler responds to `#update` before forwarding. If it does not, return `false` instead.
=> Fix RuleSampler forwarding #update to sampler without #update

docs/GettingStarted.md
What does this PR do?
---------------------
Updates the dead link for Net/HTTP(line 48) to match actual working link:
https://docs.datadoghq.com/tracing/setup/ruby/#net-http
Who will it impact?
-------------------
All of the documentation users.
Motivation
----------
I was using the documentation and realized this did  not redirect.
=> Updating dead link when clicking Net/HTTP.

lib/ddtrace/runtime/metrics.rb, spec/ddtrace/runtime/metrics_spec.rb
When runtime metrics are disabled, they won't emit metrics, but it still accumulates service names to tag metrics with. This pull request prevents that accumulation from happening, out of consideration for performance.
=> Fix RuntimeMetrics accumulating service names when disabled

lib/ddtrace/contrib/sidekiq/tracing.rb
Fixes #943 
In Rails ActiveJob via https://github.com/rails/rails/commit/0e64348ccaf513de731f403259ec5b49e7b3f028 they pass `wrapped` as a Class constant instead of a String. When this constant is set as the resource, it's suspected that it cannot be converted via Msgpack and raises an error on serialization.
This pull request makes sure the job resource is always a string.
=> Fix Sidekiq setting non-serializable Class as resource

lib/ddtrace/configuration/option.rb, lib/ddtrace/configuration/option_definition.rb, lib/ddtrace/configuration/options.rb, spec/ddtrace/configuration/option_spec.rb, spec/ddtrace/configuration/options_spec.rb
This pull request introduces a couple of small features to configuration options
- Adds `reset_option` which allows individual options to be reset without resetting the entire configuration.
- Adds the old value to `setter` and `on_set` args so the blocks can use them
e.g. `setter { |value, old_value| ... }`
=> Reset and old values for options

spec/ddtrace/opentracer/tracer_spec.rb
Other libraries (in this case Statsd) are generating warnings which pollutes `stderr` in a way that confuses and breaks expectations for our own warning generations with OpenTracer.
This pull request changes those expectations to be a bit more flexible, so as not to cause CI tests to flake out.
=> Fix warning output expecation

lib/ddtrace/contrib/presto/patcher.rb
In between this branch getting approved and merged I missed the cleanup that happened here in  https://github.com/DataDog/dd-trace-rb/pull/912 , 
This PR removes the remaining reference to Datadog::Tracer.log in favor of Datadog::Logger.log
=> fix reference to old Datadog::Tracer.log

lib/ddtrace/environment.rb
Makes `Datadog::Environment` functions accessible on the module instead of having to compose it into a class.
=> Make Datadog::Environment helpers to be accessible via module

lib/ddtrace/event.rb, spec/ddtrace/event_spec.rb
Extracted from #879 
This pull request adds `Datadog::Event`, which is a very simple pub-sub pattern, similar to `ActiveSupport::Notifications` (which we can't use because of possible conflict with user libraries/dependencies.)
Although not applied to any practical case in this PR, it is intended to be used for `Datadog::Tracer`, to break dependencies/coupling between `Tracer` and `Writer`, among other components to allow their designs to be simplified.
=> Add Datadog::Event

lib/ddtrace/tracer.rb, spec/ddtrace/integration_spec.rb
This PR is a POC to address https://github.com/DataDog/dd-trace-rb/issues/967 . It demonstrates one way to resolve the runtime metrics issue detailed in the referenced open issue, so I'm making it as a draft. If there's interest in getting merged I'd be happy to move it out of drafts and add some tests, but also feel free to close.
=> patch to not drop runtime metrics config when creating new writer

Appraisals, Rakefile, lib/ddtrace/contrib/faraday/patcher.rb, lib/ddtrace/contrib/faraday/rack_builder.rb, spec/ddtrace/contrib/faraday/middleware_spec.rb
Fixes #965 
When we added support for Faraday v1 in https://github.com/DataDog/dd-trace-rb/pull/906, a warning started to be emitted by Faraday versions < 1.0: `WARNING: Unexpected middleware set after the adapter. This won't be supported from Faraday 1.0.`
This did not affect the correct behaviour of instrumentation on Faraday < 1.0.
This PR addresses that warning by patching Faraday < 1.0 using our old approach, the one removed in https://github.com/DataDog/dd-trace-rb/pull/906, instead of the new patching used by v1.0.
The removal of the old approach was originally intended, as the new patching used for 1.0 also works for < 1.0, as stated, but this warning we are seeing is not desirable either.
I've added a new Appraisal category for `contrib` to allow us to test older version: …
=> Address Faraday warnings on v0.x

lib/ddtrace/correlation.rb, lib/ddtrace/ext/environment.rb, lib/ddtrace/metrics.rb, lib/ddtrace/tracer.rb, spec/ddtrace/correlation_spec.rb, spec/ddtrace/metrics_spec.rb, spec/ddtrace/tracer_spec.rb
To make it easier to tag traces with the application environment, this pull request defines `DD_ENV` which users can set, which will automatically:
- Be set as a tag on all traces
- Be set as a tag on all metrics
- Be added as an attribute to `Datadog::Correlation` for logs correlation
=> Add DD_ENV environment variable

Appraisals
A continuation of #894, the 5.2.4.2 Rails release does not include the bugfix for the Ruby 2.2 syntax error. This prevents CI from breaking.
=> Fix CI Actionpack 5.2.4.2 syntax error breaking Ruby 2.2

lib/ddtrace/correlation.rb, lib/ddtrace/environment.rb, lib/ddtrace/ext/environment.rb, lib/ddtrace/metrics.rb, lib/ddtrace/tracer.rb, spec/ddtrace/configuration/settings_spec.rb, spec/ddtrace/correlation_spec.rb, spec/ddtrace/environment_spec.rb, spec/ddtrace/metrics_spec.rb, spec/ddtrace/tracer_spec.rb
This pull request adds `DD_TAGS` as a environment variable which can be used to set default tags on the tracer.
It also does some minor refactoring of `DD_ENV` into `Datadog::Environment` to make things a little cleaner/more consistent, and fixes two bugs:
- Default tags were overriding tags provided via the `:tags` option to `Tracer#start_span`.
- Adding the string and symbol tag name equivalents via `Tracer#set_tags` e.g. `tracer.set_tags(foo: :bar, 'foo' => :baz)` would keep duplicates for each type which would lead to an arbitrary one being used. (Problematic if you aren't consistent when using strings vs symbols.)
=> Add DD_TAGS environment variable

Rakefile, docs/GettingStarted.md, lib/ddtrace.rb, lib/ddtrace/correlation.rb, lib/ddtrace/environment.rb, lib/ddtrace/ext/correlation.rb, lib/ddtrace/ext/environment.rb, lib/ddtrace/metrics.rb, lib/ddtrace/opentelemetry/extensions.rb, lib/ddtrace/opentelemetry/span.rb, spec/ddtrace/correlation_spec.rb, spec/ddtrace/environment_spec.rb, spec/ddtrace/metrics_spec.rb, spec/ddtrace/opentelemetry/span_spec.rb
To make it easier to tag traces with the application version, this pull request defines `DD_VERSION` which users can set, which will automatically:
- Be set as a tag on all traces
- Be set as a tag on all metrics
- Be added as an attribute to Datadog::Correlation for logs correlation
This pull request also:
- Adds conversion of OpenTelemetry's `service.version` tag to `version` accordingly
- Fixes a bug where correlations for spans without context would not tag the environment.
=> Add DD_VERSION environment variable

lib/ddtrace/environment.rb, lib/ddtrace/ext/environment.rb, lib/ddtrace/opentelemetry/span.rb, lib/ddtrace/span.rb, spec/ddtrace/environment_spec.rb, spec/ddtrace/opentelemetry/span_spec.rb, spec/ddtrace/span_spec.rb
To make it easier to tag traces with the application version, this pull request defines `DD_SERVICE` which users can set, which will act as the default service for spans if a service isn't explicitly provided for that span.
Additionally it also adds conversion of OpenTelemetry's `service.name` tag to the `service` attribute on `Datadog::Span`.
In its current implementation, `DD_SERVICE` will only affect manual instrumentation that does not provide a `service`, as most integrations automatically have their own default service name defined. Integration behavior will be adjusted to use this default where appropriate in another pull request.
=> Add DD_SERVICE environment variable

lib/ddtrace/worker.rb, lib/ddtrace/workers/async.rb, lib/ddtrace/workers/loop.rb, lib/ddtrace/workers/polling.rb, lib/ddtrace/workers/queue.rb, spec/ddtrace/worker_spec.rb, spec/ddtrace/workers/async_spec.rb, spec/ddtrace/workers/loop_spec.rb, spec/ddtrace/workers/polling_spec.rb, spec/ddtrace/workers/queue_spec.rb, spec/support/synchronization_helpers.rb
Extracted from #879 
This pull request adds the `Datadog::Worker` base class and its extension modules. It is intended to act as the foundation for background processes that run within the tracing library. Examples of these would be "writing traces to the agent" and "flushing runtime metrics to Statsd".
At its core, there is the `Datadog::Worker` class which itself defines a simple task, and a `perform` function.
Each background process would extend this base class, and define its work behavior within. e.g.
```ruby
class TraceWriter < Datadog::Worker
def perform(traces)
end
end
```
Because each worker might need to behave differently (e.g. polling, queuing, threading etc) these behaviors are provided through modules `Polling`, `Async::Thread`, `IntervalLoop`, `Queue` which can then be …
=> Add Datadog::Worker and extensions

lib/ddtrace/sync_writer.rb, lib/ddtrace/workers.rb, lib/ddtrace/workers/trace_writer.rb, spec/ddtrace/workers/trace_writer_spec.rb
Extracted from #879
This pull request adds the `Datadog::Workers::TraceWriter` and `Datadog::Workers::AsyncTraceWriter` classes, which act as replacements for the `Datadog::Writer` class.
- The `TraceWriter` is the base class for trace writing and defines how traces are written to a transport; it's analogous to `SyncWriter` and replaces it.
- `AsyncTraceWriter` extends `TraceWriter`, decorating it with asynchronous behaviors that allows the same trace writing behavior to execute in its own worker thread on a polling basis. It will replace `Datadog::Writer` and the `AsyncTransport`.
Once in place, the goal is to have these workers act as drop-in replacements for the writer, then eventually phase out/remove the `Writer` and `AsyncTransport` entirely, in a future PR.
=> Add TraceWriter and AsyncTraceWriter workers

lib/ddtrace/workers.rb, lib/ddtrace/workers/runtime_metrics.rb, spec/ddtrace/workers/runtime_metrics_spec.rb
Extracted from #879
This pull request introduces the `Datadog::Workers::RuntimeMetrics` worker, which is responsible for collecting and submitting runtime metrics via Statsd. The pull request effectively extracts this runtime metrics behavior from the `AsyncTransport` which runtime metrics had previously hitchhiked on; it now separates it into its own thread and component, by using the same base as the `AsyncTraceWriter`.
It is the complement to `AsyncTraceWriter` in the respect that the combination of the two replace the responsibilities of `Datadog::Writer`; we will use this component when we also transition to the new `TraceWriter` by default.
=> Add runtime metrics worker

lib/ddtrace/contrib/rails/framework.rb, spec/ddtrace/contrib/rails/defaults_spec.rb
Introduced via #990, the Rails integration was auto-setting `env` to the Rails env as a default when no setting was provided. This had the unintended consequence of overriding `env` tags set explicitly through other means, and configuration at the agent level. This pull request reverts this behavior, leaving the `env` untouched.
=> Revert Rails default env

docs/DevelopmentGuide.md, docs/GettingStarted.md, lib/ddtrace/buffer.rb, lib/ddtrace/configuration.rb, lib/ddtrace/configuration/components.rb, lib/ddtrace/configuration/settings.rb, lib/ddtrace/context.rb, lib/ddtrace/contrib/analytics.rb, lib/ddtrace/contrib/patcher.rb, lib/ddtrace/diagnostics/health.rb, lib/ddtrace/opentracer/global_tracer.rb, lib/ddtrace/sampler.rb, lib/ddtrace/span.rb, lib/ddtrace/tracer.rb, lib/ddtrace/transport/statistics.rb, spec/ddtrace/configuration/components_spec.rb, spec/ddtrace/configuration/settings_spec.rb, spec/ddtrace/configuration_spec.rb, spec/ddtrace/contrib/analytics_examples.rb, spec/ddtrace/integration_spec.rb, spec/ddtrace/span_spec.rb, spec/ddtrace/tracer_spec.rb, spec/ddtrace/transport/http/client_spec.rb, spec/ddtrace/transport/statistics_spec.rb, spec/support/health_metric_helpers.rb
Currently our configuration settings and tracer components (`Tracer`, `RuntimeMetrics`, etc) are mutable which makes state management cumbersome and can result in some undesirable side effects when reconfigured.
In this pull request, we'd like to address some of these issues by moving towards an immutable configuration model, where tracer components are not mutated, but recreated. This should make state management of tracer components simpler and consistent.
In practice:
1. Users configure the application with `Datadog.configure { |c| #... }` and apply the settings they desire, which mutates the `Datadog.configuration` settings object.
2. When `Datadog.configure` block completes, it creates a `Components` object from the settings, which contains all the major components used by the tracer …
=> Extract components from configuration

Appraisals, Rakefile
Support for Ruby 2.7 has been added to [gRPC 1.28.0](https://github.com/grpc/grpc/releases/tag/v1.28.0).
This allows us to re-enable our gRPC CI tests for Ruby 2.7.
=> Restore gRPC testing for Ruby 2.7

docs/GettingStarted.md
This PR makes it more clear that configuring each Faraday connection is not necessary anymore.
Because this was necessary in past versions, our documentation still had language that suggested this is still necessary.
The language used to explain how to override is the same we use when documenting our MongoDB integration overrides.
=> Clear wording Faraday default integration

docs/GettingStarted.md, lib/ddtrace/configuration/settings.rb, lib/ddtrace/correlation.rb, lib/ddtrace/ext/correlation.rb, lib/ddtrace/ext/environment.rb, spec/ddtrace/configuration/settings_spec.rb, spec/ddtrace/correlation_spec.rb
This pull request:
- Populates configuration `env`, `service`, and `version` to be populated from `tags`, if no value is set but a corresponding tag is configured.
- Omits correlation attributes that have blank values from correlation strings.
- Adds `dd.service` as a correlation attribute.
=> Populate env, service, and version from tags

spec/ddtrace/workers/trace_writer_spec.rb
I'm temporarily disabling `TraceWriter#stop` for JRuby due to their flakiness.
I was not able to find the root cause within reasonable time, so I'm proposing these changes to allow for our CI to work smoothly until the correct fix is found.
=> Temporarily disable flaky TraceWriter#stop tests for JRuby

lib/ddtrace/workers/runtime_metrics.rb, spec/ddtrace/workers/runtime_metrics_spec.rb, spec/ddtrace/writer_spec.rb
After refactoring the runtime metrics worker out of `Writer` in #1004, the worker was not lazily starting after a trace was written, preventing runtime metrics from being emitted.
This pull request changes `Workers::RuntimeMetrics#associate_with_span` to now start the worker when called.
=> Fix runtime metrics not starting after #write

ddtrace.gemspec
The version of bundler we use for testing in CircleCI was locked for Ruby 2.7 due to a bug which seemed to be related to the Appraisal gem.
That issue was [addressed in the upstream ruby docker image](https://github.com/thoughtbot/appraisal/issues/162#issuecomment-614141295), so new docker images we build for CI will work correctly with new versions of bundler.
This PR unlocks the version of bundler so we can continue testing with the latest available version. One thing to note is that the version of bundler we use in CI is locked at the time we publish the image, so we are not actually constantly upgrading bundler. This PR then publishes a new version of the Ruby 2.7 CI image, to allow it to upgrade to the latest version.
=> Unlock Bundler version for testing

lib/ddtrace/buffer.rb, lib/ddtrace/profiling/buffer.rb, lib/ddtrace/profiling/event.rb, lib/ddtrace/profiling/recorder.rb, spec/ddtrace/buffer_spec.rb, spec/ddtrace/profiling/buffer_spec.rb, spec/ddtrace/profiling/event_spec.rb, spec/ddtrace/profiling/recorder_spec.rb
This pull request adds the profiling `Recorder` class, which acts like a buffer for profiling events. The "collector" will generate events and write data to this `Recorder`, then the "scheduler" will dequeue all events from this `Recorder` by invoking `pop`.
=> Add profiling recorder

lib/ddtrace/profiling/exporter.rb, lib/ddtrace/profiling/transport/io/client.rb, lib/ddtrace/profiling/transport/io/response.rb, lib/ddtrace/profiling/transport/parcel.rb, lib/ddtrace/profiling/transport/request.rb, lib/ddtrace/profiling/transport/response.rb, spec/ddtrace/profiling/exporter_spec.rb, spec/ddtrace/profiling/transport/io/client_spec.rb, spec/ddtrace/profiling/transport/io/response_spec.rb, spec/ddtrace/profiling/transport/parcel_spec.rb, spec/ddtrace/profiling/transport/request_spec.rb, spec/ddtrace/profiling/transport/response_spec.rb
This pull request adds the `Profiling::Exporter`, which writes profiling events to a given output. Then exporter receives `#export` with profiling events then uses a `Datadog::Transport::IO::Client` to transmit the data.
By design it implements an extension for its IO protocol, allowing profiling events to be written to IO. It's possible to support other protocols in the future as well (HTTP), but is not currently implemented in this PR.
=> Add profiling exporter

docs/GettingStarted.md, lib/ddtrace/contrib/sinatra/env.rb, lib/ddtrace/contrib/sinatra/ext.rb, lib/ddtrace/contrib/sinatra/patcher.rb, lib/ddtrace/contrib/sinatra/tracer.rb, lib/ddtrace/contrib/sinatra/tracer_middleware.rb, spec/ddtrace/contrib/sinatra/activerecord_spec.rb, spec/ddtrace/contrib/sinatra/multi_app_spec.rb, spec/ddtrace/contrib/sinatra/tracer_spec.rb
Fixes #486 and #913
Closes #491 (thank you @jpaulgs!)
This PR adds improved support for [Sinatra modular applications](
https://github.com/sinatra/sinatra/blob/d112f8f67119e0248b90e98a4a384e2f4287e1fb/README.md#serving-a-modular-application).
We already had support for [classic applications](https://github.com/sinatra/sinatra/blob/d112f8f67119e0248b90e98a4a384e2f4287e1fb/README.md#using-a-classic-style-application-with-a-configru), but it did not translate correctly to modular apps.
We now support nested modular Sinatra apps, and added a new span measuring the specific application route that was matched for a request (`sinatra.route`).
To help support modular apps, a new tag (`sinatra.app.name`) was added to the existing `sinatra.request` span, to identify which modular app handled to the …
=> Support for Sinatra modular apps

lib/ddtrace/configuration/components.rb, spec/ddtrace/configuration/components_spec.rb
Fixes #1021 
This line was collecting old Statsd instances and shutting them down if not in use on `teardown!`. Looks like somehow we were getting `nil` Statsd instances in for metrics, and this array did not `compact` them out, resulting in the function attempting to `nil.close`.
https://github.com/DataDog/dd-trace-rb/blob/10592cebfed7d4f9c509910e4d11faaf00cca668/lib/ddtrace/configuration/components.rb#L135
Added a `compact` and test to address the issue.
=> Fix Components#teardown! NoMethodError

lib/ddtrace/profiling/recorder.rb, lib/ddtrace/profiling/scheduler.rb, lib/ddtrace/utils/time.rb, lib/ddtrace/workers/async.rb, lib/ddtrace/workers/loop.rb, spec/ddtrace/profiling/recorder_spec.rb, spec/ddtrace/profiling/scheduler_spec.rb, spec/ddtrace/utils/time_spec.rb, spec/ddtrace/workers/loop_spec.rb
This pull request adds the `Profiling::Scheduler`, which is responsible for keeping a worker thread which wakes up on an interval to flush all profiling events from the `Recorder` to all the provided `Exporters`.
To do this, `Scheduler` is a `Datadog::Worker` that re-uses `Workers::Polling` to wrap its `perform` method with a polling thread. It also defines some behaviors to manage behavior when forks occur: it should automatically restart the worker thread and clear its buffers on fork, to allow profiling to continue on a child process.
=> Add profiling scheduler

docker-compose.yml
This PR adds a missing part of our support for JRuby: a local docker test environment.
We should not be able to:
```
$ docker-compose run --rm tracer-jruby-9.2
root@645db68092db:/app# ruby -v
jruby 9.2.11.1 (2.5.7) 2020-03-25 b1f55b1a40 OpenJDK 64-Bit Server VM 25.242-b08 on 1.8.0_242-b08 +jit [linux-x86_64]
```
=> Add JRuby to local docker test environment

spec/ddtrace/workers/async_spec.rb
Sometimes the specs assert on `running?` before the worker thread has a chance to reach a running state, causing the test to fail. This pull request adds a delay to give the thread a time to start.
=> Fix flaky Workers::Async test

lib/ddtrace/buffer.rb, lib/ddtrace/ext/profiling.rb, lib/ddtrace/profiling/collectors/stack.rb, lib/ddtrace/profiling/event.rb, lib/ddtrace/profiling/events/stack.rb, lib/ddtrace/profiling/recorder.rb, spec/ddtrace/buffer_spec.rb, spec/ddtrace/profiling/collectors/stack_spec.rb, spec/ddtrace/profiling/event_spec.rb, spec/ddtrace/profiling/events/stack_spec.rb, spec/ddtrace/profiling/recorder_spec.rb
This pull request adds the `Profiling::Collectors::Stack` which polls the available threads (every 10ms by default) for their backtraces, which are packaged inside `StackSample` events, then written to the `Recorder`.
To do this, `Scheduler` is a `Datadog::Worker` that re-uses `Workers::Polling` to wrap its `perform` method with a polling thread. It also defines some behaviors to manage behavior when forks occur: it should automatically restart the worker thread and clear its buffers on fork, to allow stack collection to continue on a child process.
=> Add profiling stack collector

Rakefile, lib/ddtrace/contrib/http/circuit_breaker.rb, lib/ddtrace/contrib/http/instrumentation.rb, spec/ddtrace/contrib/http/circuit_breaker_spec.rb, spec/ddtrace/contrib/suite/transport_spec.rb, spec/support/faux_transport.rb
Fixes #1030 
After refactoring the transport for payload chunking in #840 (released in 0.35.0), it appears that the HTTP circuit breaker misread the transport and didn't flag Net::HTTP requests from the transport as it should have, causing traces to be produced erroneously.
This pull request changes the circuit breaker strategy; rather than to be dependent on reading transport internals and match host/port, it inspects the HTTP request itself for the tracer version header which should only be present on Datadog-made HTTP requests. It will prevent transport changes from causing this error to re-occur.
Note that this is still not optimal; if the trace library makes HTTP calls that do not have this header (which they always should), it will re-occur. We'll need to introduce a better …
=> Fix HTTP circuit breaker

lib/ddtrace/configuration/base.rb, lib/ddtrace/configuration/options.rb, lib/ddtrace/contrib/configuration/settings.rb, lib/ddtrace/contrib/rails/configuration/settings.rb, spec/ddtrace/contrib/configuration/settings_spec.rb, spec/ddtrace/contrib/rails/analytics_spec.rb
Fixes #1032 
When configuring, `Contrib::Configuration::Settings` were effectively eager loading their configuration options in dependency order, which lead to unintended side effects like caching settings that were unwanted.
This pull request removes the eager evaluation so that values do not erroneously cache.
=> Fix #configure forcing all options to eager load

Rakefile, lib/ddtrace/configuration/base.rb, lib/ddtrace/configuration/options.rb, lib/ddtrace/contrib/configuration/settings.rb, lib/ddtrace/contrib/http/circuit_breaker.rb, lib/ddtrace/contrib/http/instrumentation.rb, lib/ddtrace/contrib/rails/configuration/settings.rb, spec/ddtrace/contrib/configuration/settings_spec.rb, spec/ddtrace/contrib/http/circuit_breaker_spec.rb, spec/ddtrace/contrib/rails/analytics_spec.rb, spec/ddtrace/contrib/suite/transport_spec.rb, spec/support/faux_transport.rb
Backport #1033 and #1034 from `master` to `0.35-stable` to allow for a 0.35.2 bugfix release.
These pull requests address issues introduced in 0.35.
=> Backport master fixes to since 0.35.1

.rubocop.yml, lib/ddtrace/contrib/extensions.rb, lib/ddtrace/contrib/rails/configuration/settings.rb, lib/ddtrace/contrib/rails/framework.rb, spec/ddtrace/contrib/extensions_spec.rb, spec/ddtrace/contrib/rails/middleware_spec.rb, spec/ddtrace/contrib/rails/redis_cache_spec.rb, test/contrib/rails/controller_test.rb, test/contrib/rails/errors_test.rb, test/contrib/rails/rack_middleware_test.rb
Today, in a configuration block...
```ruby
c.use :faraday
end
```
`c.use` configures and patches the integration immediately. This has the unwanted side effect of causing trace components being initialized with default settings before the configuration block is completed, because patching integrations often calls `Datadog.logger` which is a trace component.
In this pull request, `c.use` adds the integration to a list of pending integrations, which are each patched after the configuration block completes and the trace components are initialized. This prevents trace components from being re-initialized multiple times during setup.
=> Lazily activate integrations

Appraisals
Since `google-protobuf` `3.12.0` has been released, our older versions of Ruby have been trying to install it, but this new version only support Ruby => 2.5.
Bundler/rubygems should know this and not try to install an compatible version, but that doesn't seem to be the case. I found a few older GH issues about this issue, but nothing conclusive.
I believe the older version of bundler+rubygems are likely part of the problem, but it's ok to use those old versions when testing older Rubies.
This PR locks gRPC and it's dependency, `google-protobuf`, to the latest supported version for Ruby 2.2, 2.3 and 2.4. Ruby >= 2.5 continue to be supported by the latest release as usual.
=> Lock gRPC version for older Rubies

Appraisals
The same issue we had with Rails 5.2 running on Ruby 2.2 is back: https://github.com/rails/rails/issues/39371
Because Rails 5.2 is only receiving security updates (but those have been flaky recently) we should be safe with not updating the version of Rails for Ruby 2.2.
=> Lock Rails 5.2 version for Ruby 2.2

test/concurrent_test.rb
Our new JRuby test suite fails frequently while running `test/concurrent_test.rb`. This happens because the tracer is lazily initialized concurrently across many threads, which we currently do not support.
This PR ensures the tracer is properly initialized before the concurrency test runs.
=> Initialize tracer before concurrency test

lib/ddtrace/pin.rb, spec/ddtrace/pin_spec.rb
After switching to an immutable component structure in #996, `Datadog.tracer` can change after `Datadog.configure` is run. `Datadog::Pin#new` caches `Datadog.tracer` on itself when created, which could be undesirable if the intent is to use the default tracer.
This pull request changes `Datadog::Pin` to delegate to `Datadog.tracer` when no tracer is configured instead of caching the value of `Datadog.tracer` on the pin.
=> Only store #tracer on Pin when configured

lib/ddtrace/contrib/rails/integration.rb, spec/ddtrace/contrib/rails/integration_spec.rb
Per #993, when users run Rails applications without `gem 'rails'` and opt to load gems manually, the Rails patcher aborts patching because it can't find the Rails version in the Rails gem.
This had to do with some changes we made to add stricter version checks for integrations in 0.33.0. It was checking if `Gem.loaded_specs['rails']` was loaded, and when it didn't find it, it would assume Rails wasn't present.
This pull request changes this check to also see if `gem 'railties'` are loaded, which are used in Rails applications, regardless of whether `gem 'rails'` is included or not. If `railties` are present, it will attempt Rails patching.
=> Allow Rails patching to occur if Railties are loaded

.gitlab-ci.yml
This PR adds a build file to trigger our internal Gitlab CI pipeline, which currently triggers a deployment for our reliability environment when new commits are added to the `master` branch of `dd-trace-rb`.
This build pipeline is private because it contains secret credentials.
=> Add Gitlab build pipeline

Rakefile, ddtrace.gemspec, spec/ddtrace/benchmark/microbenchmark_spec.rb, spec/support/faux_writer.rb
This PR adds microbenchmarks to core components of `ddtrace`.
Currently we test:
* Trace creation (`tracer.trace`)
* Writer trace recording (`writer.write`)
* Baseline benchmark overhead: tests an empty method call, to validate if the benchmark environment is stable.
All test cases are measure for execution time, memory usage and GC impact.
The output looks like this (for testing `Datadog::Tracer nested traces` in this example):
```
Test:Microbenchmark Datadog::Tracer nested traces memory
Calculating -------------------------------------
1   253.544k memsize (    91.440k retained)
2.830k objects (   704.000  retained)
4.000  strings (     1.000  retained)
10     1.811M memsize (   862.280k retained)
14.488k objects (     5.661k retained)
3.000  strings (     0.000  retained)
100 …
```
=> Add Microbenchmarking

Rakefile, ddtrace.gemspec, docs/DevelopmentGuide.md, lib/ddtrace/context.rb, lib/ddtrace/ext/system.rb, lib/ddtrace/tracer.rb, lib/ddtrace/utils.rb, spec/ddtrace/benchmark/microbenchmark_spec.rb, spec/support/faux_writer.rb
_**TL;DR: 26%-35% memory reduction, 3%-17% speedup**_
This PR aims to reduce the memory footprint of a trace object creation. Execution time improvement is not the goal, but a regression should be avoided.
This work was mostly guided by the results of our benchmark memory report `Microbenchmark benchmark detailed report memory report`. This test provides a very detailed result of all allocation sites exercised during a run.
We use the benchmark `Microbenchmark Datadog::Tracer nested traces` to measure the impact of our changes. This benchmark runs the statement `tracer.trace('my.op'){ ... }` with varying amount of nested spans: `1`, `10` and `100` in the results below represent the number of nested spans created during a test run.
Bellow are the results after the changes have been …
=> Reduce memory overhead of Tracer#trace

spec/ddtrace/benchmark/gem_loading_spec.rb
Similar to #1043, this PR adds memory and timing benchmarking to the gem loading process: `require 'ddtrace'`.
Here's the sample output:
```
ddtrace gem memory footprint: 6199.06 KiB
ddtrace gem load time: 0.155863s
```
We run the gem loading process a few times in a new process (to be able to `require` again like it is the first time) and collect the average to create these results.
Plus, we also have the detailed memory report when running locally:
```
Total allocated: 6477394 bytes (47492 objects)
Total retained:  895123 bytes (7032 objects)
allocated memory by gem
-----------------------------------
6455955  ./lib
21439  other
allocated memory by file
-----------------------------------
685735  ./lib/ddtrace.rb
276785  ./lib/ddtrace/tracer.rb
200023 …
```
=> Add gem startup benchmarking

docs/DevelopmentGuide.md, lib/ddtrace/context.rb, lib/ddtrace/ext/system.rb, lib/ddtrace/tracer.rb, lib/ddtrace/utils.rb
This reverts commit 0625ccc10682699d8d3a226cae65588b7d221a6b.
Ever since we've merged this change, we've noticed spikes in our internal testing environment.
We are taking a conservative approach to revert these changes for now and try to introduce them again in the future with further testing.
=> Revert "Reduce memory overhead of Tracer#trace (#1050)"

.circleci/config.yml
`appraisal install` runs `bundle check` first, then `bundle install` if `bundle check` returned false:
```
bundle exec appraisal install
>> bundle check --gemfile='gemfiles/rails5_mysql2.gemfile' || bundle install --gemfile='gemfiles/rails5_mysql2.gemfile'
```
`bundle check` returns true if the gems currently installed in the system can fulfill the `Gemfile.lock` (or simply the `Gemfile`, if a lock file is absent).
When `bundle check` runs the for first time in our CI, there is no `Gemfile.lock` available, so it tries to satisfy the `Gemfile` dependencies, which are lenient (e.g. `gem 'excon'`), and `bundle check` will  consider that dependency fulfilled as long as a version that satisfies the version constraint is installed.
In contrast, `bundle install` will always try to fetch the …
=> ci: Ensure Appraisal fetches latest version of dependencies

lib/ddtrace/transport/io/response.rb, lib/ddtrace/transport/io/traces.rb, spec/ddtrace/transport/io/response_spec.rb, spec/ddtrace/transport/io/traces_spec.rb
When `Profiling::Transport::IO` was inheriting from `Transport::IO`, the base class had a requirement for some trace-specific attribute (`trace_count`.) This pull request moves this trace specific attribute into the traces transport, so that profiling transports do not need it.
=> Fix Profiling::Transport::IO load dependency

lib/ddtrace/transport/io/response.rb, lib/ddtrace/transport/io/traces.rb, lib/ddtrace/utils/compression.rb, spec/ddtrace/transport/io/response_spec.rb, spec/ddtrace/transport/io/traces_spec.rb, spec/ddtrace/utils/compression_spec.rb
In order to support compressing content sent over the wire, this pull request adds a `Datadog::Utils::Compression` utility that adds support for gzip compression and decompression.
=> Add Datadog::Utils::Compression

LICENSE-3rdparty.csv, lib/ddtrace/vendor/multipart-post/LICENSE, lib/ddtrace/vendor/multipart-post/multipart.rb, lib/ddtrace/vendor/multipart-post/multipart/post.rb, lib/ddtrace/vendor/multipart-post/multipart/post/composite_read_io.rb, lib/ddtrace/vendor/multipart-post/multipart/post/multipartable.rb, lib/ddtrace/vendor/multipart-post/multipart/post/parts.rb, lib/ddtrace/vendor/multipart-post/multipart/post/version.rb, lib/ddtrace/vendor/multipart-post/net/http/post/multipart.rb
Because our HTTP transports need the ability to send multipart forms, and `Net::HTTP` doesn't support multipart form building out of the box, we need to add support for this behavior.
In this pull request, we copy [`multipart-post`](https://github.com/socketry/multipart-post) into our `vendor` directory with some minor alterations in order to 1) avoid conflict with user's applications, and 2) avoid re-engineering form building.
=> Add multipart-post package

spec/ddtrace/workers/async_spec.rb
While testing `Datadog::Workers::Async::Thread#running?`, we could encounter a race condition where we start a background task but that task finishes before we can check the result of `#running?`:
https://github.com/DataDog/dd-trace-rb/blob/6e326cce76c0b6130d5bb936f6ba71a924b15850/spec/ddtrace/workers/async_spec.rb#L266-L274
This happens because the task we schedule to run is empty, finishing very quickly.
This PR changes the background task to wait for some time, so we can assert on it. The thread won't hold our test suite back because we call `worker#terminal`, which forcefully terminates the thread.
=> test:Ensure worker thread waits for test assertion

lib/ddtrace/contrib/sidekiq/ext.rb, lib/ddtrace/contrib/sidekiq/server_tracer.rb
Currently the traces captured for Sidekiq jobs when using the sidekiq integration include `sidekiq.job.retry` which is just the configuration value for whether the job should be retried, or how many retries should be attempted. This information doesn't add too much value, as it can be found on the code and rarely changes for any particular job.
This PR adds the current retry count for each job, which is available as `retry_count` in the job payload according to [Sidekiq documentation](https://github.com/mperham/sidekiq/wiki/Job-Format). This information is useful for debugging and identifying traces of jobs that are being repeated.
=> Add retry_count tag to Sidekiq job traces

lib/ddtrace/pipeline/span_filter.rb
This patch modifies `Datadog::Pipeline::SpanFilter` to make a single pass through the trace array.
The motivation for this change is that we ran into a situation where a trace was being generated with tens of thousands of spans. The trace was fairly shallow and we were filtering around half the spans (all without children). This became a performance issue as each span that was deleted results in another pass through the remaining array.
We have since modified our tracing to avoid the large traces, but I believe the SpanFilter remains a performance concern.
One case this does not handle is if a child span can appear before a parent in the trace array. The current tests do not cover that scenario. If that is a concern, then the approach below could be modified to make additional passes …
=> Single pass SpanFilter

docs/GettingStarted.md, lib/ddtrace/configuration/settings.rb, lib/ddtrace/contrib/extensions.rb, lib/ddtrace/diagnostics/environment_logger.rb, lib/ddtrace/ext/diagnostics.rb, lib/ddtrace/sampler.rb, lib/ddtrace/transport/http/adapters/net.rb, lib/ddtrace/transport/http/adapters/test.rb, lib/ddtrace/transport/http/adapters/unix_socket.rb, lib/ddtrace/transport/response.rb, lib/ddtrace/workers/trace_writer.rb, lib/ddtrace/writer.rb, spec/ddtrace/contrib/extensions_spec.rb, spec/ddtrace/diagnostics/environment_logger_spec.rb, spec/ddtrace/transport/http/adapters/net_spec.rb, spec/ddtrace/transport/http/adapters/unix_socket_spec.rb, spec/ddtrace/writer_spec.rb
Adds standardized startup logging as soon as we have enough information to do so.
Help support get as much information as they can from app startup logs.
We collect logs when the first trace is attempted to be sent to the agent. This allows us to collect valuable information about the connectivity with the agent and any specific failure conditions, if any.
This information is logged only once for the application lifetime.
=> feat:Startup environment log

lib/ddtrace/contrib/rack/middlewares.rb, lib/ddtrace/contrib/rest_client/request_patch.rb, lib/ddtrace/tracer.rb, spec/ddtrace/contrib/rack/middlewares_spec.rb, spec/ddtrace/contrib/rest_client/request_patch_spec.rb, spec/ddtrace/tracer_spec.rb
When a Ruby application raises a fatal (non-`StandardError`) exception our tracer might intercept that error in one of our `being/rescue` blocks. We should make sure that we properly propagate such errors, as they are normally important signals of an unrescuable situation.
This PR addresses the remaining code blocks that could intercept fatal exceptions and not correctly propagate them, normally due to these blocks erroring themselves during edge cases.
The most common case this PR will alleviate is the proper handling of graceful shutdowns in the form of fatal `SignalException`s.
=> Ensure fatal exceptions are propagated

lib/ddtrace/contrib/faraday/middleware.rb, lib/ddtrace/contrib/faraday/patcher.rb, spec/ddtrace/contrib/faraday/middleware_spec.rb
Our auto instrumentation did not configure itself to work with Faraday's default connection.
The default connection is used when using the short Faraday syntax: `Faraday.get("http://domain.com/path")`.
Other use cases that create a `Faraday::Connection` (`Faraday.new`, for example) are already auto instrumented.
=> Auto instrument Faraday default connection

lib/ddtrace/contrib/grpc/datadog_interceptor/client.rb, lib/ddtrace/span.rb, lib/ddtrace/tracer.rb, spec/ddtrace/span_spec.rb
In many places it is reasonable to set span tags from a hash. Currently the only way was to iterate thru the hash and call `set_tag`. `set_tags` implements this directly in Span so user code does not need to repeat it everytime tags are set from a hash.
=> Introduce Span#set_tags

bin/ddtracerb, ddtrace.gemspec, lib/ddtrace/configuration.rb, lib/ddtrace/ext/profiling.rb, lib/ddtrace/profiling.rb, lib/ddtrace/profiling/collectors/stack.rb, lib/ddtrace/profiling/events/stack.rb, lib/ddtrace/profiling/ext/thread.rb, lib/ddtrace/profiling/pprof/converter.rb, lib/ddtrace/profiling/pprof/stack_sample.rb, lib/ddtrace/profiling/preload.rb, lib/ddtrace/profiling/tasks/setup.rb, lib/ddtrace/tasks/exec.rb, lib/ddtrace/tasks/help.rb, spec/ddtrace/profiling/collectors/stack_spec.rb, spec/ddtrace/profiling/events/stack_spec.rb, spec/ddtrace/profiling/ext/thread_spec.rb, spec/ddtrace/profiling/integration_spec.rb, spec/ddtrace/profiling/pprof/stack_sample_spec.rb, spec/ddtrace/profiling/pprof/template_spec.rb, spec/ddtrace/profiling/preload_spec.rb, spec/ddtrace/profiling/spec_helper.rb, spec/ddtrace/profiling/tasks/setup_spec.rb, spec/ddtrace/profiling_spec.rb, spec/ddtrace/tasks/exec_spec.rb, spec/ddtrace/tasks/help_spec.rb
Out of the box, Ruby is unable to provide CPU time per thread, because the Ruby API does not expose either the native thread ID or the clock ID for which to get the time from. Although there is a C API for getting the current native thread, getting the clock for that thread, and getting the time for that clock, this is not accessible from another thread (our profiling thread.)
To work around this, this pull request:
1. Adds a `bin/ddtrace` executable that can be used to wrap any Ruby process to preload a patch to `Thread`...
2. ...which hijacks the `Thread`'s execution block, and uses it to obtain and store the native thread ID from within the thread, and store it on the `Thread` object.
3. Then the "stack" profiler can call `cpu_time` against the patched `Thread` object to get the CPU …
=> Add profiling CPU time per thread

.gitignore, docker-compose.yml, lib/ddtrace/configuration/settings.rb, lib/ddtrace/environment.rb, lib/ddtrace/ext/environment.rb, spec/ddtrace/configuration/settings_spec.rb, spec/ddtrace/diagnostics/environment_logger_spec.rb, spec/ddtrace/environment_spec.rb
This pull request adds `DD_SITE` and `DD_API_KEY` configuration settings, which can be set via either ENV or via `Datadog.configure`. These settings are used for submitting trace and profile data to Datadog.
=> DD_SITE and DD_API_KEY configuration

lib/ddtrace/profiling.rb, lib/ddtrace/profiling/profiler.rb, spec/ddtrace/profiling/integration_spec.rb, spec/ddtrace/profiling/profiler_spec.rb
This pull request adds the `Datadog::Profiler`, which holds the collectors and scheduler for profiling, which can be collectively started or shutdown.
=> Add Datadog::Profiler

lib/ddtrace/profiling/collectors/stack.rb, lib/ddtrace/profiling/encoding/profile.rb, lib/ddtrace/profiling/exporter.rb, lib/ddtrace/profiling/flush.rb, lib/ddtrace/profiling/recorder.rb, lib/ddtrace/profiling/scheduler.rb, lib/ddtrace/profiling/transport/client.rb, lib/ddtrace/profiling/transport/io/client.rb, spec/ddtrace/profiling/encoding/profile_spec.rb, spec/ddtrace/profiling/exporter_spec.rb, spec/ddtrace/profiling/recorder_spec.rb, spec/ddtrace/profiling/scheduler_spec.rb, spec/ddtrace/profiling/spec_helper.rb, spec/ddtrace/profiling/transport/io/client_spec.rb
In order to assist transport, and make "flushes" more self-contained, this pull request adds some richer metadata to the `Flush` object. This richer version of `Flush` includes the events, time stamps, and details about the environment.
This additional data can be used to produced a more robust dump of flush data to HTTP, or other channels.
=> Add metadata to profiling flush

CHANGELOG.md, lib/ddtrace/diagnostics/environment_logger.rb, spec/ddtrace/diagnostics/environment_logger_spec.rb
This PR ensures that integration settings that can store arbitrary values, e.g. `"integration_rack_application"`, don't expand into a large payload like:
```
#<RailsApp::Application:0x00007fde60c43bc8
@_all_autoload_paths=
["./rails/app/controllers",
"./rails/app/helpers",
"./rails/app/jobs",
"./rails/app/models"],
@_all_load_paths=
["./rails/app/controllers",
"./rails/app/helpers",
"./rails/app/jobs",
"./rails/app/models"],
@app=
#<Datadog::Contrib::Rack::TraceMiddleware:0x00007fbfb4dda128
@app=
#<ActionDispatch::HostAuthorization:0x00007fbfb4dda240
@app=
#<Rack::Sendfile:0x00007fbfb4dda308
@app=
#<ActionDispatch::Executor:0x00007fbfb4dda380
@app=
#<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x00007fbfb4f3e000
@app=
#<Rack::Runtime:0x00007fbfb4dda3d0
@app= …
```
=> fix:Convert custom setting value to string for startup log

docs/GettingStarted.md
This PR address the wording on ActiveRecord's `orm_service_name` option, to make it clear that it refers to the Ruby object instantiation portion of ActiveRecord queries.
=> docs:Clear wording for :orm_service_name setting

spec/ddtrace/diagnostics/environment_logger_spec.rb
We were disabling the tracer for a `environment_logger_spec.rb`, but never re-enabling it.
This could cause subsequent tests to fail, like this one: https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/1563/workflows/080116a3-5a99-45ca-a4ec-3fe67c657cb0/jobs/77623
=> test:Fix leaky tracer setting

lib/ddtrace/configuration/settings.rb, lib/ddtrace/diagnostics/environment_logger.rb, lib/ddtrace/logger.rb, spec/ddtrace/configuration/settings_spec.rb, spec/ddtrace/configuration_spec.rb, spec/ddtrace/diagnostics/environment_logger_spec.rb, spec/ddtrace/logger_spec.rb
Fixes #1112
This PR changes the default `Datadog.logger` default level to `INFO`.
This allows us to reduce the log level of #1104 down from `WARN` to `INFO`, which was the original plan.
The change to the default log level does not affect any internal usage of `Datadog.logger`: we don't have any active path emitting `INFO` level messages.
We **do** have an undocumented [alternative implementation of `Datadog::Statsd`](https://github.com/DataDog/dd-trace-rb/blob/9c73f569ed973631f8113a360f159422005c80b9/lib/ddtrace/metrics.rb#L185-L214), which needs to be explicitly instantiated by the user, which outputs `INFO` level messages. This use case is not common, and only recommended for developing/debugging environments.
=> change:Default logger level from WARN to INFO

lib/ddtrace/contrib/httprb/instrumentation.rb, spec/ddtrace/contrib/httprb/instrumentation_spec.rb
Resolves https://github.com/DataDog/dd-trace-rb/issues/1116 
This piggybacks off the discussion here https://github.com/DataDog/dd-trace-rb/pull/1117
Ultimately, it is not safe to read the http.rb response body in ddtrace: we end up consuming the body reading stream, so the host application cannot properly read it. The httprb suggests usage of `.readpartial` which we would also impact.
To address this issue we should stop reading the response body message altogether. This will remove some information from our error reporting, but it's ultimately required for the safe operation of ddtrace with http.rb.
=> Fix 1116, remove parsing of resp body from http.rb instrumentation

spec/ddtrace/workers/polling_spec.rb
Similar to #1103, this PR makes background threads in `polling_spec.rb` wait until assertions can be performed on the worker class under test.
This has manifested more clearly in [JRuby sporadic CI failures](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/1484/workflows/0f3d214c-f1da-4ba1-be8a-91fca0c519ba/jobs/75277/steps):
```c
1) Datadog::Workers::Polling when included into a worker #stop called multiple times with graceful stop is expected to equal true
Failure/Error: expect(worker.stop).to be true
expected true
got false
```
=> test:Ensure worker thread waits for test assertion 2

lib/ddtrace/transport/http/adapters/test.rb, spec/ddtrace/transport/http/adapters/test_spec.rb
This PR addresses https://github.com/DataDog/dd-trace-rb/issues/1125, in which the startup env logger attempts to record the `adapter.url`, but in test environments using the `Adapters::Test` class, this method is not defined, causing an exception to be thrown. While we catch and handle this exception, it's unintended/noisy and causes startup env logs to be lost. This PR adds a stubbed out url method on the test adapter. Long term it make might sense to have all adapters inherit from  a base adapter
=> add url method on test adapter to prevent startup env logs from throwing exception

spec/support/synchronization_helpers.rb, test/helper.rb
While trying to debug flaky tests that wait for an asynchronous condition (by invoking `try_wait_until`), I found that it is possible that some of these tests are timing out while waiting for the condition to be met.
We currently don't provide any signal that a timeout happened, we just return and move along the test execution. This can cause assertions to be performed on incomplete data, causing seemly random failures.
This PR adds clear information (in the for of an exception) that a timeout was reached when calling `try_wait_until`, meaning the required condition might not have been reached.
=> test:Report when test exhausts wait timeout

docs/GettingStarted.md
These should now work when published to https://docs.datadoghq.com/tracing/setup/ruby/
=> docs:Fix http.rb internal links

docs/GettingStarted.md
After one year under "Maintenance" status, support for Ruby 1.9 has reached its end of life.
=> docs:Mark Ruby 1.9 as EOL

lib/ddtrace/configuration.rb, lib/ddtrace/configuration/components.rb, spec/ddtrace/configuration/components_spec.rb, spec/ddtrace/configuration_spec.rb
Some parts of `Datadog::Configuration::Components` require startup (namely worker threads); this pull request adds a `Components#startup!` method which defines this behavior. It also does some minor refactoring of how components are built/replaced in the configuration cycle (original behavior should be largely unaffected though.)
This hook isn't employed in this PR but will become necessary for profiling and other auto-starting processes.
=> Add Components#startup! hook

spec/ddtrace/contrib/sucker_punch/patcher_spec.rb
Fixes https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/1691/workflows/ebaf9777-0229-49e2-9172-438841cea5d4/jobs/81378:
```
1) sucker_punch instrumentation delayed job should instrument enqueuing for a delayed job
Failure/Error: is_expected.to be true
expected true
got false
```
This error happens because `SuckerPunch::Job#perform_in` schedules the job to be performed and then checks if the job status is `:pending` right before returning. If the job finishes too quickly, it might have already been moved into a `:fulfilled`, thus making `#perform_in` return false.
This PR does not verify the return value of `#perform_in` anymore, as it is unimportant to our tests, but maintains the verification that the job has finished and that the correct spans have been generated.
=> test:Fix sucker_punch flaky test

lib/ddtrace/contrib/racecar/events.rb, lib/ddtrace/contrib/racecar/events/consume.rb, lib/ddtrace/contrib/racecar/ext.rb, spec/ddtrace/contrib/racecar/patcher_spec.rb
Right now, Racecar consumer processes use one of two top level span names based on the mode of operation: `racecar.message` or`racecar.batch`. Because of this, the Datadog interface cannot show single message consumers and batch consumers in the same list.
This change subscribes to the `main_loop` event which wraps both of these more specific events. The new span is called `racecar.consume` since that is the logical operation.
=> Add a single top level span for Racecar consumers

lib/ddtrace/profiling/ext/forking.rb, lib/ddtrace/profiling/ext/thread.rb, lib/ddtrace/profiling/tasks/setup.rb, spec/ddtrace/profiling/ext/forking_spec.rb, spec/ddtrace/profiling/spec_helper.rb, spec/ddtrace/profiling/tasks/setup_spec.rb
We currently have a number of processes, background workers running on threads, which must run continuously in order to function. When Ruby forks, it terminates threads (including these workers), which must be manually restarted.
There is no Ruby-provided hook for running code at the start of new forks (see https://bugs.ruby-lang.org/issues/5446), so right now we depend upon leveraging analogous "on fork" hooks implemented within various frameworks that do the forking (e.g. Resque, Puma, etc.) This means users must manually add this configuration.
This pull request provides an `on_fork` hook, that leverages `ddtracerb` to patch `fork` to trigger callbacks. When a callback is defined, it will be invoked within the fork prior to any other code being executed.
We could use this hook to …
=> Add on_fork callback

lib/ddtrace/workers/async.rb, lib/ddtrace/workers/loop.rb, lib/ddtrace/workers/polling.rb
This PR fixes most recent CI timeouts, specially the ones seen for JRuby:
```
Failures:
1) Datadog::Workers::Polling when included into a worker #perform by default 
Failure/Error: raise StandardError, 'Wait time exhausted!' if attempts <= 0
StandardError:
Wait time exhausted!
```
These timeouts happen because probing `worker.run_loop?` can have the non-thread-safe side-effect of setting `@run_loop = false`:
```ruby
def run_async?
@run_async = false unless instance_variable_defined?(:@run_async)
@run_async == true
end
```
If the check for `instance_variable_defined?(:@run_async)` is executed then the Ruby VM context switches to:
```ruby
def perform_loop
@run_loop = true
loop do
return unless run_loop? || work_pending?
end
end
```
which sets it to true: `@run_loop = true`.
Then context …
=> fix:Race condition on instance variable assignment

lib/ddtrace/configuration.rb
When `Components` are built, they sometimes log messages to `Datadog.logger`. If this happens, logger is not yet built/resolved, so it will lazily build another, triggering yet another log message and forming a recursive loop.
A simple way around this is to have some kind of default logger when components have not been initialized, but yields to the configured logger once its been built/configured.
=> Prevent logger recursion during startup

docs/GettingStarted.md, lib/ddtrace/profiling.rb, lib/ddtrace/profiling/ext/cpu.rb, lib/ddtrace/profiling/ext/cthread.rb, lib/ddtrace/profiling/ext/forking.rb, lib/ddtrace/profiling/preload.rb, lib/ddtrace/profiling/tasks/setup.rb, spec/ddtrace/profiling/ext/cpu_spec.rb, spec/ddtrace/profiling/ext/cthread_spec.rb, spec/ddtrace/profiling/ext/forking_spec.rb, spec/ddtrace/profiling/preload_spec.rb, spec/ddtrace/profiling/tasks/setup_spec.rb, spec/ddtrace/profiling_spec.rb
To simplify the setup of the profiler, this pull request adds an `autostart_profiler` step to the setup task for profiling. In doing so, using `ddtracerb exec` will automatically start the profiler, and set the restart hooks when forked, if profiling is enabled. If an error is raised, or profiling is enabled but not supported, it will print warnings to STDOUT.
Some pre-requisites for this are:
- Some refactoring of the setup task (included in this PR)
- at_fork hook (added in #1143)
- Logging recursion fix (#1158)
=> Autostart profiler

lib/ddtrace/contrib/action_pack/action_controller/instrumentation.rb, lib/ddtrace/contrib/rails/middlewares.rb, test/contrib/rails/apps/controllers.rb, test/contrib/rails/apps/routes.rb, test/contrib/rails/rack_middleware_test.rb
This PR addresses https://github.com/DataDog/dd-trace-rb/issues/1155 , when a user modifies or handles a Rails Controller exception in a `rescue_from` block.  Since adding https://github.com/DataDog/dd-trace-rb/pull/1124, the instrumentation has been setting any rails errors upstream on the rack span. However, in cases where these exceptions get swallowed, or re-raised with a different exception, in a `rescue_from`, this causes the rack span to contain stale information, since we haven't been accounting for `rescue_from` in our current rails instrumentation.
By moving the rails => rack span upstream error propagation from the `action_controller` instrumentation, and into the datadog rails `exception_middleware`, we ensure we're modifying the rack span as late as possible before the …
=> Updated Rack/Rails span error setting behavior

spec/ddtrace/opentracer/propagation_integration_spec.rb
Fixes [this CI issue](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/1807/workflows/d231dc3a-567b-44cc-b380-c3e5191b263f/jobs/84823):
```
Failures:
1) OpenTracer context propagation via OpenTracing::FORMAT_RACK when receiving a carrier with no headers 
Failure/Error: Datadog::Statsd.new(default_hostname, default_port)
ArgumentError:
wrong number of arguments (given 2, expected 0)
```
This error happens because the OpenTracing test was not properly closing the worker thread crated by its write, causing it to interfere with subsequent test runs. This PR fixes that by properly shutting down the tracer after each run.
This error can be reproduced with the following command:
`bundle exec rspec ./spec/ddtrace/opentracer/propagation_integration_spec.rb --seed=42061`
You might have …
=> Ensure OpenTracer test does not leak writer thread

.circleci/config.yml, .simplecov, Rakefile, ddtrace.gemspec, docs/DevelopmentGuide.md, spec/spec_helper.rb
Seeing is believing: https://84200-66497320-gh.circle-artifacts.com/0/coverage/index.html
This PR adds code coverage reporting for our CI tests.
Tests from different runs are merged together in a new `coverage` step.
A report is made available as an uploaded artifact in the `coverage` step, under `coverage/index.html`: 
It's also possible to see the individual coverage on a per Ruby version basis: these reports will be uploaded on the same build step, under (e.g. for Ruby 2.0) `coverage/versions/test-2.0/index.html`. This is specially useful when adding support for a new Ruby version.
A report can also be generated locally by executing `bundle exec rake coverage:report` after running any of our test suites or individual tests. Results will be written to the `./coverage/` directory.
=> test:Code coverage report

.gitlab-ci.yml
This removes the Gitlab internal CI check from all Github commits, unless it's applicable: only `master` commits and manually triggered Gitlab job runs will show up here on Github.
This will allow our commits to come back into a ✅ state when everything passes.
=> ci:Remove gitlab deployment when not applicable

spec/ddtrace/profiling/ext/forking_spec.rb
This forking patch test attempts to unpatch and repatch classes between examples. Although this is a bit tricky, in Ruby 2.3+ this seems to be okay, while it intermittently fails in Ruby 2.1. It's not clear why the random test failure occurs, and its not particularly critical either. Opting to disable it for now.
=> Skip Forking patch test for < 2.3

lib/ddtrace/buffer.rb, lib/ddtrace/profiling/backtrace_location.rb, lib/ddtrace/profiling/buffer.rb, lib/ddtrace/profiling/collectors/stack.rb, lib/ddtrace/profiling/pprof/stack_sample.rb, lib/ddtrace/profiling/recorder.rb, lib/ddtrace/utils/object_set.rb, lib/ddtrace/utils/string_table.rb, spec/ddtrace/buffer_spec.rb, spec/ddtrace/profiling/backtrace_location_spec.rb, spec/ddtrace/profiling/buffer_spec.rb, spec/ddtrace/profiling/collectors/stack_spec.rb, spec/ddtrace/profiling/recorder_spec.rb, spec/ddtrace/utils/object_set_spec.rb, spec/ddtrace/utils/string_table_spec.rb
Currently the profiler produces a `Profiling::Events::StackSample` object per thread per sample, and within each of these samples, they have up to 128 `Thread::Backtrace::Location` objects that represent the stack. Given the buffer flushes these samples once every 60 seconds, these samples can have a significant memory footprint.
To reduce this footprint, we'd like to re-use equivalent objects wherever possible, including `StackSample`, `Backtrace::Location` and `String` objects.
In this pull request, we add secondary "string table" and "object sets" to the `Profiling::Buffer`. The idea is that before a sample is pushed to the buffer, the stack collector would use these tables to see if there's already a `BacktraceLocation` or `String` in the buffer that is equivalent. If there is, simply …
=> Add string table and object sets to profiling buffer

spec/spec_helper.rb
Collecting code coverage during benchmarks slows down the execution.
This PR disables coverage collection on all tests run from a benchmark directory.
=> Disable coverage report for benchmarks

ddtrace.gemspec, lib/ddtrace/contrib/active_support/notifications/subscription.rb, lib/ddtrace/contrib/grape/endpoint.rb, lib/ddtrace/span.rb, lib/ddtrace/span/duration.rb, lib/ddtrace/tracer.rb, spec/ddtrace/contrib/active_support/notifications/subscription_spec.rb
When measuring durations, it's preferable to use the system monotonic
clock rather than `Time.now` in order to avoid problems with the wall
clock potentially moving forwards or backwards for corrections that
would throw off calculation of elapsed time.
https://blog.dnsimple.com/2018/03/elapsed-time-with-ruby-the-right-way/
This was written in order to preserve the existing behavior in cases where the start time or end time were manually set.
**NEW BEHAVIOR**
* If a span has `start` and `finish` called in-order, with no explicit `start_time` or `finish_time` given it will use the monotonic clock to measure duration.
**Existing (preserved) behavior**
* If a span has `finish` called without first having called `start` the duration will be `0`
* If a span has `start` called with an explicit …
=> Improve duration counting using monotonic clock

spec/ddtrace/benchmark/microbenchmark_spec.rb, spec/ddtrace/benchmark/support/benchmark_helper.rb
Add an end-to-end test to our benchmarking suite.
This test generated traces (ranging from 1 to 100 nested spans), sends them to the write, which sends it by HTTP to a locally running agent.
This benchmark exercises the exact same code path that host applications will perform.
With this benchmark we should be able to report on measurable, tracer-level gains performed when optimizations on a subset of the tracer.
=> Add end-to-end benchmarking

lib/ddtrace/configuration.rb, spec/ddtrace/configuration_spec.rb, spec/ddtrace/contrib/support/tracer_helpers.rb
We have inconsistent behaviour with `Configuration#shutdown!` where we shut down our components object (`        components.shutdown!`), but we keep its lingering instance in an instance variable (`@components`), with partially living references.
This prevented us from ever being able to restart the tracer, only ever returning dirty instances of the tracer on every call to `Datadog.tracer` after a shutdown.
This PR now allows the tracer components to be cleanly `shutdown!` and restarted, without lingering references.
=> Allow tracer components to be cleanly restarted after shutdown

ddtrace.gemspec, lib/ddtrace/buffer.rb, lib/ddtrace/ext/runtime.rb, spec/ddtrace/benchmark/buffer_benchmark_spec.rb, spec/ddtrace/buffer_spec.rb
**_tl;dr: reduction of 17-93% of allocated bytes, 5-15% faster._**
Leveraging the fact that the native Ruby `Array` ["is thread-safe in practice because CRuby runs threads one at a time and does not do context switching during the execution of C functions"](https://github.com/ruby-concurrency/concurrent-ruby/blob/c1114a0c6891d9634f019f1f9fe58dcae8658964/lib/concurrent-ruby/concurrent/array.rb#L23-L27), this PR implements a version of the `TraceBuffer` that does not use explicit locking.
The buffer is one of the tracer hot-stops, being a sync point between the application critical path and the tracer's worker thread. All traces will eventually be pushed into the buffer, so improvements to it affect all instrumentations.
This version works correctly on CRuby, but will not maintain the same …
=> Faster TraceBuffer for CRuby

Rakefile
With the introduction of new benchmarks, our CI builds have got very slow.
Benchmarks will not yield representative numbers when running in a shared cloud environment, like CircleCI for example.
We are in the process of executing our benchmarks in a dedicated environment, using internal infrastructure.
This PR removes benchmarks from our CI runs, as they are not providing much value when executed alongside tests.
=> Disable benchmarks in CI

lib/ddtrace/configuration/settings.rb, spec/ddtrace/configuration/settings_spec.rb
This PR addresses problematic check in setter configuration that disallows using loggers that are not ruby `::Logger` descendants. Current behavior not only doesn't allow using certain loggers (e.g. [`semantic_logger`](https://github.com/rocketjob/semantic_logger) or [`logging`](https://github.com/TwP/logging)) without dirty hacks, but also silently ignores setting value that does not match this validation.
I tried finding common behavior of more popular logging libraries to introduce idiomatic duck-typing instead of  current class comparison, but there doesn't seem to be anything simple enough (apart from validating presence of all methods that `dd-trace` uses) -- commonly found methods `#add` and `#log` are not always present, and they are not always public.
I didn't find any test that …
=> Remove explicit `Logger` class verification

lib/ddtrace/span.rb, spec/ddtrace/span_spec.rb
This PR ensures `Span#pretty_print` is able to handle all valid values it prints.
The required changes were around the span's timing values.
This PR also adds a smoke test to ensure `Span#pretty_print` at least outputs a string without any errors.
The main error we stated seeing
```
NoMethodError:
undefined method `-' for nil:NilClass
```
was actually addressed in a previous PR by @ericmustin, but I remove a few of the safe-guard `rescue` statements from `def duration` when making changes to improve performance. I seek forgiveness with this PR 🙇.
=> Fix Span#pretty_print for empty duration

lib/ddtrace/contrib/sequel/database.rb, spec/ddtrace/contrib/sequel/instrumentation_spec.rb
When instrumenting an application using the `sequel` integration, tracing was failing for a case like the following:
```ruby
query = Sequel.lit("UPDATE foo SET bar = :wat WHERE bar = :var", wat: 2, var: 1)
db.run(query)
```
```ruby
Failure/Error: db.run(query)
NoMethodError:
undefined method `prepared_sql' for #<Sequel::SQL::PlaceholderLiteralString:0x00005585a864c0c0>
```
When using `Sequel.lit` in this context, it returns a `Sequel::SQL::PlaceholderLiteralString`.
This object does not respond to `prepared_sql`, the method expected by `Datadog::Contrib::Sequel::Utils.parse_opts`.
To coerce a `Sequel::SQL::PlaceholderLiteralString` into a `String`, `Sequel::Database#literal` (`Sequel::Dataset#literal`) may be used.
Unfortunately, a duck-type approach for the variety of types the `sql` …
=> Fix Sequel instrumentation when executing literal strings

lib/ddtrace/contrib/sequel/dataset.rb, lib/ddtrace/contrib/sequel/ext.rb, lib/ddtrace/contrib/sequel/utils.rb, spec/ddtrace/contrib/sequel/instrumentation_spec.rb, spec/ddtrace/contrib/support/matchers.rb
While reviewing a recent Sequel PR, I noticed that we did not have coverage for Sequel prepared statements.
This PR adds such coverage, as well as an additional span tag containing the name of the prepared statement. This name is a developer assigned internal alias for the prepared statement, which might be helpful in identifying where the query was stemmed from.
=> Improved prepared statement support for Sequel

lib/ddtrace/profiling/backtrace_location.rb, lib/ddtrace/profiling/events/stack.rb, lib/ddtrace/profiling/pprof/stack_sample.rb, spec/ddtrace/profiling/events/stack_spec.rb
In an effort to improve performance of the profiling exporter, which spends some significant resources on grouping and encoding profiling samples, this pull request caches hash values for `BacktraceLocation` and `Stack` event objects.
In the exporter, profiling samples are compared and grouped where their stacks are identical. To do this, it must compute the hash of each stack, then compare those to decide whether to keep or merge that sample. Computing this hash can be expensive, as it must compile each file & line number of every frame in each stack into a Hash.
Although this pull request doesn't reduce the complexity, it instead aims to amortize the cost, and prevent having to pay it more than once, by computing the hash of `BacktraceLocation` and `Stack` event objects at …
=> Cache hashes for BacktraceLocation and Stack events

lib/ddtrace/opentracer/distributed_headers.rb, lib/ddtrace/propagation/grpc_propagator.rb, lib/ddtrace/sampler.rb, lib/ddtrace/span.rb, lib/ddtrace/utils.rb, spec/ddtrace/distributed_tracing/headers/headers_spec.rb, spec/ddtrace/distributed_tracing/headers/helpers_spec.rb, spec/ddtrace/opentracer/distributed_headers_spec.rb, spec/ddtrace/opentracer/propagation_integration_spec.rb, spec/ddtrace/sampler_spec.rb
Ruby transparently handles small and large integers using the [Integer](https://ruby-doc.org/core-2.5.0/Integer.html) object. Behind the scenes, a number could either be a [Fixnum](https://ruby-doc.org/core-2.2.10/Fixnum.html) or [Bignum](https://ruby-doc.org/core-2.2.10/Bignum.html).
A Fixnum ["Holds Integer values that can be represented in a native machine word (minus 1 bit)"](https://ruby-doc.org/core-2.2.10/Fixnum.html), and thus requiring no auxiliary memory to be represented.
Fixnums are faster to create and manipulate.
The transparent boundary between Fixnums and Bignums, in the positive integer range, is around `2**62`:
```ruby
require 'objspace'
ObjectSpace.memsize_of(2**62-1)
ObjectSpace.memsize_of(2**62)
```
In the tracer, we were generating random span ids up to `2**63`, …
=> Reduce generated Span ID range to fit in Fixnum

docs/GettingStarted.md, lib/ddtrace/contrib/delayed_job/configuration/settings.rb, lib/ddtrace/contrib/delayed_job/ext.rb, lib/ddtrace/contrib/delayed_job/plugin.rb, spec/ddtrace/contrib/delayed_job/plugin_spec.rb
It would be great to monitor delayed_job enqueues in case of any errors or latency related to those events.
Example usage:
```ruby
c.use :delayed_job, {
service_name: "some_service_name-delayed_job",
client_service_name: "some_service_name-delayed_job-client",
analytics_enabled: true,
}
end
```
=> Extend delayed_job plugin

lib/ddtrace/profiling/collectors/stack.rb, spec/ddtrace/profiling/collectors/stack_spec.rb
Instead of using the string table when looping through each sample, we can use it only when we're creating the new `BacktraceLocation`. This is a small optimization that should save a few extra lookups/CPU per sample in the collector thread.
=> Use string table when building BacktraceLocations

CONTRIBUTING.md
We have moved to master-based development a while ago, for neglected to update our `CONTRIBUTING.md`.
This PR addresses that by pointing users to create a PR against this repository's master branch.
=> Update branching guidelines in CONTRIBUTING.md

lib/ddtrace/buffer.rb, spec/ddtrace/benchmark/buffer_benchmark_spec.rb, spec/ddtrace/buffer_spec.rb
This PR extracts behaviour from `Datadog::TraceBuffer` into multiple components that can be assembled together.
These components allow for the construction of custom object buffers that might be required down the line.
There's no change in behaviour in this PR, the contract of `Datadog::TraceBuffer` stays the same.
=> Break down buffer into multiple parts

spec/ddtrace/configuration/settings_spec.rb
We were previously trying to match on `expect_any_instance_of(Kernel)`, which is a very blunt matcher that doesn't work reliably: it failed to intercept mocked method calls depending on test execution order.
This PR changes that matcher to `expect_any_instance_of(Object)`, which seems to behave nicely regardless of our execution patterns.
Overall, `expect_any_instance_of` has many corner cases we've stumbled upon recently, and it has proven flaky ([RSpec team doesn't recommend it either](https://relishapp.com/rspec/rspec-mocks/docs/working-with-legacy-code/any-instance)), but I don't see a better way to this `require` statements like in this test.
=> Fix diagnostic debug settings test

lib/ddtrace/context_provider.rb, lib/ddtrace/tracer.rb, spec/ddtrace/context_provider_spec.rb, spec/ddtrace/tracer_spec.rb
Currently `Datadog.tracer.active_correlation` provides a `Datadog::Correlation::Identifier` for the current thread: it is not possible to obtain the correlation for an arbitrary thread on which a trace might be running.
This pull request allows a key (aka thread) to be provided when the active correlation is accessed, so that the correlation matching that key can be returned. This will be useful for profiling or logging when producing correlations from threads other than the current.
=> Access active correlation by thread

ddtrace.gemspec, docs/DevelopmentGuide.md, spec/ddtrace/benchmark/microbenchmark_spec.rb, spec/ddtrace/benchmark/support/benchmark_helper.rb
This PR adds CPU profiling using [ruby-prof ](https://ruby-prof.github.io/).
All our existing benchmarks only provide deep analysis for memory behavior. This PR introduces a detailed analysis tool to measure application timing.
By default, the results are output in [Cachegrind](https://www.valgrind.org/docs/manual/cg-manual.html) format, and can be analyzed with tools like [KCachegrind or QCachegrind](https://kcachegrind.github.io/html/Home.html).
Here's an example:
When the benchmark runs, instructions are printed on how to get to this colorful screen I posted above.
=> Add detailed CPU benchmark

lib/ddtrace/contrib/grpc/datadog_interceptor/client.rb, lib/ddtrace/propagation/grpc_propagator.rb, spec/ddtrace/propagation/grpc_propagator_spec.rb
gRPC metadata values can be arrays (see https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-metadata.md). In gRPC's Ruby metadata implementation, single metadata values are a singular type, and multiple values come as an array.
This library assumes a single value each time. This PR fixes this assumption to take the first value of an array, like the [Go version](https://github.com/DataDog/dd-trace-go/blob/54b73b3e126a7489ed774c98aadd301488e44123/contrib/google.golang.org/internal/grpcutil/mdcarrier.go#L27).
This bug surfaced a separate bug with dd-trace-go, which [appends values to metadata](https://github.com/DataDog/dd-trace-go/blob/54b73b3e126a7489ed774c98aadd301488e44123/contrib/google.golang.org/internal/grpcutil/mdcarrier.go#L36) rather than setting. If your trace looks …
=> GRPCPropagator: handle metadata array values

lib/ddtrace/profiling/ext/cpu.rb, lib/ddtrace/profiling/ext/cthread.rb, spec/ddtrace/profiling/collectors/stack_spec.rb, spec/ddtrace/profiling/ext/cpu_spec.rb, spec/ddtrace/profiling/ext/cthread_spec.rb, spec/ddtrace/profiling/spec_helper.rb
After adding a [type check](https://github.com/DataDog/dd-trace-rb/pull/1200/files#diff-62e0521325c7c05c2ca53226e748a05eff8619193dcae150f141a90cb6428620R47) in #1200, it became clear that profiling tests would leave the `Thread` in an unclean state. Specifically, `Thread` would be replaced with a duplicate of the original class. Although this was functionally similar to the original `Thread` class object, the `object_id` is different, and this was causing `Thread.current.class == Thread` to evaluate as `false`.
In this pull request, we want to leave the `Thread` constant in a pristine state after a profiling test is complete, so that subsequent tests are consistent and dependable. To do this, we leverage `stub_const` to temporarily replace the `Thread` constant with a copy of `Thread` and …
=> Restore clean Thread class after applying Profiling thread extensions

docs/GettingStarted.md, lib/ddtrace/contrib/rails/patcher.rb, spec/ddtrace/contrib/rails/rails_log_auto_injection_spec.rb, spec/ddtrace/contrib/rails/support/base.rb
This PR addresses https://github.com/DataDog/dd-trace-rb/issues/1205. Since Rails may load lograge's initializer file sequentially _after_ datadog's (Rails loads initializer's alphabetically and datadog's _suggested config_ filename precedes lograge's _suggested config_ filename), we cannot rely on checking `lograge.enabled` to determine whether to patch lograge with our trace correlation code, as it may yield a false negative.
However, since we can _detect_ if the lograge gem has been included in the application (enabled or otherwise), and since setting `lograge.custom_options` (which we need to set as a lambda that attaches our trace correlation context) is a no-op in the case that `lograge.enabled` is, later, explicitly set to `false` after our patching code, we can "naively" add …
=> fix: add improved lograge auto patching support and improve docs

docs/GettingStarted.md, lib/ddtrace/contrib/delayed_job/configuration/settings.rb, lib/ddtrace/contrib/delayed_job/plugin.rb, lib/ddtrace/contrib/que/configuration/settings.rb, lib/ddtrace/contrib/que/tracer.rb, lib/ddtrace/contrib/resque/configuration/settings.rb, lib/ddtrace/contrib/resque/resque_job.rb, lib/ddtrace/contrib/shoryuken/configuration/settings.rb, lib/ddtrace/contrib/shoryuken/tracer.rb, lib/ddtrace/contrib/sidekiq/configuration/settings.rb, lib/ddtrace/contrib/sidekiq/server_tracer.rb, lib/ddtrace/contrib/sneakers/configuration/settings.rb, lib/ddtrace/contrib/sneakers/tracer.rb, spec/ddtrace/contrib/delayed_job/plugin_spec.rb, spec/ddtrace/contrib/resque/instrumentation_spec.rb, spec/ddtrace/contrib/sidekiq/tracer_configure_spec.rb, spec/ddtrace/contrib/sneakers/tracer_spec.rb
**Goal**
Allow passing custom error handler for background job gems. Useful to retry jobs for known transient errors without reporting errors to Datadog.
Example usage:
```ruby
TRANSIENT_ERRORS = [SomeTransientError]
custom_error_handler = proc { |span, error| span.set_tag('error', true) unless TRANSIENT_ERRORS.include?(error.class) }
Datadog.configure do |c| 
c.use :sidekiq, {
error_handler: custom_error_handler
}
end
```
=> Background job custom error handlers

lib/ddtrace/contrib/active_support/cache/instrumentation.rb, lib/ddtrace/contrib/active_support/cache/patcher.rb, lib/ddtrace/contrib/active_support/ext.rb, spec/ddtrace/contrib/rails/cache_spec.rb
In current implementation only `read`, `write` and `fetch` methods of `ActiveSupport::Cache::Store` are instrumented. This PR adds the instrumentation of `read_multi`, `write_multi` and `fetch_multi` methods.
=> Add "multi" methods instrumentation for Rails cache integration

lib/ddtrace/runtime/identity.rb, lib/ddtrace/utils.rb, lib/ddtrace/utils/forking.rb, spec/ddtrace/runtime/identity_spec.rb, spec/ddtrace/utils/forking_spec.rb
There are a number of places in code where we need to detect whether forking has occurred, and conditionally trigger some kind of behavior when it does. (This happens in runtime ID resolution, Resque, trace and runtime metric workers, etc...)
To make this behavior more consistent and generally available, this pull request introduces a small module called `Datadog::Utils::Forking` which adds this functionality. It can be applied at the class/module or instance level. e.g.
```ruby
module Identity
extend Datadog::Utils::Forking
end
class Worker
include Datadog::Utils::Forking
end
```
It then provides `forked?` and `after_fork!` methods that can be used to detect forking:
```ruby
def run
after_fork! { reset! }
do_work
end
```
=> Add Forking helpers

lib/ddtrace/context.rb, lib/ddtrace/context_provider.rb, spec/ddtrace/context_provider_spec.rb, spec/ddtrace/context_spec.rb
When Ruby processes fork, they copy objects from the parent process into the child process: this includes the trace context objects we've assigned to each `Thread`. As a result, child processes are copying all the spans from the parent process, which could result in redundant transmission of spans.
Instead, we'd like forked processes to act like distributed traces; they should be linked to the parent process (trace ID/parent ID/sampling, etc) but only build and transmit spans generated from its own process.
To do this, we're leveraging the forking helpers implemented in #1221 to make the `Datadog::Context` fork aware, then lazily clone the `Datadog::Context` in the `Datadog::DefaultContextProvider` whenever a context is accessed and observed to have forked.
=> Reset trace context after fork

lib/ddtrace/ext/runtime.rb, lib/ddtrace/tracer.rb, spec/ddtrace/tracer_spec.rb, test/tracer_test.rb
In order to distinguish different runtimes within a trace, this pull request adds `runtime-id` tags to the "local root span" (the top most span in a given process.)
```ruby
Datadog.tracer.trace('parent_span') do
Datadog.tracer.trace('child_span') do
fork do
Datadog.tracer.trace('fork_parent_span') do
Datadog.tracer.trace('fork_child_span') do
end
end
end
end
end
```
It's based on the context reset changes in #1225, which adds the necessary auto-clearing of spans after forking.
=> Add runtime ID tag to parent spans

lib/ddtrace/configuration/settings.rb, lib/ddtrace/contrib/rails/patcher.rb, lib/ddtrace/ext/distributed.rb, spec/ddtrace/configuration/settings_spec.rb
This PR addresses https://github.com/DataDog/dd-trace-rb/issues/1226 as well as some residual followup from https://github.com/DataDog/dd-trace-rb/issues/1205.
- It updates environment variables for B3 Header Inject and Extract to fit broader datadog specification and [what's in documentation](https://docs.datadoghq.com/tracing/custom_instrumentation/ruby/?tab=activespan#b3-headers-extraction-and-injection), updating from `DD_PROPAGATION_INJECT_STYLE` and `DD_PROPAGATION_EXTRACT_STYLE` to `DD_PROPAGATION_STYLE_INJECT` and `DD_PROPAGATION_STYLE_EXTRACT`, respectively.
- It also cleans up a case in the rails trace context auto-injection feature where a warning log would occur erroneously.
=> Fix log injection warn logs and b3 env vars

spec/support/container_helpers.rb
When testing container ID detection, we would stub `File.open('/proc/self/cgroup')`, but not `File.exist?('/proc/self/cgroup')`, which we call before reading the file.
This causes the tracer to check if the testing process itself (RSpec) has a `/proc/self/cgroup` file defined. This incidentally works on Linux environment, but is not the intention of the test.
This change also allows tests to run successfully on MacOS.
=> Stub all relevant IO calls for cgroup mocking

lib/ddtrace/contrib/aws/instrumentation.rb, lib/ddtrace/contrib/aws/patcher.rb, spec/ddtrace/contrib/aws/instrumentation_spec.rb
Our current AWS SDK instrumentation labels its spans as `web`, which is used to identify web servers.
This PR changes that span type to `http` instead, which is the type we use for egress HTTP requests. Given the SDK performs remote work on the large majority of its calls, out of all the types we have available, `http` labels the AWS SDK the best.
=> Use correct span type for AWS SDK

lib/ddtrace/ext/profiling.rb, lib/ddtrace/profiling/collectors/stack.rb, lib/ddtrace/profiling/events/stack.rb, lib/ddtrace/profiling/pprof/stack_sample.rb, lib/ddtrace/profiling/transport/http/api/endpoint.rb, spec/ddtrace/profiling/collectors/stack_spec.rb, spec/ddtrace/profiling/events/stack_spec.rb, spec/ddtrace/profiling/integration_spec.rb, spec/ddtrace/profiling/pprof/stack_sample_spec.rb, spec/ddtrace/profiling/spec_helper.rb, spec/ddtrace/profiling/transport/http/adapters/net_integration_spec.rb, spec/ddtrace/profiling/transport/http/api/endpoint_spec.rb, spec/support/container_helpers.rb
We'd like profiles to reference active traces so that we can link between the two.
In this pull request, we leverage the correlation API in #1200 to access the active trace for each thread, add their IDs respectively to each `StackSample`, then serialize these as labels on the pprof file.
=> Add trace ID/span ID to profile labels

lib/ddtrace/contrib/faraday/patcher.rb, lib/ddtrace/contrib/http/instrumentation.rb, lib/ddtrace/contrib/httprb/instrumentation.rb
The default `Datadog::Pin` or `Datadog::DeprecatedPin` created on the `Net::HTTP`, `Faraday` and `http.rb` integrations were erroneously typed as `web`, while they should have been of `http` type.
This actually is a non-issue for most users, as the span type eventually gets overwritten with `http` in all three integrations ([Faraday example](https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/contrib/faraday/middleware.rb#L43)).
Only users that directly manipulate the `Datadog::Pin` or `Datadog::DeprecatedPin` associated with these three integrations are affected. The change from `web` to `http` will provide better classification of the spans by the backend, providing proper categorization in our front-end. There are no changes to the data contained in a tracer or to the …
=> Fix mistyped internal Pin on HTTP clients

lib/ddtrace/contrib/configurable.rb, lib/ddtrace/contrib/configuration/resolvers/pattern_resolver.rb, lib/ddtrace/contrib/excon/middleware.rb, spec/ddtrace/contrib/configuration/resolvers/pattern_resolver_spec.rb, spec/ddtrace/contrib/ethon/easy_patch_spec.rb, spec/ddtrace/contrib/excon/instrumentation_spec.rb, spec/ddtrace/contrib/faraday/middleware_spec.rb, spec/ddtrace/contrib/http/request_spec.rb, spec/ddtrace/contrib/httprb/instrumentation_spec.rb, spec/spec_helper.rb
Updated:
This PR is a first step at addressing https://github.com/DataDog/dd-trace-rb/issues/1204 .
As far as I can tell our multiplexing code that relied on `describes` blocks for http clients was never really functional. It appears that, due to the way our PatternResolver attempts to `resolve` a key, we woulld always "fallback" to `:default` configuration if that `describes` pattern has not yet been added, which leads to methods like `configuration_for?(key)` to _always_ return true. And since `configuration_for?(key)` always returns true when using a PatternResolver, we never add the `describes` pattern to the configurations, instead always just overwriting the default, [seen here](https://github.com/DataDog/dd-trace-rb/pull/1227/files#diff-5404a32ad5b25528f6b0702fa60b7ab6fad0e5883e1604 …
=> Multiplexing fix

lib/ddtrace/configuration/components.rb, lib/ddtrace/configuration/settings.rb, spec/ddtrace/configuration/components_spec.rb, spec/ddtrace/configuration/settings_spec.rb
To make configuration slightly nicer, this pull request effectively renames the `profiling.exporter.timeout` option to `profiling.upload.timeout`.
=> Change `profiling.exporter.timeout` --> `profiling.upload.timeout`

.github/workflows/add-milestone-to-pull-requests.yml
This PR adds a Github Action to automatically tag PRs with the latest milestone, if not milestone was assigned to it.
This should help us streamline our release process, as we normally have to manually do this tagging. There's no complex logic around this tagging that would require human intervention today.
This PR is basic a copy of the Java tracer's action: https://github.com/DataDog/dd-trace-java/blob/v0.67.0/.github/workflows/add-milestone-to-pull-requests.yml
The milestone chosen is the latest created milestone, not the one with the largest semantic number. This is actually very helpful in our case, given we have a 1.0.0 milestone that we don't want to automatically assign PRs to at this point. Luckily, it was created before recent release milestones were created, so PRs will …
=> Actions: Add milestone to merged pull requests

lib/ddtrace/configuration.rb, lib/ddtrace/writer.rb, spec/ddtrace/configuration_spec.rb, spec/ddtrace/contrib/support/tracer_helpers.rb, spec/ddtrace/writer_spec.rb
Fixes #1235 
Changes introduced in release 0.38.0 (#1091) allowed the internal worker instance, held by the `Writer`, to be restarted on demand. This is normally ok, except during a shutdown.
With the introduction of https://github.com/DataDog/dd-trace-rb/pull/1177, in release 0.41.0, the issue has change, as a brand new `Writer` is now created. That new `Writer` is then fed a trace, which triggers the lazy initialization of it's internal worker thread.
This PR prevents the re-creation of components during shutdown, the most relevant one being the `Writer`.
Components are still responsive to method calls after `Datadog.shutdown!` (as to not surface host application errors), but they might not perform their work internally after their resources have been disposed of (e.g. `Writer` will not …
=> Avoid writer reinitialization during shutdown

.github/workflows/create-next-milestone.yml
This PR adds a Github Action to automatically create a milestone for the next release, after the current release milestone is closed.
This PR is basicaly a copy of the Java tracer's action: https://github.com/DataDog/dd-trace-java/blob/v0.68.0/.github/workflows/create-next-milestone.yml
Example of this workflow creating milestone 0.6.0 after 0.5.0 was closed: https://github.com/marcotc/dd-trace-rb/runs/1414428349?check_suite_focus=true#step:5:3
=> Actions: Create next milestone after closing

spec/ddtrace/writer_spec.rb
In https://github.com/DataDog/dd-trace-rb/pull/1248/files#diff-ffc89a0ffd0de70be571ade8e3296d6a96c3126da82421877a6027b533d72773L260-R268, a few RSpec mock setup statements have been refactored.
This ended up leaving `Datadog.configuration.runtime_metrics.enabled` not properly mocked for all example groups in that context.
This PR ensures that `Datadog.configuration.runtime_metrics.enabled` is correctly mocked for all `#write` tests in that test file. This fixes flaky CI issues [like this one](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/2216/workflows/4944530b-4b74-42cf-877c-064abbc19087/jobs/97270/parallel-runs/2?filterBy=FAILED).
=> Ensure consisten configuration in writer test

.simplecov
We have a few files in our repository that are not maintained by us (`lib/ddtrace/vendor/active_record/connection_specification.rb`, `lib/ddtrace/contrib/redis/vendor/resolver.rb`).
Despite that, we have them as "undertested" in our coverage reports.
This PR excludes vendored files from our coverage reports.
=> Skip vendored files in coverage report

docs/GettingStarted.md
This PR expands on the explanation of the `middleware_names` option for Rack.
This option sets the Rack resource name to the last executed Rack middleware, which show match the name of the middleware responsible for handling the request.
The existing description is a bit vague, and can be misinterpreted as enabling the tracing of all Rack middleware layers.
=> Clarify Rack middleware_names option

spec/ddtrace/contrib/mongodb/regression_issue_1235_spec.rb
This PR adds a spec specifically reproducing the crash reported in https://github.com/DataDog/dd-trace-rb/issues/1235.
We've fixed the root cause in https://github.com/DataDog/dd-trace-rb/pull/1248, but we'd like to have a reproducible test case to prevent regressions.
=> Add regression test for MongoDB crash

lib/ddtrace/profiling/collectors/stack.rb, lib/ddtrace/profiling/ext/cthread.rb, lib/ddtrace/profiling/ext/forking.rb, lib/ddtrace/profiling/tasks/setup.rb, spec/ddtrace/profiling/ext/forking_spec.rb, spec/ddtrace/profiling/tasks/setup_spec.rb
The `Kernel#fork` extension introduced for callbacks in #1143 did not cover the scenario in which a `fork` is called without a block. This pull request adds support for this case, and triggers the appropriate callbacks accordingly.
This should address forking & profiler worker restart issues in applications using Unicorn, or others that use `fork` without a block.
=> Support #fork without block

docs/GettingStarted.md
Fixes #1264
This PR updates the required type for the `Datadog::Tracer#trace(start_time:)` option.
The type required is a Ruby [Time](https://ruby-doc.org/stdlib-2.7.2/libdoc/time/rdoc/Time.html) object, while the documentation erroneously requested an `Integer`.
As as follow up, I suggest we move most of this documentation to our published API docs: https://www.rubydoc.info/github/DataDog/dd-trace-rb/Datadog/Tracer#trace-instance_method. This allows us to keep the documentation close to implementation, and prevent information drift between the two.
=> Fix Tracer#trace start_time type documentation

lib/ddtrace/workers/runtime_metrics.rb, spec/ddtrace/workers/runtime_metrics_spec.rb, spec/spec_helper.rb, spec/support/test_helpers.rb
This PR reduces the Runtime Metrics (thread count, global class count, and GC statistics) reporting frequency from every second to every 10 seconds.
Reporting of these values in such fine granularity has a measurable cost, but don't provide enough value to justify the current resolution. Most reporting done across the data collected here span throughout the lifetime of the host application, which can require minutes to hours of data to provide meaningful results.
Additionally, because of the introduction of a new integration tests in this PR, I've also added an Integration Test helper, to allow for easily tagging integration tests and have them only run when appropriate, given their high execution cost.
=> Reduce Runtime Metrics frequency to every 10 seconds

lib/ddtrace/contrib/aws/services.rb
My team at Square uses Datadog for tracing. We currently use the Datadog Ruby SDK to provide metrics for our S3 and DynamoDB integrations. We would like to also use Datadog to provide metrics for our upcoming [Textract](https://aws.amazon.com/textract/) integration. After taking a look at their [Textract SDK](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/Textract.html), it seems like they also use the AWS Seahorse Client to make calls to their endpoints. I figured we can add `Textract` to the list of services traced by Datadog and things should "just work". We were hoping to have metrics like latency and whatnot for Textract in our Datadog AWS dashboard. Currently we see metrics for S3 and DynamoDB.
It seems after I made my change, all main specs are passing:
```
bundle exec rake …
```
=> Add AWS Textract to the list of AWS services Datadog provides traces for

lib/ddtrace/contrib/ethon/easy_patch.rb, lib/ddtrace/contrib/ethon/ext.rb
This string appears to be allocated a lot but can be moved to a constant. This only improves memory for versions below Ruby 2.3 because I belive Ruby has optimizations going forward that allow it to re-use these immutable strings.
=> Make frequently allocated string a constant

.circleci/config.yml, Rakefile, ddtrace.gemspec
After our changelog was _linkified_ in https://github.com/DataDog/dd-trace-rb/pull/1267, we should have mechanisms in place to ensure it stays that way.
This PR adds a Rake task that formats the changelog with the proper GitHub links: `rake changelog:format`.
There's also a new CI that verifies the the changelog was properly formatted prior to release. This jobs runs on release branches, which we name with the pattern `bump_to_version_.*`. If we forget to format the changelog, we'll be reminded by in our version bump PR.
=> Add Rake task to format changelog

.github/workflows/add-milestone-to-pull-requests.yml
Reference issue: https://github.com/WordPress/gutenberg/issues/17324#issuecomment-724784917
Because the GitHub Action runs on our repository, it doesn't have permission to modify a community pull request, as those belong to the original forked repository.
This PR solves that by running the Action in the context of the original repository, by triggering from the `pull_request_target` event, instead of `pull_request`.
=> Action: Fix milestone tagging not working for community PRs

Rakefile, spec/ddtrace/contrib/action_cable/patcher_spec.rb
Previously we'd disabled action_cabled rails6 specs as they were hanging in CI. I can't recreate this locally so trying to trigger in CI again, we've also done some work on the tracer as well as test suite since these were originally disabled that may have resolved the issue (but i doubt it)
https://github.com/DataDog/dd-trace-rb/pull/951
=> Add back actioncable rails6 specs

lib/ddtrace/contrib/configuration/resolvers/pattern_resolver.rb
`Enumerable#find` occurs a penalty because it allocates an Array (because `Set` is internally a hash) - this is very wasteful if the Set is empty. Alternative is make `@patterns` an Array and pay the `contains?` tax at `add` time - open to either.
Profiling of `dd-trace-rb`:
```
allocated memory by location
-----------------------------------
7392  /mnt/airlab/rbenv/versions/2.1.8/gems/gems/ddtrace-0.42.0/lib/ddtrace/span.rb:412
1680  /mnt/airlab/rbenv/versions/2.1.8/gems/gems/ddtrace-0.42.0/lib/ddtrace/span.rb:73
1512  /mnt/airlab/rbenv/versions/2.1.8/gems/gems/ddtrace-0.42.0/lib/ddtrace/contrib/configuration/resolvers/pattern_resolver.rb:12
720  /mnt/airlab/rbenv/versions/2.1.8/gems/gems/ddtrace-0.42.0/lib/ddtrace/span.rb:74
720 …
```
=> Do not use Enumerable#find if Set is empty

docs/GettingStarted.md, lib/ddtrace/contrib/redis/configuration/resolver.rb, lib/ddtrace/contrib/redis/configuration/settings.rb, lib/ddtrace/contrib/redis/ext.rb, lib/ddtrace/contrib/redis/patcher.rb, lib/ddtrace/contrib/redis/quantize.rb, lib/ddtrace/contrib/redis/tags.rb, spec/ddtrace/contrib/redis/quantize_spec.rb, spec/ddtrace/contrib/redis/redis_spec.rb
For security (& memory allocation reasons) we want to disable this as the keys could contain sensitive information. Allow for this to be disabled.
=> Allow ability to disable Redis capturing the args

Appraisals, spec/ddtrace/contrib/sinatra/activerecord_spec.rb
Rails 6.1 introduces dependancies on mysql2 `~> 0.5` that we need to handle appropriately in appraisals. There also appear to be some changes in the way `activerecord` handles connection pools that are causing issues in some of our Mocks, i've hardcoded these tests for now to unblock CI
=> update appraisals for rails 6.1 and hardcode active record defaults

Appraisals
This PR fixes the CI build failure:
```
Failure/Error: Article.count()
FrozenError:
can't modify frozen Hash
```
This happens because there's no hard version requirement in our Appraisal gemfile for the JDBC driver.
This PR ensures that we are using at least the latest version.
=> Use latest JDBC drivers for new versions of Rails

lib/ddtrace/ext/ci.rb, spec/ddtrace/ext/fixtures/ci/jenkins.json
Removes invalid Jenkins URL from CI env detection.
related https://github.com/DataDog/dd-trace-py/pull/1875
=> ext: remove invalid Jenkins URL

.circleci/config.yml
While working on Ruby 3.0, I noticed that our `checkout` CI job didn't perform any meaningful Ruby work. Additionally, all `checkout-2.*` jobs performed the same work: checkout this repo, save files to cache to be restored in `build-2.*` jobs. All cached copies are effectively the same, but we had them as a separate jobs per Ruby version.
This PR removes the standalone `checkout-2.*` jobs and instead performs the builtin `checkout` step. The checkout step takes around 1 second to execute, compared to the existing `checkout-2.*` jobs that take from 15 seconds to over 1 minute.
This replaces these jobs:
With this step on each `build-2.*` job:
=> Simpily git checkout in CI

lib/ddtrace/contrib/httprb/instrumentation.rb, spec/ddtrace/contrib/httprb/instrumentation_spec.rb, spec/support/span_helpers.rb
This PR fixes the negative matching case for our custom error matchers, e.g. `have_error_message` matcher (`is_expected.to_not have_error_message`).
There was one test that had an incorrect assertion: `http.rb` https://github.com/DataDog/dd-trace-rb/blob/774ee8e81380f746bf16e6c5023478c81096b6da/spec/ddtrace/contrib/httprb/instrumentation_spec.rb#L152-L154
This assertion is for the 404 case, which by default is considered an error by our integration. The tracer itself is correctly recording this error, but the test was broke, and was actually asserting that there was **no** error.
=> Fix negative assertion for custom span error matching

spec/ddtrace/buffer_spec.rb
These performance tests are not run in CI (`before { skip('Performance test does not run in CI.') }`), and thus count negatively towards our code coverage report.
This PR skips coverage collection for these performance tests.
=> Ignore coverage report for skipped benchmark tests

docs/GettingStarted.md
This PR documents our support for Ruby 3.0.
It's worth noting that only Rails 6.1 is supported for Ruby 3.0, because of changes to keyword arguments that made older versions of Rails not compatible with Ruby 3.0.
=> Add Ruby 3.0 support to docs

lib/ddtrace/contrib/ethon/easy_patch.rb
I've noticed that `datadog_tag_request` makes multiple calls to `uri` but because it isn't memoized we're re-parsing it 3 times.
=> Memoize URI to cut down multiple parsing

spec/spec_helper.rb
By default, rspec uses the "progress formatter" to output the status
of running our test suite -- this is the one that outputs a single
character for each executed test: ./F/*. This is the correct default
to avoid a deluge of text whenever we run the test suite.
But when developing some specific component, it's common that you run
rspec only for a single spec file. In that case, there's not a lot of
tests so it's nice to switch to the documentation formatter that
prints a nice looking description for each test.
So there's a nice trick that rspec itself adds to the `spec_helper.rb`
when you initialize it on a new project with `rspec --init`, which is
to switch to the documentation formatter only when there's a single
spec file to run.
I claim this gives us the best of both worlds :)
=> Use doc formatter when running a single spec file

spec/ddtrace/profiling/integration_spec.rb
I was running our tests using TruffleRuby to better understand our
codebase, and realized that this test failed because it was relying on
the (arguably wrong) behavior that MRI has where it attributes a call
to a method like `backtrace_locations` to the caller, and not to the
callee.
Specifically, we were using two stacks:
```ruby
[1] pry> stack_one
=> ["/dd-trace-rb/spec/ddtrace/profiling/integration_spec.rb:19:in `backtrace_locations'",
"/dd-trace-rb/spec/ddtrace/profiling/integration_spec.rb:19:in `block (3 levels) in <top (required)>'",
"/ruby-2.7.2/gems/rspec-core-3.10.1/lib/rspec/core/memoized_helpers.rb:317:in `block (2 levels) in let'"]
[2] pry> stack_two
=> ["/dd-trace-rb/spec/ddtrace/profiling/integration_spec.rb:20:in `backtrace_locations'", …
```
=> Minor: Fix test failing on alternative Ruby

lib/ddtrace/configuration/components.rb
The `Scheduler` class already has a `DEFAULT_INTERVAL = 60` which gets
initialized to
`self.loop_base_interval = options[:interval] || DEFAULT_INTERVAL`.
By also setting it in `components.rb`, in practice we would always be
overriding the apparent default in the class itself, which is very
confusing if we ever want to change it.
Thus, let's instead let the class `Scheduler` class rely and
maintain its own defaults.
=> Minor: Remove extra "hidden" default interval

Appraisals
[Breaking changes in `graphql` `1.12.0`](https://github.com/rmosolgo/graphql-ruby/blob/a9a7373a1fbf91cbcc10a1385cc4cf8c2af8254d/CHANGELOG.md#breaking-changes-1) are causing our `master` build to fail, this will block any work in `ddtrace` currently.
This PR unblocks us from doing `ddtrace` work by locking the version of `graphql` until we address changes introduced in `1.12.0`.
At first glance, it seems like extra spans are now produced in our tests, but doesn't seem like anything major.
=> Temporarily lock graphql due to breaking changes

lib/ddtrace/contrib/active_record/utils.rb
When an ActiveRecord event fires an ActiveSupport notification, it can provide the connection object information in two ways: a direct reference to the connection object; an indirect reference, through a `connection_id` number.
The `connection_id` is actually the result of `connection.object_id`, thus directly references the respective connection object.
Today, when receiving only the `connection_id`, we try to iterate over all ActiveRecord connection pools to find an object that matches this id. This is not necessary, as we can directly retrieve the connection from the VM by using `ObjectSpace._id2ref(connection_id)`.
Because the `connection` object is part of the caller stack frame, there's no risk that this object has been garbage collected (possibly making `connection_id` point to a …
=> Direct object_id lookup for ActiveRecord connections

docs/GettingStarted.md, lib/ddtrace/contrib/rack/middlewares.rb, lib/ddtrace/contrib/rack/request_queue.rb
This PR removes the experimental status of the `request_queuing` option for web servers.
This option has been stable for quite a while across multiple production environemtns, thus we are confident that it can be enabled without concern.
=> Promote request_queuing out of experimental

.circleci/config.yml, ddtrace.gemspec
This PR [exports RSpec of test results to CircleCI](https://circleci.com/docs/2.0/collect-test-data/).
This allows CircleCI to properly record and display test failures, instead of us having to dig around the plain text output: (from [Ruby 2.0 test failure](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/2563/workflows/d627ea4b-fa40-47ef-bc75-6ee7f747730f/jobs/107079))
There's also a way to get historically flaky and slow tests, but it's only available [through CircleCI API calls](https://circleci.com/docs/2.0/collect-test-data/). I haven't had the time to do this API work yet, but it's good to start collecting data already for such report.
=> Export RSpec results metadata to CircleCI

.circleci/config.yml
We are currently asking CircleCI to initialize eight different containers that we need to run our tests, but we don't actually wait until their services are ready to process requests.
This hasn't affected us too much, but recently MySQL started taking longer to initialize than our tests take to start running.
This PR waits for service's respective TCP ports to start responding before tests start running:
Notice that 3306, MySQL's port, actually had to wait 3 seconds in this example. Without this wait time, we might have started our tests too early to communicate with this service.
=> Wait for containers to start in CI

Appraisals, spec/ddtrace/contrib/graphql/tracer_spec.rb
`graphql` 1.12.0 [changed the default execution strategy for new schema definitions](https://github.com/rmosolgo/graphql-ruby/blob/v1.12.0/CHANGELOG.md#breaking-changes-1).
This means that, by default, new schema executions will, amongst other changes, perform authorization checks.
These checks generate spans with resource names like such: `Example.authorized`.
These spans existed before this version, but did not come enabled by default.
This PR adds new test assertions for both the old and new execution strategies, given we still support `graphql` older than 1.12.0.
No production change was required: `graphql` 1.12.0 is fully supported by `ddtrace` even without this change.
=> Update tests for GraphQL 1.12.0

spec/ddtrace/contrib/graphql/test_types.rb
We test the `graphql` integration with both class-based and `.define`-style schema definitions.
`.define`-style schema definition is deprecated and will be removed in `graphql` 2.0.
With the progress towards 2.0, some deprecations are being enforced. The deprecated `types.ID` and `types.String` files have been deprecated in 1.12.
This PR updates our test suite to continue testing correctly with `.define`-style schemas.
=> Update deprecated GraphQL types

ddtrace.gemspec
The newest release of msgpack (1.4) is not currently compatible with Ruby 2.0 and 2.1.
This PR locks the msgpack version to < 1.4 until we know if support will be restored and completely dropped for these old rubies.
=> Temporarily lock msgpack version for Ruby 2.0 and 2.1

lib/ddtrace/tasks/exec.rb, spec/ddtrace/tasks/exec_spec.rb
When for some reason `ddtracerb exec` failed, we were just letting Ruby handle it as usual:
```
$ bin/ddtracerb exec does-not-exist
Traceback (most recent call last):
2: from bin/ddtracerb:9:in `<main>'
1: from /Users/ivo.anjo/.rvm/gems/ruby-2.7.2/gems/ddtrace-0.43.0.feature.profiling.98496/lib/ddtrace/tasks/exec.rb:13:in `run'
/Users/ivo.anjo/.rvm/gems/ruby-2.7.2/gems/ddtrace-0.43.0.feature.profiling.98496/lib/ddtrace/tasks/exec.rb:13:in `exec': No such file or directory - does-not-exist (Errno::ENOENT)
```
which is not very user-friendly.
I've taken a bit of inspiration from [`bundler exec`](https://github.com/rubygems/rubygems/blob/dd93966cac224532035deda533cba2685dfa30cc/bundler/lib/bundler/cli/exec.rb#L45) and improved the error messages, as well as outputting the same exit status as …
=> Improve error message and set exit status when ddtracerb fails

lib/ddtrace/profiling/ext/cpu.rb, lib/ddtrace/profiling/tasks/setup.rb, spec/ddtrace/profiling/ext/cpu_spec.rb
When attempting to use our profiler on macOS, I got a cryptic error
message:
```
$ DD_PROFILING_ENABLED=true bundle exec bin/ddtracerb exec ruby -e "1"
[DDTRACE] CPU profiling unavailable. Cause: Function 'pthread_getcpuclockid' not found in [libruby.dylib, libpthread.dylib] Location: /Users/ivo.anjo/.rvm/gems/ruby-2.7.2/gems/ffi-1.14.2/lib/ffi/library.rb:273:in `attach_function'
```
I had forgotten that we didn't support CPU profiling on macOs, and
had to doublecheck this in our documentation.
I thus decided to improve our error message to be as clear as
possible about any limitations:
```
$ DD_PROFILING_ENABLED=true bundle exec bin/ddtracerb exec ruby -e "1"
[DDTRACE] CPU profiling skipped because native CPU time is not supported: Feature requires Linux; macOS is not supported.
```
=> Improve CPU profiling unsupported log message

lib/ddtrace/contrib/redis/vendor/LICENSE, lib/ddtrace/vendor/active_record/MIT-LICENSE
For both the ActiveRecord and the Redis vendored code, we need to include their licenses, because they are under the MIT license which states
> Permission is hereby granted [...] to deal in the Software without
> restriction, including without limitation the rights to use, copy,
> [...] distribute [...] subject to the following conditions:
>
> The above copyright notice and this permission notice shall be
> included in all copies or substantial portions of the Software.
=> Add missing license files for vendor'd code

Appraisals
With the latest release of i18n (`1.8.8`), a bug surfaced when running under JRuby: https://github.com/ruby-i18n/i18n/issues/555
The current recommendation is to stick to `1.8.7` for the time being.
This issue is affecting all commits today, and it looks like this:
```
NoMethodError:
undefined method `deep_merge!' for {}:Concurrent::Hash
/usr/local/bundle/jruby/2.5.0/gems/i18n-1.8.8/lib/i18n/backend/simple.rb:45:in `store_translations'
```
=> Temporarily pin i18n for JRuby

spec/ddtrace/transport/http/adapters/net_integration_spec.rb
When starting webrick in-process in a background thread WITH a fixed port, we need to make sure that the webrick thread has shut down between tests, otherwise a follow-up test can fail with
`Errno::EADDRINUSE: Address already in use - bind(2) for [::]:6218`
due to the main test runner thread being faster at starting the next test case before the old webrick thread has had time to shut down.
In this specific case, there's only a single test case for this file, so this issue would only trigger whenever another test case also uses webrick with a fixed port OR once more test cases are added to this file.
I ran into this because there's a test in the profiling branch that was partially copy-pasted from this one and had exactly the same issue, so I'm fixing the issue on both places.
Tips for …
=> Fix potential flaky test

spec/ddtrace/profiling/transport/http/adapters/net_integration_spec.rb
When starting webrick in-process in a background thread WITH a fixed port, we need to make sure that the webrick thread has shut down between tests, otherwise a follow-up test can fail with
`Errno::EADDRINUSE: Address already in use - bind(2) for [::]:6218`
due to the main test runner thread being faster at starting the next test case before the old webrick thread has had time to shut down.
This is the same issue as fixed in #1350 (both tests are similar).
Tips for hunting down these kinds of issues:
* The `rspec_n` gem (thanks @roberts1000 !) was very useful in running   a given test case multiple times to cause it to trigger
* This specific issue can be triggered really easily by modifying the   webrick sources and adding a `sleep 1` to the webrick shutdown   sequence, thus making sure …
=> Fix flaky test in profiling branch

Gemfile, ddtrace.gemspec, lib/ddtrace/profiling/ext/cthread.rb, spec/ddtrace/profiling/ext/cthread_spec.rb
This incompatible change in Ruby 3.0 is documented in
<https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/>
and the approach used is the one described in
<https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/#a-compatible-delegation>
I believe the `ruby2_keywords` is our best option, because we want to
support all rubies from 2.0 on, so we can't use some of the more modern
alternatives (such as `...`).
For the reviewers: Would it make sense to vendor the `ruby2_keywords`
gem instead of depending on it? The license is
[2-Clause BSD](https://github.com/ruby/ruby2_keywords/blob/master/LICENSE)
so it seems like a reasonable candidate, if we'd prefer to go that
route.
=> [PROF-2807] Fix Thread#initialize patch breaks keyword args in Ruby 3

.circleci/config.yml, Appraisals
In certain situations (example below), when consuming a gem build from
our test builds source, bundler will decide to start pulling A LOT of
metadata, which makes `bundle install` so slow that it just seems to
hang (`bundle install -V` reveals that it's not hung).
@pawelchcki suggested that we try publishing to a new, separate folder,
so that there's less metadata to pull, until we find a real fix.
So let's try it out!
The issue can currently be reproduced using the following `Dockerfile`:
```
FROM alpine:3 AS base
RUN echo -e "source 'https://rubygems.org'\n \
\n \
source 'http://gems.datadoghq.com/prerelease' do \n\
gem 'ddtrace', '0.45.0.feature.profiling.109457' \n\
end \n\
" > Gemfile && \
echo -e "GEM\n\
remote: https://rubygems.org/\n\
specs:\n\
\n\
PLATFORMS\n\
ruby\n\
\n\ …
```
=> Publish profiling gem test builds to separate folder

Gemfile, ddtrace.gemspec
In #1345 I added the `ruby2_keyword` gems (which is maintained by the Ruby VM developers) to provide a compatibility shim that helps us support both Ruby 3.0 and older rubies in the same codebase.
During development of that PR, I discovered that the currently-released version of `ruby2_keywords` (0.0.4 as I write this) was broken for really old rubies -- 2.1 and below.
The good news is that I got in contact with upstream and submitted a PR to fix this, which was merged, but the bad news is that upstream hasn't released the fix yet.
The worse news is because I added '>= 0.0.5' as a dependency in our `gemspec`, this dependency on an unreleased version means that customers in private beta helping us test the profiler just get an error for a missing dependency when they try to import our …
=> Avoid declaring dependency on unreleased version of ruby2_keywords

Appraisals
No longer needed; upstream has released the fix.
=> Revert "Workaround bug in upstream aws-partitions gem that breaks CI for 2.2"

lib/ddtrace/profiling/collectors/stack.rb, lib/ddtrace/profiling/ext/cthread.rb, spec/ddtrace/profiling/collectors/stack_spec.rb, spec/ddtrace/profiling/ext/cthread_spec.rb
When a thread is missing CPU instrumentation due to it being started
before our `Ext::CThread` was applied (or in a way which skips our
custom thread initialization code), the resulting CPU profile will
be incomplete -- it will be missing the CPU timing data from those
threads.
This means that regarding CPU instrumentation, we can be in one of
three cases:
1. CPU instrumentation is available AND every thread is correctly
instrumented
2. CPU instrumentation is available BUT there are threads that are
missing the instrumentation
3. CPU instrumentation is NOT available
Our ideal case is # 1, and then # 3. Being in # 2 is not desirable,
because it means that our profiling data is incomplete, and thus
may lead customers astray or to lose confidence in our results.
This commits adds a detector …
=> Detect and warn about threads without CPU time instrumentation

.circleci/config.yml
Use the [`--dev`](https://github.com/jruby/jruby/wiki/Improving-startup-time#use-the---dev-flag) option for JRuby in CI.
This yields faster startup times in CircleCI:
```
--dev
Benchmark #1: ruby -e ''
Time (mean ± σ):      1.173 s ±  0.059 s    [User: 1.701 s, System: 0.145 s]
Range (min … max):    1.095 s …  1.301 s    10 runs
Benchmark #1: ruby -e ''
Time (mean ± σ):      1.411 s ±  0.073 s    [User: 3.872 s, System: 0.158 s]
Range (min … max):    1.315 s …  1.521 s    10 runs
```
Because our CI suite runs many short-lived instances of Ruby, this reduces the JRuby CI steps execution time by 20-40%.
=> [ci] Faster JRuby startup with dev mode

spec/ddtrace/contrib/sucker_punch/patcher_spec.rb
The newly-released [sucker_punch](https://github.com/brandonhilkert/sucker_punch) 3.0.0 gem includes a few changes to support Ruby 3.0 keyword syntax (see https://github.com/brandonhilkert/sucker_punch/pull/235), but it made our current tests fail in JRuby.
Relevant snippet is (from [this failed run](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/2764/workflows/596c0f11-c7dd-4e89-a36a-78397cc724c6/jobs/112458/parallel-runs/21)):
```
F.E, [2021-02-17T08:12:15.473545 #1277] ERROR -- : Sucker Punch job error for class: '#<Class:0x17abef0f>' args: [:fail, {}]
ArgumentError wrong number of arguments (given 2, expected 0..1)
/app/spec/ddtrace/contrib/sucker_punch/patcher_spec.rb:62:in `perform'
/usr/local/bundle/jruby/2.5.0/gems/sucker_punch-3.0.0/lib/sucker_punch/job.rb:62:in …
```
=> Workaround wrong delegation in sucker_punch triggering JRuby bug

lib/ddtrace/profiling/ext/cthread.rb
To search for `pthread`, FFI goes through the usual folders for system libraries (`/usr/lib`, etc...) and tries to find a file called `libpthread.so`.
This file is then parsed to find out the real name of the library .so -- in this case `libpthread.so.0` -- which can then be `dl_open`ed.
(Curiously enough, on Ubuntu 20.04, libc actually handles this lookup of `libpthread.so` -> `libpthread.so.0` automatically when `dl_open` is called, whereas on Ubuntu 16.04 it doesn't and the FFI gem implements this behavior using regular Ruby code. Nice!)
When the `libpthread.so` file is missing (on Ubuntu, this happens when the `libc6-dev` package is not installed) trying to load `pthread` will fail with the following error:
> LoadError (Could not open library 'pthread': pthread: cannot open shared …
=> Fix failure to load libpthread when development package is not installed

Gemfile, ddtrace.gemspec, lib/ddtrace/profiling/ext/cthread.rb
Inspired by <https://eregon.me/blog/2021/02/13/correct-delegation-in-ruby-2-27-3.html> I've decided to adopt the `respond_to?` approach to only call `ruby2_keywords` on rubies that need it, and thus workaround any issues around needing an unreleased fix to support old Rubies.
=> Drop dependency on ruby2_keywords gem

lib/ddtrace/profiling/ext/cpu.rb, lib/ddtrace/profiling/tasks/setup.rb, spec/ddtrace/profiling/ext/cpu_spec.rb, spec/ddtrace/profiling/tasks/setup_spec.rb
When I initially worked on #1300 ("Warn on incompatible rollbar version") my understanding of the issue on rollbar/rollbar-gem#1018 was incomplete and I did not realize that old rollbar versions, beyond breaking datadog profiler's CPU time instrumentation, could actually break the customer's application.
One of our private beta customers mentioned he had seen both the warning but also had seen a stack trace:
```
[1] ! Unable to load application: SystemStackError: stack level too deep
/usr/local/bundle/gems/rollbar-3.1.1/lib/rollbar/plugins/thread.rb:5:in `initialize_with_rollbar': stack level too deep (SystemStackError)
from /usr/local/bundle/gems/ddtrace-0.45.0.feature.profiling.109457/lib/ddtrace/profiling/ext/cthread.rb:47:in `initialize'
from …
```
=> Skip CPU time instrumentation if incompatible rollbar is detected

lib/ddtrace/configuration.rb, spec/ddtrace/configuration_spec.rb
While experimenting with Ruby profiler, I noticed that sometimes more
than one profiler was being started.
Upon closer investigation, I identified this as a race between the
profiler's sampling thread and the thread that was initializing the
Datadog APM: If initialization of components was not "fast enough",
the Datadog::Profiling::Collectors::Stack would run and try to access
`Datadog.tracer` (stack.rb:140), which would trigger a new
initialization of the components, including starting a second profiler.
This can be triggered reliably by injecting an artificial slow down
into component initialization -- change configuration.rb from
```ruby
def components
@components ||= build_components(configuration)
end
```
to
```ruby
def components
@components ||= build_components(configuration).tap { …
```
=> [PROF-2711] Fix multiple profilers starting in the same process

.circleci/config.yml, integration/apps/rack/README.md, integration/apps/ruby/.dockerignore, integration/apps/ruby/.envrc.sample, integration/apps/ruby/.gitignore, integration/apps/ruby/Dockerfile, integration/apps/ruby/Dockerfile-ci, integration/apps/ruby/Gemfile, integration/apps/ruby/README.md, integration/apps/ruby/agent.yaml, integration/apps/ruby/app/datadog.rb, integration/apps/ruby/app/fibonacci.rb, integration/apps/ruby/bin/run, integration/apps/ruby/bin/setup, integration/apps/ruby/bin/test, integration/apps/ruby/docker-compose.ci.yml, integration/apps/ruby/docker-compose.yml, integration/apps/ruby/script/build-images, integration/apps/ruby/script/ci
This pull request adds a new test application to the integration test suite. This application is a very simple pure Ruby application that computes Fibonacci and produces traces/profiles.
It's intended as a minimalist example of Datadog tracing/profiling in use, and a sandbox in which we can drive some more Ruby-specific scenarios (e.g. threads, Ractors, IO, etc) outside of any framework.
=> Add Ruby integration test app

lib/ddtrace/contrib/aws/services.rb
Hi, I'm using ddtrace AWS integration to be able to track every interaction with AWS services in Datadog.
I've noticed that the calls to EventBridge API seem to be missing though.
I think simply adding `EventBridge` to the list of supported AWS services should enable that tracking.
[aws-sdk-eventbridge](https://github.com/aws/aws-sdk-ruby/tree/master/gems/aws-sdk-eventbridge/lib/aws-sdk-eventbridge) gem uses AWS Seahorse Client (like all the other AWS services), so I reckon it should "just work".
I checked that `:EventBridge` exists in `::Aws.constants`, so it won't get filtered out in https://github.com/DataDog/dd-trace-rb/blob/1343922a2c5fe921c22e1482625f09679db383e5/lib/ddtrace/contrib/aws/patcher.rb#L34
=> Add EventBridge to supported AWS services

spec/ddtrace/profiling/collectors/stack_spec.rb
While running a few experiments with this spec, I ran into a `SystemStackError: stack level too deep` (aka stack overflow) when rspec is trying to pretty print an error failure.
I tracked it down to the usage of `pp` and our mocking of `Thread.current` -- `pp` uses the fiber-local storage of the thread (<https://github.com/ruby/ruby/blob/4e32a4ab81d510b1cb3cd45f7faafc917aa071cc/lib/pp.rb#L121>) which our mock breaks.
By having our mock pass through the required methods, rspec can again print error messages when the test fails for some reason.
=> Avoid stack level tool deep error when spec fails

lib/ddtrace/contrib/rake/instrumentation.rb, spec/ddtrace/contrib/rake/instrumentation_spec.rb
Rake spans were missing many properties when an error was raised in a Rake task.
This happened because we failed to call `annotate_invoke!` and `annotate_execute!` in error scenarios.
This PR ensures annotations happens regardless of the outcome of the Rake task execution. It also increases coverage of the Rake integration, by ensuring that all properties are tested in both the error and non-error path.
=> fix:Fully populate Rake spans on exceptions

docs/GettingStarted.md, lib/ddtrace/contrib/cucumber/configuration/settings.rb, lib/ddtrace/contrib/cucumber/ext.rb, lib/ddtrace/contrib/cucumber/formatter.rb, lib/ddtrace/contrib/rspec/configuration/settings.rb, lib/ddtrace/contrib/rspec/example.rb, lib/ddtrace/contrib/rspec/example_group.rb, lib/ddtrace/contrib/rspec/ext.rb, spec/ddtrace/contrib/cucumber/formatter_spec.rb, spec/ddtrace/contrib/rspec/instrumentation_spec.rb
We don't use this on ci-app backend and it's actually harmful due to some internals it makes use lose some tests that go to APM instead
=> [CIAPP-1198] Remove APP_ANALYTICS from tests instrumentation

spec/ddtrace/benchmark/support/benchmark_helper.rb, spec/ddtrace/context_provider_spec.rb, spec/ddtrace/contrib/qless/instrumentation_spec.rb, spec/ddtrace/contrib/resque/instrumentation_spec.rb, spec/ddtrace/diagnostics/environment_logger_spec.rb, spec/ddtrace/integration_spec.rb, spec/ddtrace/runtime/class_count_spec.rb, spec/ddtrace/runtime/identity_spec.rb, spec/ddtrace/tracer_spec.rb, spec/ddtrace/utils/forking_spec.rb, spec/ddtrace/workers/async_spec.rb, spec/ddtrace/workers/runtime_metrics_spec.rb, spec/ddtrace/workers/trace_writer_spec.rb, spec/support/platform_helpers.rb, test/utils_test.rb
The minor changes in this PR are enough to run both `bundle exec rake spec:main` and `bundle exec rake test:main` on TruffleRuby with only 2 tests failing.
The 2 failing tests are due to https://github.com/oracle/truffleruby/issues/2273 so we'll need an upstream fix for them.
Thanks to @P403n1x87 for pairing with me on this.
=> Get our test suite passing on TruffleRuby

lib/ddtrace/profiling/ext/cthread.rb
Ever since it was added for Ruby 2.1, `rb_nativethread_self()` has always been an alias for `pthread_self()`. This can be observed by running `git blame` on <https://github.com/ruby/ruby/blame/master/thread_pthread.c> -- the method has not changed once in 8+ years.
In TruffleRuby, we can call `pthread_self()` but not `rb_nativethread_self()` so let's just pick the option that works on both MRI and TruffleRuby.
=> Replace rb_nativethread_self with pthread_self

lib/ddtrace/contrib/extensions.rb
Currently if integration fails to load I see the following message:
```
W, [2021-03-02T19:29:57.645910 #57008]  WARN -- ddtrace: [ddtrace] Unable to patch  (Available?: true, Loaded? false, Compatible? true, Patchable? false)
```
I believe it should include name of the integration in the message like this:
```
W, [2021-03-03T17:07:12.203732 #67324]  WARN -- ddtrace: [ddtrace] Unable to patch Datadog::Contrib::Rake::Integration (Available?: true, Loaded? false, Compatible? true, Patchable? false)
```
It gets really confusing if multiple integrations fail to load.
=> Fix failed integration message

lib/ddtrace/configuration.rb, spec/ddtrace/configuration_spec.rb
In #1329 we added locking to component initialization and made sure that the logger method would:
a) not trigger component initialization
b) grab the lock to access the components after components were initialized
Unfortunately, b) has a corner case -- what happens when components are being replaced (e.g. during reconfiguration) if a component being replaced tries to log?
The answer is -- a deadlock:
```
E, [2021-03-01T09:43:26.970633 #18619] ERROR -- ddtrace: [ddtrace]
(lib/ddtrace/configuration.rb:113:in `rescue in block in
safely_synchronize') Detected deadlock during ddtrace initialization.
Please report this at https://github.com/DataDog/dd-trace-rb/blob/master/CONTRIBUTING.md#found-a-bug
Source:
lib/ddtrace/configuration.rb:109:in `synchronize' # <-- boom …
```
=> Fix deadlock when trying to log during component replacement

lib/ddtrace/profiling/collectors/stack.rb, lib/ddtrace/profiling/ext/cpu.rb, lib/ddtrace/profiling/ext/cthread.rb, spec/ddtrace/profiling/collectors/stack_spec.rb, spec/ddtrace/profiling/ext/cpu_spec.rb, spec/ddtrace/profiling/ext/cthread_spec.rb
When a `Thread` is started with either `start` or `fork` (they are aliases), then our `CThread#initialize` patch never gets run and thus these threads are not properly instrumented.
This API is used in Ruby's own built-in `timeout` gem (see <https://github.com/ruby/timeout/blob/14d421252b54027108da183783a7a26d0cf5aac1/lib/timeout.rb#L87>) although I'm not entirely sure how common it is in the community.
The behavior of skipping `#initialize` is by design, but it seems a rather weird API; here's what the docs say:
> Basically the same as ::new. However, if class Thread is subclassed,
> then calling start in that subclass will not invoke the subclass's
> initialize method.
(<https://rubyapi.org/3.0/o/thread#method-c-start>)
To fix this, we introduce a new module, which wraps these two …
=> [PROF-2710] Fix missing instrumentation when using Thread.start/fork

lib/ddtrace/context_provider.rb, spec/ddtrace/context_provider_spec.rb
Thread type checking is very incompatible with some debuggers.
For example, if you are using [Debase](https://github.com/ruby-debug/debase), Thread will be replaced with `Debase::DebugThread` and the type check will fail.
I saw a [commit](https://github.com/DataDog/dd-trace-rb/commit/eebfbc89f73c46052bc76124e70baa7ad222b854) with typecheck added, but I don't feel a strong intention to do it.
Do not remove this guard condition?
=> Remove type check from ThreadLocalContext#local.

.github/workflows/create-next-milestone.yml
Our GitHub action that creates the next milestone failed during the last release: https://github.com/DataDog/dd-trace-rb/runs/2025927681
This happened because we are locked in an old version of one of the actions we use (`WyriHaximus/github-action-next-semvers`).
This PR upgrades that dependency to the latest release, fixing the issue (tested in my fork of `ddtrace`).
The version lock is also changed to using SHA hashes now: this is a [recommendation from the GitHub security team](https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions).
=> [Actions] Upgrade create-next-milestone dependencies

docs/ProfilingDevelopment.md, lib/ddtrace/configuration/components.rb, lib/ddtrace/configuration/settings.rb, lib/ddtrace/profiling/collectors/stack.rb, lib/ddtrace/profiling/preload.rb, lib/ddtrace/profiling/scheduler.rb, lib/ddtrace/profiling/tasks/setup.rb, lib/ddtrace/workers/async.rb, spec/ddtrace/configuration/components_spec.rb, spec/ddtrace/configuration/settings_spec.rb, spec/ddtrace/configuration_spec.rb, spec/ddtrace/profiling/collectors/stack_spec.rb, spec/ddtrace/profiling/preload_spec.rb, spec/ddtrace/profiling/scheduler_spec.rb, spec/ddtrace/profiling/spec_helper.rb, spec/ddtrace/profiling/tasks/setup_spec.rb
Previously, if a customer onboarded via code and forgot to `require 'ddtrace/profiling/preload'` the profiler would still start, but would be missing the CPU and fork extensions.
```ruby
c.profiling.enabled = true
end
```
At least one customer ran into this issue.
To fix this, I've refactored the profiler start code-paths so that the `Setup` task only does extension initialization (does not start the profiler), and then the `Datadog::Components` becomes responsible for calling the `Setup` task as well as starting the profiler.
Because the `Setup` task is now called every time the profiler is starting up, I've added a tiny helper that ensures that it only applies the monkey patches and other setups only once per Ruby VM execution.
I've also …
=> [PROF-2796] Fix profiler starting without extensions

lib/ddtrace/profiling/ext/forking.rb, spec/ddtrace/profiling/ext/forking_spec.rb, spec/ddtrace/profiling/integration_spec.rb
This is a collection of fixes for our profiling-specific specs to make them work on TruffleRuby.
=> Test suite fixes for TruffleRuby support for the profiling branch

lib/ddtrace/profiling/transport/http/client.rb
Sometimes I just stare thinking "is this damn thing on?!", so the answer is using `DD_TRACE_DEBUG=true` and this new amazing log message to confirm that yes, indeed, the damn thing is on.
=> Minor: Add debug log message when sending profiling data

Gemfile
The old `pry-nav` is basically abandoned at this point, see <https://github.com/nixme/pry-nav/issues/35> and <https://github.com/nixme/pry-nav/pull/33> and the README points to `pry-byebug`: <https://github.com/nixme/pry-nav#using-mri-we-recommend-pry-byebug-instead>.
Because of our usual support matrix of old Rubies, I've kept `pry-nav` around for older versions.
I've also added `pry-debugger-jruby`, which is a nicer alternative for JRuby.
This setup works correctly for all Rubies: 2.0 to 3.0, JRuby and even TruffleRuby.
=> Use modern pry/pry-byebug on Rubies that support it

.circleci/config.yml, .circleci/images/primary/Dockerfile-truffleruby-21.0.0, docker-compose.yml, spec/ddtrace/contrib/rails/rails_auto_instrument_spec.rb, spec/spec_helper.rb
Due to the issues documented in #1383 we're not yet ready to run TruffleRuby in our CI, but here's a few more improvements to get us closer to that goal.
=> Add docker setup for TruffleRuby, and a few more bits to get us closer to running TruffleRuby in CI

spec/ddtrace_integration_spec.rb
Our public API can be use permissively across the host application. During the event of a Ruby process shutdown, `ddtrace` will invoke `Datadog.shutdown!` (though an `at_exit` hook) to gracefully flush any pending traces and decommission resources.
When this shutdown happens, internal parts of the tracer won't work anymore (new traces won't be captured), which is acceptable, but we must still ensure that calls out public API methods do not raise errors and still behave predictably during a shutdown. We don't want the tracer to interfere with any of the host application's own shutdown routines by introducing uncertain behavior in our tracer public methods.
This PR ensures that our publicly exposed API does not change their interface, nor raise errors after the tracer has been shutdown.
=> Ensure public apis don't fail after shutdown

lib/ddtrace/configuration.rb, spec/ddtrace/configuration_spec.rb
In #1329, after running into issues where background threads caused the `@components` to be initialized multiple times, we decided to add locking to prevent this from happening.
By design, we forced every access to `@components` to go through a lock (even reads) with the intent that:
1. during configuration (e.g. `@components` was previously `nil`) other    threads would block until the `@components` were available
2. during reconfiguration (e.g. `@components` was not `nil`) other    threads would still block until the new `@components` were available
The first issue we ran into was #1387, where the thread doing reconfiguration could try to access the `@components` (e.g. to log) and ran into a deadlock.
And then in <https://github.com/DataDog/dd-trace-rb/pull/1373#issuecomment-799593022> …
=> Correctly synchronize @components creation and access, third try

lib/ddtrace/runtime/cgroup.rb, spec/ddtrace/runtime/cgroup_spec.rb, spec/support/container_helpers.rb
While working on https://github.com/DataDog/dd-trace-rb/pull/1334, I noticed the test that checks if no file descriptions have been left open was failing intermittently.
This was happening because the Linux cgroups parsing code never closed the `/proc` file it opens. The real-world impact is small, as this file is only open once per application execution and its result cached after that. But there's no reason to keep the file open after its contents have been read.
This PR ensures that the file reading closes the file when it's done.
=> Close /proc/self/cgroup file after reading

spec/support/synchronization_helpers.rb
When a test running under our `expect_in_fork` test helper fails, it creates this output:
```
1) Datadog::Workers::AsyncTraceWriter integration tests forking when the process forks and a trace is written with :async fork policy does not drop any traces
Failure/Error: expect(status && status.success?).to be true
expected true
got false
```
This message unfortunately only tells us that the child process exited with a status non-zero.
This error happens to be a flaky issue today: https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/2998/workflows/5c01a51a-b03d-4bfb-a32d-5015716207df/jobs/120042/parallel-runs/2
This PR captures the STDERR output inside the forked process and reports that output when the fork exists with a non-zero status. I introduced a fake failure (`expect(1).to …
=> Report fork spec failures

spec/ddtrace_integration_spec.rb
Since #1334 was merged, we noticed flaky tests affecting the `master` branch.
This PR unblocks the `master` branch build.
This happens because we don't have a clean `Datadog.configuration` object for each test run.
For this specific case, we want a clean tracer instance for this test, but this value is normally populated from previous runs. Because `Datadog.configuration` has not deep reset feature, we always try to reset parts of it during tests, but we can forget those.
As a follow up, we should always correctly reset the components and configuration between each test run.
=> Fix leaky configuration failure in integration test

lib/ddtrace/configuration.rb, spec/ddtrace/configuration_spec.rb
This PR backports the work done in #1329, #1387 and #1411 in the context of the `feature/profiling` branch to the `master` branch.
I've explicitly kept the merge commits in the history because I think the PR discussions on all three were very relevant. If someone is looking at this in the future, #1373 (never merged) also contains a lot of relevant discussion.
Hopefully the final diff looks reasonably understandable and we can close this chapter for a while.
=> Backport synchronization of @components creation and access to master

lib/ddtrace/configuration.rb
The first time we go to read the `@components`, they were not
previously defined, so we get a warning:
```
lib/ddtrace/configuration.rb:116: warning: instance variable @components not initialized
```
This can be trivially triggered by running
```bash
$ bundle exec ruby -we "require 'ddtrace'; Datadog.tracer"
```
=> Fix "warning: instance variable @components not initialized"

lib/ddtrace/workers/queue.rb, lib/ddtrace/workers/trace_writer.rb, spec/ddtrace/workers/trace_writer_spec.rb
This PR addresses an old, but recently more pronounced flaky test, regarding a `Datadog::Workers::AsyncTraceWriter` test.
This this was trying to wait until the writer had flushed all data, but instead, was waiting until the writer had started processing all traces (by calling `#work_pending?`).
`#work_pending?` is used internally by the writer to know if there are traces queued to be process, thus allowing the tracer to either go on a busy processing loop, or sleep for a short bit. This behaviour describes correctly if "Is there more work to be done next?", which is exactly what it represents, but does not answer "Is all the work done?".
This PR waits for the tracer to completely finish its work before verifying the desired conditions.
There's no impact on the correctness of the …
=> [test] Wait for AsyncTraceWriter to finish sending traces

spec/ddtrace/contrib/rspec/instrumentation_spec.rb
When running a single example in the RSpec integration test suite (e.g. `rspec --example 'RSpec hooks creates span for example'`), I noticed that theses test would fail, but while running the whole file it would pass.
This happened because the RSpec test context created for testing was not completely isolated from the `ddtrace` RSpec test runner. We already isolated `RSpec.configuration`, but we forgot to also isolate `RSpec.world`. This PR does that. This behaviour became more apparent when working addressing issues around configuration leaks between tests.
Also, this PR refactors the code in `spec/ddtrace/contrib/rspec/instrumentation_spec.rb`, as there were a few unused variables and manual span tracking (which is already provided by …
=> Ensure clean environment for RSpec integration tests

lib/ddtrace/profiling.rb, lib/ddtrace/profiling/transport/http/client.rb, spec/ddtrace/profiling/transport/http/client_spec.rb, spec/ddtrace/profiling_spec.rb
The `google-protobuf` gem depends on a native component, and its creators helpfully tried to provide precompiled versions of this extension on rubygems.org.
Unfortunately, for a long time, the supported Ruby versions metadata on these precompiled versions of the extension was not correctly set. (This is fixed in newer versions -- but not all Ruby versions we want to support can use these.)
As an example, if you try to use version 3.6.1 (from 2018) with Ruby 2.7 (released in December 2019) it'll happily install the precompiled version of the gem:
```
$ gem install google-protobuf -v "3.6.1"
Fetching google-protobuf-3.6.1-universal-darwin.gem
Successfully installed google-protobuf-3.6.1-universal-darwin
Parsing documentation for google-protobuf-3.6.1-universal-darwin
Installing ri …
```
=> Gracefully handle google-protobuf require failures

.circleci/config.yml
I've seen a few CI runs fail due to the TruffleRuby build step failing.
A quick investigation seems to point at this being oracle/truffleruby#2294 which is already fixed in master and will be in an upcoming TruffleRuby release, so let's just disable it until the new version comes out.
Issue #1383
=> Temporarily disable building TruffleRuby in CI

lib/ddtrace/contrib/resque/integration.rb
I happened to spot this while reviewing the current implementation.
`MINIMUM_VERSION` was added in 768f560216836a6a71f8a5c829661fc15f540817 but not used and presumably an oversight.
=> Use MINIMUM_VERSION in resque compatible? check

.circleci/config.yml, docker-compose.yml
[PrestoSQL has been rebranded to Trino](https://trino.io/blog/2020/12/27/announcing-trino.html), and recently yanked all their DockerHub images named `prestosql`.
This PR changes our environment to use [`starburstdata` images instead](https://hub.docker.com/r/starburstdata/presto): [Starburst is a Presto enterprise vendor](https://www.starburst.io/).
There were no query syntax changes with this rebranding, but the authentication header changed names, causing all our tests to not be able to authenticate with to the server anymore: https://github.com/treasure-data/presto-client-ruby/issues/64
This prevents use from using [TrinoDB docker images](https://hub.docker.com/r/trinodb/trino), thus why we are using Starburst for now.
We'll be able to revert to official project images when the linked …
=> PrestoSQL renamed Trino

lib/ddtrace/configuration/options.rb, lib/ddtrace/contrib/active_record/configuration/resolver.rb, lib/ddtrace/contrib/httpclient/instrumentation.rb, lib/ddtrace/contrib/httprb/instrumentation.rb, lib/ddtrace/runtime/container.rb
> Makes CI green, alongside https://github.com/DataDog/dd-trace-rb/pull/1429
Rubocop recently changed the existing `Style/RedundantBegin` cop to identify additional cases.
This PR addresses the newly discovered infractors and addresses them.
=> Lint changes for latest Rubocop minor release

.circleci/images/primary/Dockerfile-jruby-9.2-latest, Appraisals
After many version of `mimemagic` being yanked, some older Rails versions were affected.
This didn't affect much of our test environment, as older docker images have the required [`freedesktop.org.xml` database file](https://github.com/mimemagicrb/mimemagic/blob/af5a9b1c5b774e65fd84bd7ca4239a9f3eba2039/ext/mimemagic/Rakefile#L7-L10) available, while recently created ones, like JRuby images, do not.
This PR adds the Debian package `shared-mime-info` to our affected docker images.
This change could theoretically be added to all older docker images, but, from my experience, trying to rebuild, for example, the Ruby 2.0 docker images does not produce the same compatible environment: Debian packages have changed quite a bit since last image build, and some libraries that depend on legacy native …
=> Fix JRuby builds after mimemagic license change

spec/ddtrace/profiling/ext/forking_spec.rb
The `forking_spec.rb` doesn't make sense to run on JRuby, since JRuby does not support the `fork` API, and we had a `skip` to avoid running the test.
But there was a bit of clean-up code in the `around` block that seems to be broken on JRuby 9.2.0.0 (but not on later versions).
The broken part seems to be replacing the `::Kernel` constant:
```ruby
unmodified_kernel_class = ::Kernel.dup
Object.send(:remove_const, :Kernel)
Object.const_set('Kernel', unmodified_kernel_class)
```
This caused an unrelated test in the test suite to later break with
```
NoMethodError: private method `require' called for Kernel:Module
require_relative at uri:classloader:/jruby/kernel/kernel.rb:13
block in Support at /usr/local/bundle/gems/rspec-support-3.10.2/lib/rspec/support.rb:33
block in require_rspec_support …
```
=> Fix broken test due to bug in JRuby 9.2.0.0 by skipping `around` block too

lib/ddtrace/profiling/collectors/stack.rb, spec/ddtrace/profiling/collectors/stack_spec.rb
If the profiler is started for a while, stopped and then restarted OR whenever the process forks, we need to clean up the per-thread cpu time counters we keep, so that the first sample after starting doesn't end up with:
1. negative time: At least on my test docker container, and on the reliability environment, after the process forks, the clock reference changes and (old cpu time - new cpu time) can be < 0
2. large amount of time: if the profiler was started, then stopped for some amount of time, and then restarted, we don't want the first sample to be "blamed" for multiple minutes of CPU time
By resetting the last cpu time seen, we start with a clean slate every time we start the stack collector.
I also did a few clean-ups while I was touching this class and the specs. I've separated …
=> Reset existing cpu time tracking state when starting Stack collector

Gemfile, ddtrace.gemspec, lib/ddtrace/diagnostics/environment_logger.rb, lib/ddtrace/profiling/ext/forking.rb, spec/ddtrace/integration_spec.rb, spec/ddtrace/profiling/ext/cthread_spec.rb, spec/ddtrace/profiling/integration_spec.rb, spec/ddtrace/profiling/scheduler_spec.rb, spec/ddtrace/profiling/tasks/setup_spec.rb
Clean up our changes to `.gemspec`, as well as fix all leaky threads and other misc warnings when running profiling specs.
=> Misc tidying up in profiling branch

spec/ddtrace/workers_spec.rb, spec/ddtrace_integration_spec.rb
`cat `<https://www.youtube.com/watch?v=amYzBQMT4VI>` | sed 's/snakes/flaky tests/' | sed 's/plane/CI/'`
=> Add better error messages when flaky tests fail

lib/ddtrace/sampling/rule_sampler.rb, spec/ddtrace/integration_spec.rb, spec/ddtrace/sampling/rule_sampler_spec.rb
`DD_TRACE_SAMPLE_RATE` controls the global sampling rate of traces in `ddtrace`. This settings was introduced as a newer feature, compared to our default, agent-driven, RateByServiceSampler.
Because `DD_TRACE_SAMPLE_RATE` is implemented using the new RuleSampler (instead of RateByServiceSampler), it has different semantics that affect backend behaviour: RuleSampler sets two new tags (`_dd.rule_psr` and `_dd.limit_psr`) that report application-side sampling rates to the backend for throughput extrapolation (if we sent 10 spans/sec, with a sampling rate of 0.1, the application actually generated 100 spans/sec).
This PR addresses the fact that setting a sampling rate to the new environment variable `DD_TRACE_SAMPLE_RATE` was not sending the required sampling tags.
This PR keeps intact the …
=> Ensure DD_TRACE_SAMPLE_RATE enables full RuleSampler

docs/GettingStarted.md
Since we want to merge the profiling feature into master, but don't want customers to use it until we actually decide to release it, let's temporarily remove all mentions of the feature from the getting started doc.
We can re-add this once we're ready for public beta. And that point, we can revise the documentation to mention <https://github.com/DataDog/dd-trace-rb/pull/1439#discussion_r605026392>, as well as how to configure via code (which is something several of the private beta customers are using).
=> Temporarily remove profiling from getting started doc

lib/ddtrace/buffer.rb
In #1339 I added and tweaked the documentation of several profiler-related classes, but completely missed that the `Buffer` class was used by the profiler but was shared with other components, so my documentation change was actually incorrect.
This reverts that change.
=> Minor: Revert class documentation change

Appraisals, Gemfile
This PR unblocks the build of `ddtrace` since recent updates to `mimemagic`.
Until https://github.com/mimemagicrb/mimemagic/issues/142 is solved, we are pinning `mimemagic` to an older version that still supports rubies <= 2.3.
Also, in order to the build to pass, I've pinned rexml to version < 3.2.5 for Ruby < 2.3, as the latest release does not effectively support these older Ruby runtimes: https://github.com/ruby/rexml/issues/69
=> Pin mimemagic to a working version for Ruby 2.2

.circleci/config.yml
As discussed in <https://github.com/DataDog/dd-trace-rb/pull/1358>, it seems like under certain situations, `bundle install` tries to read A TON of metadata for all the existing prerelease builds, making it seem like `bundle install` just hung.
Initially, we changed this to a `profiling-prelease` for the profiling branch and it solved the issue, and now that we're getting
ready to merge profiling into master, let's permanently adopt a new folder, so that customers trying out prerelease builds don't run into this issue.
=> Publish prerelease builds to prerelease-v2 folder

lib/ddtrace/configuration/components.rb, lib/ddtrace/configuration/settings.rb, lib/ddtrace/ext/profiling.rb, lib/ddtrace/profiling/collectors/stack.rb, spec/ddtrace/configuration/components_spec.rb, spec/ddtrace/configuration/settings_spec.rb, spec/ddtrace/profiling/collectors/stack_spec.rb, spec/ddtrace/profiling/integration_spec.rb
In internal testing with GitLab, as well as in feedback from private beta customers, the default maximum frames sampled from a thread (128) has not been enough for most apps, and it's common to see "broken" flamegraphs where there are a bunch of mismatched stack depths that then don't merge as expected.
So let's do two things:
* Raise it to 400 as a default (I've arrived at this number after observing a few applications that got their stacks cut off; the number of cut frames seems to be between 100 and 300).
Since we dynamically adjust our sampling rate depending on our overhead, I do not expect this to have a big impact on the overhead, but I'll validate this new value along with my ongoing experiments on the reliability environment.
* Make this a configurable toggle, similar to how …
=> Make max frames taken during sampling configurable and raise default to 400

Gemfile, ddtrace.gemspec, lib/ddtrace/profiling/ext/cpu.rb, spec/ddtrace/profiling/ext/cpu_spec.rb
Ffi is needed to enable cpu-time profiling and possibly other features in the future. I want to move it to a real required dependency.
I claim that this has a low impact on our existing customers:
* ffi has been around for a long time (version 1.0.0 was released back in 2010) and has regular fixes and maintenance; the JRuby and TruffleRuby developers are amongst its biggest contributors
* ffi is supported on CRuby, JRuby and TruffleRuby
* ffi is a native extension, **but so is msgpack**, our sole other dependency. msgpack provides only pre-compiled versions for windows (see <https://rubygems.org/gems/msgpack/versions>), which means that any of our customers on Linux/macOS already need to have a working compiler to install it. ffi is in the exact same boat: it provides pre-compiled …
=> Add ffi as a required ddtrace dependency

Appraisals, Gemfile, Rakefile, lib/ddtrace/configuration/components.rb, lib/ddtrace/metrics.rb, lib/ddtrace/workers/runtime_metrics.rb, spec/ddtrace/configuration/components_spec.rb, spec/ddtrace/configuration_spec.rb, spec/ddtrace/metrics_spec.rb, spec/ddtrace/workers/runtime_metrics_spec.rb, spec/ddtrace_integration_spec.rb, spec/spec_helper.rb, spec/support/tracer_helpers.rb
The new version of [`dogstatsd-ruby`, v4.9.0,](https://github.com/DataDog/dogstatsd-ruby/releases/tag/v4.9.0) creates a background thread, which needs to be properly closed by calling the previously existing method `#close`.
In a few parts of our tracer and test suite we fail to call `#close` on all instances of the StatsD client. This PR addresses that.
The configuration of Runtime Metric and Health Metrics components reuse the existing `statsd` client from previous configurations, thus directly manipulating the lifecycle of `statsd`. This doesn't seem like a natural relationship, as the `statsd` client is nested inside the Runtime Metrics Worker object, and trying to manipulate its lifecycle from outside creates a few complications. These are documented inline. This also gives us …
=> Correctly close all StatsD clients

docs/GettingStarted.md, lib/ddtrace/contrib/shoryuken/configuration/settings.rb, lib/ddtrace/contrib/shoryuken/tracer.rb, spec/ddtrace/contrib/shoryuken/tracer_spec.rb
This PR adds the option to configure tagging of Shoryuken jobs with the SQS message body.
I've made it default to `false`, which changes the default behaviour. However, I think this is probably the best option as:
1. This brings the configuration in line with the other job library instrumentations (Sidekiq, Sneakers, Que etc.)
2. It's a secure default (I think it's a reasonable expectation that the SQS message can/will contain sensitive data)
=> Add tag_body configuration option for Shoryuken

.rubocop.yml, lib/ddtrace/tracer.rb, spec/ddtrace/tracer_spec.rb
Extracted from #1390 
This pull request adds a `trace_completed` event that is triggered whenever the tracer completes a trace. It is meant to allow fan-out of traces, such that other things may be done with them (logged to file, emit metrics, etc.) In the future, the writer will subscribe to this event to ingest traces.
=> Add trace_completed event to Tracer

docs/GettingStarted.md
This PR documents the transition from the deprecated [App Analytics](https://docs.datadoghq.com/tracing/legacy_app_analytics/) to [Tracing without Limits™](https://docs.datadoghq.com/tracing/trace_retention_and_ingestion/).
New users are encouraged to enable Tracing without Limits™ in new deployments, as this provides much better control over trace retention and ingestion.
App Analytics users are still supported and encouraged to migrate, but migration might require decisions in the Datadog app around trace retention that can affect billing. Given this, we do not want to emit a deprecation warning to all clients without a concrete actionable, which we don't have at this moment.
Changing the default to enable Tracing without Limits™ would be ideal, but it's a breaking change that affects …
=> Document Tracing without Limits

lib/ddtrace/runtime/container.rb, spec/ddtrace/runtime/cgroup_spec.rb, spec/ddtrace/runtime/container_spec.rb, spec/support/container_helpers.rb
AWS Fargate 1.4 changed its `cgroup` scheme from `/ecs/<arn>/<container-id>` to `/ecs/<container-id>` and the format of the container ID itself, which causes container ID to not be extracted or tagged properly. This pull request detects and fixes this tagging.
=> Fix Fargate 1.4 container ID not being read

spec/spec_helper.rb
While I was chasing down a leaked thread, I gathered a few improvements. These mostly affect tests that finish too fast, my
test case was:
```ruby
RSpec.describe "A short-lived thread" do
it 'lives for a really short while' do
Thread.new { }
end
end
```
Improvements:
* Set the `@caller` before the thread actually starts running. This works fine (we're using a similar construct in the profiler), and ensures that the `@caller` is available from the moment the thread gets created, instead of being a race.
I observed that if a test run too fast, it was possible that `@caller` was not set because the thread still hadn't run by the time the detector started working.
* Call `Thread.pass` whenever a backtrace is not available -- this tries to give newly-created threads a chance to run, so that we …
=> Improve leaked thread detector

Rakefile, lib/ddtrace/configuration/components.rb, lib/ddtrace/profiling.rb, lib/ddtrace/profiling/collectors/stack.rb, lib/ddtrace/profiling/ext/cpu.rb, spec/ddtrace/configuration/components_spec.rb, spec/ddtrace/profiling/ext/cpu_spec.rb, spec/ddtrace/profiling/integration_spec.rb, spec/ddtrace/profiling_spec.rb
We've decided not to support Ruby 2.0 in the first release of the profiler.
I've piggy-backed on the existing mechanism for only loading the profiler if it is supported, and thus, on Ruby 2.0 is never even loaded (allowing us to use 2.1 features in code).
This also enables us to simplify the CPU extension support: we no longer have to separately check if we're on 2.1 or not, and we can now assume that if the extension is being loaded, then we're on a supported Ruby version.
I've tested that `ddtracerb exec` also continues to work correctly on 2.0 (it just doesn't start profiling, even if you try to
enable it).
Note: This will need a rebase once the CI madness is fixed, but otherwise should be considered complete.
Tip: The diff has some indentation level changes; hiding whitespace makes …
=> Set Ruby 2.1 as minimum version supported by Profiler

lib/ddtrace/ext/profiling.rb, lib/ddtrace/profiling/transport/http/api/endpoint.rb, spec/ddtrace/profiling/transport/http/adapters/net_integration_spec.rb, spec/ddtrace/profiling/transport/http/api/endpoint_spec.rb
This behavior is already present in both the Python and Go profilers, and can be quite useful when understanding services that employ multiple processes.
=> Include process pid when reporting profile

.rubocop.yml
Upstream dropped support for Ruby 2.4, so we need to disable a few cops that require 2.5.
=> Fix broken linting after upstream release

docs/GettingStarted.md
While looking for guidelines on `RestClient`'s integration, found that one of the references on it has a broken anchor and this is only a fix on it.
Regards,
Kex
=> Fix anchor in README.md

lib/ddtrace/profiling/ext/cthread.rb, spec/ddtrace/profiling/collectors/stack_spec.rb, spec/ddtrace/profiling/ext/cthread_spec.rb, spec/ddtrace/profiling/spec_helper.rb, spec/support/synchronization_helpers.rb
In Ruby versions 2.3 to 2.6, there's a very special subclass of `Thread` called `Process::Waiter` that causes VM crashes whenever something tries to read its instance variables. This subclass of thread only shows up when the `Process.detach` API gets used.
In this case the "something that tries to read its instance variables" is our stack sampler, which was trying to read the `native_thread_id` from one such instance.
I've reported this issue upstream https://bugs.ruby-lang.org/issues/17807 .
To workaround this issue, I've added a check if the instance variable exists before reading it, and validated it works with all affected Ruby versions (as well as adding regression tests for it all).
=> Workaround Ruby segfault when reading instance variable from Process::Waiter

lib/ddtrace/profiling/scheduler.rb, lib/ddtrace/workers/loop.rb, spec/ddtrace/profiling/integration_spec.rb, spec/ddtrace/profiling/scheduler_spec.rb, spec/ddtrace/workers/loop_spec.rb
Note: _This PR is an alternative to #1462. I think both approaches are reasonable and solve the issue, although having done this one, I think I like it a bit more than the other. On the other hand, the other only modifies the one specific profiling class where we need this behavior, whereas this one modifies a core class to add a behavior that effectively has a single customer right now. Hence, I opened a separate PR so that it's easy to compare both approaches and pick one._
When a scheduler starts, it immediately tries to report a profile, which is incorrect, because there's nothing to profile yet.
In most cases, we avoided this incorrect report because we checked if the recorder had anything to report, and skipped it whenever the recorder was empty.
BUT, ever so often, and because both …
=> Avoid immediately reporting profile after start (alternative to #1462)

lib/ddtrace/runtime/container.rb, spec/ddtrace/runtime/container_spec.rb
Fixes #1475 
Our container parsing code was raising an error when encountering cgroup paths that weren't in containerized environments; although the defensive measure in place was working as intended, this pull request prevents that error and makes CI assert no such error is raised.
=> Fix CGroup parsing for non-containerized environment.

lib/ddtrace/profiling/profiler.rb, lib/ddtrace/profiling/recorder.rb, lib/ddtrace/profiling/scheduler.rb, spec/ddtrace/profiling/recorder_spec.rb, spec/ddtrace/profiling/scheduler_spec.rb
The `#work_pending?` callback is used to signal to `Datadog::Workers::IntervalLoop` when there is more work to be done.
During shutdown, when `#stop` is called on the `Scheduler`, this flag is used to determine if there is still work to do before `Scheduler` stops.
Thus, by correctly setting it to reflect the state of the recorder, we ensure that on application shutdown, any pending events are still reported; previously they would just be dropped.
Finally, the `#work_pending?` also needs to take into account the `#skip_next_flush?` so that we still preserve the behavior introduced in #1462 where we want the first `#flush_event` to always execute, but do nothing.
(Note: Current base branch is `fix/avoid-flush-after-start` since this builds off the change in #1462)
=> Ensure profile gets reported on application shutdown

spec/ddtrace/profiling/ext/cthread_spec.rb
It seems that sometimes the signal can also be SEGV, not just ABRT, see
<https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/3305/workflows/79cd1d5d-75a2-410e-b91a-1634ed39c6f5/jobs/131082>.
So let's extend this test to avoid flakiness.
=> Fix flaky test in cthread_spec.rb

.rubocop.yml, lib/ddtrace/contrib/action_pack/action_controller/instrumentation.rb, lib/ddtrace/contrib/action_pack/utils.rb, spec/ddtrace/contrib/action_pack/action_controller/instrumentation_spec.rb
When running ActionPack standalone (without Rails), ActionController instrumentation may raise `undefined method 'starts_with?'` when processing requests. This bug was discovered when running the Rails test suite with Datadog tracing enabled.
This occurs because `starts_with?` is an ActiveSupport function, which may not be available. This pull request changes the function to `start_with?` which is the Ruby core library version, so it should be available outside Rails as well.
This bug was not caught earlier because we have a gap in our test coverage over this controller instrumentation. This pull request tests for this specific bug, but does not fully address that gap: something we will want to do soon, possibly accompanying a refactor of the instrumentation itself.
=> Fix ActionPack instrumentation #starts_with? error

.gitignore
Some of our builds create a strange emtpy file, `gemfiles/_.gemfile.lock`: https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/3317/workflows/cb87c676-8e05-4c41-a67c-24b779e08d0a/jobs/131458:
```
Gem lock files were modified or new lock files were created during
'bundle install' and 'bundle appraisal install' installation in CI.
You need to check in those changes in your branch.
Affected files:
?? gemfiles/_.gemfile.lock
```
I have not been able to reproduce the CI steps that create this file, and removing it from CI cache prevent it from be recreated for a while.
This file has always been empty, and I see no references in `ddtrace` or Appraisal source code that could create a `_` gemfile, specially one with no content.
Because we check for changes to `gemfiles` during CI, to …
=> Ignore appraisal empty artifact

lib/ddtrace/configuration/agent_settings_resolver.rb, lib/ddtrace/configuration/components.rb, lib/ddtrace/ext/transport.rb, lib/ddtrace/tracer.rb, lib/ddtrace/transport/http.rb, lib/ddtrace/workers/trace_writer.rb, lib/ddtrace/writer.rb, spec/ddtrace/configuration/agent_settings_resolver_spec.rb, spec/ddtrace/configuration/components_spec.rb, spec/ddtrace/integration_spec.rb, spec/ddtrace/tracer_spec.rb, spec/ddtrace/transport/http_spec.rb, spec/ddtrace/workers/trace_writer_spec.rb, spec/ddtrace/writer_spec.rb
After getting reports from two customers that had tracing working, but no profiles, I discovered those customers were running into issues because they had the agent settings configured via code.
Currently, if you configure your agent via the `DD_AGENT_HOST` and `DD_TRACE_AGENT_PORT` environment variables, these settings are shared by both the tracer as well as the profiler. So for such a customer, adding the profiler would be as easy as enabling it + adding any needed dependencies.
BUT, if you configure your agent using code, e.g.
```ruby
Datadog.configure { |c| c.tracer.hostname = 'some-hostname' }
```
then as the code hints at, this setting is ONLY for the tracer. In such a case, customers would need to also provide separate configuration for the profiler as well (currently something …
=> [PROF-3118] Refactor reading agent settings into separate class

lib/ddtrace/runtime/container.rb, spec/ddtrace/runtime/cgroup_spec.rb, spec/ddtrace/runtime/container_spec.rb, spec/support/container_helpers.rb
Adds support for:
- k8s burstable containers (drops `.slice` and `.scope` from IDs)
- Gnome VTE cgroup
- More defensive behavior against empty cgroup paths.
Also includes some minor refactoring for tests and a slightly more permissive expectation (so it doesn't break with `pry`.)
=> Fix container parsing for k8s cgroup

lib/ddtrace/configuration/components.rb, lib/ddtrace/configuration/settings.rb, lib/ddtrace/profiling/transport/http.rb, spec/ddtrace/configuration/components_spec.rb, spec/ddtrace/configuration/settings_spec.rb, spec/ddtrace/profiling/transport/http/adapters/net_integration_spec.rb, spec/ddtrace/profiling/transport/http_spec.rb, spec/ddtrace/transport/http_spec.rb
Following the refactoring on #1478 that introduced the `AgentSettings` object and wired the tracer up to use it, we now also make the profiler use the same object.
This also means the deprecation of `c.profiling.exporter.transport_options` that some private beta customers had to use to be able to match their profiler and tracer configurations (whenever they were configuring them via code).
It also means that temporarily, and until global agent settings such as `Datadog.configure { |c| c.agent_hostname = ... }` are introduced, that the only way to configure the profiler via code is through the tracer configurations (e.g. `c.tracer.hostname` and friends). I claim that this is an acceptable trade-off for beta and we can clean it up separately (e.g. by adding these settings to the …
=> [PROF-3118] Wire up profiler to use `AgentSettings` object for configuration

benchmarks/profiler_sample_loop.rb, lib/ddtrace/profiling/collectors/stack.rb, lib/ddtrace/profiling/recorder.rb
I spent a bit of time checking for low-hanging fruit in the main sampling loop, using the simple benchmark attached.
As a result of these improvements, in my machine (Ruby 2.7.3/macOS 10.15.7/i7-1068NG7) I get a 1.68x speedup on samples/s:
```
stack collector before
233.553  (± 6.0%) i/s -      2.346k in  10.084525s
stack collector after
392.156  (± 6.4%) i/s -      3.939k in  10.092307s
```
Of course, during the normal work of the profiler, we don't sample "as fast as possible", but lowering the amount of work we do to take every sample goes towards minimizing the impact we have on the profiled application.
=> Profiler sampling loop performance improvements

ddtrace.gemspec, lib/ddtrace/contrib/sucker_punch/instrumentation.rb, lib/ddtrace/version.rb, spec/ddtrace/contrib/sucker_punch/patcher_spec.rb
The kwargs separation change for Ruby 3.0 is tricky: there are different behaviours on 2.6, 2.7, and 3.0. While `ruby2_keywords` attempts to smooth that out, it is due to disappear on 3.2, therefore relying on it produces surefire broken code when 3.2 is released and 2.6 EOL'd.
`ruby2_keywords` also suffers from subtle brokenness by virtue of leveraging an internal stateful flag attached to the hash. This is generally OK for very local uses but gets troublesome with complex delegations and even more for instrumentors. Case in point, attempting to use `ruby2_keywords` here works for `perform_in` and `perform_async`, but does not solve the issue in the `__run_perform` direct call case.
Thus the only future-proof and reliable syntax on Ruby >= 3 is to capture the arguments with `*args, …
=> Fix kwargs passing on Ruby 3.0 for sucker_punch

lib/ddtrace/error.rb, spec/ddtrace/error_spec.rb, spec/ddtrace/span_spec.rb
Fixes #1265 
This PR changes the format of Ruby exceptions reported in `ddtrace` spans to match the latest default language format.
`ddtrace` will now include all exception causes and format the output to exactly match the Ruby native format, introduced in Ruby 2.6.
```ruby
def root
raise 'root cause'
end
def wrapper
root
rescue
raise 'wrapper layer'
end
wrapper
```
The stack trace order was reversed between Ruby 2.5 and 2.7, but `ddtrace` will follow the current Ruby 3.0 format, using natural ordering on all Ruby versions supported.
For recent Ruby versions (>= 2.6), the output is retrieved from a single VM call (`Exception#full_message`), thus incurring a much lower cost compared to the backported versions for Ruby < 2.6.
Ruby 2.0 does not support `Exception#cause`, thus this change …
=> Add cause to error stack trace

lib/ddtrace/error.rb, spec/ddtrace/error_spec.rb
Raise a new TypeError when handling an exception class that returns an nil message.
Changed to always treat exception message as String.
The actual case is as follows.
```
require 'bundler/inline'
gemfile do
source 'https://rubygems.org'
gem 'ddtrace', '0.49.0', require: 'ddtrace'
gem 'thrift', require: 'thrift'
end
class SomethingException < Thrift::Exception
include Thrift::Struct
FIELDS = {}
def struct_fields; FIELDS; end
Thrift::Struct.generate_accessors self
end
begin
Datadog.tracer.trace('SomethingException') do
raise SomethingException
end
rescue SomethingException => e
p 'nice catch!', e.message
end
```
=> Fixed an issue where backtrace handling of exception classes that return nil message fails.

lib/ddtrace/profiling.rb, spec/ddtrace/profiling_spec.rb
On environments where protobuf is already loaded, we skip any interaction with `Gem.loaded_specs`. This allows us to support customers that don't load gems using rubygems but still have all the needed dependencies.
This is similar to
https://github.com/teamcapybara/capybara/commit/caf3bcd7664f4f2691d0ca9ef3be9a2a954fecfb
The change is quite small so I think it's worth it.
=> Skip Gem.loaded_specs calls if protobuf is already loaded

spec/ddtrace_integration_spec.rb
The leaky file description and leaky thread test has been flaky for JRuby for a while.
Because it depends on a clean test application of virtually all our test suite, it's easy to have this test assert that the expect file descriptors after shutdown are miscounted.
This PR disables it until we have the bandwidth for perform a thorough investigation.
This PR unblocks all builds (including master) from flaky failures.
=> Temporarily disable graceful shutdown tests for JRuby

lib/ddtrace/metrics.rb, spec/ddtrace/metrics_spec.rb
this pr addresses https://github.com/DataDog/dd-trace-rb/issues/1505. Within the core tracer we should generally try to avoid `Gem.loaded_specs` if a known libraries version constant exists, as `loaded_specs` may not work depending on how the user is using Rubygems.
This work builds on top of https://github.com/DataDog/dd-trace-rb/pull/1506 and the next step here would be to add fallback code, where possible, for each contrib integration. Doing this repeatedly would be a chore so it's preferable to have a helper class for this that safely checks the version constant, maybe something like
```
module Datadog
module Utils
module Gem
module_function
def loaded_specs_present?(gem_name = '', &block)
begin
Gem.loaded_specs[gem_name] || block.call
rescue NameError, ArgumentError
end
end
def …
```
=> Add loaded specs fallback

lib/ddtrace/profiling/tasks/setup.rb, spec/ddtrace/profiling/tasks/setup_spec.rb
It seems like saying:
> [DDTRACE] CPU profiling skipped because native CPU time is not supported: Feature requires Linux; macOS is not supported.
is generating a bit of confusion on what users should expect. This PR changes it to:
> [DDTRACE] CPU time profiling skipped because native CPU time is not supported: Feature requires Linux; macOS is not supported. Profiles containing Wall time will still be reported.
to hopefully clarify to users that they're on the right path and they'll still get profiles.
=> Clarify in warning that wall time profiles are still available when CPU time is not

.circleci/config.yml, .gitignore
Since #1470, we have all Appraisal gemlock available at git checkout time.
This allows us to know precisely if the restored bundle cache contains all the gems we need to run our CI workflow.
This reduces the CI `build` steps execution time by **62%: from 69s to 25s on average.**
Before, we had to use the heuristics to get the best possible cache key after checkout, but we still had to always perform `bundle install` and `bundle exec appraisal install` regardless of the restore cache completeness, we we could not be sure of an exact match.
`bundle install` is relatively fast, but `bundle exec appraisal install` is not, even when all gems are present locally.
This PR uses the already existing `bundle_checksum`, which is calculated based on the content of all our gemfile locks …
=> Skip bundle install when cached gems match exactly

docs/GettingStarted.md
Add profiler user documentation: an intro, a link to the getting started docs, as well as the workaround needed for resque.
=> Profiler user docs

.circleci/images/primary/Dockerfile-truffleruby-21.1.0, docker-compose.yml, spec/ddtrace/error_spec.rb, spec/ddtrace/profiling/ext/cthread_spec.rb, spec/ddtrace/profiling/integration_spec.rb
I took a look at the current state of adding TruffleRuby to our test suite.
I found out two new issues (https://github.com/oracle/truffleruby/issues/2356 and https://github.com/oracle/truffleruby/issues/2359) and updated the list on #1383 of things that prevent our test suite from passing on TruffleRuby.
Again I keep being amazed how most of it passes, without excluding large parts of it like we do for JRuby.
=> Bump TruffleRuby docker images to latest version, and a few more test suite fixes

.rubocop.yml, benchmarks/profiler_submission.rb, lib/ddtrace/profiling/pprof/builder.rb, lib/ddtrace/profiling/pprof/stack_sample.rb, lib/ddtrace/utils/object_set.rb, spec/ddtrace/profiling/integration_spec.rb, spec/ddtrace/profiling/pprof/builder_spec.rb, spec/ddtrace/profiling/pprof/stack_sample_spec.rb, spec/ddtrace/profiling/spec_helper.rb
A second round of performance improvements to pprof encoding. Compared to dd-trace-rb 0.49.0, there's a 3.7x speedup, or 2.27x speedup when comparing with current master.
This takes care of the low-hanging fruit I could identify in pprof encoding.
```
exporter objectset-yield
10.028  (± 0.0%) i/s -    101.000  in  10.079207s
Comparison:
exporter objectset-yield:       10.0 i/s
exporter locations-avoid-method-missing:        9.9 i/s - 1.01x  (± 0.00) slower
exporter locations-hashmap:        9.2 i/s - 1.09x  (± 0.00) slower
exporter cached-build-location-v2 (current master):        4.4 i/s - 2.30x  (± 0.00) slower
exporter baseline (before any work):        2.7 i/s - 3.72x  (± 0.00) slower
```
=> More profiler pprof encoding performance improvements

lib/ddtrace/profiling/ext/cthread.rb, spec/ddtrace/profiling/ext/cthread_spec.rb
[Process.clock_gettime](https://ruby-doc.org/core-2.1.0/Process.html#method-c-clock_gettime) is now available for all supported versions of Ruby.
This PR removes conditional checks for its presence.
=> Remove conditional checks for Process.clock_gettime

.rubocop.yml, lib/ddtrace/configuration/base.rb, lib/ddtrace/configuration/settings.rb, lib/ddtrace/contrib/aws/patcher.rb, lib/ddtrace/diagnostics/environment_logger.rb, lib/ddtrace/runtime/metrics.rb, lib/ddtrace/tracer.rb
This PR uses [`Array#to_h`](https://ruby-doc.org/core-2.1.0/Array.html#method-i-to_h), instead of `Hash[array]`, as this method is available since Ruby 2.1.
`Array#to_h` has cleaner syntax, is much faster with empty arrays, and is slightly faster with populated arrays:
```ruby
require 'benchmark/ips'
arr = []
a16 = 16.times.map{|i|[i.to_s.to_sym, 'test']}
Benchmark.ips do |x|
x.config(time: 2, warmup: 0.1) if x.respond_to? :config
x.report('empty array: Hash[A]') { Hash[arr] }
x.report('empty array: A.to_h ') { arr.to_h }
x.report('16 elements: Hash[A]') { Hash[a16] }
x.report('16 elements: A.to_h ') { a16.to_h }
x.compare!
end
```
=> Use Array#to_h instead of Hash[array]

integration/apps/rack/script/ci, integration/apps/rails-five/script/ci, integration/apps/ruby/script/ci
Currently, when you manage to make a change that passes all unit tests, but fails only on our `integration/apps` tests, it's hard to know what the failure is as the error logs are not reported in CI.
This PR prints out the container logs for the `integration-tester` container when execution fails.
=> Print logs on integration app run failure

docs/GettingStarted.md
Let's advise to pin to `dogstatsd-ruby` to v4.x until https://github.com/DataDog/dogstatsd-ruby/issues/182 is fixed.
=> Pin `dogstatsd-ruby` to v4 while we adapt the compatibility with the dogstatsd-ruby companion thread.

lib/ddtrace/profiling/scheduler.rb, lib/ddtrace/workers/async.rb, lib/ddtrace/workers/polling.rb
When a Ruby process is about to finish, ddtrace has an `at_exit` hook to shut down any ongoing work.
In the case of the profiler, if it was working, the profiler will try to report the current profiling data as part of that shut down.
We need to be very careful with these kinds of "extra work items during shutdown" as we don't want to make it appear that
applications "hang". Thus, we enforce a strict timeout of 1 second -- see `SHUTDOWN_TIMEOUT` in `Datadog::Workers::Polling`.
But this whole mecanism was quite confusing, as even with `DD_TRACE_ENABLED` customers would see either:
```
DEBUG -- ddtrace: [ddtrace] (/Users/ivo.anjo/datadog/third-dd-trace-rb/lib/ddtrace/profiling/profiler.rb:19:in `shutdown!') Shutting down profiler
DEBUG -- ddtrace: [ddtrace] …
```
=> Improve debug logging for worker termination during shutdown

lib/ddtrace/contrib/active_support/cache/redis.rb, lib/ddtrace/contrib/qless/patcher.rb, lib/ddtrace/contrib/sucker_punch/exception_handler.rb, lib/ddtrace/opentracer.rb, lib/ddtrace/profiling/ext/forking.rb, spec/ddtrace/contrib/rails/support/rails3.rb, spec/ddtrace/profiling/ext/forking_spec.rb, spec/support/synchronization_helpers.rb
Quite a few of our `class_eval` and `class_eval + class << self` statements were due to not having access the previously private #prepend or #include methods.
This PR cleans up such usages.
Not all occurrences across the code base were converted, as some performed other operations (e.g. defining methods inside the `class << self` block). This PR touches the ones that are safe to do so, with minimal refactor.
=> Clean up singleton class eval statements

lib/ddtrace/error.rb, spec/ddtrace/error_spec.rb
The implementation of nested error reporting in #1472 had a bug in which it did not correctly visit the full `#cause` error chain in the reported exception, only the first cause was reported.
This PR correctly navigate the whole cause chain and reports such information.
=> Nested error reporting not walking clause chain

lib/ddtrace/profiling.rb, lib/ddtrace/profiling/tasks/setup.rb, spec/ddtrace/profiling/tasks/setup_spec.rb
Before #1391, the `Datadog::Profiling::Tasks::Setup` task was run before the gem logger was initialized/available, and thus the class was made to use `puts` for its logging needs.
But since the refactor in #1391, this is no longer the case -- this task is now called by `Datadog::Configuration::Components#build_profiler` and thus we can safely make use of the logger and get rid of any custom logging specific to this class.
=> [PROF-3430] Get rid of puts logging during profiler initialization

lib/ddtrace/profiling/collectors/stack.rb, spec/ddtrace/profiling/collectors/stack_spec.rb
A customer was a bit misled by seeing this message in their logs (e.g. it led them to believe CPU time profiling was not working).
This debug message is still useful for our own debugging so I've left it, but I've reworded it to clarify that seeing this message is mostly harmless.
=> Tweak debug message about missing instrumentation

lib/ddtrace/profiling/collectors/stack.rb, lib/ddtrace/profiling/ext/cthread.rb, spec/ddtrace/profiling/ext/cthread_spec.rb
Ruby 3.1 has introduced their own `Thread#native_thread_id` (see <https://bugs.ruby-lang.org/issues/17853>) which differs from the `pthread_self()` we're using here.
This means that our `CThread` monkey patch would conflict with the upstream behavior due to a name collision.
To avoid this issue, I just did a global find-and-replace on the codebase to rename all usages of `#native_thread_id` with
`#pthread_thread_id`.
I have some ideas on how to get rid of the need to monkey patch `Thread` in the future, so hopefully at some point we'll just be able to delete these monkey patches.
=> [PROF-3461] Rename Thread#native_thread_id to #pthread_thread_id to avoid conflict with Ruby 3.1

lib/ddtrace/profiling/encoding/profile.rb, lib/ddtrace/profiling/pprof/converter.rb, lib/ddtrace/profiling/pprof/stack_sample.rb, lib/ddtrace/profiling/pprof/template.rb, lib/ddtrace/workers.rb, lib/ddtrace/workers/async.rb, spec/ddtrace/profiling/encoding/profile_spec.rb, spec/ddtrace/profiling/pprof/converter_spec.rb, spec/ddtrace/profiling/pprof/stack_sample_spec.rb, spec/ddtrace/profiling/pprof/template_spec.rb
I was trying to diagnose some issues in the connection between traces and profiles and did these two improvements to our current debug logging; see individual commit messages for more details.
=> Debug log statistics during profile encoding + Tweak "started thread" debug logs

lib/ddtrace/profiling/flush.rb, lib/ddtrace/profiling/transport/http/api/endpoint.rb, spec/ddtrace/profiling/flush_spec.rb, spec/ddtrace/profiling/transport/http/adapters/net_integration_spec.rb, spec/ddtrace/profiling/transport/http/api/endpoint_spec.rb
Tags configured via `Datadog.configure { |c| c.tags = { ... } }` or via `DD_TAGS` are now included in reported profiles.
This brings the Ruby profiler into feature parity with our other profilers (such as dd-trace-py).
=> [PROF-3320] Include tags in profiles

lib/ddtrace/configuration/settings.rb, spec/ddtrace/configuration/settings_spec.rb
As documented in <https://docs.datadoghq.com/tracing/setup_overview/setup/ruby/#environment-and-tags>:
> If `DD_ENV`, `DD_SERVICE` or `DD_VERSION` are NOT set, tags defined in `DD_TAGS` will be used to populate `env`/`service`/`version` respectively.
Unfortunately, the previous implementation was missing a weird corner case: the `service`/`env`/`version` in the settings object were only set as a side-effect of trying to access or write to the `tags` option.
This meant that in a situation where `service`/`env`/`version` were defined in `DD_TAGS` only AND those values were accessed BEFORE calling `tags`, the accessing code would not see the correct values (it would still see them as `nil`).
In particular, this happened during tracer initialization inside `Components#build_tracer`, and meant …
=> Fix tracer ignoring value for service tag (service name) in DD_TAGS

lib/ddtrace/metrics.rb, spec/ddtrace/metrics_spec.rb
This PR adds a one-time warning when `ddtrace` tries to instantiate `Datadog::Statsd` with a version that can cause unbounded memory usage by leaking threads #1491.
We've already updated our documentation instructing new users to not install `dogstastd-ruby` >= 5.0: #1533. Versions < 5.0 are confirmed safe.
There's only one place in `ddtrace` where `Datadog::Statsd` instances are created, so the warning was placed at that point.
=> Add warning for incompatible dogstastd-ruby version

ddtrace.gemspec, docs/GettingStarted.md, lib/ddtrace/version.rb
This PR updates the minimum Ruby version in our gemspec, as well the official documentation with the remove of support for Ruby 2.0.
Ruby 2.1 is the new minimum Ruby version supported.
=> Declare EOL for Ruby 2.0 support

spec/ddtrace_integration_spec.rb
I noticed one of my tests didn't seem to have failed ([expected 11, got 11](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/3615/workflows/8b5bfc13-08c4-484b-a669-b7c5416bc62b/jobs/141636/parallel-runs/2)), but it turns out that the custom message was using the wrong count.
This PR addresses that.
=> Fix test typo

lib/ddtrace/auto_instrument.rb, spec/ddtrace/auto_instrument_spec.rb
For users that enable profiling via environment variable (`DD_PROFILING_ENABLED=true`), doing `require 'ddtrace/auto_instrument'` means that the profiler is also started as a side effect, even if they forget to use `ddtracerb exec` or `require 'ddtrace/profiling/preload'`.
This is a nice property!
Right now it semi-happens by chance, but I want to make it an actual feature, so I'm adding a bit more code and tests to make this happen explicitly so that we don't regress.
=> Explicitly start profiler on ddtrace/auto_instrument

lib/ddtrace/configuration/components.rb
In #1545 a user reported a NameError during profiler initialization.
I wasn't able to reproduce the issue, but I've added a small check and a nicer message in case it comes back to ask users to report the issue to us, and that avoids breaking their application.
Issue #1545
=> Handle NameError during profiler initialization

lib/ddtrace/configuration/components.rb, lib/ddtrace/span.rb, spec/ddtrace/span_spec.rb
Some Span tags have special handling in the Datadog Agent. [Here's the list of these tags](https://github.com/DataDog/datadog-agent/blob/2ae2cdd315bcda53166dd8fa0dedcfc448087b9d/pkg/trace/stats/aggregation.go#L13-L17).
These tags have to always be reported as string Tags, not numerical Metrics.
One example of issues caused by setting these values as numerical is this:
```
span.set_tag('version', 123)
```
In this case, `version` will not correctly set the span version, thus not correctly updating the Datadog backend version value.
This PR adds a check and ensures that these values are always string tags.
=> Ensure special tags are always strings

lib/datadog/ci/contrib/cucumber/configuration/settings.rb, lib/datadog/ci/contrib/rspec/configuration/settings.rb, lib/ddtrace/configuration/settings.rb, lib/ddtrace/contrib/rails/framework.rb, lib/ddtrace/ext/runtime.rb, lib/ddtrace/tracer.rb, spec/ddtrace/configuration/components_spec.rb, spec/ddtrace/configuration/settings_spec.rb, spec/ddtrace/diagnostics/environment_logger_spec.rb, spec/ddtrace/tracer_spec.rb
When no service name is provided (no `DD_SERVICE`, `DD_TAGS=service:...` or they equivalents via code), the tracer falls back to using the Ruby process name.
This default was embedded within the tracer class, which meant that profiler did not use it, resulting in mismatched service names in tracing/profiling: tracing would use the Ruby process name, and profiler would get "unnamed service".
To fix this, I've extracted this fallback service name into a constant set when ddtrace gets loaded, and added it as a default for the service.
Note that the existing priority for deciding the service name is still respected: `c.service` > `DD_SERVICE` > `c.tags` > `DD_TAGS` > fallback name.
=> Extract default/fallback service name from tracer

lib/ddtrace/profiling/ext/cpu.rb, spec/ddtrace/profiling/ext/cpu_spec.rb
...instead, customers will get a log message as follows:
```
INFO -- ddtrace: [ddtrace] (/app/lib/ddtrace/profiling/tasks/setup.rb
:44:in `activate_cpu_extensions') CPU time profiling skipped because
native CPU time is not supported: The `logging` gem is installed and
its thread inherit context feature is enabled. Please add
LOGGING_INHERIT_CONTEXT=false to your application's environment
variables to disable the conflicting `logging` gem feature. See
https://github.com/TwP/logging/pull/230 for details. Profiles
containing Wall time will still be reported.
```
This is a repeat of #1362 -- the logging gem also monkey patches `Thread` initialization using `alias_method`, which is incompatible with our instrumentation that uses `preload`.
For details, see …
=> [PROF-3514] Skip CPU time instrumentation if logging gem is detected

lib/ddtrace/configuration/components.rb, lib/ddtrace/metrics.rb, lib/ddtrace/runtime/metrics.rb, spec/ddtrace/metrics_spec.rb, spec/ddtrace/runtime/metrics_spec.rb
A customer reported the following `NoMethodError`:
```
components.rb:245:in `each': private method `close' called for  #<Datadog::Statsd:0x00007fa757896bc8> (NoMethodError)
```
Turns out that the customer had an incompatible dogstatsd-ruby version, but since they had their instance manually configured, rather than created by the `Metrics` class, our version check was being bypassed. This led the incompatible dogstatsd-ruby version to be used, and one of the incompatibilites is the fact that `#close` was private on that old version.
A minimal test case for this issue is:
```ruby
require 'bundler/inline'
gemfile do
source 'https://rubygems.org'
gem 'dogstatsd-ruby', '< 3'
gem 'ddtrace', '= 0.50.0'
end
require 'datadog/statsd' …
```
=> Do not use configured dogstatsd instance when it's an incompatible version

spec/ddtrace/metrics_spec.rb
Leftover from #1560, I noticed that I had left a confusing description for a test group.
=> Minor: Fix confusing test description

.gitattributes
This PR hides Gemfiles that automatically generated in the `gemfiles/` direcotry from showing in GitHub diffs.
This follows this GitHub documentation on how to accomplish this: https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/customizing-how-changed-files-appear-on-github
=> Hide generated gemfiles from GitHub diffs
