docs/GettingStarted, lib/ddtrace/contrib/rails/framework.rb, test/contrib/rails/tracer_test.rb
Add new options to the rails tracer configuration.
=> Add rails options

lib/ddtrace/contrib/rails/framework.rb
If ActiveRecord is not available, do not try to hook into it.
=> add support for rails apps which do not use ActiveRecord

lib/ddtrace/contrib/rails/action_controller.rb, lib/ddtrace/contrib/rails/action_view.rb
This patch double-checks that a given operation has been started
before closing it in another span. Not doing this could lead to
some strange behavior if, for some reason, the finish event is
triggered without the corresponding start_... event.
=> [rails] checking that spans are created before finishing them

lib/ddtrace/contrib/sidekiq/tracer.rb
so that the sample in the doc actually works 
http://gems.datadoghq.com/trace/docs/#label-Sidekiq
```
Sidekiq.configure_server do |config|
config.server_middleware do |chain|
chain.add(Datadog::Contrib::Sidekiq::Tracer)
end
end
```
=> sidekiq: make options optional *cough*

Appraisals, Rakefile, gemfiles/contrib.gemfile, gemfiles/rails4_postgres_sidekiq.gemfile, gemfiles/rails5_postgres_sidekiq.gemfile, lib/ddtrace/contrib/sidekiq/tracer.rb, test/contrib/rails/apps/application.rb, test/contrib/rails/rails_active_job_test.rb, test/contrib/rails/rails_sidekiq_test.rb
This PR should fix https://github.com/DataDog/dd-trace-rb/issues/90 the fix is quite straightforward so it's mostly about testing it.
=> [contrib:sidekiq] handle wrapped ActiveJob resource

README.md, docs/GettingStarted.md, lib/ddtrace/contrib/active_record/patcher.rb, lib/ddtrace/logger.rb, lib/ddtrace/monkey.rb, test/logger_test.rb
Did a few minor code fixes as well.
=> [doc] updated docs for release 0.7.0

lib/ddtrace/contrib/sidekiq/tracer.rb, test/contrib/sidekiq/tracer_test.rb
=> Option to customize Sidekiq service on a worker level

lib/ddtrace/contrib/elasticsearch/patcher.rb, test/contrib/elasticsearch/transport_test.rb
for consistency with other http-based integrations
=> elastic: set http status code

lib/ddtrace/contrib/elasticsearch/patcher.rb
Thanks @dorner for spotting this!
=> [contrib:es] fix ugly typo error StandardError with a d

docs/GettingStarted.md
=> Add to documentation around configure

test/pin_test.rb
Adds a test for a custom getter/setter in the `Pin`.
=> [pin] add tests for custom setter/getter

lib/ddtrace/contrib/rails/active_support.rb, lib/ddtrace/contrib/rails/core_extensions.rb
Before this patch, the Rails cache instrumentation relied in the span order to find the active ``Span``. This patch makes use of a ``tracing_context`` that propagates the ``rails.cache`` span so that it can be retrieved when the cache processing ends. It has also a slightly better stable way to avoid double instrumentation when a `Rails.fetch` calls a `Rails.read`.
In the case of Rails 3.x, there is no need to patch the instrumentation system since we use our custom signals. This will make the integration far stable.
No breaking changes are expected. Backward compatibility with Rails 3.0 still applies.
=> [rails] use custom signals for Cache instrumentation

docs/GettingStarted.md
* moves the Faraday doc, adding a navigation link
* adds the SuckerPunch doc
=> [docs] add integration docs

docs/GettingStarted.md
The previous documentation was incomplete.
=> [resque] update docs with the right imports

.gitignore, lib/ddtrace/contrib/redis/patcher.rb, lib/ddtrace/contrib/redis/quantize.rb, lib/ddtrace/contrib/redis/tags.rb, lib/ddtrace/ext/redis.rb, test/contrib/rails/redis_cache_test.rb, test/contrib/redis/quantize_test.rb, test/contrib/redis/redis_test.rb
Addition of `redis.raw_command` tag and `redis.pipeline_length` metric.
=> [redis] Updates Redis integration tag/metric

lib/ddtrace/workers.rb, lib/ddtrace/writer.rb, test/workers_test.rb
* Adds exponential back-off to `Worker`;
* Remove retries from `Writer`;
=> Flushing policy improvement

lib/ddtrace/ext/priority.rb, lib/ddtrace/sampler.rb
Add-on to #290 , suggested by @delner 
If we want to do this, we probably also want to apply it in other integrations (Python, Go, ...)
=> [dual sampling] adding constants for sampling priority values

lib/ddtrace/contrib/rails/utils.rb, test/contrib/rails/utils_test.rb
Closes PR https://github.com/DataDog/dd-trace-rb/pull/222
=> Memoize `active_record` connection config

lib/ddtrace/contrib/rack/patcher.rb
This PR simply provides error handling during rack middleware patching. These errors are expected when the code executes outside a `rails server` process – that is, processes that don't serve HTTP requests but load the Rails environment through `config/environment.rb`
=> Add error handling during middleware patch 

docs/GettingStarted.md
=> Fixing Processing Pipeline Documentation Typo

lib/ddtrace/transport.rb
This change makes the application stop spamming error logs when Datadog agent can't be contacted.
This is meant to reduce the impact of not available agent on readability of logs.
=> Log consecutive errors in Transport only once

lib/ddtrace.rb, lib/ddtrace/contrib/aws/configuration/settings.rb, lib/ddtrace/contrib/aws/ext.rb, lib/ddtrace/contrib/aws/instrumentation.rb, lib/ddtrace/contrib/aws/integration.rb, lib/ddtrace/contrib/aws/patcher.rb
This pull request implements the configuration core from #450 in the AWS integration.
=> Implement AWS integration configuration

lib/ddtrace/span.rb, spec/ddtrace/tracer_spec.rb
Inspired by https://github.com/rails/rails/commit/42fec4b8de8c40d7778f936e200081c0dded1ed0, this change starts capturing the number of allocations made in each span.
I'm not sure how you'd like to integrate this data – do you just want to use a tag, or would you prefer a first-class attribute on Span?
=> Track the number of allocations made in each span

lib/ddtrace/contrib/grape/endpoint.rb
Grape [released version 1.2.0](https://github.com/ruby-grape/grape/blob/master/CHANGELOG.md) on 11/26/18 which broke our CI builds. In this new version, Grape deprecated the use of `Grape::API` directly.
Applications that are still using `Grape::API` after 1.2.0 will not be able to see the class name of the API in their trace resource names. This is because these well-known types are coerced into anonymous classes as noted [in this issue](https://github.com/ruby-grape/grape/issues/1825). Users who experience this, as a workaround, should upgrade their base class from `Grape::API` to `Grape::API::Instance` [as described here](https://github.com/ruby-grape/grape/blob/master/UPGRADING.md), e.g.
```
class MyApi < Grape::API; end
class MyApi < Grape::API::Instance; end
```
To fix our CI build, …
=> Fix bad resource name with Grape::API when used in Grape 1.2.0

spec/ddtrace/contrib/mongodb/client_spec.rb
With the release of Mongo 2.9, Mongo operation attributes were re-ordered in such a way that broke tests that expected them to match a specific string.
This pull request aims to fix those tests by deserializing the output and comparing it against the expected equivalent Hash value.
=> Fix Mongo 2.9 breaking CI build

docs/GettingStarted.md
Fixes Titles in order to allow a better navigation within the public doc.
=> Fixing header indent for doc

spec/ddtrace/contrib/mongodb/client_spec.rb
Given the frequent updates to Mongo gem that repeatedly break our tests for quantization, we need to find a better way to gracefully handle minor changes to the query structure, especially those that don't represent a meaningful issue for quantization.
This pull request changes the strategy from comparing deserialized objects to one another, which are intolerant to additional keys, to a strategy which generally scans the deserialized resource. It expects every value in the resource to be quantized with `'?'` except for Hash keys, and key-pairs that are explicitly expected to have some specific value.
Expectations now look like:
```
expect(span.resource).to be_quantized.except('operation' => 'insert', 'database' => 'test', 'collection' => 'people')
```
In doing so, we're trading explicit …
=> Fix Mongo quantization tests

docs/GettingStarted.md
@delner, we got a support request saying that this is a typo. Can you verify?
=> updating supported rails version

docs/GettingStarted.md
This pull request changes the formatting of our Ruby support table.
=> Update support table

test/tracer_test.rb
The following wait loop does not exist as one would expect:
```ruby
1000.times do
mutex.synchronize do
break unless @thread_ctx.nil? || @thread_span.nil?
end
sleep 0.01
end
```
The `break` statement is actually breaking out of `#synchronize`, not `#times`, meaning this test always runs to its maximum time of around 11s.
This PR replaces this loop with our helper method `try_wait_until`. I also removed the mutex around the instance variable assignment verification, as instance variable assignment is an atomic VM operation.
This is the slowest single test in our test suite currently.
=> Fix bad await loop in tracer test

.circleci/config.yml
This PR creates an S3 file that triggers the deployment of the current master branch of `dd-trace-rb` into our internal test environment.
The file uploaded to S3 has the following information (one per line):
```
branch name
commit hash
user who did the commit
```
=> Deploy master branch to test environment

.circleci/config.yml
Reverts ca5adf78f1195330bb0e9a04a043353491189b59, as we have decided to evaluate a different approach to ship new changes to our test environment.
=> Revert "Deploy master branch to test environment"

CHANGELOG.md, lib/ddtrace/version.rb
Update `master` version number and changelog from bugfix release.
=> Merge 0.35.2 into master

docs/GettingStarted.md
that previous statement was hella vague
=> clarify activation/enablement in docs

lib/ddtrace/writer.rb
resolves #1063
tangentially related to #1072
@marcotc @delner 
feel free to make additional changes
=> writer thread safety

lib/ddtrace/contrib/faraday/patcher.rb
Follow up from https://github.com/DataDog/dd-trace-rb/pull/1057
Related to https://github.com/DataDog/dd-trace-rb/issues/978
This PR addresses the middleware insertion order for global default connections (e.g. `Faraday.get`) for Faraday < 1.0.
Functionality is not affect by this change, but a warning emitted by Faraday is now addressed:
```
WARNING: Unexpected middleware set after the adapter. This won't be supported from Faraday 1.0.
```
Faraday >= 1.0 is **not** affected, as it uses a different patching code path.
Testing that warnings won't happen in the future is tricky: because activating an integration has irreversible side-effects on the patched library (Faraday in our case), we can only test `Datadog::Contrib::Faraday::Patcher.patch` once per RSpec execution. This would require …
=> fix:Default connection middleware order for Faraday < 1.0

lib/ddtrace/buffer.rb, spec/ddtrace/buffer_spec.rb
Our health metrics counters for the TraceBuffer were not consistent among each other.
Before this change `buffer_accepted_lengths` had the current number of spans in the buffer, but this value is already covered by `queue_spans`. The object was for `buffer_accepted_lengths` to have the total cumulative number of spans pushed into the buffer.
All values should be consistent now with this PR:
* Cumulative total: `queue_accepted`, `queue_accepted_lengths`, `queue_dropped`
* Current value: `queue_max_length`, `queue_spans`, `queue_length`
=> Correct tracer buffer metric counting

docs/DevelopmentGuide.md
=> docs: fix links

lib/ddtrace/tracer.rb, spec/ddtrace/tracer_spec.rb
@marcotc had a small typo in previous PR , got too cute with one liners
=> hotfix: fix if statement

Appraisals
(avoid too many changes in #1216)
=> chore: format Appraisals

CHANGELOG.md
👋 I just ran [`pimpmychangelog`](https://github.com/pcreux/pimpmychangelog) to pimp your CHANGELOG. It adds links to pull requests and users making it easier to jump to a specific PR to get more details.
=> Ran pimpmychangelog

.circleci/config.yml, Rakefile, ddtrace.gemspec
Will install and upload final coverage report to Codecov in CI (while still generating the html formatted report)
=> Upload coverage report to Codecov

lib/ddtrace/propagation/http_propagator.rb, spec/ddtrace/propagation/http_propagator_spec.rb
Adds a "begin/rescue" block around `HTTPPropagator` extractors and injectors. This should catch any issues that could arise for any propagator implementations, specially useful for custom propagators.
This ensures that `HTTPPropagator.inject!` and `HTTPPropagator.extract` never fail.
An error is logged to `Datadog.logger` if any error occurs in the propagators.
=> More defensive distributed HTTP propagator

lib/ddtrace/ext/ci.rb, lib/ddtrace/ext/git.rb, spec/ddtrace/ext/fixtures/ci/appveyor.json, spec/ddtrace/ext/fixtures/ci/azurepipelines.json, spec/ddtrace/ext/fixtures/ci/bitbucket.json, spec/ddtrace/ext/fixtures/ci/bitrise.json, spec/ddtrace/ext/fixtures/ci/buildkite.json, spec/ddtrace/ext/fixtures/ci/circleci.json, spec/ddtrace/ext/fixtures/ci/github.json, spec/ddtrace/ext/fixtures/ci/gitlab.json, spec/ddtrace/ext/fixtures/ci/jenkins.json, spec/ddtrace/ext/fixtures/ci/travisci.json
* Removing deprecated CI tags
* Add new tags for GitLab
=> ext: update ci specs

docs/GettingStarted.md
As suggested in https://github.com/DataDog/dd-trace-rb/pull/1260#discussion_r565472417, this PR cleans up our section titles, removing repetitive language.
=> Clearer section naming for automatic instrumentation

docs/ProfilingDevelopment.md, lib/ddtrace/buffer.rb, lib/ddtrace/configuration/components.rb, lib/ddtrace/profiling/backtrace_location.rb, lib/ddtrace/profiling/collectors/stack.rb, lib/ddtrace/profiling/encoding/profile.rb, lib/ddtrace/profiling/exporter.rb, lib/ddtrace/profiling/ext/cpu.rb, lib/ddtrace/profiling/ext/cthread.rb, lib/ddtrace/profiling/ext/forking.rb, lib/ddtrace/profiling/flush.rb, lib/ddtrace/profiling/profiler.rb, lib/ddtrace/profiling/recorder.rb, lib/ddtrace/profiling/scheduler.rb, lib/ddtrace/profiling/tasks/setup.rb
I've been taking a few notes as I go around the codebase, and I finally
sat down to try to gather them in a document.
There's still a lot of hand-waving (e.g. the descriptions of how things
work are still very high-level), but hopefully this will be at least
valuely useful to other people wanting to get into the codebase.
=> Add high-level intro to profiling development

docs/GettingStarted.md
Add links and documentation for httpx (http client library) which maintains its own integration with ddtrace.
=> documentation for httpx (http client) integration

lib/ddtrace/configuration/agent_settings_resolver.rb, spec/ddtrace/contrib/sucker_punch/patcher_spec.rb, spec/support/language_helpers.rb
Hello I'm Ivo and I'm the world's # 1 fan of keyword arguments.
=> Cleanup more Ruby 2.0 support code

spec/ddtrace/profiling/ext/cthread_spec.rb
There is a brief period where a thread has been started but the `#native_thread_id` and `#clock_id` have not yet been set.
Because of it, a few of the tests in `cthread_spec.rb` could trigger flaky failures from time to time.
This is fixed by ensuring that the thread has actually started and set the needed ids before the expectations are run.
This change is simpler than it seems on the diff -- just ignore whitespace to see the actual change.
Link to failed CI run:
<https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/3505/workflows/2a54fe7e-8e43-4bd0-bd95-9be717eddf9f/jobs/138057/tests#failed-test-0>
=> Fix flaky cthread_spec tests due to races

tasks/update_appraisal_gemfiles.rake
Minor clean up on rake task I spent way too much time running today.
=> Reorganize update_appraisal_gemfiles task

CHANGELOG.md, lib/ddtrace/contrib/aws/patcher.rb, lib/ddtrace/version.rb, spec/ddtrace/contrib/aws/instrumentation_spec.rb
This is a bugfix release, based on the `0.51-stable` branch as `master` already has a few unrelated changes merged in since `0.51.0`.
=> Bump to version 0.51.1

spec/support/http_helpers.rb
Not being used anymore, goodbye and thanks for all the 🐟 !
=> Minor: Remove unused test helper

integration/apps/rack/README.md, integration/apps/rack/bin/run, integration/apps/rack/script/build-images, integration/apps/ruby/script/build-images, integration/script/build-images
See individual commit messages for details.
=> Misc fixes and cleanups to integration apps setup

lib/ddtrace/contrib/extensions.rb
=> Minor: Fix typo in warning message

lib/datadog/ci/ext/environment.rb
Fixes https://github.com/DataDog/dd-trace-rb/issues/1621 
Props to @andrewhampton for finding the issue and proposing a solution.
=> [ci-app] Fix GHA Env Vars Extraction

CHANGELOG.md, lib/ddtrace/contrib/aws/patcher.rb, lib/ddtrace/version.rb, spec/ddtrace/contrib/aws/instrumentation_spec.rb
The diff in this PR is actually a bit misleading as the S3 fix is actually already in master -- the main change we want back in master is the addition of 0.51.1 to the changelog.
=> Merge fixes in 0.51 stable branch back to master

docs/ProfilingDevelopment.md, lib/ddtrace/profiling/events/stack.rb, spec/ddtrace/profiling/events/stack_spec.rb
Two small commits I extracted from a larger branch. See individual commit messages for details.
=> Profiler cleanups

Appraisals, Rakefile
I started looking into a few `Appraisals` improvements but did not get as far as I wanted.
On the way, I did a few smaller cleanups, so here's what I got so far.
See individual commit messages for more details.
=> Appraisal readability cleanups

spec/ddtrace/contrib/analytics_examples.rb, spec/ddtrace/contrib/mongodb/client_spec.rb, spec/ddtrace/contrib/presto/client_spec.rb, spec/ddtrace/contrib/rails/rails_auto_instrument_spec.rb, spec/ddtrace/contrib/rails/support/application.rb, spec/ddtrace/contrib/redis/integration_test_spec.rb, spec/ddtrace/contrib/support/spec_helper.rb, spec/ddtrace/propagation/http_propagator_spec.rb, spec/ddtrace/span_spec.rb, spec/ddtrace/sync_writer_spec.rb, spec/ddtrace/transport/http/adapters/unix_socket_integration_spec.rb, spec/ddtrace/workers/async_spec.rb, spec/ddtrace/writer_spec.rb, spec/spec_helper.rb, spec/support/tracer_helpers.rb
So, crazy idea: what if running `bundle exec spec:main` actually produced meaningful output, rather than never-ending deluge of noise? :P
I've taken a few steps towards that dream. See individual commits for details.
=> Improve test suite output

docs/GettingStarted.md
This PR cherry-picks #1671 to the release branch, so that the doc issue is fixed asap.
=> Fix link to Ruby profiler onboarding (cherry-pick to release branch)

docs/GettingStarted.md
Cherry pick documentation fix from #1676 to release branch
=> Cherry pick documentation fix from #1676 to release branch

docs/GettingStarted.md, lib/ddtrace/contrib/rails/configuration/settings.rb, lib/ddtrace/contrib/rails/framework.rb
=> Allow overriding service name for rails ActiveJob

ext/ddtrace_profiling_native_extension/extconf.rb
The `CAN_USE_MJIT_HEADER && RbConfig::CONFIG['MJIT_SUPPORT'] != 'yes'` condition was being activated also for JRuby/TruffleRuby, which while warmless meant that we printed a confusing message about their JIT being disabled.
By turning all the checks into their own functions, we make advantage of `||` short-circuiting, and thus never evaluate `expected_to_use_mjit_but_mjit_is_disabled?` on those Rubies.
I also took the opportunity to move the `disabled_via_env?` to the beginning of `skip_building_extension?` as that one applies regardless of any of the others.
=> Fix disabled mjit banner being printed when it shouldn't

.circleci/images/primary/Dockerfile-truffleruby-21.3.0, Rakefile, docker-compose.yml, spec/ddtrace/auto_instrument_spec.rb, spec/ddtrace/configuration/components_spec.rb, spec/ddtrace/configuration_spec.rb, spec/ddtrace/profiling/collectors/stack_spec.rb, spec/ddtrace/profiling/integration_spec.rb, spec/ddtrace/profiling/native_extension_spec.rb, spec/ddtrace/profiling/pprof/builder_spec.rb, spec/ddtrace/profiling/pprof/stack_sample_spec.rb, spec/ddtrace/profiling/pprof/template_spec.rb, spec/ddtrace/profiling/transport/http/adapters/net_integration_spec.rb, spec/ddtrace/profiling/transport/http/integration_spec.rb
We don't yet support TruffleRuby, but I did one of my passes at adding it to our CI.
I ran out of Hackathon time before I was able to validate its addition, but here are a few cleanups that we can already merge in.
(Hackathon!)
Issue #1383
=> Another round of TruffleRuby cleanups and fixes

lib/ddtrace/version.rb
Let's officially mark the master branch as being the place where changes for the upcoming 1.0.0 release are landing.
=> Mark master branch as being 1.0.0.dev

lib/ddtrace/configuration/settings.rb, lib/ddtrace/pipeline.rb
Adds documentation to settings missing such information.
=> Document transport and sampling tracer settings

lib/datadog/tracing/event.rb
This mutex creates measurable overhead in the trace span creation and handling, but adds no value today, given spans cannot be safely shared across threads today.
=> Remove Tracing::Event mutex

lib/datadog/appsec/contrib/rack/request.rb
Rack 1.x lacks a each_header method, adjust for it.
=> Fix request header for Rack 1.x

docs/GettingStarted.md
DD no longer maintains this link, so removing
=> DOCS-3203 Remove link to removed web page

lib/datadog/tracing/contrib/aws/instrumentation.rb, spec/datadog/tracing/contrib/aws/instrumentation_spec.rb
See https://github.com/DataDog/dd-trace-rb/pull/1928 for context. Recreating because git is brutal...
=> Provide metrics for AWS spans

LICENSE-3rdparty.csv
=> fix LICENSE-3rdparty.csv [ci skip]

ddtrace.gemspec
Today I was talking with another team member about this, and I thought it'd be nice to document this sharp edge that only people that were around for previous discussions may remember.
Closes #1739
=> Document potential confusion with msgpack dependency in .gemspec

.github/workflows/system-tests.yml
This PR does two things : 
- Add a usefull scenario for AppSec (around 2mn to execute)
- Add a fancy report in github action :
=> Add fancy report, Add a scenario in test

docs/UpgradeGuide.md
Fix a small mistake in the upgrading guide.
=> Fix old configuration example in upgrading guide

lib/datadog/tracing.rb, lib/datadog/tracing/sampling/priority_sampler.rb, lib/datadog/tracing/sampling/rate_by_service_sampler.rb, lib/datadog/tracing/sampling/rate_sampler.rb
Hi. I just noticed typo in some files. 
`::` should be use to express namespace instead of `:::`
**Motivation**
When search class by name, I have little problem because this expression is no hitted.
=> fix small typo 

ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time.c, spec/datadog/profiling/collectors/cpu_and_wall_time_spec.rb
Tags stack samples with the wall-clock time elapsed since the last sample.
This works by tracking the timestamp of when a thread was sampled (in `wall_time_at_previous_sample_ns` inside the `per_thread_context`), and then tagging samples with the elapsed time between the current and the previous sample. (The first time a thread is sampled, the elapsed time is set to 0).
One of the main responsibilities of the `CpuAndWallTime` collector is tracking the amount of wall-clock time (aka real world time) that elapses between samples.
This allows users to tell what their threads are spending time, even when they're not actually spending CPU (e.g. when they're waiting on a database query).
Tracking of cpu-time is still missing, and …
=> [PROF-4902] Track passage of wall-clock time between samples

integration/README.md, integration/apps/sinatra2-classic/.envrc.sample, integration/apps/sinatra2-modular/.envrc.sample
Add `.envrc.sample`
Add Sinatra app in `README.md`
=> Minor improvement for integration environment

docs/GettingStarted.md
Update docs about graphql setting.
**Motivation**
I realize syntax error and missing option.
Description came from:
https://graphql-ruby.org/queries/tracing.html
I make list from this code:
https://github.com/DataDog/dd-trace-rb/blob/v1.2.0/lib/datadog/tracing/contrib/graphql/patcher.rb#L30-L32
=> Update graphql related docs

spec/datadog/tracing/contrib/sidekiq/support/helper.rb
I accidentally forgot to remove a (commented out) `binding.pry` statement when working on #2170.
**Motivation**
=> Remove binding.pry statement

spec/spec_helper.rb
Oops, forgot to push this commit to #2210 before merging it. 😢
=> CI:Test time limit with thread dump report (missing commit)

docs/GettingStarted.md
Updates an empty anchor link.
**Motivation**
Transifex
=> Tracing Ruby Applications Edit

ext/ddtrace_profiling_native_extension/NativeExtensionDesign.md
Add development notes around fork usage and the profiler.
This documentation is extracted from a recent slack discussion, and @r1viollet suggested that we record this information somewhere, so I'm adding it to the profiling `NativeExtensionDesign.md` document.
`fork` is just a really weird API :)
This is a documentation-only change!
=> Add development notes around fork usage and the profiler

LICENSE-3rdparty.csv, lib/datadog/tracing/contrib/utils/quantization/http.rb, spec/datadog/tracing/contrib/utils/quantization/http_spec.rb
Backport of #2311 to `1.5-stable`
**Motivation**
Without this there's a possibility of crash.
=> Backport "Handle URLs with invalid characters"

lib/datadog/core/runtime/ext.rb, lib/ddtrace/transport/trace_formatter.rb, spec/ddtrace/transport/trace_formatter_spec.rb
Tag `process_id` with the process id
=> Unified tagging `process_id`

lib/datadog/appsec/assets/waf_rules/recommended.json, lib/datadog/appsec/assets/waf_rules/risky.json, lib/datadog/appsec/assets/waf_rules/strict.json
Update ruleset to v1.4.2
**Motivation**
Keeping it up to date :)
System tests should cover this.
=> Update AppSec ruleset to v1.4.2

.circleci/images/primary/Dockerfile-2.5.9
Make the Dockerfile more like the other more recent rubies
=> Align Ruby 2.5.9

.circleci/config.yml
Depends on https://github.com/DataDog/dd-trace-rb/pull/2399
=> Use Ruby 3.2.0-preview3 in CircleCI

.circleci/config.yml, gemfiles/ruby_2.5.9_contrib.gemfile.lock, gemfiles/ruby_2.5.9_contrib_old.gemfile.lock, gemfiles/ruby_2.5.9_core_old.gemfile.lock, gemfiles/ruby_2.5.9_cucumber3.gemfile.lock, gemfiles/ruby_2.5.9_cucumber4.gemfile.lock, gemfiles/ruby_2.5.9_cucumber5.gemfile.lock, gemfiles/ruby_2.5.9_hanami_1.gemfile.lock, gemfiles/ruby_2.5.9_rails5_mysql2.gemfile.lock, gemfiles/ruby_2.5.9_rails5_postgres.gemfile.lock, gemfiles/ruby_2.5.9_rails5_postgres_redis.gemfile.lock, gemfiles/ruby_2.5.9_rails5_postgres_redis_activesupport.gemfile.lock, gemfiles/ruby_2.5.9_rails5_postgres_sidekiq.gemfile.lock, gemfiles/ruby_2.5.9_rails5_semantic_logger.gemfile.lock, gemfiles/ruby_2.5.9_rails61_mysql2.gemfile.lock, gemfiles/ruby_2.5.9_rails61_postgres.gemfile.lock, gemfiles/ruby_2.5.9_rails61_postgres_redis.gemfile.lock, gemfiles/ruby_2.5.9_rails61_postgres_sidekiq.gemfile.lock, gemfiles/ruby_2.5.9_rails61_semantic_logger.gemfile.lock, gemfiles/ruby_2.5.9_rails6_mysql2.gemfile.lock, gemfiles/ruby_2.5.9_rails6_postgres.gemfile.lock, gemfiles/ruby_2.5.9_rails6_postgres_redis.gemfile.lock, gemfiles/ruby_2.5.9_rails6_postgres_redis_activesupport.gemfile.lock, gemfiles/ruby_2.5.9_rails6_postgres_sidekiq.gemfile.lock, gemfiles/ruby_2.5.9_rails6_semantic_logger.gemfile.lock, gemfiles/ruby_2.5.9_resque2_redis3.gemfile.lock, gemfiles/ruby_2.5.9_resque2_redis4.gemfile.lock, gemfiles/ruby_2.5.9_sinatra.gemfile.lock
Appraisal install 2.5 for `tracer-jruby-9.2.8.0`, `tracer-jruby-9.2` and `tracer-2.5` . CI green
=> Appraisal 2.5 install

ext/ddtrace_profiling_native_extension/clock_id_from_pthread.c, ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time.c, ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time.h, ext/ddtrace_profiling_native_extension/collectors_cpu_and_wall_time_worker.c, ext/ddtrace_profiling_native_extension/helpers.h, ext/ddtrace_profiling_native_extension/profiling.c, ext/ddtrace_profiling_native_extension/stack_recorder.c, ext/ddtrace_profiling_native_extension/time_helpers.c, ext/ddtrace_profiling_native_extension/time_helpers.h
This PR collects a number of small refactoring operations that were extracted from my branch for implementing dynamic sampling rate.
See individual commit messages for details.
I decided to extract this from my branch so that the following PR/PRs to add the dynamic sampling rate can be more focused on the feature and less on shuffling code around.
(N/A)
These refactoring operations do not change any existing behavior, and thus are covered by existing tests.
=> [PROF-6557] Refactoring in preparation for implementing dynamic sampling rate

.circleci/images/primary/Dockerfile-3.0.4
**Motivation**
This somehow went missing from the previous pinning commit in #2559 
I should get a brain. The current one appears to be defective.
Same as #2559
=> Pin bundler on 3.0

docs/DevelopmentGuide.md
Updates the [DevelopmentGuide.md](https://github.com/DataDog/dd-trace-rb/blob/master/docs/DevelopmentGuide.md)
Most of the changes are related with the testing commands mentioned. The problem I found is that the appraisal name did not matched with the ones created after running `appraisal install`
**Motivation**
Make sure people following the guide can run the test without issues
=> update development guide

.circleci/images/primary/Dockerfile-2.1.10, .circleci/images/primary/Dockerfile-2.2.10, .circleci/images/primary/Dockerfile-2.3.8, .circleci/images/primary/Dockerfile-2.4.10, .circleci/images/primary/Dockerfile-2.5.9, .circleci/images/primary/Dockerfile-2.6.10, .circleci/images/primary/Dockerfile-2.7.6, .circleci/images/primary/Dockerfile-3.0.4, .circleci/images/primary/Dockerfile-3.1.2, .circleci/images/primary/Dockerfile-3.2.0, .circleci/images/primary/Dockerfile-jruby-9.2.21.0, .circleci/images/primary/Dockerfile-jruby-9.2.8.0, .circleci/images/primary/Dockerfile-jruby-9.3.9.0, .circleci/images/primary/Dockerfile-jruby-9.4.0.0, .circleci/images/primary/Dockerfile-truffleruby-22.3.0, .circleci/images/primary/README.md
This PR adds a new section in the container images `README.md` explaining the steps to publish new versions of the images, as well as a quick note to every `Dockerfile` to remind people that the note in the `README.md` exists.
Recently a change was merged, but not published, and I was a bit confused on how to actually publish the images, so I made a note to come back and document this, so hopefully this is clear for others and for a next time.
(N/A)
Test the steps I've documented!
=> Document how to publish updates to test container images

docs/GettingStarted.md
Add hanami instrumentation is the Getting started doc
=> Add hanami getting started doc

lib/datadog/appsec/instrumentation/gateway.rb, lib/datadog/appsec/reactive/address_hash.rb, lib/datadog/appsec/reactive/engine.rb, lib/datadog/appsec/reactive/operation.rb, lib/datadog/appsec/reactive/subscriber.rb, sig/datadog/appsec/instrumentation/gateway.rbs, sig/datadog/appsec/reactive/address_hash.rbs, sig/datadog/appsec/reactive/engine.rbs, sig/datadog/appsec/reactive/operation.rbs, spec/datadog/appsec/instrumentation/gateway_spec.rb, spec/datadog/appsec/reactive/engine_spec.rb, spec/datadog/appsec/reactive/operation_spec.rb
Adding test for `appsec/intrumention/*` and `appsec/reactive/*` components.
Also: 
- adds frozen string comment to updated files
- small refactors
**Motivation**
Started learning about how appsec works underneath. Noticed that some components were missing unit tests and I used that oppportunity to learn more about how they work and write some tests
CI
=> add tests for Appsec reactive engine

.github/workflows/lib-injection.yml, lib-injection/auto_inject.rb
=> System test for lib injection

.github/workflows/lib-injection.yml
I have prepared some apps to demonstrate the constraints/limitation for Ruby lib injection. However, our system test has not provided the framework to conduct test for that. So I wrote a workflow for those apps to make sure the apps keep running even with lib injection failure.
=> Negative test cases for lib injection

docs/GettingStarted.md
Docs only - updates link text in getting started
**Motivation**
DOCS-5086
=> [DOCS-5086] Update link text in Ruby tracing setup

.gitlab/benchmarks.yml
Add appsec configuration benchmarks
**Motivation**
Do it early so that we can get actual data
[Variants are already defined](https://github.com/DataDog/benchmarking-platform/tree/132c96cd0d331ddd090e36142273fab2bae2c74c) so hopefully this works right away!
benchmark env should run and report data.
=> Add appsec configuration benchmarks

docs/GettingStarted.md
Small grammar fix
**Motivation**
This was brought up through Transifex
=> Small grammar fix 

lib/datadog/appsec/remote.rb, spec/datadog/appsec/remote_spec.rb, spec/datadog/core/remote/client/capabilities_spec.rb
Remove ASM_CUSTOM_RULES capability
**Motivation**
This feature is misreported as it is not supported yet.->
None
CI
=> Remove ASM_CUSTOM_RULES capability

.circleci/config.yml, integration/images/ruby/2.3/Dockerfile, integration/images/ruby/2.4/Dockerfile, spec/datadog/appsec/contrib/rack/integration_test_spec.rb, spec/datadog/appsec/contrib/rails/integration_test_spec.rb, spec/datadog/appsec/contrib/sinatra/integration_test_spec.rb
- Fix the docker ruby images for 2.3 and 2.4 for the integrations apps
- Fix AppSec slow tests https://github.com/DataDog/dd-trace-rb/pull/2843
**Motivation**
=> Fix slow CI and broken images 

spec/datadog/core/remote/client_spec.rb
**Motivation**
Fix flaky test on `core/remote/client_spec.rb`
[flaky test output .txt](https://github.com/DataDog/dd-trace-rb/files/11472425/flaky.test.output.txt)
=> [APPSEC-9575] fix flaky appsec test

.github/workflows/check.yml, Rakefile, tasks/rbs.rake, tasks/steep.rake
- Re-add CI checks for RBS files
- Add a few more, for reporting
**Motivation**
To ensure `sig` does not drift away from `lib` these checks are essential. They will also encourage us to do typing of new files.
Follow-up to #2859 
CI
=> Add RBS checks

docs/GettingStarted.md
Minor updates to the text per documentation style guide.
**Motivation**
This PR was originally merged directly into the release branch (https://github.com/DataDog/dd-trace-rb/pull/2878) and I'm re-opening it targeting the master branch.
N/A
N/A
=> Update GettingStarted.md (In master branch)

.circleci/config.yml, docker-compose.yml
pin the test agent release to the latest tested version
=> pin test agent releases

.github/workflows/lib-injection.yml
Fix the lib-injection Actions by pointing to the main branch of the lib-injection runner https://github.com/DataDog/system-tests/tree/main/lib-injection and adding the the necessary ENV variable 
**Motivation**
=> Fix lib-injection actions

.gitlab-ci.yml, .gitlab/build-deb-rpm.sh
PRODUCT_NAME is needed for subsequent pipeline to work
Add the product_name in gitlab-ci.yml for agent-release-management pipeline to succeed
**Motivation**
Releasing
=> Add product for releasing

Rakefile
Add minitest integration test in our test matrix, which will be picked up on CI.
=> Run minitest integration test on CI

spec/datadog/core/workers/interval_loop_spec.rb
Changes the `IntervalLoop` spec to use a `Fiber` instead of a `Thread`.
**Motivation**
This spec is considered flaky; it appears to hang often in CI, causing intermittent failures. Opting for a fiber should hopefully allow for a faster, more consistent test.
It should not affect any production code; the use of `Fiber` is only in the test suite, not in the main library.
`bundle exec rake spec:main`
=> Use Fiber instead of Thread for IntervalLoop spec

.github/workflows/system-tests.yml
Add the `APPSEC_AUTO_EVENTS_EXTENDED` scenario to out system test action. 
This PR that enabled those tests on system tests https://github.com/DataDog/system-tests/pull/1527
**Motivation**
=> Add APPSEC_AUTO_EVENTS_EXTENDED scenario to the system test GH action

spec/datadog/tracing/contrib/sidekiq/support/helper.rb
While trying to resolve the currently flaky Sidekiq test (https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/11598/workflows/ca1cc8ff-de03-491a-8519-55dc1d7a9572/jobs/435301), I noticed there's a random wait period during Sidekiq server startup that is very long.
[It can be as long as 15 seconds, and with configuration can be reduced to 5 seconds](https://github.com/sidekiq/sidekiq/blob/fcc9406c02b809d18af419e164a8840630d60d23/lib/sidekiq/scheduled.rb#L218C1-L224):
```ruby
def initial_wait
total = 0
total += INITIAL_WAIT unless @config[:poll_interval_average]
total += (5 * rand)
```
This is still large, and can exceed the default timeout for `try_wait_until` (5 seconds). This Sidekiq test has a custom `try_wait_until`, but the test is still rather long.
This PR reduces this …
=> Test:Reduce Sidekiq initial wait time

Rakefile, docs/DevelopmentGuide.md
Currently, developer need to provide the spec task to the test task such as 
```
bundle exec rake test'[spec:redis]'
```
However, we can make the task explicitly by defining them. So it can be invoke as 
```
bundle exec rake test:redis
```
=> Implement test tasks

.github/workflows/system-tests.yml
Revert https://github.com/DataDog/dd-trace-rb/pull/3123
Collaborators do not have write access to the package scope. We need to figure out a way how to handle this action, for now I rather unblock community PR to be merged 
=> Do not run the system tests action for every pull request. 

docs/DevelopmentGuide.md
To encourage community contribution and improve developer experience. 
* Remove the sections related to our obsolete benchmarks, since we are migrating to our benchmark platform
* Document some recent changes for our test runner and appraisal dependency management. 
* Provide some code example to help elaborate.
=> Improve contribution documentation

lib/datadog/appsec/assets/waf_rules/recommended.json, lib/datadog/appsec/assets/waf_rules/strict.json
Update AppSec rules to 1.7.2
Keep things up to date
There's 1.8.0 now.
CI
=> Update AppSec rules to 1.7.2

CHANGELOG.md
The changelog information can be improved. 
A lot of cleanups and rewriting the messages.
=> Cleanup changelog for 1.15.0

CHANGELOG.md, lib/ddtrace/version.rb
=> Bump version 1.15.0 to 1.16.0

Gemfile
Upgrade the steep typechecker to version 1.6.0.
The steep typechecker is under very active development so there's a number of improvements to be picked up, see
https://github.com/soutaro/steep/wiki/Release-Note-1.6 .
In particular, I'm very interested in improvements to error messages, since I still think that's a particular weak point for steep.
N/A
=> Upgrade steep typechecker to version 1.6.0

.gitlab-ci.yml, .gitlab/Dockerfile-2.7.8, .gitlab/Dockerfile-3.0.6, .gitlab/Dockerfile-3.1.4, .gitlab/Dockerfile-3.2.2, lib-injection/README.md
Reverts DataDog/dd-trace-rb#3260
=> Revert "Support lib injection for ARM64 architecture"

spec/datadog/core/telemetry/collector_spec.rb
https://github.com/DataDog/dd-trace-rb/pull/3320 made extension building a requirement only for executing `rake spec:profiling` given only those suites should focus on exercising the actual native components.
For core suites, the intention is that we can abstract the internals through high-level mocking of the profiler component initialization (and the linked PR updated some core tests accordingly). 
However, turns out https://github.com/DataDog/dd-trace-rb/blob/master/spec/datadog/core/telemetry/collector_spec.rb#L97 was forgotten and still going through the full initialization logic. Because it doesn't actually depend on the profiler running, it worked fine if either:
* The profiling extension was not built/supported in which case profiler would be nil.
* The …
=> Prevent spec:main errors with stale extensions

benchmarks/tracing_trace.rb
Add benchmarking measuring how long it takes to load all the files and perform any initialization processes.
This does not include calling `Datadog.configure`, only `require 'ddtrace'`.
This benchmark help us reduce bloat that affects the host application's startup time.
=> Add benchmark for gem loading

lib/datadog/tracing/span_operation.rb, spec/datadog/tracing/span_operation_spec.rb
Removed argument `child_of` from `SpanOperation.new`.
This PR removes the unused argument `child_of` from `SpanOperation.new`.
This argument is only used for testing.
=> Remove SpanOperation.new(child_of)

.gitlab/onboarding_tests.yml
Fix onboarding tests, fix the gitlab runner configuration.
Similar issue in the systemt-tests pipeline. Solved: https://github.com/DataDog/system-tests/commit/9ae1dcff8ca55bcc4157781a406bbcafeb358d54
=> Onboarding tests: Fix gitlab runner config

.gitlab/onboarding_tests.yml
Fix onboarding tests. Tweaks in the gitlab runner
=> fix onboarding tests gitlab runner 2 0

.github/PULL_REQUEST_TEMPLATE.md
Upgrades for request instructions for the 2.0 branch, now that the migration guide document has been created.
We now have to keep this document up-to-date with every request with a meaningful change.
=> PR instructions for upgrade guide updates

docs/GettingStarted.md
Adds beta banner:
[DOCS-7564](https://datadoghq.atlassian.net/browse/DOCS-7564)
[DOCS-7564]: https://datadoghq.atlassian.net/browse/DOCS-7564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add banner to documentation that announces beta release

.github/workflows/add-milestone-to-pull-requests.yml
Fix Add milestone GHA automation
=> Fix add milestone GHA

Rakefile, appraisal/ruby-3.0.rb, appraisal/ruby-3.1.rb, appraisal/ruby-3.2.rb, gemfiles/ruby_3.0_relational_db.gemfile, gemfiles/ruby_3.0_relational_db.gemfile.lock, gemfiles/ruby_3.1_relational_db.gemfile, gemfiles/ruby_3.1_relational_db.gemfile.lock, gemfiles/ruby_3.2_relational_db.gemfile, gemfiles/ruby_3.2_relational_db.gemfile.lock, lib/datadog/tracing/contrib/trilogy/instrumentation.rb
It was missed out during resolving conflict from 2.0. 
Changes could be found from `g show -m 2602e1c09af9fc7cc5025ba3d665af1102676822 Rakefile`
=> Add trilogy to test matrix

.github/workflows/lib-injection.yml, .github/workflows/system-tests.yml
Update using system test branch `main`
https://github.com/DataDog/system-tests/pull/2222
=> Update system test branch with `main`

.github/workflows/lib-injection.yml, .github/workflows/release-lib-injection.yml
The docker build arguments does not matched due to renaming.
=> Fix build args for lib injection docker

.gitlab-ci.yml
The latest stable version of the packaging template now includes a tool dd-pkg. This PR uses this tool to lint the produced DEB and RPM packages.
This lint has been run at the time of package promotion, this change moves this step to the left and lets teams identify issues before they're trying to release to production.
[BARX-245](https://datadoghq.atlassian.net/browse/BARX-245)
[BARX-245]: https://datadoghq.atlassian.net/browse/BARX-245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: Lint produced deb and rpm packages

.github/workflows/build-gem.yml, .github/workflows/check.yml, .github/workflows/test-head.yaml, .github/workflows/test-macos.yaml, .github/workflows/test-yjit.yaml, .github/workflows/update-gemfiles.yml
**Why**
`macos-latest` points to `macos-14` and failed.
1. Update GHA with `ruby/setup-ruby@v1`
2. Fix MacOS test with `macos-13`
=> Update GHA with `macos-13` and `ruby/setup-ruby@v1`

.github/workflows/build-gem.yml, .github/workflows/check.yml, .github/workflows/test-head.yaml, .github/workflows/test-macos.yaml, .github/workflows/test-yjit.yaml, .github/workflows/update-gemfiles.yml
=> Backport update GHA with `macos-13` and `ruby/setup-ruby@v1` (#3612)

.gitlab/benchmarks.yml
Backport https://github.com/DataDog/dd-trace-rb/pull/3614
=> Backport fix macro benchmark

lib-injection/auto_inject.rb
Backport https://github.com/DataDog/dd-trace-rb/pull/3622
=> Backport file force remove

CHANGELOG.md
This PR updates the `CHANGELOG.md` in the master branch with the changes from the 1.x-stable branch (e.g. the 1.23.0 release).
Make sure the `CHANGELOG.md` in master reflects all releases.
N/A
Nothing to test, this is just a documentation change.
=> Update changelog with release 1.23.0

lib/datadog/core/remote/configuration/repository.rb, lib/datadog/core/remote/dispatcher.rb
Both changes are in comments, there are no code changes.
=> Two spelling fixes

lib/datadog/appsec/contrib/devise/tracking.rb, shell.nix
Backport #3645 
1.x is affected by https://github.com/DataDog/dd-trace-rb/issues/3564
=> Backport #3645

.github/workflows/test-macos.yaml
Backporting https://github.com/DataDog/dd-trace-rb/pull/3655
=> Backport macos tess bundle changes

docs/UpgradeGuide2.md
Add a note about `use` vs `instrument`
Context was lacking about `use` vs `instrument` in 1.x
Nope
Read.
=> Add a note about `use` vs `instrument`

docs/GettingStarted.md
=> Point to correct upgrade guide

ddtrace.gemspec
Adds a deprecation description that will show up on our next 1.x release.
=> Add gem renaming message to the gemspec

docs/GettingStarted.md, docs/legacy/GettingStarted-v1.md
Updates the anchor link for header tags.
Translator pointed out the broken anchor link.
=> Update Ruby documentation link to Data Security doc

ext/datadog_profiling_native_extension/collectors_cpu_and_wall_time_worker.c, ext/datadog_profiling_native_extension/collectors_discrete_dynamic_sampler.c, ext/datadog_profiling_native_extension/collectors_idle_sampling_helper.c, ext/datadog_profiling_native_extension/collectors_thread_context.c, ext/datadog_profiling_native_extension/heap_recorder.c, ext/datadog_profiling_native_extension/stack_recorder.c
This PR collects a few fixes/optimizations for rare issues in the profiler that I collected this week. I recommend reviewing commit-by-commit.
Fix these potential issues.
I've never seen any of the fixed issues happen in a production release of our library; I don't believe our customers were ever affected.
It's really hard to add test coverage for these, as they need a really specific timing + set of  conditions to trigger. Such testing would be very complex, so for now we rely on our other integration tests/dogfooding to catch these things.
=> [NO-TICKET] Fixes for rare issues in the profiler + small optimization

.github/workflows/system-tests.yml
=> add auth for system tests aws tests and additional scenarios

lib/datadog/di/error.rb, lib/datadog/di/probe.rb, sig/datadog/di/error.rbs, sig/datadog/di/probe.rbs, spec/datadog/di/probe_spec.rb
Adds the Probe class which encapsulates probe data and general state such as the rate limiter. Also adds exception classes (all of them that I have currently defined to avoid conflicts during rebasing).
Dynamic instrumentation implementation.
Unit tests at this time.
=> DEBUG-2334 dynamic instrumentation Probe class

lib/datadog/di/redactor.rb, sig/datadog/core/configuration/settings.rbs, sig/datadog/di/redactor.rbs, sig/datadog/di/serializer.rbs
This PR adds sig files for dynamic instrumentation settings.
Perform additional type checks.
Existing tests.
=> DEBUG-2334 add types for dynamic instrumentation settings

gemfiles/jruby_9.2_elasticsearch_latest.gemfile.lock, gemfiles/jruby_9.2_opensearch_latest.gemfile.lock, gemfiles/jruby_9.2_stripe_latest.gemfile.lock, gemfiles/jruby_9.3_elasticsearch_latest.gemfile.lock, gemfiles/jruby_9.3_opensearch_latest.gemfile.lock, gemfiles/jruby_9.3_stripe_latest.gemfile.lock, gemfiles/jruby_9.4_elasticsearch_latest.gemfile.lock, gemfiles/jruby_9.4_opensearch_latest.gemfile.lock, gemfiles/jruby_9.4_stripe_latest.gemfile.lock, gemfiles/ruby_3.0_elasticsearch_latest.gemfile.lock, gemfiles/ruby_3.0_opensearch_latest.gemfile.lock, gemfiles/ruby_3.1_elasticsearch_latest.gemfile.lock, gemfiles/ruby_3.1_opensearch_latest.gemfile.lock, gemfiles/ruby_3.2_elasticsearch_latest.gemfile.lock, gemfiles/ruby_3.2_opensearch_latest.gemfile.lock, gemfiles/ruby_3.3_elasticsearch_latest.gemfile.lock, gemfiles/ruby_3.3_opensearch_latest.gemfile.lock, gemfiles/ruby_3.4_elasticsearch_latest.gemfile.lock, gemfiles/ruby_3.4_opensearch_latest.gemfile.lock
_This is an auto-generated PR from [here](https://github.com/DataDog/dd-trace-rb/blob/master/.github/workflows/auto-update-gemfiles.yml), which creates a pull request that will be continually updated with new changes until it is merged or closed)_
The PR updates latest versions of defined dependencies. Please review the changes and merge when ready.
=> [🤖] Update Latest Dependency

docs/ProfilingDevelopment.md
=> Fix typo in file reference

.github/workflows/system-tests.yml
Prefix env var to not conflict with local dev env vars.
=> chore: prefix system tests env var

ext/datadog_profiling_native_extension/heap_recorder.c
This PR adds extra error checking to the heap profiler's `on_committed_object_record_cleanup` function.
We've seen one report of a segmentation fault in this function, and we've not been able to reproduce the issue, so for now I decided to be extra careful and add a bunch of extra error checking to this function.
Investigate potential crash in this function.
As a reminder, heap profiling is off by default AND still marked as alpha. The crash we saw was triggered on Ruby 2.7.5, a version where we need a specific workaround to support heap profiling, so I'm wondering if the crash is 2.7 specific or not...
Hopefully we'll find out soon.
=> [PROF-10656] Add extra error checking to heap profiling function

.github/PULL_REQUEST_TEMPLATE.md
This PR adds a section for change log entry to the github pull request template.
To help create change log during releases, customer-visible changes can have the relevant change log entries pre-composed by the PR author and added to the PR description.
=> Add change log entry section to pull request template

.circleci/config.yml, docker-compose.yml
Updates dd-apm-test-agent to 1.18.0 (current release)
Our version is outdated (1.12).
Check if CI is green
=> Update dd-apm-test-agent to 1.18.0 (current release)

.github/workflows/test-yjit.yaml
Adds a clarification comment.
See https://github.com/DataDog/dd-trace-rb/pull/3991#discussion_r1805074138
=> clarify --yjit-stats=quiet in YJIT CI

lib-injection/host_inject.rb
Fix the argument to the telemetry forwarder command
https://datadoghq.atlassian.net/browse/INPLAT-11
We noticed we weren't getting any telemetry
=> [SSI/Onboarding] Fix the argument to the telemetry forwarder command

spec/datadog/core/utils/safe_dup_spec.rb
I spotted these typos and why not fix them :)
(Not user visible)
N/A
If CI is still green, all's cool!
=> [NO-TICKET] Minor: Fix typos in safe_dup_spec.rb

.github/labeler.yml, .github/workflows/pull-request-labeler.yml
=> Fix labeler

.circleci/images/primary/Dockerfile-2.5.9, .circleci/images/primary/Dockerfile-2.6.10, .circleci/images/primary/Dockerfile-2.7.8, .circleci/images/primary/Dockerfile-3.0.7, .circleci/images/primary/Dockerfile-3.1.6, .circleci/images/primary/Dockerfile-3.2.4, .circleci/images/primary/Dockerfile-3.3.2, .circleci/images/primary/Dockerfile-3.4.0, .circleci/images/primary/Dockerfile-jruby-9.2.21.0, .circleci/images/primary/Dockerfile-jruby-9.3.9.0, .circleci/images/primary/Dockerfile-jruby-9.4.7.0
This pinned the bundler version and fix encoding. Backported from https://github.com/DataDog/images-rb/pull/1
=> Pin bundler versions and fix encoding

.github/workflows/system-tests.yml
Remove force-executed tests and scenario from system-tests workflow
=> Post release steps for 2.5.0

spec/datadog/core/remote/transport/http_spec.rb
=> Remove duplicate require

.github/workflows/update-latest-dependency.yml
Enable auto-merge for dependencies update PR
=> Enable auto-merge for dependencies update PR

spec/datadog/core/crashtracking/component_spec.rb
This PR re-adds the spec that validates that the at_fork hook in crashtracking correctly picks up the latest instance of the component.
Since this is quite a weird corner case, I think it's important to have a spec to cover it.
None. (Not needed)
This spec was temporarily removed in #3970 with the intention of re-adding it in #3983 but we kinda forgot about it.
Check this test passes as-is, and fails if you change the `update_on_fork` call to use `self`, for instance.
=> [NO-TICKET] Re-add at_fork hook testing for crashtracking

.gitlab/scripts/vaccine.sh
Vaccine ownership transferred, change invokation.
None.
=> Use `Datadog/vaccine`

benchmarks/profiler_memory_sample_serialize.rb, ext/datadog_profiling_native_extension/collectors_cpu_and_wall_time_worker.c, ext/datadog_profiling_native_extension/collectors_stack.h, ext/datadog_profiling_native_extension/collectors_thread_context.c, ext/datadog_profiling_native_extension/heap_recorder.c, ext/datadog_profiling_native_extension/heap_recorder.h, ext/datadog_profiling_native_extension/stack_recorder.c, ext/datadog_profiling_native_extension/stack_recorder.h
This PR contains a bunch of cleanups that I was accumulating in the managed string storage branch (e.g. the next version of #3628).
I decided to extract these changes from my branch as they were becoming quite a lot. The managed string storage work already touches a lot of code, so this way we can review and merge these separately.
None.
I've broken this PR into separate commits, so it's clearer why each change is going in.
Our existing test coverage already covers these changes.
=> [PROF-9476] Profiler cleanups extracted from managed string storage branch

.github/workflows/test.yml, spec/datadog/core/crashtracking/component_spec.rb, spec/datadog/core/environment/execution_spec.rb, spec/datadog/core/telemetry/component_spec.rb, spec/datadog/tracing/contrib/mongodb/client_spec.rb, spec/datadog/tracing/contrib/sidekiq/server_internal_tracer/heartbeat_spec.rb, spec/datadog/tracing/contrib/sidekiq/server_internal_tracer/job_fetch_spec.rb, spec/datadog/tracing/contrib/sidekiq/server_internal_tracer/redis_info_spec.rb, spec/datadog/tracing/contrib/sidekiq/server_internal_tracer/scheduled_poller_spec.rb, tasks/github.rake
Setup service container to circumvent image pull rate limit.
None.
=> Use service container for tests

.github/workflows/publish.yml
Fix publish job with `bundle install`
None.
=> Fix publish job with bundle install

.github/workflows/publish.yml
Add a job to create a pull request to update `release` branch after gem publish.
None
=> Update document branch after release from `master`

.github/workflows/test.yml, tasks/github.rake
Add `JUBY_OPTS` and better job name
None.
=> Add `JUBY_OPTS` and better job name

.circleci/config.yml, .github/workflows/test.yml, tasks/github.rake
1. Uploads JUnit reports from Github Actions
2. Disable JUnit reports in CircleCI
None.
=> Upload JUnit reports

.github/workflows/cache-cleanup.yml
Generate summary report for cleaning cache
None.
=> Generate summary for cleaning cache

.github/workflows/cache-cleanup.yml
`Deletion requires authorization with the repo scope.`
None.
=> Update token permission for cleaning cache

.github/workflows/publish.yml, tasks/version.rake
After releasing a version, 
1. open/close milestone
2. open a pull request to update `release` branch
None.
=> Post release jobs

.github/workflows/check.yml, docs/DevelopmentGuide.md
Update doc for debug local linting
None.
=> Update doc for linter debug locally

docs/DevelopmentGuide.md
Fix namespace conflict, since `zizmor` is using `/app/zizmor` 
None.
=> Fix linter doc

lib/datadog/opentelemetry.rb
Fixes https://github.com/DataDog/ruby-guild/issues/225?reload=1?reload=1
no
=> chore: don't cache opentelemetry logger

.github/workflows/system-tests.yml
Return system-tests branch to `main`
This is post-release treatment
No.
None.
CI.
=> [NO-TICKET] Switch system-tests to main branch

lib/datadog/di/transport/http.rb, lib/datadog/di/transport/http/diagnostics.rb, lib/datadog/di/transport/http/input.rb
Removes unneeded requires and bogus comments from DI that were copy-pasted from elsewhere when I implemented UDS support for DI
Clean up of DI code when copying it into telemetry
None
Existing tests
=> DEBUG-3700 clean up DI transport code

.github/forced-tests-list.json
Remove force-executed tests and scenario from system-tests workflow
=> Post release steps for 2.15.0

lib/datadog/tracing/contrib/karafka/monitor.rb, spec/datadog/tracing/contrib/karafka/monitor_spec.rb
Co-authored-by: Sergey Fedorov <oni.strech@gmail.com>
=> ignore tests only

.gitlab-ci.yml
Pin a version to shared pipeline to provide consistent result.
None.
=> Pin version to shared pipeline

integration/apps/ruby/README.md
Revises setup instructions in the integration app readme file to reflect issues I ran into trying to get the app going
Attempted to test the integration app
None
N/A
=> Revise integration app readme

.github/forced-tests-list.json
Remove force-executed tests and scenario from system-tests workflow
=> Post release steps for 2.16.0

.github/workflows/publish.yml
It adds some information on how to resolve conflicts for automated docs update PR.
Trying to resolve conflicts for [this PR](https://github.com/DataDog/dd-trace-rb/pull/4662) when merging `master` into it.
None. This is internal change.
None.
-
=> Add information on resolving conflicts to automated PR for doc update

ext/libdatadog_api/macos_development.md
Specifies where to run particular commands
As a first-time dd-trace-rb user trying to set up my workspace, I required clarification on these steps.
=> Clarify instructions in libdatadog_api docs

docs/DevelopmentGuide.md
Explains how to trigger CI for community PRs
There was no documentation, so I've made one
None.
None.
Not needed.
=> Add appendix section about community PRs

.gitlab-ci.yml, .gitlab/scripts/vaccine.sh
Replace Personal Access Token usage to invoke vaccine.
None.
=> Migrate to secure token service

.github/workflows/parametric-tests.yml, .github/workflows/system-tests.yml, .github/workflows/update-system-tests.yml
1. Fix dry-run condition
2. Add `gh` instruction
3. Schedule everyday
None.
=> Fix dry-run option 

.github/workflows/update-system-tests.yml, .gitlab-ci.yml
Pin and upgrade onboarding tests
Nope.
=> Pin and upgrade onboarding tests

.github/workflows/update-system-tests.yml
Adapt `.github/workflows/update-system-tests.yml` to the new workflow
none
=> Adapt update-system-tests.yml to new workflow
